### ISSUE TITLE
Minimum android version

### ISSUE THREAD

**Issue by mostafasedaghat** [florisboard/florisboard#10]
Hi,
What is the minimum requirement android version?
my android device is moto z with android 7 but store show this message"This app is incompatible with all of your devices."

![playstore](https://user-images.githubusercontent.com/549274/90114123-86bb1900-dd67-11ea-973e-22cd2f53cab6.png)

**Comment by patrickgold** [comment]
The minimum version for FlorisBoard is API23 (Android 6.0). I've not set any device restrictions in the PlayStore, so this should not be the problem. The only thing I could imagine is that you are in a country I've not yet unlocked. I will look into it later this day.

**Comment by patrickgold** [comment]
I've updated the available country list so it includes most of the countries. Depending on Google Play this change takes effect either tomorrow or on Monday.

**Comment by patrickgold** [comment]
The updated country list is live on Google Play, could you please check if FlorisBoard is now available on your device? If it isn't I have to investigate this issue further, as I don't know what would cause the problem. Thanks!

**Comment by mostafasedaghat** [comment]
I checked and installed Floresboard on my phone.
Thanks a lot.

**Comment by patrickgold** [comment]
Perfect, thank you!
