### ISSUE TITLE
FlorisBoard doesn't copy emoji

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1000]
Bug 1000 is mine!  ^^

#### Short description
Only is buggy when clicking on FlorisBoard's copy-button.
I have everything clipboard-related on the default-settings.

#### Steps to reproduce
1. Open Whatsapp, if you use it
2. Copy 🙃-emoji using the copy&paste menu.

![Screenshot_20210606-204152_WhatsApp.jpg](https://user-images.githubusercontent.com/59611881/120936446-14596200-c708-11eb-919f-f9076f0c7a4f.jpg)

#### Environment information
- FlorisBoard Version: 0.3.13 beta3
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
> Bug 1000 is mine! ^^

:)

As for the issue itself, does it really not copy/paste the emoji or does it just not render the emoji in the suggestions bar?

**Comment by Glitchy-Tozier** [comment]
I assume it does not copy the emoji, as i can't paste it either.

That being said, it might be app-dependant. In my launcher copying works just fine.

Additionally it only seems to happen when coping an emoji that was typed using Whatsapp's "emoji-board"

![Screenshot_20210607-070133_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/120961585-6331e680-c75e-11eb-9299-032186d6c12e.jpg)

![Screenshot_20210607-070341_WhatsApp.jpg](https://user-images.githubusercontent.com/59611881/120961654-8197e200-c75e-11eb-94e9-bfb1a11a0f18.jpg)

**Comment by patrickgold** [comment]
Digging up this old topic, does this issue still occur in the latest beta? I still have WhatsApp as a backup and thus could try it out, and the emoji was always correctly copied, regardless if long-pressing and then using the system copy button or if the smartbar copy button was used.

**Comment by Glitchy-Tozier** [comment]
I, too, can't reproduce it amy longer. Should we close the issue?

Also, what did you do?

**Comment by patrickgold** [comment]
> Also, what did you do?

Nothing in particular, I suspect though fixing the copy/cut button in #1154 also fixed this issue.

**Comment by Glitchy-Tozier** [comment]
I see, nice!
