### ISSUE TITLE
Beta: Enter-popup missing

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1001]
#### Steps to reproduce
1. Long-press the enter-key
2. Nothing happens

#### Environment information
- FlorisBoard Version: 0.3.13 beta3
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! This one has been fixed in #992 and will be released to the beta channel in the next few days (Tuesday probably).
