### ISSUE TITLE
Change the Underline Key to Percent

### ISSUE THREAD

**Issue by puppykickr** [florisboard/florisboard#101]
<!--
- Describe your idea in a short but concise way.
- On the alternate keyboard (numbers and symbols) there is an underline key.  There is also an underline as an alternative on the hyphen key.
- Instead, perhaps the underline key could be a percent symbol key instead.  As it is now, a percent symbol is only available via long pressing the period buttonand sliding to it.
- I also think that the underline should be an alternative for the 'h' key, as that would make it syncronous with the alternative keyboard-  along with then leaving room for the percent sign as an alternative for the 'f' key.
-

**Comment by patrickgold** [comment]
Thanks for the suggestion. This is a rather easy fix and I will add it in the next hour or so so it can be released together with v0.3.2!

**Comment by patrickgold** [comment]
Above commit swaps the underscore and percentage sign. Will be released today with v0.3.2!
