### ISSUE TITLE
Use too mutch battery to saad..

### ISSUE THREAD

**Issue by PadawineAll** [florisboard/florisboard#1012]

**Comment by tsiflimagas** [comment]
Completing the info required in the issue submission form would help a lot. Right now there's no clue about your issue.

**Comment by Glitchy-Tozier** [comment]
What tsiflimagas said. The most important info would probably be the app-version you're using.

The more information you can provide about your setup, the better.

**Comment by PadawineAll** [comment]
V.0.3.12                                               --       Sent from       Canary                                                            On mercredi, juin 09, 2021 at 3:25 PM, Glitchy-Tozier <       ***@***.***> wrote:                                 What tsiflimagas said. The most important info would probably be the app-version you're using.       The more information you can provide about your setup, the better.       —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.       ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/florisboard/florisboard/issues/1012#issuecomment-857590404","url": "https://github.com/florisboard/florisboard/issues/1012#issuecomment-857590404","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by Glitchy-Tozier** [comment]
@patrickgold Can probably be closed. (On the phone, can't close issues)

**Comment by patrickgold** [comment]
Agree, this issue does not provide enough information for it to be useful in any way. Closing.
