### ISSUE TITLE
Add spacing between paste-icon and copied text

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1016]
I think this picture shows my reasoning pretty well: ![20210610_222350.jpg](https://user-images.githubusercontent.com/59611881/121592191-a92acb00-ca3a-11eb-93a2-c7e660f0061a.jpg)

**Comment by patrickgold** [comment]
Can confirm, the spacing is a bit messed up in the clipboard suggestion area. Will put it on my todo list, but currently am trying to resolve my backlog from the last few weeks :)
