### ISSUE TITLE
Glide typing doesn't activate on some words

### ISSUE THREAD

**Issue by shoalcreek5** [florisboard/florisboard#1023]
The glide typing threshold is too high when words start with adjacent letters on the keyboard. For example, the word "try" doesn't activate the glide typing. I can overshoot a little, then pick the word from the suggestions, but that is somewhat inconvenient. I have my glide typing distance threshold set to very short. I think if it were just a bit shorter it would work better on my phone.

Overall, this keyboard is the best alternative I've found to GBoard for general typing with glide. Thanks for your great app. Please don't let feature creep turn this into another gboard clone.

**Comment by patrickgold** [comment]
Above PR improves the threshold and fixes a unit issue (classic px vs dp problem). This means you should be able to type words like "try" now fine, at least on my testing devices it worked fine.

Will be released in 0.3.16-beta03, thanks for reporting! If you want to test this fix earlier you can try the debug artifact of above PR (installs separately), else I would appreciate your feedback on this when beta03 comes out, to ensure it is fixed for you too.
