### ISSUE TITLE
Eraser touch

•there is some latency when you want to erase words
•this touch continue to earase despite we don't touch this one. 
• version is 0.3.12
•version One Ui 3.1
•android 11


 



### ISSUE THREAD

**Issue by PadawineAll** [florisboard/florisboard#1024]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by Luensche** [comment]
Can you please fill out the bug report and not only the title?

**Comment by Glitchy-Tozier** [comment]
Hi, this issue has been reported a couple of times (for example in #883) and has largely been fixed in #966. With the next update, you shouldn't experience those lags anymore.

I'll close this report to keep the list of issues clean.
