### ISSUE TITLE
Option to remove language name from spacebar

### ISSUE THREAD

**Issue by necropolina** [florisboard/florisboard#1025]
Title says it - would be nice to be able to remove the current language from the space bar. Tried setting the space bar background/foreground colors to match, but it doesn't seem like theming the space key is working at the moment.

**Comment by phillipprado** [comment]
I second this. I tried configuring it on my own via a custom theme, but i wasn't able to do it.

**Comment by patrickgold** [comment]
Above commit adds the ability to hide the language name from the space bar. Will be available in the next beta release 0.3.14-beta10. Thanks again for the suggestion!
