### ISSUE TITLE
Cut does not seem to work in v0.3.13-beta04

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#1027]
Using the Cut button in the smartbar, then Paste in the smartbar results in text being lost. There is nothing to paste and the lost text cannot be retreived any more through system's copy/paste menu.

**Comment by Glitchy-Tozier** [comment]
Hi, could you possibly split those two bugs up into two separate issues? That would help keeping things organized.  :)

**Comment by MisterY** [comment]
Sure. I've updated this one and created #1028

**Comment by Glitchy-Tozier** [comment]
Perfect, thank you!  :)

**Comment by KLaurence** [comment]
For me, v0.3.13beta06 is affected but v0.3.12 isn't. I'm not sure which specific beta introduced the issue, though.

**Comment by Glitchy-Tozier** [comment]
@KLaurence Weird, for me the beta-cut works.
![Screenshot_20210717-160751_GitHub.jpg](https://user-images.githubusercontent.com/59611881/126039605-8e543cb6-b42b-4e92-85eb-005c49f66f22.jpg)

**Comment by KLaurence** [comment]
@Glitchy-Tozier The issue occurs for me with very long blocks of text. Can you try putting this lorem ipsum text in your notes app and copy/cut it?

<details>
<summary>Long lorem ipsum</summary>
```
Est incidunt exercitationem reprehenderit ipsam expedita. Iusto aliquid ut quas inventore. Ex consequatur voluptatem quaerat quas dolor.

Et aut nobis laudantium explicabo aut ipsam quisquam debitis. Sint repellendus consequatur dicta est molestias fugit. Voluptatem quod velit est repellendus nobis rerum tempore. Expedita saepe non perferendis porro. Enim esse dicta velit. Dolores est tempora voluptas dolorem quis commodi distinctio assumenda.

A et at et. Dolore ad accusamus consequatur nihil debitis maxime animi. Ratione molestiae assumenda dolorem facere. Quae voluptatem quaerat magni et. Dolorem esse sed aut.

Voluptatem suscipit voluptatem mollitia officiis porro. Laudantium id dolorem molestias rem aperiam eos. Provident voluptas praesentium sunt reiciendis molestiae. Sint numquam similique earum animi dolorum eos. Eveniet dolorem natus est.

Vel omnis asperiores voluptatem enim eum ea quisquam. Numquam assumenda cupiditate sequi nostrum possimus blanditiis est. Explicabo necessitatibus sit rerum dignissimos voluptatem. Nemo maiores ipsa molestiae. Et non minus omnis esse facilis error doloribus sed. Quia modi harum omnis fugit expedita.

Molestiae qui officiis earum saepe ut. Assumenda et voluptas facere. Cupiditate dolores iste accusamus quia aliquam perferendis dolores beatae. Dolorem quo sint officia omnis. Magnam veritatis sit porro. Voluptatibus quos perspiciatis quam repellendus explicabo.

Ipsam repellendus deserunt in voluptas aut eveniet tempora omnis. Dolorum aut molestiae ut dolores quo officiis. Laboriosam autem dolorem est aut voluptatibus nihil. Quo fugit vero velit mollitia et rerum. Itaque et et pariatur impedit qui expedita tenetur ex. Autem nulla eum id aperiam architecto alias.

Similique quaerat molestias voluptatem cum. Inventore cum consequuntur dicta enim nobis eligendi facilis rerum. A praesentium delectus odio vero. Adipisci eos rerum doloribus quidem voluptate dolorem minus assumenda.

Reiciendis ut saepe quidem. Placeat dolor facilis neque aut voluptas. Commodi sit minima ex. Animi rerum ratione cupiditate consequuntur. Porro molestiae dolore deleniti. Sint praesentium cumque sunt ipsam amet voluptates ducimus.

Delectus omnis in nisi laborum saepe modi. Ad non sunt est rerum est. Illum itaque quae ipsam deleniti dolorem. Voluptas et libero optio eos ipsa. Sed possimus ut voluptate. Nihil perspiciatis nisi enim.
```
</details>

**Comment by Glitchy-Tozier** [comment]
@KLaurence Still works. I tried it in two different apps.

![Screenshot_20210717-161720_Omni Notes.jpg](https://user-images.githubusercontent.com/59611881/126040002-16146e7e-d5f7-4333-9e75-e2149e73243f.jpg)

Does this occur in every app you try?

**Comment by KLaurence** [comment]
@Glitchy-Tozier I've just installed [Omni Notes](https://f-droid.org/packages/it.feio.android.omninotes.foss) and [Markor](https://f-droid.org/packages/net.gsantner.markor) (both linked for reference) and the issue does occur when using them. If you want to test it, I was testing the issue using [Quillnote](https://f-droid.org/packages/org.qosp.notes).

Alongside testing the beta v0.3.13-beta06, I also tested the stable v0.3.12. The stable version copied the full text. I'll test some time later if a fresh reinstall of the beta still has the issue.

**Comment by Glitchy-Tozier** [comment]
@KLaurence 
1. That app is reeeaally pretty, I should take a look at it!
2. Cut also works for me in this app.


Let me know how your further tests go!

**Comment by KLaurence** [comment]
I've just reinstalled the last beta versions to see which version introduces the issue. It first appears in v0.3.13-beta03 for me.

@MisterY In order to make sure that our clipboard-related issues are the same, can you reinstall the v0.3.13-beta02 and v0.3.13-beta03 versions and see if your issue occurs in each of those versions? I think you should use the long lorem ipsum text above.

**Comment by MisterY** [comment]
There's been an update in the meantime and I'm on beta06. A quick test in two different contexts confirms that the basic cut operation works now.
However, copying an article from the web into a Markor note, then Select All, Cut, Paste - results in just a couple of lines being pasted.
Select All + Cut + Paste reduces the text even further. At about 100 characters, the reduction does not appear again. 
All operations (select, cut, paste) in Markor done through the keyboard smartbar.

**Comment by Glitchy-Tozier** [comment]
>Select All + Cut + Paste reduces the text even further. At about 100 characters, the reduction does not appear again.
All operations (select, cut, paste) in Markor done through the keyboard smartbar.

I had the same problem, a couple of times in Markor and once in Github.
I think this is worthy of a completely new issue.

**Comment by KLaurence** [comment]
For my problem, I think I'll open a separate issue. I would elaborate there if I ever find more details.

**Comment by KLaurence** [comment]
I'm not sure if the original problem in this issue is also the problem that I'm experiencing. I think I'll open a separate issue for my problem, where I would elaborate if I ever find more details.

**Comment by patrickgold** [comment]
Further discussion surrounding this bug will be done in #1146, please follow along that thread! Closing this issue to keep the discussion for this bug in one thread.
