### ISSUE TITLE
Regression: Ž is missing on Serbian/Croatian keyboard long-press

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#1028]
v0.3.13-beta04

Only the capital letter is missing.

**Comment by Luensche** [comment]
Are you only missing it in metioned version or already before?

**Comment by MisterY** [comment]
Previously it was on and off - was missing, then added, and now it's gone again.

**Comment by Luensche** [comment]
What is the name in the language settings? `Serbian (QWERTZ)`?

**Comment by MisterY** [comment]
This happened in the combination of the Serbian language with the Dvorak layout.

**Comment by patrickgold** [comment]
Above PR fixes the merge bug, the Z key on Dvorak now also has a capital Ž as popup. Will be released tomorrow in beta09!
