### ISSUE TITLE
Text editing not work!

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1030]
#### Short description
In the latest beta version 3.13-beta04 the text editor doesn't show any tools it's just a transparent screen!

#### Steps to reproduce
1. Go to 'Keyboard app'
2. Click on 'Text editor icon'
3. Scroll down to 'Shows transparent screen'

https://user-images.githubusercontent.com/3160786/122246998-b24ee880-cecf-11eb-9d6c-14a35f4f1fbe.mp4

#### Environment information
- FlorisBoard Version: 3.13-beta04
- Install Source: Github
- Device: OnePlus Nord
- Android: 11 OOS**

**Comment by tsiflimagas** [comment]
This one was "broken" at some point (when improving keyboard rendering I think) and is scheduled for 0.5.0 milestone, iirc.

**Comment by GoRaN909** [comment]
> This one was knowingly "broken" at some point (when improving keyboard rendering I think) and is scheduled for 0.5.0 milestone, iirc.

But in the older versions the app doesn't have this bug 😕 this bug was appeared on 3.12 version and newer!

**Comment by Glitchy-Tozier** [comment]
@GoRaN909 Yup, that keyboard is broken. I think a big change was made and it'll take a while until this view is re-implemented. (in ~0.5.0)

I think we can close this issue. Or at least rename it to "Reimplement Selection Keyboard" or something similar.

**Comment by GoRaN909** [comment]
> @GoRaN909 Yup, that keyboard is broken. I think a big change was made and it'll take a while until this view is re-implemented. (in ~0.5.0)
> 
> I think we can close this issue. Or at least rename it to "Reimplement Selection Keyboard" or something similar.

Ohh no that's not good news 0.5.0 is toooooo far :( 

anyway thanks for your info i will close this issuses right now :)

**Comment by Glitchy-Tozier** [comment]
(By the way, for some reason 5.0 means that it'll get fixed in 0.4.x. Basically, it'll be one of the steps *towards* 5.0)

**Comment by Glitchy-Tozier** [comment]
> (By the way, for some reason 5.0 means that it'll get fixed in 0.4.x. Basically, it'll be one of the steps *towards* 5.0)

@patrickgold I've wondered about that for quite some time now. Is that a common convention for naming things? It seems counter-intuitive to me, seeing as most of the items under the **4.0**-headline (in the readme) are done but we're in 0.3.xx.

**Comment by patrickgold** [comment]
@Glitchy-Tozier  I agree the naming scheme is a bit confusing but I don't really know how to make a better one and there isn't the single best way to do this sadly, every project uses some other convention.

A convention I've seen quite often though is this:

Let's say we have a new milestone, v0.1.0, they have a list of things they want to be done in this release.
- So they begin with development and make alpha releases: v0.1.0-alpha01, v0.1.0-alpha02, etc. This can go really far such as 20-30 alpha versions. In this state, interested people can see the early stages of the milestone's planned features, but everything is buggy and may break, some things are completely missing.
- Then they do beta releases, same naming scheme as the alpha releases, features are still modified and also added, but the app is much more usable than the alpha .
- After the last beta, every feature is finalized in terms of functionality, also APIs are stable, but they still want to see if some features contain bugs, so they do release candidates. (v0.1.0-rc01, ...)
- After the last release candidate, they do a stable track release: v0.1.0

Sub versions like v0.1.1, v0.1.2 etc on the stable track are possible but are only bug fixes, minor patches like fixing typos or updating translations. Maybe some minor QOL updates or some fine adjustments are also done, but nothing big.

The next big update in terms of functionality is v0.2.0. The development of this may either begin in parallel to v0.1.1, v0.1.2 etc. or is done after the last stable track patch and goes through the same circle as v0.1.0.

This development cycle would make much much more sense in terms of naming, as the big cool updates are v0.1.0, v0.2.0, v0.3.0 etc.

Another idea could be to rename the v0.4.0 milestone to v0.3.x, as this would indicate any v0.3 release may add this feature.

The above mentioned cycle means that stable releases are much more spaced out but also guaranteed to be much more stable than my current stable releases. I can switch to this scheme after the v0.4.0 release, this wouldn't even be a problem IMO. The namespace id `dev.patrickgold.florisboard.beta` would be used for all non-stable versions (alpha, beta, rc), as I cannot change this anymore (I could technically but the effort to change the GPlay, Izzy repo entry etc is just too much effort). The namespace `dev.patrickgold.florisboard` is all stable track releases.

What would you think of this idea? I think it would definitely clear up some confusion around the naming and also make sense to people already used to this alpha/beta/rc release cycle.

**Comment by Glitchy-Tozier** [comment]
> What would you think of this idea? I think it would definitely clear up some confusion around the naming and also make sense to people already used to this alpha/beta/rc release cycle.

Can your idea be summarized as "Instead of counting up the third number, we'll count up the second number and reserve the third number for really small changes"?

> The above mentioned cycle means that stable releases are much more spaced out but also guaranteed to be much more stable than my current stable releases. I can switch to this scheme after the v0.4.0 release, this wouldn't even be a problem IMO. The namespace id dev.patrickgold.florisboard.beta would be used for all non-stable versions (alpha, beta, rc), as I cannot change this anymore (I could technically but the effort to change the GPlay, Izzy repo entry etc is just too much effort). The namespace dev.patrickgold.florisboard is all stable track releases.

This stuff is called Flavours, correct? Is that how you manage to get beta AND normal versions installed on the same device?

> Another idea could be to rename the v0.4.0 milestone to v0.3.x, as this would indicate any v0.3 release may add this feature.

This is what i originally meant. This is the naming that would make the most sense to me, personally.

**Comment by patrickgold** [comment]
> Can your idea be summarized as "Instead of counting up the third number, we'll count up the second number and reserve the third number for really small changes"?

Yup!

> This stuff is called Flavours, correct? Is that how you manage to get beta AND normal versions installed on the same device?

Both "build types" and "flavors" allow me to create different APKs with different namespaces, so they can be installed in parallel. (Android only allows one APK per namespace). Flavors are mostly used when the features must differ between different APKs (like a free and paid version of the app, etc.), build types are more often used for creating APKs with different version and namespace configuration when doing alpha/beta releases.

In the current FlorisBoard configuration the "release" build type just uses the base namespace, the "beta" build type uses the base namespace and appends ".beta" to it.

> This is what i originally meant. This is the naming that would make the most sense to me, personally.

I could rename the v0.4.0 milestone now and for all version further ahead I will see if I change my development/release cycle.

**Comment by Glitchy-Tozier** [comment]
> Yup!

Both systems are okay imo, but I agree that counting up the middle-number for big releases probably makes more sense.

> I could rename the v0.4.0 milestone now and for all version further ahead I will see if I change my development/release cycle.

Sounds good! So you'll be renaming it to v0.3.0, correct?

**Comment by patrickgold** [comment]
> Sounds good! So you'll be renaming it to v0.3.0, correct?

v0.3.x because v0.3.0 would make no sense as we are already at v0.3.13
