### ISSUE TITLE
How to have borderless keys for app adapted themes?

### ISSUE THREAD

**Issue by TheLoving** [florisboard/florisboard#1034]
**Theme Mode**: Follow system

**Day Theme**:-

**Selected theme**: Floris Day Borderless
**Adapt colors to app**: True

**Night Theme**:-

**Selected theme**: Floris Night Borderless
**Adapt colors to app**: True

Whenever I open an app I see keys with borders which I dont want. How can I have keyboard with borderless keys i.e., adapted to app color.

![photo_2021-06-19_12-03-50](https://user-images.githubusercontent.com/81813176/122633652-4e0e6d80-d0f7-11eb-864b-20e6e5f51497.jpg)

I did try making a seperate theme with border switch set to false and keys background color to keyboard background.

**Comment by patrickgold** [comment]
This is currently no way to achieve this, will add this to the list of proposed features!

**Comment by TheLoving** [comment]
I thought it is already implemented. In #118 I saw keys without borders and tried the same way but unable to get required output.

**Comment by patrickgold** [comment]
> I thought it is already implemented. In #118 I saw keys without borders and tried the same way but unable to get required output.

It is possible for non-adaptive theme and this is implemented for quite some time now, though adaptive themes don't use the "showBorder" property and just override the colors.
