### ISSUE TITLE
keyword suggestions not working

### ISSUE THREAD

**Issue by p1238** [florisboard/florisboard#1038]
keyword suggestions not working when typing any and not display any keyword suggestions in keyboard.

#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by Glitchy-Tozier** [comment]
Please could you fill out the emvironment information? That would help test your issue.

**Comment by GoRaN909** [comment]
Yeah you right it's not showing the suggested words in the smartbar that happned in latest beta version

**Comment by TheLoving** [comment]
This is a known issue. Check #941

**Comment by patrickgold** [comment]
Thanks for your bug report! Like I said in #941, suggestions are currently not implemented. The active [spelling](https://github.com/florisboard/florisboard/tree/spelling) branch is finalizing for a first experimental preview. Then I will have to fix and improve spell checking features (and bugs reported by early testers). After this process I will then work towards bringing suggestions back (but implemented in C++). Sadly development currently isn't as fast as I wish, but I am trying my best to implement new cool stuff into FlorisBoard. Hope u understand what I am currently working on :)

Closing this issue as a duplicate.
