### ISSUE TITLE
Vibrate on every rapid-fire deletion

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1041]
Extracted from #637.

Add a vibration every time a letter/word is deleted when holding down the delete key.

(Currently it's not working. Here's my settings)
![Screenshot_20210627-115949_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/123540503-9c4aee80-d73f-11eb-9db6-855f8820e8b4.jpg)

**Comment by patrickgold** [comment]
Above PR adds a separate toggle to control repeated action vibrations, thus allowing for such feature (it was existent before too, just did not trigger sometimes and had no separate UI toggle).
