### ISSUE TITLE
Wiping clipboard after a specific period of time

### ISSUE THREAD

**Issue by whiteeagle3** [florisboard/florisboard#1042]
clipboard timeout. If the user copy something to the clipboard, the user has the option to control for the storage duration in the clipboard, so that the clipboard got wiped automatically after a specific period of time.

**Comment by GoRaN909** [comment]
This feature is already availavle in Clipboard settings you need to Enable clipboard history then below of  clipboard history you see two option ( Clean old item and Limit history size ) that's all :)

**Comment by tsiflimagas** [comment]
As mentioned, this is already implemented. Closing thus.
