### ISSUE TITLE
Turkish only characters: Ğ and her buddy İ

### ISSUE THREAD

**Issue by kc4ca** [florisboard/florisboard#1045]
Turkish has capitalized I with dot on it "İ" letter. 
i, İ, ı, I.
on florisboard capitalized İ shows as I like in english. nothing wrong with Ğ letter I just put on title to take attention lol

**Comment by kc4ca** [comment]
![Screenshot_20210629-112654_FlorisBoard](https://user-images.githubusercontent.com/39414668/123764890-e3ff8080-d8cd-11eb-89f7-e13adf65e2e3.jpg)
![Screenshot_20210629-112723_Messages](https://user-images.githubusercontent.com/39414668/123764894-e5c94400-d8cd-11eb-8fa2-9c104040ea78.jpg)

**Comment by kc4ca** [comment]
![image](https://user-images.githubusercontent.com/39414668/123765103-14471f00-d8ce-11eb-803d-45d373936704.png)

**Comment by patrickgold** [comment]
Thanks for your bug report!

This bug is a classic one and has been fixed before the layout rework (but since then been re-introduced). This time (above linked PR) I am using fixed selectors so the correct `I` is used in the Turkish layouts. Will be available in v0.3.13-beta07.
