### ISSUE TITLE
Symbol/number hints are truncated on "Borderless" theme

### ISSUE THREAD

**Issue by asquartz** [florisboard/florisboard#1049]
I've just gone from 0.3.12 to 0.3.13-beta04, and find that the symbol and number hints are being cut off at the top and not displayed properly on the "Borderless" theme (either light or dark).  See attached screenshot. 

I've tried changing the height to "Tall" and messing with the spacing controls - but these don't change the issue.
The non-borderless styles seem OK.

Android: 9
Phone: Sony Xperia XA2 (1080x1920, default DPI settings)
![Screenshot_20210630-154759](https://user-images.githubusercontent.com/34890493/123983772-08398b00-d9bc-11eb-9edf-2b9a63eca653.png)

**Comment by patrickgold** [comment]
Thanks for your bug report! I just tested this one out and it indeed is cut off, will provide a patch for this soon.

**Comment by patrickgold** [comment]
Fixed in above PR. Will be available in beta05.
