### ISSUE TITLE
Typing is quite "sticky"

### ISSUE THREAD

**Issue by abh-oss01** [florisboard/florisboard#105]
1) The keyboard, and typing using it in general feels very sticky, wobbly, and not so smooth and suitable for typing longer texts.

2) The input has a micro delay of just short of a second, I mean, the time after pressing the letter or a symbol on the keyboard, till the letter/symbol appears on the screen, is just short of a second (Little lag).

**Environment information**
- FlorisBoard Version: 0.3.1
- Install Source: F-Droid 
- Device: rmx 2061
- Android version, ROM: 10, Stock

**Steps to reproduce**
1. Type using the keyboard
2. See/feel the listed problems

**Comment by patrickgold** [comment]
Hmm yeah I will have to investigate this, as normally the reaction time of key presses is really fast. I will add it to my todo list!

**Comment by abh-oss01** [comment]
It's not quite comfortable for typing longer texts.
My device is quite a recent one, plays 4K videos without a sweat, so rendering a small keyboard shouldn't be a problem for it.
No idea why it happens though.
Thanks for the a2a.

**Comment by RickyM7** [comment]
@patrickgold  I also feel it on my phone but I think it's because of the popups that sometimes has a micro delay. Maybe making popups disappear faster can solve that.

**Comment by yashx** [comment]
The likely reason @abh-oss01 feel this is because the text is not written when the key is pressed but when it is [released](https://github.com/florisboard/florisboard/blob/1e690018d7a0819ffb2c4055df8ad48044c68ab3/app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt#L309)

**Comment by patrickgold** [comment]
Hmm I am currently trying to improve the logic to decrease any input lag, will push via a PR as soon as I have any noticeable results.

**Comment by RickyM7** [comment]
@patrickgold Switching between hints of a key also has a slight delay. You can see by gif but it is much more perceptive when using the app.
![test](https://user-images.githubusercontent.com/24703825/103179068-1a990780-4867-11eb-926a-eb60606cd0a2.gif)

**Comment by patrickgold** [comment]
@RickyM7 Yeah that's because there is quite a lot of calculation to do in examinating which popup character should be selected and if the touch pointer is out of bounds, etc. Also PopupWindow isn't exactly the single most responsive component in Android, but it does a lot of work for actually drawing over the keyboard, so I am still using it. I can look into improving this bit, maybe try to avoid list operations as often as possible, and other similar things.

**Comment by abh-oss01** [comment]
@RickyM7 where did you get the debug apk? looks like you built it...

**Comment by RickyM7** [comment]
@abh-oss01 https://github.com/florisboard/florisboard/actions

**Comment by abh-oss01** [comment]
@patrickgold Great work, there has definitely been a lot of improvement in the performance now (v0.3.2), I don't notice any significant lag, or stickiness while typing now.

Thank you so much.

**Comment by RickyM7** [comment]
@abh-oss01 The Popup delay option already exists. It is the last option of the "Keyboard" tab.

**Comment by abh-oss01** [comment]
@RickyM7 that is long press delay, not key press delay.

**Comment by patrickgold** [comment]
> Is there a way to change theme, other than the current default in which the keys are sepatated blocks?

@abh-oss01 I am aware that this is currently not possible in FlorisBoard, but I will definitely add a borderless theme option. See #87 for this.

**Comment by RickyM7** [comment]
@abh-oss01 There are several options for customizing keyboard colors in the "Theme" tab. More customization options may be added later, I think.

**Comment by tsiflimagas** [comment]
Since this was where the performance topic was discussed, I'm reporting here. If it's not comfortable or appropriate though, let me know to open a new issue.

On v0.3.2 performance feels great indeed (though in my case I was satisfied earlier too), but it seems that cpu usage got too high. I first noticed it by some extra heat generated on the back of my phone (not much really), and then I ran "top" in a terminal to see what was going on. Indeed, FlorisBoard was running at 40%-50% on the cpu, which is unusually high. I guess that's to be looked into. Nevertheless, great job, I love it!

**Comment by patrickgold** [comment]
@tsiflimagas Thanks for reporting this! Yeah I definitely have to do some research what could cause the high CPU usage on some devices. Is the high CPU usage on your phone only while typing or also while FlorisBoard is idling? This is important to know for me to know where to start looking into this problem.

**Comment by tsiflimagas** [comment]
@patrickgold nope, when I hide the keyboard, its cpu usage goes to zero.

**Comment by lawson85** [comment]
Try turning off animations in developer options and use Universal Android Debloater and make the keyboard exempt from battery savers and task killers

**Comment by patrickgold** [comment]
Version 0.3.8 which will release later this evening contains a lot of bug fixes in the core editor instance and which also improves the responsiveness of the UI. When the new version arrives, could you give me feedback if the described bug is now fixed? This would be very helpful, thanks in advance!

**Comment by RickyM7** [comment]
I just tested v0.3.8 and everything is working great. Bugs related to slowness in the app and popups no longer happen after the app loads completely (if the app was stopped and you try to use it as soon as you open it, the popups will behave as before, but this only lasts a few seconds).

- Device: Redmi Note 4 (MIUI 11 - Android 7.0)

**Comment by lawson85** [comment]
I'm looking forward to the update. It hasn't appeared for me yet

**Comment by RickyM7** [comment]
@lawson85 You can download through GitHub if you want (I think it will take a long time to get into the F-Droid, but should soon arrive in the Play Store as updates happen quickly there).

**Comment by patrickgold** [comment]
> I just tested v0.3.8 and everything is working great. Bugs related to slowness in the app and popups no longer happen after the app loads completely

That's great to hear, thanks for giving feedback!

> I'm looking forward to the update. It hasn't appeared for me yet

Except when installing via GitHub, v0.3.8 is not yet available for download, as this version is just an hour old. When using GPlay, the update should arrive on Tuesday, when using F-Droid I honestly don't know, can range from just a few days to 2 weeks in the worst case, depending on the processing speed of their servers.

**Comment by abh-oss01** [comment]
I suggest using Izzy's repo instead of official F-Droid's, for publishing app releases.
It's much faster, and has stringent security checks using virustotal.

And the dev version works nicely now, I don't seem to see any popup lag or the stickiness anymore.
Thank you so much Patrick!

**Comment by patrickgold** [comment]
> I suggest using Izzy's repo instead of official F-Droid's, for publishing app releases.

I may use it for the planned beta track of FlorisBoard (beta track means that I make intermediate "beta" releases between versions like v0.3.8 and v0.3.9 to get features out faster to users who always like to try out the latest and greatest).

> And the dev version works nicely now, I don't seem to see any popup lag or the stickiness anymore.

As the popup lag is not existent anymore and most of the UI lag is now gone, is the issue now resolved for you? If so, you can close this issue.

>  Thank you so much Patrick!

Thank you so much for trying out new versions and giving feedback, I highly appreciate it! :)

**Comment by abh-oss01** [comment]
Ok, closing it, thanks for the support.
