### ISSUE TITLE
Disable autofill

### ISSUE THREAD

**Issue by islam2hamy** [florisboard/florisboard#1050]
How can i disable autofill in websites
Miui 11.0.2
Android 7.1.2
FlorisBoard 0.3.12

**Comment by Glitchy-Tozier** [comment]
Florisboard doesn't autofill, meaning that it's either the browser you're using or some other app.

**Comment by islam2hamy** [comment]
Ok , thank you

**Comment by Glitchy-Tozier** [comment]
Great, good luck fixing the autofill, I'll close this issue to keep the list clean :)

**Comment by lawson85** [comment]
Settings\Google\Auto-fill

**Comment by islam2hamy** [comment]
> Settings\Google\Auto-fill

Not in android 7
Or may be the miui 11
