### ISSUE TITLE
florisboard development

### ISSUE THREAD

**Issue by heberjeur** [florisboard/florisboard#1051]
I have installed this soft as my main keyboard, and I'm still waiting for v4, the last version was on 10 may, the development was stopped 23 days ago, is there any problem?

**Comment by Glitchy-Tozier** [comment]
Hi, see #1043

Regarding versions: The release of 0.4.0 will probably take a while, but 0.3.XX releases should arrive way sooner.

**Comment by patrickgold** [comment]
The spelling implementation was way more complicated than I anticipated, see #1052. But now it finally works and a new beta release is in reach again! (yay)
