### ISSUE TITLE
Number pad, extra symbols, and ABC button theming

### ISSUE THREAD

**Issue by necropolina** [florisboard/florisboard#1058]
Not sure if these special key identifiers just aren't in the theming docs or if they're not supported, but i'd like to theme the number pad, extra symbols, and ABC/main keyboard buttons that are visible from the symbols layouts.

**Comment by patrickgold** [comment]
Thanks for your suggestion! This is actually currently not directly possible in FlorisBoard's theme engine but I plan to add such functionality when I modify the theme engine again. Will add it to that todo list.

**Comment by patrickgold** [comment]
In the latest release 0.3.14-beta09 it is possible to style any button you can see and interact with on the keyboard, so I will close this issue as fixed.
