### ISSUE TITLE
Incognito mode

### ISSUE THREAD

**Issue by abh-oss01** [florisboard/florisboard#106]
Please add an option to force use the "incognito mode" everywhere.

As of now, (v0.3.1), there is no such incognito mode to use.

**Comment by patrickgold** [comment]
Thanks for your suggestion!

Its true, FlorisBoard does in its current state not have an explicit incognito mode, but as there are no features with temporarily save data (except clipboard suggestions), FlorisBoard is kinda always in incognito mode. But this is definitely useful when composing suggestions and next word suggestions are added, so I will definitely add it to my todo list!

**Comment by patrickgold** [comment]
@abh-oss01 PR #110 adds a basic implementation of a private mode. Could you please give feedback if this is what you imagined with this proposal and where I can improve it? Note, that the mode itself is almost redundant as of now, as FlorisBoard itself is designed to be very private, but will come in handy when the composing suggestions are added. Thank you in advance!
