### ISSUE TITLE
Capital words not showing in the smartbar word suggestions

### ISSUE THREAD

**Issue by yesNOmaybe69420pogchamp69** [florisboard/florisboard#1062]
The smartbar doesnt suggest capital words, even when the word we typed starts with a capital letter.
![](https://bun.filedit.ch/IgieEnlJYcGXQCBKRWw.jpg)

**Comment by patrickgold** [comment]
Thanks for your bug report! This is a very well known issue, see #441. Note that suggestions will see a re-implementation soon, so this issue will then also be fixed.
