### ISSUE TITLE
Fix German grammar mistake

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1070]
Not quite sure what that option does, which is why i have no suggestion on what would be a better alternative.

![20210714_213027.jpg](https://user-images.githubusercontent.com/59611881/125681632-ea799522-a994-48d5-9d34-30872ef96283.jpg)
nix deutsch

**Comment by webberian** [comment]
The option you highlighted is the time after which the glide "trails" (i.e. patterns) fade and disappear.

![Screenshot_20210719-233827_FlorisBoard](https://user-images.githubusercontent.com/15054744/126231281-c486ae67-1fe8-44ee-9dd5-a0809a6fbc45.png)

**Comment by webberian** [comment]
The option you highlighted is the time after which the glide "trails" (i.e. patterns) fade and disappear.

![Screenshot_20210719-233827_FlorisBoard_1](https://user-images.githubusercontent.com/15054744/126231774-f1eee636-d33f-45ff-8d52-ae362d172037.png)

**Comment by Glitchy-Tozier** [comment]
Thank you!

Why do you have an extra "length" property? 🤔

**Comment by webberian** [comment]
Maybe I have a newer version? I'm using 0.3.12.

**Comment by Glitchy-Tozier** [comment]
Ah, i use a recent beta version. Apparently this option has been removed.

**Comment by patrickgold** [comment]
Thanks for spotting this!

I looked up the Crowdin translation and apparently someone has changed this to "Zeit bis zum Ausblenden der Spur". Would this translation be ok or is there a better German alternative?

**Comment by patrickgold** [comment]
I have also discovered quite a few additional German spelling mistakes while having a quick look, seems like I have to do a full sweep across German to see what else I can find. #`Händy` xD

**Comment by Glitchy-Tozier** [comment]
> # Händy
Löl  xD

> I looked up the Crowdin translation and apparently someone else has changed this to "Zeit bis zum Ausblenden der Spur". Would this translation be ok or is there a better German alternative?

It seems kind of long.
What do you think about "Ausblendzeit der Bewegungsspur"?

Maybe it could even be shortened to "Ausblendzeit der Spur", as there is no other trail which we could be talking about.

**Comment by patrickgold** [comment]
> "Ausblendzeit der Spur"

I really like this one, gonna change the string on Crowdin:

![image](https://user-images.githubusercontent.com/19412843/129456162-48a6a811-530e-4ef1-b101-ffbd673761a8.png)

With this I also see this issue as fixed and implemented, so I will close this issue. Thanks again for spotting!

**Comment by Glitchy-Tozier** [comment]
Not sure how to say this in English, so here we go: Hat dieser Screenshot einen gewissen Aufforderungs-Charakter? :upside_down_face: 

I really should eventually check out Crowdin :sweat_smile:.
Anyway, thanks for the fix!

**Comment by patrickgold** [comment]
> Not sure how to say this in English, so here we go: Hat dieser Screenshot einen gewissen Aufforderungs-Charakter? upside_down_face

Just wanted to show how easy it is to correct a string :upside_down_face:

**Comment by Glitchy-Tozier** [comment]
> Just wanted to show how easy it is to correct a string 🙃

Understood 🙃
