### ISSUE TITLE
Add shortcut to settings in choose-keyboard-popup

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1071]
Samsung keyboard has some fun shortcut in the choose-keyboard-pop-up. No idea whether other keyboards can also do this or whether it's a privilege Samsung has reserved for itself, but it seems handy.  :)

The pop-up is triggered by clicking here:
![Screenshot_20210715-081230_GitHub.jpg](https://user-images.githubusercontent.com/59611881/125737910-d6148e63-834e-420a-9f07-46394f44b1bf.jpg)

![Screenshot_20210715-080706_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/125737736-67b4299f-3e9f-45f6-b844-d30a8ff5311f.jpg)

**Comment by patrickgold** [comment]
Thanks for suggesting this!

Unfortunately this is a privilege only the Samsung keyboard has on Samsung ROMs, not even Gboard can do this. As much as I like the idea this is up to Samsung and their decisions if they respect the settings definition of other apps or not.
