### ISSUE TITLE
thank you for proposing your keyboard 

### ISSUE THREAD

**Issue by franco27** [florisboard/florisboard#1073]
Hello. 
All my encouragement for your keyboard. I just discovered your keyboard.

 It's a shame that while writing there are no word suggestions. 
And also the possibility of using the microphone or the voice recognition to write.

thank you for your work

**Comment by Glitchy-Tozier** [comment]
Hi there!

> It's a shame that while writing there are no word suggestions.

That currently is being implemented. They should be available on the next update :)

> And also the possibility of using the microphone or the voice recognition to write.

This is also planned, but it'll take quite a bit longer.

**Comment by franco27** [comment]
Thank you for your response.
  I am with the current Beta version.
  I am French and I tried to make the word suggestions work while writing. (To get French words)

  When I write in French, I see words appear in the suggestion bar. But the words don't match.
For example, when I write the first 2 or 3 letters of a word, the suggested words do not contain the same first letters.

  I read that this feature is experimental. I guess for the moment we can test only with English words.

And when I install a French dictionary, in the section "Spellcheck settings", after that I have no more words suggested in the bar.

Maybe you already know. I wanted to inform you. 
Thank you.

**Comment by Glitchy-Tozier** [comment]
> For example, when I write the first 2 or 3 letters of a word, the suggested words do not contain the same first letters.

That is a little weird, but a lot of suggestions are a little broken at the moment, it's best to just wait.  :)

> And when I install a French dictionary, in the section "Spellcheck settings", after that I have no more words suggested in the bar.

Yup, that is a by-product of the experimental spell-checker. I'll be fixed soon (probably within the next weeks but i can't say for sure).

Thank you for informing us, it helps a lot!

**Comment by Glitchy-Tozier** [comment]
1. The speech-to-text recognition already was proposed in #195
2. I'll close this issue for now. Should any new questions/issues come up, just comment here or create a new issue! :)
