### ISSUE TITLE
[Feature Request] Smartbar Display Toggle

### ISSUE THREAD

**Issue by Mokura** [florisboard/florisboard#1075]
As per title - I have relatively big hands so occasionally I hamhand into (example) the paste key on the smartbar while typing.  Would it be possible to add a display toggle option somewhere?  The comma and Enter longpress menus would be good, and maybe on-keyboard gestures as well.

**Comment by patrickgold** [comment]
See #1794, with this proposal I added a Smartbar visibility toggle as a new swipe action. Note that I will not add it to the default popups of any key, but when custom layouts are a thing in the future you could add a key with the code `-228` to the popups, this would toggle the Smartbar.
