### ISSUE TITLE
Gripes with Borderless Theme Creation

### ISSUE THREAD

**Issue by moriel5** [florisboard/florisboard#1077]
As I had thought, my custom GBoard theme still needed work.

However, this time around, I am starting fresh on a ~~different device~~ (turns out that it is the same device, however this is a fresh start) , and I am having issues, such as FlorisBoard not obeying the spacebar color, or font size being inconsistent between key border toggle (used for comparison, the plan is to make a borderless theme that 99% mimics GBoard (sans a few shading differences)).

Here is a list of issues I am facing:
1. Spacebar is set to have a background, like GBoard's, however FlorisBoard ignores it (checked contrasting colors as well).
2. ~~Keys font size is slightly different when key borders are disabled, leading to the characters being cut off from the top~~ (it turns out that this was a bug with v0.3.13-beta04, beta06 fixes it, however is too heavy in my opinion).
3. I am unable to figure out how to change the look of the smartbar, i.e. spacing between the buttons, and removing borders (the circles).
4. I am unable to figure out how to enable borders for clipboard entries, without enabling borders for the standard keyboard view.
5. I am unable to figure out how to change the width of the key popups.
6. I am unable to figure out how to change the size of the Enter key.

Plus, it would be nice to understand how to change the key border corner radius, for more "squarish" themes.   

Aside from these pain points, I believe that my theme is almost ready, and once it will, I intend to share it.

**Comment by Glitchy-Tozier** [comment]
> Keys font size is slightly different when key borders are disabled, leading to the characters being cut off from the top.

This has been fixed recently, should be gone in the next update :)

>3. I am unable to figure out how to change the look of the smartbar, i.e. spacing between the buttons, and removing borders (the circles).
4. I am unable to figure out how to enable borders for clipboard entries, without enabling borders for the standard keyboard view.
5. I am unable to figure out how to change the width of the key popups.

>Plus, it would be nice to understand how to change the key border corner radius, for more "squarish" themes.

As far as I know, those aren't costomizable at the moment.

> Aside from these pain points, I believe that my theme is almost ready, and once it will, I intend to share it.

Looking forward to seeing what it looks like!

**Comment by moriel5** [comment]
@Glitchy-Tozier Thanks, that is understandable.

Regarding the theme, it is WIP, but since I cannot yet advance any further, I shall upload in a few minutes.

**Comment by Glitchy-Tozier** [comment]
> As far as I know, those aren't costomizable at the moment.

If you have a good reasoning why those features should be available, you could add a feature request for each of then.

**Comment by moriel5** [comment]
Thanks, when I have the time, I'll look at whether there are already feature requests for these, and whether some of these are already planned.

And here is the theme, which I first needed to copy over to my laptop (GitHub doesn't allow uploading JSONs for some reason, so just rename the file):
[GBoard_Day_Borderless.txt](https://github.com/florisboard/florisboard/files/6838720/GBoard_Day_Borderless.txt)

It was created by modifying the stock Florisboard Day Borderless theme to be in line with the GBoard Day theme, then tweaking it to actually make it look more like GBoard (like replacing the orange highlight with blue), and finally minor adjustments in accordance with my tastes (like making the background a bit more grey than GBoard's background, while remaining lighter than the stock FlorisBoard's background color).

**Comment by Glitchy-Tozier** [comment]
>GBoard_Day_Borderless.txt

 I'll check it out, ty

**Comment by Glitchy-Tozier** [comment]
For now I'll close this issue. Should you have any more questions or feature-requests, just ask here or post your ideas as new issues!  :)

**Comment by moriel5** [comment]
No problem, I'll do that once I have the time.
Thanks.

**Comment by drannex42** [comment]
Had there been any updates to remove the borders on smartbar buttons?

**Comment by moriel5** [comment]
@drannex42, I haven't touched my theme since my previous past, since I am first waiting for the necessary underlying support before I can improve it any further.

There may be things that can technically be improved at this stage, however I lack the knowledge to even know what they are.

**Comment by patrickgold** [comment]
> Had there been any updates to remove the borders on smartbar buttons?

Internally - yes, there's been a lot of progress with the [internal new theme engine](https://github.com/florisboard/florisboard/tree/master/app/src/main/java/dev/patrickgold/florisboard/snygg). This theme engine allows a lot to customize, including borders.

In terms of actual usage and a UI for it - no, not yet. My current effort is to get the new preferences up and running, but I am working on the new theme engine slowly but surely.

**Comment by drannex42** [comment]
That's great to hear (current workaround for those looking for similar — just color the smart bar media buttons to be the same color as the smart bar itself). 

This is truly a great keyboard, and am looking forward to the future development on it! Thanks for all the work you have put into this!

On November 3, 2021 5:20:10 PM CDT, Patrick Goldinger ***@***.***> wrote:
>> Had there been any updates to remove the borders on smartbar buttons?
>
>Internally - yes, there's been a lot of progress with the [internal new theme engine](https://github.com/florisboard/florisboard/tree/master/app/src/main/java/dev/patrickgold/florisboard/snygg). This theme engine allows a lot to customize, including borders.
>
>In terms of actual usage and a UI for it - no, not yet. My current effort is to get the new preferences up and running, but I am working on the new theme engine slowly but surely.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/florisboard/florisboard/issues/1077#issuecomment-960236861
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
