### ISSUE TITLE
Crash deletes characters

### ISSUE THREAD

**Issue by WikiBayer** [florisboard/florisboard#1078]
Sometimes the keyboard deletes characters and does not stop until you restart the keyboard.
I have android 11 (crdroid)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

Could you please fully fill in the bug-report-template? This would help a lot in fixing your issue.

**Comment by Glitchy-Tozier** [comment]
This is a duplicate of bug #986, closing it as such.
Should you have any further information, please mention it there!
