### ISSUE TITLE
Add copy/paste options to smartbar

### ISSUE THREAD

**Issue by CristianKerr** [florisboard/florisboard#1080]
Hi, 
when I select some text, in top bar I have following (copy, paste, etc)
![IMG_20210718_143638](https://user-images.githubusercontent.com/79404036/126067625-d358fd7c-1965-4007-897c-1f7995255dc7.jpg)
I would like to have an option, to have this menu available even if I wont select some text (especially for pasting).
Could you add one more category to the smartbar
![IMG_20210718_144320](https://user-images.githubusercontent.com/79404036/126067650-0e3b4611-c3a6-4956-b547-579ec00a0508.jpg)
that would lead to this copy/paste bar?
Thank you

**Comment by Glitchy-Tozier** [comment]
Maybe i misunderstood you, but isn't the default behaviour to always show the copy&paste-bar? (= what you want)

**Comment by CristianKerr** [comment]
It shows only when I select a word or more words. But I want to have a possibility to invoke this bar without needing to select anything. The main reason is, when I want to paste something, in the middle of the text I typically move the cursor with spacebar gesture and then I wanna paste, but If I pasted using long press I risk missaligning the cursor again.

**Comment by Glitchy-Tozier** [comment]
Did you enable word-suggestions?
If they're turned off, the bar is there.

![Screenshot_20210718-192736_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/126076633-7f62c7f1-259d-4209-9956-ad2eb69ffbfa.jpg)

Or is your request to have a paste-option EVEN THOUGH you usually use a different bar?

**Comment by CristianKerr** [comment]
Hi yes I have the word-suggestions, didn't know it's possible to have it permanently instead of that. But suggestions are very useful too. Maybe you can have two bars like Chrooma keyboard, topmost for suggestions and the one under it has (rotatable in one row with side swipe) copy/paste tools, number row and selected symbols row (which I fill with emojis)
![IMG_20210718_195036](https://user-images.githubusercontent.com/79404036/126077303-6011cabc-e2e8-4864-86bb-91d2ce539ebf.jpg)
![IMG_20210718_195128](https://user-images.githubusercontent.com/79404036/126077308-324e6bb7-c4e1-4a7e-b626-bc4e16b99112.jpg)

**Comment by Glitchy-Tozier** [comment]
Jup, that has been proposed a couple of times (see #870 and #612 for examples) and it will eventually be implemented.  :)

Mind if we close this issue to keep the list free of duplicates?

**Comment by CristianKerr** [comment]
Hi, thanks, I was actually searching for it, but maybe I just can't search :D 
Sure, close the issue and thanks again :)
