### ISSUE TITLE
Cut reduces text

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#1083]
#### Short description
As mentioned in #1027, 
> copying an article from the web into a Markor note, then Select All, Cut, Paste - results in just a couple of lines being pasted.
Select All + Cut + Paste reduces the text even further. At about 100 characters, the reduction does not appear again.
All operations (select, cut, paste) in Markor done through the keyboard smartbar.

#### Environment information
- FlorisBoard Version: 0.3.13-Beta 06

**Comment by patrickgold** [comment]
Further discussion surrounding this bug will be done in #1146, please follow along that thread! Closing this issue to keep the discussion for this bug in one thread.
