### ISSUE TITLE
Haptic Feedback broken on android os without google play service (graphene os) 

### ISSUE THREAD

**Issue by MrMattM** [florisboard/florisboard#1084]
Hi, I've used florisboard before and know the haptic feedback is usually good however on a custom os called graphene os based on AOSP without google play services seems to break haptic feedback on many keyboards except interestingly for giphyboard and its stock keyboard it comes with.

**Comment by Glitchy-Tozier** [comment]
Hi, and thank you for taking the time to report this issue!

Could you please edit your comment to include the environment-info? Here's the structure:

```
#### Environment information
- FlorisBoard Version: <!-- e.g. 0.X.X -->
- Install Source: <!-- Google PlayStore/F-Droid/GitHub/? -->
- Device: <!-- e.g. OnePlus 7T -->
- Android: <!-- e.g. 10, Stock -->
```

**Comment by MrMattM** [comment]
#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android: 


One thing to note is I am running a custom os called graphene os that removes all google play services. Also I noticed after some tweaking i got haptic feedback to work i just had to set the vibration to " system default " and interestingly for a different keyboard with same issue adjust milliseconds for a vibration to activate.

**Comment by MrMattM** [comment]
#### Environment information
- FlorisBoard Version:  0.3.1.2
- Install Source:  F-Droid
- Device:  google pixel 4 xl
- Android: 11

**Comment by patrickgold** [comment]
@MrMattM if possible could you install the [debug artifact](https://github.com/florisboard/florisboard/pull/1142/checks) (installs separately) of above PR and check if the new implementation of audio/haptic feedback fixes your issue? Thanks in advance!
