### ISSUE TITLE
Swipe geatures based on velocity measurement fail on some devices

### ISSUE THREAD

**Issue by ursi** [florisboard/florisboard#1086]
I used to use the swipe forward and swipe back gestures a lot, but now I can hardly get them to work, even with the thresholds set to very slow and very short. I'm not sure when this changed but my best guess is when glide typing was released.

#### Environment information
- FlorisBoard Version: I can't find it in the app but I believe it's the latest non-beta version
- Install Source: GitHub
- Device: Oppo Reno 10x Zoom
- Android: ColorOS v7.1

**Comment by Glitchy-Tozier** [comment]
Btw, the about-page can be found here: 
![Screenshot_20210723-073431_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/126741193-2b348b69-5ae8-4fb7-a279-c35d104ff84d.jpg)
![Screenshot_20210723-073445_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/126741198-a09f2e7f-01fe-4aaa-a1b5-a8efd048b552.jpg)

**Comment by ursi** [comment]
thanks! looks like I'm on 0.3.12.

**Comment by Donkey-Doug** [comment]
Same for the swipe down gesture.

**Comment by patrickgold** [comment]
Thanks for your bug report! There are numerous issues with swipe gestures (they work perfectly fine on some devices and don't work at all on others) and this has possibly something to do with the screen density of your display (where the pixels per inch are used for velocity calculation). I really should look into this topic in the near future, due to spell checking I kinda forgot that this issue still persists.

> I'm not sure when this changed but my best guess is when glide typing was released.

Glide typing does not influence the swipe logic, but at some point during the layout rework I changed the touch logic and this is where I think I introduced this bug.

**Comment by ursi** [comment]
I just downloaded 0.3.13, and although it does seem to be slightly better, it's still not as good enough for it to be usable again :(

**Comment by patrickgold** [comment]
What are your gesture threshold values set to?

**Comment by ursi** [comment]
very slow, very short

**Comment by patrickgold** [comment]
Ok, maybe try to play around with the thresholds (begin at normal/normal) and see if there's a combo that works for you.

**Comment by ursi** [comment]
on normal/normal it was even harder. I couldn't  even do it without taking my hand off the phone to build up speed. Seems slow/short was also still harder than very show/very short. I guess I should go back and try to find which version made it break, cuz it worked great before.

**Comment by patrickgold** [comment]
Hmm that's very strange. I looked up the device specs for the device you stated in the initial issue comment and the pixel density is not that much different from the devices I tested this on, which makes this bug very strange. I still suspect the velocity measurement has some bugs in it, which causes the measured value to be outside the selected threshold range.

> I guess I should go back and try to find which version made it break, cuz it worked great before.

v0.3.11-beta04 AFAIK from other users, the version I introduced velocity based measurement into gestures.

**Comment by patrickgold** [comment]
@ursi Could you try out to clean the cache and restart FlorisBoard to see if that improves things?

**Comment by ursi** [comment]
So idk, how to restart that app specifically cuz it's a keyboard, but I deleted the cache and the data, then restarted my phone and got this. The keyboard does work though. Setting the thresholds to VS/VS does seem better than before, but it still doesn't sometimes with my natural motion. Normal/Normal (which I tried first) was worse.

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: OPPO CPH1919
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1630346097750.stacktrace</summary>

```
java.lang.RuntimeException: Unable to instantiate service dev.patrickgold.florisboard.FlorisImeService: kotlin.UninitializedPropertyAccessException: ThemeManager has not been initialized previously. Make sure to call init() before using default().
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4224)
	at android.app.ActivityThread.access$200(ActivityThread.java:239)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7840)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:985)
Caused by: kotlin.UninitializedPropertyAccessException: ThemeManager has not been initialized previously. Make sure to call init() before using default().
	at dev.patrickgold.florisboard.ime.theme.ThemeManager$Companion.default(ThemeManager.kt:94)
	at dev.patrickgold.florisboard.ime.core.FlorisBoard.<init>(FlorisBoard.kt:134)
	at dev.patrickgold.florisboard.FlorisImeService.<init>(FlorisImeService.kt:30)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4219)
	... 8 more

```
</details>

**Comment by patrickgold** [comment]
Hmm the crash you posted above is a new one and seems to be direct-boot related.

As for the gestures, I think the best solution would either be for me to introduce on-device gesture calibration or to allow the threshold values to be manually set as an integer slider.

**Comment by ursi** [comment]
Both sound like great ideas to me! But I'm partial to the integer approach myself.
