### ISSUE TITLE
Arabic numerals are hardcoded into the Arabic layout's popups

### ISSUE THREAD

**Issue by hyphenrf** [florisboard/florisboard#1087]
In most keyboards that support Arabic, Persian, etc.., the default behaviour of long pressing a letter is getting its most frequently used variant first, not the symbol that resides in its place on the symbols layer.. For example,
![image](https://user-images.githubusercontent.com/26802762/126724608-ce0ef3aa-6df0-4fa6-9be2-42d67fbacfe6.png)
as opposed to,
![image](https://user-images.githubusercontent.com/26802762/126724592-50576318-edc1-4d7d-9b79-17df3e16d40b.png)
I think maintaining that expectation might be a good idea. As such variants are used much more often than the current symbols.

**Comment by patrickgold** [comment]
If you go to Settings > Keyboard and set the "Hinted symbols/number row" preferences to "Enabled (Accent prioritized), does this resolve the issue?

**Comment by hyphenrf** [comment]
That does solve the problem yes :)

I passed by that setting during setup and it wasn't really immediately obvious what it does so I left it at "smart" because I felt the default would be good enough whatever it is. so that's something to consider I suppose..

by the way, is long pressing the letters on the highest row for arabic supposed to reveal duplicated numbers?

![image](https://user-images.githubusercontent.com/26802762/126790521-751cf497-ba72-4504-beb6-2f3ea9edac77.png)  ![image](https://user-images.githubusercontent.com/26802762/126790576-32a4c3ea-ab34-4cf2-b2c9-76138b0aa11d.png)

**Comment by patrickgold** [comment]
> by the way, is long pressing the letters on the highest row for arabic supposed to reveal duplicated numbers?

No, this is because the Arabic layout was added before the numeric hints and Arabic numerals support were a thing, so these were hardcoded into the layout's popups. Will change the issue's title to match this issue, as the origial issue has been fixed for you.

**Comment by patrickgold** [comment]
This issue has been fixed by <span>@</span>Waelwindows in above PR and will be in tomorrows beta09 release!
