### ISSUE TITLE
get people to help ya, dude!

### ISSUE THREAD

**Issue by cauerego** [florisboard/florisboard#1088]
don't go solo!

![Screenshot_20210723-055950](https://user-images.githubusercontent.com/560418/126739205-c2dc6dec-72da-427e-a4a9-9322ffc2c0db.png)

i may be under the wrong impression, but it really looks like you're going solo right now.

on a similar note, perhaps you could join forces with anysoftkeyboard, which is taking a very similar route...

cheers! 😘

**Comment by yant0** [comment]
..

**Comment by Glitchy-Tozier** [comment]
@yant0 Please keep your contributions constructive and friendly.  :)

@cauerego What course of action do you suggest?

**Comment by cauerego** [comment]
talk to people.

over voice.

**Comment by patrickgold** [comment]
Hey @cauerego 

I am aware that me taking the solo route means things just get handled at a lot slower rate. At the time the screenshot was created I was under a lot of stress which made the situation worse. Now as you can see things start to get rolling again and a lot of bug fixes improvements and small new features get added regularly (in the beta track). Also I am not alone in the end, there are many supportive and helpful people around me, who help in keeping the issues a bit more organized, I have some people who regularly help out in testing new features/fixes, who participate in discussions and also people who add new stuff via PRs (we are already at ~200 merged PRs, that's a lot!). So I am a solo dev who isn't doing it solo at all.

~ Patrick

**Comment by cauerego** [comment]
can't wait to see what will come out of all this contribution...

for sure it'll grow much better than freaking gboard! 😘
