### ISSUE TITLE
Duplicate hints for international phonetic alphabet

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1089]
#### Short description
The hints double, showing two circles instead of one. See sreenshots

#### Steps to reproduce
![Screenshot_20210723-171947_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/126820773-a2e68f7d-bdef-4633-990c-1c7aff888e25.jpg)
![20210723_193856.jpg](https://user-images.githubusercontent.com/59611881/126820781-a92331b7-6ca0-4407-ab28-cf547c9d3c30.jpg)

#### Environment information
- FlorisBoard Version: 0.3.13-beta6
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! It seems like I added the dotted-circle so the combining marks aren't weirdly rendered, but at some point the dotted-circle was additionally hard-coded into the labels in the IPA layout. I've fixed the dotted circle appender, so it does not append a dotted circle for the marks if one is already there. Will be available in beta07!

**Comment by Glitchy-Tozier** [comment]
Great, good job!

One dotted circle will remain, it's just the un-decorated one that'll be gone, right?

**Comment by patrickgold** [comment]
> One dotted circle will remain, it's just the un-decorated one that'll be gone, right?

Yup, there will always be one dotted circle, else the circumflex marks will be all over the place (the font renderer does not like standalone circumflex marks at all).

**Comment by Glitchy-Tozier** [comment]
> the font renderer does not like standalone circumflex marks at all

I think adding the circle looks best anyways. (If i only see
```


‘


```
, I have no idea whether that's a comma or thát cháráctér.

**Comment by patrickgold** [comment]
Yes this is a good point, also adding the dotted circle for these characters is the per se standard across Wikipedia and pretty much all soft keyboards, so I think doing it this way makes most sense.
