### ISSUE TITLE
Private User Dictionary

### ISSUE THREAD

**Issue by ChaoticHub** [florisboard/florisboard#109]
It would be pretty cool to have a user dictionary that isn't the built in system dictionary. 

Anysoft keyboard has this feature 

![private-store](https://user-images.githubusercontent.com/35610319/103157477-227e7c00-4781-11eb-96c3-41bdbc6d2996.jpg)

**Comment by patrickgold** [comment]
Thanks for the suggestion! I've thought of implementing this together with the composing word suggestions, which I will soon start working on. I will add it to the milestone v0.4.0!

**Comment by ChaoticHub** [comment]
> Thanks for the suggestion! I've thought of implementing this together with the composing word suggestions, which I will soon start working on. I will add it to the milestone v0.4.0!

That's awesome, thank you. This project seems extremely promising, if suggestions are half as promising as open board or anysoft it will be my go to. Thank you so much for your work on this great project :)

**Comment by heberjeur** [comment]
can you add a button to import-export words file in the
