### ISSUE TITLE
Long press smartbar items for description

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1094]
Make it possible to longpress a button on the smartbar to get a description.

Example:

https://user-images.githubusercontent.com/50382414/126852189-3145643a-7af9-4609-8f19-66ef5e18a01c.mp4

**Comment by patrickgold** [comment]
Thanks for your feature proposal! I really like this idea, will add it to the list of things tbd for the Smartbar rework!

**Comment by patrickgold** [comment]
Above linked PR/commit implements long-press tooltips for Smartbar actions, will be available starting with v0.4.0-alpha03!
