### ISSUE TITLE
Double tap shift for caps lock

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1095]
Currently the caps lock can only be activated by press and hold of the shift key. It would be nice to have an option to use a quick double tap instead. Or perhaps even both methods can be used at the same time.

**Comment by yant0** [comment]
its already there...

**Comment by Glitchy-Tozier** [comment]
As @yant0 said, this functionality already exists. You just have to be fast.  :)

@Donkey-Doug Did you manage to get it to work?

**Comment by Donkey-Doug** [comment]
Only long press is working on my device, not double tap. This has been the case for a few versions now.

**Comment by Glitchy-Tozier** [comment]
That's really weird, let's see what Patrick can do when he finds this issue.

**Comment by patrickgold** [comment]
This is already implemented, you just have to do two consecutive taps of the shift key for caps lock (within 300-700ms depending on your configuration). There are quite a few gesture bugs in FlorisBoard, but this one would be a first, no reports from even the most problematic ROMs thus far on this issue :)

Please let me know if tapping two times quickly on the shift key does activate caps lock, else there's either a misconfiguration or a bug... Thanks in advance!

**Comment by Donkey-Doug** [comment]
Tapping two times quickly does not activate caps lock. See my video (I show my taps on screen). Let me know what I can do to help document the bug.

**Comment by Donkey-Doug** [comment]
Double tap for caps locks only works when "long key press delay" is at 150ms or higher

**Comment by patrickgold** [comment]
Ok based on your video I totally didn't see (sorry) I can rule out any theme bug, also caps lock works when long pressing. My best guess is that the last pressed character gets messed up, which is a requirement for a double tap shift to activate caps lock. Is it possible for you to install the latest beta from [IzzySoft's repo](https://apt.izzysoft.de/fdroid/index/apk/dev.patrickgold.florisboard.beta) (or just from the [GH release section](https://github.com/florisboard/florisboard/releases) directly) and see if the bug is still there?

**Comment by Donkey-Doug** [comment]
I am on beta06 (the latest)

**Comment by patrickgold** [comment]
> Double tap for caps locks only works when "long key press delay" is at 150ms or higher

This could very well mean the processing logic is too slow at processing the taps and 100ms is too close in a time frame for two taps to be successfully recognized.

**Comment by Donkey-Doug** [comment]
I don't think that is the case. Even if I press extremely fast (as fast as I can), caps lock won't trigger.

**Comment by Donkey-Doug** [comment]
Probably. 100ms is almost instantly. Would it be possible to provide a minimum of 150ms for the caps lock?

**Comment by Donkey-Doug** [comment]
Some new gaming smartphones have a touch sampling rate of 720Hz. It could be the case that my hardware cannot handle 100ms. Or it could be a limit of the human body and the speed at which we can move our fingers.

**Comment by Glitchy-Tozier** [comment]
> This could very well mean the processing logic is too slow at processing the taps and 100ms is too close in a time frame for two taps to be successfully recognized.

To me this sounds like IF this was the problem, it could be fixed by logging the timestamps of the taps, and then comparing them.

It seems weird to me that increasing the long-tap threshold impacts double-taps though.

**Comment by Donkey-Doug** [comment]
> It seems weird to me that increasing the long-tap threshold impacts double-taps though.

Me too. I only found out because of patrick's comment:
_you just have to do two consecutive taps of the shift key for caps lock (within 300-700ms depending on your configuration)._

**Comment by tsiflimagas** [comment]
Is it possible to make this gesture have a minimum duration threshold or even a fixed duration? It would be nice if it could stay at a reasonable value, while being able to have a very swift long press delay.

**Comment by patrickgold** [comment]
Above linked commit fixes this issue, I now query the system to provide the default double tap timeout for detecting double press events. Long press delay does not play a factor for double tap anymore.

Will be released in 0.3.16-beta02, thanks again for reporting!
