### ISSUE TITLE
Show "grabbers" after selection

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1099]
Is it possible to show the grabbers to adjust the highlighted text when using shift+swipe, similar to manual text selection?

![Screenshot_20210724-225854_Firefox_1](https://user-images.githubusercontent.com/50382414/126880976-cf425633-4da2-442e-9b6e-b81b9fbaf625.png)

**Comment by patrickgold** [comment]
Thanks for your feature proposal! Sadly, the keyboard cannot control the visibility of the grabbers, only the system can do this. These grabbers are only shown when manually selecting the text within the input field, when the selection is set through the input connection, the system assumes you don't need the grabbers. Closing as this feature is impossible to add.
