### ISSUE TITLE
5-Row Keyboard Layout Bug

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1100]
Hi, @patrickgold  thanks for your work and for developing this great keyboard i using it as an alternative keyboard to GBoard.

The older versions of FlorisBoard suppotred 5-Row layouts perfectly but after rewrite layout logic and rendering engine that happened since the beta version (3.11-beta02) Doesn't support 5-Row layouts when Number row is enabled from top of characters when you enable it the number row and characters are mixed that's so strange with 5 Row but other layouts works and showing without any problem could you please take a look and fix this annoying bug.

BECAUSE this 5-Row layout is mostly using and it's Standard layout for typing in Central Kurdish(کوردی)

* For info this bug is only happen when you enable top Number row in the normal layout that 4-Row there is no problem but after enabling numbers row the layout becomes 5-Row and bug shown below.

Here is screen shot from 3.11-beta01 that 5-Row is works perfectly:

![Screenshot_20210725-002901](https://user-images.githubusercontent.com/3160786/126881737-dd8b7190-a617-4f26-91a9-208285fb9013.jpg)

And this one is after 3.11-beta02 till now latest beta 3.13-beta06 same Bug appears for 5-Row

![Screenshot_20210725-003246](https://user-images.githubusercontent.com/3160786/126881775-75854d5e-b4d3-41d6-977c-db5537740af4.jpg)

**Comment by patrickgold** [comment]
Thanks for your bug report! I am aware of this bug, as since the mentioned layout rework only 5 rows in sum can be rendered nicely, when using a 5-row layout + number row this is a 6-row layout technically and the layout engine does not account for this. This bug has also been filed by you in #863 I just discovered. As this version provides more info though, I will close #863 and use this issue to fix the bug.

**Comment by GoRaN909** [comment]
You right when enabling number row it becoms 6-Row that cause the bug and characters mixed with numbers i wish you add new engine to support 6 rows.

About duplicated issue  i waited and installed all newer versions after 3.11 beta01 i thinks that will fix in newer one but the bug is not fixed after nearly 3 months ago that bug appears and still same bug there on all newer beta and stable versions.
