### ISSUE TITLE
No suggestions 

### ISSUE THREAD

**Issue by lazerleif** [florisboard/florisboard#1104]
Okay I have tried for hours to get the suggestions in the smart bar to show up. I feel so stupid for not getting it to work.

I have manage to download and activate the spelling service. But i cant get any suggestions to show up. Have tried i my language and in english. Did update to latest beta without any luck.

However if I add words to the user dictionary i will get thoose words to show up. But this mean i must add the whole English dictionary manually?

I hope i have missed some basic settings. Please help 😄

**Comment by tsiflimagas** [comment]
Suggestions aren't implemented yet, so that's normal. They're scheduled to be implemented though.

**Comment by lazerleif** [comment]
Oh okay! Good to hear i guess. I was just fooled by all the screenshot that shows suggestions 😄

I can finally get some sleep. Thank you for answer
