### ISSUE TITLE
Custom Key Border color

### ISSUE THREAD

**Issue by SoumyBhow** [florisboard/florisboard#1105]
Hello

Will it be possible to add a custom border color for the keys? I'm trying to recreate the following Gboard theme (razerred from Rboard Theme Manager app). In the theme, the key boarders are red while the keys themselves are black. Is it possible to implement this?

Thank you for your time.
![Screenshot_20210726-015647602](https://user-images.githubusercontent.com/42043870/126940260-4e5f5109-51b6-4f0b-86c3-04b7ae094429.jpg)

**Comment by patrickgold** [comment]
Thanks for your suggestion! The key border of FlorisBoard currently technically speaking is just the shadow, which makes it look like the key has a border. Looking at above screenshot though, having an option for a real colored key border would indeed look cool for some theme styles. Will add it to the theme improvements list!

**Comment by SoumyBhow** [comment]
Thank you so much! Can't wait to see it in action.

**Comment by patrickgold** [comment]
Above commit adds the ability to specify a border color and width for many elements styleable through the new theme editor. Will be released in 0.3.14-beta12. Thanks again for your proposal!
