### ISSUE TITLE
Glide Typing Issue When Typing

### ISSUE THREAD

**Issue by Linerly** [florisboard/florisboard#1106]
#### Short description
Annoying glide typing bug when typing normally.

#### Steps to reproduce
1. Enable glide typing
2. Type normally with your fingers sweating (or have moisture on them)

#### Environment information
- FlorisBoard Version: 0.3.12 
- Install Source: F-Droid 
- Device: Mito W1 
- Android: 9, Stock 

https://user-images.githubusercontent.com/47475676/126966624-b8442f87-c7b2-43ec-a693-b358e85eaf70.mp4

**Comment by Linerly** [comment]
This sometimes happen as well, even if my fingers are not sweating or have moisture on them

Typing using Gboard with swipe typing enabled, and with my fingers sweating as well, rarely makes mistakes from the accidental swipe typing for some reason (don't know if Gboard has some sort of sensitivity for the swipe typing feature, but might be just my feeling)

**Comment by Glitchy-Tozier** [comment]
(May be improved/fixed by working on #601)

**Comment by Linerly** [comment]
Ah, okay then

**Comment by patrickgold** [comment]
Is this bug still persistent and reproducible in 0.3.16-beta02?

**Comment by Linerly** [comment]
Hmm, not really

**Comment by patrickgold** [comment]
Okay if not then I think I will close this issue. Glitchy is right, #601 would be a major improvement in reducing accidental typing errors, as well as the 0.4.0 word predictions.
