### ISSUE TITLE
Open Suggest/Issue Reporter Upon App Crash

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1111]
Hi, I really like this amazing keyboard i want this app have many many new features i want to suggest to the developer of FlorisBoard @patrickgold use this [Android Issue Reporter](https://github.com/heinrichreimer/android-issue-reporter) library inside the florisboard when the app crashes show this screen instead the one now we haved the goods of this library is user can suggest an feature to the developer or report a crash info directly from the app using Github account or send the report log anonymously.

here is some screeshot of the app:

![687474703a2f2f692e696d6775722e636f6d2f644a596f6e42572e706e67](https://user-images.githubusercontent.com/3160786/127238305-c23046b2-4157-46f6-8776-9c5ee6d44701.png)

![687474703a2f2f692e696d6775722e636f6d2f41446b50514d6f2e706e67](https://user-images.githubusercontent.com/3160786/127238311-fd1550a6-49fc-4e4d-9c08-dd6c2b0df57d.png)

![687474703a2f2f692e696d6775722e636f6d2f6663466d4a35452e706e67](https://user-images.githubusercontent.com/3160786/127238313-bdda6ca6-7d75-46bd-8913-fe1f40148c1e.png)

**Comment by Glitchy-Tozier** [comment]
I may be mistaken, but wouldn't that require internet permissions to be added?

**Comment by GoRaN909** [comment]
> I may be mistaken, but wouldn't that require internet permissions to be added?

Yes it needs this permission  <uses-permission android:name="android.permission.INTERNET" />

But what's the problem if we have Internet permission in FlorisBoard!

**Comment by tsiflimagas** [comment]
Afaik, FlorisBoard isn't going to require internet permission, for privacy reasons. @patrickgold is this something we can be sure of (at least for the time being)? I think I've seen you writing about it a few times, but I don't want to close issues regarding that, if I'm not certain.

**Comment by patrickgold** [comment]
FlorisBoard will not need internet permission in the forseeable future, at least never in the base APK. It would make some things easier but privacy by default is just more important. So yeah, implementing a crash reporter like above is pretty much impossible.

**Comment by tsiflimagas** [comment]
I suppose this can be closed then.
Thanks for the proposal anyways.
