### ISSUE TITLE
Clipboard-pop-up stays visible after closing clipboard-manager

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1112]
#### Steps to reproduce
1. Copy something
2. Go to the clipboard-manager
3. Long-click the element. A pop-up will ... pop up.
4. Press the android back-button
5. Reopen the keyboard

#### Environment information
- FlorisBoard Version: 0.3.13 – beta 6
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

![florisPlace](https://user-images.githubusercontent.com/59611881/127316871-0598ca82-2136-42fa-bc7c-766e48f5eef7.jpeg)

**Comment by patrickgold** [comment]
Classic state bug :) Assigning it to the list of clipboard issues!

**Comment by patrickgold** [comment]
The clipboard popup issue is actually Glitchy-safe now in the upcoming beta07 release, so I will close this issue :)

**Comment by Glitchy-Tozier** [comment]
> The clipboard popup issue is actually Glitchy-safe now

For some reason you keep removing all those fun bugs... Good job :)
