### ISSUE TITLE
Number row appears in password fields

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1115]
Is it supposed to be the case that when I am typing in a password field, my smartbar gets replaced by a number row?

https://user-images.githubusercontent.com/50382414/127323802-7ae2effc-5978-45f9-9597-da2944cc46bd.mp4

**Comment by patrickgold** [comment]
Yes, this is an intended feature and should help with entering numbers quicker for passwords (also suggestions for passwords makes no sense, so I added this feature).

**Comment by farfromrefug** [comment]
I personally love that feature!

**Comment by chrstfer** [comment]
@patrickgold i disagree that suggestions for passwords make no sense, because password managers like bitwarden make use of that region to present available logins (or an "unlock password store" button).

**Comment by patrickgold** [comment]
@chrstfer If you are on a device with Android 11+ and have a password manager which supports inline suggestions, then password suggestions from your pw manager will override the number row in this special case. This is already implemented and works ~90% of the times you need it (the API is a bit buggy and inconsistent, but overall it works well). What I meant is traditional word suggestions coming from FlorisBoard, these make no sense at all.

**Comment by chrstfer** [comment]
Oh alright, and yeah i havent noticed this specifically so it makes sense that its actually being overridden in my case. This behavior definitely makes sense if it gets overridden by a password manager as you say. Thanks!
