### ISSUE TITLE
Why is my writing in Spanish not working well?

### ISSUE THREAD

**Issue by murph2495** [florisboard/florisboard#1119]
Hi friends. I am from Argentina and I have been testing the keyboard for several months. I wanted to comment on something, that from day one that I started using the keyboard I could never write well in spanish. Is this because dictionaries in languages ​​other than English are not required?Or is it because the suggestion and auto-correction system is not yet implemented in other languages?. In any case, if you know how I can improve my experience when writing in Spanish, please let me know, and in advance, thank you very much for your time and work.

**Comment by Glitchy-Tozier** [comment]
> ...Or is it because the suggestion and auto-correction system is not yet implemented in other languages?

This is it. If you're using the latest non-beta version, non-english languages weren't implemented yet. This is currently being worked on.  :)

**Comment by murph2495** [comment]
Thank You do much, I will wait patiently then. thanks for your reply and time
