### ISSUE TITLE
Change the default choice for held buttons

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#112]
I sometimes will hold a letter to select a number, and for example on 3, the default is another character with an accent and I have to select the number. This seems pointless and unnecessary. 3 should be the default choice.

**Comment by patrickgold** [comment]
Yeah this issue of what should take priority in the extended popup has already be discussed in #39. I will soon add a toggle for this behavior, so you can choose between the two behaviors. Closing this issue as it is a duplicate.
