### ISSUE TITLE
Using this version of Floris Beta:

V.0.3.13-beta07.

Swipe doesnt work. Any reason why? Please let me know if you need any further info..

Thanks

### ISSUE THREAD

**Issue by shreyanssshah** [florisboard/florisboard#1120]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by Glitchy-Tozier** [comment]
Hi, this is what the release-notes for beta7 say: 

> Note: this beta release accidentally breaks glide typing. In the master branch code this is already fixed and beta08 will have glide typing fully working again. Sorry for the inconvenience!

**Comment by patrickgold** [comment]
Yes, I accidentally broke glide typing, will be available again in beta08! See #1102
