### ISSUE TITLE
Layout issues and annoyances in Russian and Italian

### ISSUE THREAD

**Issue by zeronovantuno** [florisboard/florisboard#1121]
Hello!

Here are a few annoyances I noticed by using the keyboard.

In Russian
- the spacebar has a huge font saying "Russian" compared to other languages
- the default ь second function should be ?, as ъ is not a very common letter. Or at least, waaay less common than "?".

In Italian 
- the default n second function should be !, as we don't use ń at all in Italian (it's a Polish letter, you could actually remove it).

**Comment by patrickgold** [comment]
Thanks for your suggested fixes! It looks like you have the hint priority to accents prioritized, thus the ь and the ń are prioritized over the symbols. If you select "Smart prioritization" in Settings > Keyboard > Hinted number/symbols, this should fix the issue.

> the spacebar has a huge font saying "Russian" compared to other languages

Depending on the version (including the betas) you use, this language display looks different and may contain different bugs. There are already separate issues for this though and I plan to work on that display in the future.

**Comment by tsiflimagas** [comment]
It seems to me that the only thing left here is removing "ń" from italian layout, right?

**Comment by patrickgold** [comment]
Actually all of the above are fixed when using "Smart prioritization" (the default and suggested) in the hint preferences in Settings > Keyboard, checked in the latest stable version 0.3.14. As this is the case I will close this issue as fixed.
