### ISSUE TITLE
Always show clipboard manager icon on top

### ISSUE THREAD

**Issue by shockergit** [florisboard/florisboard#1122]
Please add an option to always show clipboard manager icon on top bar
![IMG_20210801_163300](https://user-images.githubusercontent.com/63154802/127768571-07c45a7f-98db-41fe-85f8-29948be26af5.jpg)

**Comment by Glitchy-Tozier** [comment]
How does it currently work?

**Comment by shockergit** [comment]
> How does it currently work?

You have to type some letters then select it. Then the clipboard manager will show up

**Comment by Glitchy-Tozier** [comment]
I assume you don't see anything else up there either?

**Comment by shockergit** [comment]
> I assume you don't see anything else up there either?

????

**Comment by Glitchy-Tozier** [comment]
Do those symbols also disappear?![Screenshot_20210801-171927_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/127776279-16332149-a756-40f3-8c8c-937a7c18ef98.jpg)

**Comment by shockergit** [comment]
Yes it disappear.
![IMG_20210801_205220](https://user-images.githubusercontent.com/63154802/127776460-dfc3dd2c-368a-4a40-ba2e-f4ba3249b2ee.jpg)

**Comment by xAffan** [comment]
I need this, please please please please or I will need to use the shitty GBoard again

**Comment by Glitchy-Tozier** [comment]
It only disappears because something else is enabled.
Did you enable word-suggestions?
![Screenshot_20210801-175900_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/127777508-a6ca21ea-c65e-4534-999e-89ab2e7f91e9.jpg)

**Comment by shockergit** [comment]
> It only disappears because something else is enabled.
> Did you enable word-suggestions?
> ![Screenshot_20210801-175900_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/127777508-a6ca21ea-c65e-4534-999e-89ab2e7f91e9.jpg)

yes i did

**Comment by shockergit** [comment]
Now it shows up it would have been nice if you add an option to customise this toolbar so that i can add the clipboard icon
![IMG_20210801_213428](https://user-images.githubusercontent.com/63154802/127777717-28c59675-a420-4014-b841-5fa39d894c24.jpg)

**Comment by xAffan** [comment]
That's what I am saying!!!! This toolbar should have clipboard icon.

**Comment by Glitchy-Tozier** [comment]
Customization of this quick-actions-bar is coming, but it'll still take a while to be implemented. Spell-checking, word suggestions, etc. have a higher priority.

**Comment by shockergit** [comment]
> Customization of this quick-actions-bar is coming, but it'll still take a while to be implemented. Spell-checking, word suggestions, etc. have a higher priority.

Thanks well prioritized👍

**Comment by slmb3** [comment]
Just checking is this still planned coming? If still far out, maybe some pointers to the relevant sections in the code could help someone else get started.

**Comment by patrickgold** [comment]
In the upcoming 0.3.14-beta07 release the clipboard history icon will always show both in the Smartbar quick actions and in the clipboard cursor row, thus this issue should be resolved. Will be released tomorrow.
