### ISSUE TITLE
Voice typing (speech-to-text) key

### ISSUE THREAD

**Issue by parcelcat** [florisboard/florisboard#1131]
I'd love to see the option to add a key or another way to activate voice typing. Ideally, this function should trigger the device's default voice input (speech-to-text) provider.

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for taking the time to write this feature request.

Speech to text has already been suggested, see #195.

**Comment by parcelcat** [comment]
@Glitchy-Tozier Oops, I only searched for voice typing and missed that one. Thanks!

**Comment by Glitchy-Tozier** [comment]
Ah, i see!
If you don't mind, I'll close this issue as a duplicate. Should you have any further ideas, make sure to post them in #195!  :)
