### ISSUE TITLE
Numeric layout with 789 on top

### ISSUE THREAD

**Issue by maocetong** [florisboard/florisboard#1132]
Hello, can anyone please reverse the numpad layout to that of computer keyboard? Or at least make a feature to toggle the layout? Thanks.

Floris Keyboard's numpad layout: 
![1628184690](https://user-images.githubusercontent.com/88506466/128395232-4a7ae699-58c5-47e3-b913-456969ab6c0b.png)

Normal keyboard's numpad layout:
![1628184653](https://user-images.githubusercontent.com/88506466/128395330-aee4e751-4642-495f-995f-de06541d8dd5.png)

**Comment by patrickgold** [comment]
Thanks for your suggestion! While the current 123 on top numeric layout is he standard for phones, it is very easy to add an alternative layout which has these numbers reversed. Will do such implementation now.

**Comment by patrickgold** [comment]
Above linked PR adds alternative layouts for the numeric and numeric advanced layouts, which have the 789 at the top. You have to edit your subtype and select the alternative layouts for them to show up. Will be available in the next beta release.

**Comment by SchmurpiDurpi** [comment]
@patrickgold Hi, thank you for implementing the PC layout for numeric fields. But there is still the phone number layout which comes up in phone number fields, that still only has the 123 layout. Can you also please add the 789 PC layout to the phone field layout?
