### ISSUE TITLE
Enable copy&paste in smart-bar for password fields

### ISSUE THREAD

**Issue by mdxe** [florisboard/florisboard#1135]

**Comment by Glitchy-Tozier** [comment]
Could you please properly explain the issue that you're having?

**Comment by mdxe** [comment]
For example, when I login into Github, if I click the username text box, I have a bar of icons at the top of the keyboard that allows me to paste, copy, cut, move the cursor left or right, etc... but when I click in the password text box, this bar of icons gets replaced with numbers from 1 to 0... I would send a screenshot but when I try to take one, the keyboard automatically disappears.  I like to use that paste icon for the password because I use KeepassDX.

**Comment by Glitchy-Tozier** [comment]
That clears up the problem, thank you for describing it.

The number row is intended to show up, probably because copying passwords is kind of unsafe.
However, customization of the smart-bar is planned, so if you wait a bit, you'll be able to change it to your liking.  :)

**Comment by mdxe** [comment]
Great news, and thanks for the great keyboard!

**Comment by 1RandomDev** [comment]
I also really miss an option for that, because I have to paste many passwords from my password manager and it would be extremely easy to just click a button to do so.

**Comment by Glitchy-Tozier** [comment]
@mdxe Could you rename this issue to something like "Enable copy&paste-bar in password-fields"?

**Comment by mdxe** [comment]
copy is not as important for password fields where you can't unmask the text
