### ISSUE TITLE
While editing theme, the keyboard looks different than in the selection

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1136]
#### Description
Whenever you're on the theme-editing screen, the keyboard slightly gets messed up.
- Icons fully disappear
- The language-text on the Spacebar is positioned differently
- The currency goes blank. (If you don't know which currency to use, you could use [the generc currency symbol](https://en.m.wikipedia.org/wiki/Currency_sign_(typography)). That being said, on the previous screen you _do_ know what symbol to use, so it should be the same here.)

#### Environment information
- FlorisBoard Version: 0.3.13-beta8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

#### Sceenshots
![Screenshot_20210807-083055_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128591003-5af16287-c5b0-4815-8c16-c20494d24c40.jpg)
![Screenshot_20210807-083120_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128591009-1b29e130-ff4c-4780-a564-6b0d46326669.jpg)

**Comment by Glitchy-Tozier** [comment]
(Also the "Speichern" Button at the bottom could be improved)

**Comment by patrickgold** [comment]
Thanks for your bug report! The theme editing preview keyboard does not have a computer assigned, thus the preview looks so weird. Will place it on my todo list!

**Comment by patrickgold** [comment]
> (Also the "Speichern" Button at the bottom could be improved. German strikes again.)

Best idea would be to change "Gruppe hinzufügen" zu "Neue Gruppe", so the save button has enough room. This change needs to be done in Crowdin though, all string resources besides English are not managed via GitHub.

**Comment by Glitchy-Tozier** [comment]
> Best idea would be to change "Gruppe hinzufügen" zu "Neue Gruppe", so the save button has enough room. This change needs to be done in Crowdin though, all string resources besides English are not managed via GitHub.

Seems like a good fix to me!  :)

**Comment by patrickgold** [comment]
I have fixed the group text for German, next time I re-fetch the translation files this should be fixed!

**Comment by patrickgold** [comment]
Above PR is a fix for the weird looking preview in the theme editor, will be available in beta09!

**Comment by Glitchy-Tozier** [comment]
Nice job, Patrick!
