### ISSUE TITLE
Rotating screen resets theme-editing-progress

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1137]
#### Steps to reproduce
1. Start editing a theme
2. After a while, rotate your phone into landscape mode and back
3. All progress is gone. Cry.

(Additionally, by rotating the screen, all pop-ups/dialogues will be closed)

#### Environment information
- FlorisBoard Version: 0.3.13-beta8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

#### Sceenshots
Before rotating:
![Screenshot_20210807-084712_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128591330-e7bafff8-3bb8-45e3-8b4e-e98352b2aa9b.jpg)

After rotating:
![Screenshot_20210807-084723_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128591337-6d298270-62fa-4b97-aff4-2331463b4562.jpg)

**Comment by patrickgold** [comment]
Classic bug in Android dev, state loss on rotation. Will place it on my todo list, but will probably fix this with the settings rework.
