### ISSUE TITLE
Current keyboard's theme influences theme-preview in settings

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1139]
#### Short description
This one is fun!  :)
May or may not be connected/helpful regarding #274.

#### Steps to reproduce
(Screenshots at the end)
Notice how I didn't change any settings regarding the theme!
1. Go to themes.
2. Activate "Adapt color to app"
3. Click on "Selected design"
4. Create a copy of Floris Day (and start editing it)
5. Remember how the keyboard currently looks. Not very green.
6. Click on one of the pen-icons to get access to a textfield
7. Click on the TextField. A green keyboard will pop up.
8. Click the back-button twice to get back to the main editing-screen. The keyboard preview will be green as well, ignoring your settings
9. Cancel out of the "Edit Theme" screen and return to the Design Manager. The preview will also be fully green.
10. Click on Gboard Day and enjoy the beautiful keyboard-preview.  :)

#### Environment information
- FlorisBoard Version: 0.3.13-beta8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

#### Sceenshots
![Screenshot_20210807-091622_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128592105-627602a4-4a5d-429f-8e02-413329db3df2.jpg)
![Screenshot_20210807-091630_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128592108-c22d2fa0-0870-430d-846a-6113be79a711.jpg)
![Screenshot_20210807-091638_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128592111-d41619c0-9cdc-40ed-a787-85a4ac577300.jpg)
![Screenshot_20210807-091645_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128592112-378c417a-2399-47db-8ce0-2bea8d151f1f.jpg)
![Screenshot_20210807-091651_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128592114-44c3ca2d-acda-44b9-b8b8-018f40ff96f5.jpg)
![Screenshot_20210807-091656_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/128592117-783d3acb-d6da-4918-b975-8506f3ae6bab.jpg)

**Comment by patrickgold** [comment]
Sorry for leaving this issue unanswered so long, my backlog is currently very big and I don't really know what to handle first :)

As for the issue - well noticed, but while trying this out I discovered just switching between two themes in the list which have different bg colors will do the trick too. This is definitely an important discovery, because the views itself are newly created and still have the old background color, meaning the bug is indeed within the theme manager. Solving it could indeed also be the solution for #274. Will add it to the todo list!

**Comment by Glitchy-Tozier** [comment]
Looking forward to what you can do!

> Will add it to the todo list!

Btw, is there an actual to-do-list this ended up on or is this another phrasing for "I'm not closing this issue"?  🤔

I have a to-do-list for my small little app so it would make sense for you to have one... I had to ask, though.

**Comment by patrickgold** [comment]
> Btw, is there an actual to-do-list this ended up on or is this another phrasing for "I'm not closing this issue"? thinking

Yes and no - at the beginning I maintained a text-file-based todo list of things I wanted to do. At the time this was more than enough and only rarely new issues were filed and this worked perfectly. Then after some time more and more things landed on that todo list - so I split it up into areas like settings and keyboard logic and layouts etc. This worked for a bit but then more and more requests flooded the issues and I became lazy in actually deleting off done stuff of the todo list, so it became a mess I tried to maintain but at some time just searched the issue list for keywords.

This was the time I introduced the `area: <area>` labels (there's actually quite a few of them). It helps me a lot in categorizing stuff. When I e.g. want to work on Settings, I filter the issue list for `area: settings` and immediately see my digital "todo list" of stuff I have to work on for this area.

So to answer your question - the act of me assigning the area label is basically me putting it on the todo list for the area this issue fits in. Me saying this pretty common term means I'll work on it when I find the time and the issue will stay open.

> I have a to-do-list for my small little app

Regarding your app, I don't know how long it is already on F-Droid but I spotted it 2 days ago. Great job!

**Comment by Glitchy-Tozier** [comment]
> ...the act of me assigning the area label is basically me putting it on the todo list for the area this issue fits in.

I see.
Does that also mean you'd prefer it if i left those labels alone? Because i *have* assigned them when i was absolutely certain where the issue belonged.

> Regarding your app, I don't know how long it is already on F-Droid but I spotted it 2 days ago. Great job!

I think that's when it was released. Thanks again for testing the pre-release and pointing out important caveats!

**Comment by patrickgold** [comment]
> Does that also mean you'd prefer it if i left those labels alone? Because i have assigned them when i was absolutely certain where the issue belonged.

No you assigning them is good for me - because if it is an issue it will land on the "todo list" either way, if you put it in the right area or I makes little difference.

**Comment by Glitchy-Tozier** [comment]
Got it!  👍

**Comment by Glitchy-Tozier** [comment]
Good job :)
