### ISSUE TITLE
Add Emoji Suggestion Feature 🤠

### ISSUE THREAD

**Issue by hellyeahmfs** [florisboard/florisboard#1141]
Add emoji suggestion feature on input like iOS. It is so handy to use. User has to search all emojis again which is a big turnoff. This could be a game changer too for this app. BTW thanks for this brilliant app ❤️

**Comment by patrickgold** [comment]
Thanks for your suggestion! I know the current emoji input is far from perfect and in [0.5.0](https://github.com/florisboard/florisboard/blob/master/ROADMAP.md#050) I will work on re-writing and improving emoji input. This particular suggestion has already been mapped in #56 / #268 (depending on what exactly you mean with emoji suggestion on iOS) though. To keep the list of issues clean, I will close this issue as a duplicate.
