### ISSUE TITLE
Cleaning-up Persian Texts!

### ISSUE THREAD

**Issue by hosseinshirmardi** [florisboard/florisboard#1144]
"[Virastar](https://github.com/brothersincode/virastar)" is really usefull tool to correct some usual mistakes in Persian.
I (and some people like me that pay attention to type correct,) doing this manually in Persian. I think it could be useful option in text correction for Florisboard.

Source: https://github.com/brothersincode/virastar

**Comment by patrickgold** [comment]
Thanks for your suggestion!

The linked library is a JavaScript library and is intended for web/nodejs platforms, FlorisBoard's codebase is Kotlin/Android or C++ native. Thus I am sorry to say that I cannot use the linked library.
