### ISSUE TITLE
Clipboard-manager and emojies don't properly adapt to app theme

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1155]
#### Steps to reproduce
1. Activate adapting themes (day-version)
2. Open the clipboard-manager in an app.

#### Environment information
- FlorisBoard Version: 0.3.13-beta8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

#### Screenshots

Invisible cards:
(Scrrenshot from github-theme)
![Screenshot_20210814-141834_Settings Suggestions.jpg](https://user-images.githubusercontent.com/59611881/129446106-4f2ce881-ae4f-4dcf-a92f-a26bc91fcce7.jpg)

**All following screenshots are made inside "pie-launcher" from @markusfisch.**
Text doesn't adapt:
![Screenshot_20210814-140458_Pie Launcher.jpg](https://user-images.githubusercontent.com/59611881/129446346-d265efea-e4d6-4c41-8bad-c759ef09cc54.jpg)

Emoji-categories don't adapt either.  This might have been mentioned somewhere else before.
![Screenshot_20210814-141233_Pie Launcher.jpg](https://user-images.githubusercontent.com/59611881/129446120-07b7c2f1-62d3-499c-bb1c-c0b8e744c694.jpg)

All other views adapt properly:
![Screenshot_20210814-141004_Pie Launcher.jpg](https://user-images.githubusercontent.com/59611881/129446264-db1c4abe-d906-496a-89b8-067722e443f0.jpg)

**Comment by imDusht** [comment]
SOmething like this also happens with me, all other are fine but when keyboard:background becomes black emoji panel looks like the screenshot.
![Screenshot_2021-09-01-11-04-23-503](https://user-images.githubusercontent.com/79660867/131618659-f4b148ef-c71b-49fe-b5db-1a4c49300760.jpeg)

**Comment by patrickgold** [comment]
I think we can close this issue as the emoji view currently does not exist (and will get proper theme support right from the start) and the clipboard view has proper theme support in the latest beta. What do you think?

**Comment by Glitchy-Tozier** [comment]
Sure, let's close the issue :)
