### ISSUE TITLE
Clipboard history elements visual improvement

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1163]
I think it would be better visually if elements in clipboard history looked exactly like keyboard keys. Therefore, add shadows and adjust the press animation/coloring to be cut exactly in the area of the key (on light theme you can notice that it's not precisely placed when you press an element).

**Comment by patrickgold** [comment]
Thanks for your suggestion!

The splash not aligning correctly is a known thing and has been reported in #1114. Adding a shadow to the clipboard items shouldn't be a problem. Should the shadow always be there or follow the theme rule for displaying key shadows?

**Comment by Glitchy-Tozier** [comment]
> Should the shadow always be there or follow the theme rule for displaying key shadows?

Personally, I like the idea of the theme extending across the whole keyboard.  :)

**Comment by tsiflimagas** [comment]
@patrickgold I agree with @Glitchy-Tozier, I'd say it should follow the theme rules, if you agree too :)

**Comment by patrickgold** [comment]
This will be indirectly resolved with tomorrow's beta07 release, but only in beta08 with the theme customization you will be able to customize the appearance of clipboard items. Note that I will attach it to the PR so GitHub will auto close this issue once I merge in the beta07 branch.
