### ISSUE TITLE
'Delete current word' doesn't work

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1166]
#### Short description

When 'delete key swipe left' is set to 'delete current word', nothing happens when swiping on delete key. 

#### Environment information
- FlorisBoard Version: 0.3.13-beta09 (52)
- Install Source: GitHub
- Device: Xiaomi Redmi note 8
- Android: 11, custom rom

**Comment by patrickgold** [comment]
Also related to #1130, current word/delete words precisely is currently buggy af and is my next thing to fix (besides working on adapting the F-Droid builds for 0.3.13). Will close this issue to keep the list of issues clean, but if you have any further info or want to discuss this further, you can always join in over at #1130!

**Comment by tsiflimagas** [comment]
Oh, missed that issue 😅
