### ISSUE TITLE
App UI has to get better and appealing.

### ISSUE THREAD

**Issue by Halfmit** [florisboard/florisboard#1167]
Things that need to be improved in terms of looks and presentation. People like what pleases their eyes. That's why people pay money in restaurants for the same item they could get for 1/10th of price at street vendors.
1. Welcome screen look outdated and plane. Grey text on white background with no formatting makes people assume that apps is not well maintained (which is faaaaar from truth tho).
2. Use hyperlinks instead of whole links for privacy policy and others.
3. Language should look more professional. Using words like `etc...` looks less appealing. 
4. After welcome screen there comes the Enable FlorisBoard. Here most important thing should be highlighted in bold that while enabling the keyboard, user will a message that "FlorisBoard might record everything you type.......", and this is a standard Android procedure and FlorisBoard will not collect any data. It should be stressed on this page.
5. Setup Finish thing is not needed. Empty and unnecessary.
6. Instead of localization (should be localisation) prefs--> implementing a good looking button would be more eye pleasing. 
7. In theme manager there should either be an info box on how to customise the themes that one wants to create on a help-link provided. Not everyone is interesting in GitHub.
This project is one of the most loved projects. No wonder why. While this FlorisBoard is way ahead of any open-source Keyboard, it should also look it is. It has compete with Keyboards like GBaord, SwiftKey and others. First thing for that is good presentation. It should look as if created by a high-end company. 
Love and love for this project.

**Comment by Glitchy-Tozier** [comment]
The welcome screen has been discussed here: https://github.com/florisboard/florisboard/issues/996

1. I suggest you remove the parts of this proposal that are duplicates of #996 to keep redundancy at a minimum.
2. I think the design proposed there by Patrick is pretty good. Should you have any further suggestions regarding the topic of the welcome-screen, make sure to post them there!
3. I think "Settings UI has to…" might be a more fitting title.

**Comment by patrickgold** [comment]
In general most points of this issue have been addressed in the beta releases over the last months, so I will close this issue with above linked PR. I am of course open to further feedback on the new UI, should you have one :)
