### ISSUE TITLE
Show Keyboard preview while Editing Keyboard Height

### ISSUE THREAD

**Issue by Halfmit** [florisboard/florisboard#1168]
One of the most important features of a good Keyboard app is to be able to customise the keys and the keyboard size per say. FlorisBoard has implement that pretty well. But what is missing is a preview of keyboard while doing it. 
There should be a **_preview_** while changing the keyboard height, offsets and key spacing so one does not have to keep switching to another app continuosly while finding the perfect combination of these. 
Amazing app tho.

**Comment by GoRaN909** [comment]
Nice idea i wish that someday see that feature in FlorisBoard :)

**Comment by patrickgold** [comment]
Thanks for your suggestion! A general keyboard preview is planned to be added to the Settings UI in 0.3.14, as this is a pretty often suggested/wanted feature. Note that this request has already been filed in #82 though, so I will close this issue as a duplicate.
