### ISSUE TITLE
Add Zero-width joiner

### ISSUE THREAD

**Issue by soheilkhanalipur** [florisboard/florisboard#1170]
Add Zero-width joiner as Zero-width non-joiner popup for Persian.

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for you request!

Could you elaborate and/or share some links that help understanding what you need?

**Comment by soheilkhanalipur** [comment]
[Zero-width joiner](https://en.m.wikipedia.org/wiki/Zero-width_joiner)
[Zero-width non-joiner](https://en.wikipedia.org/wiki/Zero-width_non-joiner)

[In GBoard](https://dl.uploadgram.me/61200ec1805b0h?raw)

**Comment by Glitchy-Tozier** [comment]
Thank you, let's see what Patrick says!

**Comment by soheilkhanalipur** [comment]
@patrickgold 😒

**Comment by soheilkhanalipur** [comment]
@patrickgold . . .

**Comment by patrickgold** [comment]
@soheilkhanalipur I know the Persian layout has some issues.

First the popups: the popups don't have an icon assigned to the key code, this the label is displayed. Looks ugly, but is relatively easy to fix.

Second: the zero-width joiner thing, that's one thing where I hear different opinions from different people what exactly should occupy the space right of the space key. I think that Gboard has a solid layout and FlorisBoard should follow suit. Currently I am occupied with the Settings rework however, so this has to wait.

Third: the space bar text being cut off: This issue happens not only for Persian, but for all kinds of languages where the space bar has too little space. Is tracked in a different issue.
