### ISSUE TITLE
Add temporary crash handler for Flictionary OOM errors until 0.3.15

### ISSUE THREAD

**Issue by heberjeur** [florisboard/florisboard#1176]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
I can't reproduce the error, just I opened firefox, the florisboard is still working, it dosen't return to the default keyboard

#### Environment information
- FlorisBoard Version: 0.3.13-beta10 (53)
- Device: Samsung SM-A505F A50
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1629670378948.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 42800 free bytes and 41KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 95420416 bytes)
	at dev.patrickgold.florisboard.ime.dictionary.Flictionary$Companion.load-B7oiUAE(Flictionary.kt:135)
	at dev.patrickgold.florisboard.ime.dictionary.DictionaryManager.loadDictionary-pqiQ7go(DictionaryManager.kt:94)
	at dev.patrickgold.florisboard.ime.text.TextInputManager$onWordHistoryChanged$1.invokeSuspend(TextInputManager.kt:1001)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
</details>

**Comment by patrickgold** [comment]
The old suggestions are implemented back, so stable track users don't loose access to the old suggestions. Aaaand they of course cause issues again. The particular stacktrace describes the infamous OOM error and happened while loading the dictionary for word suggestions. It means the Java heap ran out of memory (it is very limited unlike the native memory which the spell checker for instance uses). Best you can do is to disable word suggestions if this is a recurring problem, then the dictionary won't load and this issue won't occur. A new suggestions algorithm which operates in native memory rather than the Java heap will be implemented in 0.3.15.

The only thing I can do now is to catch the OOM crash maybe, so the keyboard at least stays, it just means that you won't have word suggestions displayed.

**Comment by patrickgold** [comment]
I've renamed this issue as I will address this before stable 0.3.13.

**Comment by heberjeur** [comment]
thanks for your explanations

**Comment by Glitchy-Tozier** [comment]
Oooooh no, OOM's back 😱

**Comment by patrickgold** [comment]
After testing a bit around the temporary fix for this is that word suggestions will only work if there's sufficient memory available to begin with. This will prevent users with weaker phones from having suggestions for now, but this is I think the best solution, as I don't want yet another OOM flood. I've also added this as a note to the Settings Home tab, which is readable without having to scroll down. This restriction will be removed once 0.3.15 suggestions are implemented.

Thanks again for reporting!

**Comment by Glitchy-Tozier** [comment]
> I've also added this as a note to the Settings Home tab, which is readable without having to scroll down. This restriction will be removed once 0.3.15 suggestions are implemented.

Maybe something like "Your phone doesn't have enough memory to use the curren word-suggestions. This will change in 2-3 updates.", similar to the "Keyboard not activated"-message.

I'm thinking this could also be a placeholder for the non-existent suggestions. Maybe that's too aggressive though.

I'm just a little traumatized from the OOM-flood. 😅
