### ISSUE TITLE
Showing suggestions irrespective of the heap size.

### ISSUE THREAD

**Issue by paritosh9199** [florisboard/florisboard#1178]
Hi. I saw this in the changelog of the latest beta release (beta11).

> Word suggestions are now only loading if sufficient memory is available. This restriction will be lifted again in 0.3.15 with the new word suggestion feature.

May I know the reason why this was implemented. 
Is it possible to have text suggestions in spite of having heap memory around 256mb, if not then can a new developer option be added to show suggestions irrespective of the heap size before the 0.3.15 release? 

Thanks in advance

**Comment by Glitchy-Tozier** [comment]
Hi, the explanation can be found in #1176.

tldr: It's only a temporary decision to prevent crashes until ~v0.3.15.

**Comment by paritosh9199** [comment]
Hi @Glitchy-Tozier Any ETA on when 0.3.15 will be released?

**Comment by patrickgold** [comment]
> May I know the reason why this was implemented.

This was implemented because the Java heap size is limited and I want to prevent crashes/freezes when that heap size is too low. The idea of adding a developer override toggle for this is good though, will implement it later today when I tweak some other things around that restriction.

> Any ETA on when 0.3.15 will be released?

Not Glitchy but 0.3.15 has currently no ETA, sorry.

**Comment by paritosh9199** [comment]
> > May I know the reason why this was implemented.
> 
> This was implemented because the Java heap size is limited and I want to prevent crashes/freezes when that heap size is too low. The idea of adding a developer override toggle for this is good though, will implement it later today when I tweak some other things around that restriction.
> 
> > Any ETA on when 0.3.15 will be released?
> 
> Not Glitchy but 0.3.15 has currently no ETA, sorry.

Thanks @patrickgold

**Comment by paritosh9199** [comment]
What are the improvements that are going to be made in 0.3.15?

**Comment by patrickgold** [comment]
> What are the improvements that are going to be made in 0.3.15?

Like also with the already implemented spell checker service which works relatively good, word predictions will be re-written in C++ and use native memory instead of loading into the Java heap, thus I don't need to have this restriction anymore.

**Comment by paritosh9199** [comment]
> > What are the improvements that are going to be made in 0.3.15?
> 
> Like also with the already implemented spell checker service which works relatively good, word predictions will be re-written in C++ and use native memory instead of loading into the Java heap, thus I don't need to have this restriction anymore.

Okay. How is Next word suggestion going to work? I believe this is NYI right now.

**Comment by patrickgold** [comment]
> Okay. How is Next word suggestion going to work? I believe this is NYI right now.

Tbh - I don't know yet. I have a few ideas but no concrete plan yet. As the next version 0.3.14 (after 0.3.13 stable release this week) focuses on completely rewiring the settings and prepare proper extension support, this gives me some time to gain more ideas and come up with a plan for 0.3.15's next word suggestions.

**Comment by patrickgold** [comment]
Above commit adds an override toggle for the restriction, to be found in the advanced settings in the devtools section. Will be available in beta12 shortly.

**Comment by paritosh9199** [comment]
> Above commit adds an override toggle for the restriction, to be found in the advanced settings in the devtools section. Will be available in beta12 shortly.

Awesome! Thanks for the quick support!!
