### ISSUE TITLE
Tweaks for gesture detection when thresholds are set to very fast

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1183]
I have my device set up to hide the keyboard when I swipe down on the keyboard. The swipe down gesture is only detected correctly if I swipe really fast. If I swipe slower, it registers a press on a letter and ignores the gesture.

See video:

https://user-images.githubusercontent.com/50382414/130688602-0de5e788-4d5e-4ca5-8895-b058afa13a37.mp4

**Comment by patrickgold** [comment]
What version are you on? This has been fixed in the beta track a few weeks ago and will be released to stable this week.

**Comment by Donkey-Doug** [comment]
The most recent - 0.3.13-beta12

**Comment by patrickgold** [comment]
Ok then it's a bug in the current code base. Could you do the following please:

- Just to test out set velocity/distance thresholds back to normal
- Fill out the environment info (template attached below)

Thanks in advance!

---

#### Environment information
- FlorisBoard Version:
- Install Source:
- Device:
- Android:

**Comment by Donkey-Doug** [comment]
I found the reason for the swipe problem: if swipe velocity threshold is set fast or very fast, the swipe down gesture becomes difficult to execute.

Environment information

    FlorisBoard Version: 0.3.13-beta12
    Install Source: izzidroid fdroid repo
    Device: Xiaomi mi 9t pro
    Android: 10 (lineageos without google play services)

**Comment by patrickgold** [comment]
> I found the reason for the swipe problem: if swipe velocity threshold is set fast or very fast, the swipe down gesture becomes difficult to execute.

Thanks for trying this out. Does that means gestures work on your device, they were just mis-configured? If so then we can close this issue.

**Comment by patrickgold** [comment]
Ok then it is less a gesture malfunction and more a gesture tweak. Will assign it to the gesture's issue list.

One thing: could it be that you accidentally begin your downwards motion for the gesture within the Smartbar? This could be one clue to why it does not trigger sometimes. Also do left/right/up also behave this strange or is it only down?

**Comment by Donkey-Doug** [comment]
In version 0.3.14-beta05 all gestures work very well. I would not change a single thing.
