### ISSUE TITLE
Glided word appeares after typed word if...

### ISSUE THREAD

**Issue by imDusht** [florisboard/florisboard#1187]
#### Short description
If i gesture a word and really fast keytype next word before gestured word appears keyttyped word appears before gestured word.

#### Steps to reproduce
1. Gesture type any word eg ' What '
2. Right after gesturing the word ( without any delay before it appears) really fast key type ' are '. It should type ' What are ' but what it types is
4. Ar what e (or A what re / Are what )

#### Environment information
- FlorisBoard Version: 0.3.13 beta12
- Install Source: Google PlayStore (but latest apk from github)
- Device: Lenovo VIBE K5 Note
- Android: 6.0

**Comment by patrickgold** [comment]
Using the latest release 0.3.16-beta02, is this bug still possible to reproduce when typing really fast? I cannot really reproduce it when typing realistically, no matter how hard I try.

**Comment by imDusht** [comment]
> Using the latest release 0.3.16-beta02, is this bug still possible to reproduce when typing really fast? I cannot really reproduce it when typing realistically, no matter how hard I try.

I haven't experienced it for a while, this issue is solved.

**Comment by patrickgold** [comment]
Perfect, great to hear! Will close this issue then. Should Glitchy be able to still break it we can re-open this issue if it impacts normal typing :)
