### ISSUE TITLE
glide typing preview not working

### ISSUE THREAD

**Issue by Aman9das** [florisboard/florisboard#1191]
Florisboard version 0.3.13

Gesture typing is on
Show preview during glide typing is on.
Android version is 9
Worked well on 0.3.12

Is it a known issue?

**Comment by patrickgold** [comment]
I can rermember although I always have the clipboard cursor row on during development, then the preview won't show anyways.

**Comment by Aman9das** [comment]
https://github.com/florisboard/florisboard/blob/b15f7f68aef657d1fbd529192e6ca360f4871734/app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/GlideTypingManager.kt#L55

I think something has changed here to cause the issue..

**Comment by patrickgold** [comment]
Thanks for the tip @ Aman9das! It wasn't exactly the line you mentioned, but further down the same file I found this:
https://github.com/florisboard/florisboard/blob/b15f7f68aef657d1fbd529192e6ca360f4871734/app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/GlideTypingManager.kt#L108-L116

Can't work if it is commented out xD. IIRC I commented this out with 0.3.13-beta01, but could be wrong. Anyways, now that I know where to fix the issue I might do the fix in the next few days.

**Comment by opusforlife2** [comment]
@patrickgold Could you please publish an F-Droid release with just this fix? A normal release cycle with several betas would take too long.

In general, maybe throw in some versions that consist only of bug fixes every once in a while?

**Comment by patrickgold** [comment]
@opusforlife2 No because that completely messes up the version milestone that is written (0.3.14 = preferences), I am sorry.

> In general, maybe throw in some versions that consist only of bug fixes every once in a while?

I am very aware of the issue with my current versioning scheme and how I don't really have a way to make a stable track patch release without messing up the major number, so beginning with v0.4.0 (is planned to be the version after 0.3.15) I will change the versioning scheme a bit to allow for such patch releases. See the [roadmap](https://github.com/florisboard/florisboard/blob/master/ROADMAP.md) for this.

**Comment by opusforlife2** [comment]
Sorry, I'm a bit confused... is it not possible to release a v0.3.13.1 as a bug fix version? I've seen plenty of projects do that.

**Comment by patrickgold** [comment]
> Sorry, I'm a bit confused... is it not possible to release a v0.3.13.1 as a bug fix version? I've seen plenty of projects do that.

Technically speaking it doesn't matter what the version string is and you are correct, however this looks weird and adds even more confusion to the already messed up 0.3.x version scheme I currently have. Additionally all FlorisBoard tools are configured to work with X.X.X scheme and I would have to manually create a lot of the release files or re-write the tools, both which I don't want to do just for this release. Like I said, I acknowledge the problem and with 0.4.0 I won't have this problem anymore, as the second number will increase and the third number is the hotfix/patch number.

**Comment by patrickgold** [comment]
As for the issue itself, above commit fixes the bug and 0.3.14-beta01 will contain the fix. Thanks again for spotting this issue!
