### ISSUE TITLE
Abnormal supp gesture

### ISSUE THREAD

**Issue by heberjeur** [florisboard/florisboard#1196]
#### Short description
I want to delete "aaaaa bbbbb" but when I press to supp button it return to the right side and it delete all the characters , in the normal situation it keep "ccccc"
I don't change the default gesture settings

https://user-images.githubusercontent.com/11852634/131206982-48da4588-8b0e-4170-9bff-b14d3d8d42a5.mp4

## Steps to reproduce
1. write something
2. Move the cursor to the right place
3. Long press to delete button

#### Environment information
- FlorisBoard Version: <!--. 0.3.13
- Install Source: <!-- github 
- Device: <!-- samsung a 50 
- Android: 11

**Comment by heberjeur** [comment]
See also what, I want to correct " write" to "Write" but when I press to supp it delete the "e" character

https://user-images.githubusercontent.com/11852634/131207095-d44910c9-9a09-48f7-8f42-3c1466002bdb.mp4

**Comment by Glitchy-Tozier** [comment]
What's a supp?

**Comment by heberjeur** [comment]
![Screenshot_20210828-143514_Firefox](https://user-images.githubusercontent.com/11852634/131219727-6f1023b1-cb68-4188-8f8e-849bbc6c97dc.jpg)

Sorry for my bad english*

**Comment by tsiflimagas** [comment]
Are you still able to reproduce this on version 0.3.14

**Comment by heberjeur** [comment]
> Are you still able to reproduce this on version 0.3.14?
It resolved
