### ISSUE TITLE
Error with hebrew keyboard

### ISSUE THREAD

**Issue by mccakestd** [florisboard/florisboard#1197]
#### Short description
Hebrew letters inverted in 2nd and 3rd line

#### Steps to reproduce
1. Select hebrew keyboard
2. Click on any letter in 2nd or 3rd line (for exemple - ש)
3. See error (in my exemple, tap to ש gave you ף)

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Device: Redmi 9S
- Android: 11, Corvus OS
[Exemple of error in video](https://youtube.com/shorts/Q4oyfLs24TU?feature=share)

**Comment by patrickgold** [comment]
Thanks for your bug report! This issue has been fixed in 0.3.13, feel free to reopen if you can still reproduce it in the new release.
