### ISSUE TITLE
Adding clipboard manager option on the smart bar

### ISSUE THREAD

**Issue by TSnatch72** [florisboard/florisboard#1199]
curently, the only option i have seen to spawn the clipboard manager is to select a text, which opens a series of options like, home, end, cut, paste, copy and the clipboard manager on the suggestion part of the top bar, but i think it would make it way more usable if there were o a button that opens the clipboard manager on the smart bar alongside the one handed mode, undo and redo buttons like there is on gboard

### Here's how it looks on gboard compared to the current smartbar
![IMG_20210828_140846](https://user-images.githubusercontent.com/88058182/131228916-e1fa7fa4-4e36-4cec-a227-9b349f6e0562.jpg)

![IMG_20210828_141335](https://user-images.githubusercontent.com/88058182/131229008-18578cb2-6a94-40de-8a59-f4e635fdd81b.jpg)

**Comment by patrickgold** [comment]
Will be available in the upcoming 0.3.14-beta07 release.
