### ISSUE TITLE
wrong question mark in arabic layout

### ISSUE THREAD

**Issue by itskareem** [florisboard/florisboard#120]
In the arabic layout there's "?" which is wrong because the arabic is a rtl language, so it should be  "؟"

**Environment information**
- FlorisBoard Version: 0.3.2
- Install Source: IzzyOnDroid
- Device: Condor plume L1
- Android version, ROM: 7.0, Stock

**Steps to reproduce**
1. Go to keyboard on the Arabic layout
2. Click on '?123'

**Comment by patrickgold** [comment]
Thanks for reporting this issue!

This is less a bug than a missing implementation for subtype specific symbol layouts. I will look into this and add it to my todo list!

**Comment by itskarim** [comment]
@patrickgold thank you, i just discovered the keyboard today and it's way too better. If you can please make the emojis better in the viewing like what it is in the Google board or should i make a bug report.

**Comment by patrickgold** [comment]
@itskarim I will definitely rework emojis with v0.5.0, it is already on the roadmap.

**Comment by patrickgold** [comment]
Above PR finally adds the ability to define subtype-specific layouts, with this I added a preset for Arabic and Persian, which also adds the rtl question mark. Will be released with v0.3.10-beta05!
