### ISSUE TITLE
Unicode (?) Error for 'İ'

### ISSUE THREAD

**Issue by CuvlBoi** [florisboard/florisboard#1200]
#### Short description
False capital i for Turkish-Q keyboard layout. Eventhough preview on keybord right, outcome isn't.

Little note: Unlike English we have ı and İ.  Its a little bit confusing when you type without turkish letters. 

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Device: Huawei p smart
- Android: 10

**Comment by patrickgold** [comment]
This issue is well known and has been fixed in 0.3.13.
