### ISSUE TITLE
Diacritic letters appear with two dotted rings

### ISSUE THREAD

**Issue by Huy-Ngo** [florisboard/florisboard#1204]
#### Short description
Letters that appear as diacritics (ones that occupy 1 space in monospace fonts), such as `◌̃` would appear with two rings (`◌◌̃`) on the keyboard.  Meanwhile, independent letters like `◌ⁿ` (occupying 2 spaces in monospace fonts) appear with one ring.

#### Steps to reproduce
1. Add IPA keyboard
2. Switch to IPA keyboard
3. Affected characters (has two rings): appear in symbol keyboards
4. Unaffected symbols (has one ring): appear when holding keys: n, g, h , j, w, t, x

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Device: Xiaomi Redmi Note 7
- Android: 10

#### Screenshots

![IMG_20210829_202219](https://user-images.githubusercontent.com/19296926/131251861-e2221968-c6f8-493f-91c2-da42db7e5204.jpg)

**Comment by Huy-Ngo** [comment]
I didn't realize this bug earlier because I've been using debug version all this time :sweat_smile: 

I suppose this is because the diacritics are dependent and it is rendered with a ring by Android already, so you can simply remove the ring. I can't build the app now for testing though: it appears my CMake version is incompatible.

**Comment by patrickgold** [comment]
Thanks for your bug report!

> I didn't realize this bug earlier because I've been using debug version all this time sweat_smile

This is because debug is much further ahead than 0.3.12 and contained a fix for this bug. The newest release, 0.3.13 does also have this fix. Closing this issue to keep the list of issues clean!
