### ISSUE TITLE
Swipe gesture in the latest release is glitchy

### ISSUE THREAD

**Issue by paritosh9199** [florisboard/florisboard#1207]
The swipe gesture in the latest stable release is very glitchy. It just freezes when I stop moving while fingers while using swipe gestures. This was not the case with beta 12 release. 

Please revert the swipe gestures animation changes. It was really good in beta 12.

https://user-images.githubusercontent.com/27616102/131264286-e18d22eb-00aa-4621-9c1e-9fd66d49e5df.mp4

**Comment by paritosh9199** [comment]
This it's how it is in beta 12

https://user-images.githubusercontent.com/27616102/131264349-58377f28-8a92-490e-8a65-0f60de59ede9.mp4

**Comment by Aman9das** [comment]
I guess you increased the glide trail duration a lot..

**Comment by paritosh9199** [comment]
> I guess you increased the glide trail duration a lot..

Everything is set to the default value.

**Comment by patrickgold** [comment]
The thing is, I haven't changed a thing for glide typing between beta12 and stable 0.3.13. I guess this is the remainings of some caching bug still persisting from 0.3.12. Could you please try to force kill FlorisBoard, clear the cache and then reopen FlorisBoard to see if this bug is gone?

**Comment by paritosh9199** [comment]
@patrickgold Clearing the storage and cache fixed it!!

**Comment by patrickgold** [comment]
Ah, then some bugged behavior from 0.3.12 still persisted its way through to 0.3.13, this can sometimes happen. As this issue is now resolved, can we close it?

**Comment by paritosh9199** [comment]
Yeah we can close this! Do add this note somewhere to clear cache after updating if some issues pop up.
