### ISSUE TITLE
Add option to specify which theme attributes are affected by adaptive themes

### ISSUE THREAD

**Issue by patrickgold** [florisboard/florisboard#1216]
### Discussed in https://github.com/florisboard/florisboard/discussions/1211

<div type='discussions-op-text'>

<sup>Originally posted by **imDusht** August 30, 2021</sup>
Hi Dev, right now adapt color to app theme option changes keyboard : background and key : background color, i was wondering if it could be possible to implement that we can choose which parts of keyboard ui adapts to app color, like implement an option which lists keyboard : background, key : foreground (currently it doesn't changes forever white), key : background parts and we can choose one or multiple options between them.</div>

**Comment by imDusht** [comment]
I'm excited for this one, thank you.

**Comment by AKDub** [comment]
Was going to suggest this for just the "Enter" key as a nice subtle theme change. Good idea having it more customisable.

**Comment by patrickgold** [comment]
This feature is not supported by FlorisBoard anymore, thus I am closing this issue as not-planned.
