### ISSUE TITLE
Suggestions non functional

### ISSUE THREAD

**Issue by VA1DER** [florisboard/florisboard#1218]
#### Short description
Word suggestions non functional in new release 0.3.13

#### Steps to reproduce
1. Go to configuration
2. Enable  display suggestions
3. Suggestions don't display

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by nicktyke** [comment]
I'm getting suggestions from touch  typing but not gesture typing. FWIW the default word chosen by gesture typing does seem more accurate
Android 10 fboard 0.3.13 stable

**Comment by gsteinLTU** [comment]
Same here on Pixel 4a, both on suggestions not showing and being better for glide typing than before.

**Comment by azizLIGHT** [comment]
My touch typing suggestions stopped working after updating to 0.3.13 in addition to gesture suggestions. I brought back touch typing suggestions by overriding min heap size restriction for word suggestions from the advanced settings. 

Version: 0.3.13
Device: Google Pixel 3a
Android: 10 Stock

Heap mem
Used: 89-94 MB
Max: 192 MB
Avail: 98-102 MB

If i gesture type, press space, and backspace, I can see suggestions for the gesture typed word, but that seems to be touch type suggestions/corrections

Using google spell checker or florisboard spell checker (with mozilla's english_united_states_dictionary-78.0.xpi) doesn't seem to affect touch typing or gesture based typing suggestions, even if spell checking is turned off from system settings

**Comment by vulpes2** [comment]
Having the same issue here except suggestions are completely nonfunctional for both touch typing and glide typing.

Install Source: F-Droid
Version: 0.3.13
Android: 11, LineageOS

**Comment by Glitchy-Tozier** [comment]
Thank you all for reporting this issue. The reason for the suggestions disappearing is that they temporarily had to be disabled on devices with too little memory to prevent crashes.

In version v0.3.15 the word-suggestions will be returning, better than ever.

---

@patrickgold Maybe this should be pinned as well.

**Comment by patrickgold** [comment]
> @ patrickgold Maybe this should be pinned as well.

I agree pinning a suggestions not functional issue should be done. This issue's initial comment does provide little detail though, so either we modify the initial issue text or open a collection issue for suggestions.

**Comment by tsiflimagas** [comment]
Since there's a pinned issue for this, and the new suggestions mechanism is arranged to be implemented in 0.4.0 milestone, let's close this.
