### ISSUE TITLE
By setting 'Space bar' gestures to switch the subtype language, the globe key becomes redundant

### ISSUE THREAD

**Issue by pleiozc** [florisboard/florisboard#1222]
Wouldn't be good to allow to remap globe key with '?' , '/' or any other custom key?

**Comment by Aman9das** [comment]
settings > keyboard > keys > show utility key > off..
?/ can be accessed by long pressing [.] key...

**Comment by patrickgold** [comment]
I agree that having both a space bar gesture set to language switch and a language switch button may be redundant, although in the default configuration this is not set to be this way. The best thing you can do atm is to set the utility key either to off or to emojis. Customizing this key would be part of runtime layout customization, which is planned to be implemented in the future.

Closing this issue as this specific issue has no real fix for it, and layout customization is tracked in a separate issue.
