### ISSUE TITLE
Delete clipboard items with a swipe (like Gboard)

### ISSUE THREAD

**Issue by imDusht** [florisboard/florisboard#1223]
Currently to delete a clipboard item log press on it and than delete, to delete one item it's fine but if we have to delete many at a same time it isn't convenient, It would be better if we can swipe them left or right to delete like Gboard.

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your feature request!

This has already been proposed in #1179. I will close this issue as a duplicate.
If you have any further comments regarding this proposal, please mention them there. :)

**Comment by imDusht** [comment]
>This has already been proposed in #1179. I will close this issue as a duplicate.

OKAy, thanks.

>If you have any further comments regarding this proposal, please mention them there. :)

Nothing but i'm going to open next suggestion (•‿•)
