### ISSUE TITLE
Increasing the font size of emojis

### ISSUE THREAD

**Issue by kareeeeeeeem** [florisboard/florisboard#123]
Looks like the emojis are small comparing to other keyboards
![USER_SCOPED_TEMP_DATA_orca-image--121858432](https://user-images.githubusercontent.com/52888633/103579375-810dcd80-4ed8-11eb-89c4-0ebddff3b044.jpeg)

**Comment by patrickgold** [comment]
Thanks for your suggestion! I think this is less a bug than an improvement suggestion, as the emoji size and spacing is intended to be this way. I can increase the font size of the emojis a bit (which will reduce spacing between emojis), but I think 8 - 9 emojis per row is a good number to display many emojis at once. For instance OpenBoard has somewhat big emojis which just looks strange, while GBoard has a bigger emoji size than FlorisBoard but the same underlying grid.

Note though that I plan to completely rework the media input part with v0.5.0, so maybe then the emoji view is more customizable an allows for custom grid sizes.
