### ISSUE TITLE
Florisboard dissapears after deleting words

### ISSUE THREAD

**Issue by nestlecrunchkid** [florisboard/florisboard#1231]
#### Short description
After deleting words using gestures, florisboard go's down while typing (it also happens while doing other stuff, but mostly while deleting words)

#### Steps to reproduce
1. Type something
2. Delete using gestures
3. Florisboard go's down (doesnt happen every single time)

#### Environment information
- FlorisBoard Version: 0.0.13 beta 12
- Install Source: F-Droid
- Device: Samsung galaxy a30s
- Android: 11, one ui

Heres a video of it happening: https://bun.filedit.ch/YtucRNgfTqVXXxizwWH.mp4

**Comment by Glitchy-Tozier** [comment]
Hi!
1. Does this bug still occur?
2. Did some "Florisboard Crashed" pop-up appear in that dropdown-menu at the top of your screen?

**Comment by tsiflimagas** [comment]
- The demo video can't be played.
- This is probably one of the crashes occuring in delete gestures, which have been fixed.
- The issue has been stale for too long.
Closing thus.
