### ISSUE TITLE
floris board crashes in mac book pro m1 when running a project

### ISSUE THREAD

**Issue by MuhammadSikandarali2019** [florisboard/florisboard#1238]
Build command failed.
Error while executing process /Users/sikandar/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/sikandar/AndroidStudioProjects/florisboard-master/app/.cxx/Debug/3s591524/arm64-v8a florisboard-native}
ninja: Entering directory `/Users/sikandar/AndroidStudioProjects/florisboard-master/app/.cxx/Debug/3s591524/arm64-v8a'

ninja: error: '/Users/sikandar/AndroidStudioProjects/florisboard-master/app/src/main/icu4c/prebuilt/jniLibs/arm64-v8a/libicuuc.a', needed by '/Users/sikandar/AndroidStudioProjects/florisboard-master/app/build/intermediates/cxx/Debug/3s591524/obj/arm64-v8a/libflorisboard-native.so', missing and no known rule to make it

**Comment by patrickgold** [comment]
You need to make sure to check out all git submodules, else the project won't build. Execute `git submodule update --init --recursive` and after that the project should build fine.

**Comment by MuhammadSikandarali2019** [comment]
@patrickgold where to write these commands? **git submodule update --init --recursive**

**Comment by patrickgold** [comment]
When you are in the base directory of the cloned FlorisBoard repo, issue the command in the terminal.
