### ISSUE TITLE
Clipboard history clears when switching between keyboards

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#1239]
I have setting 'clear old items' disabled.
![](https://i.imgur.com/34Ut6Fc.jpg)
Yet, in certain cases like when switching between keyboards and phone reset or battery dying,
history is cleard on return to florisboard.
At least when switching keyboards history should be retained, since it uses internal history.

**Comment by patrickgold** [comment]
This issue should be resolved with beta07 release, as the items are now properly stored in the app's internal encrypted storage.
