### ISSUE TITLE
Capitalize first word of new sentence while gesture typing without manually entering space

### ISSUE THREAD

**Issue by daveriedstra** [florisboard/florisboard#1240]
When gesture-typing full sentences, spaces are automatically inserted between words. With auto-capitalization on, after inserting a period at the end of a sentence, the first word of the next sentence is not capitalized _unless_ a space is manually entered after the period. This feature request is for the auto-capitalization setting to capitalize this word, ie, without needing to manually insert the space.

(To look a little closer at the UX: this little change addresses a slightly larger perceived friction. This is possibly the only context in which a space needs to manually be entered while gesture typing, so it stands out. The space is unnecessary as a space, since the gesture typing will insert it anyway, so it feels like redundant work. The space _is_ necessary to capitalize the word, which confuses the role of the space character with shift.)

Similar to #1013, #335

Thanks for the great app!

**Comment by patrickgold** [comment]
#1913 or 0.4.0-alpha1 tomorrow will release auto-spacing after punctuation as an experimental feature. As this also solves your issue, I will close it. You can try auto-spacing out and give feedback about it in #1935.
