### ISSUE TITLE
Suggestions are not appearing in latest version f droid

### ISSUE THREAD

**Issue by sultanahamer** [florisboard/florisboard#1243]
Hi, i have been liking Floris keyboard for the fact that it supports glide typing. With recent version i am not able to see suggestions on keyboard when i glide. I had to downgrade

**Comment by vulpes2** [comment]
Having the same problem as well. Looks like it's the same issue as #1218?

**Comment by Glitchy-Tozier** [comment]
Yeah, let's close this issue and continue in #1218!
