### ISSUE TITLE
Manually modifying capitalization

### ISSUE THREAD

**Issue by echofoxtrott** [florisboard/florisboard#1245]
Feature for manually changing/modifying capitalisation would be great, in addition to auto-capitalisation and/or word suggestions or rather for correcting those.

Suggestion: Use shift / caps lock key while word is selected or better while cursor is located between a word's letters. Tap shift / caps lock key to cycle through "first letter uppercase -> first letter lowercase" and optional add/enable "all letters uppercase".

Similar/addition to [#419](https://github.com/florisboard/florisboard/issues/419)

Thanks for the great app and your dedication!

**Comment by tsiflimagas** [comment]
Thank you for your suggestion! This has already been suggested in #759.
