### ISSUE TITLE
Spacebar switches to full keyboard in number-only fields

### ISSUE THREAD

**Issue by ElishaAz** [florisboard/florisboard#1248]
#### Short description
When "Space bar switches back to character layout" is enabled, spacebar switches to full keyboard in number-only fields .

This is unwanted, as only numbers (and somtimes a few symbols and space) should be entered.

#### Steps to reproduce
1. Enable "Space bar switches back to character layout"
2. Open a number-only field (e.g. a phone number field).
3. Press space.
4. The keyboard switches to the full layout.

#### Environment information
- FlorisBoard Version: v0.3.13
- Install Source: F-Droid
- Device: Redmi Note 8 (ginkgo)
- Android: 11, crDroid 7.9

**Comment by patrickgold** [comment]
Thanks for your bug report! I just tried it out and was able to fully re-produce this bug. Will assign it to the keyboard list issues.

**Comment by patrickgold** [comment]
Above commit fixes the described issue, additionally also for phone and phone2, where this bug was also present. Thanks again for reporting this bug!
