### ISSUE TITLE
Clipboard contents on lock screen

### ISSUE THREAD

**Issue by imDusht** [florisboard/florisboard#1250]
#### Short description
On lockscreen smartbar is disabled (so no clipboard) but other methods to access clipboard like long pressing enter button works but they shouldn't. There is a high chance that clipboard contains personal & sensitive information  (includes pinned items) 
It's a privacy scare for me (sensitive content :p ) and i think it's a priority @patrickgold

#### Environment information
- FlorisBoard Version: v0.3.13-beta12
- Install Source: Google PlayStore
- Device: Lenovo K5 Note
- Android: 6.0, Stock

**Comment by patrickgold** [comment]
What exactly do you mean with lockscreen? The one on device boot (with SIM input etc) or the one which you use to unlock your phone in daily use?

**Comment by bowmasters** [comment]
FWIW, on my device there's only one android lock screen (the one you can configure under Settings > Security > Screen Lock), and you cant  use 3rd party keyboards right after device boot until you've unlocked the device. 

In any case, I can confirm what @imDusht has reported. Steps to reproduce:

- set florisboard as default input method
- enable clipboard history
- configure a gesture to open clipboard history (I used long press space bar)
- copy some text
- lock the screen (press power button. make sure password/pin required for unlock)
- turn on the screen and swipe to unlock (Florisboard will popup for password entry, but don't enter password )
- perform the gesture to bring up clipboard history
- observe that your clipboard  history and any pinned items are available for anyone to see without even needing to unlock the device.

I agree, this is a significant flaw in the security of this app, and the privacy implications should make this a high priority. 

I've also noticed occasionally having access to the smart bar from the lock screen, but I can't reproduce this reliably.

For now, I'm disabling florisboard as primary input method. Disabling clipboard history presumably would mitigate this, but I'd rather play it safe until we know for sure the cause of this issue and can verify no other sensitive data can be leaked elsewhere.

**Comment by imDusht** [comment]
> What exactly do you mean with lockscreen? The one on device boot (with SIM input etc) or the one which you use to unlock your phone in daily use?

DAily use lock screen @patrickgold 

@bowmasters has provided steps to reproduce and ( some concerns too :p )

> For now, I'm disabling florisboard as primary input method

I'm using tasker for this (screen locked then gboard but when unlocked whatever i was using before lock)
And for my device once any keyboard is set as default it doesn't change to stock even after 1st boot.

**Comment by patrickgold** [comment]
In the new keyboard UI which will be released tomorrow in beta07 the clipboard history will always be accessible. As I agree with your concerns, that this is a concerning privacy issue, I show this UI in the clipboard history (regardless if enabled or not):

![image](https://user-images.githubusercontent.com/19412843/145688677-62ebc3a3-9944-408e-a994-ce7c6e21c6a3.png)

Note that this only works if you have a lockscreen (PIN, password, lock pattern, ...) set in your system, but without a lockscreen your device has a much bigger security issue anyways.

Once the device is unlocked, the clipboard history will work as normal. I will include this in tomorrow's beta07 release, should there be any need to add additional functionality in this regard I am of course open for discussion.
