### ISSUE TITLE
RTL Comma

### ISSUE THREAD

**Issue by mortezae** [florisboard/florisboard#1258]
The rtl comma (،) has been removed in v3.0.13 . Please give it back to us, Thanks.

**Comment by patrickgold** [comment]
Knowingly I haven't removed it. In which layout and where exactly was the RTL comma?

**Comment by reg3xp** [comment]
I can see RTL comma in v3.0.13
Maybe it's because you're typing in a URL box like a browser.

**Comment by patrickgold** [comment]
Ah that's what OP means. That behavior is there since ages and only in URL bars or email fields.

**Comment by mortezae** [comment]
It's strange. I upgraded it again, and I see the Persian/Arabic comma at it's place. I really don't know what was the problem, And I can't reproduce it. Yes, Maybe the URL bar was the case. So this issue should get closed. Thank you
