### ISSUE TITLE
Dark mode glitch on following system

### ISSUE THREAD

**Issue by reg3xp** [florisboard/florisboard#1260]
#### Short description
FlorisBoard shows a glitch upon changing to the night theme (white keys) when following the system.
In order to fix it I have to do a force stop and launch it again.

![image](https://user-images.githubusercontent.com/77643465/133492962-ca76f423-1f7f-4023-9037-aba1f6dbe4da.jpg)

#### Environment information
- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Device: Samsung S10
- Android: 11

**Comment by patrickgold** [comment]
Thanks for your bug report! This is related to #1139 and #274, both having issues with the theme manager. As this bug is tracked in those two issues I will close this one, to keep the list of issues a bit cleaner.
