### ISSUE TITLE
no colour choice for emojis

### ISSUE THREAD

**Issue by EzekealI** [florisboard/florisboard#1264]
Hi, I'm having an issue with the emojis, if I long press on for example the thumbs up emoji I am not able to choose from the different coloured options because the menu for it opens only for a second before closing and not doing anything. 
I'm on a Huawei P20 if thats any help.

**Comment by GoRaN909** [comment]
This issues is duplicate of #1047

**Comment by Glitchy-Tozier** [comment]
Thanks to @GoRaN909 for pointing out the duplicate, please continue further discussion in the mentioned issue. :)
