### ISSUE TITLE
Preserve capitalization after clicking on suggested word.

### ISSUE THREAD

**Issue by Khilseith** [florisboard/florisboard#1265]
When clicking a suggestion it changes the whole word to lowercase. It would be great if it preserved at least the first character's capitalization.

**Comment by patrickgold** [comment]
Thanks for your suggestion! Word suggestions currently are buggy as hell and will be replaced in 0.3.15. The capitalization issue is one of those things which will be addressed, will close this isse as it is already tracked in #653
