### ISSUE TITLE
vibration duration twice in settings

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1272]
The vibration duration is shown twice in settings:

![Screenshot_20210920-190030_FlorisBoard_Beta](https://user-images.githubusercontent.com/50382414/134043683-59450506-754a-4ae5-b45c-223b00bc086d.png)

**Comment by Glitchy-Tozier** [comment]
Very weird!

Could you please add your app-version to the issue?  :)

**Comment by patrickgold** [comment]
Thanks for spotting this! This is a classic copy-paste error. The backend is correctly separated in duration and strength, while the UI string was not updated when I copy-pasted the strength preference. Will address this in the next beta.
