### ISSUE TITLE
dedicated precise selection button(highlight texts and letters)

### ISSUE THREAD

**Issue by OilSubjectLoss7** [florisboard/florisboard#1284]
That can be adjusted or controlled by the gesture arrow via space bar or the arrow in the toolbar.
 The default highlighting is working(holding the text down or double clicking it) but if i try to use the arrow gesture(spacebar) or the arrow keys in the tool bar, the highlight color(blue) always dissappear by itself.

**Comment by tsiflimagas** [comment]
I'm not sure if I got your issue correctly, but it seems that what you do is first select text in the way regular way, and then try to resize the selection just by using the arrows or the space bar. If that's so, you have to use the these keys in conjunction with the caps lock to go into text selection mode.

**Comment by OilSubjectLoss7** [comment]
Yrrrrr gtr,rfgg trergy
