### ISSUE TITLE
three delete key precise gesture feature is always bugging out randomly

### ISSUE THREAD

**Issue by OilSubjectLoss7** [florisboard/florisboard#1285]
I had to like initiate a key input first once or more before it could work like inputting keys a-z0-9 or a space then the backspace/delete keys precise gesture would start working again. It happens randomly

My settings are;

Delete key swipe left: Delete characters precisely
Swipe velocity threshold: Normal
Swipe distance threshold: Normal

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for taking the time to write this report!

Could you please fill in all of the bug-template?
Device, app version, and so on are very important in fixing your issue.

**Comment by patrickgold** [comment]
Closing this issue as it is stale. If it is still reproducible in the latest version 0.3.15-rc01 we can ofc reopen it.
