### ISSUE TITLE
too small language selector size 

### ISSUE THREAD

**Issue by heberjeur** [florisboard/florisboard#129]
I changed the keyboard height to 150% in disposition 

![Screenshot_20210108-115302_Finder](https://user-images.githubusercontent.com/11852634/104007802-ccf69600-51a8-11eb-8704-26e1111a2ec4.jpg)

**Environment information**
- FlorisBoard Version:  0.3.2
- Install Source: fdroid
- Device: samsung a 50
- Android version, ROM:  android 10

**Steps to reproduce**
1. Go to setting floriskeyboard
2. Click on keyboard
3. Scroll down to disposition,keyboard height to 150%
4. See error : too small icon of the language changer

**Comment by patrickgold** [comment]
This shouldn't normally happen, I will try to fix this. Thanks for the report!

**Comment by patrickgold** [comment]
Commit 6607ad17390316db313970c319f3a8a9383721da fixes the language selector size. Will be released in the next beta version.
