### ISSUE TITLE
Vibration strengh incorrect unit (ms)

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1291]
Vibratiomn strengh is measured in ms.

**Comment by patrickgold** [comment]
What would be the better unit, percentage? Also this is not a bug, but a feature improvement, will re-label it.

**Comment by Donkey-Doug** [comment]
Since there is no clear scale, I would simply apply a scale from 0 (or 1) to 100. Since there is no obvious unit, I would simply use %.

You could decide to start from 1%, because 0% means the feature is turned off.

**Comment by patrickgold** [comment]
Above commit fixes the vibration strength unit/min value. WIll be available in beta04, thanks for your feedback!

**Comment by patrickgold** [comment]
You don't need to manually close this issue, as I have linked it to the relevant PR, so GitHub does this automatically once merged. Does not matter in this case though, just so you know :)

**Comment by Donkey-Doug** [comment]
Thanks for letting me know.
