### ISSUE TITLE
[Beta] Welcome screen shows up multiple times

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1292]
#### Short description
1. Even though I had used the beta before, after updating, the welcome-screen shoed up.
2. It kept showing up, even though I always clicked the finish-button.
3. When I tried recording the bug, it stopped occuring. Now I can't reproduce it.

#### Environment information
- FlorisBoard Version: 0.3.14-beta03 (59)
- Install Source: <Google PlayStore/
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
> Even though I had used the beta before, after updating, the welcome-screen shoed up.

Once this is completely fine, because the isImeSetUp flag has also been reset with the move to the new UI.

> It kept showing up, even though I always clicked the finish-button.

That's strange, possibly related to your another issue with the "Welcome to %s". If you try to reinstall the beta completely, could you then reproduce this issue?

> When I tried recording the bug, it stopped occuring. Now I can't reproduce it.

Schrödinger's setup screen? xD

**Comment by Glitchy-Tozier** [comment]
> Schrödinger's setup screen? xD

Apparently xD

> If you try to reinstall the beta completely, could you then reproduce this issue?

I tried deleting the memory and/or uninstalling the app a couple of times, but i couldn't get it to reoccur. Should we close the issue?

**Comment by patrickgold** [comment]
> Should we close the issue?

Yes, because I think this happened indeed because of the upgrade caching error, in which case the bug is that the cache does not get cleared.
