### ISSUE TITLE
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1295]
#### Short description

I reinstalled FlorisBoard a few times to test something and in one of the iterations I got this crash when I tapped on the button of the second step. The thing is I can't reproduce it, it seemed very random. I hope the crash log is more informative than my description.

#### Steps to reproduce
1. Go to setup screen
2. Click on second step
3. See crash

#### Environment information
- FlorisBoard Version: 0.3.14-beta03 (59)
- Device: Xiaomi Redmi Note 8
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1632826153862.stacktrace</summary>

```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at dev.patrickgold.florisboard.ime.text.layout.LayoutManager$loadLayoutAsync$1.invokeSuspend(LayoutManager.kt:85)@3e97ab6]){Completed}@59ce724. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.internal.DispatchedContinuation
	at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:108)
	at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	... 4 more

```
</details>

**Comment by tsiflimagas** [comment]
Hmm, just managed to make it occur again, immediately after completing the second step.

**Comment by patrickgold** [comment]
I have experienced this crash too, it has nothing to do with the setup screen however. It seems to be a bug within the Kotlin coroutine library which affects FlorisBoard everywhere where coroutines are used.

At this time I do not really know how to fix this bug, either a newer Kotlin version will fix it or I will find a workaround.

**Comment by tsiflimagas** [comment]
Oh, this sounds awkward for devs.
Should I close this issue as duplicate then?

**Comment by patrickgold** [comment]
No I think you are the only one who filled in the bug report form for this crash, so I will close all other issues with the exact same crash and reference to this one. Makes it at least more easy to reference in the future.

**Comment by patrickgold** [comment]
I just noticed that I do not use the latest Kotlin coroutine library and see what the https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.5.1 changelog has in it:

> Fixed a spurious ClassCastException in releaseInterceptedContinuation and IllegalStateException from tryReleaseClaimedContinuation 

This smells like it is the/a source of this mysterious crash. If possible, could you try out the debug build of #1290 and check if you can reproduce this crash? I had this crash happen too but only very very infrequently and only if my device slept for a while.

**Comment by tsiflimagas** [comment]
I think I found an area where I can get it to happen relatively often (setup screen), so I'll try to test repeatedly there, to ensure (at least as much as I can) that this is fixed.
About dependency updates, would dependabot be helpful for this project? Perhaps you've already considered it and it would be more of a hassle than help, but I mention it in case you haven't.

**Comment by tsiflimagas** [comment]
Well, I made over forty attempts and got no crashes. It feels like it's fixed. Do you think that's enough to close the issue or does it need further trial from other users?

**Comment by patrickgold** [comment]
Thanks for testing it out! I will attach this issue to the PR, which means this issue will auto-close if I get no report until I release beta04. This is the best way to handle this case I think.

**Comment by patrickgold** [comment]
As for dependabot:

I agree that I might should put in an automatic dependency version updater, but I do not really like the fact that dependabot uses PR's for this. Will see if I can find local alternatives for this.
