### ISSUE TITLE
Importing themes doesnt work

### ISSUE THREAD

**Issue by GL513** [florisboard/florisboard#1299]
#### Short description
Importing themes doesnt work when importing from json that was previously exported, even on same version.

#### Steps to reproduce
1. Go to " import theme"
2. Import .json file (theme file)
3. Snackbar says "imported successfully"
4. Name-author-source all say invalid
5. When exiting theme manager, the keyboard theme tab, under whatever theme mode (light/dark) will say "!! Invalid ref!!"

#### Environment information
- FlorisBoard Version:  0.3.13
- Install Source: Github
- Device: Samsung Galaxy a51 5g
- Android: oneui 3.x

**Comment by GL513** [comment]
Cross-importing doesnt work. Direct import (day to day, not night to day) works. Changing the "isnight" boolean in the backup json solves the problem. Maybe make it in future releases that you can cross import.

**Comment by patrickgold** [comment]
Thanks for your issue!

The imported successfully snackbar does not lie, the theme was indeed successfully imported. If you import a night theme through the day UI (or vice versa), the theme will not appear in the list however, but in the theme manager for the mode the "isNight" boolean says so. As the theme part is the current main objective for development in the next days, expect this to change and be fixed though.
