### ISSUE TITLE
incomplete Arabic letters

### ISSUE THREAD

**Issue by heberjeur** [florisboard/florisboard#130]
**Environment information**
- FlorisBoard Version: 0.3.2
- Install Source: fdroid
- Device: Samsung a50
- Android version, ROM: android 10

**Steps to reproduce**
1. Go to florisboard
2. Click on keyboard
3. Scroll down to disposition, change the keyboard height to 150%
4. See error: 20% of the character was disappeared of, ص،ض،ف،ش،س،ظ

![Screenshot_20210108-120815_Finder](https://user-images.githubusercontent.com/11852634/104009126-cec15900-51aa-11eb-9696-2ef7120950db.jpg)

**Comment by rancidfrog** [comment]
Also, question mark should be available, too '؟'

**Comment by patrickgold** [comment]
Thanks for your bug report! I don't know exactly how to fix this, as I somewhat rely on the Android system to tell me if the character fits in the specified rectangle of the key. I would suggest setting the key font size multiplier to 80% to counter this issue. I will let this issue open to see if I can improve this algorithm for arabic letters. For the wrong question mark, see #120.

**Comment by patrickgold** [comment]
The Arabic question mark is already available, as for the cut off you can decrease the font-size if they shouldn't fit. Closing this issue though.
