### ISSUE TITLE
Design-Tab Loads for a Long Time

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#131]
"Long time" not as in "hours" but a long time compared to the other tabs in the FlorisBoard settings.
1 second, which is significantly longer than the other tabs.
**Environment information**
- FlorisBoard Version: 0.3.2
- Install Source: F-Droid
- Device: Samsung Galaxy S9 (a pretty fast device)
- Android version, ROM: 10

**Steps to reproduce**
1. Go to the app's settings
2. Click on 'design' on the bottom bar
3. See error

**Comment by Glitchy-Tozier** [comment]
Also, just found this app - it looks amazing!
Maybe there'll finally be a really good open source keyboard-app!

**Comment by patrickgold** [comment]
Thanks for the feedback and the bug report! I am currently reworking the complete Theme engine, this also completely affects the Theme tab in the Settings. I hope to be able to push a good first look of the new theme settings and the engine tomorrow, where this issue should also be resolved. I will ping you when I create the PR, so you can have a look on the changes when I upload them.

**Comment by Glitchy-Tozier** [comment]
I'm not quite comfortable downloading and installing something that hasn't beed validated by Fdroid/Google Play, i hope you understand!

Thank you for the suggestion though, if you want i'll update you as soon as possible. :)

**Comment by patrickgold** [comment]
Yeah if it is more comfortable for you just give me feedback about the new theme rework after it has been released to GPlay/F-Droid, I don't have a problem with that! :)
