### ISSUE TITLE
Adapt colours to app not working after restart

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#1313]
#### Short description
Having adapt colours to app enabled and then restarting your device makes the keyboard not adapt to the app until you change to another keyboard then back

#### Steps to reproduce
1. Go to theme settings
2. Enable adapt colours to app
3. Restart the app
4. Open the keyboard on any app
5. See the keyboard using the deafult theme

#### Environment information
- FlorisBoard Version: 0.3.14-beta03
- Install Source: F-Droid
- Device: Redmi Note 9 Pro
- Android: 11, MIUI

**Comment by patrickgold** [comment]
This feature is not supported by FlorisBoard anymore, thus I am closing this issue as not-planned.
