### ISSUE TITLE
Show Clipboard UI on SmartBar when Word Suggestions are enabled

### ISSUE THREAD

**Issue by sabzo** [florisboard/florisboard#1336]
Currently when word suggestion is disabled, the "clipboard" buttons show. However when the word suggestion is disabled, the clipboard UI shows when a word is selected. A user therefore cannot  open up the clilpboard paste functionality when the word suggestions are enabled, unless they first select a word.

A better UI/UX experience would be such that unless a user is typing, by default enable the clipboard to show. If word suggestions is enabled AND user is typing, show word suggestions.

**Comment by patrickgold** [comment]
Will be fixed in the upcoming 0.3.14-beta07 release.
