### ISSUE TITLE
Emoji Skintones cannot be chosen for emojis on second right of the screen

### ISSUE THREAD

**Issue by sabzo** [florisboard/florisboard#1337]
#### Short description
The emoji buttons on the second right half of the panel do not show properly

#### Steps to reproduce
1. Go to  Emojis
2. Click on the "Peoples" category
3. Choose any emoji on the right side of the screen
4. Notice that other skin tones cannot be selected besides the yellow one

![emoji_skin_tone_bug](https://user-images.githubusercontent.com/2899124/138389649-e545f8b6-7b91-4a0a-a033-a21782e21119.gif)

#### Environment information
- FlorisBoard Version: Current Master branch ( Release v0.3.14-beta04)
- Install Source: Github
- Device: Android Emulator
- Android: 11

**Comment by Pocarai** [comment]
This was the still problem in v0.3.13
