### ISSUE TITLE
More control to "adapt colors to a app" theming

### ISSUE THREAD

**Issue by Pun-e** [florisboard/florisboard#1338]
Adapting colors automatically is awesome, but the lack of control is a bit underwhelming.

I enjoy the default color scheme immensely, with its small pops of color, but when I turn on adaptive colors, the new colors completely ignore my current theme.

I propose that in the theme maker, that in the ui for selecting a color swatch underneath the transparency slider is a check box simply labeled "adaptive"

Ticking this box means that if you subsequently enable adaptive colors that the program will know which colors to change

Obviously there's bigger things to tackle, but hopefully this is something that can be squeezed in at some stage

Edit: i've just discovered the advanced attributes for theming, so a custom attribute to access the adaptive color palette could also work - but will make setting the default color a bit confusing

**Comment by klaurence** [comment]
Should this issue be closed? `Adapt colors to app` isn't a feature of Florisboard anymore but this can be the issue for implementing specific "adaptive" options in the theme maker.

**Comment by patrickgold** [comment]
This feature is not supported by FlorisBoard anymore, thus I am closing this issue as not-planned.
