### ISSUE TITLE
Search-text cannot be deleted in K9Mail

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1354]
#### Short description
This is really weird. Both with Florisboard v0.3.14-beta03 (59) and v0.3.13 I cannot delete my search query, not even by using delete-swipe.

Deleting this text DOES work when using the IrregularExpressions-keyboard or Samsung-keyboard.

I'm using K9mail v5.902

#### Steps to reproduce
1. In K9Mail, click on that magnifying glass-icon.
2. Type text
3. Try to delete that text

#### Environment information
- FlorisBoard Version: 0.3.14-beta03 (59)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android:  10

![blur1635142012278.jpg](https://user-images.githubusercontent.com/59611881/138643518-db3f0e09-1c55-4f5c-bf32-628f392afba7.jpg)

**Comment by Glitchy-Tozier** [comment]
Starting with K-9 Mail v5.909, [thanks to this commit](https://github.com/k9mail/k-9/commit/6d2e0e17c3905a584dc3a310b4c48f407a5c794a), the problem seems to be gone.

Should we close this issue?

**Comment by patrickgold** [comment]
Yup, I think so, seems like it was a K-9-specific issue.
