### ISSUE TITLE
User should be able to backup settings to a file, and then import them

### ISSUE THREAD

**Issue by chrstfer** [florisboard/florisboard#1362]
If the app was able to read/write settings to json, that would be a hugely helpful and hopefully quick-to-add workaround for issue #1304. It's an overall useful feature on its own, as well. 

I realize that the settings (and resulting json api) might change, breaking old settings files. There are ways to fail gracefully and would still save a ton of time. I've had to redo my settings just about every day, and im still always worried that i'll forget something.

Info/version: 
- 0.3.14-beta03 (59)
- Samsung galaxy s20 ultra

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for posting your idea!

This feature already has been requested in #467, thus I'll close this issue as a duplicate. If you have anything further to add to this topic, please post your thoughts there!
