### ISSUE TITLE
Prefs inaccessible, stuck in point 1 of the Welcome page

### ISSUE THREAD

**Issue by uli-on** [florisboard/florisboard#1364]
Although FB beta is installed and activated/enabled (I'm currently writing with FB beta), I can not do anything to enter its settings. I've already disabled all other keyboards, but nada. This was introduced in beta 02 or 03, I just didn't find the time to report it any earlier.

FB beta 05 (from F-Droid) 
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 94.0.4606.71
Motorola Moto G4
device not rooted

**Comment by patrickgold** [comment]
Thanks for your bug report! I just tested out a fresh install of FlorisBoard on an Android 6 device and it worked flawlessly, thus I can rule out a general issue with Android 6. Does clearing the cache for FlorisBoard help?

**Comment by babudro** [comment]
Hi. I just installed FlorisBoard 0.3.13 from FDroid, first time installation, and after enabling FlorisKbd in settings the Next button remains disabled.  I went into Language & Input settings and set Floris as the system keyboard, but no change, still greyed out, even though I am able to use it as my keyboard, albeit without spell check or any other prefs.

Version 0.3.13 is the latest version FDroid offers me, by the way.

I have an older Asus phone Z00XS, not rooted.

**Comment by patrickgold** [comment]
@babudro 0.3.13 is really outdated, because the mechanics in the current 0.3.14 beta builds for detecting the preference have changed quite a lot. If possible could you try out the latest beta [beta05](https://github.com/florisboard/florisboard/releases/tag/v0.3.14-beta05) and see if you can successfully set FlorisBoard up in this version?

Also which Android version are you on?

**Comment by uli-on** [comment]
Unfortunately this doesn't solve the issue, no.

**Comment by patrickgold** [comment]
Ok thanks for letting me know. Still, what Android version are you on? I need this info to narrow down why this issue is happening to some users.

**Comment by uli-on** [comment]
Ah, 2 points: 

1. I've updated my comment above https://github.com/florisboard/florisboard/issues/1364#issuecomment-955815011
2. You've mixed me up with @babudro, MY Android version is in the first post here :)

**Comment by patrickgold** [comment]
> You've mixed me up with @ babudro, MY Android version is in the first post here :)

You are right, I misread the username, sorry for that :)

> like @ babudro -- I've also an inaccessible v0.3.13.

I somewhat suspect that your device OEM maybe has renamed the device IME system settings and FlorisBoard thus reads a system settings that does not even exist on your device. At the moment I do not really know what else could cause the issue. Will see what I can do to investigate/fix this issue.

**Comment by babudro** [comment]
Hi.  That's odd: I was certain I had put my Android version in my report.  I must've deleted it by mistake.

My Asus Z00XS is running Android 6.0.1.

**Comment by babudro** [comment]
The beta-05 version goes through the configuration steps properly.  Thanks.

**Comment by patrickgold** [comment]
Hmm that's strange, but thanks for letting me know! For both of you it didn't work in 0.3.13, but in beta05 it works for one while it does not work for the other. It could technically be an issue with the settings observer on the Motorola device, but currently I am unsure. Will investigate further tomorrow.

**Comment by uli-on** [comment]
> I somewhat suspect that your device OEM maybe has renamed the device IME system settings and FlorisBoard thus reads a system settings that does not even exist on your device. At the moment I do not really know what else could cause the issue. Will see what I can do to investigate/fix this issue.
> 
Hm, if I get you right I should not have been able to open the prefs of any FlorisBoard version. But I had some good months  with the stable version(s) and even some of the betas, until the prefs implementation changed, just FYI. 
Please let me know if I can try anything to narrow things down. Currently I can't customize any of the FBs I've installed, so maybe I load the F-Droid archive and de-/re-install some of these until I can't access the prefs any longer?

**Comment by patrickgold** [comment]
I would like to see what happens with a completely fresh install of beta05 on your device, but you may not want to loose your configuration and themes etc.

If you want though you can try out installing the current debug artifact (https://github.com/florisboard/florisboard/pull/1370/checks). It installs separately and thus you can freely try out/wipe the app data etc. without having to loose your main config.

**Comment by uli-on** [comment]
(https://github.com/florisboard/florisboard/pull/1370/checks <https://github.com/florisboard/florisboard/pull/1370/checks>). It installs separately and thus you can freely try out/wipe the app data etc. without having to loose your main config.

Thanks, but … wrong link?

**Comment by patrickgold** [comment]
Ah that sh*t again - GitHub sometimes thinks it is funny and shows a 404 on mobile for artifacts. Try either logging in to GitHub in the browser or ticking the "Desktop site" toggle in your browser menu, this often helps that this page is available.

**Comment by patrickgold** [comment]
What could also have happended is that your email app took the `)` into the URL, here's the URL safely formatted for such cases:

https://github.com/florisboard/florisboard/pull/1370/checks

**Comment by uli-on** [comment]
> https://github.com/florisboard/florisboard/pull/1370/checks <https://github.com/florisboard/florisboard/pull/1370/checks>
> 

Looks like the same page. If I click around (click path forgotten) I find this here
https://github.com/florisboard/florisboard/actions/runs/1406003847

with an app-debug.apk of 28.4 MB. That one?

**Comment by patrickgold** [comment]
Jup, exactly that one!

**Comment by uli-on** [comment]
That went smoothly! Phew! Will explore one of the next days.

FYI: On my device/Android version, the action buttons for each of the three steps were initially invisible and needed to be scrolled up in each frame/step. I. e. there was no long scrollable page but everything was squeezed in one screen height with scrollable sub-frames.

**Comment by patrickgold** [comment]
Perfect, great to hear! This means that in general the bug is fixed, but on upgrade the APK somehow got corrupted.

I suspect that there's still some issue with the beta05 APK locally installed on your device. Could you try force-stopping beta05 and clearing the cache and then trying to enter the beta settings again? (Force stopping is in the same screen as the storage/cache options provided by the system for every app). I would just like to know if there's a way to recover from that corruption without reinstalling the APK in case it happens for other users as well.

> On my device/Android version, the action buttons for each of the three steps were initially invisible and needed to be scrolled up in each frame/step.

Is your device's screen small? If so, then that's the intended outcome, because the step layout cannot hide and make the step headers itself scroll-able (would be double vertical scroll which is not possible with the current UI library I use).

**Comment by uli-on** [comment]
> Could you try force-stopping beta05 and clearing the cache and then trying to enter the beta settings again?
> 
That didn't change the setup procedure, sorry.
> Is your device's screen small?
> 
I've 1080 x 1920, scale factor 3x (so 360 x 640). But that's not what I think is the reason. The stable FlorisBoard has a setup screen that is understandable even for newbies, while this one, frankly said, was only doable cause the debug version was not my first keyboard installation. It appeared like — if it were a website — some Javascript didn't do its job. There must be a better solution, and if it were only for minimising some wide paddings/margins and/or reducing the amount of text displayed, so the buttons would be visible at least with some pixels, cause there are no scrollbars indicating there's further contents.

I'll soon delete the app data in order to make screenshots of what I've had, and post them from my desktop computer (which is not doable via mail reply).

**Comment by uli-on** [comment]
Quick question: The debug app's setup procedure will once become that one of the stable version, right? Or am I putting energy into a dead horse thing?

**Comment by patrickgold** [comment]
> I've 1080 x 1920, scale factor 3x (so 360 x 640)

Ok the new setup screen is definitely not designed for this scale factor with a screen ratio of 16:9... The design baseline is 1080 x 2220 pixels, 1x scale factor, 18.5:9 ratio, this is the current standard for new phone screens.

I just tested out the setup UI with a scale factor of 3 and this is how it looks on one of my main testing devices:

![image](https://user-images.githubusercontent.com/19412843/139719689-abef8221-3eb8-41f0-a8f0-85b2f2b38a02.png)

Tight, but due to the screen height still fits in nicely.

> It appeared like — if it were a website — some Javascript didn't do its job.

Would it be possible that you post a screenshot of the setup UI so I can assess how bad it looks?

>  cause there are no scrollbars indicating there's further contents.

That's true, the UI library I use currently does not support scrollbars well, but my plan is to add them to the pref UI before the stable track release.

> Quick question: The debug app's setup procedure will once become that one of the stable version, right? Or am I putting energy into a dead horse thing?

Debug -> Beta -> Stable

So yeah, the beta05/debug procedure will be parts of 0.3.14 stable once the whole preference rework is finished, the only things that may change is little adjustments and bug fixes.

**Comment by Glitchy-Tozier** [comment]
@patrickgold Slightly off-topic butif this space isn't used (and is not filled by some line that connects the step-numbers), couldn't we just increase the room the text may fill up?
![Screenshot_20211103-211537_GitHub.jpg](https://user-images.githubusercontent.com/59611881/140186107-7737a874-e0b4-49b3-bc19-f8c58e98b18c.jpg)

**Comment by patrickgold** [comment]
Thanks for providing the screenshots! IMO this problem would be helped a lot if scroll bars were shown. As JC still does not support scroll bars out-of-the-box, I guess I will have to work on a custom implementation so this issue gets addressed properly.

> Slightly off-topic butif this space isn't used (and is not filled by some line that connects the step-numbers), couldn't we just increase the room the text may fill up?

I mean we could, but I like the text alignment to the header box (especially for bigger screens). Maybe I can try to decrease the vertical padding a bit, so more space for the content is there, will see.

**Comment by Glitchy-Tozier** [comment]
> but I like the text alignment to the header box (especially for bigger screens)

I thought so. In this case, could we fill that space somehow? Maybe add a simple dotted line between those enumeration-circles?

**Comment by patrickgold** [comment]
Dotted line implementation, now the space is not wasted anymore. The color chosen is the exact same as the color used for an completed step, so it does not distract too much from the content.

![Screenshot_20211104-203908.jpg](https://user-images.githubusercontent.com/19412843/140408461-a804dfb8-4338-4cc9-b709-9fe8330383ec.jpg)

**Comment by patrickgold** [comment]
In light mode for reference:

![Screenshot_20211104-204153.jpg](https://user-images.githubusercontent.com/19412843/140408799-0891305d-6bb0-4442-a0fa-1c2a853c6a37.jpg)

**Comment by Glitchy-Tozier** [comment]
Looks neat!  👌

**Comment by patrickgold** [comment]
So I played around a lot and finally implemented scroll bars:

(Using split screen mode to demonstrate tight vertical space)

https://user-images.githubusercontent.com/19412843/140429000-eea99361-9530-4bf7-b1bf-02547cd82e49.mp4

On initial show of a view that scrolls, the scrollbar stays for about 2s, this indicates that the inner box is scrollable.

I hope that with this at least for now most issues are resolved with the setup layout.

What I will still try is to decrease vertical space/padding of the boxes to allow for more content to show, but still I have to experiment with that one.

As this scrollbar is universal, it will apply to all scrollable views throughout the app, except some dialogs for now.

**Comment by Glitchy-Tozier** [comment]
> So I played around a lot and finally implemented scroll bars:

What's your reasoning for using it in the welcome-screen?

**Comment by patrickgold** [comment]
> What's your reasoning for using it in the welcome-screen?

Mainly because if a step content has too little space to show the button and it just so happens that the button is fully hidden while the text is fully visible, this introduces bad UX as nothing suggests that there is a button if you scroll the inner box. With the scrollbar (and its initial visibility), this is an indicator and additionally behaves similar to the way Android handles scrollbars system-wide.

**Comment by Glitchy-Tozier** [comment]
Now that I think about it, it makes sense!
It looked a bit weird at first glance but reducing paddings/margins in some places should help with that!

**Comment by uli-on** [comment]
This here has reappeared for me with the arrival of v0.3.14
