### ISSUE TITLE
Old preference backend stopped working in 0.3.14-beta05

### ISSUE THREAD

**Issue by uli-on** [florisboard/florisboard#1365]
Might have been present in beta 04 already, but I could not start that version (I was the guy who reported a crash on starting up beta 04)

#### Environment information
FlorisBoard Version (from F-Droid) 
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 94.0.4606.71
Motorola Moto G4
device not rooted

(Edited to remove junk from my tech data template)

**Comment by patrickgold** [comment]
Thanks for your bug report! The issue affects more than just the theme prefs: all preferences which still use the old preference backend (which I am working to get rid of) just stop applying. That's definitely a bug, but as the next beta will remove the old backend anyways (some of the frontend will still be the old UI), this bug should be resolved in beta06. Will add it to the project.

**Comment by patrickgold** [comment]
This issue should be fixed in #1370, which will be beta06 once released.
