### ISSUE TITLE
Delete key and deleting action not synched

### ISSUE THREAD

**Issue by uli-on** [florisboard/florisboard#1366]
After pressing the delete key for some time (one second or the like and more), FB beta 05 does not stop deleting characters on releasing the del key. Precise deleting of several words is not possible. From memory, vibration duration is set to 30 msec, but I can't check, currently because of #1364

#### Environment information
FB beta 05  (from F-Droid) 
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 94.0.4606.71
Motorola Moto G4
device not rooted

(Edited for amending my actions and correcting the vibration duration, looked up in stable FlorisBoard.)

**Comment by patrickgold** [comment]
Thanks for your bug report! I just discovered that each vibration on the delete key is fully blocking the main thread (in your instance 30sec per triggering), thus the deleting action and what actually happened de-synced really quick. #1370 provides a fix for this, will be released in beta06.

**Comment by uli-on** [comment]
The vibration, after all, great! Was just a gut feeling.
Thanks, Patrick!
