### ISSUE TITLE
Any plans to implement a T9 layout?

### ISSUE THREAD

**Issue by GitHub-user-2020** [florisboard/florisboard#1368]
### Discussed in https://github.com/florisboard/florisboard/discussions/1367

<div type='discussions-op-text'>

<sup>Originally posted by **GitHub-user-2020** October 30, 2021</sup>
Namely something like [this](https://ytprivate.com/watch?v=Su4-_v2qGvQ).

I'm aware of only one open source project that implements this (AnySoftKeyboard) but that project seems inactive and their implementation of T9 requires more work: prediction is not based on the key pressed, but rather, on what letter has been returned after the number of presses to return a specific letter as input.

For instance, typing the numbers with T9 prediction "269" can return either the numbers themselves, or with an English language keypad layout and dictionary the words "any", "box" or "boy". With AnySoftKeyboard's implementation, the user would not be able to type the words "box" or "boy" without pressing the number 2 twice (in order to type the letter "b" first before returning suggestions).

The current T9 keyboard app I use is Multiling O Keyboard, which thankfully does not have AnySoftKeyboard's hasty T9 implementation. However, the main issues with Multiling O Keyboard are that it's not open source (to my knowledge) and it is almost exclusively distributed through the Google Play Store (which leaves me and/or others with few, if any de-Googled or even general alternatives to a keyboard which I believe is best suited for small devices).

Thank you in advance for taking the time to consider my suggestion. I would very much appreciate it if you were able to implement this as soon as it's possible or provide an explanation and/or possible recommendations if you can't implement this at all.</div>

**Comment by Glitchy-Tozier** [comment]
Hi, this already has been suggested in #165 and the proposal was accepted. It just hasn't been implemented yet.

**Comment by GitHub-user-2020** [comment]
Thanks for letting me know! Thought I'd detail to you how I'd like this implemented to give you a bit of extra help.

**Comment by Glitchy-Tozier** [comment]
That's a good idea!

Could you possibly comy your thoughts into the linked issue so that we can close this one as a duplicate? :)

**Comment by GitHub-user-2020** [comment]
"Comy?" I'm sorry, I don't understand. You can feel free to close this if you wish.

**Comment by Glitchy-Tozier** [comment]
Sorry, thazwas supposed to be "copy".
Corrected version:

Could you possibly copy your thoughts into the linked issue (#165) so that we can close this one as a duplicate? :)
