### ISSUE TITLE
Dynamic color [a.k.a Material You] support

### ISSUE THREAD

**Issue by OxygenCobalt** [florisboard/florisboard#1371]
Add an option to theme the keyboard with Android 12's dynamic colors. GBoard already has this feature, but I would rather want to use FlorisBoard. This is optional, but you could also implement Material Design 3 elements too [Pill shapes & circles instead of rounded rectangles].

Here's a screenshot of GBoard's dynamic color theme:
![gboard](https://user-images.githubusercontent.com/65370175/139607945-c7f6b2a6-a512-47df-a008-8b52b0f52508.png)

Thanks!

**Comment by patrickgold** [comment]
Thanks for your proposal!

I am planning to support Material You, but currently Jetpack Compose (the UI library I use) does not yet have Material You support, thus FlorisBoard also does not have it. Either way, the preference UI will be first to get MY once it is available in the UI library, and then I will implement it for the keyboard UI later. Assigning to the themes issue list.

**Comment by patrickgold** [comment]
> This is optional, but you could also implement Material Design 3 elements too [Pill shapes & circles instead of rounded rectangles].

Although I am not exactly planning to support everything of Material 3, the new theme engine I am working on rn has placeholders to define custom shapes for keys, thus you can recreate this pillows once that theme engine is ready.

**Comment by OxygenCobalt** [comment]
Sounds good. I know that M3 is getting compose support eventually, it's just not ready right now [I think it's at alpha01 currently].

**Comment by OxygenCobalt** [comment]
Any updates on this? I'd imagine compose support for dynamic color has matured enough by now.

**Comment by tsiflimagas** [comment]
There's #1695 for this, but there haven't been any progress on it yet.

**Comment by patrickgold** [comment]
Small update on this feature: Sadly Jetpack Compose's [material3](https://developer.android.com/jetpack/androidx/releases/compose-material3) library is still considered experimental as of July 25 2022:

![image](https://user-images.githubusercontent.com/19412843/180880121-3247696c-7b94-426f-915d-11e7e2f2b8aa.png)

Additionally #1695 seems to be stale sadly, so I think it will still take a while until Material You is supported by FlorisBoard, either by someone contributing it or by me once the material3 library has matured enough.

**Comment by yavko** [comment]
From what I can see I think its almost stable, maybe a branch can be developed with it.

![Screenshot_20220827-165030_Trebuchet.png](https://user-images.githubusercontent.com/15178513/187051758-141abae4-d07c-428f-8c17-5f16f524e990.png)

**Comment by OxygenCobalt** [comment]
Perhaps. Personally I haven't had much issue with APIs changing under me once a release hits beta.

**Comment by patrickgold** [comment]
Quick status update: #2046 proposes to use a compat library for Material You's Monet component (which is responsible for the color extraction). This could mean I do not have to use the AndroidX library, plus it would mean Material You is also supported on version Android 11 and lower too. However I don't have spare time to take a closer look at the proposed compat lib atm, so it will take some time until I can take a closer look at this topic again.

**Comment by OxygenCobalt** [comment]
Doesn't sound too bad. Although, given how *slow* palette generation tends to be even before Monet, I don't know how practical this will be.

**Comment by yavko** [comment]
Can't you grab the colors by getting system accents?

**Comment by TadaCZE** [comment]
There is another method to implement this, just spawn a normal, unprivileged shell and execute a command somewhat like this:

`cmd overlay lookup android android:color/system_accent1_500`

You can replace accent1 with accent2, accent3, neutral1 or neutral2 and the 500 with a multiple of 100 anywhere between 0-1000 (and the values 10 and 50 also work) and it returns the needed monet color.

**Comment by OxygenCobalt** [comment]
Sure, but then you have to update it every time you change your wallpaper, making it a non-solution for people with slideshow wallpapers.

**Comment by TadaCZE** [comment]
Yeah, you are right, but this can be solved with periodic checks. I think it would be nice if every time you opened the keyboard, it would check the current colors.

The real problem with my proposed method would be the overhead of opening a shell every time, but that would need to be tested.

**Comment by OxygenCobalt** [comment]
That feels like a really in-efficient implementation of just grabbing the system accents manually.

**Comment by TadaCZE** [comment]
Maybe it is...

Okay it is...

im dumb

**Comment by yavko** [comment]
Idk how the AOSP keyboard does it, but maybe someone can reimplement what its doing.

**Comment by OxygenCobalt** [comment]
It should just be a matter of manually plugging in the system attribute resources, something that is trivial with compose.

**Comment by TadaCZE** [comment]
Yeah, florisboard literally already has a variables system built for this, so in the edit property dialog, you could just select under property value an option like "Dynamic color" and in the second dropdown there could be a list of all the possible monet color values (there's only like 65 of them, they would fit). These options would only show if you had the correct android version or when somebody deems it fit later on to implement a compatibility library.

I think that shouldn't be too hard, it's just a simple if check for the android version and then adding a way to select an already existing variable.

**Comment by patrickgold** [comment]
In above linked PR [1fexd](https://github.com/1fexd) has kindly implemented Material You support into FlorisBoard. The PR is currently under review by me but if no other roadblocks are found Material You support will be shipped in the next alpha release v0.4.0-alpha05 alongside the experimental word suggestion support.

> I think that shouldn't be too hard, it's just a simple if check for the android version and then adding a way to select an already existing variable.

While it doesn't look that hard at first it still required 27 files to be changed in order for dynamic system colors to be correctly propagated to all UI elements and to properly integrate it into the theme editor. This is mainly due to the fact that the dynamic color names from the system and FlorisBoard mismatch and the dynamic system colors need a reference to the Context which the internal variable system doesn't, so implementing Material You support is just more work than you assume.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/florisboard/florisboard/issues/1371#event-10830614126

Although this has been closed as completed for 8 months, I don't see any way to enable Material You colouration on the keyboard, nor does it appear to conform to Material 3:

>

**Comment by lm41** [comment]
You can enable material you in the theme editor. https://github.com/itsmartashub/floristyle is a collection of themes that use material you in the keyboard.
Material you in the settings app was implemented in https://github.com/florisboard/florisboard/pull/2467 and will be available in the next beta release.
