### ISSUE TITLE
Theme resets 

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1374]
Occasionally the theme resets itself to the default themes. It seems to happen mostly when I browse the settings or change a setting in florisboard. 

Sorry for little info, but I have not been able to determine what cause this issue.

**Comment by patrickgold** [comment]
Thanks for your bug report!

Which version of FlorisBoard are you on?

Also if possible could you try out the current debug artifact of #1370 (https://github.com/florisboard/florisboard/pull/1370/checks) and check if it is fixed there?

**Comment by Donkey-Doug** [comment]
Version: 0.3.14-beta05
Android: 10 (lineageos without google play services)

**Comment by Donkey-Doug** [comment]
I just found out that force stopping the app temporarily resets the theme. After a while it reverts automatically.

**Comment by Donkey-Doug** [comment]
I think the debug version solves issue https://github.com/florisboard/florisboard/issues/1374 Not sure about this issue, simce the crashes do not happen frequently.

**Comment by Donkey-Doug** [comment]
I also believe changing spell checker settings in florisboard resets the theme.
