### ISSUE TITLE
Feature request: key press vibrate duration

### ISSUE THREAD

**Issue by ainola** [florisboard/florisboard#138]
Thanks for this fantastic board! It's really excellent. Happily typing on it now :-)

It would be nice to be able to specify the duration of the vibrate when pressing buttons. This would be useful to allow a more "thocky" feel akin to the system buttons on the Pixel where there's a higher intensity yet short vibrate.

**Comment by patrickgold** [comment]
Glad you like FlorisBoard :)

I can definitely add a vibration duration preference, I will add to to the current milestone.
