### ISSUE TITLE
Make smartbar buttons customizable

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1380]
![Screenshot_20211104-005726_Firefox_1](https://user-images.githubusercontent.com/50382414/140235251-7048c8f6-475a-4704-ad8b-820cb9faebca.png)

I already have gestures for cursor control and the clipboard. I do not need those 2 buttons. I suggest making it possible to hide and sort the buttons.

**Comment by Glitchy-Tozier** [comment]
Hi duplicateof #689.
