### ISSUE TITLE
Weird animatiom glitch in firefox

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1381]
See video

https://user-images.githubusercontent.com/50382414/140236979-bfe88520-4c7c-466e-b5fd-5a1b305a756b.mp4

**Comment by patrickgold** [comment]
Does this only happen with FlorisBoard or also with other keyboards?

**Comment by Donkey-Doug** [comment]
Only florisboard.

**Comment by Donkey-Doug** [comment]
> Does this only happen with FlorisBoard or also with other keyboards?

Only with florisboard.

**Comment by pokegamer5547** [comment]
I'm using fennec for android (fork of firefox for android) and having same issue

**Comment by Donkey-Doug** [comment]
This might be fixed in 0.3.14-beta06, but I am not sure yet.

**Comment by Donkey-Doug** [comment]
Solved
