### ISSUE TITLE
Separate Keyboard height setting for portrait and horizontal mode

### ISSUE THREAD

**Issue by sudden6** [florisboard/florisboard#1388]
Currently there's one setting which controls keyboard height for portrait and horizontal mode, but it's not really possible to have good tradeoff that works for both modes. My suggestion is to make separate settings, equivalent to the bottom offset and horizontal key spacing ones.

**Comment by patrickgold** [comment]
This has been implemented in the latest beta snapshots, see beta05 (current release).

**Comment by sudden6** [comment]
Ok, then sorry for the noise and I'll wait until it's on F-Droid.
