### ISSUE TITLE
autocapitalize isn't disabled

### ISSUE THREAD

**Issue by theotheroracle** [florisboard/florisboard#1396]
#### Short description
Autocapitalize isnt disabled

#### Steps to reoroduce
Go to old settings
Turn off autocapitalize
Open an app and see that autocapitalize isnt disabled

#### Environment information
- FlorisBoard Version: 0.3.14-beta05 (61)
- Install Source: Izzydroid 
- Device: Oneplus 7T
- Android: 11

**Comment by theotheroracle** [comment]
fixed in latest beta

**Comment by patrickgold** [comment]
I indirectly addressed auto-capitalization in beta06 but oversaw that this issue exists. Thanks for giving feedback on this and closing the issue, really appreciate it!
