### ISSUE TITLE
Sound Volume for Input Events not working

### ISSUE THREAD

**Issue by ianmenz** [florisboard/florisboard#1402]
I am trying to change the volume of each key press. I opened the app, went to Keyboard, scrolled down to Sound and Vibration, and clicked on Sound Volume for Input Events. The default is 50%. I changed it to various volume levels, but only 0% worked, which made it silent. Every other volume was the same as the original 50%.

**Comment by patrickgold** [comment]
Thanks for your bug report!

Could you please fill out the bug report template so I can narrow down this issue? Thanks in advance!

**Comment by patrickgold** [comment]
Closing as this issue does not provide any details which could help narrowing down the bug.
