### ISSUE TITLE
Emoji long click gesture bug

### ISSUE THREAD

**Issue by shahzzz68** [florisboard/florisboard#1404]
When press the long click on emoji it selects the first item and require long swipe gesture towards right to move along the icons. Sometimes when long press on emoji the popup shows and automatically disappear that is mostly found in people emojis.

**Comment by patrickgold** [comment]
Thanks for your bug report! The emoji view is completely bugged in its current state and subject to a complete re-implementation (this applies especially to the popups). As this issue is already well known, I will close this issue.
