### ISSUE TITLE
[Feature request] Customizable layouts

### ISSUE THREAD

**Issue by bege10** [florisboard/florisboard#1407]
I have used Multiling O Keyboard for years because it is fully customizable. Unfortunately it is not well maintained any more and it is not open source. So I am looking forward to using FlorisBoard.

I like the ongoing layout development of FlorisBoard, but actually I would want to have (fully) customizable layouts. I customized the QWERTZ layouts I currently use as close as possible to the PC layout and packed them with useful features.

![screenshot_2021_09_08_15 04 23_1](https://user-images.githubusercontent.com/1184237/143718487-74b1c098-3ad6-4556-86ff-a9684d827173.png)

![screenshot_20211127_190507_1](https://user-images.githubusercontent.com/1184237/143718816-ad4d134f-47a3-4bfd-b8b4-f4f71dcae154.png)

![screenshot_2021_09_08_15 05 06_1](https://user-images.githubusercontent.com/1184237/143718499-ed120f54-5366-46d9-b312-1610d2c93607.png)

![screenshot_2021_09_08_15 05 54_1](https://user-images.githubusercontent.com/1184237/143718868-2e025541-b02d-44b7-b356-5d7a85c7c48d.png)

**Comment by bege10** [comment]
This is related to #196 and #686

**Comment by lawson85** [comment]
I'm in exactly the same boat. I want to change more colours and move symbols to other keys to replicate multiling

**Comment by patrickgold** [comment]
Thanks for your proposal. Custom layouts with an in-app UI are planned and #196 is the tracking issue for that. Will close this issue as a duplicate.
