### ISSUE TITLE
Allow for deletion of words and adding of spaces via gesture

### ISSUE THREAD

**Issue by tydog98** [florisboard/florisboard#141]
Being able to swipe left to delete words and swipe right to add spaces is a very intuitive way of typing on the keyboard Fleksy. After getting used to this way of typing it's very hard to change back and would be great to have with this keyboard.

**Comment by Glitchy-Tozier** [comment]
If I may add an additional gesture-request:

Add those two:
- swipe right: go to end of line
- swipe left: go to beginning of the 

I know buttons exist for those but they feel kind of uncomfortable.

**Comment by patrickgold** [comment]
This can definitely all be implemented. As a workaround, you can use the swipe left gesture for now on the delete button to delete words (defaults to precise char-deletion).

**Comment by patrickgold** [comment]
@tydog98 Thanks again for your suggestion! I've just added the delete word and insert space actions. Note that these are not set as the default ones for left/right, you have to configure this in the gesture prefs.

@Glitchy-Tozier Your suggested 2 actions are also included in the above PR, thanks for the idea!

**Comment by Glitchy-Tozier** [comment]
@patrickgold Amazimg, thank you!

**Comment by tydog98** [comment]
Awesome. Other FOSS keyboard projects haven't even acknowledged the suggestion so this is great. Will definitely be using over ASK now.
