### ISSUE TITLE
Glide typing wont work. 

### ISSUE THREAD

**Issue by durgadas9645** [florisboard/florisboard#1418]
Hi. 
Glide typing won't work. I turned it on in gesture settings. 

I'm on Realme x2 pro using Crdroid custom rom. 
Florisboard app version: 0.3.13

**Comment by Aman9das** [comment]
Use beta 5

**Comment by patrickgold** [comment]
I just implemented glide typing back into FlorisBoard in my prefs-reowrk-8 branch. You can either wait for beta08, stay on beta05 or use one of the debug builds of #1440. Hope this helps.

**Comment by ildar** [comment]
On Tue, Dec 14, 2021 at 4:53 AM Patrick Goldinger wrote:

> I just implemented glide typing back into FlorisBoard in my prefs-reowrk-8
> branch. You can either wait for beta08, stay on beta05 or use one of the
> debug builds of #1440
> <https://github.com/florisboard/florisboard/pull/1440>.
>
#1440 crashes on 7.1
