### ISSUE TITLE
IPA subtype — the letter ŋ produces a ɷ

### ISSUE THREAD

**Issue by maurysiek** [florisboard/florisboard#1420]
#### Short description
in the IPA outlay — the letter ŋ is incorrectly set to write a ɷ instead

#### Steps to reproduce
1. Go to settings, typing, and add an IPA subtype,  then switch to it;
2. long click on n and slide on ŋ to pick it;
3. See error — a ɷ produced instead.

#### Environment information
- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Android: 11

screen recording:
https://user-images.githubusercontent.com/87310760/144508383-2b62c2d1-e9ac-4b6c-88d9-2dc34efe490d.mp4

**Comment by tsiflimagas** [comment]
I've fixed this and a few more characters in IPA layout in #1444. You can try the artifact from it if you want and give some feedback.
