### ISSUE TITLE
Pressing smartbar activates one-handed mode

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1422]
In the latest beta the smartbar functionality was removed. However, pressing on the smartbar activates one-handed mode.

https://user-images.githubusercontent.com/50382414/144694049-76c883bc-1ec2-430d-b67d-e9a2325a93e3.mp4

**Comment by patrickgold** [comment]
This was a way for me to quickly test the one-handed mode, and I forgot to remove it. In beta07 a fully-working Smartbar replaces the beta06 Smartbar and then this issue will also be resolved.

**Comment by alissonlauffer** [comment]
Also noticed that, sometimes, when I click it, the keyboard freezes and I can't click on anything. Android 12 if it helps.

**Comment by patrickgold** [comment]
> Also noticed that, sometimes, when I click it, the keyboard freezes and I can't click on anything. Android 12 if it helps.

That's a known issue and actually fixed in the current debug builds for the next beta07 release.
