### ISSUE TITLE
Please enable clipboard,left,right,select all option

### ISSUE THREAD

**Issue by gsweeh** [florisboard/florisboard#1423]
Please enable clipboard,left,right,select all option work in all the time like in all webiste,apps in private mode or etc
As shown in photos
![IMG_20211205_190600](https://user-images.githubusercontent.com/65717972/144748806-a3bddc8f-8d54-431c-a125-a0f6c89844f7.jpg)
![IMG_20211205_190718](https://user-images.githubusercontent.com/65717972/144748809-36178f94-6907-4976-9a17-7124be6c58fe.jpg)

**Comment by patrickgold** [comment]
Will be re-implemented in the beta07 release (the current debug builds already have this included).
