### ISSUE TITLE
Could not stop the haptic feedback!

### ISSUE THREAD

**Issue by MSoumen** [florisboard/florisboard#1426]
I think the haptic feedback is lagging behind my notmal typing speed. I dont know may be for this the inputs are lagging. I tried by disabling the phone vibration from "Sounds and Vibration" section, by silent my phone but it doesn't help. My device details are:
Samsung M12 (4, 64) 
Android 11, One UI core 3.1

Thanks in advance.

**Comment by Glitchy-Tozier** [comment]
Thank you for taking the time to write this bug-report!
Could you share the version of FlorisBoard you're using?

**Comment by MSoumen** [comment]
Yeah sure... 
I'm using version 0.3.13

**Comment by patrickgold** [comment]
@MSoumen Is this bug still reproducible for you using the latest stable or alpha release (0.3.16 or 0.4.0-alpha02)?

**Comment by MSoumen** [comment]
> @MSoumen Is this bug still reproducible for you using the latest stable or alpha release (0.3.16 or 0.4.0-alpha02)?

Now Its working smoothly 👌 😌

**Comment by patrickgold** [comment]
Great to hear, thanks for replying!
