### ISSUE TITLE
New settings: Arrow in testing-row points to wrong direction

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1429]
I was sure I already reported this bug, but I can't find the issue anywhere. Apparently, I was wrong.

#### Short description
![Screenshot_20211206-130953_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/144843723-c0a4273b-557c-4255-bdbb-5a1c45e0f3a5.jpg)
The arrow doesn't _always_ point into the wrong direction; It happens when the user closes the keyboard via pressing android's back-button instead of the in-app arrow button.

#### Steps to reproduce
1. Click on the arrow-button or the texfield to open up the keyboard (and reverse the arrow)
2. Close the keyboard by pressing android's back-button
3. The arrow won't flip back, leaving it in the wrong orientation

#### Environment information
- FlorisBoard Version: 0.3.14-beta06 (62)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
> I was sure I already reported this bug, but I can't find the issue anywhere. Apparently, I was wrong.

Yes, in the #1235 mega-thread. But that does not count as an issue, so I will use this issue for this particular bug.

>  The arrow doesn't always point into the wrong direction; It happens when the user closes the keyboard via pressing android's back-button instead of the in-app arrow button.

That's true, but also a thing where the Jetpack Compose focus manager and the input field somewhat fail to work together correctly, thus this error occurs. I will still wait if new JC releases improve things in this regard, in the worst case I have to improvise in the last beta release before the rc releases for 0.3.14 begin.

**Comment by Glitchy-Tozier** [comment]
While you're at it, changing that text to say something like "Test Configiration" or "Test Keyboard" might be more intuitive.

![Screenshot_20211225-103130_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/147382231-96d5cb81-7a25-4fd8-ab61-7f658f110840.jpg)

**Comment by patrickgold** [comment]
> While you're at it, changing that text to say something like "Test Configiration" or "Test Keyboard" might be more intuitive.

The original string says "Try out your setup" which in my opinion is very intuitive, so this is a translation issue. I'd suggest something like "Probiere deine Konfiguration aus" or "Teste deine Konfiguration aus".

**Comment by patrickgold** [comment]
I just discovered that this string is translated into "Tastatur-Konfiguration ausprobieren", which is correct. So in fact this is not a translation issue but an issue with the available space for the text (try rotating your device and you should see the full text). Luckily I removed the arrow icon in the linked commit (will be released with beta08), so the text now has 1 button width more space to display. In my opinion the already existing translation can stay, except if you have a better suggestion or reason to change it.

**Comment by patrickgold** [comment]
Above commit additionally addresses the issue that the preview field placeholder text did not use the available space with an ellipsis clipping (three-dots), this is now fixed. For you the text would now appear as "Tastatur-Konfiguration ausprob...", which indicates that there's an additional word at the end. Together with the additional space gained through the arrow-button removal I think this particular issue is now fixed.

**Comment by Glitchy-Tozier** [comment]
Nice! If I may suggest two small improvements to the wording (this matters on smaller devices):
1. As you know we can (and most often should) append nouns to each other in the German language. Thus I recommend "`Tastaturkonfiguration`". It looks less "denglish" and is shorter.
2. "`testen`" is shorter than "`ausprobieren`" (and sounds slightly more professional :) )

Comparison:
Tastatur-Konfiguration ausprobieren
Tastaturkonfiguration testen

**Comment by patrickgold** [comment]
> As you know we can (and most often should) append nouns to each other in the German language. Thus I recommend "Tastaturkonfiguration". It looks less "denglish" and is shorter.

Agreed, will change that in Crowdin so the next strings.xml update contains this change.

> "testen" is shorter than "ausprobieren" (and sounds slightly more professional :) )

Shorter yes, but more professional? IMO I think "ausprobieren" sounds better and better reflects the "try out" part in the original source string.

**Comment by Glitchy-Tozier** [comment]
> Shorter yes, but more professional? IMO I think "ausprobieren" sounds better and better reflects the "try out" part in the original source string.

I guess we'll agree to disagree and go with your preference :p


>> "Tastaturkonfiguration". It looks less "denglish" and is shorter.

>Agreed, will change that in Crowdin so the next strings.xml update contains this change.

:+1:
