### ISSUE TITLE
"+" missing while typing contact number

### ISSUE THREAD

**Issue by Luciogi** [florisboard/florisboard#1430]
#### Short description
I wanted to save a number in contacts application, there was no (+) symbol in numpad.
I opened numpad in other apps, it shows (+) symbol

#### Steps to reproduce
1. Go to 'Contact app' 
2. Click on '+ button' (for adding contact)
3. Click on  'Number Field'
4. See opened numpad

#### Environment information
- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Device: Redmi 9T
- Android: 11(Crdroid)

**Screenshot**
![Screenshot_20211208-104248105](https://user-images.githubusercontent.com/84625092/145155943-982ca340-e3a2-4013-b56b-7713a5e1b0f7.jpg)
>

**Comment by Luciogi** [comment]
My mistake, I press *# button and plus symbol showed there.

**Comment by GoRaN909** [comment]
Long press on zero "0" number it will show as popup plus "+" symbol.
