### ISSUE TITLE
[Donation suggestion] Setting up a liberapay account for donations

### ISSUE THREAD

**Issue by PEPERSO** [florisboard/florisboard#1434]
Hi there !

I would like to make a periodic donation. It is a feature proposed by [Liberapay](http://liberapay.com/) a platform for FOSS projects financing. I think it would be useful to ease donations !

Thanks for all your work !

**Comment by patrickgold** [comment]
Thanks for your proposal!

Generally I think it would be a great idea having one FOSS option to donate (which currently is not really the case). Personally I have used Liberapay myself to support other FOSS projects (e.g. F-Droid), so this is a good site IMO. Note though that in the moment (December) I am completely occupied with Christmas preps, work and making sure I make steady progress on the 0.3.14 beta front, so I will either add this option in the Christmas holidays or early January 2022.

**Comment by PEPERSO** [comment]
No problem, it's fine for me ! :)

**Comment by patrickgold** [comment]
Sorry for the months-long delay on setting up Liberapay, had a lot going on in the last month and kind of lost track on this one...

I finally have set up my Liberapay account (https://liberapay.com/patrickgold/) to accept donations in addition to the existing PayPal and GH Sponsors options. Will also add this to the FUNDING.yml file, so it is officially linked in the repo's main overview.

Thanks again for your suggestion!
