### ISSUE TITLE
Implement Dracula theme

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#1435]
Hello,
Recently I created a new theme for FlorisBoard based on Dracula.
Perhaps when it gets accepted [(request pending)](https://github.com/dracula/dracula-theme/issues/659), it could be integrated into FlorisBoard if the Dracula project gives permission.

Thank you in advance

**Comment by patrickgold** [comment]
Sorry for getting back so late to you, had much to do in the last few weeks. The Dracula theme you created looks dope I must say, really liking it!

The small issue I see is that with 0.3.14 (or 0.3.14-beta08 to be correct as this is the current beta release) the theme engine has been rewritten entirely and is in a pretty stable state. Not all default themes have been transferred yet to the new format, but the ones included in the `org.florisboard.themes` package have been: https://github.com/florisboard/florisboard/tree/master/app/src/main/assets/ime/theme/org.florisboard.themes

This means for me to be able to consider adding it to the core APK package (if the Dracula project gives permission to do that) you'd have to adjust the theme to be packaged in your own `.flex` archive file (basically a zip with a different file ext), using the default themes package as a template. Which package name you choose is up to you, as long as it does use a domain relevant to either you, the Dracula project or `io.github.{lowercase_username}`, in your case `io.github.venom`.

What also must be changed is the "Install theme" instructions on the [theme page](https://draculatheme.com/florisboard), but these should be changed only if 0.3.14 is almost stable or stable, else I can't guarantee that the steps might slightly change.

Should you need any assistance don't hesitate to ask me in this issue!

**Comment by Venem** [comment]
Thanks for the reply and feedback!

To create the `.flex` file, would I essentially need to create a `io/github/venem/` folder structure inside it and place the theme `.json` file somewhere inside? I'm not really acquainted with android development or whether the app needs a specific file name for the themes.

Also, (I assume) that I'll need to redo the theme with the new format. Could this be done through the app (possibly the beta?) or would I need to write the json according to a template?

About getting permission from the Dracula project, I can open an issue on the main repo asking around. I don't expect there to be any issues seeing as their license (MIT) allows sublicensing and redistribution.

**Comment by patrickgold** [comment]
> To create the .flex file, would I essentially need to create a io/github/venem/ folder structure inside it and place the theme .json file somewhere inside?

If it were Kotlin or Java then yes, but in FlorisBoard you create a folder named `io.github.venem`, in which the structure looks somewhat like this: https://github.com/florisboard/florisboard/tree/master/app/src/main/assets/ime/theme/org.florisboard.themes

> I'm not really acquainted with android development or whether the app needs a specific file name for the themes.

The directory structure is FlorisBoard-specific, so in this particular case having Android experience can help but is absolutely not required. The only required file name in an extension is an `extension.json` manifest, everything else is inferred based on what you define in that manifest and can be freely named (with restrictions of special symbols of course).

> Also, (I assume) that I'll need to redo the theme with the new format. Could this be done through the app (possibly the beta?) or would I need to write the json according to a template?

Beta09 will provide an in-app theme extension editor, so if you wait a week or so this should be doable without touching a single json file + you have a live preview of what you are styling. There's no auto-converter though, but still I think re-configuring the theme in app should not take too long. Note that after exporting the extension you have a flex archive, but to include it in FlorisBoard's repo you need to unpack it and name the folder `io.github.venem` (but that is the last step anyways, so not that important for now).

Also thanks for obtaining permission from the Dracula project to include the theme, I have seen the issue you linked!

**Comment by Venem** [comment]
So for the `extension.json`, would it look something like
```
{
  "$": "ime.extension.theme",
  "meta": {
    "id": "io.github.venem",
    "version": "0.1.0",
    "title": "Dracula theme",
    "description": "Dracula theme for the keyboard UI",
    "maintainers": [ "Venem <vldpm@protonmail.com>" ],
    "license": "mit"
  },
  "themes": [
    {
      "id": "dracula",
      "label": "Dracula",
      "authors": [ "Venem" ],
      "isNight": true,
      "isBorderless": false,
      "isMaterialYouAware": false
    }
  ]
}
```
and I assume `stylesheets/dracula.json` would be the theme itself.

All of which is in a folder called `io.github.venem` which would eventually be zipped?

PS: About the permission, no problem!

**Comment by patrickgold** [comment]
> So for the extension.json, would it look something like

Yup

> and I assume stylesheets/dracula.json would be the theme itself.

Correct. You can also provide a "stylesheet" parameter to provide a custom relative path if needed.

> All of which is in a folder called io.github.venem

Yup.

> which would eventually be zipped?

If you include it in the app core assets then no, it will not be zipped, but shipped and read in its unzipped state (this is because the app assets file API is a pain in the butt to work with and this makes it a lot faster in runtime to read a stylesheet or other json file). Also it is a lot easier for version control systems to work with unzipped files than zipped ones.

If you would publish your theme on the community repo for theme sharing (which currently does not exist but will in the future) then you need to use the flex format (zipped), else users would not be able to install a custom theme.

**Comment by Venem** [comment]
Ok, thanks for the clarification. Once beta09 is out I'll get working on porting the theme

**Comment by Venem** [comment]
I've made the theme but I don't know how to export it 🤣. Could you kindly help me find a way to get it?

**Comment by patrickgold** [comment]
Click on the extension name (in the manager screen), then you have the export button, which gives you a `.flex` archive, where everything relevant for your theme extension is contained.

I know that the button is not particularly easy to find, and other users have already suggested to make it more obvious or change how one gets to the export button. Will fix that before 0.3.14 stable.

**Comment by Venem** [comment]
Thanks, I've got the file. Should I wait until the extension store is completed or make a PR now?

**Comment by patrickgold** [comment]
The official addons store will allow community themes and everything related to it, see #2468 for more info. Closing to avoid duplicate discussions around this.
