### ISSUE TITLE
Add possibility to set clipboard bar as default row

### ISSUE THREAD

**Issue by Krusty27** [florisboard/florisboard#1439]
I checked and I don't think there already is a issue about this. 
I would like to put the copy/paste/etc... bar as default in the one row smartbar and toggle the other one with the toggle button. Something like the attached photo but plus the toggle button. Thanks for your work!

![image](https://user-images.githubusercontent.com/28927643/145818639-a27d275f-46da-415e-b54b-efaa5047a614.png)

**Comment by patrickgold** [comment]
I am currently working on this feature, please see #1548 (same proposal) for details. Closing this to prevent duplicate threads.
