### ISSUE TITLE
Change Keyboard-Colors According to App-Colors

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#144]
Got the idea from AnySoftKeyboard. It's probably best to try it out there to fully understand it.

This supposedly is their pull-request: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1556

**Comment by patrickgold** [comment]
That's a pretty nice idea right here. As I am currently working on the Theme rework, I will implement it together with it. Thanks for the suggestion!
