### ISSUE TITLE
Don't make keyboard disappear when opening emoji-view

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1447]
It seems a bit dirty to let the keyboard just disappear. I suggest using some kind on `"not yet implemented"`-toast.

#### Environment information
- FlorisBoard Version: 0.3.14-beta07 (63)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Should have probably added this I agree but I forgot about that. It isn't irreversible though, just hide and show the keyboard again and it will automatically reset to the keyboard UI.

**Comment by Glitchy-Tozier** [comment]
I know, "irreversably" probably wasn't the right word.

**Comment by patrickgold** [comment]
Above PR adds a TODO toast and does not "hide" the keyboard anymore for the emoji action, this will stay until I re-implement an emoji view.
