### ISSUE TITLE
Clear primary clip doesn't clear clipboard histories' last item

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1448]
#### Steps to reproduce
1. Copy something
2. Clear primary clip
3. It's still in the clipboard-manager-history

#### Environment information
- FlorisBoard Version: 0.3.14-beta07 (63)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Not a bug because I never implemented that in the first place. The question is should it delete from the history? I mean I could add a toggle for it, but per se the history and the primary clip live and work pretty independently from each other.

**Comment by Glitchy-Tozier** [comment]
You once told me that the idea behind the `clear primary clip`-functionality was to for example delete passwords, so that they can't be accessed anymore.
With this in mind, it seems only reasonable that this button clears all instances of the copied text, not just one of them.

**Comment by patrickgold** [comment]
> You once told me that the idea behind the clear primary clip-functionality was to for example delete passwords, so that they can't be accessed anymore.

You are correct here, but my main concern was that sensitive data was within the system primary clip (which other apps, although with some restrictions on modern Android, can read from). The Floris clipboard history is internal and other apps cannot access it, so it was less of a concern. However you also make a good point here and am currently thinking if I change this (maybe still make a toggle for this but defaulting to delete from history as well).

**Comment by Glitchy-Tozier** [comment]
> You are correct here, but my main concern was that sensitive data was within the system primary clip (which other apps, although with some restrictions on modern Android, can read from)

That reasoning makes sense.

> However you also make a good point here and am currently thinking if I change this (maybe still make a toggle for this but defaulting to delete from history as well).

Sounds like a good plan!

**Comment by patrickgold** [comment]
Above PR adds a toggle (defaulting to on) for this behavior, will be available in beta08.
