### ISSUE TITLE
Relocate back-button in clipboard-manager

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1449]
The reason for this proposal is: for some reason, in this specific scenario, if the user accidentally clicks on the same spot twice
![Screenshot_20211216-110106_GitHub.jpg](https://user-images.githubusercontent.com/59611881/146350501-6c963a9f-1c54-4f2c-82b3-eead25c0974b.jpg)
![Screenshot_20211216-110752_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/146351704-9f00c2b0-270f-47b0-9c8c-a96e4eeb587e.jpg)
, then all clipboard items will be deleted. This happened to me acouple of times.

The first proposal i thought of was moving the buttons like this:
![Screenshot_20211216-105801_One UI Home.jpg](https://user-images.githubusercontent.com/59611881/146350827-701d7563-aff1-4e82-9370-37d8ea001a31.jpg)
This would align with Florisboard's "press the same area a second time to return"-design (see the navigation when going to symbols, when switching languages, or when toggling the bottom smart-bar, for example)

**Comment by patrickgold** [comment]
I see the problem and acknowledge it, but don't really like the proposed solution. The back button for LTR layouts is always left of the screen title, and changing that looks a bit out of place.

Still I see the problem and propose alternative solutions:
a. Add a confirm dialog to the delete all button to ensure that accidental taps don't result in history losses.
b. Switch the clipboard manager and select all button in the Smartbar clipboard cursor row.
c. I also intent to add an inline history editor (so you can edit and add items within the history) in the future, and I can place the button for that exactly where the delete all sits now, thus in the worst case on double tapping you land in the history editor.

**Comment by Glitchy-Tozier** [comment]
For now, option **a.** sounds like the best idea. Option **b.** blocks the select all → copy/cut workflow.

**Comment by patrickgold** [comment]
Solved this issue in above PR by adding a placeholder button for inline clipboard editing where the current sweep delete button is, thus decreasing the chance of an accidental hit. Will be released today in beta08.
