### ISSUE TITLE
Popup stays active

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1450]
#### Steps to reproduce
1. Hold down the settings button in the smart-bar
2. Hold any key that produces a pop-up
3. Let go of the settings-button. The settings will pop up (sometimes this takes quite a while)
4. Activate the keyboard inside any text-input-area
5. See the still active popup

#### Environment information
- FlorisBoard Version: 0.3.14-beta07 (63)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

![Screenshot_20211216-133649_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/146374251-311509b6-a089-43e9-8730-57f3dff2dd42.jpg)

**Comment by patrickgold** [comment]
Ffs my popups are still not Glitchy-safe xD

I can confirm however that I already have an idea on how to fix this bug, will do that when I find the time to fix keyboard UI issues.

**Comment by Glitchy-Tozier** [comment]
> Ffs my popups are still not Glitchy-safe xD

They'll never be ;)
That being said, you're doing a good job of making things as hard as possible for me.

**Comment by patrickgold** [comment]
> That being said, you're doing a good job of making things as hard as possible for me.

Will never stop making breaking my keyboard as hard as possible. Jetpack Compose fixes some tricks you used to produce earlier state bugs, but it also has its own problems (especially with focus and touch logic), and you are learning quickly to utilize these problems to produce all sorts of bugs I want to see gone :)

**Comment by Glitchy-Tozier** [comment]
Ahh, that explains it! I was wondering why I suddenly had to do a new/different kind of nonsense :)

**Comment by patrickgold** [comment]
Same as with #1446 fixed this by repairing and adjusting the lifecycle logic. Will also be parts of the 0.3.15-rc02 release later today.

**Comment by Glitchy-Tozier** [comment]
Good job! :)

**Comment by patrickgold** [comment]
Just so you know: I just discovered that above fix introduced a crash: #1771. I will fix this for 0.3.15 stable but won't make a separate rc release anymore. Should you encounter this as well you'd have to wait to 0.3.16-beta01, but this release will be done in a few days anyways, so it shouldn't be too problematic.

**Comment by Glitchy-Tozier** [comment]
Ok :)
