### ISSUE TITLE
Can you add a translator ?

### ISSUE THREAD

**Issue by AnasSdiq** [florisboard/florisboard#1456]
Can you add a translator ?

**Comment by bege10** [comment]
Do you know these translators? Both add an entry to the context menu of selected text. So you can open the translators systemwide with the selected text and copy'n'paste the teanslation..

https://f-droid.org/packages/com.example.deeplviewer (online)

https://f-droid.org/packages/de.reimardoeffinger.quickdic (offline)

**Comment by realpixelcode** [comment]
@AnasSdiq What exactly do you mean by that?

**Comment by AnasSdiq** [comment]
@realpixelcode Like the one in Gboard

**Comment by andsofine** [comment]
totally agree. a translator is very much needed

**Comment by patrickgold** [comment]
Please see above linked issue regarding the addition of a translator, will close this issue as a duplicate.
