### ISSUE TITLE
Spacebar is invisible while pressed

### ISSUE THREAD

**Issue by xV8IHmeZIAStqNFV8iKGyyertVIet15TS6gWrIV** [florisboard/florisboard#1457]
#### Short description
The spacebar becomes invisible while you press it.![Screenshot_20211219-001442__01.jpg](https://user-images.githubusercontent.com/93834402/146658203-1a04d3bc-caae-4335-b357-ba7ee6bde00b.jpg)

#### Steps to reproduce
1. Install debug build from #1440
2. Press the space bar

#### Environment information
- FlorisBoard Version: 0.3.14-debug (63)
- Install Source: Github debug build from #1440
- Device: Oneplus 6
- Android: Oxygen OS 11.1.2.2

**Comment by patrickgold** [comment]
Thanks for your bug report!

This issue is known to me and was a bug in the variable resolver of stylesheets. Locally this is already fixed, will attach this issue to the beta08 PR.
