### ISSUE TITLE
Mix Hint / Accent Prioritization

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#146]
For many languages, the current system isn't optimal. Here's an example for German:

- **Accent prioritized**: ä, ö, ü, and ß can easily be typed. However, é and í aren't used at all and thus should not be the prioritized popup.
- **Hint prioritized**: ä, ö, ü, and ß can not easily be typed.

Solution: add a third option that only sets the letters as prioritized popups, that actually are used in the selected language.

**Comment by patrickgold** [comment]
The code base for this is actually already fully implemented with #119 (but not yet released). I named the third option "Smart prioritization". Note, that depending on the language some popups don't have this properly configured in their corresponding json file. I did my best to properly configure it for all languages I know of, but there is definitely fine-tuning work to do there.

**Comment by Glitchy-Tozier** [comment]
I see, if i remember, I'll let you know if German has any problems!
