### ISSUE TITLE
Numbering post suggestions

### ISSUE THREAD

**Issue by singhh9596** [florisboard/florisboard#1461]
While typing, the suggestions appearing have numbers on them. Is it a bug or a feature? And the suggestions aren't reliable as gboard.

**Comment by Glitchy-Tozier** [comment]
Thank you for posting your bug-report.
Please fill out the full issue-template, including the environment information, to make fixing this issue possible.

**Comment by singhh9596** [comment]
Environment information
- FlorisBoard Version: 0.13.14(beta)7
- Install Source: Google PlayStore
- Device: 
- Android: <!-- 11 on shapeshiftOS--

Steps to reproduce:
-enable inline suggestions and type.

**Comment by patrickgold** [comment]
Not an issue but a placeholder to test out the suggestions UI. The old word suggestions may be re-added in any of the following beta releases, 0.4.0 (as per roadmap) will finally address and implement a new word suggestion implementation for more languages.
