### ISSUE TITLE
a small rearrangement of the keys

### ISSUE THREAD

**Issue by YoYoDeveloper** [florisboard/florisboard#1472]
So, It is possible a small rearrangement of the keys? I mean the special characters keys.
Im coming from Samsung Keyboard and my fingers still know the old position of special characters...

![image](https://user-images.githubusercontent.com/43702866/147387181-642733aa-631c-4ffc-8dfb-ec29f526775c.png)
![image](https://user-images.githubusercontent.com/43702866/147387190-eed36e5f-bb3f-4644-94c1-9c691935298f.png)

it will be nice if your keyboard will have this position of special characters.
If is not possible then is fine, I just say, it will be cool this.
Thank you for your work, I love your keyboard!

**Comment by Glitchy-Tozier** [comment]
Regarding the question: As far as I am aware, this currently is not possible.

Regarding the proposal: We'll have to wait and see what Patrick thinks. :)

**Comment by patrickgold** [comment]
Thanks for your proposal!

In general your proposal falls under "runtime layout customization", which #196 is the tracking issue for that. In that issue it says v0.5.0, although with the current roadmap it will more likely only be 0.6.0 for an in-app customization UI, and sooner when you are willing to manually export, modify and import a custom json layout file. Will close this issue to avoid duplicates for this topic.
