### ISSUE TITLE
Put swipe typing words on the smart bar

### ISSUE THREAD

**Issue by IveMalfunctioned** [florisboard/florisboard#1473]
Whenever I'm swipe typing with Florisboard I don't know for sure if the word I swipe typed was correct until it's spelled out, so please add a sort of preview to the smart bar like on Gboard and Samsung's keyboard

**Comment by patrickgold** [comment]
Glide typing preview of the word is already implemented, it just requires that suggestions (the placeholder toggle for real next word suggestions in 0.4.0 in the future) is enabled. Will close this issue as already implemented.
