### ISSUE TITLE
Autocorrect not working

### ISSUE THREAD

**Issue by IveMalfunctioned** [florisboard/florisboard#1474]
If I mistype a word it doesn't correct it even with autocorrect enabled in both system settings and florisboard settings

**Comment by Glitchy-Tozier** [comment]
When reporting bugs, please make sure to fill out the bug-template. Especially the **Environment Information** is important.

**Comment by patrickgold** [comment]
Autocorrect itself is not implemented yet and will be implemented together with the new word suggestion stuff in 0.4.0 (see roadmap). Will close this issue to keep the list of issues cleaner.

**Comment by IveMalfunctioned** [comment]
Ok, when will 0.4.0 be released?
