### ISSUE TITLE
Not applying custom color on space

### ISSUE THREAD

**Issue by Yurieaijoker** [florisboard/florisboard#1479]
When customizing the space its not applying

#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by Glitchy-Tozier** [comment]
1. Please give us a more detailled description of the problem.
2. Please fill in the environment details.

This information is necessary to fix your issue.

**Comment by Yurieaijoker** [comment]
I try to change the individual background color of the space bar  but its not applying, in other indiviaual keys like enter key its applying but not on space.

FlorisBoard Version: v0.3.13
Install Source: Github
Device: HUAWEI nova 7 SE CDY-NX9B 
Android: android 10

**Comment by Yurieaijoker** [comment]
Also how to customize background color of comma and period key?

**Comment by GoRaN909** [comment]
> 

> Also how to customize background color of comma and period key?

For coloring comma and other buttons use like this:

For comma 👉 key:.

For language change 👉 key:language_switch

For Shift 👉 key:shift

For Emoji button 👉 key:switch_to_media_context

For symbols 👉 key:view_symbols

Then define the color for each buttons 

Here is a custom theme created bu my 

👇

![Screenshot_20220101-170457_Samsung Internet](https://user-images.githubusercontent.com/3160786/147852358-b18dcd55-cac0-4c95-9e92-86f2d8a00730.png)

**Comment by Yurieaijoker** [comment]
> > 
> 
> > Also how to customize background color of comma and period key?
> 
> For coloring comma and other buttons use like this:
> 
> For comma 👉 key:.
> 
> For language change 👉 key:language_switch
> 
> For Shift 👉 key:shift
> 
> For Emoji button 👉 key:switch_to_media_context
> 
> For symbols 👉 key:view_symbols
> 
> Then define the color for each buttons
> 
> Here is a custom theme created by my
> 
> 👇
> 
> ![Screenshot_20220101-170457_Samsung Internet](https://user-images.githubusercontent.com/3160786/147852358-b18dcd55-cac0-4c95-9e92-86f2d8a00730.png)

Its not working and how did you remove the comma key?
![Screenshot_20220102_072930_dev patrickgold florisboard](https://user-images.githubusercontent.com/93813352/147862253-aad459c4-8de4-450b-97e7-347d05f4a3bf.jpg)

![Screenshot_20220102_072722_com google android googlequicksearchbox](https://user-images.githubusercontent.com/93813352/147862250-c8b6c29f-9982-4f44-b965-e63597fa0c4a.jpg)

**Comment by Fabio5271** [comment]
I was having the same issue, but I figured out a workaround! 

-First, download the source code
-Then copy the theme file for, say, floris dark; we're using this as a base. (It's in src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/charactersMod/default.json)
-Open the .json on a text editor of your choice and do the configuration through it
-This might seem hard at first, but the code for the enter key is a good template for any individual keys
-Space is ' ' , period is '.' , comma is ',' , and the other special keys are like the wiki says
-Save your changes
-Import the theme you made (you can import it in the same menu where you create a new one)
-It should work now

**Comment by Yurieaijoker** [comment]
Nice I'll try this. Thank you.

**Comment by GoRaN909** [comment]
> 

You must export one of available themes as a json file then add the (.) manually 

Here is an example for delete and period key

"key:.":{"background":"#FF484848","foreground":"#FFFFFFFF"},
"key:delete":{"background":"#FF484848","foreground":"#FFFFFFFF"},


I'm using the stable version 0.3.13 with some customization i made for my self and build with Android Studio 😀

![Screenshot_20220103-152006_Samsung Internet](https://user-images.githubusercontent.com/3160786/147929729-7700cccf-41fb-45d5-a922-48f7d887ca60.png)

**Comment by Yurieaijoker** [comment]
Thanks, oh and that looks nice. Great  job

**Comment by patrickgold** [comment]
The new stylesheet editor in the upcoming release 0.3.14-beta09 will allow to define a rule to change the text color of the space bar (without the json file workaround GoRaN correctly showed), thus this issue will be attached and auto-closed with the merge of the new stylesheet editor.
