### ISSUE TITLE
Make middle symbol-row shorter by one key.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#148]
In my opinion, if feels kind of weird  that the middle row changes it length (9 Letters → 10 Symbols)

I think, a better approach is to use the idea seen in the OpenBoard-Keyboard of placing the `/` key on the right side of the spacebar, opposite of the
```
12
34
```
-key.

Here's a screenshot of OpenBoard. I suggest using the same `/` location.
![Screenshot_20210109-133134_GitHub.jpg](https://user-images.githubusercontent.com/59611881/104092040-a6585e00-5281-11eb-8e68-57c6ecf69159.jpg)

**Comment by patrickgold** [comment]
This is pretty much a personal preference, and imo this length change is perfectly fine. Maybe I will look into adding additional symbol variants for this behavior, but I am currently unsure.

**Comment by Glitchy-Tozier** [comment]
I see.
The reason why i think moving the`/`-key is that users might look at the hints on the letters to know in advance, where to click on the special-keyboard.

However, i just found out that Gboard handles it the same way as you do, meaning that leaving the `/`-key where it is is probably a good idea.

**Comment by patrickgold** [comment]
What should we do with this issue? In my opinion the current symbols layout is fine as it is and we can close this issue, but I let you decide as you created this issue.

**Comment by Glitchy-Tozier** [comment]
I still think it would be nice if the row-width didn't change, but if we try to not stray too far from gboard's design, that's fine too.

I'm not very invested in this issue, closing it.
