### ISSUE TITLE
Clipboard contents randomly get pasted when typing

### ISSUE THREAD

**Issue by jmturner** [florisboard/florisboard#1484]
#### Short description
When typing, sometimes the contents of the clipboard get unexpectedly pasted into the text

#### Steps to reproduce
1. Open any app that activates keyboard
2. Begin typing.
3. At unpredictable times, the contents of the clipboard will get pasted into the text you are typing.

#### Environment information
- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Device: Xiaomi Redmi Note 10 Pro MK2101K6G aka "sweet" 
- Android: LineageOS 18.1, Android 11.

I will try adjusting FlorisBoard's clipboard settings to see if this helps.

**Comment by patrickgold** [comment]
Thanks for your bug report! If possible can you confirm that this happens on the latest beta07 as well? The current beta has a completely different clipboard logic and this bug could be fixed, the same or gotten worse with the changes made.

**Comment by patrickgold** [comment]
Closing as this issue has stalled. If this is still reproducible in 0.3.14-rc03 please tell me. Thanks!
