### ISSUE TITLE
Option to Hide Subtype Changing Button

### ISSUE THREAD

**Issue by KingLucius** [florisboard/florisboard#150]
Useful for situation like when I use gestures to change subtype, Switching subtype button is now useless so an option for hiding or changing it to emoji button only will be great specially that I can access emoji and setting via enter button.

Thanks for the great work.

**Comment by patrickgold** [comment]
Thanks for your suggestion! Like I said in #79, I plan to implement language switch / emoji enabling/disabling to be configurable in the Settings. Maybe I will even move it to the v0.4.0 milestone, as quite a lot of people want this feature. Closing this issue as it is a duplicate.
