### ISSUE TITLE
word suggestion issue

### ISSUE THREAD

**Issue by 3abdooo** [florisboard/florisboard#1502]
for exemple writing the word HELLO
the suggestions are like this
H
H1|H2|H3|H4

HE
HE1|HE2|HE3|HE4

HEL
HEL1|HEL2|HEL3|HEL4

...

HELLO
HELLO1|HELLO2|HELLO3|HELLO4

i hope some how i'm clear

############################
beta8

###########################
samsung galaxy s7 lineageos 17.1 with microg

**Comment by min7-i** [comment]
Are you referring to the suggestions displayed in the smartbar?
![Screenshot_20220115-225030(1).png](https://user-images.githubusercontent.com/97251923/149638909-72cc7e68-f16e-48ea-aed0-98d73202c3d4.png)

In the 0.3.14-beta versions word suggestions have not been implemented yet. The behavior you are describing is expected. See the info in the app or the release notes:
![Screenshot_20220115-215000(1).png](https://user-images.githubusercontent.com/97251923/149639056-430c9417-a026-4d25-aa37-56c8449c993b.png)

**Comment by 3abdooo** [comment]
oh yes it is
