### ISSUE TITLE
Tiny gap under keyboard

### ISSUE THREAD

**Issue by elesto** [florisboard/florisboard#1505]
#### Short description
Tiny gap under keyboard 

#### Steps to reproduce
1. Default behaviour 

#### Environment information
- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Device: Sony Experia 5  #II
- Android: 11, Stock 

![Screenshot_20220111-202522](https://user-images.githubusercontent.com/24771215/149611212-ea24f26b-4a02-4522-92ab-af8f0b67cc26.png)

**Comment by patrickgold** [comment]
Thanks for your bug report! Is this tiny gap also reproducible in the latest beta release 0.3.14-beta09?

**Comment by elesto** [comment]
Id like to test that for you but I dont know how to back up my floris settings so i can uninstall and re install the new app. Or can I install over the old version? But id like to go back to the stable version after testing.

**Comment by patrickgold** [comment]
The beta version installs as a separate app, so you can run both beta and stable without it interfering with each other :)

**Comment by elesto** [comment]
Yes it is fixed in the new beta
