### ISSUE TITLE
link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by CouldBeThis** [florisboard/florisboard#1506]
am just reading [CONTRIBUTING.md](https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md):

> To add a new layout, head to [`app/src/main/assets/ime/text`](https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/text) and then select the correct sub-directory for the type of layout you want to add. In most cases this will be `characters` to add a layout like QWERTY etc.

However,  [`app/src/main/assets/ime/text`](https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/text) doesn't have any subdirectories, only a single file, [`symbols-with-space.json`](https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/text/symbols-with-space.json).

Maybe the correct link is [`app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts`](https://github.com/florisboard/florisboard/tree/master/app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts) which does have a [`characters`](https://github.com/florisboard/florisboard/tree/master/app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters) sub directory.

Edit: 

Sorry am not sure if this should be separate issue but very similar and would probably be fixed together so will combine. 

Also in `CONTRIBUTING.md`,

> Any accents or diacritics that should be exposed via long press can be added at [`app/src/main/assets/ime/text/characters/extended_popups/<languageTag_name_here>.json`](https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/text/characters/extended_popups).

but there is no such directory.

Is the correct link maybe [`app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings`](https://github.com/florisboard/florisboard/tree/master/app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings)?

**Comment by patrickgold** [comment]
Thanks for pointing this out!

The 0.3.14 development introduces extensions for defining layouts, popup mappings, etc., with this the directories have also changed quite a bit. The links you found are indeed the correct ones, I will need to rework the whole contributing file anyways though so with that rework I will fix the links. Will do that before I release 0.3.14 stable.

**Comment by patrickgold** [comment]
Above commit fixes the CONTRIBUTING file, is now referencing correctly again. Thanks for reporting!
