### ISSUE TITLE
Autofill inline suggestion only displays 1 entry and looks strange on 0.3.14-beta08

### ISSUE THREAD

**Issue by ZenerDeveloper** [florisboard/florisboard#1507]
#### Short description
When both the passwird manager and keyboard have inline suggestions enabled, Florisboard doesn't seem to show all (or any) of the entries.
With KeepassDX (I haven't tested any other password managers) if you disable the option **manual selection** in Keepass, it will not show the chips at all, but will sometimes show the popup box to select an entry. SwiftKey doesn't have this issue. 
#### Steps to reproduce
1. Enable inline autofill
2. Go to a page with saved entries
3. See only one entry (the "manual select" one)

#### Environment information
- FlorisBoard Version: 0.3.13 and 0.3.14-beta08
- Install Source: F-Droid
- Device: Samsung Galaxy S10+
- Android: Android 11 OneUI 3.1

<details>
    <summary> Screenshots </summary>

##### 0.3.13 unlock prompt
![20220115_095912](https://user-images.githubusercontent.com/80724816/149626496-1ebdcce6-4f39-4203-9d82-9fccd31edf05.jpg)
##### 0.3.14-beta08 unlock prompt
![20220115_095927](https://user-images.githubusercontent.com/80724816/149626498-5f5780e4-2d4e-4d6b-b62d-6c1c898b84a1.jpg)
##### 0.3.13 select prompt
![20220115_100001](https://user-images.githubusercontent.com/80724816/149626503-0586163c-03d9-4bcd-928f-083c45d24fe1.jpg)
##### 0.3.14-beta08 select prompt
![20220115_100010](https://user-images.githubusercontent.com/80724816/149626504-64087536-310c-4320-9cf7-a07c98f73cdf.jpg)
##### SwiftKey 7.9.3.5 (expected behaviour)
![20220115_100018](https://user-images.githubusercontent.com/80724816/149626506-79e3a1c5-da35-4c86-83f4-36ae74f50b56.jpg)

</details>

**Comment by patrickgold** [comment]
Forgot to close this issue, above commit fixed this issue in 0.3.14-beta09.
