### ISSUE TITLE
Can't Access Settings

### ISSUE THREAD

**Issue by dies00irae** [florisboard/florisboard#151]
I removed the icon from the app drawer.  When I go to virtual keyboard in system settings, the app settings don't show up when I press florisboard.  Unfortunately, I got rid of the bar with the setting on the keyboard as well.

**Comment by Glitchy-Tozier** [comment]
Long-click on the emoji-button?

**Comment by dies00irae** [comment]
That works. Thanks.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Glitchy-Tozier** [comment]
It should probably be changed to the comma-key though, especially since the emoji-key will be removable soon.

**Comment by patrickgold** [comment]
> It should probably be changed to the comma-key though, especially since the emoji-key will be removable soon.

@Glitchy-Tozier This change is also included in the #119 PR, which will be released with v0.3.3.
