### ISSUE TITLE
Add keyboard tester floating button

### ISSUE THREAD

**Issue by Etim-Orb** [florisboard/florisboard#1517]
Afaik. currently there are no way to instantly test the keyboard after modifying settings. So I propose add a floating button that opens a keyboard and text testing enviornmet so we wouldn't have to open a browser for example to test the keyboard.

**Comment by min7-i** [comment]
This feature is already available in the current beta releases 0.3.14:

![Screenshot_20220122-132356.png](https://user-images.githubusercontent.com/97251923/150638515-b2d41ee6-8258-4ebb-8ee3-0de016e20b6f.png)
