### ISSUE TITLE
Fingerprint reader hardware not available (when AOSP keyboard is disabled)

### ISSUE THREAD

**Issue by bittner** [florisboard/florisboard#1520]
#### Short description

On Volla OS, when I install FlorisBoard and then disable the preinstalled AOSP Android keyboard the fingerprint reader stops working.

First, after doing the above, my lock screen would say, "Fingerprint reader hardware not available", every time I try to unlock the phone using my finger. After rebooting the device that message now has even stopped showing at all.

#### Steps to reproduce

1. On Volla OS (with your Volla Phone) configure your fingerprint reader (e.g. with fingers from your left and right hand)
2. Go to the F-Droid store and install FlorisBoard
2. Optionally, configure several keyboards (e.g. German, French, Italian)
3. Go to the Android settings (System ➜ Language and Input), configure FlorisBoard as the default keyboard
4. Lock the phone
5. Try to unlock the phone using your finger ➜ Phone unlocks, everything works fine.
6. Go to the Android settings (System ➜ Language and Input), deactivate the AOSP keyboard
4. Lock the phone
5. Try to unlock the phone using your finger ➜ The Volla lock screen says, "Fingerprint reader hardware not available" (red text at the bottom of the screen).
6. Reboot the phone, unlock with alternative method (e.g. swipe pattern)
7. Try to use the fingerprint reader ➜ The phone doesn't show any related activity anymore.
8. Go to the Android settings (System ➜ Languages and Input), configure the AOSP keyboard as an additional keyboard again, set it to the default keyboard again.
9. Fingerprint reader remains dead

#### Environment information

- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Device: Volla Phone
- Android: 10 (preinstalled Volla OS)

**Comment by patrickgold** [comment]
Thanks for your bug report!

I don't really know what to do with this issue, because I haven't seen anything in the Android docs that state that an IME does anything with the fingerprint reader, that's up to the OS to manage. Does the latest beta 0.3.14-rc02/03 also cause this issue?

**Comment by bittner** [comment]
It might be that this was a coincidence with a hardware defect. I had my device returned and repaired in the meantime.

I'll try out installing FlorisBoard again and reopen this issue if needed.
