### ISSUE TITLE
Swipe to left and delete word, not worked every time

### ISSUE THREAD

**Issue by daes10** [florisboard/florisboard#1522]
#### Steps to reproduce
1. Go to 'Gestures'
2. Click on 'Swipe to the left'
3. And click 'delete actual word'

#### Short description
Now when i swipe to the left, it doesn't delete the word. Sometimes it worked, but sometimes it won't. So i must swipe several times until it worked. This is is now a half year so. But earlier it worked well on my phone.

#### Environment information
- FlorisBoard Version:  v0.3.13
- Install Source:  F-Droid
- Device:  Huawei P20 Pro (CLT-L29)
- Android:  Android 10 (EMUI)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report. Please fill in the app-version.

**Comment by daes10** [comment]
> Thank you for your bug-report. Please fill in the app-version.

Yes of course, sry i forgot it!

**Comment by Glitchy-Tozier** [comment]
Thank you, let's see what Patrick can do when he gets around to checking out this issue!

**Comment by Albnu14** [comment]
Do u think it is caused by the default "swipe velocity threshold" setting? 

I faced a similar problem when setting the gestures of the spacebar, it seemed to accept a fast gesture ( 1900 dp/s) i changed it to 600 and now it works as expected

So @daes10 maybe changing the default from 1900 to another value can help?

**Comment by daes10** [comment]
> Do u think it is caused by the default "swipe velocity threshold" setting? 
> 
> I faced a similar problem when setting the gestures of the spacebar, it seemed to accept a fast gesture ( 1900 dp/s) i changed it to 600 and now it works as expected
> 
> So @daes10 maybe changing the default from 1900 to another value can help?

Yes, it worked! Thx for this hint, i dont saw this setting first.
