### ISSUE TITLE
Same hinted symbols layout as in gboard

### ISSUE THREAD

**Issue by LPW00** [florisboard/florisboard#1527]
Gboard's  layout is burnt into my brain. I tried to get used to floris board's default and I have a hard time, even though I've used it for quite while now (at least since august 2021). This has been the most annoying thing about the switch, actually. In most other points I either prefer floris board's way of doing things or just don't miss whatever gboard did.

My biggest issue is that the default layout is not as useful as it could be, at least when you have the number row enabled. And yes, I know that technically most of the symbols are still there, because floris has multiple symbols behind keys where gboard only has one. But I can't remember that layout, there's no visual indicator and who would guess that, for example, "<" and ">" are also hidden behind "k" and "l", which are indicated to have "(" and ")" behind them? It seems like it wouldn't be impossible to just put them behind "u" and "i", where they belong when the number row is present. 

I recently found that you can change between a few premade presets and I've tried the neo2 layout, but that one is just so far removed from what I'm used to that I found myself just using the symbols key.

So could we please have a gboard preset for the symbols?

I hope this is short and well explained enough.

**Comment by tsiflimagas** [comment]
I don't quite get what's the problem here, in exact. Is it that you haven't find a way to enable hinted symbols, or that there are no hinted symbols on the top row?

> for example, "<" and ">" are also hidden behind "k" and "l", which are indicated to have "(" and ")" behind them

They are not, hinted symbols for "k" and "l" are "(" and ")" respective, as indicated. Did it work differently when this issue was opened?

@xabelgul your suggestion should better be made in a new issue, so it can be tracked.

**Comment by LPW00** [comment]
> I don't quite get what's the problem here, in exact. Is it that you haven't find a way to enable hinted symbols, or that there are no hinted symbols on the top row?

The issue is that there are no hinted symbols in the top row.

> > for example, "<" and ">" are **also** hidden behind "k" and "l", which are indicated to have "(" and ")" behind them
> 
> They are not, hinted symbols for "k" and "l" are "(" and ")" respective, as indicated. Did it work differently when this issue was opened?

You missed a key word here. They are **also** behind a long press on k and l. Floris board is not utilizing the top row for hinted symbols and therefore the other rows have to have more symbols per letter than is necessary, which makes them less discoverable, because they're not hinted, they're just also there.
