### ISSUE TITLE
Apple Text Replacement

### ISSUE THREAD

**Issue by OpenSourceMovement** [florisboard/florisboard#1528]
Hi, I apologize if you get a lot of these but

wouldn't it be cool to add the text replacement feature from Apple?
Ex. foss => free and open source software

Looking forward to it if you do consider it :D

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your feature request!

To save some time on the dev's part, could you describe Apple's text replacement feature or share the link to a website that explains it well?

**Comment by Donkey-Doug** [comment]
This feature is already available, see https://github.com/florisboard/florisboard/issues/369.

However, maybe it is not in the latest beta due to a large code rewrite.

**Comment by OpenSourceMovement** [comment]
No way! 
Thanks!
