### ISSUE TITLE
Add the ability to access incognito/private mode from smart bar preventing the personal dictionary from learning new words 

### ISSUE THREAD

**Issue by jaywud** [florisboard/florisboard#153]

**Comment by patrickgold** [comment]
Thanks for your suggestion! So if I understood correctly, you want to be able to enable private mode temporarily from the Smartbar? Private mode is currently enabled either if the target app specifically requests it or if you force it in the advanced settings.

**Comment by jaywud** [comment]
My pleasure :) 
Correct, it's basically adding an option to enable incognito mode on demand (similar to swiftkey). Let's say i have the personal dictionary enabled with automatic learning, once i manually enable the incognito mode, the keyboard will stop adding any of the typed words to the personal dictionary and suggestions.

**Comment by patrickgold** [comment]
Ok thanks for confirming. I will place it on my todo list, should be implemented after I implement composing suggestions.

**Comment by Glitchy-Tozier** [comment]
I guess one way to implement this is by always placing the incognito-button on the top-right, and then just letting the user click on it to turn it off and on.

**Comment by patrickgold** [comment]
> I guess one way to implement this is by always placing the incognito-button on the top-right, and then just letting the user click on it to turn it off and on.

Could be the way to go, if I make the private mode button like a Smartbar button if the private mode is inactive and if it is active it is purple (or the configured color in Theme Settings).

> A second way would be to add it to the quick actions.

Quick actions is already full in terms of space left in the UI.

**Comment by Glitchy-Tozier** [comment]
> Could be the way to go, if I make the private mode button like a Smartbar button if the private mode is inactive and if it is active it is purple (or the configured color in Theme Settings).

Exactly. 
Also, I think users should be able to turn off this feature. having that omnipresent button there might make the top-bar feel cluttered.

**Comment by patrickgold** [comment]
Above linked PR reworks the incognito mode as parts of the Smartbar actions rework. With this incognito mode can now be toggled via the incognito quick action (if incognito is set to dynamic in Settings > Advanced > Incognito mode). For apps that request it it will still always be on. If you want to permanently force incognito on or off you can use the aforementioned setting to do that.

This will be released in 0.4.0-alpha03. Thanks again for suggesting!
