### ISSUE TITLE
Community theme support

### ISSUE THREAD

**Issue by stpnwf** [florisboard/florisboard#1532]
I came to the github to check how far until Material You and Material Design 3 elements are supported and learned that there are plans to greatly improve theme customization. Yay. It sounds like users will be able to customize shapes of icons, spacing and a lot more if I understand correctly. 

Therefore, I would like to suggest the addition of a section where users can choose between themes made by other users. Similar to how the app [Your Calendar Widget](https://play.google.com/store/apps/details?id=de.mash.android.calendar&hl=en_US&gl=US) does it. Screenshot below.

I reckon that the majority of users will lack the knowledge necessary to edit some of the more complex options that will be available under the Advanced and Developer modes... But by being able to download complex themes made by other users, they would be able to customize it to their liking through the Basic and Advanced modes fairly easily.

As a bonus I would like to suggest the addition of a search feature with an option to search/filter by tags. Such as Material Design 3, Samsung Keyboard, etc.

I think this would greatly improve the user experience while taking the most out of the upcoming expansion of the theme engine!

![Screenshot_20220202-191612_Your Calendar Widget](https://user-images.githubusercontent.com/81482539/152247096-74dc5fa3-0954-4a8c-86d8-7dde9f7307fd.png)

**Comment by patrickgold** [comment]
The official addons store will allow community themes and everything related to it, see https://github.com/florisboard/florisboard/issues/2468 for more info as it is the implementation effort thread now. Closing to avoid duplicate discussions around this.
