### ISSUE TITLE
Add select text option

### ISSUE THREAD

**Issue by Pranab009** [florisboard/florisboard#1534]
Please add "Select text" option by  
Delete key swipe left.
If you add this then it can easily select texts for copy paste.
And you can delete selected text by using delete key.

Or Add this feature (select text) by 
Go key swipe left.

![Screenshot_20220203-083926_1](https://user-images.githubusercontent.com/65340361/152294111-c0c29b91-6402-4e92-bb49-3b0e1e1ab9a9.png)

**Comment by Donkey-Doug** [comment]
You can select text by holding shift and swiping acoss the space vbr.

**Comment by Pranab009** [comment]
That is not handy.and this is not possible with one hand.

**Comment by patrickgold** [comment]
Above commit adds the option to select text either by characters or by words with the delete key. Will be available in the next beta release 0.3.14-beta10. Thanks again for your suggestion!

**Comment by Pranab009** [comment]
Thankyou.♥
