### ISSUE TITLE
Blank settings screen

### ISSUE THREAD

**Issue by nhfo** [florisboard/florisboard#1537]
#### Short description
Seetings screen remains blank, nothing is visible at all. No matter how I open settings screen, launcher icon or any settings key in keyboard itself, the behavior is same.

I also tried clearing app data, but it had no effect.

#### Environment information
- FlorisBoard Version: 0.3.14-beta09
- Install Source: GitHub
- Device: Oneplus X
- Android: 6.0.1, stock

**Comment by patrickgold** [comment]
I do not own an Android 6 device, but I just ran FlorisBoard on an emulated Android 6 device without issues. Is this issue new with beta09 or was it also present in previous beta releases?

**Comment by nhfo** [comment]
It should be a new issue. In the previous beta keyboard remained blank. IIRC settings screen did work fine (i can double check if needed).

I was trying random things and managed to find  a workaround. If i  force stop app/remove it from recent apps and then open settings screen then it does show up and works fine thereafter.

**Comment by min7-i** [comment]
I think I might have experienced the same issue on a device with Android 9 and I was also able to reproduce it with a virtual device running Android 12.

For me it only happened when clean installing beta 9 or higher. When updating the app it works as expected.

Steps to reproduce the issue:
1. Uninstall FlorisBoard beta.
2. Install beta 9 or higher.
3. Open the app => you will see a blank screen similar to this one: ![Screenshot_20220213-201745.png](https://user-images.githubusercontent.com/97251923/153771030-c937a568-fafa-4927-8ad7-22f924689c2c.png)


As mentioned by nhfo when I close the app via the recent apps menu and then reopen it, it works.

**Comment by patrickgold** [comment]
Thanks @ min7-i for the additional info you provided, I can confirm and reproduce this issue now every time I do a clean install on any emulator instance. Seems like an automatic first time setup issue.

**Comment by patrickgold** [comment]
Already found the bug, it is within my preference library: When first loading the preferences, no file exists, but the loader still wants to read the file, thus crashing and getting stuck silently. Need to update the preference library in order to fix this issue.

**Comment by patrickgold** [comment]
Above commit should fix the blank screen, at least I could not reproduce the blank screen on my device anymore. Should this issue still be observed after this fix is shipped please report it, and I will have to investigate if there are further issues on initial setup.

This fix will be shipped with 0.3.14-beta12. Thanks again for reporting!

**Comment by GoRaN909** [comment]
> Above commit should fix the blank screen, at least I could not reproduce the blank screen on my device anymore. Should this issue still be observed after this fix is shipped please report it, and I will have to investigate if there are further issues on initial setup.
> 
> This fix will be shipped with 0.3.14-beta12. Thanks again for reporting!

I tested the Artiacts debug apk i can confirm that the blank screen bug was fixed 👌 ... Thanks

**Comment by patrickgold** [comment]
Thanks for testing it out and confirming the fix!
