### ISSUE TITLE
Settings follow system theme - amoled black

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1539]
I would like to follow system theme, but set dark option to be amoled black.

 an implementation in which the user can choose for:

    Light theme
    Dark theme
    Follow system settings

And finally, dark theme should have an option for dark grey and pure black.

**Comment by patrickgold** [comment]
Above PR adds an option to the Settings UI theme option to select "System default (AMOLED)". In this mode, the Settings UI will be pure black if the system dark mode is enabled. A manual AMOLED dark option is already present in the latest beta. This will be released in 0.3.14-beta12. Thanks for suggestiong this!
