### ISSUE TITLE
Make delete-swipe more similar to the one in OpenBoard

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#154]
1. In OpenBoard, delete-swipe works a little differently. If you swipe left, then swipe all the way to the right, no text is selected.
In FlorisBoard, you can't completely reverse your deletion
-selection... at least sometimes you can't.
I think the OpenBoard-behavior makes more sense because... well... the user returned to his original position with his thumb. Thus nothing should be selected&deleted.

2. (Openboard's delete-swipe deletes more / is faster. In my opinion, that is better.
Of course spacebar-swipe and delete-swipe should have the same speed though)

**Comment by patrickgold** [comment]
Yeah I know the whole gesture implementation is far from perfect, especially the moving swipe actions (actions that happen repeatedly while moving the touch down pointer). The amount of characters you select/deselect is dependent on how fast you swipe and how high the CPU load is. I can try to independently calculate the "should-be" selected characters and then apply this rather that 1 character per event firing, to make this behavior more consistent.

**Comment by Glitchy-Tozier** [comment]
Another weird thing i just noticed:
You said the swiping speed changes how many characters get deleted. That's fine in my opinion, but it works exactly in the opposite way i would expect.

If I swipe slowly, i can delete a lot more than if i swipe fast.

**Comment by Glitchy-Tozier** [comment]
@patrickgold If you want feedback, this is actually the most important issue right now, in my opinion.

Maybe that's just me being spoiled by OpenBoard though...

> The amount of characters you select/deselect is dependent on how fast you swipe and how high the CPU load is. I can try to independently calculate the "should-be" selected characters and then apply this rather that 1 character per event firing, to make this behavior more consistent.

Sounds like a new implementation is needed. Do you know how other keyboards approached this issue?

**Comment by patrickgold** [comment]
@Glitchy-Tozier Above PR makes the behavior of the precise character deletion way more consistent and improves the speed and accuracy. You can now select X characters and also unselect them fully like in OpenBoard. Will be included in today's release v0.3.4!

**Comment by Glitchy-Tozier** [comment]
Perfect!
I'll do my best to give feedback as soon as 0.3.4 hits the play-store!
