### ISSUE TITLE
Option to make Primary Smart bar as Secondary

### ISSUE THREAD

**Issue by FrozenVertx** [florisboard/florisboard#1540]
Hi,
![floris](https://user-images.githubusercontent.com/72699730/152466294-ce56f7f9-c492-4858-89e5-f4350ed458a7.jpeg)
![floris2](https://user-images.githubusercontent.com/72699730/152466477-c22e2c56-1109-40a8-984f-83d8fd030c83.jpeg)
As you see in current layout when I collapse 2nd row ,there is only primary row.
I just want to interchange primary and secondary because we often use secondary row options like cut,paste,select all,move cursor,etc more than opening florisboard setting ,using one handmode,viewing emoji from smartbar( i mean there is itself option beside space bar).
That's why I want to interchange them or atleast give option to choose which row I want to make secondary and which primary.

I hope you understand

**Comment by Krusty27** [comment]
Similar to #1439

**Comment by patrickgold** [comment]
I am currently working on this feature, please see #1548 (same proposal) for details. Closing this to prevent duplicate threads.
