### ISSUE TITLE
Cannot edit "System User Dictionary" or "Internal User Dictionary"

### ISSUE THREAD

**Issue by TheHawaiianKoala** [florisboard/florisboard#1544]
#### Short description
Using the latest beta, going into User Dictionaries and trying to open System or Internal User Dictionaries does nothing. So you cannot add or edit words 

#### Steps to reproduce
1. Open Florisboard Settings
2. Go to User Dictionaries
3. Tap on "Manage system user dictionary" or "Manage internal user dictionary"
4. Nothing happens

#### Environment information
- FlorisBoard Version: v0.13.4beta09
- Install Source: Fdroid
- Device: OnePlus 7T
- Android: 11

**Comment by min7-i** [comment]
A few weeks ago I mentioned this in the feedback thread / discussion about the current beta releases.

See Patrick's comment [here](https://github.com/florisboard/florisboard/discussions/1235#discussioncomment-1932043).

**Comment by TheHawaiianKoala** [comment]
Noted, but I think this issue should remain open and I will close it once it gets fixed

**Comment by patrickgold** [comment]
Above linked PR re-implements the user dictionary UI for managing the internal and system user dictionary. Will ship with 0.3.14-beta12
