### ISSUE TITLE
Smartbar: add option to change between primary and secondary row

### ISSUE THREAD

**Issue by saloniamatteo** [florisboard/florisboard#1548]
Hello,
I have downloaded the lastest FlorisBoard beta (beta 09). I have noticed that the smartbar has been reworked, however I noticed that the behaviour is very different from the previous beta.

What I noticed is the addition of another button that expands the smartbar. However, in the smartbar options there is no way to flip the "active" and the "secondary" row.

What I mean is, in the previous beta, the active buttons were: undo/redo, select all, copy, cut, move left/right, clipboard. However, with the new beta, the order has been borked.

Can you please add a way to restore the original behaviour (e.g. no collapse/expand button), and/or a way to change the order of the "active"/"primary" and "secondary" rows, and/or a way to modify which actions are on which rows.

Thanks in advance,
Matteo

**Comment by saloniamatteo** [comment]
Images for clarity:

Original (wanted behaviour):
![original_behaviour](https://user-images.githubusercontent.com/28765699/152681093-88992846-2d12-4c36-bbf3-95396c162d6c.png)

New smartbar (collapsed):
![new_smartbar_collapse](https://user-images.githubusercontent.com/28765699/152681137-aa8b1c4a-f62a-44d9-a9b5-00da8ca87205.png)

New smartbar (expanded):
![new_smartbar_expand](https://user-images.githubusercontent.com/28765699/152681092-a04094e3-fe81-4d30-99c0-46d5385b38c0.png)

**Comment by patrickgold** [comment]
Above commit is the draft PR for allowing to switch out the clipboard row with the action row and also to improve the smartbar settings screen in general. I need to fix themeing a bit and also make some other minor adjustments, but other than that this will be the Smartbar implementation for 0.3.14-beta14.

**Comment by saloniamatteo** [comment]
Thank you! 😄
