### ISSUE TITLE
"Follow system" and "Follow time" theme modes don't trigger on change

### ISSUE THREAD

**Issue by seankhl** [florisboard/florisboard#1557]
#### Short description
Setting theme to "Folow system" or "Follow time" initially sets the theme correctly based on the system theme or time respectively, but a theme switch does not take place when the system theme changes or time goes from day to night (or vice-versa). Toggling the theme mode to something else and back fixes the problem, but defeats the purpose of having the "follow" modes in the first place.

#### Steps to reproduce
1. Set the "Theme mode" to "Follow System"
2. Change the system theme from day to night (dark to light, w/e)
3. Notice that the Florisboard settings theme has changed, but the keyboard theme itself hasn't, even in the "Try out your setup" preview.

#### Environment information
- FlorisBoard Version: 0.3.14-beta10 (66)
- Install Source: F-Droid/GitHub
- Device: Xiaomi Mi 6
- Android: LineageOS 18.1 (Android 11)

**Comment by patrickgold** [comment]
Thanks for your bug report!

I can fully reproduce this issue. My fix will probably be to check if the time/system theme has changed when the keyboard window is shown, which should be more than sufficient. The alternative would be to post an update job which runs every x seconds, but that is much more battery-consuming and thus not favorable.
