### ISSUE TITLE
Plz add feature in clipboard group similar like chrome tabs in groups 

### ISSUE THREAD

**Issue by gsweeh** [florisboard/florisboard#1558]
Plz add feature in clipboard group similar like when we use chrome browser they give feature like tabs in groups that we can categorize tab in group so i want that feature clipboard with group system like in one group all gmails and others group password or something else that we can manage according to us
 
i hope that u can add this feature 

i like yours app

**Comment by tsiflimagas** [comment]
The idea sounds nice, but it also sounds like creating a notes app inside the keyboard, which seems to be going too far from the original purpose.

**Comment by naiksaitan** [comment]
But it handy to users within keyboard we can paste anything of the text other than going to notes then copy then paste plz look into this i need this feature badly

**Comment by tsiflimagas** [comment]
> But it handy to users within keyboard we can paste anything of the text other than going to notes

That's not a valid argument in my opinion. In the past, a user requested to add a qr code scanner in the app because it was handy for him in some use case. Of course it was rejected. The answer was that if someone wants a qr code scanner, he should install one. For me, the same applies here.

**Comment by patrickgold** [comment]
Thanks for your feature proposal!

I am going to have to agree on this with @ tsiflimagas, adding tabs to the clipboard history makes it more and more a notepad. I know that this sounds appealing to some, but if I were to add tabs and other notepad-like features I wouldn't do that in the clipboard history but in a separate keyboard screen called "Notepad". Anyways, I do not plan to add a notepad to FlorisBoard anytime soon or ever, so I will have to reject your proposal, I am sorry.
