### ISSUE TITLE
Key borders

### ISSUE THREAD

**Issue by Radd-max** [florisboard/florisboard#156]
could you add an option to remove key borders ? atleast for me it makes a major diffrence in the look and feel of the keyboard . this is the option available in gboard . 
![key-borders](https://user-images.githubusercontent.com/62344221/104114904-7f586580-532f-11eb-99b5-d39d392fd438.jpg)

**Comment by patrickgold** [comment]
Thanks for the suggestion! This has actually already been implemented by yashx in #118 (but not yet released). As soon as I finish with the theme engine rework, v0.3.3 will be out and together with that the option to hide key borders.
