### ISSUE TITLE
Show native language or custom name on space key

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1568]
Hi @patrickgold could you please add new algorithm to the KeyboardView to show the languages native name or use a custom LABEL for each languages that available on FlorisBoard like two other keyboard Gboard and Swiftkey has been used for language names instead of system language name for example they used custom label (کوردی) for my native language Kurdish, But on the Floris does not support using custom labeled for language name is just show the device language name I'm use English for my device it shows as (Central Kurdish) that's a long name of branch the common and standard name is (کوردی) on the older version 3.13 i used this on language tag (   "languageTag": "کوردی"  ) also i added this new line (   "languageLabel": "کوردی"  ) on the config.json file  but by this way doesn't worked on keyboard app is show (null or und) on the space bar instead of (کوردی), This maybe need to other languages like Spanish or French because native name of them is (Español and Français) but is shows Spanish and French on the space key and also on the language list.

Please let us use custom label for language names like Gboard and Swiftkey do on there keyboards.

Sorry for my bad English :(

Regards.

Here is some screenshot of all three keyboards:

GBoard:

![Screenshot_20220212-214108_Samsung Notes](https://user-images.githubusercontent.com/3160786/153724673-7d33dcb6-7b1c-4e6d-bd1b-131bd14e78ea.png)

SwiftKey

![Screenshot_20220212-214038_Microsoft SwiftKey Keyboard](https://user-images.githubusercontent.com/3160786/153724677-c7717d4b-ad93-43e0-baa0-c81c02ba2c0c.png)

FlorisBoard

![Screenshot_20220212-214354_FlorisBoard Beta](https://user-images.githubusercontent.com/3160786/153724688-5bee7787-74d1-4fe1-9bae-f503fc32ce8e.png)

**Comment by patrickgold** [comment]
Thanks for your suggestion! I like this idea, will implement it tomorrow before I release 0.3.14-beta12.

I have a question though: As this problem with the language name thingie is app-wide and not specific to the space bar, would it be sufficient if I add an app-wide toggle for this, so all languages in the app and keyboard UI are displayed either in system language (English in above screenshots) or the local name of that language? If not I can add it just for the space bar, technically this does not pose a problem.

**Comment by GoRaN909** [comment]
> Thanks for your suggestion! I like this idea, will implement it tomorrow before I release 0.3.14-beta12.
> 
> I have a question though: As this problem with the language name thingie is app-wide and not specific to the space bar, would it be sufficient if I add an app-wide toggle for this, so all languages in the app and keyboard UI are displayed either in system language (English in above screenshots) or the local name of that language? If not I can add it just for the space bar, technically this does not pose a problem.

Thank you for accept my proposal! 

Bro look in the advanced settings screen is show the correct native name of language کوردیی ناوەندی that equal to Central Kurdish

![Screenshot_20220214-025903_FlorisBoard Debug](https://user-images.githubusercontent.com/3160786/153781442-8f30d78c-3a34-409f-93b0-9f28f30946a6.png)

But on the language and layout screen it doesn't show the name that shows on app language screen it's just show by system language name Central Kurdish *because I'm using English language for my device, That need to by correct and show native name or we can use a short label for it کوردی instead of long کوردیی ناوەندی on the space key and when user wants to add a language to there layouts 

Here is the language and layout screen when you want to add new languages for the list it show English name (Central Kurdish) instead of native name (کوردیی ناوەندی) or custom short label (کوردی)

![Screenshot_20220214-030015_FlorisBoard Debug](https://user-images.githubusercontent.com/3160786/153781714-a38658af-111c-44c0-b0b6-e10e2aad4836.png)


And this one is after added the language and layout 

original screenshot
![Screenshot_20220214-030233_FlorisBoard Debug](https://user-images.githubusercontent.com/3160786/153781806-bf4f83f0-2865-4874-b070-038473f9c88a.png)

Edited screenshot that i talking about on this issues need to be like this one i edited below:

![Screenshot_20220214-030233_FlorisBoard Debug](https://user-images.githubusercontent.com/3160786/153782197-73085faa-46ec-40a8-afae-86fb50c357ce.png)


I hope you understand me sorry for boring you.

**Comment by patrickgold** [comment]
Above commit adds a language name display toggle in "Languages & Layouts", which allows you to switch the language name between system and native. This option is valid for all language names across the Settings UI and on the Space bar.

This option will be available in 0.3.14-beta12 later today. Thanks again for suggesting!

**Comment by GoRaN909** [comment]
Thank you so much for adding this option i tested the debug apk i like it thanks again 💙
