### ISSUE TITLE
Move two characters on a Persian keyboard

### ISSUE THREAD

**Issue by Mahantor** [florisboard/florisboard#1571]
In Persian, after the ( ا ) character, the ( آ ) character is the most widely used, but it is difficult to access it on the keyboard.
Please replace character ( ا ) with the specified character to make it easier to access.
![IMG_20220213_172130](https://user-images.githubusercontent.com/91434001/153761528-8be83136-bbfe-4f11-8215-68f7259dc4cc.jpg)
![IMG_20220213_172619](https://user-images.githubusercontent.com/91434001/153761537-128e459b-e237-4801-92cb-cdf5543a3847.jpg)

**Comment by H3n-beep** [comment]
+1
