### ISSUE TITLE
Reverse cursor movement in Persian

### ISSUE THREAD

**Issue by Mahantor** [florisboard/florisboard#1575]
#### Short description
The problem that exists in the Persian language is the possibility of selecting and scrolling between letters in reverse. What can be done? Is it possible to solve this problem?

#### Steps to reproduce
1. Go to persian keyboard
2. Write any thing in english and persian language
3. Move cursor by space key or use delete key

#### Environment information
- FlorisBoard Version: 0.3.14_beta11 and 0.3.13
- Install Source: GitHub
- Device: xiaomi Note 9 pro
- Android: Android 11 Stock

https://user-images.githubusercontent.com/91434001/153766331-ecbf0d4d-267a-4518-aa57-5056b5f77181.mp4

https://user-images.githubusercontent.com/91434001/153766369-a6b06b24-d78c-484c-90fe-e3aa2bfe4beb.mp4

**Comment by tsiflimagas** [comment]
So, what you want is to have the same behavior you have in English? If so, I get it for moving the cursor, but not for deleting/selecting text. Isn't it how it should be done?

**Comment by Mahantor** [comment]
I think moving the cursor, like English, also solves the problem of deleting / selecting text, right?
Or am I wrong?

**Comment by tsiflimagas** [comment]
Selecting text I connected to moving the cursor, but deleting isn't. What I said is different though. I don't see (or maybe I don't get it) a problem with the behaviour of deletion. I think it should be inverted, as it is. I also tried it on Gboard and it works like that.

**Comment by Mahantor** [comment]
Yes you are right
I do not know much about programming
Please do whatever you deem appropriate
Thankful

**Comment by patrickgold** [comment]
Above commit fixes the cursor movement for RTL text inside the preview field text, will be shipped with beta14 soon.

**Comment by patrickgold** [comment]
Note that mixed LTR/RTL messes up cursor movement, but that's something I can't avoid and where I have to wait until the devs of Jetpack Compose fix it. Will close this issue as fixed. Thanks for reporting!
