### ISSUE TITLE
Add colemak dh or custom layout.

### ISSUE THREAD

**Issue by bemyfrnd** [florisboard/florisboard#1577]
Hello,
I currently use colemak layout and love the keyboard! But I would love if there was a colemak dh mod (which has like 4 letters different than regular colemak) or the ability to put together a custom layout.
Thank you!

**Comment by Glitchy-Tozier** [comment]
A PR is on its way: https://github.com/florisboard/florisboard/pull/1401

**Comment by patrickgold** [comment]
Yup there's a PR for this request, but it uses the old layout format. I have to adjust the layout format of the PR's changes so the current layout engine can properly work with it, so I can merge the changes.
