### ISSUE TITLE
Hide app icon.

### ISSUE THREAD

**Issue by XXDRD** [florisboard/florisboard#1581]
It would be a nice feature to have,  to hide app icon from the launcher.

**Comment by Ilithy** [comment]
I think this is a feature of the launcher (some offer it via a long press on the app icon -> Hide), and not of the applications, it's easier to implement it in the launcher rather than in each application, but the idea is good :)

**Comment by TheHawaiianKoala** [comment]
It is already included in 0.3.14-beta, but the icon cannot be hidden for Android 10+ due to system restrictions.
![Screenshot](https://user-images.githubusercontent.com/97790626/154685440-b8d0677f-dc65-4691-8f48-6ce6fb09343f.png)

**Comment by patrickgold** [comment]
Thanks for your feature proposal!

As FlorisBoard is not a system-preinstalled keyboard, I cannot hide myself from the list of applications in Android 10+. If your launcher allows it there may be the option of doing so, other than that this there's no option to hide the app icon, I am sorry.
