### ISSUE TITLE
Add a dedicated button for clipboard

### ISSUE THREAD

**Issue by NonJenish** [florisboard/florisboard#1583]
-->i have to acces the clipboard by holding on a word,i think there should be a button for that

**Comment by tsiflimagas** [comment]
Thank you for your proposal, but to be honest, I can't quite get your idea. Could you provide some more information about your thought? What do you want exactly to happen when selecting text (a word or any amount)?

**Comment by NonJenish** [comment]
Like you have a clipboard button on swift key, it lets me view all texts i
copied, i didnt find that in floris board, you only get clipboard option
when you select the text. i hope im clear

**Comment by tsiflimagas** [comment]
Oh, now I see. So what you want is a button to access clipboard history. Have you enabled clipboard history in settings? If you do, then you'll get a button on the smartbar, and you'll be able to access it also by longpressing the enter button and selecting the clipboard history option.

**Comment by rancidfrog** [comment]
@NonJenish 
@tsiflimagas is correct.
There is a button:
![](https://i.imgur.com/0Rygdx5.jpg)

You click it and it takes you to clipboard history,
![](https://i.imgur.com/h6ckbqe.png)

 You do not need to hold on to anything, not even beer.

**Comment by patrickgold** [comment]
@NonJenish as I can see from the screenshot you provided it seems that you are still using 0.3.13. If you long-press the enter key there you can also access the clipboard history, always. In the smartbar the clipboard history button is only then visible if text is selected (this changed a bit in the latest betas)

I suggest that you try out the latest beta 0.3.14-beta12, where the clipboard history UI is much more stable and helpful (in the event it is disabled or your device is locked, a proper message is displayed.

**Comment by patrickgold** [comment]
As there's missing further info on this topic and the latest betas have a dedicated clipboard history button in the Smartbar I will close this issue. Should any more details for this topic come up you can post it here.

**Comment by NonJenish** [comment]
Ohh yesss, thank you very muchhh for your help❤️❤️
