### ISSUE TITLE
smart bar inconsistent across phones

### ISSUE THREAD

**Issue by scrollop** [florisboard/florisboard#1584]
On an honor view 10 (android 10) with "display suggestions" on, the smart bar either shiws the undo/redo/emoji/etc buttons, or you can switch to suggestions. The very useful clipboard functions (select all, copy paste etc) are missing (these are kife usedul then undo redo etc). Tutning off suggestions brings baxk the clipboard functions. Perhaps this is intentional? If so, can we choose which collectio of smart bar functions we can choose (eg. Undo bar, clipboard bar and/or suggesrions)?

On an xperia 5 II when suggestions is on, they dont appear, so thr clipboard functions are available.

Great keyboard, thank you!

**Comment by patrickgold** [comment]
In the latest beta 0.3.14-beta13 you can choose to have a secondary Smartbar row, so you are able to display suggestions and clipboard cursor tools at once. In the upcoming beta14 you will also be able to switch actions and the clipboard cursor row.

As such, I think we can close this issue as already implemented, if it is okay for you.
