### ISSUE TITLE
App freeze when you want add new word to system user dictionary 

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1585]
#### Short description
As defined on tittle the bug on User dictionary 

#### Steps to reproduce
1. Go to 'User dictionary'
2. Click on 'Manage user system dictionary 
3. Scroll down to 'Add word'

https://user-images.githubusercontent.com/3160786/154804970-3ee61442-3baa-45c5-899b-79364005d3c5.mp4

#### Environment information
- FlorisBoard Version: 0.3.14-beta12 (68)
- Install Source:  Github
- Device: Galaxy S20 Fe 5G
- Android: Android 12 OneUI 4 Rooted

**Comment by patrickgold** [comment]
Thanks for your bug report!

Does the current stable version 0.3.13 also freeze when you add a system dictionary entry?

**Comment by GoRaN909** [comment]
> Thanks for your bug report!
> 
> Does the current stable version 0.3.13 also freeze when you add a system dictionary entry?

Yes it's same thing when you want add new word the app is crashes on stable version 3.13

Here is the crash report 

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-G781B
- Android: 12 (cn=S sdk=31)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1645447937302.stacktrace</summary>

```
java.lang.IllegalArgumentException: Unknown URL content://user_dictionary/words
	at android.content.ContentResolver.insert(ContentResolver.java:2196)
	at android.content.ContentResolver.insert(ContentResolver.java:2162)
	at dev.patrickgold.florisboard.ime.dictionary.SystemUserDictionaryDatabase$dao$1.insert(UserDictionary.kt:432)
	at dev.patrickgold.florisboard.settings.UdmActivity.processInput(UdmActivity.kt:447)
	at dev.patrickgold.florisboard.settings.UdmActivity.showAddWordDialog$lambda-12$lambda-11(UdmActivity.kt:365)
	at dev.patrickgold.florisboard.settings.UdmActivity.$r8$lambda$o0pxw42QMSFzmjQqObHP_e2sOK8(Unknown Source:0)
	at dev.patrickgold.florisboard.settings.UdmActivity$$ExternalSyntheticLambda4.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7792)
	at android.widget.TextView.performClick(TextView.java:16045)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30184)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8641)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

```
</details>

**Comment by patrickgold** [comment]
Hmm seems like your device does not have a system dictionary available. If you go to System Settings > Language & Input, do you have an entry called "Personal Dictionary" available?

**Comment by GoRaN909** [comment]
I tried the GBoard for adding new word but doesn't worked it just a blank screen looks like the Samsung is removed Personal user dictionary is you meation above thats a stupid thing samsung removes that helpful feature from there devices 😐

![Screenshot_20220221-185337_Settings](https://user-images.githubusercontent.com/3160786/154989209-8936b1f9-fc45-4c1a-91c4-0e6ff278a93c.png)

**Comment by GoRaN909** [comment]
Hello I tried this on two other brand (Huawei and Xiaomi) and worked perfectly without any crash or errors and shows on the suggestion bar the problem is the Samsung OneUI they are removed the Personal Dictionary :( ...

So i will close this issues it's NOT the FlorisBoard error.

Thanks for your replays.

**Comment by patrickgold** [comment]
Thanks for bringing this to my attention though, so in the future I know why the system user dictionary does not work on Samsung devices!

The good thing is that FlorisBoard offers the internal user dictionary, which can act as a replacement and workaround, even though it does not have all the benefits of the system dictionary.

**Comment by GoRaN909** [comment]
> Thanks for bringing this to my attention though, so in the future I know why the system user dictionary does not work on Samsung devices!
> 
> The good thing is that FlorisBoard offers the internal user dictionary, which can act as a replacement and workaround, even though it does not have all the benefits of the system dictionary.

You welcome bro i have a good news about Personal Dictionary :), Yesterday i was revert back to Stock Samsung OneUI Rom and unrooted my device now I'm running on Stock Rom I tested the system user dictionary on florisboard it worked without any app freeze or crash also i was able to add new words to the user personal dictionary i think the ERROR is appear user ROOT his/her device the Personal Dictionary feature on Samsung devices it Secured by Knox just like all other Samsung apps e,g: (Samsung Pass, Pay, Health & Secure Folder too) the personal system dictionary is just working when you run on stock  untouched Android and OneUI Rom.

Best regards.

**Comment by patrickgold** [comment]
Hmm yeah in this case its the rooting of the device which seems to break the encryption of the personal dictionary maybe?

Anyways, if it at least works for default Samsung ROMs that's more important. Thanks for coming back to me about this topic!
