### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by PowerMan2206** [florisboard/florisboard#159]
It's a stupid question, but how do I compile Florisboard into a .apk file?

**Comment by patrickgold** [comment]
To compile FlorisBoard yourself into an APK, you need a 64-bit PC with Android Studio installed (can be Windows, Mac or any supported Linux distro). See https://developer.android.com/studio#downloads for supported platforms.

Then in Android Studio, you may have to install several SDK tools required to build FlorisBoard, but Android Studio will prompt you to do so automatically. Then you can go to Build > Build Bundles / APKs > Build APKs and Android Studio builds a release type but unsigned APK of FlorisBoard. This APK can then be manually copied to your device and installed or quickly installed via ADB (Android Device Bridge).

**Comment by PowerMan2206** [comment]
Ah, I see. Thanks
