### ISSUE TITLE
Split keyboard for landscape like one ui keyboard

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#1590]
![Screenshot_20220221-121449_Finder](https://user-images.githubusercontent.com/93302440/154902884-5265eaf7-1f51-420e-8e76-ca3e456893b1.jpg)

I hope this screenshot makes everything clear.  Please implement this.it is very handy, atheist for me 😅

**Comment by ssssamstrup** [comment]
Yep, it would be really great for tablets!

Samsungs keyboards way of letting you change the position, width and height is also really neat, so steal that if it's feasable. 😊

![Screenshot_20220630-075436_Samsung Keyboard](https://user-images.githubusercontent.com/4302516/176603007-124993cb-be10-4cb7-a336-c4a2111a12a0.jpg)

**Comment by sevmonster** [comment]
I use a Pixel 6 Pro now and have found that while I previously used landscape typing all the time, I rarely do anymore because even my long fingers find accessing the middle of the screen cumbersome. So this is helpful for bigger phones (most flagships nowadays) and not just tablets.

**Comment by lm41** [comment]
Duplicate of #200
