### ISSUE TITLE
Capslock stuck on Termux

### ISSUE THREAD

**Issue by OilSubjectLoss7** [florisboard/florisboard#1596]
The Capslock won't unset itself to lower or UPPER case.
it's lock in it's state unless i click the shift key annoyingly a couple times.
it's specifically apparent when you want to go lower case from big case. it's stuck and i had to click it several times to go lower.

i only observed this behavior when using TERMUX app

**Comment by tsiflimagas** [comment]
Thanks for your report! This issue was fixed at some point on the 0.3.14-betaxx road, so you can try out the latest beta and confirm whether it's ok for you.

**Comment by tsiflimagas** [comment]
Nevermind, it's a duplicate of #1010.
