### ISSUE TITLE
Ability to add name for custom layouts

### ISSUE THREAD

**Issue by OilSubjectLoss7** [florisboard/florisboard#1599]
It's really hard to tell which is which.

**Comment by Yurieaijoker** [comment]
You can already

**Comment by Yurieaijoker** [comment]
![Screenshot_20220225_230627_dev patrickgold florisboard beta](https://user-images.githubusercontent.com/93813352/155738322-d92b2098-30b7-4d9d-996c-274d38722e20.jpg)
![Screenshot_20220225_230634_dev patrickgold florisboard beta](https://user-images.githubusercontent.com/93813352/155738336-aa7af6f6-67a9-45a9-ba5c-57cc5b4cc403.jpg)

**Comment by Yurieaijoker** [comment]
I'm using latest beta

**Comment by patrickgold** [comment]
Thanks for your proposal! as @ Yurieaijoker already described it is already possible in the latest 0.3.14 beta version. Closing this proposal as already implemented thus.
