### ISSUE TITLE
How to change suggestions to another language?

### ISSUE THREAD

**Issue by zpcol** [florisboard/florisboard#16]

**Comment by patrickgold** [comment]
Hi zpcol,

suggestions are currently not available in any language. The suggestions you see are only a placeholder in the UI. Later on suggestions will automatically be displayed for the language selected for the current subtype (if available). Hope I could answer your question.

Have a nice day,
Patrick

**Comment by zpcol** [comment]
can you add Indonesian language?

**Comment by patrickgold** [comment]
As I stated in #24 and in [README.md](https://github.com/florisboard/florisboard/blob/master/README.md), composing suggestions are currently **not available in any language**. I plan to implement them in v0.4.0 or v0.5.0.

**Comment by LongJohn-Silver** [comment]
I think it will be very important to differentiate between languages/dialects when giving suggestions, which is my main issue with some of the other libre keyboards out there (like OpenBoard), they have global suggestions, which tends to be more annoying than helpful. I know you mentioned this above, but I wanted to remark the importance of this.

**Comment by patrickgold** [comment]
@LongJohn-Silver You make a very good point in your comment above and I know how annoying useless suggestions can be. The problem I think most libre keyboards have and I will also face is to find a reliable, accurate and free data source which is compatible with the projects license and which allows you to ship the data within the app's APK. It is difficult enough to find dictionaries for general English, German, etc. (word lists alone are useless, you need some form of frequency metric, maybe also next word pairs) but finding dialect-specific dictionaries is near impossible without paying license costs. Of course I don't know exactly yet, I've just searched the net generally, but this is the biggest hurdle in implementing suggestions.

**Comment by LongJohn-Silver** [comment]
Would it be to hard to help building one while using FlorisBoard? Like an option that users can opt in so that what they type goes into a common database, even though word lists alone aren't super helpful maybe they can be used to create something better in the long run. I see myself being able to create a dictionary using word lists, and since it's something it doesn't require coding skills I figure a lot of more people could help.

**Comment by patrickgold** [comment]
I see where you are going but the creation of a new dictionary with a common database is like a project on its own. It sounds really cool though and with the help of the community it could bring something useful for other libre keyboards as well at the long. I will think about it and see where I will go. Thanks for your input!

**Comment by LongJohn-Silver** [comment]
Would you like me to open a new issue to discuss this, even if just to keep it in mind, or would you rather end it here until you have some time to think bout it?

Still, I agree that it is a project on its own and that it escapes the purpose of this application alone, but maybe it wouldn't be something so hard to do, I guess it can be stored on plain text in a different repository, at least at the beginning.

**Comment by patrickgold** [comment]
@LongJohn-Silver I've just opened an issue (#34) which I intend to use as a general thread for implementing composing suggestions. I will therefore close this issue to avoid duplicate discussions. I try to first gather useful word lists and if I really can't find what I am looking for I will evaluate alternatives (like you mentioned creating word lists in another repo).

**Comment by UsmanAli830** [comment]
I want to have this as Two Language Only
