### ISSUE TITLE
Where is the underscore (this character : _ )

### ISSUE THREAD

**Issue by Welgriv** [florisboard/florisboard#160]
I feel a bit stupid but I can't find where is underscore? Thanks.

**Comment by Edocsil** [comment]
![Screenshot_2021-01-10-16-34-52-118_org mozilla firefox](https://user-images.githubusercontent.com/2257988/104127331-d70fc480-5361-11eb-9a6b-1d37eb29fb08.jpg)

**Comment by patrickgold** [comment]
The underscore character is placed in the bottom left corner in the secondary symbol keyboard or as a popup of the dash key in the primary symbol keyboard (screenshot above).

**Comment by Welgriv** [comment]
Ok thanks !
