### ISSUE TITLE
emojis doesn't display when using custom theme in 0.3.14-beta13 (69)

### ISSUE THREAD

**Issue by pokegamer5547** [florisboard/florisboard#1607]
#### Short description
When using a custom theme, it doesn"t display the emojis (even tho they can be clicked).

#### Steps to reproduce
Just use a custom theme and closes the florisboard app and go to any text feild and tap on emojis screen.

#### Environment information
- FlorisBoard Version: 0.3.14-beta13 (69)
- Install Source: github
- Device: poco m2 pro
- Android: android 12 crdroid 8.1 (based on lineage os 18.1)

There is a way to still display them temporarily (even with custom theme) when toggling between themes in settings. But it stops showing once the keyboard closes.
![Screenshot_20220228-180306_FlorisBoard Beta](https://user-images.githubusercontent.com/65234485/155985088-3401f5c9-0a46-45e6-9567-2a04c5f29507.png)
![Screenshot_20220228-180313_FlorisBoard Beta](https://user-images.githubusercontent.com/65234485/155985100-d81a56a5-73d6-4de1-b9eb-16a74b1698b1.png)
![Screenshot_20220228-180316_FlorisBoard Beta](https://user-images.githubusercontent.com/65234485/155985105-7f820d3e-c4cb-4702-8df4-2a7cffe59642.png)

**Comment by Donkey-Doug** [comment]
Same for me

**Comment by patrickgold** [comment]
Thanks for your bug report!

Does this issue also occur for themes which are copied directly from the latest core default theme too or only for custom themes created before this beta release?

**Comment by patrickgold** [comment]
I was able to reproduce the issue, PR #1607 above should fix the issue by defining a fallback font size (in your screenshots above your custom theme lacked a font size for emoji and thus used unspecified, which equals to 0 for the emoji text view).
