### ISSUE TITLE
No Changelog on Google Play

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1609]
#### Short description
For some reason, the changelog didn't show up on the Google Play Store. All I saw was:

```
Changes:
No information from developer.
```

This is strange, considering that the correct `69.txt`-file actually exists and has content.

#### Environment information
- FlorisBoard Version: 0.3.14-beta13 (69)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! Seems to be an issue in the Play Store client, even when going on the Play Console there's the correct release notes filled in:

![image](https://user-images.githubusercontent.com/19412843/156216858-7ddda96e-deb7-4a06-a376-f1b41cbadc71.png)

Also the Play Store listing on the desktop browser shows the correct release details:
![image](https://user-images.githubusercontent.com/19412843/156217317-830621de-a3db-4261-970e-09ea39a53b06.png)

**Comment by Glitchy-Tozier** [comment]
Does it show up on your phone's Play Store? 🤔

**Comment by patrickgold** [comment]
Nope, it surprisingly does not. Tbh I don't know why it does not, as it shows for all other apps which provide changelogs.

**Comment by Ilithy** [comment]
This does not surprise me, I have already noticed that, even googles apps are provided without any information about the update, see:

![Screenshot_20220301-202731](https://user-images.githubusercontent.com/36798218/156236052-44ecd911-d6e7-4800-807d-05a286a54f28.jpg)


_Aucune informations du développeur -> No information from the developer_

**Comment by patrickgold** [comment]
> This does not surprise me, I have already noticed that, even googles apps are provided without any information about the update, see:

That's true but still for me other apps correctly show the changelog in the update section, even FlorisBoard stable. Only FlorisBoard beta lacks this changelog, even though I provided one.

**Comment by GoRaN909** [comment]
It shows for me without any problem 😄

Try to clear cache and clear data of Google Play Services and Google Play Store it maybe fix that problem 

![Screenshot_20220301-230623_Google Play Store](https://user-images.githubusercontent.com/3160786/156241119-baaae09b-2eac-46b2-aa0d-6fb677623782.png)

**Comment by patrickgold** [comment]
Looked into the changelog issue again and today no app has any changelog at all (only on the app though, the website provides them correctly). There's no thing I can change about a PlayStore client issue affecting all apps. Should we close this issue thus or leave it open?

**Comment by Glitchy-Tozier** [comment]
Imo we can close it. Seems more comfortable this way, instead of having to keep this issue in mind.

**Comment by patrickgold** [comment]
Yeah I agree, will close the issue. If new info regarding this topic should come up, we can still discuss it in this thread.

**Comment by patrickgold** [comment]
https://www.androidpolice.com/google-play-is-making-it-maddeningly-difficult-to-tell-whats-new-with-your-favorite-apps/

I think above article seems to be the reason why my changelog is not displayed anymore. WTF Google...

**Comment by Glitchy-Tozier** [comment]
> https://www.androidpolice.com/google-play-is-making-it-maddeningly-difficult-to-tell-whats-new-with-your-favorite-apps/

I hate that! Weirdly enough, changelogs are one of my favourite things about updates.

**Comment by patrickgold** [comment]
> I hate that! Weirdly enough, changelogs are one of my favourite things about updates.

Yes, they are exiting to read, I love changelogs too.

At least for FlorisBoard the detailed changelog was always on the GitHub release itself anyways and that won't be going away anytime soon. But it is still a dumb move on Google's part and hurts the overall experience of GPlay even more.
