### ISSUE TITLE
Overflow menu button not showin

### ISSUE THREAD

**Issue by Yurieaijoker** [florisboard/florisboard#1615]
Why is it that the three dot button/toggle for overflow menu is not showing in my  phone?
![Screenshot_20220304_082814_com android chrome~2](https://user-images.githubusercontent.com/93813352/156676178-ba3a0741-b0f6-4cfe-9ebe-90fb5714523d.jpg)
But if i flip the smartbar toggle it shows
![Screenshot_20220304_082915_dev patrickgold florisboard debug~2](https://user-images.githubusercontent.com/93813352/156676218-5617ca24-f037-40bc-9c3c-f8c71ff61e63.jpg)

Florisboard v0.3.14-beta13
Huawei nova7se emui 10.1
Android 10

**Comment by patrickgold** [comment]
Thanks for your bug report!

Above commit is a possible fix for the bug in the layout measurement (which causes the icon to not draw). When 0.3.14-beta14 releases later today, could you please check if the overflow icon now draws properly? Thanks in advance!

**Comment by Yurieaijoker** [comment]
Yes it shows in default keyboard thanks
![Screenshot_20220307_072138_dev patrickgold florisboard beta~2](https://user-images.githubusercontent.com/93813352/156946757-ee9b4fe4-8c45-4ec2-8180-bbf4251c4d19.jpg)

But in my custom themes made from beta 13 and older version the smartbar is not showing 
![Screenshot_20220307_072222_dev patrickgold florisboard beta~2](https://user-images.githubusercontent.com/93813352/156946779-9a434373-5498-466e-bc1c-6e525419009c.jpg)

**Comment by Yurieaijoker** [comment]
Oh nvm i read the changelog. Thanl you so much . This is already fix. I remake all my custom themes for it to show status bar. Thanks again.
