### ISSUE TITLE
Keyboard preview bug inside the app

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1617]
#### Short description
Hi in the latest version 0.3.14-beta13 (69) when you want to test a feature inside the FlorisBoard app the keyboard suddenly returns to characters when you press on Delete (backspace) key that's happening on all keyboard screens (symbols, emojis, phonepad.. etc)

This bug happened just when you Test a keyboard inside the florisboard app its okay when you use it in all other apps.

#### Steps to reproduce
1. Go to 'FlorisBoard'
2. Click on 'try out your setup'
3. Scroll down to 'Delete key'

https://user-images.githubusercontent.com/3160786/156819878-01d86ae4-0c4d-4f56-a594-78d4eb0f9e00.mp4

Note: I disabled (spacebar switch back to characters automatically) but the bug still there.

#### Environment information
- FlorisBoard Version: 0.3.14-beta13 (69)
- Install Source: Google Play
- Device: Galaxy S20 Fe 5G
- Android: 12, Stock OneUI 4

**Comment by patrickgold** [comment]
Thanks for your bug report!

I am aware of this issue, the problem is that the bug is inside the UI library. Every time you press delete, the input connection does a hard reset, which re-initializes the keyboard state. I don't know if I will find a workaround for this before stable 0.3.14, will let this issue stay open and inform you later on!

**Comment by patrickgold** [comment]
Above PR majorly reworks the input logic and input connection handling, thus the preview box now does not reset the keyboard when pressing backspace. Will be released in 0.3.16-beta01 this weekend. Thanks again for reporting!

**Comment by GoRaN909** [comment]
Thank you for fix the bug I tested the debug apk and bug was gone and fixed. Iwill Close this issue now  as fixed.
