### ISSUE TITLE
Auto Capitalization should be disabled on Korean keyboard

### ISSUE THREAD

**Issue by Me0wzz** [florisboard/florisboard#1623]
#### Short description
Auto Capitalization is is enabled on Korean keyboard.
But, It should be disabled for Korean.

#### Steps to reproduce
1. Go to Languages & Layouts
2. Add Korean using `Suggested subtype presets`
3. Enable Auto Capitalization at `Suggestions & Correctinos`
4. See the Bug
5. Input [ㄱ(ㄲ)][ㅗ][ㄱ][ㅣ] where Auto Capitalization is enabled.

* Expected Output: 고기
* Actual Output: 꼬기

Actually, Korean has no concept of capitalization, All characters are uniform. So, Auto Capitalization should be disabled on Korean keyboard regardless of Auto Capitalization status.

Also, Caps Lock mode(Long-pressed Shift) should not be enabled on Korean.

When input language changed to Korean, activated Shift should be reset too.

#### Environment information
- FlorisBoard Version: 0.3.14-beta14
- Install Source: Github
- Device: Google Pixel 6
- Android: 12

**Comment by patrickgold** [comment]
Above linked commit/PR fixes your described issue:

When evaluating the current capitalization automatically, Korean now never capitalizes, regardless of the current auto-capitalization settings.

When switching subtypes, the shift state is now re-evaluated and thus it always resets for Korean.

Will be released in 0.3.16-beta02 soon, thanks for reporting!
