### ISSUE TITLE
Problem with characters

### ISSUE THREAD

**Issue by Mahantor** [florisboard/florisboard#1624]
#### Short description

These characters are typed in reverse in Persian, please fix this problem

https://user-images.githubusercontent.com/91434001/157015028-8cc48e77-2d37-45fb-abbd-099dfa870d85.mp4

![IMG_20220307_134921](https://user-images.githubusercontent.com/91434001/157015370-5b7cf5cc-381c-4a93-b66f-8eb82d46bb2f.jpg)

#### Environment information
- FlorisBoard Version: 0.3.14-beta14
- Install Source: GitHub
- Device: xiaomi note 9 pro
- Android: Stock

**Comment by Glitchy-Tozier** [comment]
Possibly related? https://github.com/florisboard/florisboard/issues/422

**Comment by patrickgold** [comment]
Definitely related to #442. Will do that once I fix other RTL issues too, maybe I will do it today so it makes it into the 0.3.14-rc01 release.

**Comment by patrickgold** [comment]
Above commit fixes the parentheses. Please note that the parentheses are only in RTL mode if the active subtype's primary language is an RTL language. Will be released in 0.3.14-rc01. Thanks again for reporting this issue!
