### ISSUE TITLE
Glide typing preview not working

### ISSUE THREAD

**Issue by Ammako** [florisboard/florisboard#1627]
#### Short description
Like on 0.3.13, I am not able to get glide typing preview to show up. It'll write words properly, but I don't have a preview.

Happy to provide more information, if it's just me and it works for others. I don't know what might be preventing it from showing a preview. Yes, the option to show glide preview is on.

English (Canada) subtype, but the same happens with English (US) subtype.

#### Steps to reproduce
1. Enable glide typing
2. Swipe a word
3. It'll write words succesfully, but I don't see a preview

#### Environment information
- FlorisBoard Version: 0.3.14-beta14
- Install Source: Github apk
- Device: Pixel 4a (5G)
- Android: Android 12

**Comment by patrickgold** [comment]
Thanks for your bug report!

For glide typing preview to show you need to enable word suggestions (even if there are no suggestions available in 0.3.14). This is a limitation of the current Smartbar logic.

Above commit adds a warning for this exact info, so it should be more clear going forward. Closing your issue, the warning will be included in 0.3.14-rc01.
