### ISSUE TITLE
Adding in-line autofill API support (Android 11+)

### ISSUE THREAD

**Issue by gothmog123** [florisboard/florisboard#163]
The one where you can autofill passwords from the keyboard. Is it planned?

**Comment by patrickgold** [comment]
No I haven't really planned on adding password auto-fill ever to FlorisBoard, as there are plenty of other open-source password managers which do this exact feature already perfectly. Also passwords are highly sensitive data which require extra security in storage and handling and it just does not make sense to have this kind of feature in FlorisBoard, sorry.

**Comment by D3SOX** [comment]
I don't know if @gothmog123 meant adding a password manager into FlorisBoard. There is a new API on Android 11 that can implement your system password manager into the keyboard when a login form is focused.
This is a very new API and not many password managers implement this (f.e. I think my password manager of choice Bitwarden does not implement this yet)

See here: https://www.androidpolice.com/2020/08/10/android-11-will-make-password-autofill-much-better-thanks-to-keyboard-integration/#1

**Comment by patrickgold** [comment]
Thanks for bringing up this API Nico! I have to admit that I've never heard of this new API but looks pretty cool. If this is what @gothmog123  meant than I am open to support this new API in the future.

**Comment by D3SOX** [comment]
Although I don't know if this is actually possible since the article I linked was published before Android 11 was released.

**Comment by patrickgold** [comment]
Yes it is, at least at first glance when looking at the official docs: https://developer.android.com/guide/topics/text/ime-autofill

**Comment by D3SOX** [comment]
Ok awesome, I'm also not sure if this has to be supported by both the keyboard and the selected Autofill app

**Comment by patrickgold** [comment]
> IMEs and password managers both need to be updated to make use of this feature.

Yup, both the keyboard and the password manager have to support this new API according to the Android dev guide. Bitwarden seems to already support this new API (maybe only in beta for now, I am not sure), see https://github.com/bitwarden/mobile/pull/1145.

**Comment by D3SOX** [comment]
It was released in https://github.com/bitwarden/mobile/releases/tag/v2.7.0

I'm very excited to see this in FlorisBoard. The project is really booming lately and there are a lot of issues now, so I understand if it takes a while considering you are developing it mostly on your own.
My respect and thanks again for the project.

**Comment by gothmog123** [comment]
Yeah this new API is what I meant, sorry.

**Comment by patrickgold** [comment]
Thanks for clarifying! The new in-line autofill API will of course be supported, I will add it to the todo list. Though, I am currently unsure if it will be implemented in v0.4.0 or v0.5.0, as the v0.4.0 milestone is already pretty packed. Sorry again for confusing your proposal!

**Comment by gothmog123** [comment]
no worries, thanks

**Comment by bumjrah** [comment]
Bump. @patrickgold any news on this feature support ?

**Comment by patrickgold** [comment]
@bumjrah Currently I am working on a rework of the suggestions front end + better integrations of the clipboard suggestions (they were pretty useless until now), then I will work on some suggestion related stuff. Don't know exactly when I will add it but it should be possible for the v0.4.0 milestone.

**Comment by patrickgold** [comment]
Above PR introduces inline autofill support for FlorisBoard on Android 11+. Will be released today in v0.3.13-beta01!

**Comment by D3SOX** [comment]
Seems to be a bit hit or miss.
I tried it in Bromite on Twitter, EteSync, Nextcloud, Standard Notes for which I have all entries in Bitwarden and it showed nothing.
But it worked really well with Fennec on Twitter (Unbranded Firefox from F-Droid), SoundCloud,  Tutanota and ProtonMail.

I assume this is an upstream issue, so from what I've seen, the integration looks really good. Great job!

**Comment by patrickgold** [comment]
You are right, the implementation isn't perfect. There are three components which have to implement this new inline suggestions API in order for it to work:

- the autofill provider (in your case Bitwarden)
- the IME (FlorisBoard)
- and the target app (like ProtonMail, EteSync, etc.)

Now some apps have already excellent support, that being Bitwarden as the autofill provider and target apps such as Twitter, ProtonMail, etc. Then there are apps which either use a custom edit text implementation and haven't added it yet or browsers where it is the most buggy experience.

I tried it Twitter in Bromite and not even Gboard shows anything, so I suspect Bromite hasn't added support for inline suggestions yet (maybe worth searching their issue tracker and possibly filing an issue to check on that).

Brave (also Chromium based) has good support, it does work in like 95% of the times. Firefox (the new one) is a big hit and miss for me, especially if you change the IME while the login web page is active.

So I think there's a bit of room to improve within FlorisBoard but not every app supports inline suggestions yet or has a buggy implementation themselves.

**Comment by D3SOX** [comment]
https://github.com/bromite/bromite/blob/master/FAQ.md#does-bromite-support-the-android-autofill-framework
Sadly they will not work in Bromite because or proprietary blobs.
I wonder if microG has an implementation of it and how Firefox get's them to work.

**Comment by hakkikaancaliskan** [comment]
Firefox nightly autofill works 95% of time but beta and stable has problems. Beta and stable don't even work with gboard.

**Comment by patrickgold** [comment]
>  I wonder if microG has an implementation of it and how Firefox get's them to work.

The question is why you need Google services at all to use this API. The autofill API consists mainly of two parts:
1. The code that's backed into the Android framework since API30.
    For IMEs the source code is found [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/inputmethod/).
    The inline widget source code is [here](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/widget/inline/)
2. The androix.autofill package ([source code](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-autofill-release/autofill/autofill/)).

With these two components the inline suggestions should be possible to support, as far as I've understood the API and how it works, without any proprietary "magic" blobs, the source code for everything needed is available. Of course there could be some limitations by Google what exactly can be used within Chromium (I am not familiar with the Chromium code base), but at least this explains why Firefox and many others can support this so easily. Brave either uses proprietary blobs or some workaround, I don't know.
