### ISSUE TITLE
Add reset button to default value

### ISSUE THREAD

**Issue by Mahantor** [florisboard/florisboard#1631]
Please add the ability to reset the changed value to the default value
![IMG_20220309_203830](https://user-images.githubusercontent.com/91434001/157494771-5a634b12-7395-4d42-8207-5a0fecc2f79f.jpg)

**Comment by patrickgold** [comment]
Thanks for your feature proposal!

The theme values do not have a default value by design (except if you see the fallback #00000000 as the default). The problem is when you copy from the default theme the stylesheet is copied 1 to 1, but there's no back reference to the original. So it is impossible to say what the original even was, thus there's no button for it.

**Comment by patrickgold** [comment]
I mean I could theoretically add a button which reads the color from the core theme (either day or night), but if you have modified your theme structure it may not work out all the time.

**Comment by Mahantor** [comment]
Do you mean that the themes we created are not possible for them?
If you mean this
Edited themes are stored at this address.
![IMG_20220311_210045](https://user-images.githubusercontent.com/91434001/157922991-00b7e877-4602-4bb0-83dd-de6cdfc7c661.jpg)
![IMG_20220311_210603](https://user-images.githubusercontent.com/91434001/157923109-92dcbc90-77b8-4033-9c7c-28c50f34b79a.jpg)
![IMG_20220311_210739](https://user-images.githubusercontent.com/91434001/157923422-ee8d5a84-21de-4b4c-a04f-f50b39647b17.jpg)

Why is it not possible to read values ​​from this path for edited themes ??

**Comment by patrickgold** [comment]
> Why is it not possible to read values ​​from this path for edited themes ??

Sure I am able to read from that file, in fact the whole stylesheet editor is the UI for said file. You requested a button for the default value for a variable/property, and here I meant I don't know where I should take the default value from.

**Comment by patrickgold** [comment]
Or do you mean with default value the value the variable/property has when you tapped the edit button, before you made changes?

**Comment by tsiflimagas** [comment]
> Or do you mean with default value the value the variable/property has when you tapped the edit button, before you made changes?

That's what it is I guess. I mean, that's the only rational and useful interpretation to me.
Currently, the only way to discard temporary changes is to cancel editing and discard them altogether, or remember the last used value. So, a way to undo a temporary change, could be useful, I guess. Would placing a reset button be the best solution, or a general undo button, or maybe something else? I don't have any strong opinion on this. I don't have an opinion on whether such an ability needs to be added either, as I haven't spend much time in theme editor yet.
