### ISSUE TITLE
Unable to edit /syetem/etc/hosts file

### ISSUE THREAD

**Issue by GithbUser** [florisboard/florisboard#164]
I m unable to edit hosts file using florisboard but when using gboard(system app) i can edit hosts file
Is it due to because of florisboard being a user app?
Or there is another reason?

Thank you very much for developing  florisboard

**Comment by patrickgold** [comment]
Which app are you using for editing the hosts file? Could be because FlorisBoard conflicts while communicating with the text editor.

**Comment by GithbUser** [comment]
Mixplorer silver 6.49.5 text editor

**Comment by GithbUser** [comment]
In 0.3.3 version
I can edit hosts files 
thanks for develooing florisboard

**Comment by patrickgold** [comment]
Ok good to know thank you for reporting this to me! Tbh I didn't intentionally fix this, but it seems that alongside with the many new improvements of v0.3.3 this bug seems to have been resolved too.
