### ISSUE TITLE
Clipboard is unable to be opened.

### ISSUE THREAD

**Issue by Flam3z** [florisboard/florisboard#1641]
#### Short description
When pressing & holding on a text box I am unable to access my clipboard history.

#### Steps to reproduce
1. Go to any text box
2. Press & hold down on said text box
3. Wait for any possible options to appear.

#### Environment information
- FlorisBoard Version: 0.3.11
- Install Source: F-droid
- Device: Samsung Galaxy S10 One UI 4.0
- Android: Android 12

**Comment by patrickgold** [comment]
Thanks for your bug report!

When you tap and hold text in a text box the clipboard menu you see is managed by the system, thus there will never be a clipboard history menu button, only within the keyboard UI itself. Hope you can understand, closing this issue.
