### ISSUE TITLE
Consider adding T9 letters on the numpad like a phone's dialer

### ISSUE THREAD

**Issue by now0clock** [florisboard/florisboard#1651]
It would be nice to have the alphabet as it appears on a telephone dialer, regardless of where the numpad is being used. For instance, I memorize a sequence of numbers that is also a word/phrase this way. I've been using Florisboard for quite a while, I think it is the only thing missing from this keyboard. (I'm using it now.) Attached are some examples,

![Screenshot_20220316-090440](https://user-images.githubusercontent.com/59995403/158634998-dc540377-0cb9-4d97-a141-97298bc1c2cf.png)

![Screenshot_20220316-080621](https://user-images.githubusercontent.com/59995403/158634551-7a998301-dc19-469f-966e-feb15ef41fd9.png)

![Screenshot_20220316-085159](https://user-images.githubusercontent.com/59995403/158635003-037c2968-efa7-4746-9119-e71e42826dbc.png)

![Screenshot_20220316-085122](https://user-images.githubusercontent.com/59995403/158635006-61cc3aa2-04e6-4970-9e8f-417237c38d78.png)

![Screenshot_20220316-084954](https://user-images.githubusercontent.com/59995403/158635007-d90c1825-1cb0-42ed-accf-94da29bdf4f3.png)

![Screenshot_20220316-082556](https://user-images.githubusercontent.com/59995403/158635016-06394fc6-cbe9-4645-aa09-4fe5eb1ad81f.png)

**Comment by patrickgold** [comment]
Thanks for your proposal! This has already been suggested, see #355. Closing as a duplicate.
