### ISSUE TITLE
Can't change color string

### ISSUE THREAD

**Issue by Majuu13** [florisboard/florisboard#1655]
#### Short description
I having this issue where I can't change the hex value of color even though it's correct one. I can change color by dragging the color circle, but I can't change hex color string by editing color string.

#### Steps to reproduce
1. Go to My themes
2. Click on edit
3. Change the value any color variables by entering edit color string
4. You will the see error

#### Environment information
- FlorisBoard Version: v0.3.14-rc01
- Install Source: GitHub
- Device: Nokia 8
- Android: 9, Stock 
![Screenshot_20220318-100431](https://user-images.githubusercontent.com/21125697/158940967-39558863-7995-4a5b-8720-4d7c9673fd6c.png)

**Comment by patrickgold** [comment]
This is a known issue which is already fixed in the debug builds, see #1636 for details.

Today's 0.3.14-rc02 release will contain this fix.
