### ISSUE TITLE
Gldiing typing suggestion bug

### ISSUE THREAD

**Issue by dude-shah** [florisboard/florisboard#1657]
I use gesture/gliding typing 90% of the time and the bug made me switch to other keybords. What i want is, suggestions to show up like normal, not that same word with digits at the end like in screenshot. If you are aware of this bug then please fix this bug first.
 
![Screenshot_2022-03-18-23-52-37-92_6012fa4d4ddec268fc5c7112cbb265e7.jpg](https://user-images.githubusercontent.com/63038690/159066782-79d66bbd-b44d-452a-8ada-e91d3a75238f.jpg)

#### Environment information
- FlorisBoard Version: 0.3.24 rc1
- Install Source: github
- Device: realme 6
- Android: 11

**Comment by tsiflimagas** [comment]
Support for word suggestions has been removed from 0.3.14 builds and won't be there in 0.3.14 stable either since the current implementation has many issues. A new word prediction implementation is scheduled to come in 0.4.0 release.

**Comment by dude-shah** [comment]
Well then .. i think i should wait for 0.4 release.
