### ISSUE TITLE
Keyboard resizing between characters and symbols when number row is enabled

### ISSUE THREAD

**Issue by dude-shah** [florisboard/florisboard#1658]
on keyboard when pressing the button to symbols the keyboard size shrinks down...just want it to be the way it is on 0.3.13

Shrunken version (it happens on symbo area and clipboard region)

![Screenshot_2022-03-19-00-08-54-55_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/63038690/159068809-39cd87e7-0503-4048-9ecc-12571420a33b.jpg)

Expected behaviors (keyboard remains full size as it was before) vertical spaces between keys here too.
![Screenshot_2022-03-19-00-11-03-01_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/63038690/159069074-03071ffa-9c8e-4093-a45d-b63a55de1dae.jpg)

#### Environment information
- FlorisBoard Version: 0.3.14 rc1
- Install Source: github
- Device: realme 6
- Android: 11

**Comment by patrickgold** [comment]
Above commit fixes this issue, the symbols and numeric advanced layouts not have the same height as characters even if the number row is enabled. Will be released in 0.3.15-beta01 soon.
