### ISSUE TITLE
When double-space period is on, pressing space three times should remove the period and result in 2 spaces having been added.

### ISSUE THREAD

**Issue by magnus-ISU** [florisboard/florisboard#1664]
Subsequent spaces should also be just regular spaces, until another character is typed; then you go back to double-space-is-period functionality.

Double-space period means that most of the time you can just not use the smaller, less easy-to-press period button. However, its only downside (assuming #524 is fixed) is if you have to press space a ton, for example editing something monospace where you want to align something, then you have to double press space, then go back and delete the period, then start spamming space again.

This would just mean that if you start spamming space, it will take you one extra space but you will not need to go back and delete the period, meaning there would be no reason not to have this feature turned on.

Since the period is on-screen anyway (and #524 isn't fixed, which seems to me to be related to glide typing; when glide typing, it will be incorrect, while regular typing works) I'm leaving this feature off right now.

**Comment by patrickgold** [comment]
Thanks for your proposal!

With #1822 issue #524 should be fixed, the double-space period was very reliable in testing. As to your proposal, I think I will not implement it, as it makes little sense to me and the behavior is super inconsistent with other Android keyboards.

If you need to insert a spacing for Markdown after a word, the double-space period feature only triggers for two consecutive presses, given they follow immediately. So if you press space, wait for a sec and press space again double-space will purposely NOT trigger, only if you quickly press space+space.

This means your specific issue can easily be circumvented and thus I will not implement this, I hope you understand!
