### ISSUE TITLE
Numbers keyboard popup

### ISSUE THREAD

**Issue by z0xrv** [florisboard/florisboard#1667]
![IMG_20220319_120858](https://user-images.githubusercontent.com/52888633/159118643-1f6f5fad-dd50-44d9-87d8-cd77b92823e8.jpg)
The popup here better be disabled or atleast made a the same width like the button and a the height should be decreased a little so it won't be kinda annoying

**Comment by GoRaN909** [comment]
This is duplicate issues @Glitchy-Tozier was talked about this before at #1044
