### ISSUE TITLE
Can't import themes on beta version

### ISSUE THREAD

**Issue by OilSubjectLoss7** [florisboard/florisboard#1670]
It said "file extension unsupported"

It's working fine on stable version doe

**Comment by OilSubjectLoss7** [comment]
I managed to import it but it's not showing up in the list

**Comment by z0xrv** [comment]
Are u trying to import .json file? If so, then due to the new theme engine rework it doesn't work anymore. You need some kind of .flex file generated by the keyboard itself, check my github there's a repository called 'florisboard' with .flex file you can't test with it.

**Comment by patrickgold** [comment]
@OilSubjectLoss7 Theme import in the latest beta/release candidate uses the brand new Flex extension format (`.flex` as file extension), the old theme files are not supported anymore.

**Comment by patrickgold** [comment]
> check my github there's a repository called 'florisboard' with .flex file you can't test with it.

Cool theme you created @ z0xrv!

**Comment by z0xrv** [comment]
> Cool theme you created @ z0xrv!

Thank you, it still needs some work. I will be making a request to add it after I finish it. 
Also, can you add an option to change those colors for settings from theme?
![IMG_20220319_211837](https://user-images.githubusercontent.com/52888633/159137167-994bfea9-bc22-440b-a01e-81cf2595a9f6.jpg)

Also a way to change the smart bar?

**Comment by patrickgold** [comment]
> Also, can you add an option to change those colors for settings from theme?

No, because the Settings UI uses a different approach from getting the colors than the Keyboard UI. Also in my opinion we shouldn't overload the already packed themes I think, so the Settings UI will never be customizable from a theme in the near future.

> Also a way to change the smart bar style?

Check out the default themes or just by simply adding a new rule and playing around with the various `smartbar-*` element selectors.

**Comment by patrickgold** [comment]
Is this issue still relevant or can it be closed, as it is not a bug?

**Comment by z0xrv** [comment]
Still working well for me.

**Comment by OilSubjectLoss7** [comment]
> Still working well for me.

How do you generate the flex files exactly?

**Comment by OilSubjectLoss7** [comment]
Nvm i figured how
