### ISSUE TITLE
Currency popup not show

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1671]
#### Short description
Hello and thank you for fix the clipboard issues I tried the latest beta version 0.3.14-rc03 everything is works great without any problem expect the Currency popups when you long press on  $ Dollar sign the other alternative currencies like pound, euro ..etc is not show as a secondary popup of Dollar i tested other characters popups is working but only the secondary characters of Dollar doesn't popup.

#### Steps to reproduce
1. Go to 'symbols'
2. Click on 'long press $'
3. Scroll down to 'popups not showing'

#### Environment information
- FlorisBoard Version: 0.3.14-rc03 (73)
- Install Source: GitHub
- Device: Galaxy S20 Fe
- Android: 12, Stock OneUI 4

**Comment by patrickgold** [comment]
Above commit fixes this issue, will be released in 0.3.14-rc04 now. Thanks for reporting!
