### ISSUE TITLE
Force Smartbar and Emoji to use LTR layout direction

### ISSUE THREAD

**Issue by debnone** [florisboard/florisboard#1673]
Please add an option to stop flipping the smartbar & the emoji  in the keyboard settings for RTL  Languages.
Its very annoying 😠🤬  that every time its flip.
And its most be optional and NOT forcing the users that toggling between RTL and LTR .
Especially in situations that need a straight forward using and easy learning curve like Emoji and static feature.
The RTL flip most be in optional for those how want that.
But the best is to be static for this user UI Situations.

currently working on some recommendations for the user interface, hope to share it soon 🤞

❤️ thanks

FlorisBoard V0.3.14 rc3

**Comment by GoRaN909** [comment]
I agree with you me too I don't like the flipped icons for my language that RTL, We talked about this before at this PR! #1629

**Comment by patrickgold** [comment]
I am less for adding a toggle and just forcing the Smartbar and Emoji fully to LTR, leaving the clipboard to adapt to RTL though if necessary. Would this be sufficient for your request?

**Comment by debnone** [comment]
**A little about the problem:**

The problem is about changing directions every time you change a language.
There are people who speak several languages, like me for example, It is very inconvenient that every time you change language all directions change.

There are parts of the keyboard that need to be fixed, such as an emoji or functional buttons like smartbar.

The last change in version 3.14 is so large and inconvenient (👉👈directions), without the possibility to cancel or return to the previous state, and its happend after the multilingual users have become accustomed to how it was working in previous versions.

And *Yes* i agree with you, it must be fixed to LTR for all Languages For convenient / easiness use and a short learning curve.

thanks a lot for your great work ❤️

**Comment by patrickgold** [comment]
Above linked commit fixes this issue, with the next beta release 0.3.15-beta01 the Smartbar and Emoji is forced LTR.

**Comment by GoRaN909** [comment]
> Above linked commit fixes this issue, with the next beta release 0.3.15-beta01 the Smartbar and Emoji is forced LTR.

That's what I need and talked about Thank you so much for the correction of layouts to LTR :)
