### ISSUE TITLE
[v0.3.14rc3] Non functional arrow keys in quick access bar

### ISSUE THREAD

**Issue by uli-on** [florisboard/florisboard#1674]
The arrow keys act unexpected for two reasons: 
1 Each press on the arrow keys brings up the word prediction again (shouldn't it stay until I press the twisty another time?)

That behaviour made me think "maybe that is intended and a long press is needed?"

2 A long press, however, locks the arrow key, resulting in a repeatedly no end moving cursor and a pulsating smartphone, as long as FlorisBoard is active. (The stuck/locked key can only be stopped by force quitting FB, pressing other keys seems to have no effect.)

FlorisBoard v0.3.14 rc3 (from F-Droid) 
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 98.0.4758.87
Motorola Moto G4
device not rooted

**Comment by patrickgold** [comment]
Thanks for your bug report!

Above PR/commit adjusts the auto-closing mechanic of the quick actions shared layout. It now does not collapse on its own if you press an arrow key multiple times in a row or if you hold the arrow key. This means you can now move the cursor correctly and the arrow keys are usable again. Thanks for reporting, will be parts of the 0.4.0-alpha03 release once its ready!

**Comment by uli-on** [comment]
I appreciate your thankfulness. Honestly :)
