### ISSUE TITLE
Switch between keyboards in numeric mode

### ISSUE THREAD

**Issue by Mahantor** [florisboard/florisboard#1677]
Please add a feature that allows you to change the keyboard in numeric keypad mode
![Screenshot_2022-03-22-22-04-49-759-edit_com gapfilm app](https://user-images.githubusercontent.com/91434001/159541780-7e8b8a8c-0d83-486e-9c81-74d60d34e654.jpg)

https://user-images.githubusercontent.com/91434001/159542327-96bb4ac8-0954-4e46-9d22-6b7aa073cd2a.mp4

**Comment by tsiflimagas** [comment]
You can already do that by longpressing on space key. Closing as already implemented.

**Comment by Mahantor** [comment]
I knew this
Some programs, such as the program I posted in the photo, can only enter numbers. To change the keyboard, I have to open another program, then activate the keyboard and change the keyboard, and then return to the main program. Going through this path is really tiring.
I know this feature does not exist in other keyboards but adding it is a useful feature

**Comment by tsiflimagas** [comment]
The key above delete key is the space key in numeric pad. Maybe you didn't notice by the symbol.

**Comment by Mahantor** [comment]
Oh yes I just found out
I'm really sorry for wasting your time
Thanks for the tips
