### ISSUE TITLE
hidden Persian symbols 

### ISSUE THREAD

**Issue by m-koushan** [florisboard/florisboard#1679]
#### Short description
Some symbols are not visible in Persian

#### Steps to reproduce
![Screenshot_2022-03-22-23-47-24-580_dev.patrickgold.florisboard.beta.jpg](https://user-images.githubusercontent.com/50526840/159559321-d85f13b3-5806-477f-8f3b-b81ee34b91b3.jpg)

#### Environment information
- FlorisBoard Version: 0.3.14-rc04
- Install Source: GitHub
- Device: Redmi Note 8 pro
- Android: 11

**Comment by GoRaN909** [comment]
This can be fix easily by adding a Dotted Circle under each characters as Google did on GBoard I will fix this bug.
