### ISSUE TITLE
Undo & Redo function not working..

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1685]
#### Short description
Hello, I was wrote an article on facebook group and selected all text to copy them into clipboard but suddenly pressed an character all my wrote text input was clear and gone :( .. I tried to Undo action tapped on Undo button in Smartbar action but sadly doesn't worked I was write everything from beginning.

I test in some other places like Samsung Notes and [Markor - text editor app](https://play.google.com/store/apps/details?id=net.gsantner.markor&hl=en&gl=US) it's not works anymore you can't Undo & Redo last action. 

I hope you fix this bug and Thanks for your Improvements and fixes :) 

#### Steps to reproduce
1. Go to 'Type some text then delete'
2. Click on 'Undo or Redo'
3. Scroll down to 'Nothing happen the deleted text doesn't Undo'

#### Environment information
- FlorisBoard Version: Latest stable version 0.3.14 (75)
- Install Source: Google Play
- Device: Galaxy S20 FE 5G
- Android: 12, Stock OneUI 4

**Comment by tsiflimagas** [comment]
Weird, it works fine here. Did you try restarting the app? Also, did it work in beta builds?

**Comment by GoRaN909** [comment]
> Weird, it works fine here. Did you try restarting the app? Also, did it work in beta builds?

Yes so strange even after clean install now the Undo is work again but Redo still not, I used latest beta and the debug apk file from last commit too it's same thing.

**Comment by patrickgold** [comment]
Well in the end undo and redo functionality is the responsibility of the target app. I just send the emulated key press (`CTRL+Z` for undo and `CTRL+SHIFT+Z` for redo), I can't do more sadly.

Also a FlorisBoard undo/redo solution is near to impossible, given how many editors sometimes report incorrect cursor position, or have style spans set, or have literal images embedded in the text (like Word for instance).

With above reasoning I will close this issue as wontfix, I hope you understand.
