### ISSUE TITLE
Uppercase for language names

### ISSUE THREAD

**Issue by VladWinner** [florisboard/florisboard#1686]
Language names are taken from OS, but they are usually written with a lowercase letter. 
Possible solution (not in Kotlin):
https://stackoverflow.com/questions/1026069/how-do-i-make-the-first-letter-of-a-string-uppercase-in-javascript

**Comment by patrickgold** [comment]
Language names are lowercase?! Could you please share some example screenshots? On my devices almost all Latin-based language names are in uppercase, thus my confusion.

**Comment by VladWinner** [comment]
1. `enum__display_language_names_in__system_locale` ON, system language: Russian
English (locale dropdown in subtype dialog):
![image](https://user-images.githubusercontent.com/13555921/160030722-843b71a0-0978-4d3e-b627-215aac1b9710.png)
_English (United States)_ in `settings__localization__suggested_subtype_presets`:
![image](https://user-images.githubusercontent.com/13555921/160030976-745d3917-78d7-4d03-beed-48b73dbafc8f.png)


2. `enum__display_language_names_in__native_locale` ON
French (locale dropdown in subtype dialog):
![image](https://user-images.githubusercontent.com/13555921/160031148-e6df3dcc-0a9d-42e3-ad79-18d689beb7c4.png)
Russian, Yakut, Serbian (locale dropdown in subtype dialog):
![image](https://user-images.githubusercontent.com/13555921/160031171-2755e57a-d8d2-4d62-8143-0aeac6460510.png)

**Comment by patrickgold** [comment]
Above PR is a fix for the language names. Could you please check out the debug APK (installs separately) to check if these case conversions look good on your end? Thanks!

**Comment by VladWinner** [comment]
It worked! ❤️
