### ISSUE TITLE
Password field disables the toolbar of Florisoard

### ISSUE THREAD

**Issue by firefoxlover** [florisboard/florisboard#1687]
When a Website wants the user to insert a password, FlorisBoard's Quick-Toolbar doesn't show up.

The Quick-toolbar is the one with the symbols, enabling one-click copy, paste e.g., and its already opt-in.

This is really annoying, as there already are the privacy opt-out measurements of the internal draft. I guess its wanted, and password fields are probably detected differently, to provide different functions like using password managers.

Please remove this bug or make it opt-in, if there was some security problem with it. On LineageOS with no bad apps, using this would be absolutely no problem.

**Comment by patrickgold** [comment]
Could you please use the proper bug report template when filing a new issue? Without the additional info the fields in the template requests I can only guess.
