### ISSUE TITLE
Emoji-tab scrollbar height constant recalculation

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1700]
#### Short description
While scrolling through emojis, I noticed that the height of the scroll scrollbar is weirdy jumping up and down, like constantly being recalculated. It's not that I find it too unpleasant, I just wonder if it's an indication of some mistake/room for improvement in logic, code etc. Thus I'd call this maybe-a-bug.

#### Steps to reproduce
1. Go to emoji tab
2. Scroll up and down to
3. See the scrollbar height changing constantly in a rapid manner

#### Environment information
- FlorisBoard Version: 0.3.14
- Install Source: GitHub
- Device: Xiaomi Redmi Note 8
- Android: 12, Custom rom

**Comment by patrickgold** [comment]
Thanks for your bug report!

It is definitely a bug, because I am using the `LazyColumn` scrollbar on a `LazyVerticalGrid`, which kinda works but has it's quirks (like the jumping around). This happens because a row in the column contains more than 1 item.

I noticed this immediately when I implemented emojis, but didn't have an idea back then how to fix the current implementation, so I left it: https://github.com/florisboard/florisboard/blob/f73daa2b00f1bb52822c37122f8507e9a798b42d/app/src/main/java/dev/patrickgold/florisboard/app/ui/components/ScrollableModifiers.kt#L129-L181

If you have an idea on how to fix it feel free to work on it, else I will try to find a solution next week hopefully.

**Comment by tsiflimagas** [comment]
> If you have an idea on how to fix it feel free to work on it, else I will try to find a solution next week hopefully.

I would really like it if I could, but unfortunately I'm not a dev😄 I guess that's an invitation to any potential developer reading it, though.

**Comment by patrickgold** [comment]
I am currently thinking if I should apply the `good-first-issue` label, because this issue addresses a separated feature without having to know your way around the code base too much. Only requires a bit of knowledge in Jetpack Compose.

**Comment by tsiflimagas** [comment]
Oh, just noticed this now also applies to the, otherwise gorgeous, new third party licences screen.

**Comment by patrickgold** [comment]
> Oh, just noticed this now also applies to the, otherwise gorgeous, new third party licences screen.

Yep just saw that too, thanks for noticing!

**Comment by siva-subramaniam-v** [comment]
@patrickgold I'd like to fix this, but my build failed due to an issue related to cmake. Can you help?

Error Log:

```
[CXX1429] error when building with cmake using C:\Users\sivam\AndroidStudioProjects\florisboard\app\src\main\cpp\CMakeLists.txt: -- The C compiler identification is Clang 14.0.7
-- The CXX compiler identification is Clang 14.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/sivam/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/sivam/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Module support is disabled.
-- Version: 9.1.0
-- Build type: Debug
-- CXX_STANDARD: 20
-- Performing Test has_std_20_flag
-- Performing Test has_std_20_flag - Success
-- Performing Test has_std_2a_flag
-- Performing Test has_std_2a_flag - Success
-- Required features: cxx_variadic_templates
-- Performing Test HAS_NULLPTR_WARNING
-- Performing Test HAS_NULLPTR_WARNING - Success
-- Using the multi-header code from C:/Users/sivam/AndroidStudioProjects/florisboard/app/src/main/cpp/nlp/external/nlohmann-json/include/
-- Configuring incomplete, errors occurred!
See also "C:/Users/sivam/AndroidStudioProjects/florisboard/app/.cxx/Debug/4d3u652l/arm64-v8a/CMakeFiles/CMakeOutput.log".

C++ build system [configure] failed while executing:
    @echo off
    "C:\\Users\\sivam\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HC:\\Users\\sivam\\AndroidStudioProjects\\florisboard\\app\\src\\main\\cpp" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=24" ^
      "-DANDROID_PLATFORM=android-24" ^
      "-DANDROID_ABI=arm64-v8a" ^
      "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
      "-DANDROID_NDK=C:\\Users\\sivam\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653" ^
      "-DCMAKE_ANDROID_NDK=C:\\Users\\sivam\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653" ^
      "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\sivam\\AppData\\Local\\Android\\Sdk\\ndk\\25.2.9519653\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=C:\\Users\\sivam\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_CXX_FLAGS=-std=c++20 -stdlib=libc++" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\sivam\\AndroidStudioProjects\\florisboard\\app\\build\\intermediates\\cxx\\Debug\\4d3u652l\\obj\\arm64-v8a" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:\\Users\\sivam\\AndroidStudioProjects\\florisboard\\app\\build\\intermediates\\cxx\\Debug\\4d3u652l\\obj\\arm64-v8a" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-BC:\\Users\\sivam\\AndroidStudioProjects\\florisboard\\app\\.cxx\\Debug\\4d3u652l\\arm64-v8a" ^
      -GNinja ^
      "-DCMAKE_ANDROID_API=24" ^
      "-DICU_ASSET_EXPORT_DIR=C:\\Users\\sivam\\AndroidStudioProjects\\florisboard\\app\\src\\main\\assets\\icu4c" ^
      "-DBUILD_SHARED_LIBS=false" ^
      "-DANDROID_STL=c++_static"
  from C:\Users\sivam\AndroidStudioProjects\florisboard\app
CMake Error at nlp/icu4c/CMakeLists.txt:7 (find_program):
  Could not find GNU_MAKE_PROGRAM using the following names: gmake
```

**Comment by siva-subramaniam-v** [comment]
@tsiflimagas Thanks. I installed gmake following [this article](https://leangaurav.medium.com/how-to-setup-install-gnu-make-on-windows-324480f1da69). But the build still fails with the same error.

**Comment by patrickgold** [comment]
I am currently not on my PC but if I can see it correctly you are building for native Windows x86_64, which is not officially supported by FlorisBoard, so this might be the issue. Will have a closer look later in the afternoon.

**Comment by siva-subramaniam-v** [comment]
@patrickgold Can you elaborate on what you mean by "building **for** Windows x86_64"? I couldn't get you.

**Comment by patrickgold** [comment]
Ok I had a look at your CMake errors and while they look a bit related they might still have different causes. Do both of you have all the [dependencies for building](https://github.com/florisboard/nlp#building-for-android-targets-nlpcore-only) installed?

**Comment by patrickgold** [comment]
@siva-subramaniam-v @anjalsaneen As I am receiving more build issues than anticipated I have started a collection issue for this at #2218, hopefully I can then gather more details and find a quick fix for this.

> Can you elaborate on what you mean by "building for Windows x86_64"? I couldn't get you.

Sorry a bit of a weird wording from me, I meant you are building **for** Android **on** Windows x86_64. What type of host OS you are on is really important as I need to cross-compile ICU4C and thus I cannot support all host OSes out there. Atm Windows isn't really supported by my cross-compilation script, so your issue this might be the reason.

As for the build issue on MacOS I really have to dig deeper, because MacOS should be supported.

**Comment by tsiflimagas** [comment]
In the meantime, I just noticed that with the current source (`deaf3295`) there's no scrollbar in the emoji tab.

**Comment by patrickgold** [comment]
> In the meantime, I just noticed that with the current source (deaf3295) there's no scrollbar in the emoji tab.

That's true haven't noticed this until yet. Probably a side-effect of upgrading the Compose UI lib.

**Comment by patrickgold** [comment]
> I'm having the same error. I'm using Apple M1 Pro.

@siva-subramaniam-v In florisboard/nlp#6 I've provided a fix for the linker flags for MacOS. Could you try out the code base for that PR and check if the NLP part would now build successfully on MacOS?

**Comment by VishnuSanal** [comment]
hi, I would like to work on this issue. I am new here & looking forward to contribute :)

**Comment by KevinVan9** [comment]
Hi @patrickgold I am working on the issue
