### ISSUE TITLE
Gestures to open emojis and/or microphone

### ISSUE THREAD

**Issue by ksanf3** [florisboard/florisboard#1701]
Implement gestures to open emojis and/or microphone

**Comment by tsiflimagas** [comment]
I don't really get what do you mean by "microphone". Do you mean voice typing?

**Comment by soberhippie3** [comment]
Yes that's what I meant.

**Comment by tsiflimagas** [comment]
Ok, thanks for clarifying. For that, you'd have to wait for voice typing to be implemented first, though.

**Comment by soberhippie3** [comment]
In the mean time could it switch to Google Voice Typing?

**Comment by tsiflimagas** [comment]
Currently no, this would have also have to be implemented first. But it seems that's what's going to happen for voice typing, as you may see in #1578. But it also seems that it is more complicated than it seems, so it will probably need time.
