### ISSUE TITLE
Glide typing not entering text

### ISSUE THREAD

**Issue by crisp5** [florisboard/florisboard#1703]
#### Short description
Glide typing does not enter text into textbox. Glide trail is visible, but ending the glide gesture does not insert a word. Tap typing works as expected.

#### Steps to reproduce
1. Fresh install.
2. Click on 'Gestures & Glide Typing' and Enable glide typing.
3. Click on the 'Try out your setup' area (or any external app's text box) and start glide typing.

#### Environment information
- FlorisBoard Version: 0.3.14 (also present in 0.3.15-beta01)
- Install Source: 0.3.14 from F-Droid, 0.3.15-beta01 from GitHub
- Device: Samsung Galaxy J7
- Android: 8.1.0

**Comment by tsiflimagas** [comment]
Which app were you writing in?

**Comment by crisp5** [comment]
I initially tried using the new 'Try out your setup' box in Florisboard itself, but I also tried Firefox for Android, the phone's own Settings search and the stock Messages app.

**Comment by crisp5** [comment]
Killing the app while glide typing is enabled fixes the issue. I can reproduce the bad state by 
1. Having glide typing enabled and working
2. Opening the Settings UI, disable glide typing, and killing the app from the Recent Apps screen
3. Reopening the Settings UI and reenabling glide typing
It'll stay in the bad state until I kill the app again.

**Comment by tsiflimagas** [comment]
It works for me in all these cases. Do you use English when using glide typing? It's not available for other languages yet. Also, did you try restarting the app?

**Comment by crisp5** [comment]
Yes, I'm using English (US) and restarting helps.
Missed an important step in my last comment, it should have been
1. Kill the app with Glide disabled
2. Open the app
3. Tap on the "Try out" box to reload the keyboard
4. Reenable glide
So if the keyboard's already loaded, glide won't kick in until it's reloaded.

**Comment by tsiflimagas** [comment]
I see. These steps seem to work for me too, most of the times at least. Thank you for providing them, they could be proved to be valuable to Patrick for fixing known glide typing issues.

**Comment by junaidd09** [comment]
I am facing the same issue on my Pixel 4a. Restarted the app and it got fixed.

**Comment by patrickgold** [comment]
Thanks for your bug report!

I can fully reproduce this bug. It was caused by a missing observer on the `glideEnabled` pref state, thus it would only load new glide data if the app was re-initialized by killing it or if the subtype was changed. Now with the fix of above PR it immediately loads the word data when you enable glide typing, thus the words are generated based on your glide.

If anyone wants you can try out the debug artifact, later today I will merge it in though and release this fix in 0.3.15-rc01.
