### ISSUE TITLE
Removed or Merged Forward and backward key.

### ISSUE THREAD

**Issue by Pranab009** [florisboard/florisboard#1708]
Removed or Merged Forward and backward key with undo and redo buttons.
If you can move your cursor with gesture then physical keys are useless.
You can merged it with undo redo buttons.
Normal press for backward or forward and
Long press for undo or redo.

**Comment by patrickgold** [comment]
Same as #1705, merging things together does not make sense. When I implement detailed Smartbar customization you will be able to hide and/or re-order the action buttons of the Smartbar, then you can partially achieve your desired behavior.
