### ISSUE TITLE
Key shape should not clip content to allow pop-out hints

### ISSUE THREAD

**Issue by cYDN48** [florisboard/florisboard#1710]
#### Short description
Using a theme with circle shaped keys partially cuts off the key hints, which looks bad.

#### Steps to reproduce
1. Open FlorisBoard settings
2. Make sure key hints are enabled
2.1. Tap Keyboard
2.2. Enable hinted number row and/or hinted symbols
3. Create a theme that uses circle-shaped keys
3.1. Go to Design > Manage installed themes > Create theme extension
3.2. Tap on the orange '+'
3.3. Select an existing theme (Floris Day or Night)
3.4. Tap on 'Create'
3.5. Tap on the green 'Edit' under the new theme
3.6. Under variables change 'Common Shape' to 'Circle Shape'
3.7. Tap on 'Apply'
4. Tap on the text field at the bottom saying 'Try out your setup'

Result: Keyboard is open, key hints are partially cut off by the circle shape

#### Environment information
- FlorisBoard Version: 0.3.14
- Install Source: F-Droid
- Device: Google Pixel 3a
- Android: 12L

#### Screenshots
Circle-shaped keys
![Circle](https://user-images.githubusercontent.com/96789053/160252259-5b318034-eff1-43d3-962e-2ddad67ff5a7.png)
Rectangle-shaped keys
![Rectangle](https://user-images.githubusercontent.com/96789053/160252261-e60171aa-1ae3-46d0-935a-edeceaf3de29.png)

**Comment by patrickgold** [comment]
Not really a bug but just how the shape implementation works. The shape is applied the whole key element is forced to clip to said shape. If you want to visualize it give the default key rule a colorful background to see what I mean.

What you could do is leave the default key rule to `Common shape`, then add a rule which targets the `?123`, `Enter` and `Space bar` directly, and only for those keys define the rounded shape you like. This was no hint cut-offs but still the Material3 like pillows.

The codes for above keys would be `-202`, `32` and `10`.

**Comment by cYDN48** [comment]
It's true that in my example you can achieve the same look without that problem (and I thank you for the solution that I'll be using from now on). But what about the users that want their key background color to be different from the whole keyboard background color? In that case they'd have to compromise on either having cut off key hints or not having circle shaped keys. 

Maybe instead of adding the key hints and then applying the key shape, you could apply the key shape and then add the key hint. In the case of circle-shaped keys this would obviously lead to the key hint poking out of the key background. But this might not be a bad thing, as you can also change the key hint background. If you also implement the option to change the key hint shape, it would enable custom themes like the following: 
![Example](https://user-images.githubusercontent.com/96789053/160254050-cef1c600-92db-4019-a8b5-8ac9ec1a40b1.png)
_(Excuse the bad editing)_

In any case, I think cut off key hints is undesirable behavior, which is why I labelled this as a bug. If you think the proposal label is more fitting, you can change it.

**Comment by patrickgold** [comment]
Ok yeah based on your explanation I can change the behavior. Re-labeled it as proposal, will address it before the next beta release.

**Comment by cYDN48** [comment]
Looks great! Thanks 😃
