### ISSUE TITLE
Landscape pop-out text box is missing since 0.3.14 stable

### ISSUE THREAD

**Issue by sandikata** [florisboard/florisboard#1711]
#### Short description
Keyboard hides the text input field 

#### Steps to reproduce
1. Go to any app and open florisboard
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: since 0.3.14
- Install Source: f-droid
- Device: Moto G200
- Android: 11
![Screenshot_20220327-065659](https://user-images.githubusercontent.com/884699/160266662-91d3e5bf-9f35-4f6f-9d39-bd7808d3d70b.png)

**Comment by patrickgold** [comment]
Thanks for your bug report!

Could you please answer the following questions for me:
- Does this apply for you in all apps?
- Also how do other keyboards behave in the app above?
- And does it only happen in landscape or also in portrait screen orientation?

Thanks in advance, this would incredibly help in tracking down the bug!

**Comment by sandikata** [comment]
Hello,

Yes it applies for all apps, no matter portrait or landscape.
Other keyboard apps behave properly (showing the text input field, not hidden behind the keyboard)

**Comment by ejedades** [comment]
Same issue with me. Occurs in most apps in landscape mode in version 3.14. 

Version 3.14
![Screenshot_20220401-011314_Messenger.jpg](https://user-images.githubusercontent.com/102756772/161118792-e3cba9f6-288e-4398-8209-ca57a18aef38.jpg

Verson 3.9
![Screenshot_20220401-012539_Messenger.jpg](https://user-images.githubusercontent.com/102756772/161118923-3f3c68e0-011e-41bf-b88c-d0bc1bb6c86f.jpg)

**Comment by patrickgold** [comment]
Ah I see the issue now: 0.3.14 has reworked the keyboard UI fundamentally and there's no landscape pop-out UI box like in 0.3.13 and earlier, because I oversaw the fact it was missing. Need to work on adding this back again, then this issue should be fixed.

**Comment by patrickgold** [comment]
Above PR adds back an extracted landscape UI with full theme support. If you want you can try out the debug APK to see if it works properly. Note that for custom themes it will be a generic black/white theme in the extracted UI, whereas for the default themes it is properly colored.

Will be released in 0.3.15-rc01 in the next days.
