### ISSUE TITLE
Error: Double-space period weird behaviour

### ISSUE THREAD

**Issue by markjoshwel** [florisboard/florisboard#1712]
#### Short description
Pressing space multiple times with double-space period enabled results in characters being deleted

#### Steps to reproduce
1. Go to 'Suggestions & Corrections'
2. Scroll down to 'Corrections'
3. Enable 'Double-space period'
4. Type in text
5. Press space buttom multiple times
6. See error

#### Environment information
- FlorisBoard Version: 0.3.14
- Install Source: F-Droid
- Device: Samsung Galaxy S8+
- Android: 12.1, LineageOS Unofficial

Screen Recording: https://user-images.githubusercontent.com/89562141/160274979-7ad6d2ab-3405-45d7-89bc-480757afcb00.mp4

**Comment by ranomier** [comment]
Jup can confirm. It deletes characters.

**Comment by patrickgold** [comment]
Can reproduce this bug within FlorisBoard's try-out-your-setup field itself, but not in other apps. Does it work for you in other apps (is a bit buggy though but does not delete stuff)?

**Comment by ranomier** [comment]
True, i didn't check that. Sorry my mistake.

It works in other apps.

**Comment by patrickgold** [comment]
Kk. This is a combi then of the apace bar double space buggyness and the preview field itself having some logic issues as well. Don't know how quickly I will fix this issue, but it is definitely known and reported quite often in the latest days so I need to fix it sooner than later.

**Comment by patrickgold** [comment]
Based on initial testing above PR fixes double-space period thanks to the new editor text caching mechanism and will release with 0.3.16-beta01 this weekend. When I merge the PR in this issue will auto-close. Could you still try it out once released so I can make sure I really fixed this issue? Thanks!

**Comment by markjoshwel** [comment]
> Based on initial testing above PR fixes double-space period thanks to the new editor text caching mechanism and will release with 0.3.16-beta01 this weekend. When I merge the PR in this issue will auto-close. Could you still try it out once released so I can make sure I really fixed this issue? Thanks!

Will do!

**Comment by markjoshwel** [comment]
Can confirm, does work as expected in 0.3.16-beta01! Lovely work and thank you for FlorisBoard!
