### ISSUE TITLE
Emoji Search 

### ISSUE THREAD

**Issue by jay5656** [florisboard/florisboard#1716]
Coming from the google keyboard, (not sure if its possible) but id love the abilty to search for certain emojis within the emoji section.

**Comment by GoRaN909** [comment]
Emoji search was suggested along time ago and maybe add when @patrickgold star working on 0.5.0 :) look at #45

**Comment by jay5656** [comment]
> Emoji search was suggested along time ago and maybe add when @patrickgold star working on 0.5.0 :) look at #45

Im so sorry i swear i looked through the lists before posting this, (proposal + emoji) i must have missed it.
