### ISSUE TITLE
Suggestions are displayed even when disabled

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#1719]
I disabled suggestions, yet they still appear,
![](https://i.imgur.com/UnqzuLk.jpg)

1,
![](https://i.imgur.com/yowHUqq.jpg)
2,
![](https://i.imgur.com/LTF657S.jpg)

Also, the cropped issue still occurs,
![](https://i.imgur.com/Z77tDV7.jpg)

Unable to see nor select, forcing user to click back button or cursor

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your report.

On first glance, there suggestions look like Android's native suggestions instead of belonging to Florisboard. Could you check whether you have enabled siggestions in your phone's settings?

**Comment by patrickgold** [comment]
Spell checker suggestions IS NOT word suggestions within the Smartbar. You have the spell checker enabled, but word suggestions off, so this is correct behavior.

**Comment by rancidfrog** [comment]
@Glitchy-Tozier 
Yes. Thank you. 
Disabling Spell check stops suggestions:
![](https://i.imgur.com/qz0Rnn8.jpg)

But,
What does it mean then for Florisboard being default spell checker?

**Comment by rancidfrog** [comment]
@patrickgold 
So what is word suggestions? The difference is not clear.

Also, when spell check was enabled, the suggestions were terrible. Is there any suggestions on how it can be improved or is it still a work in progress?
Just to see if I can do some tests, or just keep spell check off for the moment.

As apart from the overlapping between keyboard and spelling suggestions, florisboard is great.

**Comment by Glitchy-Tozier** [comment]
The issue seems to be resolved, closing.
