### ISSUE TITLE
Invisible on dark/black background

### ISSUE THREAD

**Issue by zekooooo** [florisboard/florisboard#172]
Hello, thanks for working on this project, I love it! I've been meaning to switch from the system default keyboard but there hasn't been a good alternative so far on F-Droid. Here's my first issue:

Since the keyboard is black and transparent, it becomes invisible or hard to see on dark backgrounds, such as in Firefox Klar.

Maybe it would be possible to work around this by detecting the background color and switching the keyboard to white if it's dark. A passive workaround would be to add a light-colored/white outline to keyboard letters.

Using v0.3.2 (F-Droid) on Android 7.0

**Comment by patrickgold** [comment]
What exactly do you mean with "dark and transparent keyboard"? Do you mean that every texture is either slid black or transparent and that you are able to "see through" the keyboard to the underlying app? If so, this means that the theme failed to load. Could you also try to go to Settings > Theme  and select a theme there? Maybe this resolves this issue.

Note: I am currently completely reworking the theme engine, so this bug should normally not exist in v0.3.3.

**Comment by patrickgold** [comment]
@zekooooo I've just released v0.3.3, which completely rewrites the theme engine. Did the theme engine rewrite fix your issue or does this issue still occur?

**Comment by patrickgold** [comment]
Closing issue as it is stale. Should there still be an issue with this, feel free to reopen.
