### ISSUE TITLE
Clipboard does not support videos, results in infinite crash loop

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1721]
I copied an mp4 video to the clipboard and florisboard ended in an infinite crash loop.

I had to delete the app. Clearing clipboard did not work. I think I was using version 0.3.15-beta01

**Comment by patrickgold** [comment]
The clipboard is currently only designed to handle text and images (jpg, png, ...), not videos. The primary reason is that I didn't even know that this is a thing.

Which app allows you to copy mp4 videos to the clipboard? This way I can try to implement this feature.

**Comment by patrickgold** [comment]
@Donkey-Doug which app were you using to copy a video to the clipboard? I tried my own research but couldn't at all get an mp4 to even try getting on the clipboard, so I am dependent on you to know which app allows it so I can reproduce it locally and then work on video support. Thanks!

**Comment by Donkey-Doug** [comment]
Aves gallery.

https://github.com/deckerst/aves

**Comment by patrickgold** [comment]
Above commit fixes the crash, videos now get properly imported into the clipboard UI. Haven't been able to test the paste of videos though, as no app on my devices accepts videos from the clipboard.

Will be released in 0.3.15-rc01 now, thanks again for reporting!
