### ISSUE TITLE
Slim German layout

### ISSUE THREAD

**Issue by pludi** [florisboard/florisboard#1723]
Please re-introduce a slim layout for German (QWERTZ) without keys for Umlauts & ß, moving them to their base characters again, as available in previous versions.

**Comment by patrickgold** [comment]
You can just use the default QWERTZ layout with "de" as the popup mapping, this would be the equivalent to a slim German layout.

**Comment by pludi** [comment]
This is the layout from 0.3.13:

![Screenshot_20220329-184923~2](https://user-images.githubusercontent.com/2112148/160664657-e87d9cab-b508-42ab-b77b-2a1861da6c04.png)

And this is it using the "de" popup mapping in 0.3.14:

![Screenshot_20220329-184706~2](https://user-images.githubusercontent.com/2112148/160664603-b810bbb8-2d05-4d9e-923a-6ec17f30a521.png)

So in 0.3.13 I have QWERTZ without umlauts, on 0.3.14 I have them with the default popup mapping.

Screenshots of the settings can be provided.

**Comment by patrickgold** [comment]
I still don't understand what's wrong with the 0.3.14 layouts for German.

Try adding a subtype which looks like this:

![image](https://user-images.githubusercontent.com/19412843/160671550-d91a6ddc-cb95-4a12-8519-49bb3dec3a88.png)

After saving, switch to the subtype and it should be exactly what you request, a QWERTZ layout without extra `äöüß` keys, and these 4 keys are popups of their respective base char `aous`. This is what you want, right?

**Comment by pludi** [comment]
Ah, now I see the issue. I didn't notice that there was a "QWERTZ"-only layout, I always selected the "German (QWERTZ)" layout and didn't notice the plain ones at the end.

Sorry, my bad.
