### ISSUE TITLE
Does force private mode is implemented!

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1727]
#### Short description
Hi @patrickgold in the previous stable version 0.3.13 before the new UI/UX that's we had now for FlorisBoard in the Advanced settings when user enabled (Force private mode) an security button was shown in purple colour on the left side smartbar near to select all button but now with newer version of app when you enables same option nothing shows up in the left side of smartbar, my question is that feature is implemented on the FlorisBoard or it's not yet implemented.

Here is a screenshot of feature i meant in this issue:

Note: app language is my native language.

Translate text in red box: Force private mode 

![Screenshot_20220331-010740_FlorisBoard](https://user-images.githubusercontent.com/3160786/160940779-67df1925-5543-4270-b8ab-bb1945eb8dd8.png)

#### Steps to reproduce
1. Go to 'Advanced settings 
2. Click on 'Forece private mode'
3. Scroll down to 'Button not show in smartbar'

#### Environment information
- FlorisBoard Version: 0.3.14 (75)
- Install Source:Google PlayStore
- Device: Galaxy S20 Fe 5G
- Android: 12, Stock Rom with OneUI 4.1

**Comment by patrickgold** [comment]
No it isn't, but any "smart" feature that would learn your words is currently (0.3.14) not implemented anyways, and won't be so until 0.4.0. Then I will make sure to add it again. Closing to keep the list of issues cleaner!
