### ISSUE TITLE
Limit clipboard item preview max length

### ISSUE THREAD

**Issue by saloniamatteo** [florisboard/florisboard#1730]
Greetings,
I installed the latest FlorisBoard beta, beta 0.3.15-beta01. While scrolling my clipboard, I noticed that a (fixed) item is displayed entirely, and it takes a really long time to scroll through all of it.

Basically, this item is a list of BitTorrent trackers, nothing out of the ordinary, and the recommended feature I'm suggesting is to limit the maximum length of the preview of the items, or to set a custom character limit (e.g. set custom limit to 150 characters). This would only affect the preview of the items, not the actual clipboard item content.

Image previews for this issue:
![issue_preview_1](https://user-images.githubusercontent.com/28765699/161060717-019601c1-a202-4be0-b5eb-e329897abe31.jpg)
![issue_preview_2](https://user-images.githubusercontent.com/28765699/161060727-baff3764-0f00-4c53-a675-03c7c837a8b9.jpg)
(it just keeps on going)

**Comment by patrickgold** [comment]
Thanks for your idea! Above commit implements your suggestion:

The normal preview is now capped to at most 5 lines of preview within the clip box, if it needs more then an ellipsis (...) is added at the end to indicate that it goes on further. When long pressing such an item, you can scroll through the long text in the popup. This does only affect the visual representation of the clip item, pasting will always paste the full content.

Will be released in 0.3.15-beta02 later today.

**Comment by saloniamatteo** [comment]
Thank you! 😁👍🏻
