### ISSUE TITLE
Problem with character (پ) in new persian layout

### ISSUE THREAD

**Issue by Mahantor** [florisboard/florisboard#1736]
Please replace the 31 character layout with 27 characters
The new Persian keyboard layout (Persian 2) has only 27 characters and the most used character (پ) is in the pop-up character (گ)
![Screenshot_2022-04-02-09-10-08-872-edit_dev patrickgold florisboard beta](https://user-images.githubusercontent.com/91434001/161366883-f14ad885-83f4-48c5-bdef-6e7005db3fa4.jpg)
![Screenshot_2022-04-02-09-07-36-969-edit_dev patrickgold florisboard beta](https://user-images.githubusercontent.com/91434001/161366888-0f77927a-b16c-4da9-b1c2-98a5d73f593c.jpg)

**Comment by patrickgold** [comment]
Isn't this the whole purpose of a second Persian keyboard, to have an alternative to the first one? In PR #1683 the author @ m-koushan states that it is based off the SwiftKey layout, so maybe it's done a bit differently there.

As I am not speaking Persian though I can't say much else about this issue. @m-koushan what do you think about the proposal above?

**Comment by m-koushan** [comment]
I made the new layout like Swiftkey keyboard layout.
![IMG_20220404_110452_521.jpg](https://user-images.githubusercontent.com/50526840/161486716-cd95482e-d908-4668-9bbc-48062501231c.jpg)
as you can see this is the swiftkey layout here i had before i find florisboard.
Also if you are not comfortable with it you can use the first one.

**Comment by m-koushan** [comment]
@patrickgold you can close this because its not even an issue, he/she made this only for his/her convenience and there is no problem with the layout. As is said he/she can use first layout instead. Thanks for your concern.

**Comment by op30mmd** [comment]
@mkoushan the swiftkey layout is diffrent, the (پ) is in the (گ). But your layout doesnt have this, it must popup the پ but it doesnt. So its basically arabic

**Comment by mkoushan** [comment]
> @mkoushan the swiftkey layout is diffrent, the (پ) is in the (گ). But your layout doesnt have this, it must popup the پ but it doesnt. So its basically arabic

Are you sure that you're using persian2 (fa2) layout? Because I'm using it and it's working for me

**Comment by op30mmd** [comment]
@mkoushan ![Screenshot_20240915_131131_FlorisBoard Beta.jpg](https://github.com/user-attachments/assets/d2964394-9e7d-47eb-aca3-6d8e2392ac1f)

**Comment by op30mmd** [comment]
Is it only available in stable version?

**Comment by op30mmd** [comment]
Or another versions?

**Comment by mkoushan** [comment]
@op30mmd > Is it only available in stable version?
No it's available in both beta and stable.
I think you have selected the Persian2 layout but not the fa2 popup mapping. Check the sub-type and select the fa2 for ``Popup mapping`` section.

**Comment by op30mmd** [comment]
> @op30mmd > Is it only available in stable version?
> No it's available in both beta and stable.
> I think you have selected the Persian2 layout but not the fa2 popup mapping. Check the sub-type and select the fa2 for ``Popup mapping`` section.
> 
> 

@mkoushan thanks

**Comment by op30mmd** [comment]
@mkoushan Would it be possible for you to add the Samsung keyboard layout?
