### ISSUE TITLE
Wrong place of two characters in Persian layout 2

### ISSUE THREAD

**Issue by Mahantor** [florisboard/florisboard#1737]
#### Short description
Please change the place of these two characters together. This problem was solved in Farsi 1 layout, but it exists in Farsi 2 layout.
![Screenshot_2022-04-02-09-31-57-860-edit_ir ilmili telegraph](https://user-images.githubusercontent.com/91434001/161367367-fc569b2f-112e-495e-98b9-0d0058e83346.jpg)

#### Environment information
- FlorisBoard Version: 
- Install Source: GitHub
- Device: xiaomi redmi note 9 pro
- Android: 11

**Comment by patrickgold** [comment]
Can be fixed together with #1736 probably, placing it on the kbd-layout issue list.

**Comment by m-koushan** [comment]
Now it's fixed. Thanks for reporting @Mahantor !
