### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by Raif1** [florisboard/florisboard#1740]
#### Short description
Cant use other languages except english

Does the app need internet access to download and use other languages ? I have blocked florisboard from connetring to the internet.

**Comment by GoRaN909** [comment]
By defaults only English(Qwerty) is enabled if you want other languages and layouts you need add it to the list

1- Open FlorisBoard settings 

2- Goto languages & layout first option 

3- Tap on Add subtype then press on Show all if not suggest any languages

4- In the list pick one of available language & layout.

5- To change layouts swipe left/right 

That's everything so simple 😶

**Comment by GoRaN909** [comment]
By defaults only English(Qwerty) is enabled if you want other languages and layouts you need add it to the list

1- Open FlorisBoard settings 

2- Goto languages & layout first option 

3- Tap on Add subtype then press on Show all if not suggest any languages

4- In the list pick one of available language & layout.

5- To change layouts swipe left/right 

Florisboard is no need Internet to work or add languages it's fully offline and only permission used is 

`<uses-permission android:name="android.permission.VIBRATE"/>
`

That's everything so simple 😶

**Comment by patrickgold** [comment]
> Cant use other languages except english

Depends on where you want to change languages. In the Settings UI you can do this in Advanced > Settings language.

For the keyboard subtypes, you'd go to Localization > Add subtype (+), in there everything can be set. Note though that word suggestions currently work in no language and glide typing only in English (US), so that's something to be aware of.

Everything stated is based on the latest stable 0.3.14.

**Comment by Raif1** [comment]
> By defaults only English(Qwerty) is enabled if you want other languages and layouts you need add it to the list
> 
> 1- Open FlorisBoard settings 
> 
> 2- Goto languages & layout first option 
> 
> 3- Tap on Add subtype then press on Show all if not suggest any languages
> 
> 4- In the list pick one of available language & layout.
> 
> 5- To change layouts swipe left/right 
> 
> Florisboard is no need Internet to work or add languages it's fully offline and only permission used is 
> 
> `<uses-permission android:name="android.permission.VIBRATE"/>
> `
> 
> That's everything so simple 😶

Ah then 

![ooo.png](https://user-images.githubusercontent.com/93464125/161450635-74cb5e7c-4df8-48bf-b19f-1996aaf96842.png)

I have selected arabi but my keybord is in english

**Comment by Raif1** [comment]
Aaaah my language doesnt have characters layout so i checked arabi but i wasnt able to make it right. After checking arabic preset i was able to make the characters right

**Comment by Raif1** [comment]
I will be closing this then
