### ISSUE TITLE
Caps lock issue with JuiceSSH

### ISSUE THREAD

**Issue by KaKi87** [florisboard/florisboard#1742]
#### Short description
> I'm using JuiceSSH, and when I'm in the terminal, press Shift then a letter, Shift remains active. To turn off Caps Lock(?) I have to press Shift twice

Source : AnySoftKeyboard/AnySoftKeyboard#446

I am experiencing exactly the same issue using FlorisBoard.

#### Steps to reproduce
1. Open a JuiceSSH terminal
2. Press Shift to enable
3. Press Shift to disable
4. Notice Shift still enabled
5. Press Shift again
6. Notice Shift finally disabled

#### Environment information
- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Device: Xiaomi Mi 8
- Android: 11, DotOS

---
Thanks

**Comment by tsiflimagas** [comment]
This issue has been fixed in latest version, 0.3.14. Please update to it, and confirm that's the case (and close the issue if it is). Thank you!

**Comment by KaKi87** [comment]
Yes, the issue was fixed, however :
- my preferences were reset
- the default swipe velocity treshold was increased
- delete key's can be decreased but the spabar's cannot

**Comment by KaKi87** [comment]
Also, I think keys' height has been decreased and I don't like it...
