### ISSUE TITLE
Improve Vietnamese keyboard

### ISSUE THREAD

**Issue by DNM1008** [florisboard/florisboard#1751]
Support for Telex is welcomed, but it could be better. during normal use on any other keyboard/operating system, you can type the whole word before adding the signs, and they would be centered and be at the correct place. In Floris, you have to type the letters and signs one by one, which is not very convenient.

For example, when I typed "chuoois", the text in the box should be "chuối", not "chuôis", or when I typed "oaf", the returned text should be "òa", not "oà".

Perhaps it's better to learn from iBus' way of implementing Telex on the desktop?

**Comment by thanhhocse96** [comment]
I'm working on it.
At the moment the rule for telex is too simple. I'm adding more rule to the telex composer

**Comment by nhm567** [comment]
Làm sao để có giao diện tiếng Việt?

**Comment by thanhhocse96** [comment]
> Làm sao để có giao diện tiếng Việt?

@nhm567 In \[Language and Layout\] choose Add Subtype
