### ISSUE TITLE
Emoji panel black on black with a monochromatic emoji font and the background changed to #000000

### ISSUE THREAD

**Issue by janicez** [florisboard/florisboard#1752]
#### Short description
I use a monochrome emoji font and a #000000 background in a modified Night theme.

#### Steps to reproduce
1. Install a monochrome emoji font on a phone already running FlorisBoard 0.3.14
2. Create a theme with a #000000 background
3. Try to input an emoticon

#### Environment information
- FlorisBoard Version: 0.3.14 
- Install Source: F-Droid 
- Device: OnePlus GM1915 
- Android: 11 lineage_guacamole-userdebug 11 RQ2A.210505.003 a6df48d972

**Comment by patrickgold** [comment]
Could you please check the latest beta release 0.3.15-beta02 if this bug is fixed for you? Should be like I stated in the Matrix channel but want to make sure it is for you too.

**Comment by patrickgold** [comment]
Closing as stated that it is fixed by OP in the Matrix group.
