### ISSUE TITLE
Crash occurs when opening the keyboard in landscape mode before portrait

### ISSUE THREAD

**Issue by Keepkeepzz** [florisboard/florisboard#1758]
#### Short description
If I initally open the keyboard in landscape mode it crashes. The crash doesn't occur if I have opened in portrait mode first. It also doesn't happen if landscape full screen input is set to never show.

#### Steps to reproduce
1. Make sure landscape full screen mode is not set to dynamically show or always show.
2. Close the Florisboard Beta app.
3. Reopen the app.
4. Rotate to landscape mode.
5. Open the keyboard.
6. See crash.

#### Environment information
- FlorisBoard Version: 0.3.15-rc01 (78)
- Device: HMD Global Nokia 7.1
- Android: 10 (cn=Q sdk=29)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = false
clipboard_history = true
```

#### Attached stacktrace files
<details>
<summary>1649217207271.stacktrace</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.inputmethodservice.ExtractEditText.setIME(android.inputmethodservice.InputMethodService)' on a null object reference
	at android.inputmethodservice.InputMethodService.setExtractView(InputMethodService.java:1638)
	at android.inputmethodservice.InputMethodService.updateFullscreenMode(InputMethodService.java:1330)
	at dev.patrickgold.florisboard.FlorisImeService.updateFullscreenMode(FlorisImeService.kt:397)
	at android.inputmethodservice.InputMethodService.prepareWindow(InputMethodService.java:1934)
	at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:1884)
	at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:638)
	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:220)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```
</details>

**Comment by patrickgold** [comment]
Thanks for your bug report!

Cannot specifically reproduce this bug. Does this crash occur for all apps or is there a specific one does this?

**Comment by Keepkeepzz** [comment]
The crash occurs in any app that I use. It only happens if the keyboard hasn't 'loaded in' (like when you open the keyboard and it takes a second or two to for the keys to appear). For me I can force that to happen when I have the Florisboard Beta app open and then swipe to close it, then the next time I bring up the keyboard it happens. It's just that when trying to do that in landscape it crashes.

**Comment by Keepkeepzz** [comment]
In 0.3.15-rc01 when they keyboard is 'loaded in' landscape with fullscreen input set to always or dynamically show, it would always result in a crash.

However in the debug version you linked in #1760 it doesn't. It now only crashes if it uses the fullscreen input method, So if I have it set to dynamically show and 'load it' in landscape but in a text field that uses the normal input it won't crash.

**Comment by patrickgold** [comment]
Hmm ok yeah as I thought. However are you sure it doesn't only crash in landscape if the extracted text field is needed right from the start in 0.3.15-rc01 too? The logic behind this hasn't changed, the extracted text view is only then constructed when it is really needed.

**Comment by Keepkeepzz** [comment]
Yes, in rc01 it crashes if I open it in landscape in any text field regardless of whether it uses extracted text view. In debug it only happens when it uses extracted text view.

**Comment by patrickgold** [comment]
Ok that is very strange. I will try out something later to attempt to mitigate the crash, but it is difficult to test because it does not crash on any of my testing devices.

**Comment by patrickgold** [comment]
Ok so after some experimenting and source code digging I think I found a solution. Could you please try out the new debug APK of above PR to check if the crash has been fixed for you? Thanks!

**Comment by Keepkeepzz** [comment]
It looks like it's fixed. I've set it to always use extracted text view, opened and closed the Florisboard debug app and tried it in a bunch of different apps and text fields and I haven't experienced the crash at all.

**Comment by patrickgold** [comment]
Thanks for testing out, will merge the changes in then and later release 0.3.15-rc02.
