### ISSUE TITLE
Thai Keyboard does not show extra symbols

### ISSUE THREAD

**Issue by thiskappaisgrey** [florisboard/florisboard#1759]
#### Short description
Thai keyboard does not show special accent characters(not sure what to call it) like " "่ื. The keys work as normal though. here's a photo:
![IMG_20220405_212226](https://user-images.githubusercontent.com/16870341/161895420-6dcffe65-21f1-4f8a-b35c-98f45c9577c6.jpg)

The expected behavior is(using android keyboard):
![IMG_20220405_213505](https://user-images.githubusercontent.com/16870341/161896477-ecc6d193-4902-4da4-9896-af94f5867dec.jpg)

#### Steps to reproduce
1. Use default settings for Thai
![Screenshot_20220405-212838](https://user-images.githubusercontent.com/16870341/161896000-09e499ff-6d0d-425d-8083-797fc60830a4.png)

#### Environment information
- FlorisBoard Version: 0.3.15-rc01 (78)
- Install Source: Github
- Device: Pixel 5a
- Android: 12, Calyx

**Comment by patrickgold** [comment]
> Thai keyboard does not show special accent characters(not sure what to call it) like " "่ื. The keys work as normal though

You mean the [Unicode Non-spacing characters](https://www.compart.com/en/unicode/category/Mn). These characters cannot display without a base character. Above commit thus adds a fix for this, so Thai non-spacing characters have a dotted circle on the key as a base (the dotted circle will not be inputted, is just for display as a key label).

Will be released in 0.3.15-rc02 soon, thanks for reporting!
