### ISSUE TITLE
Bug that causes landscape keyboard to be place higher than it should be

### ISSUE THREAD

**Issue by Keepkeepzz** [florisboard/florisboard#1760]
#### Short description
Opening landscape keyboard with fullscreen input will make it so the next time you open it in normal landscape the keyboard will be placed much higher on the screen than it should be.

#### Steps to reproduce
1. Set landscape fullscreen input to dynamically show
2. Rotate to landscape.
3. Tap on a text field that automatically uses fullscreen input.
4. Close the keyboard. Make sure not to open the keyboard in portrait mode.
5. Tap on a text field that doesn't use fullscreen input.
6. See bug.

Alternate method:
1. Set landscape fullscreen input to always show
2. Open the keyboard in landscape mode.
3. Close the keyboard.
4. Set landscape fullscreen input to never show.
5. Open the keyboard.
6. See bug.

#### Environment information
- FlorisBoard Version: 0.3.15-rc01
- Install Source: Github
- Device: Nokia 7.1
- Android: 10, Stock
![Screenshot_20220406-165607](https://user-images.githubusercontent.com/99106227/161898792-53e5ab38-9d77-4ba8-aa82-f4c8b6087287.png)

**Comment by patrickgold** [comment]
Thanks for your bug report!

Can confirm and reproduce this bug. Interestingly the touch space itself is correctly calculated, but then the UI is shifted upwards. Placing on my keyboard UI issue list.

**Comment by patrickgold** [comment]
Above commit is a fix for the placement of the keyboard view and also fixes some state bugs within the extracted input UI visibility.

Could you please check the debug artifact APK of above linked PR to try it out on your device that it now works correctly? Note that I didn't fix #1758 yet, so ensure to "load in" the keyboard in portrait first. You can try starting it in landscape immediately too but I doubt that I accidentally fixed the #1758 crash too. Thanks in advance!

**Comment by Keepkeepzz** [comment]
I tried it out and it seems like both this and the crash I posted about are fixed.

**Comment by Keepkeepzz** [comment]
Was unsure of whether I should create a new issue or comment here but this bug has kinda returned in 0.4.0-alpha03.

Same steps to repropduce and everything except now the keyboard goes all the way to the top of the screen.

![Screenshot_20220830-202006.png](https://user-images.githubusercontent.com/99106227/187392591-e6aadadd-13fc-41d4-bf5d-e724e899d2fe.png)

![Screenshot_20220830-202300.png](https://user-images.githubusercontent.com/99106227/187392629-28a5c681-bc06-41ca-9af6-cbdfad535e53.png)

**Comment by patrickgold** [comment]
I was able to reproduce this issue. The newly introduced bottom sheet host UI didn't account for a potential landscape input UI. Now the bottom sheet should just overdraw the landscape input UI and the keyboard should be placed correctly (you can try out the debug artifact if you want of above linked PR). Will be parts of the v0.4.0-alpha04 release.
