### ISSUE TITLE
Hold-Shift for Quick Capitilization

### ISSUE THREAD

**Issue by realdep** [florisboard/florisboard#1764]
As the title suggests, currently when you hold shift, only the first letter is capitilized. I suggest making it like a physical keyboard where as long as you keep shift held down, everything typed is capitilized. 

This conflicts with the current hold-to-toggle (which is honestly very buggy) but nothing a simple option in the settings can't fix.

**Comment by m-koushan** [comment]
pls check out the [Bug Reporting Guideline ](https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md#bug-reporting) for reporting issues.

**Comment by patrickgold** [comment]
Above commit/PR reworks the long press behavior of shift:

While the shift key is pressed down, you can type capitalized letters like on PC now. However normally the caps lock is activated after long press timeout. Above commit adds a logic that suppresses long press shift for caps lock if you enter a character before caps lock gets activated. This way when releasing the key it resets back to unshifted. If you don't enter a character then caps lock gets activated after long press timeout, like previously.

This behavior is the hybrid solution between keeping support for long press shift for caps lock and your proposal, I hope it satisfies your request close enough. Will be released in 0.3.16-beta02 in a few days. Thanks again for your suggestion!

**Comment by OoTMaestro** [comment]
Does this change allow for a shift+enter equivalent as one would find on a physical keyboard?
