### ISSUE TITLE
Please allow manual switch to Numpad mode

### ISSUE THREAD

**Issue by firefoxlover** [florisboard/florisboard#1766]
Sometimes, for example for Wifi passwords, the password isn't always a pin, but in fact it is.

This is just a comfort feature, but switching to the numpad manuall would be very useful in this case.

Thank you!

**Comment by patrickgold** [comment]
You can already always switch from the characters via symbols to the numeric advanced layout (1234 key in symbols), which also contains a numpad. Does this satisfy your proposal?

**Comment by m-koushan** [comment]
I think it would be better if we put the 1234 key in ?123 popups too

**Comment by tsiflimagas** [comment]
> I think it would be better if we put the 1234 key in ?123 popups too

If you'd like to have this change, it would be better to open a new proposal for it, so it can be tracked. 

As I see it, this is already implemented, in the very basic functionality of the keyboard. In case there's a misunderstanding of your proposal, feel free to reopen the issue, providing more information.
