### ISSUE TITLE
Quick control hide button is unnessecary, should be deletable

### ISSUE THREAD

**Issue by firefoxlover** [florisboard/florisboard#1767]
The button doesn't hide the quick controls actually, then the bar is just empty.

Also duplicating the quick controls to the row above doesn't do anything, maybe this will be useful when there is auto-correction right?

I wont use that feature, so please make the "hide" button (">") removable. 

Also, editing to items on the quick control panel would be somewhat useful, but thats a different request.

**Comment by patrickgold** [comment]
Atm it is unnecessary, this is correct. However once word suggestions come in the 0.4.0 dev cycle then this button will not be at all unnecessary anymore, so it will not be removable.

> Also duplicating the quick controls to the row above doesn't do anything, maybe this will be useful when there is auto-correction right?

That is more meant to switch where the clipboard and quick action rows are placed and not to duplicate one row.

> Also, editing to items on the quick control panel would be somewhat useful, but thats a different request.

That's true and an in-UI todo is already there, so it will come in the future :)

**Comment by patrickgold** [comment]
Closing as this proposal does
