### ISSUE TITLE
When glide swiping then manually typing Florisboard neglects adding a space between words. 

### ISSUE THREAD

**Issue by soulmist7** [florisboard/florisboard#1777]
_**Short description**_
Using the latest version, after glide typing a word, manually typing neglects to enter a space in front of the last word, resulting in two words mashed together. This is either a bug (this functionality was present in the last version) or needs a toggle in settings that allows the feature to be used or turned off.

_**Steps to reproduce**_
Glide type some word
Manually enter a new word one letter at a time
New words are attached to the old word, without a space entered between them.

_**Environment information**_
FlorisBoard Version: v0.13.4 (75)
Install Source: Fdroid
Device: Pixel5a
Android: 12, CalyxOS 3.4.0

**Comment by soulmist7** [comment]
(This in conjunction with the backspace bug not removing whole words after swipe make the keyboard almost unusable.)

**Comment by Glitchy-Tozier** [comment]
I agree that this stuff like this (and the backspace-bug) needs to be fixed for glide-typing to be viable.

**Comment by patrickgold** [comment]
Thanks for your bug report!

This is indeed a bug, the glide typing commit word function was not setting the phantom space flag, thus there was never a space entered for manual input after a glided word. This is now fixed in above PR and will be released in 0.3.16-beta01 soon.

**Comment by patrickgold** [comment]
As for the backspace word deletion after a glided word: I am aware of this and will try to add this also in for 0.3.16-beta01

**Comment by madduck** [comment]
When I am sliding to type a couple of words,no spaces are inserted at all. What am I doing wrong? Using latest beta...
