### ISSUE TITLE
space on , key persian2 layout

### ISSUE THREAD

**Issue by m-koushan** [florisboard/florisboard#1778]
#### Short description
After re-ordering the emoji icon in persian2 layout, I see a weird ```space``` thing on ```،``` key.
I checked on one other device (Samsung s20 fe) and its not appearing on that. Maybe problem occurs when you change size of keyboard or theme.

![Screenshot_2022-04-12-00-08-54-732_nekox messenger_1](https://user-images.githubusercontent.com/50526840/162818022-c5eb095a-4539-473f-ab1a-bad091e4a26e.jpg)

#### Steps to reproduce
1. Go to settings and add persian2 subtype
2. Click on somewhere to test
3. Switch to persian language

#### Environment information
- FlorisBoard Version: 0.3.15-rc02
- Install Source: GitHub
- Device: Redmi Note 8 Pro
- Android: 11

**Comment by patrickgold** [comment]
Thanks for your bug report!

The hint logic did not filter out the space bar from symbols, this is why you saw the hint above the comma here. I now fixed this with above commit, will be released with 0.3.16-beta01 soon.
