### ISSUE TITLE
SmartBar icons too small Landscape mode

### ISSUE THREAD

**Issue by dude-shah** [florisboard/florisboard#1781]
Can Make it the same size as the icons in secondary action row, those icons are too small in landscape.
![IMG_20220412_062606.jpg](https://user-images.githubusercontent.com/63038690/162860196-55b39b41-8700-42ee-a602-5e278c4fea7c.jpg)

**Comment by bege10** [comment]
For the icons are too small generally, not only in landscape mode.
smartbar-key font-size only affects secondary smartbar.

**Comment by patrickgold** [comment]
Above PR/commit fixes your issue, the icon size is now bigger and adjusted to the other icons in landscape mode. Thanks for reporting this issue! Will be parts of the 0.4.0-alpha03 release in the future.
