### ISSUE TITLE
Removing non-existent items from clipboard disables other buttons

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1783]
#### Steps to reproduce

1. Go to the clipboard-manager
1. Make sure the clipboard is empty
1. Click on the delete-items-button
1. See bug

#### Solution
What would be nice to see
1. That this bug didn't happen
2. That all (both) delete-clipboard-history buttons get disabled when there's no items in the clipboard-manager

#### Environment information
- FlorisBoard Version: 0.3.15-rc01 (78)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

#### Screenshots, in order
![Screenshot_20220412-082634_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/162908580-b71e7906-18b9-4105-b0af-4eb631598a5d.jpg)
![Screenshot_20220412-082657_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/162908607-96ccd2a9-d423-43cf-b4bc-5808ed55342b.jpg)
![Screenshot_20220412-082714_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/162908633-07fbe810-f1b6-4d7b-b5fe-9bb09c57df07.jpg)
![Screenshot_20220412-082732_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/162908653-7d883cf5-3ff9-4022-a499-76dd738a8b23.jpg)

**Comment by patrickgold** [comment]
This is a sneaky bug, but luckily easy to solve. What happens here is that the buttons disable themselves do you don't press them while the dialog is open, but only after that I check if the dialog even makes sense to show. Need to make the check before disabling and this bug will be solved. Placing on my clipboard issue list.

**Comment by Glitchy-Tozier** [comment]
👍🏻
Additionally, I think the "disable history"-button shouldn't get disabled.

**Comment by patrickgold** [comment]
No I only disable the clear button while the confirmation dialog would show. If there's nothing to show I will change it to a don't disable the buttons and b) show a toast saying something like "Nothing to clear...".

**Comment by Glitchy-Tozier** [comment]
I'm not sure, what you mean. I was talking about this switch-button and saying that it shouldn't get disabled:
![image](https://user-images.githubusercontent.com/59611881/162921231-f8f91ab1-3315-4d48-912e-6fb911c61b5b.png)

**Comment by Glitchy-Tozier** [comment]
> Ah so you mean the button to disable the clipboard history? If so it is affected by the same state bug and me fixing the accidental grey out when empty will also fix this.

Yep

> Edit: I conclude I cannot read xd, you clearly stated "disable history button". Yeah that button will only be disabled if the dialog really shows.

Ah, now I finally understand the bug! You act as if there was a pop-up, even though there isn't.

**Comment by patrickgold** [comment]
> Ah, now I finally understand the bug! You act as if there was a pop-up, even though there isn't.

Yep exactly!

**Comment by Glitchy-Tozier** [comment]
Btw, I think I didn't make this clear: I think this button should get disabled when there's no clipboard-elements:
![Screenshot_20220412-143712_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/162983853-6e4554fc-2c96-4121-b3fb-42eef2954b17.jpg)

**Comment by patrickgold** [comment]
Above commit is the simplest and most straightforward fix: Like you stated in your original request, I just disable the history delete button if there's no history.

If the history is empty the other two buttons, disable history and edit/add items will still stay active, as those still have a use if there are no clipboard entries.

Also like discussed above the primary clip delete button is synced with the paste button and not the history, so left it as as.

Will be released in 0.3.16-beta01 soon, thanks for finding this bug :)

**Comment by Glitchy-Tozier** [comment]
Got it,good job! :)
