### ISSUE TITLE
Design rules don't apply to ABC and backspace key on emoji page

### ISSUE THREAD

**Issue by bege10** [florisboard/florisboard#1784]
#### Short description
Added rules for ABC and backspace keys have no effect on emoji page

#### Steps to reproduce
1. Add rule (in my case background) for mentioned keys
2. Works on letters and numbers page
3. No effect on emoji page

#### Environment information
- FlorisBoard Version: 0.3.15-rc02
- Install Source: IzzyOnDroid repo
- Device: Fairphone 3
- Android: 10, /e/OS (based on LineageOS for microG, Android 10)

**Comment by Takokeshi** [comment]
https://github.com/florisboard/florisboard/discussions/1675 is most likely related.

**Comment by tsiflimagas** [comment]
Emoji panel is pretty different from the main layout, so I'm not sure if it's supposed to be themed. So, this is probably not a bug, but it could be a potential proposal (I mean I don't know if it would be accepted). I'd rather hear what Patrick has to say though.
