### ISSUE TITLE
Add gesture to toggle Smartbar on/off

### ISSUE THREAD

**Issue by Nenoeldeeb** [florisboard/florisboard#1794]
The Smartbar is a great feature.
It helps me a lot, especially with clipboard shortcuts.
But I think not everybody uses it every time he opens a keyboard and it makes the keyboard much taller without any benefit.
So that if you add a gesture to quickly toggle it this will be much appreciated.
Thank you.

**Comment by patrickgold** [comment]
Thanks for your feature proposal!

Above PR adds a new swipe action called "Toggle Smartbar visibility", which will dynamically toggle the Smartbar for you each time the gesture is triggered. Note that this is basically just a wrap around the "Smartbar enabled"-preference, and as such it will remember the last Smartbar state even if you close and restart the keyboard.

Will be released in 0.3.16-beta01 soon.

**Comment by Nenoeldeeb** [comment]
Thank You about this great keyboard.
