### ISSUE TITLE
Add Emoji History

### ISSUE THREAD

**Issue by Mifuto** [florisboard/florisboard#180]
Pretty self-explanatory title.
I went through some open issues regarding emojis and I saw that you plan on implementing emoji search. I personally think emoji history would be more useful than emoji search, so it would be nice if you consider implementing emoji history too.

**Comment by patrickgold** [comment]
Thanks for the suggestion! This can definitely be done and is already on my todo list for v0.5.0. (But it seems that there's no issue specific for the emoji history, so this issue is now assigned to the todo entry.)

**Comment by patrickgold** [comment]
I will transfer this issue into #268, which provides more details how this history ("recents") should look like. Else nothing has changed, it is still planned for the v0.5.0 milestone and will be implemented together with the media rework.
