### ISSUE TITLE
settings not loaded on reboot

### ISSUE THREAD

**Issue by theotheroracle** [florisboard/florisboard#1809]
#### Short description
on reboot the settings are not loaded until i kill the app and open it again

#### Steps to reproduce
1. reboot
2. settings are not loaded

#### Environment information
- FlorisBoard Version: 0.3.15-rc02 (79)
- Install Source: izzydroid
- Device: OnePlus 7T
- Android: lineage, android 11

**Comment by Takokeshi** [comment]
Likely the same as #1726

**Comment by theotheroracle** [comment]
oh rats, i searched for rebooting and not restarting, sorry
