### ISSUE TITLE
Bépo layout

### ISSUE THREAD

**Issue by Salamandar** [florisboard/florisboard#181]
Thanks for such a great keyboard !
Gonna use it... Once it gets the bépo layout.
here's a screenshot of SwiftKey's bépo layout.
The first layer is OK, the "overlay" characters not so much. 

![Screenshot_20210113-231725_Firefox_1](https://user-images.githubusercontent.com/6552989/104517265-02aadd00-55f6-11eb-9e90-e9128fca1fdc.png)

**Comment by patrickgold** [comment]
Thanks for the proposal! I will definitely add this layout to FlorisBoard, but probably not before v0.5.0 (v0.4.0 milestone is too packed already). Added to my todo list!

**Comment by Salamandar** [comment]
@patrickgold I took some time to do a PR so that you can focus on something else :D
