### ISSUE TITLE
Florisboard settings reset upon force rebooting device

### ISSUE THREAD

**Issue by alissonlauffer** [florisboard/florisboard#1819]
#### Short description
When I force reboot my device (e.g.: to recover from hangs), Florisboard settings are reset.
Maybe Florisboard preferences database get corrupted somehow by force rebooting?

#### Steps to reproduce
1. Customize Florisboard to your liking
2. Keep the keyboard open
3. Force reboot your device (Press the power button for ~5 seconds)
4. Open the keyboard
5. See the preferences returning to default

#### Environment information
- FlorisBoard Version: 0.3.15
- Install Source: GitHub
- Device: Poco F3
- Android: 12 (ArrowOS custom ROM)

**Comment by tsiflimagas** [comment]
Thanks for your bug report! Some other users face the same problem too and there's currently an open issue for it, #1726. Let's close this one and keep discussion about this there.
