### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by paledega** [florisboard/florisboard#182]
Keyboard doesn't support turkish language. 

Turkish has two type

First type is qwerty with turkish characters. Second type is turkish f keyboard.  Turkish keyboard users generally use turkish q and a lot of users use turkish f

I can help you for creating turkish layouts

**Comment by paledega** [comment]
# Turkish f ![IMG_20210114_070447](https://user-images.githubusercontent.com/38860643/104543588-a956a400-561d-11eb-9b72-447d145c674b.jpg)

**Comment by patrickgold** [comment]
I will add this to my todo list, probably for the v0.5.0 milestone (v0.4.0 is almost full). Thanks for the suggestion!

**Comment by patrickgold** [comment]
Above PR adds both a Turkish-Q and Turkish-F layout, available to choose from in the subtype dialog. Will be shipped with the next beta release v0.3.10-beta03 tomorrow.
