### ISSUE TITLE
Default layout after restart for first login

### ISSUE THREAD

**Issue by jopejoe1** [florisboard/florisboard#1821]
#### Short description
After restarting the phone it uses the default layout for the first login.

#### Steps to reproduce
1. Enable number row
2. Change layout
3. Restart phone
5. Shows default layout and no numbers row

#### Environment information
- FlorisBoard Version: 0.3.15 (80)
- Install Source: F-Droid
- Device: Samsung Galaxy S10+
- Android: 12

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-request!
Is this first login part of the booting-process or are you referring to a "regular login", on a website, for example?

**Comment by jopejoe1** [comment]
Im referring to the first login after booting

**Comment by Takokeshi** [comment]
If you are using encryption with an alphanumeric password, then this is expected because the app doesn't have access to user preferences before decryption.

**Comment by jopejoe1** [comment]
Earlier versions of the app remembered the layout and if the number row should be showen.

**Comment by patrickgold** [comment]
During the first login the user data in encrypted and I can only access the device encrypted storage, thus your layout choice is not applied.

#1123 proposes that a minimal necessary config gets stored in the device encrypted storage too, so the keyboard can use the correct layout without knowing the user data config yet in the first login. Closing as a duplicate thus.
