### ISSUE TITLE
Fatal Crash when switching apps

### ISSUE THREAD

**Issue by AnonWombat** [florisboard/florisboard#1824]
#### Short description
I typed something in one app, and then switched to anorher. Then my phone crashed and rebooted

04-27 19:32:23.165 E/AndroidRuntime( 3604): FATAL EXCEPTION: main

04-27 19:32:23.165 E/AndroidRuntime( 3604): Process: dev.patrickgold.florisboard.beta, PID: 3604

04-27 19:32:23.165 E/AndroidRuntime( 3604): kotlin.UninitializedPropertyAccessException: lateinit property popupUiController has not been initialized

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutController.getPopupUiController(TextKeyboardLayout.kt:439)04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt.TextKeyboardLayout$lambda-9$resetAllKeys(TextKeyboardLayout.kt:146)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt.access$TextKeyboardLayout$lambda-9$resetAllKeys(TextKeyboardLayout.kt:1)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt$TextKeyboardLayout$1$3.invoke(TextKeyboardLayout.kt:162)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.ime.text.keyboard.TextKeyboardLayoutKt$TextKeyboardLayout$1$3.invoke(TextKeyboardLayout.kt:160)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1.invoke$lambda-0(DisposableLifecycleEffect.kt:37)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1.$r8$lambda$-3ALqMvi9iwlusIGFG3z5Hb_ybQ(Unknown Source:0)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.app.ui.components.DisposableLifecycleEffectKt$DisposableLifecycleEffect$1$$ExternalSyntheticLambda0.onStateChanged(Unknown Source:4)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.ime.lifecycle.LifecycleInputMethodService.onWindowHidden(LifecycleInputMethodService.kt:81)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at dev.patrickgold.florisboard.FlorisImeService.onWindowHidden(FlorisImeService.kt:372)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.inputmethodservice.InputMethodService.hideWindow(InputMethodService.java:2354)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.inputmethodservice.InputMethodService.doHideWindow(InputMethodService.java:2339)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.inputmethodservice.InputMethodService.access$700(InputMethodService.java:301)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInput(InputMethodService.java:766)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.inputmethodservice.InputMethodService$InputMethodImpl.hideSoftInputWithToken(InputMethodService.java:739)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:232)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.os.Handler.dispatchMessage(Handler.java:106)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.os.Looper.loopOnce(Looper.java:201)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.os.Looper.loop(Looper.java:288)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at android.app.ActivityThread.main(ActivityThread.java:7871)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at java.lang.reflect.Method.invoke(Native Method)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)

04-27 19:32:23.165 E/AndroidRuntime( 3604): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by tsiflimagas** [comment]
Please don't remove the template when creating an issue. If you don't fill the information in, other people can't understand nor help you. At least information about your OS and FlorisBoard version are rudimentary.

**Comment by AnonWombat** [comment]
> Please don't remove the template when creating an issue. If you don't fill the information in, other people can't understand nor help you. At least information about your OS and FlorisBoard version are rudimentary.

The crash template includes nothing about OS or Florisboars versions, or anything of the sort.

Android 12 
0.3.15-rc02 (79)

**Comment by tsiflimagas** [comment]
> The crash template includes nothing about OS or Florisboard versions, or anything of the sort

Right, I forgot that. Those information are included in the report produced by FlorisBoard. Maybe you copied that text from logcat or something. Thanks for adding the information anyway. The issue could be closed, since it's something that's been fixed, but maybe Patrick wants to check out how is it possible that a FlorisBoard crash can crash the whole system.

**Comment by Glitchy-Tozier** [comment]
> but maybe Patrick wants to check out how is it possible that a FlorisBoard crash can crash the whole system.

That's pretty impressive, actually.

**Comment by patrickgold** [comment]
Yeah this issue is normally fixed, however that this results in an OS reboot is indeed strange. Could you please try out the following:

In "FlorisBoard Settings > Devtools" (enable them if they aren't) click on "Test crash report screen". This will result in a purposely thrown unhandled exception. Normally this should then cause the crash notification to appear. If it results in an OS reboot then that's definitely an issue with your OS.

Other than that I don't really know how this could result in an OS reboot.

**Comment by AnonWombat** [comment]
> Yeah this issue is normally fixed, however that this results in an OS reboot is indeed strange. Could you please try out the following:
> 
> In "FlorisBoard Settings > Devtools" (enable them if they aren't) click on "Test crash report screen". This will result in a purposely thrown unhandled exception. Normally this should then cause the crash notification to appear. If it results in an OS reboot then that's definitely an issue with your OS.
> 
> Other than that I don't really know how this could result in an OS reboot.

Hi Patrick, thanks for the reply!

I followed those steps and Florisboard correctly sends the crash notification. If it would be more helpful, I can send you the full Android log. If so, is there some way that I can send it to you privately? 

Thanks.

**Comment by patrickgold** [comment]
> I followed those steps and Florisboard correctly sends the crash notification.

Interesting, then this means that in general the crash utility and unhandled exception handler works for you.

> If it would be more helpful, I can send you the full Android log. If so, is there some way that I can send it to you privately?

I do not really think that the full log will help me (because it is a generic crash), but if you want you can send it to florisboard@patrickgold.dev , then I can have a look at it.

**Comment by patrickgold** [comment]
How should we proceed with this issue? The crash in question is fixed in the latest stable/beta and the log AnonWombat kindly sent me didn't help me in identifying if and why FlorisBoard would bring the whole system down.
