### ISSUE TITLE
Glide Typing a word that has an apostrophe doesn’t automatically add a space before it

### ISSUE THREAD

**Issue by Keepkeepzz** [florisboard/florisboard#1828]
#### Short description
 If you type a word and then glide type a word that has an apostrophe in it, a space won't be automatically added between the two words.

#### Steps to reproduce
1. Enable glide typing
2. Type a word like the
3. Glide type a word with an apostrophe like they're
4. Results. There won't be a space between the two words.

#### Environment information
- FlorisBoard Version: 0.3.16beta-01
- Install Source: GitHub
- Device: Nokia 7.1
- Android: 10, Stock

**Comment by patrickgold** [comment]
Above commit/PR fixes this issue, gliding a word like "should've", "they're", etc. will now insert a space again. Thanks for reporting, will be parts of the next beta 0.3.16-beta03!
