### ISSUE TITLE
lobster emoji in the animal section

### ISSUE THREAD

**Issue by theotheroracle** [florisboard/florisboard#1837]
hello, as lobster is one of my favohrite animals i was sad to see it in the food section and hope it could be moved to the nature section with the other animals

**Comment by patrickgold** [comment]
> hello, as lobster is one of my favohrite animals i was sad to see it in the food section and hope it could be moved to the nature section with the other animals

Well I didn't put it in the food section, the Unicode consortium did it :) I just take the emoji data of the Unicode CLDR standard (v40) and import it into FlorisBoard. Here's the spec of the lobster, and you can see it is assigned to "sea food":

![image](https://user-images.githubusercontent.com/19412843/167466540-a3751fa1-1746-4f9a-836f-5c555d06afb1.png)

Tbh I do not want to start moving emojis around manually, as this complicates stuff unnecessarily in the long run. The best workaround for you is to use it once, then you always have it in the recents section for quicker selection, also it is not directly associated as food while in recents :)

I will thus reject your proposal, hope you can understand.
