### ISSUE TITLE
Capitilized i in Turkish outputs "I"

### ISSUE THREAD

**Issue by Atlas-19** [florisboard/florisboard#1840]
#### Short description
Whenever I press shift and press i the keyboard outputs "I" instead of "İ".

A video demonstration:
https://user-images.githubusercontent.com/71735202/167711788-b5504a94-ea5f-4fb8-b56e-2f8bf29df0f3.mp4

#### Steps to reproduce
1. Go to "Languages & Layouts"
2. Create a Turkish keyboard subtype
3. Press shift and type "i" using the aforementioned subtype

#### Environment information
- FlorisBoard Version: 0.3.15 (80)
- Install Source: F-Droid
- Device: Lenovo TB-X606F & Samsung SM-J730F
- Android: Android 10 & Android 9

**Comment by demirdegerli** [comment]
Fixed this 🇹🇷 
#1966

**Comment by patrickgold** [comment]
@demirdegerli Please see #1966 why I think your PR does not address the issue, while my PR (#1967) does address the issue.

Both of you: could you try out #1967's debug artifact (installs separately and does not alter your main/beta installation) and test out the behavior of the I in QWERTY for both a Turkish and English subtype? The Turkish subtype should cause the capital I to have a dot, while the English one shouldn't have one. Thanks in advance!

**Comment by demirdegerli** [comment]
Ok, this commit (#1967) dynamically solves the issue for all languages. Exactly corrects me, thanks!
