### ISSUE TITLE
Shift + Space-swipe doesn't select text

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1843]
#### Steps to reproduce
1. Write text
2. Try to select it using shift + space-swipe

#### Environment information
- FlorisBoard Version: 0.3.16-beta01 (81)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! I am aware of this issue, this bug was introduced in 0.3.16-beta01 and I will fix this before 0.3.16 stable.

**Comment by patrickgold** [comment]
Above PR fixes the issue, shift+space should now be properly working again with the next beta release 0.3.16-beta04. I included the space swipe into the mass selection mechanism, which allows for fast updates without knowing the exact content. Once your finger lifts off the space bar, the content re-generates properly and the keyboard has proper context again.

Thanks again for reporting!

**Comment by Glitchy-Tozier** [comment]
Great to hear, looking forward to the update! :)
