### ISSUE TITLE
Keys highlight on gestures

### ISSUE THREAD

**Issue by DaniAndTheWeb** [florisboard/florisboard#1846]
I just noticed that when performing a gesture like the one of deleting precisely or moving the cursor swiping on the spacebar the key initially pressed stops being visually highlighted. I think that highlighting the key until the gesture is completed could give the keyboard a more refined and consistent look.

**Comment by patrickgold** [comment]
Thanks for your proposal!

This was a rather quick fix, the initial key for moving gestures now stays active visually until you release your finger. Is parts of above linked PR, which will be released with 0.3.16-beta03!
