### ISSUE TITLE
Korean support in Crowdin

### ISSUE THREAD

**Issue by HexagonWin** [florisboard/florisboard#185]
Hello!
I am a Korean user who likes this keyboard.
I wanted to translate, so I went to crowdin, but I cant find a section to add language.
I am a complete newbie to crowdin, so I don't know the basics. Sorry..
Is there any way I can do?
Thanks

**Comment by patrickgold** [comment]
First off thanks for considering to translate FlorisBoard into Korean, I really appreciate it!

No, there's no way for a contributor to add a new language in Crowdin other than writing the maintainer (me) a mail or opening an issue, so you did the right thing :)

I've just added Korean to list of languages, so you can start translating.

I will close this issue now but if you have any question, just ask it in this issue!
