### ISSUE TITLE
Dvorak-ES layout request

### ISSUE THREAD

**Issue by SrEstegosaurio** [florisboard/florisboard#1853]
Hello, 
If possible it would be very nice to add a **Dvorak-es** layout to florisboard.

Something similar to this one:
![Screenshot_20220515-100440~2.png](https://user-images.githubusercontent.com/49443421/168463418-097db75f-0ea7-4b03-bedc-3f25d101bf34.png)

Thanks for such a nice app!

**Comment by SrEstegosaurio** [comment]
I forgot to add the `kbd-layout` flag and I can't figure out how to do it from my phone. Sorry about that.

**Comment by tsiflimagas** [comment]
Don't worry about it, those further tags can only be put by users with certain permissions to the repo.

**Comment by tsiflimagas** [comment]
Which keyboard has this layout? Every keyboard I tried has a slightly different Dvorak-es layout.

**Comment by tsiflimagas** [comment]
Uh, sorry, I just saw there's a Dvorak (ÑÇ) layout.

**Comment by tsiflimagas** [comment]
I added this layout in #1884. You can try the debug build if you want to see if the layout is correct.
