### ISSUE TITLE
"Delete characters precisely" highlights characters incorrectly in Ace-based(?) text editors

### ISSUE THREAD

**Issue by unilock** [florisboard/florisboard#1854]
#### Short description
Using the "Delete characters precisely" gesture in apps that are based off of [Ace](https://ace.c9.io/), such as [Acode](https://github.com/deadlyjack/Acode) or [Code Editor](https://play.google.com/store/apps/details?id=com.rhmsoft.code), results in strange behavior concerning character highlighting. Example (Acode):

https://user-images.githubusercontent.com/11802133/168632970-43d984be-108b-4fd3-8159-b97ea6a786ae.mp4

However, using it in other text editors, such as [Editor](https://github.com/billthefarmer/editor) or [Simple Text Editor](https://github.com/maxistar/TextPad), works fine.

https://user-images.githubusercontent.com/11802133/168633652-5697255f-82db-45ee-aaec-c536cb4aec70.mp4

(Note that I'm not really sure whether this issue is actually because of Ace; that's just the only thing Acode and Code Editor have in common, as far as I know.)

#### Steps to reproduce
1. Open an Ace-based text editor, e.g. Acode
2. Type in some text
3. Use the "Delete characters precisely" feature
4. Characters are not highlighted correctly, but are deleted correctly

#### Environment information
- FlorisBoard Version: 0.3.16-beta02
- Install Source: F-Droid
- Device: Google Pixel 4a
- Android: 13 beta 2 (TPBB.220414.015)

**Comment by patrickgold** [comment]
Can you confirm that this strange behavior only occurs with FlorisBoard and not with other keyboards too?

**Comment by unilock** [comment]
@patrickgold Indeed, it doesn't work with Gboard, either. Must be a quirk of Ace, then. What a shame; I can't find any text editors that provide a similar feature set that *don't* use Ace...

**Comment by patrickgold** [comment]
> Indeed, it doesn't work with Gboard, either. Must be a quirk of Ace, then. What a shame; I can't find any text editors that provide a similar feature set that don't use Ace...

Ah that probably means that the app is at fault then. I can only do so much before I need at least some reliable data and behavior of the target app.

> [QuickEdit](https://rhmsoft.com/?p=283) seems to fit the bill nicely

Yes I used that editor for a time and it was always reliable if I needed it. (Although I never did more than viewing basic txt files).
