### ISSUE TITLE
Emojis missing half if increased

### ISSUE THREAD

**Issue by 1011io** [florisboard/florisboard#1856]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Increase emojis size in theme editor
2. Activate Auto rotate
3. Rotate the device

![Screenshot_20220516-194751_Bromite](https://user-images.githubusercontent.com/105464717/168661949-b4c0a1f0-eed4-4204-985e-85d8cbdabd29.png)

#### Environment information
- FlorisBoard Version: 0.3.16-beta02
- Install Source: Google Playstore
- Device: Samsung Galaxy J6+
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! Above commit/PR fixes the issue, if an emoji fits into the grid on portrait then it will do so too in landscape. Will be released in 0.3.16-beta03.

**Comment by 1011io** [comment]
there's an issue on the smartbar primary actions on which icons appear to be small when phone is rotated too. 
![Screenshot_20220517-111840_Bromite](https://user-images.githubusercontent.com/105464717/168789532-e4ae174a-8a0c-4c59-91b1-17c91ecae159.png)
