### ISSUE TITLE
Update to 0.3.15 configuration reset

### ISSUE THREAD

**Issue by Ace0fspadev** [florisboard/florisboard#1868]
#### Short description
Today i did a update from F-Droid to 0.3.15 (i don't know the version i had before) and after the Update i had an English layout instead of my German one and the config was reset.
Then i needed to create a thing called a Subtype to have my German input again and now i have Ä, Ü, Ö and ß direct in the Keyboard. Before i had to hold the letter A for a bit to write an Ä.
I want this behaviour back, i do not want to have these letters in my Keyboard.

#### Subtype Config
- Deutsch
- de
- German (QUERTZ)
- Western
- Western
- Appender
- Euro
- Western Arabic
- Western Arabic
- Western Arabic
- Simple telpad input
- Simple telpad input (advanced controls)

#### Steps to reproduce
1. Use FlorisBoard on a lower Version
2. Update

#### Environment information
- FlorisBoard Version: 0.3.15
- Install Source: FDroid
- Device: Redmi Note 10
- Android: 11

**Comment by patrickgold** [comment]
Instead of using the "German" layout, just use the "QWERTZ" layout, then the letter Ä is only accessible through long-press A
