### ISSUE TITLE
Use form issue template

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1869]
- [Example](https://github.com/ventoy/Ventoy/issues/new?assignees=octocat&labels=&template=issue_template.yml&title=%5Bissue%5D%3A+)
- [Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

1. This may help with making people to actually fill out their **Environment information**.
2. Additionally, it might make reporting issues (especially on phones) easier, since it doesn't lead to tons of comments inside your issue-report.

That being said, if this is implemented, we should wait until it is available in the GitHub-app. Currently, issue-templates containing a form may only be edited in the browser.

**Comment by patrickgold** [comment]
Yep I've seen those issue forms before and I think they would be really useful. But as you also said, I want to wait until they are stable and available in the official GitHub app too.

**Comment by lm41** [comment]
#2366
