### ISSUE TITLE
Native file issue

### ISSUE THREAD

**Issue by shahzzz68** [florisboard/florisboard#1877]
Build command failed.
Error while executing process C:\Users\dell\AppData\Local\Android\Sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C D:\Android Studio projects\florisboard-0.3.13\florisboard\app\.cxx\Debug\6l6w2z3b\arm64-v8a florisboard-native}
ninja: Entering directory `D:\Android Studio projects\florisboard-0.3.13\florisboard\app\.cxx\Debug\6l6w2z3b\arm64-v8a'

ninja: error: 'D:/Android Studio projects/florisboard-0.3.13/florisboard/app/src/main/icu4c/prebuilt/jniLibs/arm64-v8a/libicuuc.a', needed by 'D:/Android Studio projects/florisboard-0.3.13/florisboard/app/build/intermediates/cxx/Debug/6l6w2z3b/obj/arm64-v8a/libflorisboard-native.so', missing and no known rule to make it

**Comment by tsiflimagas** [comment]
Did you initialize submodules after cloning the repo? It's done with this command `git submodule update --init --recursive`.

**Comment by tsiflimagas** [comment]
I'll consider this as answered.

**Comment by 26feb97shubham** [comment]
Can you please tell me the solution in more detail. As I am also facing this issue
