### ISSUE TITLE
[feature request] please add ability to paste images from clipboard

### ISSUE THREAD

**Issue by gmankab** [florisboard/florisboard#1881]

**Comment by tsiflimagas** [comment]
That's possible already, you just have to do it in a supported app, e.g. it's rational that you can't paste an image to a search bar.

**Comment by gmankab** [comment]
I'm sorry, it turns out that if you copy the picture, it really appears in the clipboard. But unfortunately the screenshots do not appears in the florisboard clipboard, but appears in gboard clipboard

**Comment by tsiflimagas** [comment]
That's a different feature though. Screenshots doesn't have to be copied to clipboard if such a feature hasn't been implemented in the keyboard. There's already an open issue for that.
