### ISSUE TITLE
Vibration continues when navigating through words with the spacebar and continuing swiping after the end/beginning of the textbox is reached

### ISSUE THREAD

**Issue by Nablesss** [florisboard/florisboard#1886]

**Comment by tsiflimagas** [comment]
Please follow the issue template properly instead of removing it, and describe the problem in the issue body instead of the title, else I'll have to close it.

**Comment by patrickgold** [comment]
> Vibration continues when navigating through words with the spacebar and continuing swiping after the end/beginning of the textbox is reached

Yes I am aware and there is no **reliable** way to fix this issue, as some editors report inconsistent content, selection, boundaries, etc. This means that I can thus not determine if you are really at the start/end, and thus also not stop with the vibration. Will close this issue as a `wontfix`, hope you can understand.

Also for the next bug report please don't delete the bug report template, it makes the work for everyone involved just harder.
