### ISSUE TITLE
Inline autofill isn't working properly with KeePassDX

### ISSUE THREAD

**Issue by E0697** [florisboard/florisboard#1898]
#### Short description
Inline autofill isn't working for KeePassDX
#### Steps to reproduce
1. Go to a website/app with login window and focus on the password field
2. Click on "Select entry"/"Sign in with KeepassDX"
3. After selecting the entry, a popup message says "Autofill suggestion added" but nothing is added.

#### Environment information
- FlorisBoard Version: 0.3.16-beta04
- Install Source: F-Droid
- Device: Realme 7 Pro
- Android: Android 11

**Comment by Glitchy-Tozier** [comment]
I'm not sure this is a florisboard issue 🤔
Does this behaviour get corrected when using other keyboards?

**Comment by E0697** [comment]
Works well with Gboard.
I'll see if I can test other keyboards too.

**Comment by E0697** [comment]
I tested AnySoft too, after selecting the item, it added a second "select item" to the suggestion bar.
I tested SafeInCloud and it works well with FlorisBoard.
I'll try to troubleshoot this with KeePassDX's dev.

**Comment by patrickgold** [comment]
Thanks for your bug report!

This could theoretically be a FlorisBoard issue because the whole inline suggestions UI/API for passwords is not that well documented and also a bit weird and thus I may have missed something, but may also be a bug in KeePassDX.

> I'll try to troubleshoot this with KeePassDX's dev.

Perfect thanks a lot! Like I said it could be an issue on both ends, if the dev of KeePassDX has any results on the investigation this could help eliminating the bug.

**Comment by E0697** [comment]
Thank you too.
I opened a dicussion in KPDX's repo.
One user reported that it's working well.
So yes it needs more investigation. Could be OS related. I'm using RealmeUI 2.0 if that has any bearing on the issue.

**Comment by E0697** [comment]
Bitwarden works properly too.
Should I keep this issue open?

**Comment by patrickgold** [comment]
Yes for now lets keep it open, we can close it later if needed.

**Comment by KiaraGrouwstra** [comment]
for me they're not playing well either.

- Florisboard 0.3.16
- KeepassDX 3.5.0 Beta01
- device Pixel 5
- GrapheneOS (Android 13)

**Comment by glemco** [comment]
This could be the issue https://github.com/Kunzisoft/KeePassDX/issues/1166#issuecomment-2096685913

**Comment by patrickgold** [comment]
Can you please test the debug artifact of linked PR to check if KeePassDX works with the new implementation? On my side KeePassDX behaved as expected (using latest F-Droid version), however my device alone isn't a stable measure.

**Comment by E0697** [comment]
I just tested it. The entries are indeed displayed properly now, much appreciated!
