### ISSUE TITLE
Add custom keyboard sounds

### ISSUE THREAD

**Issue by sdkmap** [florisboard/florisboard#1899]
As the title says please add a feature to set   custom keyboard key press sounds, andriod 12 sounds just sucks

**Comment by lawson85** [comment]
Less! We could make pianos or fart sounds!

**Comment by rancidfrog** [comment]
Many people enjoy silent keysounds, as vibration is enough and already makes some sound.

Will sounds affect apk size?

**Comment by patrickgold** [comment]
Thanks for your proposal!

This has already been proposed in #1360, will close this issue to avoid duplicate discussions. In general though I am open to add custom sounds, or at least the option for the user to load in their own sound files.

> Many people enjoy silent keysounds, as vibration is enough and already makes some sound. Will sounds affect apk size?

Only if I include custom sounds but even then keypress sounds are so short you will hardly see any change in the APK size. There are other not yet implemented areas where the APK size may be problematic to keep small, and keypress sounds is definitely not one of these areas.
