### ISSUE TITLE
Please fix suggestions problem,i need word suggestions for typing.I know you are fixing other bugs ,but i think this feature is very important.I like your app so much ,but i can't use it becoz of that problem,waiting for updated that we all eagerly waiting for months.

### ISSUE THREAD

**Issue by Finalboss77** [florisboard/florisboard#1900]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by tsiflimagas** [comment]
As explained many times by now, this feature is the next to be implemented, and no ETA is given. And since you know this already, I really don't see what's the point of this issue.
