### ISSUE TITLE
The custom automatically delete itself after switching off the device.

### ISSUE THREAD

**Issue by starboyrs** [florisboard/florisboard#1903]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by Glitchy-Tozier** [comment]
1. Courrently the title is very difficult to understand. Could you try rewording it?
1. Please properly fill in the template. Add description, steps to reproduce, and environment information.

**Comment by patrickgold** [comment]
If I had to take an educated guess this is a duplicate of #1726. Should @starboyrs not clarify and properly fill out the template within a reasonable time we can close it as a duplicate of that issue IMO.

**Comment by patrickgold** [comment]
Closing as a possible duplicate of above mentioned issue.
