### ISSUE TITLE
How to help developping autocomplete? 

### ISSUE THREAD

**Issue by tschmoderer** [florisboard/florisboard#191]
I would like to help developping this wonderful and add the only missing function (that is dictionary aitocomplete) 
I am a good dev myself (even if i do not know about kotlin yet) 

I have some time to help if possible. 

Ty

**Comment by patrickgold** [comment]
Thanks for considering to help me with implementing dictionary autocomplete, I really appreciate this!

The biggest issue I had (and have) is finding an open-source dictionary source which has at least a word frequency measure and respects capitalization of words while also having a compatible license. I know what dictionaries other FOSS keyboards use, but I am unsure about the usage rights and how to properly add them to FlorisBoard.

The most promising thing I have found yet is this Python library: https://github.com/LuminosoInsight/wordfreq
I've looked at the code and dictionary data and I think shouldn't be a problem to process it in Kotlin and use it for suggestions, but I am not 100% sure if I will use this in FlorisBoard or something else.

I am currently unsure how exactly you can help me in developing this feature, as I have not started it yet, but I think the most help would be in figuring out how to use this library in Kotlin and experimenting with it. The Python library has the schema `word`  + `language code` => `frequency`, while for suggestions we need something like `current word input` + `language code` => `n words that begin with the input and have the highest frequency`, where n is the number of requested words to be suggested in the Smartbar. Of course this is a very basic understanding of this rather big issue (I have never coded anything in suggestion algorithms / logic yet), so maybe you have a better idea how to tackle this.

Looking forward to work together with you. If you have a better suggestion for the dictionary, feel free to suggest it to me, I am very open to suggestions here!

**Comment by kj7rrv** [comment]
Also, will there be way for it to use context to improve predictions?

**Comment by patrickgold** [comment]
@kj7rrv The current input text is cached in the EditorInstance, so this can be used for the context.

**Comment by HolySoap** [comment]
@patrickgold for the prediction algorithm you should look at the Levenshtein distance and for auto correction at the N-Gram model for prediction.


Levenshtein distance: https://www.wikiwand.com/en/Levenshtein_distance

N-gram: https://www.wikiwand.com/en/N-gram

**Comment by patrickgold** [comment]
@HolySoap Thanks for your comment, I will look at this when implementing text prediction!

**Comment by Glitchy-Tozier** [comment]
That would be SUPER IMPORTANT!

It's a major tripping point of current open-source keyboards, which basically don't learn at all from your previous sentences.

> Also, will there be way for it to use context to improve predictions?
