### ISSUE TITLE
Auto-capitalisation broken on 0.3.16

### ISSUE THREAD

**Issue by penn5** [florisboard/florisboard#1915]
#### Short description
When opening a new text field, shift is not automatically enabled. Typing a character then deleting it fixes this.

#### Steps to reproduce
1. Click a text field
2. See that shift is not enabled even if the setting is on

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: F-droid
- Device: Mi 9
- Android: MIUI 12

**Comment by tsiflimagas** [comment]
Here it's working fine. Did you try multiple different text fields/apps?

**Comment by penn5** [comment]
Yes, it's the same in GitHub, Signal and Firefox

**Comment by tsiflimagas** [comment]
Did you try the same text fields with other keyboards? It would be interesting to see if those behave differently or not. I usually test against Gboard.
Btw, I tried in Nova Launcher and GitHub (i would have to first make an account in Signal to use it i guess), and found out that Nova Launcher search bar doesn't activate auto capitalization with other keyboards too. Also, in GitHub, what text fields did you try? When writing replies in issues, discussions etc, it should normally activate auto capitalization, and it does for me. But, in the search field, for example, it doesn't for any keyboard, and I guess that's intended. So, I suggest to try with other keyboards too. Perhaps you tried text fields which aren't supposed to get auto capitalization, or there's something outside FlorisBoard causing this behaviour.

**Comment by penn5** [comment]
It works in Gboard and the last version of Floris; it is a regression that worked before. Since it works for you, there must be _something_ outside of FlorisBoard causing the issue, but I couldn't say what. All I did is update the app via F-droid.

**Comment by penn5** [comment]
Could it be [this](https://github.com/florisboard/florisboard/blob/3d6cacc753e54e952f8741c4546dce898a2cb657/app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt#L115)? It doesn't appear to respect the setting to automatically enable shift, and it should instead call [reevaluateInputShiftState](https://github.com/florisboard/florisboard/blob/3d6cacc753e54e952f8741c4546dce898a2cb657/app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt#L237)

**Comment by penn5** [comment]
Indeed, enabling the setting to remember caps lock state fixed the issue. I don't understand what this toggle is for, as it does not appear to remember the caps lock state when changing between text fields. Perhaps it is supposed to work when changing between fields in a form? In any case, this is surely a regression.

**Comment by patrickgold** [comment]
I think this could be a concurrency issue. [This (snippet A)](https://github.com/florisboard/florisboard/blob/3d6cacc753e54e952f8741c4546dce898a2cb657/app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt#L115) linked code piece does reset the shift on start, but it is then reevaluated [here (snippet B)](https://github.com/florisboard/florisboard/blob/3d6cacc753e54e952f8741c4546dce898a2cb657/app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/AbstractEditorInstance.kt#L126). Expected execution order is A->B, but if it gets out of order with B->A it means it correctly sets the auto shift but then resets it, which is not good. Will investigate into this.

The workaround with remember caps lock=true is a fix, however it is not intended to be used this way.

**Comment by patrickgold** [comment]
Above commit is a somewhat fix for this issue, at least on my testing in affected apps I could resolve issues for a lot of them (although this issue is very weird and depends entirely on the app's behavior).

If possible, could you try out the debug build of linked PR (Click on checks > artifacts > app-debug.apk) and test out if the fix helps on your device? (Make sure that "remember caps lock" is turned off in the debug app, else this test has no purpose).

**Comment by penn5** [comment]
It seems to be fixed, thanks!

**Comment by patrickgold** [comment]
Perfect, thanks for confirming!
