### ISSUE TITLE
"select characters precisely" isn't as precise as "delete characters precisely"

### ISSUE THREAD

**Issue by KaKi87** [florisboard/florisboard#1917]
Hello,

#### Short description

The "delete characters precisely" option of the "delete key swipe left" gesture selects characters individually.

Meanwhile, the "select characters precisely" option of the same gesture :
- selects the characters individually when there only are two characters ;
- selects the first character individually then the next characters two by two when there are three characters or more.

#### Steps to reproduce
1. Enable the "delete characters precisely" option (if not already enabled)
2. Type characters
3. Swipe-left the delete key
4. See how precise the deletion is
5. Enable the "select characters precisely" option
6. Type characters
7. Swipe-left the delete key
8. See how less precise the selection is

#### Environment information
- FlorisBoard Version: 0.3.15 (80)
- Install Source: F-Droid
- Device: Xiaomi Mi 8 (dipper)
- Android: 11, DotOS 5.2.1

---
Thanks

**Comment by patrickgold** [comment]
Thanks for your bug report!

Using the latest release, 0.4.0-alpha01, I cannot reproduce this behavior, both select and delete precisely work with the same precision. Could you please recheck this on your end using the latest alpha release? Thanks in advance!

**Comment by KaKi87** [comment]
Actually, it was already fixed in `0.3.16`, but I did upgrade to `0.4.0-alpha01` anyway because of #1911. Thanks !

---
PS:

> Beginning with v0.4.0 FlorisBoard will follow [SemVer](https://semver.org/#summary) versioning scheme.

Article 9 of said specification says the proper version tag is `0.4.0-alpha.1`.

**Comment by patrickgold** [comment]
> Article 9 of said specification says the proper version tag is 0.4.0-alpha.1

While this is true the version formatting of pre-builds of FlorisBoard follows Google's convention for Android library releases, and tbh I kinda hate the look of `alpha.1`. Besides that I do intend though to conform to SemVer, especially when it comes to the major, minor and patch numbers and how to use them properly instead of whatever happened with the 0.3.x series...

**Comment by patrickgold** [comment]
But thanks for confirming and closing the issue! :)

**Comment by KaKi87** [comment]
> tbh I kinda hate the look of `alpha.1`

With all due respect, personal opinions shouldn't matter here, as the point of having standards is that everything that follow these is guaranteed to work together.

Also, here's an objective reason why the separator matters : chunk boundaries.
When SemVer is followed, every piece of the string is separated by `.`, `-` or `+`, making these easy to parse.

For example, the pre-release kind (`alpha`) and number (`1`) are easier to distinguish when separated (`alpha.1`) than when grouped as a single keyword (`alpha1`).

Those strings may be read by humans, but they must be readable by machines above all.
Nothing prevents you from automatically stripping out the separator in the *About* section of the app, for example.

Thanks

**Comment by daakru** [comment]
as a developer I actually think personal opinion matters a lot, but that's just a personal opinion
