### ISSUE TITLE
Improve descriptions of vibraton-options

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1919]
I just observed soneone setting up the app, and the person found it pretty confusing to read the apparent contradictions in the vibration-settings. One of them states that Android will be depended on, while the other states that Android will be bypassed.

Both are active.

![Screenshot_20220626-135010_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/175813530-263c7d9f-cc16-4c7b-b340-683f251ad17d.jpg)

**Comment by patrickgold** [comment]
Well that's partly a localization issue, but also a general design issue. What do you suggest to improve this in the UI? I want to give the user the ability to fully control vibration, so either force-off, force-on or depend-on-system. Btw the second toggle is the force override on toggle, but I agree the description does not really give that away.

**Comment by patrickgold** [comment]
I just remembered that my preference library has the switch/list compo, which are internally 2 preferences squashed together into one in the UI. Basically I could do this, where the 2 list items are only select-able if the switch is on (see the Keyboard > Hinted number row pref for an example what I mean):

```
Enable vibration  <switch>
  - Follow system
  - Always on
```

**Comment by patrickgold** [comment]
Apart from that I just discovered that the underlined third pref is not actually the force override, but has something to do with the technical fact on how to trigger the vibration. I can either talk directly to the vibrator or use the haptic feedback interface. Both are equally limited and unreliable, but I give the user a choice here. The actual force-on toggle would be the second option, which would be squished into the switch/list pref I proposed.

**Comment by Glitchy-Tozier** [comment]
> I just remembered that my preference library has the switch/list compo, which are internally 2 preferences squashed together into one in the UI. Basically I could do this, where the 2 list items are only select-able if the switch is on (see the Keyboard > Hinted number row pref for an example what I mean):

Sounds pretty well suited for this scenario!
In fact, I think many settings might be able to make good use of this feature. It may be a good idea to go through all of them and search for optimizations. (I may be able to do this on the weekend)
Two examples:
![Screenshot_20220628-080139_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/176105536-500ad9bf-b81f-4cd5-94ee-f615d3904f64.jpg)
![Screenshot_20220628-080150_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/176105542-928e4292-3be2-4544-bffe-1081cf4b4035.jpg)

> I can either talk directly to the vibrator or use the haptic feedback interface.

Do we have access to a distinct either-or-option instead of an on-off-option?

**Comment by patrickgold** [comment]
> Why are these switches not aligned with the others?

Lol I never noticed it, now I can't unsee it anymore... That's definitely not intended and a margin/padding issue, oops. Will fix that the next time I do fixes in my prefs library.

> This first option seems like it should disable the following ones.

No, because the latter two prefs are for the extended popup panel, which cannot be turned off and always appears, even if you disable the base popups with the first key. Although I agree the wording might be confusing. And I think I need to generally sweep over the German translation to fix some inconsistencies and reduce length.

> General: It seems like sometimes you hide options that aren't needed sometimes you disable them

That's true, and it has partially to do with discoverability. If I want preferences to be easily discovered they get greyed out. But some options don't contribute to that and then I hide them when not needed.

**Comment by Glitchy-Tozier** [comment]
> No, because the latter two prefs are for the extended popup panel, which cannot be turned off and always appears, even if you disable the base popups with the first key.

I see

> And I think I need to generally sweep over the German translation to fix some inconsistencies and reduce length.

You're probably right, that's a good idea.

> That's true, and it has partially to do with discoverability. If I want preferences to be easily discovered they get greyed out. But some options don't contribute to that and then I hide them when not needed.

I can't imagine the use of being able to find a disabled option when the whole functionality is turned off. Could you give me an example of where this would be useful? 🤔

**Comment by patrickgold** [comment]
As for the switch misalignment, I fixed the issue in the JetPref library (culprit was the minimum touch target size not being respected in the switch). Thus in a few days this fix will also be released in 0.4.0-alpha2.

**Comment by Glitchy-Tozier** [comment]
Good job :)

**Comment by patrickgold** [comment]
Above linked PR finally addresses the _Sounds & Vibration_ screen again and with this I thought I try to fix this issue as well.

I played around a bit with the switch/list pref combo (to eliminate the ignore system pref setting) and this is what it looks like:

https://user-images.githubusercontent.com/19412843/183052644-12febb54-ac11-45ed-8981-44cc5c2c3d4e.mp4

However I must say I am not really happy with the outcome, and for me the merge of the enable toggle and ignore system settings toggle is more confusing than the current state is. What's your opinion on this?

**Comment by TheHawaiianKoala** [comment]
If you keep it this way, kindly add a vertical line so that a user knows the switch and tab are two different clickable targets.

![Screenshot](https://user-images.githubusercontent.com/97790626/183116638-0a2d854d-11a3-4158-a46c-bb49e478d4f8.png)

**Comment by patrickgold** [comment]
> If you keep it this way, kindly add a vertical line so that a user knows the switch and tab are two different clickable targets.

That's actually a good idea, never thought about this yet from a UX perspective. Will adjust this in my preference library in the future. I am already using the switch/list combo in FlorisBoard (e.g. keyboard options for hinted rows), so even if above draft does not make it it will still benefit the other use cases for this widget.

**Comment by TheHawaiianKoala** [comment]
Regarding the UX of combo switches, imo you should use the design that would fit more options (i.e. This new design draft fits in Hinted Rows and Audio/Vibration settings). 

If the previous design fits more options use that. In this way, the same UX would be through out the app so users would not be confused.

**Comment by Glitchy-Tozier** [comment]
> However I must say I am not really happy with the outcome, and for me the merge of the enable toggle and ignore system settings toggle is more confusing than the current state is. What's your opinion on this?

I prefer it over the old version. It's immediately obvious that both those options target the same setting and that they're mutually exclusive.

> If you keep it this way, kindly add a vertical line so that a user knows the switch and tab are two different clickable targets.

That's a great idea! The two-clickable-targets-thing was bothering me too, but I wasn't sure about what solution to propose.

**Comment by patrickgold** [comment]
> I prefer it over the old version. It's immediately obvious that both those options target the same setting and that they're mutually exclusive.

Ok, but I am still at least unhappy with the wording and readability of the enable toggle summary. Currently they are:

- Never play sounds for input events
- Play sounds for input events, respecting system settings
- Play sounds for input events, ignoring system settings

I now thought of better strings, where the first word immediately indicates what option it is:

- Never play sounds for input events, regardless of system settings
- Dynamically play sounds for input events, depending on system settings
- Always play sounds for input events, regardless of system settings

Would look like this in the UI:

https://user-images.githubusercontent.com/19412843/183240595-eaa363e4-d8d2-4223-a576-8756244181b3.mp4

Thoughts on this?

**Comment by patrickgold** [comment]
Additionally I now transformed the "Use vibrator directly" switch into a list pref and gave each option a detailed description, as the option labels alone may not be useful for normal users:

https://user-images.githubusercontent.com/19412843/183242351-c17385da-9c82-4d8a-bb74-e32a3818d6ba.mp4

**Comment by TheHawaiianKoala** [comment]
This is much better than the previous option, clearly explains the option and what it does

**Comment by patrickgold** [comment]
Minor change to above screen recording:

Previously I used the sentence `{app_name} directly queries and interacts with the default hardware vibrator.`, but that's not really English (especially the term "queries with"), so now I just use `{app_name} directly interacts with the default hardware vibrator.`. Is also a bit shorter and quicker to read IMO.

**Comment by patrickgold** [comment]
Merged into master, will be parts of the 0.4.0-alpha02 release. Thanks again for everyone's feedback on this!
