### ISSUE TITLE
Separate font size for emoji

### ISSUE THREAD

**Issue by szofiasaint** [florisboard/florisboard#1927]
Hi! First off, amazing work so far, this keyboard has everything I could want and more - no more SwiftKey for me :) I even made a github account just to make this feature request as the dev team seems quite active and receptive to suggestions!

One thing I'd like to suggest, is to add the ability to adjust the font size of the emoji panel selarately from the keyboard. It's a small QoL thing, but I prefer to keep my keyboard compact and a smaller font makes it look sleeker in a smaller size, but it turns the emoji panel into a vision test, and I have to pull my phone up to my face and squint like an old lady lmao.

**Comment by patrickgold** [comment]
Hi! Great to hear you like this keyboard :)

As for your feature proposal - This is actually already possible to do if you create a custom theme! If you don't have a custom theme, go to Settings > Themes > Manage > Create theme extension > Orange Plus > _Select the base theme you prefer_ > Create (I know a bit confusing, this is scheduled to be simplified in the future).

In your custom theme extension, click Edit, scroll until you find the "Emoji key" group (its way down in the list), there click Font size and change the _sp_ value to something bigger. At any time you can click into the "Try out your setup" field and preview live how your stylesheet looks. When finished styling, go back one step and click Save.

For the first time after theme creation you must then select your custom theme as the preferred one in the day/night selection page. After that its done, you have successfully changed only the emoji font size. Btw, you can change the look of a lot of specific UI parts with custom stylesheets - and with the live preview feature I built in once you get used to the outer extension edit/save procedure it is relatively easy to completely customize the look, even have custom styling on a per-key basis.

As earlier said the custom theme creation and theme extension UI in general is really complicated for new users, and there's missing documentation - both are things I will address in the future.

Hope that this helps, else let me know :)

**Comment by patrickgold** [comment]
> Seeing as how the regular font-size is theme-independent, wouldn't it make sense to also add that emoji-size-option into the regular settings?

The option you marked is indeed theme-independent - however it is applied both to the normal keys and the emoji keys + popups of both at once as a multiplier (configured theme size in _sp_ times the multiplier/100). And tbh I prefer having the specific font size option in the theme stylesheet and this one pref for the global font size multiplier to avoid cluttering of the UI. This of course requires that I simplify custom themes a bit.

**Comment by Glitchy-Tozier** [comment]
> And tbh I prefer having the specific font size option in the theme stylesheet and this one pref for the global font size multiplier to avoid cluttering of the UI. This of course requires that I simplify custom themes a bit.

Got it! :)

**Comment by patrickgold** [comment]
@szofiasaint Closing this issue as it is stale. If further assistance is needed in this specific topic feel free to ask here!
