### ISSUE TITLE
Numeric keyboard keys don't popup

### ISSUE THREAD

**Issue by Goscomat** [florisboard/florisboard#1928]
#### Short description
The keys don't pop up when pressed on the numeric keyboard, like they do on the regular keyboard.

#### Steps to reproduce
1. Find an input field that only accepts numeric input (If you go [here](https://www.filamentgroup.com/lab/type-number.html) on mobile, and scroll down, you'll find a few input fields for numbers)
2. Tap on the number input field
3. Tap on any number key
4. Observe that the number key doesn't pop up

#### Environment information
- FlorisBoard Version: 0.3.15 (80)
- Install Source: F-Droid
- Device: Fairphone 4
- Android: /e/OS 1.1-20220628199800

**Comment by patrickgold** [comment]
Thanks for your bug report!

Actually this is not a bug but an intended behavior. Popups on those keys never have anything extended, so they also don't have a base popup so it looks cleaner. This is also the case for the telephone input (telpad) layout.

**Comment by Goscomat** [comment]
Thanks for the reply. After I posted this, I kind of reflected that it might be by design. Then the issue can be closed :)!
