### ISSUE TITLE
Swiping and long pressing on spacebar gestures interfere

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#193]
I've noticed since some time that when swiping on spacebar to move the cursor, it's pretty easy to trigger the keyboard selection window to pop up (trigger the long press action rather than the swipe one), and this happens if you don't swipe fast and long enough. So I tried to observe why is that, and I concluded it's because of the reaction time of the long press gesture. It seems to me that on FlorisBoard, the reaction time of this gesture is approximately half of that on other keyboards like gboard and simple keyboard. I don't know if something on the swiping gesture would have to be also adjusted, but I suspect that only making the long press react a bit slower, would work as desired.

**Comment by patrickgold** [comment]
Thanks for your report! I am aware of this issue, see #88 . I will use your above suggestions when fixing this. Closing this issue as it is a duplicate.
