### ISSUE TITLE
Phantom-space not activated properly after gliding a word

### ISSUE THREAD

**Issue by thane-k** [florisboard/florisboard#1937]
if a word is entered by swiping immediately after another entered the same way, it would be nice if a space were automatically entered between the two

what a beautiful project florisboard is ♥

**Comment by thane-k** [comment]
0.3.16, just installed today.
it's certainly possible to be somewhere, being so new to it on this end; but so far, efforts to find such a function, bear no fruit

**Comment by patrickgold** [comment]
Thanks for your suggestion!

This is actually already implemented for glide typing and always active. After you glide a word, there's a phantom space activated. This means the space is dependent on your next input, if you insert another word then a space should be placed between those, if you insert a symbol (like period) then not. If this does not work, could you please test out today's 0.4.0-alpha1 release and test it out there? A bit has changed in the spacing logic between 0.3.16 and 0.4.0-alpha1, so maybe it has fixed the bug for you.

Also what Android version and device are you on?

**Comment by patrickgold** [comment]
https://github.com/florisboard/florisboard/releases then click the 0.4.0-alpha01 version name, there on the end of the changelog is an APK file attached which you can install. Or if you visit the repo README and scroll down until near the end there is a release block, which will take you to the link as well.

If you want to install this via Google Play only you have to wait until tomorrow (or today depending on your timezone), the release is still under review.

As a third alternative you can also get it via the [IzzyOnDroid](https://apt.izzysoft.de/fdroid/) F-Droid repo, where 0.4.0-alpha01 is already published.

**Comment by patrickgold** [comment]
> also, can a custom theme be ported over to a new build?

Yes, in fact you can (almost) fully copy your config from stable to beta, not just your themes! In stable go to Settings > Advanced > Back up data > Back up, click Backup and choose a place where you will find the archive again. Then in the beta app Settings > Advanced > Restore data, select the ZIP you just exported and then click Restore.

The only thing which does not get ported over is the clipboard history and user dictionaries.

**Comment by patrickgold** [comment]
> a new build

Also if you didn't know: the beta installs completely separately and won't touch your main installation, so you can have two versions of FlorisBoard at the same time!

**Comment by thane-k** [comment]
hopefully not too late to bring this back
would have done so sooner but life has brought some HECTIC times in the past few weeks

the space does work beautifully in beta, for the most part. love it.
but at least on this end, on the android 7.0 phone or the android 11 phone upon which this was first discovered (phone has since been lost and most likely not coming back, so many details on that end cannot be retrieved for detailed coding etc., but guessing the code from the currently available a.7 phone would be sufficient anyway), there is never a space entered after a single letter and before a swiped word; for example, 'a phone' would need a manual space or it would show as 'aphone'.

is there by any chance a way to fix this so far?

**Comment by patrickgold** [comment]
The one letter+phantom space not working bug was fixed in #1968 and will also be parts of the upcoming 0.4.0-aplha02 release!
