### ISSUE TITLE
Removing the Emotes key

### ISSUE THREAD

**Issue by Kalytis** [florisboard/florisboard#194]
I'm really not used to having the Emotes key just next to the spacebar, and I really wish there was a way to disable it and have it filled with the spacebar instead.

Thrilled to see the project continue though !!

**Comment by patrickgold** [comment]
Thanks for your suggestion! This idea has been posted a lot recently and I will add it with v0.3.4. See issue #79 for when it is added to FlorisBoard. Closing this issue as it is a duplicate.
