### ISSUE TITLE
Space is not inserted when glide typing after a 1 letter word.

### ISSUE THREAD

**Issue by Keepkeepzz** [florisboard/florisboard#1940]
#### Short description
If I type a single letter and then glide type a word, a space will not be automatically inserted between the two words. This is regardless of whether auto space after punctuation is enabled or not.

For example pressing **a** then glide typing **tree** results in **atree** rather than **a tree** (how it worked in 0.3.16).

#### Steps to reproduce
1. Make sure glide typing is enabled. 
2. Type a single letter. 
3. Glide type a word.
4. Results, no space is placed inbetween the words.

#### Environment information
- FlorisBoard Version: 0.4.0-alpha01
- Install Source: GitHub
- Device: Nokia 7.1
- Android: 10, Stock

**Comment by patrickgold** [comment]
Thanks a lot for the bug report! As discussed in #1935, this bug has been introduced with 0.4.0-alpha01. Will provide a fix for this before making the next alpha release.

**Comment by patrickgold** [comment]
Above linked commit/PR should fix the issue, will be released in 0.4.0-aplha02 after further testing. If possible, could you please try out the debug artifact of said PR (installs separately) and test this out? Thanks!

**Comment by Keepkeepzz** [comment]
Yea it seems to be working fine now. Typing one letter then glide typing automatically inserts a space. Tried it across multiple apps and didn't notice any issues.
