### ISSUE TITLE
Not showing the true version

### ISSUE THREAD

**Issue by m-koushan** [florisboard/florisboard#1942]
#### Short description
In main menu the version in Welcome message field is wrong.

#### Steps to reproduce
1. Open the app
2. See the welcome message

#### Environment information
- FlorisBoard Version: 0.4.0-alpha01 
- Install Source: Github
- Device: Redmi Note 8 pro 
- Android: 11

**Comment by patrickgold** [comment]
Yup I noticed this too after I published the release, I forgot to update the message there... With the next alpha release I will make sure to write a new message for the alpha track of 0.4.

**Comment by patrickgold** [comment]
Above commit fixes the issue, closing as completed thus. Thanks again for reporting!
