### ISSUE TITLE
Suggestion: Add Clipboard History in Backup/Restore Data category

### ISSUE THREAD

**Issue by 09kkthxbb** [florisboard/florisboard#1944]
![Screenshot_20220708-170228_Pixel Launcher](https://user-images.githubusercontent.com/70685560/177959047-90e02513-0906-4b94-9c17-810ba4bab7c9.png)
Hi. I've been using your keyboard for several months and I have no issues so far. I like its Backup/Restore feature because it doesn't need to reconfigure everything manually when I want to reinstall or use it to my other devices from scratch.

And I think it would be better if you add Clipboard History as well (text-based clipboard) to be a part of backup/restore checkbox in Advanced settings, like for the Pinned and Other categories if possible. By adding that, we don't need to recopy or readd text everything to clipboard and re-pin what I want in particular order.

Thank you very much for this keyboard development!

**Comment by patrickgold** [comment]
Thanks for your suggestion!

As the clipboard data is stored inside a database, it isn't as easy to backup and restore it. There was already a discussion about this here on GitHub (but I can't find it for some reason), but basically what we concluded there is that we can write a converter to a json file upon backup, and on restore reading this json and creating new database entries.

Will add this to the list of Backup&Restore issues, don't know though when exactly I will implement this, as it requires a bit more work to do this properly.
