### ISSUE TITLE
"I" when i type "İ"

### ISSUE THREAD

**Issue by demirdegerli** [florisboard/florisboard#1945]
#### Turkish character bug
In turkish keyboard preset, there is an "İ" letter on keyboard, but when i press on it, it types "I" letter.

#### Steps to reproduce
1. Go to "Languages and Layouts"
2. Click on "Add subtype"
3. Click on "Show all" in "Suggested subtype presets"
4. Select "Turkish"
5. Capitalize the keyboard and press "İ"
6. [Result] The typed letter is "I"

#### Environment information
- FlorisBoard Version: 0.13.16 (86)
- Install Source: F-Droid
- Device: Redmi Note 8
- Android: 11 (MIUI Global 12.5.2 Stable)

**Comment by tsiflimagas** [comment]
Thanks for your report! That's already reported in #1840 though. So, closing as duplicate.
