### ISSUE TITLE
Space bar does not work on Korean

### ISSUE THREAD

**Issue by Me0wzz** [florisboard/florisboard#1947]
#### Short description
Describe the bug in a short but concise way.
Space bar does not work on Korean.
English works fine.

#### Steps to reproduce
1. Use Korean on Florisboard beta 0.4.0-alpha
2. Type "ㄱ" + " " + "ㄴ"
Expected Behavior: ㄱ ㄴ
Actual Behavior ㄱㄴ

#### Environment information
- FlorisBoard Version: 0.4.0-alpha
- Install Source: F-Droid
- Device: Pixel 6
- Android: 12.1 Stock

**Comment by patrickgold** [comment]
Seems to be an issue with the `HangulUnicode` composer. Space bar itself is fine and not effected, but the space gets basically "eaten" by the composer mentioned. Adding to the list of keyboard logic issues.

@Hayleia only if you want and have a bit of spare time, could you have a look into it? (as you implemented this composer and thus may notice the issue much easier)

**Comment by Hayleia** [comment]
Seems like a more general issue. In Vietnamese with Telex too, when typing "e"+" "+"e" you get "ee". So it's probably not a problem in individual composers.
