### ISSUE TITLE
"Enter" not always working

### ISSUE THREAD

**Issue by Archeix7** [florisboard/florisboard#1955]
Some input fields do not respond to "Enter" button for searching

https://user-images.githubusercontent.com/51048550/178795626-6ee8e2a2-f654-40c5-865b-8d6c2643911a.mp4

https://user-images.githubusercontent.com/51048550/178795643-4b8c85d9-2a83-49a8-8b39-ce3586bbdb02.mp4

FlorisBoard Version: 0.3.16 Stable
Install Source: Github
Device: Poco F2 Pro
Android: 11 (Crdroid)

**Comment by patrickgold** [comment]
Thanks for your bug report!

How are other keyboards behaving with those websites/apps? I think this could be a website issue and not a FlorisBoard issue.

**Comment by Archeix7** [comment]
Maybe you right

**Comment by tsiflimagas** [comment]
So, did you try other keyboards?

**Comment by Archeix7** [comment]
> So, did you try other keyboards?

No, but if u can, try please in this resources from my videos.

https://search.ononoki.org/search?q=
Rutracker.org

**Comment by tsiflimagas** [comment]
It doesn't work for other keyboards too, so it's a problem with Searx probably.

**Comment by Archeix7** [comment]
> It doesn't work for other keyboards too, so it's a problem with Searx probably.

Okay than, thx for check
