### ISSUE TITLE
Glide typing behaviour after single-letter words keeps changing

### ISSUE THREAD

**Issue by magnus-ISU** [florisboard/florisboard#1958]
In 0.3.16, tapping a single letter (notably the words 'a' and 'I') worked as I wanted it, which is that gliding another word after tapping the letter would insert a space. So without typing space ever, I can type the phrase "I am a free software user" (Ignoring that auto capitalize is shaky on if it works too).

In alpha 0.4.0, you must explicitely type space, and which was 0.3.14 behaviour too if I recall correctly.

I think this should be a user setting whether you want it or not. Right now, it seems to be not explicitely defined what is intended behaviour.

**Comment by Glitchy-Tozier** [comment]
I agree that this is an issue and should be addressed

**Comment by Glitchy-Tozier** [comment]
I agree that this is an issue and should be addressed

**Comment by patrickgold** [comment]
Thanks for your bug report! Your issue seems to be the same as #1940 if I am not mistaken. If so this is a bug and will be fixed before the next alpha release.
