### ISSUE TITLE
Spell checker suggestions obscured by the keyboard.

### ISSUE THREAD

**Issue by qwertea** [florisboard/florisboard#1961]
#### Short description

The spell checker's suggestion box gets hidden behind the keyboard. Images for reference:

![Screenshot_20220721-123500~2](https://user-images.githubusercontent.com/24505745/180153019-351e3818-0c13-442b-83ea-6428bab07dd8.png)
![Screenshot_20220721-123715~2](https://user-images.githubusercontent.com/24505745/180153025-9ad97743-6815-44bd-951f-39a308be5432.png)

#### Steps to reproduce
1. Enable spell checking then misspell a word in an app that has a text input box at the far bottom of the screen. (The app pictured is Discord.)

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: F-Droid
- Device: Redmi Note 10 Pro
- Android: ArrowOS 11

**Comment by patrickgold** [comment]
Thanks for the bug report!

The spell checker window is drawn by the system, not by FlorisBoard, so I think this is a system issue. Could you please test this with other keyboards as well, should they not obstruct the window then FlorisBoard may have a bad window configuration.

**Comment by Glitchy-Tozier** [comment]
@qwertea Were you able to test this issue with other keyboards (and re-test it with FlorisBoard)?
What were the results?

**Comment by moon-cacke** [comment]
This bug is imacting any keyboard app and is introduced by app using the permission "display over other apps" when two apps are running and using that permission the autocorrect popup is displayed behind the keyboard.

Apparently the bug does not happen when a single active app use that permission...

Solution disable the app using the permission "display over other apps"

**Comment by qwertea** [comment]
Oh, I see. That's unfortunate because I do need the app that's using that permission. Since it's apparently not a bug with Florisboard, I'll close this.
