### ISSUE TITLE
Can you add circumflex letters to Turkish keyboard (â, û, î)

### ISSUE THREAD

**Issue by sudowesu** [florisboard/florisboard#1962]
In Turkish; Ââ, Ûû and Îî characters are used sometimes. It would be nice if they were in the keyboard when you hold the key, just like how it is in the attachments.

![Screenshot_20220722-004736_GitHub.png](https://user-images.githubusercontent.com/67051709/180321161-5ed52674-c254-4c81-a060-4aced8889a64.png)
Ââ in the pop-up menu

![Screenshot_20220722-004724_GitHub.png](https://user-images.githubusercontent.com/67051709/180321201-2d0dd940-1ffc-4ac8-84ce-f8aa2c86f616.png)
Ûû in the pop-up menu

![Screenshot_20220722-004727_GitHub.png](https://user-images.githubusercontent.com/67051709/180321317-980280f0-94f0-4784-9b01-e040ae2147b3.png)
Îî in the pop-up menu

If you are able to add the other characters shown in the pop-up, it would be so great if you could do that! But if you are going to do it, can you please make "ı" as the first suggestion, and "î" as the next to that one, just like how the order is in the screenshots? (the same for â, and û) Because ü and ı are often used whilst û and î are rarely used in Turkish

**Comment by patrickgold** [comment]
Above fix provided by @tsiflimagas adds circumflex letters to the Turkish popup mapping, while ü and ı are still prioritized like you requested. Will be parts of the 0.4.0-alpha02 release. Thanks for your suggestion!
