### ISSUE TITLE
Kurdish Language Support

### ISSUE THREAD

**Issue by kurdikeyboard** [florisboard/florisboard#197]
**Hello, 

I found this amazing keyboard on github when i searched for AOSP based keyboard and found this great one, I interested to use this keyboard in my native language Kurdish i can help with you to add kurdish layouts into your keyboard the in next release the most used Kurdish layout is Kurmanji (Kurdî) Hawar layout and Sorani (کوردی) layouts, The Hawar is write with Latin alphabets and Sorani is writing with perso-arabic alphabets.

Sorani have many Layouts i will attach most used below

Here is the Screenshot:

Kurdî : Qwerty

[![IMG-20210117-063024.jpg](https://i.postimg.cc/qvPX55Jz/IMG-20210117-063024.jpg)](https://postimg.cc/BjCK8N10)

کوردی: Qwerty

[![IMG-20210117-063014.jpg](https://i.postimg.cc/wTbkhBn5/IMG-20210117-063014.jpg)](https://postimg.cc/KRBLbmG4)

کوردی: Standard

[![IMG-20210117-063037.jpg](https://i.postimg.cc/bwD9Lhj7/IMG-20210117-063037.jpg)](https://postimg.cc/TKxbYB10)**

**Comment by patrickgold** [comment]
Thanks for your suggestion! I will place this on my todo list.

**Comment by kurdikeyboard** [comment]
> Thanks for your suggestion! I will place this on my todo list.

You are welcome bro thank you for support Kurdish language :)

**Comment by tsiflimagas** [comment]
I guess this issue can be closed now :)

**Comment by kurdikeyboard** [comment]
> I guess this issue can be closed now :)

Yeah you right i just colsed the issuse :)
