### ISSUE TITLE
Hide "Hide button"

### ISSUE THREAD

**Issue by Archeix7** [florisboard/florisboard#1977]
I suggest adding a toggle to hide this button so you don't accidentally press it when you click on "select all" if your fingers are like sausages ;)
And in general, maybe someone does not need this hiding, because you can simply disable this line in the settings 
![IMG_20220727_212205_273](https://user-images.githubusercontent.com/51048550/181345030-900c519e-9425-4b95-92e8-59351cb4fdf9.jpg)

**Comment by patrickgold** [comment]
Smartbar actions-only layout should solve this issue for you. Closing as resolved.
