### ISSUE TITLE
Broken uppercase accented characters in Greek layout

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1981]
#### Short description
I just came to notice that popups for vowels in Greek don't have any accents, in current HEAD. The offending commit seems to be https://github.com/florisboard/florisboard/commit/b04f8d75f36659beb046fe7ab55d1a8ae1600d4c.
Btw I'm not sure if this should be labeled as `kbd-logic` instead.

#### Steps to reproduce
1. Go to the keyboard, using the Greek layout
2. Hold on a vowel
3. See that popups don't have accents

#### Environment information
- FlorisBoard Version: 0.4.0-alpha01
- Install Source: locally compiled
- Device: Xiaomi Redmi note 8
- Android: Android 12.1, custom rom

**Comment by patrickgold** [comment]
Thanks for the bug report!

At first I thought that I couldn't reproduce this issue, but then I noticed that this is only the case for UPPERCASE popups, where the accents are clearly missing.

Doing a quick search in the Android source code reveals, that Greek capitalization has a [custom implementation](https://cs.android.com/android/platform/superproject/+/master:libcore/libart/src/main/java/java/lang/CaseMapper.java;l=151-153;drc=c989d0ad845e9fd1e5d36e8287395dc16ef39b6d), so it makes me wonder what exactly goes wrong here.

While trying to fix this issue I noticed the Y with the two dots and accent above it. This character behaves very strange and Gboard does not capitalize it at all. Is there something special about this character in Greek?

![image](https://user-images.githubusercontent.com/19412843/181712286-fdd2abb2-f505-45b3-9bec-a153e4fe5175.png)

**Comment by patrickgold** [comment]
>  Btw I'm not sure if this should be labeled as kbd-logic instead.

Yeah I think it is more logic than layout due to the source of the issue. WIll relabel.

**Comment by patrickgold** [comment]
I am currently wondering if we might rewrite the Greek layout to have case selectors (like some characters in Turkish and other languages have) instead of auto text keys, so we prevent this problem all along by manual definitions of both lower and upper case?

**Comment by tsiflimagas** [comment]
> but then I noticed that this is only the case for UPPERCASE popups

What the hell, how did I miss noting that 😬 Sorry for the confusion.

> Is there something special about this character in Greek?

I also noticed that for `ι` too and I don't know why they do so. Well, it's actually very rare to see a capital `υ` or `ι` with dieresis or dieresis and accent, because another vowel has to be before them, since what dieresis does is to state they're separate, and not forming a diphthong, so you can't have them as the first letter in a word. They only do it for dieresis and accent though, so maybe they think that two signs over a capital letter make it too tall and weird looking(?). I don't really know.

> I am currently wondering if we might rewrite the Greek layout to have case selectors

If you think it's a good approach, I can do it really quick.

**Comment by patrickgold** [comment]
> If you think it's a good approach, I can do it really quick.

If you don't mind doing it I'd really appreciate it, this would fix capitalization issues with the Greek layout once-and-for-all.
