### ISSUE TITLE
Spacing after word input in glide typing

### ISSUE THREAD

**Issue by Mech4Life1970** [florisboard/florisboard#1983]

**Comment by Glitchy-Tozier** [comment]
Could you please specify your proposal. Automatic spacing when glide-typing has been a feature for a long time.

**Comment by KLaurence** [comment]
This might be a duplicate of #1940

**Comment by patrickgold** [comment]
I agree with @KLaurence that this is probably a duplicate of #1940, closing thus.

**Comment by Mech4Life1970** [comment]
Yes its on the same lines as #1940 sorry didnt see it...
