### ISSUE TITLE
Shift options with number line

### ISSUE THREAD

**Issue by wolftune** [florisboard/florisboard#1988]
As Anysoftkeyboard offers, please include the standard set of shift-symbols with the numeral line when that is turned on.

So, florisboard already has an option to show the number keys in a line above the text keyboard. That line should have the standard set of symbols `! @ # $ % ^ & * ( )` as the alternate options for those number keys. They should work both with shift and with holding.

**Comment by patrickgold** [comment]
Thanks for your feature request!

Above commit/PR addresses this issue, for manual shifts the numeric row changes to the requested symbols, you can also hold shift and immediately insert one of the symbols and it will automatically return. For caps lock the numbers stay though, in accordance to the behavior of other keyboards which also implement this behavior. The forth symbol, the `$` sign, automatically adapts to the currency set, so it may be `€` or something else depending on your subtype.

Demo:

https://user-images.githubusercontent.com/19412843/182133949-f5ea2bf6-f017-4ac2-a07e-39b9bb5ed2a6.mp4

Will be released in 0.4.0-alpha02.

**Comment by wolftune** [comment]
Nice! Thank you! Will they also be displayed in miniature as hints if that sort of thing is turned on in general?

**Comment by patrickgold** [comment]
No, because if I add a hint the symbol must be permanently accessible as a popup behind the number, which it isn't. Also the numbers are already packed with their own popups (fractions and super script numbers).

**Comment by vy-storm** [comment]
It would sure be nice if you could set each of those shift symbols to any symbol you wanted, I've often wished for this as their existence is a bit of a redundancy if you have hold alts. There are plenty of situational symbols that aren't found in hold alts which I'd love to have bound in place of the standard !@#$%^&*(), of which only ^ can't be accessed simply by holding a letter.

**Comment by wolftune** [comment]
Speaking just as a user (I'm not a developer): It would be nice to offer alternative layouts to choose from with whatever arrangements of alts etc. I could imagine a robust eventuality where layouts are easily customized and shared, so you could just publish your own layout for others to download and so on, separately from forking the whole florisboard project. I haven't investigated how far from that things are currently.

**Comment by vy-storm** [comment]
> Speaking just as a user (I'm not a developer): It would be nice to offer alternative layouts to choose from with whatever arrangements of alts etc. I could imagine a robust eventuality where layouts are easily customized and shared, so you could just publish your own layout for others to download and so on, separately from forking the whole florisboard project. I haven't investigated how far from that things are currently.

I agree, I personally wouldn't change the default alphabet alts, but I know many certainly would. I'd add both Icelandic and German characters to the extended alts but that's just me.

I would however absolutely change the !@#$%^&*() number row alts to either symbols that hide in the secondary =}< symbol menu, or even if given the choice ones which aren't present on my keyboard at all!
