### ISSUE TITLE
Allow disabling emoji history

### ISSUE THREAD

**Issue by omentic** [florisboard/florisboard#1990]
Emoji history was added in #268 which is great for those who use it: but now there's no way to not have it! :smiley: 

I suggest changing the "emoji history max size" setting so that the low end of the spectrum is 0, which would disable the recently used pane and make the smilies pane the default. The "unlimited" setting could be moved to right after the current numerical max (120).

**Comment by patrickgold** [comment]
Thanks for your suggestion!

Didn't think that there will ever be the need for such toggle, as this feature was requested a lot at the time and pretty much every emoji palette out there nowadays has a recents panel. However adding an enable/disable toggle shouldn't be a problem and it allows customizing the keyboard even more.

The reason why I won't use the `0` value for this in the slider dialog is that this would be super inconsistent with the way other feature enable toggles are handled in this app and `0` is internally the Unlimited option already.

> The "unlimited" setting could be moved to right after the current numerical max (120).

While this would logically make sense it is difficult to implement, as it would prevent me from ever adjusting the max value again if I put the Unlimited value on the right (technical limitation atm).

**Comment by Saarsk** [comment]
This is awesome. It have been driving me crazy. 🙂 

I used to think I wanted emoji history. The problem with emoji history is that the emojis change place and move around all the time. So every time you have to go on a treasure hunt to find the emoji you're looking for. You can never know where the emoji you need is.

But without emoji history you can actually learn where emojis are so you can quickly seek them out every time.
