### ISSUE TITLE
[bug] fennec & tampermonkey : cannot export zip

### ISSUE THREAD

**Issue by DriftMANHD** [florisboard/florisboard#1993]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: i do not know, using feenec 102.1.1
- Install Source: f-droid
- Device: Samsung S7 Edge SM-G935F, Xiaomi Redmi 7A
- Android: 8.0.0 & 9.0 both original

[bug] i can not export zip with scripts, loading image doing 360o in infinity time.. 

can i fix this?

**Comment by patrickgold** [comment]
How should this be an issue with FlorisBoard? The keyboard has nothing to do with the interaction between Tampermonkey and Fennec.

**Comment by DriftMANHD** [comment]
sorry i'm doing a mistake not in this topic 
i we can delete this isssue
