### ISSUE TITLE
[bug] keyboard and mouse from usb otg

### ISSUE THREAD

**Issue by DriftMANHD** [florisboard/florisboard#1994]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…' keyboard and mouse and plugin to the phone
2. Click on '…' any element
3. Scroll down to '…' error
4. See error error? click mouse on any element or click and drag on screen to move on zoom not working or working partialy explain lick on first element working and... click on second element not working.. it doesnt matter fennec window or webpage.

#### Environment information
- FlorisBoard Version: fennec 102.1.1
- Install Source: f-droid
- Device: Samsung S7 Edge SM-G935F & Xiaomi Redmi 7A
- Android: 8.0.0 & 9.0

**Comment by Glitchy-Tozier** [comment]
> this too..

Do you mean "This issue can be closed"?

**Comment by patrickgold** [comment]
Closing as this issue is not properly filled out and does not provide any useful information.
