### ISSUE TITLE
Upstreaming Catppuccin theme

### ISSUE THREAD

**Issue by skinatro** [florisboard/florisboard#1996]
Hello,

I created a [catppuccin theme for floris board ](https://github.com/catppuccin/floris-board). Hoping it would get merged upstream into the app itself

Thank you

**Comment by lm41** [comment]
Somehow related to #2327. I don't think user created themes will be upstreamed in Florisboard, but #2327 is already being worked on and I think this would be the right place to share something like that.

**Comment by patrickgold** [comment]
Once #2468 is finished you will be able to publish your theme in the addons store, thus I'll close this issue.
