### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by qw123wh** [florisboard/florisboard#2]
hello your app is very nice I'm trying it on the play store.  I would like to fully translate it into Italian, send me the necessary strings for the translation.

**Comment by patrickgold** [comment]
Hi qw123wh,

thank you very much for your offer to translate FlorisBoard into Italian, I really appreciate it!

I've updated the [CONTRIBUTING.md](https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md) file with a translating guide. If you need any further assistance don't hesitate to ask me.

Best regards, Patrick

**Comment by qw123wh** [comment]
I completed the translation into Italian. See if I did well with the pull request. I'm not very practical
