### ISSUE TITLE
Computer Keyboard

### ISSUE THREAD

**Issue by xmha97** [florisboard/florisboard#2002]
Please add computer keys
For example F1-F12
Alt, Ctrl, Shift, Tab, etc
![Screenshot_2022-08-04-13-06-06-261_org.pocketworkstation.pckeyboard.jpg](https://user-images.githubusercontent.com/23485114/182803988-3596847a-9054-4b0f-978b-bfae1adf4c39.jpg)

**Comment by flexagoon** [comment]
Duplicate of #229

**Comment by Glitchy-Tozier** [comment]
@flexagoon is right, please move all discussion to #229.
