### ISSUE TITLE
Narrow Popup Items

### ISSUE THREAD

**Issue by Arbaazhussain829** [florisboard/florisboard#2009]
#### Short description
Issue that each popup item itself in the expanded panel is very narrow.

#### Steps to reproduce
In keyboard while using it.
It is not customisable in any manner.
![Screenshot_2022-08-09-17-53-51-403_dev.patrickgold.florisboard.beta.jpg](https://user-images.githubusercontent.com/69892240/183788359-7529dafb-7031-4609-95d2-8844326d114d.jpg)

Unlike on previous build v0.4.0-alpha1 and release builds which doesnt have this issue.
![Screenshot_2022-08-09-17-56-04-581_dev.patrickgold.florisboard.jpg](https://user-images.githubusercontent.com/69892240/183788554-b87047a5-f395-4a49-91e7-15b4e0714a7b.jpg)

#### Environment information
- FlorisBoard Version: v0.4.0-alpha2 
- Install Source: GitHub
- Device: Redmi Note 10 Pro Max
- Android: Android 12, MIUI 13

**Comment by Arbaazhussain829** [comment]
Addition to it
Its not just popup when i changed my themes to a border one i found that its also same for keys ![Screenshot_2022-08-10-06-55-32-130_dev.patrickgold.florisboard.beta.jpg](https://user-images.githubusercontent.com/69892240/183790312-710adecc-bf33-48f2-8e3d-4634332d1ef7.jpg)

**Comment by Arbaazhussain829** [comment]
Only occured when dirty updating 
When i reinstalled it was alright
Maybe updates are breaking themes

**Comment by patrickgold** [comment]
Thanks for your bug report!

May I ask what value is set for the preference Keyboard > Key spacing (both values)?

**Comment by Arbaazhussain829** [comment]
> Thanks for your bug report!
> 
> May I ask what value is set for the preference Keyboard > Key spacing (both values)?

It was 0.0 dp on both.

**Comment by patrickgold** [comment]
As this seems to be a single occurrence of this issue and it does not occur with a clean install I will close this issue. Should this be more widespread further investigation might me needed.
