### ISSUE TITLE
[suggestion] for emoji selector

### ISSUE THREAD

**Issue by itskareem** [florisboard/florisboard#201]
there's this [emojis app](https://github.com/klinker-apps/Android-SlidingEmojiKeyboard) and since the emojis won't get updated until v0.5 it would be nice if you could use it as an alternative emoji selector until v0.5 thanks.

**Comment by patrickgold** [comment]
I am unsure what exactly you mean for this. It is already possible to switch to the previous keyboard via space swipe up, which could lead you to the emoji selector keyboard (if it was your last used keyboard). The emoji key itself will just lead to the FlorisBoard internal emoji keyboard and I will not change this, sorry. v0.3.4 will though allow you to disable the emoji key completely, so I hope the space swipe up + emoji key disabling is a sufficient workaround for you.
