### ISSUE TITLE
Support long press for left/right/undo/redo

### ISSUE THREAD

**Issue by KaKi87** [florisboard/florisboard#2013]
Just like backspace supports long press.

Thanks

**Comment by patrickgold** [comment]
Left and Right already support long press, don't they? And for Undo and Redo, I added support for long press in the draft PR #2012 (due to the quick actions rework I thought this would make sense), so I will attach your issue to the PR.

**Comment by KaKi87** [comment]
Here's what happens when long-pressing an arrow button :

![](https://user-images.githubusercontent.com/21284089/184933088-21a6359b-c545-43e9-97fa-d18bf7530c87.gif)

**Comment by patrickgold** [comment]
Ah I see, so your issue is basically #1674, I thought you meant general hold-and-press functionality. This bug is addressed in my current draft PR #2012, meaning in v0.4.0-alpha03 this will not be an issue anymore and you can hold the arrow key for repeated cursor movement.

**Comment by KLaurence** [comment]
@patrickgold Would this be okay with #1094?

**Comment by patrickgold** [comment]
> Would this be okay with https://github.com/florisboard/florisboard/issues/1094?

Yes and no, as I've experienced it in testing of #1094's implementation. Yes in the fact that the tooltip does not block the repeating action of an key, only the up. No in the fact that there will always be a tooltip shown if you use arrows within the Smartbar, qhich could be annoying. So for now a design issue, however I don't know if this conflict is fixable.

**Comment by KLaurence** [comment]
I see. If I have any ideas for the design, I'll likwly mention them in #1094 or #2012 to avoid the bikeshedding here.
