### ISSUE TITLE
Suggestions underlines words even when disabled

### ISSUE THREAD

**Issue by Cuddle0456** [florisboard/florisboard#2019]
#### Short description
Wordz getting underlined but suggestions & corrections are disabled.

#### Steps to reproduce
Disabled everything related suggestions etc. even removed samsung keyboard, still problems happens but it doesn't happen on OpenBoard.

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: F-Droid
- Device: Samsung A52
- Android: 12, Stock

https://user-images.githubusercontent.com/108587502/185802722-74dbf4ea-76ed-489a-b040-131b4dcda7f0.mp4

**Comment by KLaurence** [comment]
Can you download the latest alpha release (either from the IzzyOnDroid repo for F-Droid or the [Releases page](https://github.com/florisboard/florisboard/releases) of this repo) and check if the underline still appears?

This should have been fixed with #1911 on an alpha release.

**Comment by Cuddle0456** [comment]
I have tried beta version and It looks like It is fixed on it so I am closing this issue, I hope developers can bring this fix to stable release as soon as possible alao thanks everyone who put effort to make this amazing keyboard it is perfect.

**Comment by navid-zamani** [comment]
Adding beta/alpha versions to F-Droid (marked as such, so that only users who have them enabled get them) would be quite welcome, by the way.

**Comment by tomatojam42** [comment]
This bug now after `0.4.1` release!

![Screenshot_2024-10-13-08-35-10-29_d0ef7a9810af20f7b394f4f927b723b0](https://github.com/user-attachments/assets/d19fa407-e2b8-4ebf-9da3-65c14031bf87)

**Comment by patrickgold** [comment]
not a bug because emoji suggestions are enabled, if you disable them then the line won't show
