### ISSUE TITLE
Emoji keyboard is missing heart hands emoji

### ISSUE THREAD

**Issue by IveMalfunctioned** [florisboard/florisboard#2023]
Hello, I was looking through the emoji list for the heart hands emoji (🫶), it doesn't appear to have it. I have no idea if Florisboard has its own list of emoji characters or if it pulls it from some sort of online unicode list, so my apologies if this comes off as spam. Maybe have a separate tab in the emojis list for unicode emojis that aren't fully supported everywhere? Because on PC it doesn't appear correctly in the font.

**Comment by patrickgold** [comment]
The emoji heart hands was added in Emoji 14.0 back in 2021, see [here](https://emojipedia.org/heart-hands/) and according to this page it was added to Android in 12L, which is one of the newest versions. So unless you have an ultra up-to-date device your system font does not support it and with that FlorisBoard does also not offer it. However FlorisBoard should be up-to-date with Unicode 14.0 in general, so if your system font supports it it should be findable.

Normally you can also try various messenger apps to test if you find the emoji there, as these often times use EMojiCompat, which allows to load a different font for emojis, independent from the system standard.

**Comment by IveMalfunctioned** [comment]
It shows up fine in Google Messenger, but not anywhere else that I've seen including devices other than my phone which is Android 11. Specifically on Firefox 103.0.2 on Windows 10 21H2. I don't know if Firefox pulls fonts from Windows or uses its own updated version, but in theory it should show up correctly there as well. Couldn't Floris pull the font from the same source as Messenger? Or if it's not already installed on the device, perhaps include it with the app just so it shows up as a typable emoji even if it doesn't when it's in the text box of wherever you type it?

**Comment by patrickgold** [comment]
> I don't know if Firefox pulls fonts from Windows or uses its own updated version, but in theory it should show up correctly there as well.

If Firefox pulls from the system your system is Windows 10 21H2, and according to Emojipedia Windows 10 has no support for this emoji.

> Couldn't Floris pull the font from the same source as Messenger, Google noto color emoji? That's what it already uses that I can see. Or if it's not already installed on the device, perhaps include it with the app just so it shows up as a typable emoji even if it doesn't when it's in the text box of wherever you type it?

I mean I can include a custom Emoji font, however I find it extremely weird if the emoji looks completely different in FlorisBoard in comparison to what the app renders it (if it even supports it), so FlorisBoard adapts to the target app, both in in compatibility of which emojis are supported and in the font.

@ GoRaN909 presented a way to change your system font (which is used by most apps outside messengers), some ROMs include such options for all users in the system settings or in a system theme app. Other than that I don't really know if I can do much more in this issue.

**Comment by CutestNekoAqua** [comment]
btw, new emojis
🩵🩷 arent listed in floris beta on fdroid too :/

**Comment by patrickgold** [comment]
Closing as this issue is stale and there is nothing to implement.
