### ISSUE TITLE
Clipboard suggestions are showing even if suggestions are turned off

### ISSUE THREAD

**Issue by KaKi87** [florisboard/florisboard#2029]
**Edit by @patrickgold**: The bug is that clipboard suggestions how even though suggestions are disabled in the preferences.

---

Hello,

When copying text from an app and opening the keyboard in another one, it suggests pasting the copied text.

It would be nice to be able to disable this behavior.

Thanks

**Comment by KLaurence** [comment]
What version of Florisboard are you on? On the latest version (which doesn't have word suggestions), that should be already possible in `Settings` > `Typing` > `Clipboard content suggestion`.

**Comment by KaKi87** [comment]
Actually, I'm on `0.4.0-alpha01` (needed it to solve other issues).
Turns out, I had to do something a bit weird :
- Check *Display suggestions*
- Uncheck *Clipboard content suggestions*
- Uncheck *Display suggestions*
(The *Clipboard content suggestions* option is greyed out -while checked by default- when the *Display suggestions* option is unchecked).
Thanks

**Comment by KLaurence** [comment]
Clipboard suggestions showing even if `Display suggestions` is off sounds like a bug.

I can reproduce in 0.4.0-alpha3 that copied URLs and phone numbers are suggested even if `Display suggestions` is off (although you might need to click the overflow button that switvhes from the Smartbar to the suggestions bar).

I'll let Patrick (the keyboard's developer) see this and decide if it really is a bug.

**Comment by patrickgold** [comment]
Clipboard suggestions should not show if suggestions are off, that is definitely a bug. I am able to fully reproduce this bug too. Will reopen this issue, rename it and provide a fix later on.

**Comment by patrickgold** [comment]
Above linked commit/PR fixes this issue, the clipboard suggestions are now only showing if both the main suggestions and clipboard suggestions are enabled. This fix will be included in the v0.4.0-alpha03 release. Thanks again for reporting!

**Comment by KaKi87** [comment]
> This fix will be included in the v0.4.0-alpha03

But, that release already exists

**Comment by patrickgold** [comment]
Yeah I meant v0.4.0-alpha04, I am sorry
