### ISSUE TITLE
Ability to change the font size of the symbols keyboard and the alphabet keyboard separately

### ISSUE THREAD

**Issue by sirsleon** [florisboard/florisboard#203]
If I set key font size to 100%, when I switch to symbols it goes up about 15%.
It would be nice if I could lower it to match each other as it's annoying that it is not uniform in size.

**Comment by patrickgold** [comment]
Hmm strange, this should not happen. If possible could you post 2 screenshots (character and symbol layout) for comparison? Normally, the font size should match up between a character and symbol key.

**Comment by sirsleon** [comment]
![Screenshot_20210119-095403](https://user-images.githubusercontent.com/65666396/104969571-f632e400-5a3c-11eb-8e7b-2b16fdf19814.png)
![Screenshot_20210119-095359](https://user-images.githubusercontent.com/65666396/104969572-f7641100-5a3c-11eb-8137-3cdbfc44186b.png)



@patrickgold

**Comment by patrickgold** [comment]
Ah I see, this happens due to the number row being enabled and the base key size does not match between the character and symbol layout. I will place this on my todo list!
