### ISSUE TITLE
Make it so that closing extended actions also closes the overflow menu.

### ISSUE THREAD

**Issue by Keepkeepzz** [florisboard/florisboard#2035]
When you have smartbar layout set to suggestions & actions shared, if you have the overflow menu open and press the shared actions toggle it will automatically close the overflow menu. This behaviour however doesn't happen when the smartbar layout is set to suggestions & actions extended.

It would be nice if closing extended actions also closed the overflow menu just so that if you do close the extended actions without closing the overflow menu, you don't have to re-open it, close the overflow, then close the extended actions again.

**Comment by patrickgold** [comment]
Above linked commit/PR changes the behavior, the extended actions toggle now also closes the actions overflow like the shared actions toggle. Will be parts of the v0.4.0-alpha04 release.
