### ISSUE TITLE
[Ctrl, Alt, Tab] Key Add

### ISSUE THREAD

**Issue by kayyum-uddin** [florisboard/florisboard#2038]
This keyboard makes life easier and better with these 3 key in smartbar.

**Comment by patrickgold** [comment]
These keys are planned to be supported within the keyboard UI itself (and in a separate modifier&selection keyboard), not as an Smartbar actions, as they don't fit the theme for an action. Maybe this will be possible with custom actions sometime in the future (where you can dynamically add new actions for yourself), but for now I will reject your proposal.
