### ISSUE TITLE
Default to symbol shown on key when long-pressing

### ISSUE THREAD

**Issue by ohhai-kthxbai** [florisboard/florisboard#204]
(love this keyboard so far, thanks!)

When we long press on a key to get the symbol shown (e.g. excalmation point) could we please get the symbol shown on the key by default, and not have to move across to it. I keep getting odd alternative characters instead of the one shown (superscript) on the key and it's slow/frustrating.

Thanks!

**Comment by patrickgold** [comment]
If you go to `Settings > Keyboard` you have two preferences, one for the hinted number row and one for the hinted symbols. If you set these to `Enabled (Hint is prioritized)`, the small character shown on the key will actually be the first character in the extended popup.

Let me know if this fixes your issue!

**Comment by Kreuger** [comment]
@patrickgold I yhink this is asking the same thing as I had asked in issue #112

**Comment by patrickgold** [comment]
@ohhai-kthxbai In the current version v0.3.4/v0.3.5 you have three options for this: `Accent priority`, `Hint priority` (what you are asking for) and `Smart prioritization`. Found in Settings > Keyboard. Closing this issue as it is stale. If you have anything further regarding this issue, you can of course re-open it.
