### ISSUE TITLE
Vibrate on long press activation on all keys

### ISSUE THREAD

**Issue by sybenx** [florisboard/florisboard#2043]
When long pressing to select a symbol or number from keyboard, vibrate on activation. This would allow user to get feedback on activation without needing visual confirmation, speeding up typing. This feature is present on some other keyboards such as Samsung Keyboard.

**Comment by patrickgold** [comment]
Thanks for your feature proposal!

If I am not mistaken this is already implemented, if you go to Floris Settings > Keyboard > Sounds&Vibration and enable "Key long press vibration" it should vibrate on long press activation, provided vibration itself is enabled.

**Comment by sybenx** [comment]
You're right
