### ISSUE TITLE
Secondary action row

### ISSUE THREAD

**Issue by Mahantor** [florisboard/florisboard#2044]
Please add secondary action row to the keyboard again. In the new version of Alpha 4, there are a few useful shortcuts available in main row

**Comment by KLaurence** [comment]
The shortcuts that were previously in the main row (`Select all`, `Copy`, `Cut`, `Arrow left`, `Arrow right`, `Paste`, `Clear clipboard`, and `Open clipboard history`) should be available by using either of the new options `Suggestions & Actions shared` and `Suggestions & Actions extended` in `Settings > 6Smartbar > Layout`.

**Comment by patrickgold** [comment]
Like KLaurence said, all the clipboard/cursor row items have been merged into the normal actions. So inside the action row, if you click the three dots you should get to the actions overflow, where all the other actions are that do not fit into the main row. You can also freely reorder them using the "Reorder actions" button. Closing as this is already implemented.

**Comment by Mahantor** [comment]
So please add the possibility of adding more items and horizontal swiping of items, or add the possibility of adding more items to the part specified in the photo.
![Screenshot_2022-09-03-13-52-01-690_dev patrickgold florisboard beta-edit](https://user-images.githubusercontent.com/91434001/188265231-cc3db58b-8014-43f1-9140-2ec6dfcfcb65.jpg)
![Screenshot_2022-09-03-14-14-39-403_dev patrickgold florisboard beta-edit](https://user-images.githubusercontent.com/91434001/188265246-03d4da6f-2fb1-4eca-81a1-65f2de5130ff.jpg)
