### ISSUE TITLE
Use MonetCompat  to implement Material You Support

### ISSUE THREAD

**Issue by Yurieaijoker** [florisboard/florisboard#2046]
Hi!  I am not really a dev so i dont know a lot but i just found this monetcompat developed by Kieron Quinn https://github.com/KieronQuinn/MonetCompat
and he implements this to his apps to have a material you style interface that automatically matches the wallpaper on Android version lower than A12 that does not implement material you theming and its very good cause my phone is Android 10. I would like to suggest using this to generate automatic material you theming on florisboard themes to support monet on themes on Android version lower than A12.

Hoping for a kind response.  Thank you!

**Comment by Yurieaijoker** [comment]
Heres a sample of his app that uses monet and I am on android 10
And it looks good. 
I dont know if its possible to implement to themes but it would also be nice to have it implemented in the app interface
![Screenshot_20220903_083709_com kieronquinn app darq](https://user-images.githubusercontent.com/93813352/188249046-851c4043-3f69-439f-b57c-74139affa507.jpg)

**Comment by Yurieaijoker** [comment]
![Screenshot_20220903_094820_com kieronquinn app darq](https://user-images.githubusercontent.com/93813352/188251244-c52a0b7d-a3da-486a-b121-c0f5c3c42a40.jpg)

**Comment by Yurieaijoker** [comment]
https://github.com/KieronQuinn/MonetCompat/wiki/2:-Usage

**Comment by patrickgold** [comment]
Thanks for your proposal!

This is definitely an interesting library. I've had a quick look and it could be very useful and I may use this over the AndroidX library. I will take a closer look at this library when I have a bit more spare time, at the moment I have a lot to do and am experimenting with word suggestions locally.

**Comment by Yurieaijoker** [comment]
No problem. I just really love this keyboard.

**Comment by HardcodedCat** [comment]
Any plans for adding monet support for A12? Along with Monetcompat?

**Comment by patrickgold** [comment]
In above linked PR [1fexd](https://github.com/1fexd) has kindly implemented Material You support into FlorisBoard. The PR is currently under review by me but if no other roadblocks are found Material You support will be shipped in the next alpha release v0.4.0-alpha05 alongside the experimental word suggestion support.

**Comment by rokejulianlockhart** [comment]
@patrickgold, what linked PR by @1fexd?
