### ISSUE TITLE
Smartbar tooltips appear on tap when smartbar key (pressed) has a border

### ISSUE THREAD

**Issue by whatevenisthat** [florisboard/florisboard#2047]
#### Short description
If the theme you are using has a border color set for the "Smartbar action key pressed" rule, it will make it so that whenever a smartbar action is tapped (without long press) the tooltip will show up.

#### Steps to reproduce
1. Create or edit a theme.
2. Add rule with Target element **Smartbar action key** and Selectors set to **Pressed**.
3. Add property **Border color** and set the value to any color.
4. Tap any smartbar action key (excluding clipboard or emoji) and the tooltips will pop up even without long-press.

#### Environment information
- FlorisBoard Version: 0.4.0-alpha04 (also in alpha03)
- Install Source: Github
- Device: Nokia 7.1
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report!

I just tested out this bug and I can indeed confirm this. What I can observe is that with a border color the animation is janky too, which leads me to believe that the button element somehow duplicates itself and its initial element stays pressed, thus the tooltip logic thinks you still long-press that item. Although I am not entirely sure what happens here, this needs a bit of testing. Adding to the list of Smartbar issues.

**Comment by patrickgold** [comment]
For me this bug is not reproducible in the latest v0.4.0-beta02 anymore, could you check if it is fixed?

**Comment by whatevenisthat** [comment]
Yeah I can't seem to reproduce it in the latest beta either.

**Comment by patrickgold** [comment]
Ok then I think I will close this issue, if it is consistently reproducible we can reopen it.
