### ISSUE TITLE
Allow for smaller shift and backspace keys (mostly for bépo)

### ISSUE THREAD

**Issue by Salamandar** [florisboard/florisboard#205]
As discussed on https://github.com/florisboard/florisboard/pull/202, the lower line of the keyboard is not adapted to more than 7 keys.
But bépo usually has "ê" and "à" on this line. I've been using Swiftkey and its bépo layout has 9 chars : the shift and backspace are the same width than the same keys (that makes a 11 chars width screen).

Would it be possible to reduce the minimum width of those two keys ?

**Comment by patrickgold** [comment]
I've just looked at the KeyView measurement implementation and this is definitely possible. Are the shift and delete key on SwiftKey the same width as a normal key in this row when there are 9 keys in between?

**Comment by Salamandar** [comment]
I tried removing DELETE and SHIFT from the `when` in KeyView.kt (lines 126 and 410) and that looks GREAT. Although that "breaks" other layouts (screenshots incoming).

> Are the shift and delete key on SwiftKey the same width as a normal key in this row when there are 9 keys in between?
Yeah exactly the same width. I don't know how their width calculation is done (are they always the same width as the other keys of the line ?).

**Comment by patrickgold** [comment]
Ok I think I've found a nice solution after experimenting around a bit, I will make a PR soon.

**Comment by patrickgold** [comment]
@Salamandar above PR is an attempt to fix this issue. I've attached screenshots too.

**Comment by patrickgold** [comment]
> But bépo usually has "ê" and "à" on this line

As the issue with 9 characters has been resolved in #206, if you want you can add a bépo variant with the 2 extra keys in the third row for users who are used to this. I've looked at different keyboards and it seems that there are some keyboards which have 7 keys in the third row and some the 2 extra, so it is easier for all to adapt to FlorisBoard.
