### ISSUE TITLE
Incognito icon behind keyboard

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#2050]
#### Short description
Describe the bug in a short but concise way.
There is an incognito icon behind the keyboard in some app, "infinity for reddit"

![Screenshot_20220904-133945_Infinity](https://user-images.githubusercontent.com/50382414/188311450-6e2971e3-c534-4fa9-b4c5-ff9b88d044cf.png)

#### Environment information
- FlorisBoard Version: 0.4.0 alpha 4
- Install Source: Github
- Device: Xiaomi Mi 9T Pro
- Android: Android 10, lineageos

**Comment by tsiflimagas** [comment]
It's a feature. Some apps (like browsers in incognito mode) request the keyboard to be in incognito mode, for privacy reasons I guess. FlorisBoard have this I indication when it's in incognito. I thought Gboard had that too, but I don't see it there now.

**Comment by tsiflimagas** [comment]
Well, that was more of a question, essentially, so I guess it can be closed now that it's been answered.

**Comment by patrickgold** [comment]
> I thought Gboard had that too, but I don't see it there now.

Gboard replaces its quick action arrow icon with the incognito icon. So it still has this indicator, just not behind the keys.

**Comment by furkun** [comment]
I think there should be an option to turn this off.
