### ISSUE TITLE
It was fun plau with floris. 

### ISSUE THREAD

**Issue by FruSanchez** [florisboard/florisboard#2052]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by tsiflimagas** [comment]
Your issue is empty. Reopen it once you fill it out with the report you wanted to do.
