### ISSUE TITLE
Use space if sticky action isn't used

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#2059]
The new actions system is an interesting update. It definitely helped declutter the smart-bar.

One thing I'd like to point out is that space could be better used when not using a sticky action. I suggest moving the `...` one slot over and making room for one additional dynamic action.

![Screenshot_20220907-222703_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/188970800-df549876-fb42-46cf-b133-e813fcb05643.jpg)

**Comment by patrickgold** [comment]
I think you mean #2033, which was implemented with v0.4.0-alpha04. It should be published on Gplay hopefully this Friday (GPlay track still have the alpha03 release due to the extended review of the privacy policy).

**Comment by Glitchy-Tozier** [comment]
Ah, yes, I thought I had seen a similar issue, but I couldn't find it.

**Comment by Glitchy-Tozier** [comment]
I'm on the phone, so I'll close without changing tags.

**Comment by patrickgold** [comment]
Added the tags. I must say though the original issue didn't exactly use the best wording in the title, so that's why you oversaw it probably :)
