### ISSUE TITLE
Can anyone tell me which app from system is missing 

### ISSUE THREAD

**Issue by araafroyall** [florisboard/florisboard#2067]
![IMG_20220911_065130](https://user-images.githubusercontent.com/87515236/189508066-7532d835-0188-4b3f-a2d6-f7e22ef3480d.jpg)

Hi when i click voice input it shows this. 
can anyone tell me which app require in system for this to work

**Comment by KLaurence** [comment]
From what I can tell, you should be able to go to your device's settings ([using this guide](https://www.techbone.net/android/user-manual/manage-keyboards)), turn on voice keyboards, and switch to them using the `Voice input` button.

Alternatively, some of the voice keyboards that are supported are listed [here](https://github.com/florisboard/florisboard/issues/195#issuecomment-1041339205) (at the second paragraph).

**Comment by patrickgold** [comment]
As KLaurence correctly explained, you need a Voice IME (Input Method Editor). FlorisBoard atm does not support the usage of a non-keyboard based voice provider (because this requires more advanced technical setup), and FlorisBoard itself does also not provide a voice service by itself atm, so a voice IME must be installed so the voice input button works.

As this question has been answered I will close this issue.

**Comment by araafroyall** [comment]
I want to know where can i find this voice IME app. If you know please give me the link . Thanks

**Comment by araafroyall** [comment]
> As KLaurence correctly explained, you need a Voice IME (Input Method Editor). FlorisBoard atm does not support the usage of a non-keyboard based voice provider (because this requires more advanced technical setup), and FlorisBoard itself does also not provide a voice service by itself atm, so a voice IME must be installed so the voice input button works.
> 
> As this question has been answered I will close this issue.

I want to know where can i find this voice IME app. If you know please give me the link . Thanks

**Comment by tsiflimagas** [comment]
As KLaurence explained already, there's a list of voice IMEs here https://github.com/florisboard/florisboard/issues/195#issuecomment-1041339205
