### ISSUE TITLE
Keyboard height issue in incognito mode 

### ISSUE THREAD

**Issue by Lavin-tom** [florisboard/florisboard#2076]
#### Short description
When switch to incognito mode, keyboard height slightly raised

#### Environment information
- FlorisBoard Version:  v0.4.0-alpha04
- Install Source: F-Droid
- Device: Samsung Galaxy M31s
- Android:  11, Stock

**Comment by patrickgold** [comment]
Do you have a screenshot for this? I've never seen this and a visual of the bug might help me understand how this is caused.

**Comment by Lavin-tom** [comment]
![MP4_20220922_192145_1](https://user-images.githubusercontent.com/53207510/191771661-c2091ec4-9a29-4180-8fd6-f264c92a13e0.gif)

**Comment by Lavin-tom** [comment]
Currently am using blank theme, still i hope you can understand what i mean

**Comment by rancidfrog** [comment]
What is the theme? It looks great

**Comment by Lavin-tom** [comment]
> What is the theme? It looks great

Customized theme

**Comment by patrickgold** [comment]
Is this issue resolved for with with the latest v0.4.1 release?

**Comment by itsmartashub** [comment]
> Is this issue resolved for with with the latest v0.4.1 release?

It seems to be fixed in the latest `v0.4.1` release. No matter how small I set the keyboard height, when switching to incognito mode, the height doesn’t raise anymore. Everything stays consistent now 👏🏼

**Comment by patrickgold** [comment]
thanks for confirming, closing this as resolved :+1:
