### ISSUE TITLE
Separate settings for different popups

### ISSUE THREAD

**Issue by SosPosos** [florisboard/florisboard#2083]
Why can't i make different shapes for different popups?
When i change settings for one popup it applies to all of the popups
![IMG_20221006_212458_927](https://user-images.githubusercontent.com/52379151/194390170-e179884c-f74b-4746-94b5-cc6b39132c43.jpg)
![IMG_20221006_212500_746](https://user-images.githubusercontent.com/52379151/194390187-b2f5ea28-dfb7-4cb1-90fb-7dcf978c9446.jpg)

**Comment by patrickgold** [comment]
Thanks for your bug report!

I just had a quick look at the popup UI implementation and I think this snippet is reponsible for the incorrect behavior:
https://github.com/florisboard/florisboard/blob/4b2211b5c02a2338556b458f4322ae9c6b68e021/app/src/main/kotlin/dev/patrickgold/florisboard/ime/popup/PopupUi.kt#L56-L58

As you can see I only pass in the element selector name (`key-popup`), but completely ignore the code and other parameters. Will add this to the list of theme issues.

**Comment by SosPosos** [comment]
Thank you!!
