### ISSUE TITLE
Do not copy padded contents from websites

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#2086]
Is there a way to force only selected text being copied on sites?
Some sites pad selected text with extra contents, i.e. site url

**Comment by rancidfrog** [comment]
Screenshot is not useful,
But.
```
<script type="text/javascript">
function addLink() {
	var body_element = document.getElementsByTagName('body')[0];
	var selection;
	selection = window.getSelection();
	var pagelink = "<br /><br /><a href='"+document.location.href+"'>"+document.location.href+"</a><br />Copyright &copy;"; // change this if you want
	var copytext = selection + pagelink;
	var newdiv = document.createElement('div');
	newdiv.style.position='absolute';
	newdiv.style.left='0';
	body_element.appendChild(newdiv);
	newdiv.innerHTML = copytext;
	selection.selectAllChildren(newdiv);
	window.setTimeout(function() {
		body_element.removeChild(newdiv);
	},0);
}
document.oncopy = addLink;
</script>
```
Sites are using JS to append selected text with content somehow hijacking copy function.

**Comment by patrickgold** [comment]
I don't see how should FlorisBoard distinguish between dynamically added text by websites and by manually written text? Websites run in their own sandbox and FlorisBoard has little control over them. The copy function is first managed by the browser, which FlorisBoard can then access and use.

As I don't see how this should work I am closing this feature-request.
