### ISSUE TITLE
Hide 'Show more actions' button in smartbar if there is only one action in the menu

### ISSUE THREAD

**Issue by Elbullazul** [florisboard/florisboard#2094]
If there is only one action in the 'more actions' menu, it would be better to display that action instead of the 'show more actions' button.

What do you think?

**Comment by Glitchy-Tozier** [comment]
1. On one hand, this sounds very elegant.
2. On the other hand, I'm suspecting this might cut the user off off ever editing these actions, due to being unable to return to the menu.

I haven't investigated this topic too deeply though. Are you aware of any alternate intuitive paths to open that menu?

**Comment by Elbullazul** [comment]
I don't know of another way to open the 'more actions' menu. Maybe adding an option in the settings, or in the ',' long-press pop-up menu would be a good idea, if it's not too hard to do?

**Comment by Glitchy-Tozier** [comment]
It shouldn't be to difficult to implement, but I'm still not sure how user-friendly something like this would be.
Let's see what Patrick (the main developer) thinks, when he gets around to reading this thread!

**Comment by patrickgold** [comment]
Thanks for your feature request, really appreciate it!

I get where you coming from and find the idea very elegant at first glance. However as this discussion has already brought up though there are no alternative ways of accessing the quick action editor menu atm, so this could very well lead to confusion among some users.

On a technical level adding a button in the settings should be very easy, however I am not satisfied with the user experience of that, as normally you'd expect to access this menu more quickly within the Smartbar UI itself.

A possible solution I could think of: By default the current behavior is left as-is. If you want this behavior you have to actively flip a toggle for this in the Smartbar Settings Screen, this way you are now aware that the more button might disappear and you must use the button within the Settings to access said menu.

Thoughts or other ideas?

**Comment by Glitchy-Tozier** [comment]
> Thoughts or other ideas?

I'd just like to mention that we should be very careful about adding more toggles to the settings.
I live in constant fear of FlorisBoard turning into AnySoftKeyboard over time. Even now settings already feel pretty extensive.

**Comment by Elbullazul** [comment]
Should this be closed with a wontfix tag then?

**Comment by patrickgold** [comment]
I think this will probably never be implemented due to the unnecessary UX complication, as such I will close it as wontfix.
