### ISSUE TITLE
Adapt Currency to Language

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#210]
Currently, even though I use the German FlorisBoard, the currency-symbol on the first symbol-keyboard still is the dollar (`$`).
I think, it would be best to change this to `€`, at least in the case of German and a couple of other European languages.

It might be a good idea to do the same thing and adapt the currency for other languages. (`¢`, `¥`, `£`)...

Of course that would result in redundancy on the second symbol-keyboard. Meaning the keys there should also be adapted.

**Comment by patrickgold** [comment]
The idea is good and if I am not mistaken it has already been mentioned somewhere here, I think though that binding this to a specific subtype is not sufficient, as I often write English text on phones but still need the Euro symbol. So I will probably make subtype specific symbols (especially for Arabic, Russian, etc.) and decouple the currency keys to a separate preference.

**Comment by Glitchy-Tozier** [comment]
Sounds like a plan!

**Comment by MisterY** [comment]
I also use a different currency than what is the default for the language.
Consider also the case when multiple languages are in use. What would be the symbols used by default?
I normally have three languages active at all times. Moreover, I often type words in one language as a part of a conversation in another.

**Comment by patrickgold** [comment]
Above PR adds the ability to dynamically choose a "currency set" for each subtype. Each currency set consists of 6 currency symbols, which together fill all base character and popup slots both on the symbols and symbols2 layout. For each default subtype, I've also tried to find the best matching default currency set, which is pre-selected when adding a subtype (can be freely changed though). Will be released in v0.3.10-beta05 this weekend.
