### ISSUE TITLE
Excessive bottom padding

### ISSUE THREAD

**Issue by sevmonster** [florisboard/florisboard#2106]
#### Short description
I am not sure what triggered this issue, perhaps it was my upgrade to alpha04, or switching to gesture nav, but all the sudden my bottom padding is massive in landscape (with padding in options set to 0), and even worse with gesture nav:
![Screenshot_20221105-120355](https://user-images.githubusercontent.com/16788697/200133039-2f0cb78e-82b2-4423-a7f6-be510104c110.png)
![Screenshot_20221105-120437](https://user-images.githubusercontent.com/16788697/200133045-844db346-8b58-4a52-a3c6-4fd45090f2dc.png)

#### Steps to reproduce
1. Dunno yet

I cleared app data and the issue went away. Trying to recustomize to see if I can get it to reoccur.

#### Environment information
- FlorisBoard Version: 4.0-alpha04
- Install Source: GitHub
- Device: Google Pixel 6 Pro
- Android: 13 (GrapheneOS)

**Comment by sevmonster** [comment]
Been unable to reproduce, and in my hubris I did not think to export my old config. Hopefully someone else runs into this and can reproduce. Feel free to close.

**Comment by patrickgold** [comment]
This sounds like you enabled the bottom offset. If you go to Floris Settings > Keyboard > Layout > Bottom offset and set a value >0dp for landscape, the keyboard UI should look the the one on the screenshot, right?

**Comment by sevmonster** [comment]
If you look at the first screenshot, you can see it is already set to 0 for landscape. I adjusted it but it would just add/remove from what was already there.

**Comment by patrickgold** [comment]
> If you look at the first screenshot, you can see it is already set to 0 for landscape. I adjusted it but it would just add/remove from what was already there.

Ah I didn't see that, sorry for that.

What it could also be is that it is a state bug within the extended input layout, which was partially calculated but invisible. Could you try entering a text messaging field in landscape (e.g Signal, WhatsApp, etc.), and then going to a text field which does not have an extended landscape field? If the offset has magically appeared this could lead to the source of the bug.

Also normally force stopping FlorisBoard in App Info should be enough to get rid of this state bug once it has appeared.

**Comment by sevmonster** [comment]
I wasn't able to get it to happen again, including when switching between gesture nav and 2-button/3-button, nor when reinstalling alpha04. If it does I will try your suggestion to confirm if it is just a temporal issue.
