### ISSUE TITLE
Add negative padding in landscape

### ISSUE THREAD

**Issue by sevmonster** [florisboard/florisboard#2107]
Originally I was going to open this instead of #2106, but here we are.
With gesture nav selected, there is padding added to the bottom of the keyboard since gesture mav understandably breaks tradition of the nav cluster always staying glued to the true bottom of the screen and instead rotates with the phone. But that padding makes typing really difficult and the keyboard take up too much screen realestate. At least on my device, the gesture bar is really forgiving and the tap zone is actually quite small, so it would be safe to remove some of the padding without impacting too much. Allowing the user to customize this with negative bottom padding in landscape (if gesture nav or some other reason to have default padding is enabled) would be great.
![Screenshot_20221105-123359](https://user-images.githubusercontent.com/16788697/200133649-9f029957-1afe-43be-ab75-4ecfa48b6a6b.png)

**Comment by patrickgold** [comment]
Thanks for your feature request!

Sadly this is not possible, as the gesture nav bar is system real estate. I could theoretically draw there, but cannot at all receive touch events and thus such a feature sadly makes no sense. This is a security measure by the system to block apps from blocking system interaction areas.

As such I am closing your issue, hope you can understand.

**Comment by sevmonster** [comment]
So the point that it begins to draw at is the start of the system UI? If so that is really disappointing. I want to like gesture nav but it just takes up soo much space in landscape...
I anticipated this but thank you for clarifying anyway.
