### ISSUE TITLE
Native Issue

### ISSUE THREAD

**Issue by 26feb97shubham** [florisboard/florisboard#2109]
I am getting this error. Please help me out:

ninja: error: 'D:/Shubham_Jain/florisboard-master/florisboard-master/app/src/main/icu4c/prebuilt/jniLibs/arm64-v8a/libicuuc.a', needed by 'D:/Shubham_Jain/florisboard-master/florisboard-master/app/build/intermediates/cxx/Debug/6w6u95t2/obj/arm64-v8a/libflorisboard-native.so', missing and no known rule to make it

**Comment by tsiflimagas** [comment]
You have to checkout submodules running `git submodule update --init --recursive`

**Comment by Glitchy-Tozier** [comment]
@26feb97shubham Do you have any further questions or can we close this issue?
