### ISSUE TITLE
Hinted symbols dosnt work and shows only ńçß instrad of question mark or dash or plus

### ISSUE THREAD

**Issue by Triplesweet** [florisboard/florisboard#211]
No hinted symbol lile plus or question mark works
Ver 0.3.3 from github
LG Q6 android 7.1.1 stock
  

![Screenshot_2021-01-19-21-39-06](https://user-images.githubusercontent.com/77248142/105075513-15faf400-5a9f-11eb-9f64-4f30199c8030.png)
![Uploading Screenshot_2021-01-19-21-38-58.png…]()

**Comment by patrickgold** [comment]
Thanks for reporting this bug! I've just tested this on my device and was able to reproduce it in the latest version v0.3.3 as long as the hinted number row is disabled. Could you just confirm that the hinted popups would work if you enable the hinted number row?

**Comment by Triplesweet** [comment]
> Thanks for reporting this bug! I've just tested this on my device and was able to reproduce it in the latest version v0.3.3 as long as the hinted number row is disabled. Could you just confirm that the hinted popups would work if you enable the hinted number row?

yes. after enabling the hinted number row it did work again

**Comment by patrickgold** [comment]
Perfect, thanks for confirming! Will push a fix for this before v0.3.4 is released.

**Comment by patrickgold** [comment]
Above commit fixes the key hint bug. It was a simple copy paste error 😄 

Will be released this Wednesday or Thursday evening with the v0.3.4 release.
