### ISSUE TITLE
Add option to share image to florisboard

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#2112]
Most apps do not provide copy image,
![](https://i.imgur.com/IRcBOcj.png)

Even gallery apps and image editors such as simple gallery, aves, pocketpaint, do not have a copy image.
Only bromite does, in my apps list.

However, all apps have share, so we can extend the share to florisboard which in turn copies image to clipboard.

Currently, share mechanism does not have a copy for images themselves:
![](https://i.imgur.com/anblqdz.png)

![](https://i.imgur.com/6Fn8u7L.png)

It either shows the image or blank, but no option to copy,

**Comment by patrickgold** [comment]
That's a creative idea I must say, really like it :)

I don't know for sure if it is 100% possible but normally this should be absolutely implementable. Will assign it to the list of clipboard issues for now, cannot give any ETA when I (or someone else) will work on this.

**Comment by alensiljak** [comment]
What would be the point of sharing an image to a keyboard app?

There are already several "share to clipboard" apps one can use for the scenario mentioned here. Share is a common operation on mobile devices. Not to mention that clipboard is inherently unsafe (can be monitored by other apps).

**Comment by rancidfrog** [comment]
Fairemail supports pasting images inline.
I use it when I need to add an image inline in an email quickly without any hassle.
Florisboard already supports copying and pasting images.
As many other apps have yet to support copying images to clipboard, sharing to florisboard solves the limitation of other apps. So you can use copying and pasting images as user and keyboard already allows
