### ISSUE TITLE
Error when editing themes

### ISSUE THREAD

**Issue by notBradPitt** [florisboard/florisboard#2122]
I'm on the current latest version and got a bug and a crash when editing the theme.
First, the setting the colors to comma and full stop works in the editor then crashes when you try to exit. Second, trying to add font size to emoji key. It said that the same value already exists, setting the  shape for switch to emoji (utility?) button also doesn't work. Tried adding the value and doesn't show.

There should be more errors simijar to this, but I haven't checked yet.

**Comment by notBradPitt** [comment]
Update: Now trying to save an edit crashes the app

**Comment by tsiflimagas** [comment]
Thanks for your report. Generally, when reporting crashes, it's pretty much required to also post the crash log of it, so please update the issue with it.

**Comment by notBradPitt** [comment]
Thanks for your response. (Un)fortunately, I have been unable to replicate the issue after recreating the theme and is now working properly. I will make an update if I encounter this issu again. Thanks!
