### ISSUE TITLE
IF ME PRESS ENTER TO 3 SWITCHER TO EMOJI,CLIPBOARD,LOGO PHONE PLEASE DELETE feature 

### ISSUE THREAD

**Issue by MelisaTanaga** [florisboard/florisboard#2127]

**Comment by notBradPitt** [comment]
?

**Comment by MelisaTanaga** [comment]
That part is annoying when you press enter, the green color always appears, just delete it. There are also useless features like this, even though above there is already an option like that, so from here you understand what I mean, don't add weird and eccentric things, it's very uncomfortable.
![Screenshot_20221205-050548028~2](https://user-images.githubusercontent.com/115115645/205518428-fa074691-4a17-4f91-8e79-e659945013ef.jpg)

**Comment by tsiflimagas** [comment]
It's not weird nor eccentric, it's a useful function which provides accessibility. You probably have set a too low long key press delay so it to easy to trigger the popup.
