### ISSUE TITLE
One hand mode switchable direct on keyboard.

How about a function to switch between normal keyboard and one hand mode direct on keyboard. Maybe as an additional option on utility key.
I didn't find an option.
If it already exist please delete this request.

### ISSUE THREAD

**Issue by newbee2011** [florisboard/florisboard#2130]

**Comment by KLaurence** [comment]
May I ask what version you are currently on? In the recent alpha versions (available from the repo's [releases](https://github.com/florisboard/florisboard/releases)), there is a customizable top bar that has a button that allows you to toggle a one-handed keyboard.

**Comment by newbee2011** [comment]
Of course
I use 0.3.16(86) on Android 11

Am 8. Dezember 2022 14:34:33 MEZ schrieb KLaurence ***@***.***>:

**Comment by newbee2011** [comment]
I found the button to toggle on/off one-hand mode for keyboard. I am sorry for inconvenence you.

Am 8. Dezember 2022 14:34:33 MEZ schrieb KLaurence ***@***.***>:

**Comment by tsiflimagas** [comment]
There's also a popup button to switch to one handed mode when you long press the enter key.
Btw you generally have the rights to close issues you've opened yourself.
