### ISSUE TITLE
Clipboard: Add recetnly taken screenshot into smartbar

### ISSUE THREAD

**Issue by yarub123** [florisboard/florisboard#2143]
With the Samsung keyboard (and I'm sure others) after taking a screenshot, when you go to message someone (or open up the keyboard)....you get the option to paste the image right away. It would be located in the smart bar. 

On the current clipboard, whether you're using the system or the internal clipboard, whether it's synced or not, the screenshotted image does not show up at all. 

- Would be awesome to have it display in the smart bar right away.
- or at least have an option in the settings to enable or disable such a feature. 

Thanks a lot devs, we will continue supporting this project as best as we can and if we are able to. Because it deserves to be respected and supported ♥️

**Comment by tsiflimagas** [comment]
Thanks for your suggestion. It's already been suggested in #1761, so I'm closing this one.
