### ISSUE TITLE
[BUG] when using internal clipboard, clear primary clipboard clip doesn't clear system clipboard

### ISSUE THREAD

**Issue by l2eused** [florisboard/florisboard#2180]
#### Short description
when using internal clipboard, clear primary clipboard clip doesn't clear system clipboard

#### Steps to reproduce
1. open `Use internal clipboard` and `Sync from system clipboard` (disable `Sync to system clipboard`)
2. select example text and use cut/copy with system built-in (not on Florisboard)
3. press `Perform clear primary clipboard clip`
4. it's only clear internal clipboard but clip in system clipboard is still alive

Is it should clear system clipboard too? (I think it because I disable `Sync to system clipboard` but mostly user using `Perform clear` for clear primary clipboard in system app? because if you want to clear internal clipboard you can do it in clipboard manager tab)

#### Environment information
- FlorisBoard Version: 0.4.0-alpha04
- Install Source:  GitHub
- Device: Xiaomi MI9
- Android: 10

**Comment by lm41** [comment]
If you deactivate `Sync from system clipboard` and delete the primary clipboard entry of the internal clipboard, the system primary clipboard entry will of course not be deleted.
