### ISSUE TITLE
FlorisBoard now underlines every character or number typed until the space bar is pressed.

### ISSUE THREAD

**Issue by muchuelo** [florisboard/florisboard#2184]
#### Short description
FlorisBoard now underlines every character or number typed until the space bar is pressed.

#### Steps to reproduce
Start typing.

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: GitHub
- Device: Huawei P10
- Android: 10, Stock

I've just updated FlorisBoard from v0.3.13 to v0.3.16. I have an issue with a new 'quirk'. I'll begin with a short description of this bug (or is it a 'feature'?) and end with a more verbose positive general commentary...

Unfortunately I have a gripe with something FlorisBoard does now which it didn't do before...

FlorisBoard now underlines every character or number typed until the space bar is pressed. It's very irritating. It does it in my notes app, browser address bar - anywhere I type.

I've been through the entire array of configuration options and can find no way to change this new behaviour. I have read the release notes carefully, and I suspect this might perhaps be related to the new option to be able to choose between deleting single characters or whole words (I'm sticking to deleting single characters for now) but I might be wrong.

Can you please fix this bug -- or if it's a 'feature' then add an option to disable it.

---------------------------------------------------

... Now some positive commentary directed to the developer. (I hope I'm not breaking 'Issue' posting rules by adding this, but where else is there to comment in general?)

FlorisBoard is by far the best Android keyboard I've ever seen or used (and I tested lots of different keyboards before I found FlorisBoard). I've been using it right from its early days. I love the layout design, the way it looks, and its great functionality. Also the fact that it is very focused on privacy/security is of paramount significance. It's a work of art. (Talking of art, I was also struck by the beautiful new icons - so much so, I spent quite some time browsing the gallery/portfolio of the creator. Very nice work indeed). Keep up the good work.

**Comment by KLaurence** [comment]
It should be fixed on the 0.4.0-alpha versions in the [Releases](https://github.com/florisboard/florisboard/releases) page.

**Comment by muchuelo** [comment]
Ok. I'm fine with beta testing but I don't usually get into alpha testing. I'll make an exception in this case.

**Comment by muchuelo** [comment]
Thanks

**Comment by KLaurence** [comment]
No problem.

**Comment by moonbeamcelery** [comment]
The underline is part of the typing suggestion, which is undergoing development recently. It shows the composing region, i.e. the part that is subject to change with autocorrect and suggestion. 

If you do not want this behavior for now (it does not work right now anyway), you can disable suggestions in the settings. However, with the next few updates the autocorrect and suggestion will be implemented, and you will have to tolerate the underline if you want those to work.

**Comment by muchuelo** [comment]
Thanks for the info. I have now updated to 0.4.0 alpha04 and am totally impressed. I've got the smartbar arranged exactly how I want it now.

Re the underlining ... I have Suggestions deactivated and the distraction of the underlining has gone, as you indicate. The Suggestions feature is, as I see it,  essentially a time saving feature, but I am rarely in a hurry when I'm typing, so it's not a feature I will likely ever use, but I will probably try it out at some point, just out of curiosity when I see reports that it's reached a mature stage of development. 

In the past I've received a lot of very garbled text mesages from people who, when I reply saying "say what?" (because I just couldn't understand what they were trying to say) the usual response from them was "Oh, the keyboard typed it on its own". I noticed that alnost all of the garbled messages were coming from people I knew were iPhone users, but the number of garbled messages has dropped recently, so it seems perhaps iPhone has improved its keyboard suggestions. (Of course the real problem is that these people don't read what they've typed before hitting the Send button, but hey, I'm old school).

Either way, I can appreciate how the Suggestions feature will likely be a powerful tool in the right hands.

Best of luck with the development.

**Comment by bastiiiii** [comment]
Oh I mentioned this as well but after a while I thought, what a nice feature 😅.
Comming to the request: Possible to add it as a toggle option?

**Comment by KLaurence** [comment]
In the latest alpha (0.4.0-alpha04), word underlining is tied to the suggestions toggle (#1911, `Settings > Typing > Display suggestions`). You can create a feature-request issue if you desire a suggestions-independent toggle.

**Comment by BlastboomStrice** [comment]
I had the same issue today, but I found out my phone's spell-checker was on for some reason (it may be that I deleted the data from gboard and resetted something). Try these steps to fix it:

Go to settings->typing
- If it is disabled, there should be a red banner saying spelling is disabled. Try tapping on it, turn spell checking on and then off.
![florisboard-spellcheker](https://github.com/florisboard/florisboard/assets/65232133/5fc4425c-07fc-470d-8689-a2ca93f4819d)
![florisboard-spellcheker4](https://github.com/florisboard/florisboard/assets/65232133/74b5fa19-03d4-4be5-8083-95db4dc1cf40)
![florisboard-spellcheker2](https://github.com/florisboard/florisboard/assets/65232133/39d87d0b-2d1e-4af1-847d-fc59fc678936)

- If it is enabled, it should show you a button with the spell-checker currently used. Tap on it, it will take you to the appropriate settings and then you can disable it. (If it shows it is disabled in the window that pops-up, just turn it on and off.)
![florisboard-spellcheker3](https://github.com/florisboard/florisboard/assets/65232133/441b5fdf-9c87-46b6-8179-168a7c290920)

In my device I have now disabled gboard, so even if I have spell checker on, there is no line underneath anymore.

**Comment by muchuelo** [comment]
Closing now, as this stopped being an issue ever since I updated to 0.4.0-alpha04.

**Comment by BlastboomStrice** [comment]
> Closing now, as this stopped being an issue ever since I updated to 0.4.0-alpha04.

Could we possibly re-open this?

As per the latest update 0.4.1 (99), when I type in text bars (like in messenger apps), my text is underlined, until I press enter. I have suggestions, spell checking and smartbar disabled and I even tried clearing the data of the app. I'm providing a screenshot of the issue from the testing area inside the app:
![Screenshot_2024-10-15-09-58-17-804_dev patrickgold florisboard beta_1](https://github.com/user-attachments/assets/4c07a291-c568-46e3-8bf3-cb16b9ef9e3f)

**Comment by lm41** [comment]
Is it possible that emoji suggestions are enabled?

Settings → Emojis → Emoji suggestions

**Comment by BlastboomStrice** [comment]
Thank youu :)
I think this was added very recently and didn't think about checking it. Thanks again.
