### ISSUE TITLE
The input method is selected via 3 methods. Is this necessary?

### ISSUE THREAD

**Issue by albotroz** [florisboard/florisboard#2187]
FlorisBoard 0.3.16
LineageOS 20 (Android 13) + MindTheGapps 13.0.0

I have not yet found a setting to adjust this to my needs.

It is possible to select the input method via 3 options. Via Florisboard you can at least switch off the upper column and thus also the symbol for the input method (see 1).

But then there is still the icon at the bottom right (2). 
![Screenshot_20230403-134847_FlorisBoard](https://user-images.githubusercontent.com/67508404/229509363-be3f4955-0ff3-4344-ad99-90c7c7dcdb40.png)
And additionally it is still possible to call the input method via the icon (3 - long press).
It would be better if you could only call the input method via a selection (e.g. icon 3 - long press or instead only via icon 2).

All in all, it is currently possible to select the input method via 3 choices. But this is not necessary and only inflates and confuses everything.

**Comment by bastiiiii** [comment]
I don't know if it will fix your issueor it is an option for you.
I disabled all other input methods/ keyboards in the system settings. This removed the at least 1 and 2.
Also the 3 was possible to cut. But therefore I added my personal keymap - which took me a while to get the debug version compiled. I totally reworked the symbol 1 and 2 pages - especially symbol2 is used for a preset of emojis.
If you are interested I can provide the apk in my fork.

**Comment by patrickgold** [comment]
alensiljak described what each method does and why pretty well and also brings up some other facts I have to agree. On most modern keyboards you simply have such a button integrated into the keyboard UI. The button in the Settings UI is also here for quick switching keyboards for testing purposes.

If you really wanna disable these buttons, here are the options for each one:

- Method 1: You can't. As this button is only present in the preview UI of the Settings interface I think that is fully acceptable.
- Method 2: This is a system interface UI which FlorisBoard does not have control over. Some manufacturers allow disabling it, some don't. On my OnePlus I can disable it by going to "System Settings > System Settings > Keyboard & input method > Keyboard location > Show input methods button" (Or simply hide the whole bar by selecting Hide). Like said on your phone this could be an entirely different option or simply not present.
- Method 3: Go to "FlorisBoard Settings > Keyboard > Show utility key" and toggle it off

For me there isn't anything else to do here, so I will close this issue as wontfix.
