### ISSUE TITLE
Request to add the letter ç to the layout of the Brazilian version of the keyboard

### ISSUE THREAD

**Issue by Neiyr** [florisboard/florisboard#2188]
I'd like to ask about the possibility of adding the letter ç to the Brazilian version of the keyboard, as in to the right of the letter L, instead of having to hold the C character every time.

**Comment by tsiflimagas** [comment]
Thanks for your suggestion! This is actually a duplicate of #1939, and as noted there, this layout is already available as Catalan (QWERTY), which just may not be the most obvious name for most users
