### ISSUE TITLE
Brackets (< and >) extended popups

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#219]
Brackets usually have some extended popups, could you add them to FlorisBoard?
Usually these popup symbols are both in brackets and on other keys (some of these are already on other keys in FlorisBoard but they should also be in brackets).
The symbols are:

- Left bracket (`<`): `‹`, `≤` and `«`
![left-bracket](https://user-images.githubusercontent.com/24703825/105425973-132c0a80-5c29-11eb-962f-cff9d20b6322.jpg)

- Right bracket (`>`): `›`, `≥` and `»`
![right-bracket](https://user-images.githubusercontent.com/24703825/105425018-47063080-5c27-11eb-834e-8b3e96a63fde.jpg)

**Comment by patrickgold** [comment]
Thanks for the suggestion! Will place this on my todo list for v0.3.5, as it is easy to add.

**Comment by patrickgold** [comment]
Above commit c74a5841eca2a6ca324db23a69012e5a7fe2299b adds your suggested popups as well as an extra one Gboard seems to have added recently. Will be released today evening with v0.3.5.
