### ISSUE TITLE
[Suggestion] Default templates on GitHub Issues.

### ISSUE THREAD

**Issue by marchingon12** [florisboard/florisboard#22]
Make the default template for feature requests like this:

Title: [Request/Bug/Suggestion/Question]

Issue post:

```markdown
<!-- 
- Describe your idea in a short but concise way. 
- If you have multiple ideas which are not directly connected to each other, file an issue per idea. This makes it easy to implement one feature proposal at a time. 
- If you have any examples, e.g. screenshots or other keyboards which have the proposed feature implemented, link them here.
Thank you for your help in making FlorisBoard better! -->
```

Including the comment tags, if that wasn't clear. 

Florisboard seems promising, I hope for a great future development! 👍🏽

**Comment by patrickgold** [comment]
Thank you for your suggestion, your issue made me think about my default issue templates.

Personally I do not like putting tags into the title, that's what labels are for. As for bugs, there is already a separate issue template with a much more detailed process on what to fill in (I will probably simplify it because the current bug report is little bit bloated).

My current setup on default issue templates is:
Bug report - for things like exceptions, crashes, unexpected behaviors, etc.
Feature request - for suggestions + features wanted
Free form - for everything else

It seems like there is need for a third template:
Question - a question about an implemented feature or if the issuer needs help in using FlorisBoard

Your idea for putting the instructions on what to write in comment tags is pretty good, I will definitely add these.

One last thing: I've seen that you distinguish between feature request and suggestion - for me, there is a blurry line between these two, so I group them with the proposal label (feature request template).

**Comment by marchingon12** [comment]
Thanks for taking note on my proposal. 

> Personally I do not like putting tags into the title, that's what labels are for. As for bugs, there is already a separate issue template with a much more detailed process on what to fill in (I will probably simplify it because the current bug report is little bit bloated).

Putting tags in the title is just a personal preference, it just helps me quickly differentiate what issues are posted, since it's at the start of the title and not at the end 👍🏽, not a big deal if it isn't changed :D 

>My current setup on default issue templates is:
Bug report - for things like exceptions, crashes, unexpected behaviors, etc.
Feature request - for suggestions + features wanted
Free form - for everything else

The current template setup is alright, I would suggest adding:
- Device name, android version, logs on deldog or hastebin and other elements if that could help with bug reporting.
- Feature requests are good enough I think.
- Free form is standard so nothing to change here.
- For Questions you could also name, quote, "...issuer needs help in using FlorisBoard" to "general questions" about Folrisboard in addition to implemented features.

> One last thing: I've seen that you distinguish between feature request and suggestion - for me, there is a blurry line between these two, so I group them with the proposal label (feature request template).

I see. For me, suggestions are more towards the direction of suggesting improvements to the current code or important fixes to be made that you may not have seen. Feature requests are solely for requesting new features and not making suugestion to amend current features. This is, again, only a personal preference.

I'd also add some labels, for example priority labels: priority-high/low, 
Other useful labels: feedback (for feedback), to-do (currently in the to-do list), completed (finished and is going to be in the next release).

Hope this helped further!

**Comment by patrickgold** [comment]
Thank you for your detailed response.

I've just pushed an update to the issue templates. It would be super helpful for me if you could look over the changes and if I could improve them somewhere. Thanks!

> I see. For me, suggestions are more towards the direction of suggesting improvements to the current codebase or important fixes to be made that you may not have seen. Feature requests are solely for requesting new features and not making suugestion to amend current features. This is, again, only a personal preference.

I see why you distinguished those two now. But still, I am almost certain that there would be confusion in the future whether to use the suggestion or feat-request template / label, so I will stick with the proposal label, which houses both. Also, when looking through the issue list, I want to see at a glance what new ideas are wanted. But like you said - its only a personal preference. 😄 

> I'd also add some labels, for example priority labels: priority-high/low,

This is an excellent idea which I will definitely consider using in the future, especially with bug reports.

> Other useful labels: feedback (for feedback), to-do (currently in the to-do list), completed (finished and is going to be in the next release).

Don't know if I will use these labels, but they sound useful and I will keep them in my mind. As for the feedback label, I'm not sure if I should add a template for it or if general feedback should only be given outside of this repo's issue manager (e.g. by using the review function on Google Play).

Thanks for your suggestion & response, this really helped me in improving the issue management for this project!

**Comment by marchingon12** [comment]
You're very welcome, I love the fact the project is open source and that someone is motivated to do it, so let me thank you as well!

> I've just pushed an update to the issue templates. It would be super helpful for me if you could look over the changes and if I could improve them somewhere. Thanks!

I will indeed! If you need any other help regarding something like this, contact me right away (you'll see some links on my GitHub profile :D)

> Don't know if I will use these labels, but they sound useful and I will keep them in my mind. As for the feedback label, I'm not sure if I should add a template for it or if general feedback should only be given outside of this repo's issue manager (e.g. by using the review function on Google Play).

I mentioned the feedback label as, as far as I know, the majority of people who I know that know about florisboard (this may be just me) or recommend it as an alternative to anysoftkeyboard are from open source related groups, who aren't a fan of Google Play. Since F-Droid doesn't have any review function, their only choice is either either through GitHub or, as you said, through the review function on the Play Store. 
Thus, I also would suggest opening a Telegram channel and group, if that may help. I'm still in many open source groups on Telegram today, and I'd more than be happy to help setting up the group if you'd like.

**Comment by patrickgold** [comment]
Thanks for reviewing the issue templates, I really appreciate it!

> I mentioned the feedback label as, as far as I know, the majority of people who I know that know about florisboard (this may be just me) or recommend it as an alternative to anysoftkeyboard are from open source related groups, who aren't a fan of Google Play. Since F-Droid doesn't have any review function, their only choice is either either through GitHub or, as you said, through the review function on the Play Store.

You make a good point here - I didn't really think about the fact that F-Droid does not have any review function and that my current target group is very privacy-oriented and thus doesn't use Google Play.

> Thus, I also would suggest opening a Telegram channel and group, if that may help. I'm still in many open source groups on Telegram today, and I'd more than be happy to help setting up the group if you'd like. Having many options to choose from is generally good for the user, but for maintaining groups and support on different platforms, you may need some moderators.

I haven't used Telegram at all tbh, so I have zero experience in it. Like you said, as these groups grow, I may need some moderators and manage all the different places- I just don't feel ready to do this step yet. Regarding your offer in helping me setting up such a group (which I really really appreciate!!) - Would it be okay for you if I come back to you at a later stage to discuss this topic?

For now, I will use this projects email address as an alternative feedback option.

Thanks again and have a nice evening!

**Comment by marchingon12** [comment]
> I haven't used Telegram at all tbh, so I have zero experience in it. Like you said, as these groups grow, I may need some moderators and manage all the different places- I just don't feel ready to do this step yet. Regarding your offer in helping me setting up such a group (which I really really appreciate!!) - Would it be okay for you if I come back to you at a later stage to discuss this topic?

Absolutely! I'll be glad to help if the time for it comes. 

And using the email address as the feedback option was a good move :D
