### ISSUE TITLE
Request: Add early beta/alpha versions to F-Droid too.

### ISSUE THREAD

**Issue by navid-zamani** [florisboard/florisboard#2203]
Adding beta/alpha versions to F-Droid (marked as such, so that only users who have “unstable updates” enabled get them) would be quite welcome, by the way. At least until 1.0 is released.

The version there is quite old, and I was already about to file several bugs, when I found that they had already been posted, and people were told to upgrade to the latest alpha/beta.

The problem with installing versions manually, is that they aren’t updated AFAIK, so as soon as one does that, it’s becoming a permanent assignment that one has to create a reminder for and all.

P.S.: The project is already really nice, for being is such an early stage. You’re quickly becoming more popular on alternativeto.net! :)

**Comment by BHydden** [comment]
Use the izzy on droid repo

**Comment by tsiflimagas** [comment]
Pretty much, it's what @BHydden said. For more, read the discussion in #1896, of which this is a duplicate. Thanks for your suggestion anyway!

**Comment by navid-zamani** [comment]
Wow, I literally searched first to avoid creating a duplicate. ^^

I’m sorry. I don’t know what went wrong.

Thanks for the quick response anyway. :)
