### ISSUE TITLE
saved clipboard not exported with backup

### ISSUE THREAD

**Issue by theotheroracle** [florisboard/florisboard#2204]
#### Short description
a full export and import of settings doesn't copy saved clips

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: fdroid
- Device: terracube emerald
- Android: /e/OS 1.10-s

**Comment by tsiflimagas** [comment]
I'd call this a suggestion rather than a bug, since that's how it is intended to work currently. There's already an issue for the same request though, so let's close this one to keep the section tidy.
