### ISSUE TITLE
Emoji Page not showing up

### ISSUE THREAD

**Issue by smolpando** [florisboard/florisboard#2208]
When opening the emoji page through the emoji button next to the keyboard, it just shows a blank page with the background color and nothing else.

Os: android 11

**Comment by FrostyNick** [comment]
Do you have the tabs on the emoji keyboard? That's where they should be if everything is working properly. The background is blank if you've never used any emojis on the first tab.
<details><summary>Screenshot of tabs in emoji keyboard</summary>

![image](https://github.com/florisboard/florisboard/assets/57016218/dd6901d5-ddf5-4eaa-8dba-111cbfaf6e13)

</details>

**Comment by smolpando** [comment]
They were there as far as I know but when i tapped on the normal emoji
button the screen was still black.

**Comment by tsiflimagas** [comment]
I guess you made your own theme, or edited an existing one and you did some mistake in how the emoji tab is coloured so emojis are there but they have the same colour as the background. Try one of the default themes to see if emojis appear properly.

**Comment by tsiflimagas** [comment]
No problem! I guess that's solved now.
