### ISSUE TITLE
Chinese (pinyin) input support

### ISSUE THREAD

**Issue by du82** [florisboard/florisboard#2211]
It would be great to have pinyin support in Florisboard. Trime is an open-source keyboard that supports it, but it's slow and doesn't work on expandable text boxes, which means it won't work with most messaging apps.

I'd recommend using the rime prediction algorithm, as its open source and reasonably fast.

**Comment by tsiflimagas** [comment]
Thank you for your suggestion! It seems that this has been already suggested in #149, so let's keep that one to track this suggestion.
