### ISSUE TITLE
Option to change keyboard size for normal and one-handed mode

### ISSUE THREAD

**Issue by qdlmcfresh** [florisboard/florisboard#2212]
Distinguish between the modes and allow to set e.g. a height for one-handed and for two-handed

**Comment by Glitchy-Tozier** [comment]
Are you aware this mode exists? You can enter it by long-pressing the enter-key or the comma-key.
![Screenshot_20230511-100233_FlorisBoard Beta.jpg](https://github.com/florisboard/florisboard/assets/59611881/b106581d-2b2f-4558-9c32-c38a65a0f758)

![Screenshot_20230511-100308_FlorisBoard Beta.jpg](https://github.com/florisboard/florisboard/assets/59611881/c978ae1d-19b6-4c98-a1d5-4e490ee25b47)

![Screenshot_20230511-100259_FlorisBoard Beta.jpg](https://github.com/florisboard/florisboard/assets/59611881/d5e4d49f-241f-4303-b5ca-bdad7d43e0db)

![Screenshot_20230511-100448_GitHub.jpg](https://github.com/florisboard/florisboard/assets/59611881/1997935d-6131-4490-86fc-9d58b161c80c)

**Comment by qdlmcfresh** [comment]
![WhatsApp Image 2023-05-11 at 13 02 09](https://github.com/florisboard/florisboard/assets/10837173/ad647c4c-b6b0-4a70-8672-27d923ea0e3c)
I'm aware a one-handed mode exists. But the options in the screenshot affect both, one-handed and two-handed mode.
I thought it might be useful to have different settings for both modes.
Maybe i should have been clearer on that, sorry.
