### ISSUE TITLE
Improving the usability of Theme Editor for non-advanced users

### ISSUE THREAD

**Issue by Triplesweet** [florisboard/florisboard#222]
Thats about it :)

**Comment by patrickgold** [comment]
Thanks for your issue! It reminded me that I forgot to add the wiki page link to the theme editor 🤦 . Will do this in v0.3.5 then... 

This is the theme editor wiki entry, where it is explained how you can achieve exactly what you are asking for: https://github.com/florisboard/florisboard/wiki/Using-the-new-Theme-Editor

Note, that the minimum required version for this is v0.3.4 (as in v0.3.3 I messed up with input validation). Let me know if this helps or if you have any improvement suggestions for the wiki entry!

**Comment by Triplesweet** [comment]
@patrickgold thanks for the link.
And i have a small proposal. What about making 2 theme editor. Basic and advanced. In basic we can change very basic things like background and key colours and text colour and stuff in advanced we can have all possible things. 

Because even tho it was (the wiki) was clean and explained alot, most people wont changed the default more than some extent and will not like how complocated it seems.

**Comment by patrickgold** [comment]
Well the theme editor can already be used in basic mode by creating a theme from the selected and then just changing the desired colors. If you want to have custom styles for shift, delete, whatever, this already counts as advanced for me. I tried to make the theme editor UI and UX as simple as possible and as long as you base your theme off a pre-configured one, there should not be a problem using it without having read the wiki page.

**Comment by patrickgold** [comment]
What I can do though is the following: I still have the string resources for the old theme Settings (at least the attribute and group names). So as long as an attribute or a group has a standardized name, I will display the localized string instead the English attribute name. This way editing the theme seems more natural and easier for some. When opening the group or attr viewer, you will still be able to modify the original raw name.

**Comment by Triplesweet** [comment]
@patrickgold to be honest i havnt been using it for a long time so i dont know how the old theme editor was.
But if you think it was easier then im down with it

**Comment by patrickgold** [comment]
@Triplesweet I am at least trying to make the user feel more comfortable using the new Theme Editor by this change. I will keep you updated with how this change looks!

**Comment by patrickgold** [comment]
@Triplesweet above PR is an attempt at improving the theme editor, I also provided comparison screenshots. The changes will be released today evening together with v0.3.5.
