### ISSUE TITLE
Simplify the creation of layout

### ISSUE THREAD

**Issue by GrimPixel** [florisboard/florisboard#2226]
In the ideal situation, if one wants to add a layout, he/she can simply add a JSON file to that folder and there is no need to add it into those two “extension.json” files, with all the metadata in the layout's JSON file. They can be detected automatically.

**Comment by patrickgold** [comment]
Thanks for your suggestion!

There's a reason why there's an extension system - to standardize the packaging of dynamic content for FlorisBoard. Layouts worked exactly like you suggested in the early days of FlorisBoard - however that's not future-proof, as layouts are more than a simple json file. For some layouts you require special modifiers, different popup mappings, and I also plan that the user can choose a background picture, which would not be feasible to put into a json file.

I agree that some parts of the layouting may be clunky a little bit counter-intuitive, however with time we will get there, just that I will continue using the extension system I built. As such I will reject your proposal, hope you can understand.
