### ISSUE TITLE
iOS emoji

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#2236]
hi i know this are FOSS but it's likely android system emoji looks ugly as heck 

i recommend to use iOS emoji style for florisboard as other emoji style are not good as iOS 

thank you for consideration 🙏

**Comment by Glitchy-Tozier** [comment]
I agree that an emoji-rework would be a good idea.  If I'm not mistaken, the emojis Twitter/Telegram use are open-source (and look great), so that might be an option as well.

**Comment by kadisonm** [comment]
I would also like to switch emoji packs. Maybe offering a choice between iOS, the current and twemoji would be nice.

**Comment by obakha** [comment]
I second this.

**Comment by lm41** [comment]
Duplicate of https://github.com/florisboard/florisboard/issues/1965
