### ISSUE TITLE
Project is not building

### ISSUE THREAD

**Issue by souravsoftwareer** [florisboard/florisboard#2238]
Task :prepareKotlinBuildScriptModel UP-TO-DATE
Checking the license for package CMake 3.22.1 in /Users/john/Library/Android/sdk/licenses
License for package CMake 3.22.1 accepted.
Preparing "Install CMake 3.22.1 (revision: 3.22.1)".
Warning: Failed to read or create install properties file.

**Comment by souravsoftwareer** [comment]
![Screenshot 2023-06-09 at 5 40 35 PM](https://github.com/florisboard/florisboard/assets/8158259/f45dc514-8574-49ed-81de-c6e20ccee432)

**Comment by tsiflimagas** [comment]
From a quick search I found [this](https://stackoverflow.com/questions/43042032/android-studio-fails-to-install-update-error-failed-to-read-or-create-install). What I suppose has happened is that when you installed Android SDK tools you were running as root, so now that you're running as user, Android Studio doesn't have the permission to write to that directory. So, running `sudo chown -hR $USER $ANDROID_HOME` might fix it.

**Comment by souravsoftwareer** [comment]
![Screenshot 2023-06-09 at 6 05 29 PM](https://github.com/florisboard/florisboard/assets/8158259/7b026dc1-d8c0-4ae0-b2aa-33e889c60962)
Now getting this one

**Comment by tsiflimagas** [comment]
I see. This is fixed in https://github.com/florisboard/nlp/pull/6/commits/881966f8e86ff6c047f888dfc5396e05001a071e but I'm not sure what's the right way to use it. Maybe change the nlp submodule with the hash of this commit in `app/src/main/cpp/nlp` and update submodules.

**Comment by souravsoftwareer** [comment]
See i have added submodules already still same issue

![Screenshot 2023-06-09 at 7 22 39 PM](https://github.com/florisboard/florisboard/assets/8158259/2b9a3844-1d94-4cbd-8b56-ffde3ff1bfa5)

**Comment by souravsoftwareer** [comment]
Now that error resolved but getting new one

![Screenshot 2023-06-09 at 7 30 56 PM](https://github.com/florisboard/florisboard/assets/8158259/40688482-7b8d-49b7-9888-cc10e48cd1cb)

**Comment by souravsoftwareer** [comment]
-- Configuring done (0.1s)
CMake Error in icuext/src/CMakeLists.txt:
  The "fl_icuext" target has C++ module sources but its experimental support
  has not been requested


CMake Error in nlpcore/src/CMakeLists.txt:
  The "fl_string" target has C++ module sources but its experimental support
  has not been requested


CMake Error in nlpcore/src/CMakeLists.txt:
  The "fl_utils" target has C++ module sources but its experimental support
  has not been requested


CMake Error in nlpcore/src/CMakeLists.txt:
  The "fl_nlp_core" target has C++ module sources but its experimental
  support has not been requested


CMake Error in nlpcore/src/common/CMakeLists.txt:
  The "fl_nlp_core_common" target has C++ module sources but its experimental
  support has not been requested


CMake Error in nlpcore/src/latin/CMakeLists.txt:
  The "fl_nlp_core_latin" target has C++ module sources but its experimental
  support has not been requested


CMake Error in nlptools/src/common/CMakeLists.txt:
  The "fl_nlp_tools_common" target has C++ module sources but its
  experimental support has not been requested


CMake Error in nlptools/src/core_ui/CMakeLists.txt:
  The "fl_nlp_tools_core_ui" target has C++ module sources but its
  experimental support has not been requested


CMake Error in nlptools/src/prep/CMakeLists.txt:
  The "fl_nlp_tools_prep" target has C++ module sources but its experimental
  support has not been requested


CMake Error in nlptools/src/train/CMakeLists.txt:
  The "fl_nlp_tools_train" target has C++ module sources but its experimental
  support has not been requested


-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by tsiflimagas** [comment]
Uh, I think I'm running short on ideas. I've actually no idea on cpp and build systems for it (well, I'm not a dev), I'm just searching on the internet. Is Ninja 1.10+ installed on your system?

**Comment by tsiflimagas** [comment]
I don't know what distro you're using. You can search it yourself though about your specific distro. For example, on Ubuntu you'd run `sudo apt-get install ninja-build`.

**Comment by Glitchy-Tozier** [comment]
I haven't read this too in-depth, but could it be related to #2218?

**Comment by tsiflimagas** [comment]
Partly yes, the error about not finding `gmake` specifically. But, in general, it seems to be an issue with the user's system setup and not complying with the requirements to build `nlpcore`.

**Comment by patrickgold** [comment]
Thanks for your bug report!

This issue is indeed related to #2218.

@souravsoftwareer You can try out the following (commands are for Linux systems):
1. `git clone https://github.com/florisboard/florisboard.git`
2. `cd florisboard`
3. `git submodule update --init --recursive`
4. `cd app/src/main/cpp/nlp`
5. `git checkout origin/rework-cmake-configuration`
6. Now try building the project (refresh the Gradle/CMake cache though), it should include my latest patches to the build system

Also make sure you generally have the requirements installed, else the build will fail.

**Comment by souravsoftwareer** [comment]
Can you please check this i have followed all steps but still getting issue. I think issue in clang i am using MAC OSX Ventura 13.3.But calng is installed clang version is shown in screenshot


![Screenshot 2023-06-12 at 10 53 48 AM](https://github.com/florisboard/florisboard/assets/8158259/9e9bb3d8-731a-4eb9-8fc0-13303c3bcdcd)

![Screenshot 2023-06-12 at 10 56 25 AM](https://github.com/florisboard/florisboard/assets/8158259/09616040-2067-4168-8744-8fcbd514adcb)

**Comment by souravsoftwareer** [comment]
I got this error when i try to run following error
cmake --preset=release .

**Comment by souravsoftwareer** [comment]
Above issue is resolved for command 

cmake --preset=release .

But when i running following command |

cmake --build --preset=release giving me error please check screenshot attached

![Screenshot 2023-06-12 at 7 40 58 PM](https://github.com/florisboard/florisboard/assets/8158259/0515ad64-6475-444b-885b-4e4b9a4049e2)

**Comment by souravsoftwareer** [comment]
@patrickgold can you please suggest me what to do on this ?

**Comment by patrickgold** [comment]
@souravsoftwareer whats the contents of "{projectdir}/build/release/icu4c/.intermediate/host"? Often times this file points to more details of why the ICU script refuses the compilation

**Comment by souravsoftwareer** [comment]
build is failed i am not having such file path in project

**Comment by patrickgold** [comment]
The file should be in this dir:

![image](https://github.com/florisboard/florisboard/assets/19412843/ccc6a400-82dc-4cc9-ad9a-91310f6844a5)

**Comment by GoRaN909** [comment]
> The file should be in this dir:
> 
> ![image](https://user-images.githubusercontent.com/19412843/249292198-ccc6a400-82dc-4cc9-ad9a-91310f6844a5.png)

What about Windows 11 ? please I need some help here.

**Comment by patrickgold** [comment]
> What about Windows 11 ? please I need some help here.

Isn't supported natively (see [system requirements](https://github.com/florisboard/nlp#system-requirements)), however you can either dual-boot with Linux, run a VM or use WSL2 (I strongly recommend WSL2 as it is from Microsoft officially and Windows 11 has excellent support and easily installation for it, after installation it integrates almost seamlessly into Windows).

**Comment by souravsoftwareer** [comment]
[config.log](https://github.com/florisboard/florisboard/files/11890331/config.log)

This is the log file you can check this out i have macOSX 13.3 (22E252)

**Comment by GoRaN909** [comment]
> > What about Windows 11 ? please I need some help here.
> 
> Isn't supported natively (see [system requirements](https://github.com/florisboard/nlp#system-requirements)), however you can either dual-boot with Linux, run a VM or use WSL2 (I strongly recommend WSL2 as it is from Microsoft officially and Windows 11 has excellent support and easily installation for it, after installation it integrates almost seamlessly into Windows).

Thanks for the guide I just installed Ubuntu 22.04 with WSL2 but it's only shows in the terminal design to run commands! Is there any tutorial how can I install full OS GUI just like when running the windows 11

![Screenshot 2023-06-29 025130](https://github.com/florisboard/florisboard/assets/3160786/d1957fd8-8f82-4f7e-8118-7c5446669085)
![Screenshot 2023-06-29 032320](https://github.com/florisboard/florisboard/assets/3160786/ca314482-4880-41ae-95be-1e4085c4f1fa)


I followed this [Install Desktop GUI for WSL](https://www.youtube.com/watch?v=QC7a9nowsz8) and do same like that but still shows in the terminal screen not the UbuntuOS desktop GUI!

**Comment by androider-wang** [comment]
> 

same.

Apple M1 Pro
13.4.1 (c) (22F770820d)

**Comment by androider-wang** [comment]
> [config.log](https://github.com/florisboard/florisboard/files/11890331/config.log)
> 
> This is the log file you can check this out i have macOSX 13.3 (22E252)

same.

Apple M1 Pro
13.4.1 (c) (22F770820d)

**Comment by SZTSIIT** [comment]
> > [config.log](https://github.com/florisboard/florisboard/files/11890331/config.log)
> > This is the log file you can check this out i have macOSX 13.3 (22E252)
> 
> same.
> 
> Apple M1 Pro 13.4.1 (c) (22F770820d)

Same. 

Apple M2 Pro

**Comment by lm41** [comment]
The C++NLP core is going to be replaced by a rust module.
