### ISSUE TITLE
Textbox fills screen and Smartbar shrinking

### ISSUE THREAD

**Issue by w0nd3r365** [florisboard/florisboard#2240]
#### Environment information
- FlorisBoard Version: 0.4.0-alpha04 (90)
- Install Source: F-Droid
- Device: Samsung Galaxy Tab A7 (10.4 inch screen)
- Android: 11

#### Bugs description
- When I try to type in apps while in landscape mode on a tablet, textbox fills screen. Back swipe navigation gesture doesn't work when this happens, only the home swipe gesture works. Then I relaunch the app from recents screen.

![image](https://github.com/florisboard/florisboard/assets/97921087/609ae3a3-63b9-4ee6-a016-dc5eab640e9d)
 
- Smartbar shrinks in size when decreasing vertical height of keyboard, making its icons very small. To fix this perhaps a resize smartbar option?

![image](https://github.com/florisboard/florisboard/assets/97921087/695ee64f-ab89-4136-9b34-086cb1ab31c3)

**Comment by Glitchy-Tozier** [comment]
Again, please take one of these bullet-points and move it to a separate issue. This makes it easier to tag, discuss and fix your issues. Thank you.
