### ISSUE TITLE
Textbox fills screen

### ISSUE THREAD

**Issue by w0nd3r365** [florisboard/florisboard#2242]
#### Environment information
- FlorisBoard Version: 0.4.0-alpha04 (90)
- Install Source: F-Droid
- Device: Samsung Galaxy Tab A7 (10.4 inch screen)
- Android: 11

#### Bugs description
When I try to type in apps while in landscape mode on a tablet, textbox prompt fills screen. A textbox like the search bar in a file manager, file rename textbox, browser url bar, etc. Back swipe navigation gesture doesn't work when this happens, only the home swipe gesture works. Then I relaunch the app from recents screen. The size of the screen isn't small, because I've seen this happen only when the vertical height of screen is small in landscape mode. This makes it impossible to see the interactive result output related to the text being input in the respective application, such as list of possible webpages, files, etc.

![image](https://github.com/florisboard/florisboard/assets/97921087/609ae3a3-63b9-4ee6-a016-dc5eab640e9d)

**Comment by patrickgold** [comment]
> However, even though I don't have this issue anymore, it's noteworthy that Dynamically show option failed to disable fullscreen input even when the screen size was large enough in landscape view.

Dynamically show asks the target app if it wants to show this large textbox and if it says yes FlorisBoard will do that. There's no decision-making based on screen-size here.
