### ISSUE TITLE
Farsi keyboard bad accesiballity due to a duplicated key

### ISSUE THREAD

**Issue by mokazemi** [florisboard/florisboard#2250]
When setting the keyboard layout to Farsi, there's an accessibility issue. The space key is not at the center, as you see here:

![Screenshot_20230622_105615_Telegram](https://github.com/florisboard/florisboard/assets/18334056/32492fc8-b07e-4db3-b6e4-3b51b7db7b9d)

But the thing is, one key is extra! The shown key here (in below screenshot) is also available when you hold down dot key. So it shouldn't be in the main keyboard row (and this key is not used that much).
![Screenshot_20230622_105648_Telegram](https://github.com/florisboard/florisboard/assets/18334056/72916a37-ba67-4ff1-8b9a-97f1c2dcbab4)

So that the space key would be bigger and at a better place.

**Comment by GoRaN909** [comment]
It's already fixed by #2227 and it will be available on next release 0.4.0-alpha05, So you must close this issues as completed!

**Comment by mokazemi** [comment]
> It's already fixed by #2227 and it will be available on next release 0.4.0-alpha05, So you must close this issues as completed!

Oh, I didn't know it. Thanks! Do you have any idea when it'll be released?
