### ISSUE TITLE
Word suggestion/Spell check with corresponding emoji

### ISSUE THREAD

**Issue by MayuraVerma** [florisboard/florisboard#2274]
word suggestion and spell check can present word and also corresponding emoji

say dog, 🐕
tiger, 🐅

Most majority languages have emojis localized. So, this feature should be made available across all script.
Keyboard can either leave the emoji mapping database be part of keyboard package or pull from Emoji database with localized data.

**Comment by Glitchy-Tozier** [comment]
Maybe we could go the nowadays common route that colons should be used to indicate the intention of typing an emoji. For example,
- `do` (part of the word `dog`) would mainly suggest stuff like `dog` while
- `:do` (part of `:dog:`) would suggest `🐶`

**Comment by MayuraVerma** [comment]
iOS has implemented emoji suggestion part of word suggestion bar, it's neat

![image](https://github.com/florisboard/florisboard/assets/14062593/0119a6db-028d-4c78-9c6e-7e14828a03bf)

![image](https://github.com/florisboard/florisboard/assets/14062593/1a551bb4-8a3c-467d-9f8d-74d4dfc9d359)

**Comment by MayuraVerma** [comment]
> Maybe we could go the nowadays common route that colons should be used to indicate the intention of typing an emoji. For example,
> 
> * `do` (part of `dog`) would mainly suggest stuff like `dog` while
> * `:do` (part of `:dog:`) would suggest `🐶`

This is one way. It is also doable.

But most do not know all the syntax.

Apple has implemented very way in iOS17.

It takes unicode emoji list with description

https://[unicode.org/Public/emoji/15.1/emoji-sequences.txt](https://unicode.org/Public/emoji/15.1/emoji-sequences.txt)

https://unicode.org/emoji/charts/full-emoji-list.html

When the user types something close in the emoji description. Keyboard suggests the emoji along with the word suggestion, it was doing as usual.

So, now user can type as natural as he/she did before, iOS will suggest emoji along with words. User can be more expressive, if he/she chooses to do so.

FYI: This emoji list is localized for all major languages.
Depending on the keyboard language, emoji list can use appropriate localized emoji list.

Keyboard do not need to maintain the list. Unicode Consortium will maintain the list, will continue to update the list every year. 

Keyboard needs to bring suggestion from wordlist and emoji from emoji list.

**Comment by patrickgold** [comment]
Implemented since v0.4.0 (see changelog) with the :emojiname syntax, closing thus.
