### ISSUE TITLE
replace the first/second row toggle buttons with undo/redo

### ISSUE THREAD

**Issue by unclereeemus** [florisboard/florisboard#2276]
Hi, thanks for your work on this awesome keyboard!

I like my keyboards small and compact so i don't have the second row (where undo/redo reside) toggled esp bc i don't have use for the other buttons so...

I propose to implement the option to remove the row hide and second row toggle buttons to make space for the undo/redo buttons or even choose which buttons one wants in each row, if you feel like it

Many thanks!!

**Comment by klaurence** [comment]
These have already been implemented to some extent in the 0.4.0-alpha versions. The latest alpha version is 0.4.0-alpha04, which you can get [here](https://github.com/florisboard/florisboard/releases).

In 0.4.0-alpha04, you can disable your first row (the suggestions row) but not your second row (the actions row) by going to `Settings > Smartbar > Layout` and selecting `Actions only` (don't hesitate to also try out the other layouts).

You can also customize your "actions" in the Actions row like `Undo` and `Redo` by clicking the `Three dots` button in the actions row of the keyboard itself, clicking `Reorder actions`, and then dragging the actions to the order you like.
