### ISSUE TITLE
Long-press improvement

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#228]
### Issue
**(Assuming the space-bar long-press-action is set to "none / no action")**

When long-pressing on spacebar, nothing happens. Which, in my opinion, is wrong.

**It shouldn't be**

_long press is triggered → do nothing_.

**Instead it should be**

_Long press NEVER EVEN GETS ACTIVATED → space-bar behaves as if it was short-pressed_.

Meaning, that if there was no swiping going on, when the finger releases the space-bar, input `space`.

I assume, the "insert space" option was intended to do this, but this option is no replacement for a real "long-press disabled" option.
Why? Because "insert space" doesn't insert `space` when releasing the space-bar. It triggers like a regular long-press. Meaning that with this, we'd return to the https://github.com/florisboard/florisboard/issues/88 -problem.

### Request:
Add a switch that lets the user turn off long-presses for the space-bar.

This makes it only input space once released. Just like this button works:
![Screenshot_20210123-080728_GitHub.jpg](https://user-images.githubusercontent.com/59611881/105571652-1a9b0300-5d52-11eb-94f5-fa9bece54298.jpg)

**Comment by Glitchy-Tozier** [comment]
**Comment 1**: Of course, space should only be input if no swiping occued.
**Comment 2**: This might make the `no acrion`-option obsolete.
Debateably, this could also remove the _insert space_-option.

**Comment by patrickgold** [comment]
Thanks for your suggestion!

>  Debatably, this could also remove the insert space-option.

The `Insert space` action was NEVER intended to be used as a long press action on the space bar. I think it was unlucky that it was in the same PR, but I added this option because @tydog98 wanted to be able to insert a space when swiping right on the keyboard (#141).

> Long press NEVER EVEN GETS ACTIVATED → space-bar behaves as if it was short-pressed.

This is true, after thinking about it, this makes more sense than doing nothing.

> Add a switch that lets the user turn off long-presses for the space-bar.

I think I will let the space bar insert a space on long press when it is set to `No action` (so it behaves like a space bar should), because I do not want to add another toggle for this.

**Comment by Glitchy-Tozier** [comment]
> I think I will let the space bar insert a space on long press when it is set to `No action` (so it behaves like a space bar should), because I do not want to add another toggle for this.

Sounds smart.

**Comment by patrickgold** [comment]
> EDIT: So does that mean insert space will be removed as well?

Nope, why should I remove it. The `Insert space` action is available to all swipe actions across the board, especially to the swipe right. The `No action` will work independently of it.

**Comment by Glitchy-Tozier** [comment]
Oh, ok.
I just thought an `insert space` would be somewhat redundant. But if you want  every menu to have the same options, it makes sense to keep `insert space`.

**Comment by patrickgold** [comment]
Yeah managing a different list for every swipe pref is both annoying and will definitely lead to some bugs if not carefully maintained. If I have one list for all swipe prefs, this makes the process so much easier. I know that the `Insert space` action makes no sense on the space key, but on other swipe actions it can definitely come in handy, especially for some people coming from SwiftKey, who may be used to swiping right somewhere in the keyboard to quickly insert a space.

**Comment by Glitchy-Tozier** [comment]
Makes sense.

**Comment by patrickgold** [comment]
No there isn't because the lists are defined in XML and are statically compiled into the APK. But I've circumvented the `Insert sapce` in #232, which should avoid any confusion.

**Comment by Glitchy-Tozier** [comment]
Okay, what you did in the pull-request works.

(I'm still a little bothered by the fact that there are two options that do the same thing and by the fact that having "insert space" as a long-press-option kind of implies that it's a long-press and not a release...thing.
However, this still is the best decision to go for i think, since we can't remove `insert space`)
