### ISSUE TITLE
Save most frequently used emojis in exported backup data

### ISSUE THREAD

**Issue by kuba-orlik** [florisboard/florisboard#2285]
It would be neat if the exported backup data would include the list of most frequently used emojis -- currently the list of recently used emojis is empty when restoring from a backup

**Comment by patrickgold** [comment]
Not a bug - for both scenarios:
- erase and overwrite: the history is always reset and then if the backup contains an emoji history it is taken
- merge with current: if the backup contains a history this is taken, else the current one persists

Closing thus.
