### ISSUE TITLE
Idea/Feature: Hide clipboard button when disabling it (go to settings to show again by enabling) or add ability to hide/show clipboard button on Action rows (both of them)..

### ISSUE THREAD

**Issue by ssssamstrup** [florisboard/florisboard#2296]
I don't use and don't want to have my copied info save in clipboard history. Since I don't use the feature it would be great to be able to hide/remove the icon fron the Action rows (it's shown on both of them). 

Right now on smaller devices (like mine), it can easily be enabled by mistake, since it only takes two taps in the same position to;
1. press to open clipboard history,
2. press to enable clipboard button.

![Screenshot_20230919-231047](https://github.com/florisboard/florisboard/assets/4302516/30b5a393-c96a-4460-bb86-663a53cd4408)

Hope you'll consider this for privacy minded users. 😊

Regards, Sune

**Comment by lm41** [comment]
You can already rearrange the smartbar actions and hide them.

In the smartbar the three points. Scroll to the bottom and click reorder actions.

![Screenshot_20240709-234414.png](https://github.com/florisboard/florisboard/assets/59062169/37eb6c8c-45d9-40a3-bf8e-a9b4364a94db)
