### ISSUE TITLE
Long press for symbols, g-board style?

### ISSUE THREAD

**Issue by formula-spectre** [florisboard/florisboard#23]
I mean how on Gboard you can long press letter keys and it pops out a symbol. May I ask for the implementation of this in also florisboard?

**Comment by patrickgold** [comment]
This behavior should be implemented and fully working exactly like in Gboard. If it is not working than its a bug.
It would be best if you file a [bug report](https://github.com/florisboard/florisboard/issues/new?assignees=&labels=bug&template=bug_report.md&title=) and fill out all the fields, so I can work on fixing it, Thank you!
