### ISSUE TITLE
Select text with shift+arrow keys

### ISSUE THREAD

**Issue by eckende** [florisboard/florisboard#230]
> First of all, I love what you're doing here - a functional keyboard that also looks nice and professional. Thank you for your work!

On PC, you can select text by holding the shift key and using the arrow keys. In florisboard you can do this using the smartbar select/copy menu. Also allowing shift selection would make this faster.

**Comment by patrickgold** [comment]
The selection keyboard has this feature already (Smartbar quick actions, then the `I` symbol), where you press on select and then you can expand the selection with the arrow keys. Combining this with the current shift key is difficult, as the shift key is the only key which reacts to the KEY_DOWN event (to update the UI faster and be instantly ready for the following uppercase letter the user wants to type), meaning it would change the caps mode of the keyboard when selecting text this way.

**Comment by patrickgold** [comment]
I will probably add something though in combination with #229, so I will add this on my v0.5.0 milestone too.

**Comment by Glitchy-Tozier** [comment]
@eckende Additionally, you can use the delete-swipe to select text, and then click on one of the copy&past buttons.

**Comment by patrickgold** [comment]
@Glitchy-Tozier That's more a hack than an intended feature IMO. I want to add something which works in both directions and doesn't delete your selected input text if accidentally released.

**Comment by Glitchy-Tozier** [comment]
1. Please never remove those hacks though! I love them!  :)
2. Btw, just in case you're interested, the second "hack" for highlighting text forwards is:
   1. Double-click on a word to select it
   2. Use space-bar-swiping to move the second cursor.

**Comment by patrickgold** [comment]
> Please never remove those hacks though! I love them! :)

I won't, at least not intentionally :)

> Btw, just in case you're interested, the second "hack" for highlighting text forwards is: 

Hmm I can't use this "hack" on my device (the cursor just resets) but good to know that this also can work for selection expansion.

**Comment by Glitchy-Tozier** [comment]
> Hmm I can't use this "hack" on my device (the cursor just resets) but good to know that this also can work for selection expansion.

It's partially app-specific... at least some apps make you select the whole row of text instead of a word  :/
