### ISSUE TITLE
[Feature Request] :- Found Colored Shadow Implementation On Another Open Source App.

### ISSUE THREAD

**Issue by atikattar1104** [florisboard/florisboard#2306]
There Is This App Called 'Acode' (https://github.com/deadlyjack/Acode). It Is An VS Code Like Editor For Android. It Has A Feature For Custom Theme, Which Allows Users To Create Their Own Theme, Using Custom Definable Colors. From This, You Can Change Color Of Shadows. E.g. :- 

![Screenshot_2023-10-04-20-55-27-375_com foxdebug acode](https://github.com/florisboard/florisboard/assets/93785261/76223f17-54e9-426f-9d28-7afed40ca7dc)

![Screenshot_2023-10-04-20-55-36-875_com foxdebug acode](https://github.com/florisboard/florisboard/assets/93785261/82304d99-bc9a-44c1-9def-e42c8ea1a98a)

Notice The Popup Box's Shadow Color. And Title Bar's Shadow Color. 

I Am Not Sure Whether This Would Work For Florisboard, Since Difference Between Languages Of Both Apps. But Just Thought It Might Be Helpful To Let You Know. 

Thanks!

**Comment by tsiflimagas** [comment]
Thank you for your proposal! This is actually already proposed in #1547, let's keep discussion about it there.
