### ISSUE TITLE
Copying to clipboard unpins pinned items

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#2318]
#### After pinning a word, if you copy the same word sometimes it unpins the pinned entry
In my case I pinned some tracking numbers.
Sometimes it is easier to just copy and paste than to go to history and select pinned item.
However, copying the same tracking number in some cases unpins the previously pinned entry, which is not what I want.
Pinned entries should not be unpinned unless user specifically unpins or deletes entry.

#### Steps to reproduce
1. Pin an item/word
2. After using keyboard for a while, copy the same entry that was recently pinned
3. If you check clipboard history, sometimes that entry gets unpinned
4. Pinned items, should not be removed automatically if you copy them again

#### Environment information
- FlorisBoard Version: 0.3.16 
- Install Source: Github 
- Device: Mix 2s 
- Android: 13

**Comment by klaurence** [comment]
I can confirm that this still occurs at 0.4.0-alpha04.

**Comment by lm41** [comment]
I've dropped a fix in #2370
