### ISSUE TITLE
Create a space to share themes

### ISSUE THREAD

**Issue by Turhvjbufv** [florisboard/florisboard#2322]
Maybe a telegram channel or a matrix space where the only things allowed to be uploaded there are themes for florisboard, I think it would be nice for everyone to be able to share and get themes easily

**Comment by patrickgold** [comment]
See https://github.com/florisboard/florisboard/discussions/2327, it is an idea to allow not only sharing themes but custom layouts, dictionaries, etc. in the future.

**Comment by patrickgold** [comment]
The official addons store will allow community themes and everything related to it, see #2468 for more info as it is the implementation effort thread now. Closing to avoid duplicate discussions around this.
