### ISSUE TITLE
Typing many words in a row with swipe gesture should add a spacr between each word

### ISSUE THREAD

**Issue by SuperMeepBoy** [florisboard/florisboard#2324]
Currently, when typing with swiping gesture, if you type two words in a row, without gaping space bar it makes something like this : foobar.

Instead, it would be more convenient to add a space between the words : foo bar.

As for rules of this, the space should be added at the beginning of the next word and not at the end of each word. This so the fully erase word would still work and also because if I type a word using swiping gesture and then start typing the next word without swiping, I also expect to have a space added automatically.

Thanks a lot to whoever does that 🙏

**Comment by klaurence** [comment]
Possibly related to #2291

**Comment by SuperMeepBoy** [comment]
Yup couldn't find it with searchbar. Closing issue then !
