### ISSUE TITLE
Cannot continue further in setup guide even after enabling Florisboard

### ISSUE THREAD

**Issue by WhoTook7050** [florisboard/florisboard#2344]
#### Short description
I am unable to progress through the first start setup guide, even after enabling Florisboard Beta through the System Language and Input Settings

[Screenshot of Florisboard Beta enabled](https://github.com/florisboard/florisboard/assets/92704148/ea721c0c-bb64-4825-9661-e173ca8ea9cb)

#### Steps to reproduce
1. Install Florisboard Beta
2. Open FB Beta
3. Enable FB Beta through the System Languages and Input settings
4. Get stuck on the setup guide.

#### Environment information
- FlorisBoard Version: 4.0.0-alpha05
- Install Source: GitHub (obtainium)
- Device: Pixel 6a
- Android: 14, stock

**Comment by greensheeps** [comment]
I have the same issue

Environment information

FlorisBoard Version: 4.0.0-alpha05
Install Source: GitHub (Obtainium)
Device: Pixel 6a
Android: 14, GrapheneOS

**Comment by M00NJ** [comment]
Like mentioned it the matrix group, I just installed florisboard but can't get past the first step on the setup screen even though floris beta is enabled, selected and I'm typing on it right now. I'm on Android 14 GrapheneOS.

**Comment by patrickgold** [comment]
Until now there seems to be a trend that this bug affects Pixel phones running Android 14

**Comment by WhoTook7050** [comment]
I should also mention I can still type with Florisboard Beta, since I typed this bug report with it

**Comment by alissonlauffer** [comment]
> Until now there seems to be a trend that this bug affects Pixel phones running Android 14

This is also happening on custom ROMs, I can reproduce it with crDroid 10 (Android 14) on my Poco F3.

**Comment by patrickgold** [comment]
^^ above PR should fix the issue, could some of you please test the debug artifact and confirm it if now works?

**Comment by NeveHanter** [comment]
I've tested it on Pixel 6 Pro running latest Android 14 and it worked fine with the debug APK.
