### ISSUE TITLE
Switch to another localization service

### ISSUE THREAD

**Issue by zoli111** [florisboard/florisboard#2348]
Thank you for continuing to maintain and develop this useful project.

Please consider using Weblate instead of Crowdin because,
- There are many open source mobile projects on Weblate, so many potential translators.
- Weblate itself is open source, Crowdin's proprietary nature may deter some contributors.
- [Hosted Weblate](https://hosted.weblate.org) is free for open source projects, and Weblate can even be self-hosted.
- Weblate has the same features and integrations, like automatic translation, GitHub account support...

And I just find Weblate simply more convenient and user friendly, but this is probably personal, and more translators should be asked.

**Comment by patrickgold** [comment]
Hey,

thanks for your comment and your suggestion. Let's go through all of your bullet points one by one and evaluate them:

> There are many open source mobile projects on Weblate, so many potential translators.

That's true but Crowdin is also a massive platform with a lot of translators, as experience has shown. Atm we don't really have a shortage of translators.

> Weblate itself is open source, Crowdin's proprietary nature may deter some contributors.

Valid point but may I remind you that this thread is also on a propietary platform? IMO the product itself and all its dependencies are important to be open-source, if some helper tools around it like Crowdin aren't then that's not much of an issue, as long as there's the option to move away from it in case the platform's terms suddenly change.

> Hosted Weblate is free for open source projects, and Weblate can even be self-hosted
Weblate has the same features and integrations, like automatic translation, GitHub account support...

Good to know, so Weblate can always serve as a backup platform should Crowdin change.

As such I don't really see the point nor the need to switch to Crowdin atm. Ofc your personal preference may be Weblate and I respect that, but for FlorisBoard as a project Crowdin just works fine for now.
