### ISSUE TITLE
Bulgarian keyboard layout 

### ISSUE THREAD

**Issue by danyeet** [florisboard/florisboard#235]
Hi,
Just encountered this project and kudos to what you've done here.
My suggestion is to add a bulgarian keyboard layout. It's cyrillic. 
Here is a screenshot of the Phonetic layout
![Screenshot_20210125-000222](https://user-images.githubusercontent.com/20648137/105644915-12051280-5ea1-11eb-8328-640e46dc1b54.jpg)

Thanks in advance.

**Comment by danyeet** [comment]
> Hi,
> Just encountered this project and kudos to what you've done here.
> My suggestion is to add a bulgarian keyboard layout. It's cyrillic.
> Here is a screenshot of the Phonetic layout
> 
> 
![Screenshot_20210125-000222](https://user-images.githubusercontent.com/20648137/105644891-e7b35500-5ea0-11eb-89ab-2dc96be87e1d.jpg)

> Thanks in advance.

**Comment by patrickgold** [comment]
Thanks for the layout proposal! I will add it on my todo list.
