### ISSUE TITLE
Spacebar is not visible in some borderless themes

### ISSUE THREAD

**Issue by Baerbeisser** [florisboard/florisboard#2350]
#### Steps to reproduce
Install [catppucin](https://github.com/catppuccin/floris-board/releases/tag/0.0.1) theme (yous are working around this by having the spacebar in a darker color).
Choose a borderless variant,

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: F-Droid
- Device: independent
- LineageOS: 20

#### Proposed Solution
Hackers Keyboard uses ␣ (U+2423 9251 Open box) in spacebar, it looks quite nice imo.

**Comment by lm41** [comment]
You can currently avoid this problem by activating the setting "Show language on space bar". (The current language will then be visible).
I agree that extending this option to alternatively display "␣" would be a good idea.

**Comment by lm41** [comment]
![Screenshot_20240113-061603.png](https://github.com/florisboard/florisboard/assets/59062169/1cefe3cb-6d6d-442e-8845-44f69349f070)

Is this how you imagined?

**Comment by Baerbeisser** [comment]
Maybe make it scale with the font size?
