### ISSUE TITLE
Option to hide bottom bar

### ISSUE THREAD

**Issue by Baerbeisser** [florisboard/florisboard#2351]
Currently, it looks like this for me:
![Florisboard](https://github.com/florisboard/florisboard/assets/22264628/99419833-16ce-41d3-8802-d163809fe57e)
(empty spacebar already reportet)
Is there a way to disable the bottom bar with switch/hide keyboard buttons? It's rather distracting.

**Comment by patrickgold** [comment]
Yes in your system settings, the bottom-most bar isn't controlled by FlorisBoard

**Comment by Baerbeisser** [comment]
It isn't displayed in "Hackers Keyboard". Is this a "hack"?

**Comment by patrickgold** [comment]
Again that's a system bar and even if there's a way to hide it forcefully I won't because it is controllable from the system settings and actually it is useful for some.
