### ISSUE TITLE
Erroneous autodeletion of space before quotation mark - 0.4.0-alpha04 (90)

### ISSUE THREAD

**Issue by leehyunkeun** [florisboard/florisboard#2352]
To reproduce bug, type a sequence of words with each word in separate quotation marks, e.g.

> "Android" "Florisboard" "Github"

A typical use case would be Google search queries, where the results must include the exact search terms in quotation marks.

**Bug:** Florisboard autodeletes spaces preceding quotation marks, i.e. typing in the string above results in

> "Android""Florisboard""Github"

Florisboard does not seem to recognize the beginning and end of a quotation within a line or paragraph, i.e. the fact that every odd-numbered (even-numbered) quotation mark must be the beginning (end) of a quotation. Unfortunately, there is no option to disable this autocorrection 'feature'.

**Comment by lm41** [comment]
I cannot reproduce this with 0.4.0-alpha06 + nlp. 
Can you provide more information on how to reproduce this issue?

**Comment by leehyunkeun** [comment]
Thanks for your response. Which information do you need? If there is an easy way to dump the app settings, I could provide you with the exact configuration.

**Comment by atikattar1104** [comment]
Tried The Same In Latest Beta Release. This Doesn't Happens Anymore. Try In New Beta Release If It Works Or Not.

**Comment by leehyunkeun** [comment]
Thanks for the news. Is it possible to update to the new release without having to reconfigure everything?

**Comment by atikattar1104** [comment]
1. Don't Uninstall Previous App. 
2. Make Full Backup From `Florisboard Keyboard App` --> `Advanced` --> `Back up data` Option. 
3. Make Sure To Check All Options (`Preferences`, `Keyboard Extentions`, `Theme Extentions`). 
4. Select Backup Destination To `Local File System`. 
5. Click `Back up`. 
6. Save The Created Backup File To Internal Storage (Don't Worry, File May Only Be Few KBs, Not Much). 
7. Download And Install New APK Over Preinstalled App. 

It Should Keep Previous Configurations In New Version. 

If Configurations Do Delete Even After Performing This Method, Import The Backup You Created In 2nd Step. 

1. Make Full Restore From `Florisboard Keyboard App` --> `Advanced` --> `Restore Data` Option. 
2. Select `Merge With Current Data` Option. 
3. Click `Select File`, And Select The Backup File You Previously Created. 
4. Click `Restore`. 

This Should Bring Back Your Configurations To New Version Of App If It Was Not Saved While Updating.

**Comment by atikattar1104** [comment]
Shout Out To All The Devs For Creating Such Comprehensive Backup - Restore Mechanism.

**Comment by leehyunkeun** [comment]
Issue is fixed with the latest update, thank you very much. And thanks also for the detailed backup instructions.

Great support!
