### ISSUE TITLE
Add Bangla Language Google Layout 

### ISSUE THREAD

**Issue by mehedi2580** [florisboard/florisboard#2353]
Add Bangla Language Google Layout 
![Screenshot_20231229-022100_Chrome](https://github.com/florisboard/florisboard/assets/39218757/33737d70-ecb2-46cd-91b3-5776363fda2d)

**Comment by Tarek-Hasan** [comment]
Duplicate of #1885

**Comment by mehedi2580** [comment]
why you close this proposal ? still this keyboard dont have google bangla layout.

**Comment by patrickgold** [comment]
Because it is a duplicate of the linked issue.
