### ISSUE TITLE
Croatian layout proposal

### ISSUE THREAD

**Issue by PowerMan2206** [florisboard/florisboard#236]
I'm proposing a Croatian layout.
![keyboard](https://user-images.githubusercontent.com/61635519/105647887-d706dd00-5ea8-11eb-9a7e-81561dd0f7a8.jpg)
As you can see, the layout is identical to a standard QWERTZ one, with the only difference being that long-pressing some keys gives a selection of some Croatian letters:
* Zz - Žž
* Dd - Đđ
* Ss - Šš
* Cc - Čč, Ćć

There is also another layout where these letters are crammed to the right, making all the other keys slimmer. I prefer the way above because this one makes fast typing harder.

**Comment by patrickgold** [comment]
Thanks for your suggestion! I am guessing you are still on v0.3.2 (F-Droid is pretty slow in adapting updates). In the current versions this is already fully implemented and working (see #133). So it should arrive as soon as F-Droid updates.

**Comment by PowerMan2206** [comment]
Ahh, I see. My bad
