### ISSUE TITLE
There no nine in thai lang (it got replaced with 8)

### ISSUE THREAD

**Issue by PakinDeReal** [florisboard/florisboard#2360]
#### Short description
the 9 in thai lang got replace with 8
![Screenshot_2024-01-04-08-13-03-454_org chromium thorium-edit](https://github.com/florisboard/florisboard/assets/87290041/79bd53b7-243b-4cdf-ad96-d01d2b055656)
it should be  "๙" sorry if i wasted yall time with kinda pointless report

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: F-Droid
- Device: Redmi note 12
- Android: 13

**Comment by BHydden** [comment]
It was already fixed in https://github.com/florisboard/florisboard/pull/2320

If you switch to the beta channel for floris board it should be implemented in the latest release.

**Comment by PakinDeReal** [comment]
thanks you
