### ISSUE TITLE
Previous chosen theme-color resets upon reopening color-picker.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#237]
I feel like you need to long- press a color to actually activate it (?)

Basically, the color always reyets to the previous color after clicking on 'ok'.

**Environment information**
- FlorisBoard Version: 0.3.4
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Steps to reproduce**
Just try to change the main color.

Are there any quick video-sharing platforms? I can't add the video to a comment for some reason.

**Comment by patrickgold** [comment]
Hmm I cannot reproduce this bug, the color consistently sets when pressing "OK".

> Are there any quick video-sharing platforms? I can't add the video to a comment for some reason.

I really hope the GitHub Android app adds video adding support, as this would definitely help in quicker attaching of videos. Currently, I am using GDrive to move the video from my phone to my PC, where I then upload it to GitHub  (and then it is beautifully embedded into the issue).

**Comment by Glitchy-Tozier** [comment]
> I really hope the GitHub Android app adds video adding support, as this would definitely help in quicker attaching of videos.

Yeah, the app seems to always be a little behind on everything  :/
That was really annoying back when discussions weren't implemented yet.

> Hmm I cannot reproduce this bug, the color consistently sets when pressing "OK".

Anyway, I think I misinterpreted what was happening on-screen.
1. I went to the color-picker-screen
2. I clicked on a color
3. I clicked on select (meaning I went back to the first pop-up)
4. I clicked on the edit-pencil again to double check whether I picked the correct color
5. __It had reset to green!__

This is what confused me. If you pick a color, it shouldn't reset when you double-check. So I assumed it never even selected the correct color.

**Comment by patrickgold** [comment]
> Yeah, the app seems to always be a little behind on everything :/

Yeah sadly, because the design is super fluent and clear. It just sometimes lacks new features from Desktop/Web,..

> This is what confused me. If you pick a color, it shouldn't reset when you double-check. So I assumed it never even selected the correct color.

Well that's a bug. It does indeed select the correct color (can be seen as the hex color string changes), but the cached init color will always be the old until you hit "OK". I will fix this with the adaptive theme PR (which I made great progress so far, will push sometime today.)

**Comment by Glitchy-Tozier** [comment]
Perfect, sounds great!  :)

**Comment by patrickgold** [comment]
Above PR fixes the cached init color bug in the theme editor. Additionally, the background color of the color edit button now matches the currently selected color.
