### ISSUE TITLE
Adding alpha builds to F-Droid

### ISSUE THREAD

**Issue by d-e-n-n-i-s-t** [florisboard/florisboard#2376]
### Feature idea

Hey!

I was wondering why the 0.4 alpha builds don't get added to F-Droid as beta-builds. I know they're not beta because they are alpha technically, but IMO it would make more sense to release them as beta-builds than to not release them on F-Droid at all.
If you add "alpha" to the version name and release them as beta build, everyone should know what they're dealing with.

Thank you for this awesome FOSS-keyboard and best regards
Dennis

**Comment by lm41** [comment]
The alpha builds are available in the IzzyOnDroid F-Droid repo.

https://apt.izzysoft.de/fdroid/index/apk/dev.patrickgold.florisboard.beta

**Comment by tsiflimagas** [comment]
As @lm41 said, you can get alpha builds from IzzyOnDroid repo. For more insight, you can check #1896.

**Comment by d-e-n-n-i-s-t** [comment]
I'd prefer builds being built by F-Droid... By that logic you could completely eliminate the builds from F-Droid main repo and only publish them on IzzyOnDroid's repo. Doesn't make sense to me, but whatever

**Comment by patrickgold** [comment]
> By that logic you could completely eliminate the builds from F-Droid main repo and only publish them on IzzyOnDroid's repo. Doesn't make sense to me, but whatever

Alpha/Beta builds are intended to be tried out early by testers and may also contain breaking changes in the build script config, as such quick publishing is prioritized for them.

**Comment by d-e-n-n-i-s-t** [comment]
> may also contain breaking changes in the build script config

That makes sense to me, thanks for taking the time.
