### ISSUE TITLE
Florisboard resets after kernel crash/panic

### ISSUE THREAD

**Issue by kkrak3n** [florisboard/florisboard#2377]
### Short description

Whenever the kernel crashes or goes into panic mode, the app resets your keyboard. Upon opening it again you are greeted with the default after install screen.
Upon opening the app and doing nothing, then checking app data, it consumes 2.40 MB
The work profile app is not affected, although I have not tried crashing while using the work profile.

### Steps to reproduce

1. Get the system to crash or go into panic mode (I managed to crash by creating a fork bomb in Termux)
2. Wait for system to reboot
3. Open a text field

### FlorisBoard Version

0.3.16

### Install Source

F-Droid

### Device

Pixel 4a 5G

### Android

14, Graphene

**Comment by tsiflimagas** [comment]
This seems to be falling under #1726. Could you tell me, do you happen to use English (United Kingdom) layout?

**Comment by kkrak3n** [comment]
> This seems to be falling under #1726. Could you tell me, do you happen to use English (United Kingdom) layout?

No, I am using the QWERTY (US) and ЙЦУКЕН (RU) layouts

**Comment by tsiflimagas** [comment]
Thanks for the info. Let's close this issue, and keep the discussion in #1726.
