### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lukaneco** [florisboard/florisboard#238]
**Environment information**
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android version, ROM: 

**Steps to reproduce**

**Comment by patrickgold** [comment]
You posted an empty bug report, could you please fill out the fields so I can work with this? Thanks :)

**Comment by lukaneco** [comment]
When the keyboard was opened for the first time, it was freezed and closed automatically, it did not happen again

**Comment by patrickgold** [comment]
Hmm yeah could be because some preferences did some one-time setup. Though I don't think I will we able to fix anything here. Closing this issue now.
