### ISSUE TITLE
Add cross-profile support

### ISSUE THREAD

**Issue by nvllsvm** [florisboard/florisboard#2384]
### Feature idea

API level 28 added the ability for apps to communicate across device profiles (ex. personal and work profiles). For example, enabling this for Gboard allows keyboard settings to remain consistent across both profiles.

https://developers.google.com/android/work/connected-apps

**Comment by patrickgold** [comment]
To be able to use this I would need to apply for that in the Google Play Console. However one requirement is already not fulfilled:

> The application they wish to submit for review should be an existing application with demonstrated popularity (minimum 200,000 downloads in Google Play). We do not intend to accept EAP submissions for brand new applications.

As such FlorisBoard cannot offer this functionality, I am sorry.
