### ISSUE TITLE
Swipe Up From Spacebar gesture stopped working.

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#2389]
### Short description

Hello all. I have the swipe up from spacebsr gesture set to open to clipboard history and suddenly it has stopped working.

### Steps to reproduce

1. Copy text
2. Move to an input field
3. Swipe up from spacebar

### FlorisBoard Version

0.4.0-alpha6

### Install Source

F-Droid

### Device

Oneplus Nord N30 5G

### Android

OxygenOS 13 stock

**Comment by lm41** [comment]
I can reproduce this with
```
0.4.0-debug-6f169997
Android 14 (GrapheneOS)
Pixel 7 Pro
```

**Comment by kizaski** [comment]
Are you sure you've set the **space bar swipe up** gesture and not the general one? Because I can't reproduce this.

**Comment by Kreuger** [comment]
Im not sure what happened but it works fine now.

**Comment by patrickgold** [comment]
I can also verify that it works as intended, so we can close this issue?
