### ISSUE TITLE
Settings reset after every reboot

### ISSUE THREAD

**Issue by xxxcrow** [florisboard/florisboard#2394]
Hi, firstly, i'm very happy to see the project back, I've been using this keyboard for a very long time already

My issue is simple, after every reboot all the setting are reset, all the layouts, themes, haptics, everything
It even asks me to do the settings again

**Comment by lm41** [comment]
Can you please provide more information such as android system version, app version etc.

**Comment by patrickgold** [comment]
Duplicate of #1726

Sadly this rare bug still hasn't been resolved, however when I find the time could try using the read-only flag for preference models introduced with [JetPref 0.1.0-rc01](https://github.com/patrickgold/jetpref/releases/tag/0.1.0-rc01)
