### ISSUE TITLE
Add .com button when typing inside the address bar of a web browser app

### ISSUE THREAD

**Issue by mauserk98grenaderifle** [florisboard/florisboard#2405]
### Feature idea

Adding  .com (or .org) button when typing inside the address bar of a web browser app
![423686679_427906866274316_8956384042884315881_n](https://github.com/florisboard/florisboard/assets/128981897/e13426f2-4cc5-4df0-b1d0-6cfe8ee8c377)
 Adding this screenshot as reference

**Comment by lm41** [comment]
This is already available if you press and hold the period button.
