### ISSUE TITLE
Add the option to donate in cryptocurrency

### ISSUE THREAD

**Issue by TheFuzzStone** [florisboard/florisboard#2411]
### Feature idea

This is a very cool and important project for FOSS enthusiasts. I've seen a lot of cool projects die because they didn't get proper funding.

I saw that there is an option to donate through LiberaPay, but I don't have the ability to support the project through that option.

So, I suggest adding create you some wallets to be able to accept donations in crypto.

You don't need to create 1247192 wallets, but only the most popular ones, namely:

* Monero (XMR) // GrapheneOS has a positive experience, see here: https://twitter.com/GrapheneOS/status/1684663777273233408
* Bitcoin (BTC)
* Ethereum (ETH) // on which you will be able to accept ERC20 tokens, namely the most liquid ones are: USDT, USDC and DAI
* Tron (TRX) // which has the most liquid and widely used USDT on its network

----

If you add Monero (XMR) then please ping me via @ and I'll be the first to send a donation. :)

**Comment by patrickgold** [comment]
Thanks for considering to donate to this project!

Sadly as I already mentioned I do not want to receive donations in crypto currency as I do not have any use for them and makes taxation more difficult, which I want to avoid as I hate more bureaucracy. Hope you can understand :)
