### ISSUE TITLE
Remove the 'Show/Hide Additional Actions' button from SmartBar for people who don't use any additional actions.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [florisboard/florisboard#2424]
### Feature idea

Pretty much explained the request in the title.
Here's the screenshot to exactly show what I'm requesting for:
![1710642723521](https://github.com/florisboard/florisboard/assets/91815107/2b399c80-c136-4ece-babd-147ae3b1030e)

**Comment by patrickgold** [comment]
See #2094, this is not planned to be implemented due to unnecessary complexity in UX terms. Closing as wontfix.
