### ISSUE TITLE
In SmartBar, make "Cut, Copy & Select All" always white.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [florisboard/florisboard#2427]
### Feature idea

Please make Cut, Copy & Select All action buttons always white.
![Screenshot_2024-03-19-12-27-01-91_f22faf49515899f9781ec174a4d85388](https://github.com/florisboard/florisboard/assets/91815107/4d0aae58-a727-4494-84ab-db8104d11de9)

**Comment by Aryan-Chauhan** [comment]
> There's a reason why they're not always white. When there's no text to select, copy or cut, these buttons have no action to do, so they're showing they're inactive. They'll become white when they'll have so text to act upon. 

But they look inconsistent.

It won't hurt if they are always white.

The user already knows if there is any text to act upon or not.

There is literally no need for the buttons to tell that fact. 

Due to these reasons, they should be always white. So, please re-open this issue & consider adding this request as an option (so that people who like the old behaviour won't get annoyed).

Thanks!

**Comment by Aryan-Chauhan** [comment]
Waiting for devs' reply.

I'm only requesting for a "choice".

**Comment by patrickgold** [comment]
Well in typical desktop GUIs the Copy/Paste actions are also greyed out if there's nothing to copy/paste and from a UX standpoint a working looking button that does nothing is not correct behavior.

As such it makes little sense tbh, but if you really want to have it that way modify your theme so the disabled state theme matches the normal one.

**Comment by Aryan-Chauhan** [comment]
> Well in typical desktop GUIs the Copy/Paste actions are also greyed out if there's nothing to copy/paste and from a UX standpoint a working looking button that does nothing is not correct behavior.
> 
> As such it makes little sense tbh, but if you really want to have it that way modify your theme so the disabled state theme matches the normal one.

Oh! I didn't know FlorisBoard has an in-built theme creator.
