### ISSUE TITLE
[Feature Request] Search bar for emojis 

### ISSUE THREAD

**Issue by lxwulf** [florisboard/florisboard#2430]
### Feature idea

As mentioned in the title, a search bar in the emoji section would be nice. It's most of the time faster to type the emoji, instead search by hand manually.

Else, the best keyboard I had until now! 😊

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your feature request. Could this be a duplicate of #45?

**Comment by lxwulf** [comment]
Oh, yes, sorry for that! I hope the release of the feature will be soon. :smiley:

**Comment by Glitchy-Tozier** [comment]
I, too, look forward to it! :)
