### ISSUE TITLE
bug: In SmartBar, size of copy button should be decreased, so that it doesn't feel out of place.

### ISSUE THREAD

**Issue by Aryan-Chauhan** [florisboard/florisboard#2431]
### Short description

In SmartBar, copy button looks bigger when compared to other buttons. So, please fix it by making all available buttons similar in size.
![Screenshot_2024-03-26-09-07-32-53_c853220993b0ed55eb2e57645fcd343d](https://github.com/florisboard/florisboard/assets/91815107/0bd0c581-3231-44dd-8bfe-dc2869802977)

### Steps to reproduce

Just copy my SmartBar setup & notice please.

### FlorisBoard Version

0.4.0-beta01 (93)

### Install Source

GitHub

### Device

Realme 7 Pro

### Android

Android 12 (skin name is Realme UI 3.0)

**Comment by Aryan-Chauhan** [comment]
![Screenshot_2024-03-26-10-50-55-56_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/florisboard/florisboard/assets/91815107/44b3d1b1-60a1-47d7-a81f-ed8e8f8930ae)

**Comment by patrickgold** [comment]
That's just how the Material icons are designed and nothing FlorisBoard will change.

In fact in your own screenshot you can see that the create list button is not the same height as the checkbox button either, but the designers behind the icon probably had their reasons for it.
As such I will close this issue as wontfix, hope you can understand.

**Comment by Aryan-Chauhan** [comment]
> That's just how the Material icons are designed and nothing FlorisBoard will change.
> 
> In fact in your own screenshot you can see that the create list button is not the same height as the checkbox button either, but the designers behind the icon probably had their reasons for it.
> As such I will close this issue as wontfix, hope you can understand.

Yes, the reason is "disregard towards uniform size because it doesn't matter".

Which is an illogical reason.

Also, you didn't explain why it's impossible to decrease the size of Copy Button.
