### ISSUE TITLE
OpenAI's Whispher

### ISSUE THREAD

**Issue by warmachinesocial** [florisboard/florisboard#2433]
### Feature idea

I was thinking on integrating this into the keyboard, I couldn't believe because I speak multiple languages to together and it translates to english... it shocked me

**Comment by MXC48** [comment]
> ### Feature idea
> 
> I was thinking on integrating this into the keyboard, I couldn't believe because I speak multiple languages to together and it translates to english... it shocked me

You can also use whisper with Futo voice input https://voiceinput.futo.org/

**Comment by warmachinesocial** [comment]
Yeah, I never knew about this to be honest, but yeah, I mean, we can close this issue then.
