### ISSUE TITLE
Latest version on FDroid and Obtainium are outdated

### ISSUE THREAD

**Issue by Coehill** [florisboard/florisboard#2434]
### Short description

The latest version available on FDroid and Obtainium are 0.3.16. 

### Steps to reproduce

Install Florisboard from FDroid or the official github repo in Obtainium app.

### FlorisBoard Version

0.3.16

### Install Source

F-Droid

### Device

Samsung Galaxy S23

### Android

14

**Comment by Coehill** [comment]
Closing since planned FDroid has latest stable version from 2022.

**Comment by lm41** [comment]
You can get the beta/alpha releases from the izzyondroid f-droid repo.

**Comment by BHydden** [comment]
And also on obtainium,  you just need to tick the beta releases box
