### ISSUE TITLE
Redundant "hinted number row" toggle when number row is enabled

### ISSUE THREAD

**Issue by TheTrueWhiteOwl** [florisboard/florisboard#2435]
### Feature idea

In the settings, under the keyboard menu, when the "number row" toggle is enabled, the "hinted number row" toggle does nothing...

My proposal is to only hide this toggle when the number row is enabled and show it otherwise. This would help to slightly improve that menu's readability (no need to look over an option that does nothing when it isn't needed).

Alternatively, if you want to make it apparent that the option exists even when not needed, you could grey the toggle out under the conditions mentioned above.

**Comment by flori-s** [comment]
Hi, is it okay if I start working on this issue?

**Comment by patrickgold** [comment]
Yes it's okay
