### ISSUE TITLE
Key caption is not centered if hinted symbols is disabled

### ISSUE THREAD

**Issue by Whoopalla** [florisboard/florisboard#2447]
### Short description

Captions are not centered:
![image](https://github.com/florisboard/florisboard/assets/87174692/31a99eaa-6101-4d6a-ac89-f18d6913f872)

### Steps to reproduce

Open keyboard

### FlorisBoard Version

0.3.16 (86)

### Install Source

Google PlayStore

### Device

OPPO A54

### Android

11

**Comment by lm41** [comment]
This is just how the font is working. 
![2024_04_24_11_43_34](https://github.com/florisboard/florisboard/assets/59062169/3d71e779-b8b9-4d33-92f8-c4e017bb46e1)
