### ISSUE TITLE
Google swypelibs

### ISSUE THREAD

**Issue by Archeix7** [florisboard/florisboard#2459]
### Feature idea

Perhaps the idea is strange, but the heliboard keyboard implemented suggestions and swypes on closed sources, why not temporarily add such an implementation to florisboard until you implement your suggestions and swypes? For some time it will not be open source code, but it will be more convenient to use the keyboard and the data will still not leak anywhere
https://github.com/Helium314/HeliBoard

**Comment by lm41** [comment]
Using closed source libraries is against the idea of florisboard.

The glide typing will soon™ be added as a rust crate. (Similar to the word suggestions)
