### ISSUE TITLE
`Landscape fullscreen input` shows in portrait

### ISSUE THREAD

**Issue by klaurence** [florisboard/florisboard#2474]
### Short description

When `Landscape fullscreen input` is set to `Always show`, your phone is in portrait, and you focus on an input box, the Florisboard text box appears.

I'm not sure if this portrait orientation behavior should be intentional. If it should be, `Landscape fullscreen input` should be renamed to `Fullscreen input`. If it shouldn't be, it should be fixed.

### Steps to reproduce

1. Go to `Settings > Keyboard` and set `Landscape fullscreen input` to `Always show`.
2. Rotate your phone to portrait.
3. Tap an input box.

### FlorisBoard Version

0.4.0-beta02

### Install Source

Google PlayStore

### Android

10

**Comment by patrickgold** [comment]
Definitely a bug and fully reproducible for me
