### ISSUE TITLE
Scrolling with a mouse scroll wheel on the keyboard or in the app crashes Florisboard

### ISSUE THREAD

**Issue by 5h3i1ah** [florisboard/florisboard#2504]
### Short description

Title. This started happening with a recent version of a PC program called scrcpy ("Screen Copy"), a program that lets you control an Android phone directly through a computer. Specifically the Linux version. Nothing about the phone or Florisboard itself has changed since before crashes started to happen. scrcpy recently updated to communicate mouse hovering to Android (buttons used to not react to my mouse unless i clicked, but now they react upon hover if they have defined hover behavior), which is probably relevant. This happens on accident quite frequently.

### Steps to reproduce

1. Place your mouse cursor on the Florisboard keyboard or app (might specifically need to do so through scrcpy? not cerain if connecting a mouse straight into an Android device would have the same result, but i'm pretty sure it would)
2. Scroll with the mouse's scroll whell
3. Florisboard crashes

#### Environment information
- FlorisBoard [0.4.0-beta01](https://github.com/florisboard/florisboard/releases/v0.4.0-beta01) (93)
- Device: Samsung SM-A205U (a20psq)
- Android: 10 (cn=Q sdk=29)

#### Attached logs and stacktrace files
<details>
<summary>Detailed info (Debug log header)</summary>

```
======= SYSTEM INFO =======
Time                : 2024-07-11T02:50:21.601Z
Manufacturer        : samsung
Model               : SM-A205U
Product             : a20psq
Android             : 10 (cn=Q sdk=29) [QP1A.190711.020.A205USQS9BUC2]
ABIs                : [arm64-v8a, armeabi-v7a, armeabi]
Memory              : 2.14 GiB (81.06% used, 2.65 GiB max)
Font scale          : 1.1
Locales             : en-US

======= APP INFO =======
Package             : dev.patrickgold.florisboard.beta
Name                : FlorisBoard Beta
Version             : 0.4.0-beta01 (93)
Build type          : beta
Build commit hash   : 0dd1f90c83409865e2def316d7cb4089b2f1c8be
Java heap memory    : 15.43 MiB (8.04% used, 192.00 MiB max)
Native heap memory  : 35.76 MiB (96.23% used, 37.16 MiB max)

======= FEATURE CONFIG =======
Smartbar enabled            : true
Suggestions enabled         : false
Inline autofill enabled     : true
Glide enabled               : true
Internal clipboard enabled  : false

```
</details>

<details>
<summary>1720666217378.stacktrace</summary>

```
java.lang.IllegalStateException: The ACTION_HOVER_EXIT event was not cleared.
	at androidx.activity.ComponentDialog$$ExternalSyntheticLambda1.run(SourceFile:176)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7860)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```
</details>

**Comment by lm41** [comment]
This is a Jetpack Compose Bug and will be fixed when version 1.7.0 is released.
