### ISSUE TITLE
A couple of problems and a couple of suggestions...

### ISSUE THREAD

**Issue by tuqueque** [florisboard/florisboard#251]
Hello!... First of all, I LOVE this new keyboard!... I started using AnySoftKeyboard a few years ago, but I wasn't very happy with it and there has been lack of updates for at least a year now... Several months ago I moved to the OpenBoard keyboard and I am fairly happy with it... A couple of months ago I noticed this new keyboard app in the f-droid store and after seeing constant updates to it, I decided to test it and I'm impressed with it! Is fairly easy to set up, it has a good amount of features and so far it works really well.

I only have a few problems with it that I would really like to see fixed:

1.- Add an option to remove/hide the emoji key in the settings. I never use that key and to me is not only space hog but a huge annoyance if I press it by mistake.

2.- For the Spanish keyboard (all of them, Spain, Latin and even EEUU) the "accent" letters should be consistent!... If I long-press the "a" or "A", I get the correct "Á" or "á" as the first hinted symbol, but if I long-press "E", "I", "O" and "U", I get different and inconsistent hinted symbols, even after setting "Accent is prioritized" for the Hinted symbols in the settings. For all Spanish setups, the first hinted symbols at least for the vowels should be Áá, Éé, Íí, Óó and Úú... This would save A LOT of time and awkwardness!... Especially when the the "Accent is prioritized" option is set in the settings!

Finally, something I would love to have is an option to increase the relative size of the small hinted symbol in the upper-right corner of all the keys that have it... Maybe a new setting with a horizontal bar like the ones for the "Font size multiplier" but for "Main / Hint symbol ratios"... where the left end of the bar is like 95% - 5% (main key - hint symbol sizes) and the right end of the bar would be like 70% - 30% (main key - hint symbol sizes)... My eyes are not the same these days and bigger hinted symbols in the keys would make a HUGE difference!

Thank you very much in advance!

**Comment by patrickgold** [comment]
Glad you like FlorisBoard thus far!

> 1.- Add an option to remove/hide the emoji key in the settings. I never use that key and to me is not only space hog but a huge annoyance if I press it by mistake.

Has been added with v0.3.5, but was named awkwardly by me: "Switch key mode" (in Settings > Keyboard). In v0.3.6 (not yet released), it will still be in the same place, but with the name "Utility button" and the actions are also named more clearly, which seems to create less confusion what this preference even does.

> 2.- For the Spanish keyboard (all of them, Spain, Latin and even EEUU) the "accent" letters should be consistent!... If I long-press the "a" or "A", I get the correct "Á" or "á" as the first hinted symbol, but if I long-press "E", "I", "O" and "U", I get different and inconsistent hinted symbols, even after setting "Accent is prioritized" for the Hinted symbols in the settings. For all Spanish setups, the first hinted symbols at least for the vowels should be Áá, Éé, Íí, Óó and Úú... This would save A LOT of time and awkwardness!... Especially when the the "Accent is prioritized" option is set in the settings!

Thanks for bringing this up. I tried by best to set the main/relevant extended popups for as many languages, but I wasn't sure for Spanish. I will fix this for the mentioned vowels.

> Finally, something I would love to have is an option to increase the relative size of the small hinted symbol in the upper-right corner of all the keys that have it... Maybe a new setting with a horizontal bar like the ones for the "Font size multiplier" but for "Main / Hint symbol ratios"... where the left end of the bar is like 95% - 5% (main key - hint symbol sizes) and the right end of the bar would be like 70% - 30% (main key - hint symbol sizes)... My eyes are not the same these days and bigger hinted symbols in the keys would make a HUGE difference!

I will add this to my todo list! How exactly I will implement this I am unsure of, but I will definitely implement it!

**Comment by tuqueque** [comment]
Hey, thank you very much for the quick and promising feedback!... I'm super happy to know you'll fix the Spanish accents issues and you'll add a way of increasing the size of the key symbol hints!

About the 0.3.5 version. I'm using the F-Droid version of the app and the latest version there is the 0.3.4... I hope you can update the F-Droid version soon.

Again, thanks for such great feedback/news!

**Comment by Glitchy-Tozier** [comment]
Sooo... No.2 is done, maybe we should update the Title and maybe even the description to highlight suggestion no.1.
You can strikethrough text by using `~~Text~~` (=~~Text~~) and you can make text bold by using `**Text**` (=**Text**).

**Comment by Glitchy-Tozier** [comment]
As everything is implemented, we can close this issue, correct?

**Comment by patrickgold** [comment]
> Finally, something I would love to have is an option to increase the relative size of the small hinted symbol in the upper-right corner of all the keys that have it... Maybe a new setting with a horizontal bar like the ones for the "Font size multiplier" but for "Main / Hint symbol ratios"... where the left end of the bar is like 95% - 5% (main key - hint symbol sizes) and the right end of the bar would be like 70% - 30% (main key - hint symbol sizes)... My eyes are not the same these days and bigger hinted symbols in the keys would make a HUGE difference!

This part is not yet implemented but I extracted it to #752 so it is more clearer in the issue list. Closing this issue thus.
