### ISSUE TITLE
Hide contents of sensitive clip data

### ISSUE THREAD

**Issue by A1eeeee** [florisboard/florisboard#2510]
### Feature idea

If you copy sensitive information such as passwords and verification codes, display these sensitive information as ***.

**Comment by patrickgold** [comment]
Please note that the needed [meta data for this](https://developer.android.com/reference/android/content/ClipDescription#EXTRA_IS_SENSITIVE) is only available from Android 13 or newer

**Comment by lm41** [comment]
Should the sensitive data be saved to the clipboard history, or should they only be stored in the primary clip?

**Comment by A1eeeee** [comment]
> Should the sensitive data be saved to the clipboard history, or should they only be stored in the primary clip?敏感数据应该保存到剪贴板历史记录中，还是应该只存储在主剪辑中？

saved to the clipboard history,
