### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by Triplesweet** [florisboard/florisboard#253]
Hi there.
I was trying to translate some parts to persian and there is a problem. There are some words that are not really translated or got their own meanings. For example toggle or alpha testing.
Toggle got meanings that dont add up to what its saying in app
Alpha and beta testing is just "testting or early access".
If necessary should we use other words to make it work?

I will try to make it as close as possible tho

**Comment by Triplesweet** [comment]
And should i use "فلوریس بورد" instead? Because it can couse some problmes.
Perisan is right to left and when you change you keyboard to eng it makes it left to right so it can make the eng part go crazy or make it go to the left part.
I would lile to know if someone had this problem or not dont want problemst later on after all

**Comment by patrickgold** [comment]
I think it is best to use other words to describe an untranslatable word like alpha or toggle.

For the name "FlorisBoard", I think it is best to stick to this convention:
All Latin-script languages: FlorisBoard
All non-Latin-scripts: (translated version of FlorisBoard)

I have to fix this though in the apps resources somehow, as the static word "FlorisBoard" is sometimes hard-coded (where you can translate it) and sometimes dynamically inserted, where always "FlorisBoard" is inserted.

Just curious: What does "فلوریس بورد" translate to when done literally? Regardless of what it is, if you think it fits best, go for it!

**Comment by Triplesweet** [comment]
@patrickgold "فلوریس بورد" is literly letter to letter translated. As how you say it instead what the whole word mean
And for toggle. It does have a meaning but very spesial places lile safty toggle of a gun. Putting it on some other places seems very odd to read. I couldnt find anything usefull too i might have too put the exact word toggle or something else but for now i will search see if smething comes up

**Comment by Triplesweet** [comment]
@patrickgold and should i wait till you make all "florisboard"s dynamic?

**Comment by patrickgold** [comment]
"فلوریس بورد" is literly letter to letter translated. 

@Triplesweet Ok thanks for clarifying!

> And for toggle. It does have a meaning but very spesial places lile safty toggle of a gun. Putting it on some other places seems very odd to read. I couldnt find anything usefull too i might have too put the exact word toggle or something else but for now i will search see if smething comes up

Maybe there's a word in Persian for "to flip something" or just simply "flip" (noun)? This is a synonym for "toggle" in English.

> and should i wait till you make all "florisboard"s dynamic?

No, I think it would be best if you inserted it directly. I will make the `app_name` resource translatable, which will enable you to also translate the dynamically inserted string in Crowdin.

**Comment by Triplesweet** [comment]
@patrickgold ok got it and i think you can close this so it wont make issue page longer that it should be and thanks for the reply

**Comment by patrickgold** [comment]
@Triplesweet I just wanted to let you know that the `app_name` resource string is now translatable and can be edited on Crowdin.

**Comment by Triplesweet** [comment]
@patrickgold and just wanted to say i am changing it at this moment and doing some fixes too😇 There was another guy who translated it but had some small google translate problems. 😂

**Comment by Triplesweet** [comment]
Ps. Im not really that good in eng but im doing my best hope it all goes well

**Comment by patrickgold** [comment]
@Triplesweet Thanks for your work, I really appreciate it!

P.S. Your English skills are pretty good in my opinion, I rarely see grammatical or other errors :)
