### ISSUE TITLE
Bitwarden autofill is broken 

### ISSUE THREAD

**Issue by derei** [florisboard/florisboard#2542]
### Short description

Since the most recent update (0.4.0-rc01 (96)), Bitwarden autofill doesn’t work anymore.
It does work with other keyboards, but not with Floris anymore.

### Steps to reproduce

Self explanatory.

### FlorisBoard Version

0.4.0-rc01 (96)

### Install Source

F-Droid

### Device

Google Pixel 7 Pro

### Android

GrapheneOS

**Comment by phk-nord** [comment]
Are you certain the issue lies within florisboard? It seems fine with both v0.4.0-rc01 and v0.4.0-rc02. However it is depended on the website if you will get a keyboard autofill extension. As example https://paypal.com/signin will almost never trigger bitwardens keyboard extension but the login of https://chat.openai.com always does. 

I am just replying to this issue as isn't too well known that a website is entirely responsible how an autofill is triggered or even if any will be triggered. 
You can always use bitwardens accessibility services for an additional autofill prompt button next to fields 

https://github.com/user-attachments/assets/4e137064-f276-4bbc-a97b-f7ecc43dabab

**Comment by derei** [comment]
@phk-nord you are correct that on certain websites and apps it wasn't triggered even before. But now it isn't triggered anywhere.
However, if I switch to stock keyboard (GrapheneOS), or even the voice input [Transcribro](https://github.com/soupslurpr/Transcribro), the autofill prompt is being triggered.

**Comment by derei** [comment]
@phk-nord I just tested with the PayPal app: with Floris, the autofil was not triggered at all, but with stock kb and transcribro, it was triggered foe both username and pwd.

**Comment by MattRC7** [comment]
Confirming I also experience this with:
- Florisboard 0.4.0
- Android 14 (Graphene OS)
- Keepass2Android 1.10-pre
- Aegis Authenticator 3.2

When I open Aegis, the inline autofill from Keepass2Android no longer appears. Unfortunately I cannot revert to Florisboard 0.3.16 via F-Droid (unknown error). However, I know it was working yesterday.

**Comment by patrickgold** [comment]
Can you please test the debug artifact of linked PR to check if Bitwarden works with the new implementation? On my side Bitwarden works really well, thus I need users like you to confirm if it also works on your device.

**Comment by MattRC7** [comment]
> Can you please test the debug artifact of linked PR to check if Bitwarden works with the new implementation? On my side Bitwarden works really well, thus I need users like you to confirm if it also works on your device.

I just tried downloading the debug artifact, loading my saved settings (including enabled system autofill) and tested some autofills. Unfortunately none of the apps I tested worked.

I grabbed the logs from this test, maybe they will help: 

![FlorisBoard Debug log 1b8273ed0d42.txt](https://github.com/user-attachments/files/17199443/FlorisBoard.Debug.log.1b8273ed0d42.txt)

My specs for reference:

- Florisboard 0.4.0
- Android 14 (Graphene OS)
- Keepass2Android 1.10-pre (my passwd manager)
- Aegis Authenticator 3.2 (app I tested with)

**Comment by patrickgold** [comment]
Ok thanks for testing, I will have a look on the log later on my Laptop. Can you try enabling the following: In FlorisBoard Debug Settings > Advanced > Devtools > (Enable if necessary) > Show inline autofill overlay

Does the overlay then show that there were inline autofill options provided?

**Comment by patrickgold** [comment]
I had a look at the log and it indicates that the inline autofill suggestions are correctly received (when a request is incoming), so it does not make sense that none of the apps worked. I think that testing with the debug overlay is important, because it always reflects the current inline suggestion state.

**Comment by MattRC7** [comment]
> Can you please test the debug artifact of linked PR to check if Bitwarden works with the new implementation? On my side Bitwarden works really well, thus I need users like you to confirm if it also works on your device.

I just tried downloading the debug artifact, loading my saved settings (including enabled system autofill) and tested some autofills. Unfortunately none of the apps I tested worked.

I grabbed the logs from this test, maybe they will help: 

![FlorisBoard Debug log 1b8273ed0d42.txt](https://github.com/user-attachments/files/17199443/FlorisBoard.Debug.log.1b8273ed0d42.txt)

My specs for reference:

- Florisboard 0.4.0
- Android 14 (Graphene OS)
- Keepass2Android 1.10-pre (my passwd manager)
- Aegis Authenticator 3.2 (app I tested with)

**Comment by MattRC7** [comment]
Okay, I tried enabling the dev tool setting you mentioned and testing it there. I'm not very familiar with the logs but the overlay does appear to be showing an autofill option. Here's a screenshot and the logs:

![screenshot of a website login page with the inline autofill overly which has the number 1 in parenthesis and data for an NlpInlineSuggestion](https://github.com/user-attachments/assets/608b95d9-66cf-42ba-bc4f-b4176c586ab3)

Here are the logs too: [FlorisBoard Debug log 372a846d5788.txt](https://github.com/user-attachments/files/17214057/FlorisBoard.Debug.log.372a846d5788.txt)

**Comment by patrickgold** [comment]
Based on the screenshot ptovided is your Smartbar layout set to actions only? (FlorisBoard Settings > Smartbar > Layout)

With this on I can fully reproduce your issue, because if only actions are enabled the UI component responsible for displaying the inline autofill suggestions is not existent and thus does not show the inline suggestions...

**Comment by MattRC7** [comment]
> Based on the screenshot provided is your Smartbar layout set to actions only? (FlorisBoard Settings > Smartbar > Layout)
> 
> With this on I can fully reproduce your issue, because if only actions are enabled the UI component responsible for displaying the inline autofill suggestions is not existent and thus does not show the inline suggestions...

Doh, you are right! After enabling the suggestions bar it works.

![the autofill appears in the suggestion bar](https://github.com/user-attachments/assets/a7b5ab4b-28e2-4154-9bca-ddf205fc8702)

Unfortunately for the original ticket, this also now works for me in the non-debug app. Which means it may have always worked for Keepass2Android, and my test may not prove that it works for Bitwarden 😕

I'm sorry to waste your time...

**Comment by derei** [comment]
I tested if it works with Bitwarden when Suggestions are enabled: it does work indeed.

But, because suggestions are not implemented yet, it's quite annoying to see "next0", "next1" ... hence I never had it enabled.

Question: (until suggestions will be implemented), is it possible to have an options where Actions+Autofill can be enabled for smartbar, but without suggestions?

![Screenshot_20241002-052512](https://github.com/user-attachments/assets/f85f34f4-911c-4216-98ba-a1be8832f0ce)

![Screenshot_20241002-052540](https://github.com/user-attachments/assets/0eef1a65-11fc-4340-8daa-10f6088159dd)

**Comment by lm41** [comment]
The placeholder suggestions  are removed in the upcoming release.

**Comment by patrickgold** [comment]
> I'm sorry to waste your time...

No worries, at least now I cleaned up the logic and have a debug utility for inline autofill.

Also with this issue we discovered a big UX issue in settings, where it is not directly clear for the user that changing the Smartbar layout causes inline autofill to not show up anymore, here we need to add a warning box or something.

**Comment by derei** [comment]
@patrickgold or, to control inline autofill individually from the other settings. This would be even better.

When one writes code, suggestions are a bother rather than help, but logging in on (github 😜), may still be necessary.

**Comment by patrickgold** [comment]
Inline suggestions itself are a seoarate toggle from normal word suggestions already, but depend on the Smartbar suggestions layout to be shown currently.

One idea I currently have is to only allow actions-only if you have no.other suggestion setting enabled

**Comment by patrickgold** [comment]
Or another idea is to add an additional inline autofill layer to the Smartbar sandwich, which always shows up if inline autofill is enabled and there are autofill suggestions to show
