### ISSUE TITLE
Why Floris provides me these crazy suggestions?

### ISSUE THREAD

**Issue by serrq** [florisboard/florisboard#2545]
### Short description

There aren't normal words, but stranges ones in suggestions bar.

### Steps to reproduce

1. Write something in English
2. See the tool bar, suggestions are strange

![1000118288](https://github.com/user-attachments/assets/f713beb6-f88a-429f-a376-1eaee5a003d9)

### FlorisBoard Version

0.4.0 rc02

### Install Source

F-Droid (Izzy)

### Device

OnePlus CPH2399

### Android

14

**Comment by lm41** [comment]
https://github.com/florisboard/florisboard/blob/master/README.md#highlighted-features

**Comment by lm41** [comment]
The word suggestions aren't implemented in the current version. They are a major goal for the 0.5 milestone.
