### ISSUE TITLE
When the prompt cursor is behind the text and one pushes the "x" button on keyboard, then the destination path changes (while save a backup)

### ISSUE THREAD

**Issue by serrq** [florisboard/florisboard#2546]
### Short description

The path changes when one deletes text on backup name.

### Steps to reproduce

1. Do a backup.
2. Change its name, wiping text until reach the back boundary.
3. If you push yet the "x" button (delete) the path changes.

![1000118293](https://github.com/user-attachments/assets/88435424-cfcf-4e43-b038-cfc461bb208e)

### FlorisBoard Version

0.4.0 rc02

### Install Source

F-Droid (Izzy)

### Device

OnePlus CPH2399

### Android

14

**Comment by lm41** [comment]
This is the file picker UX from android itself. This is not within the scope of the florisboard project.
