### ISSUE TITLE
Incognito (face with glass and hat) not manageable in some circustances

### ISSUE THREAD

**Issue by serrq** [florisboard/florisboard#2548]
### Feature idea

In addition to this, is it possible remove the "incognito" face from the keyboard background?

I dont love that position. I cannot seeing clearing the keys.

![1000118300](https://github.com/user-attachments/assets/fc32ec55-d736-4cb8-8b75-2203982c2e1c)

**Comment by lm41** [comment]
Yes it is. 
Settings -> Keyboard - Incognito indicator
