### ISSUE TITLE
Add support for haptic feedback on Pixel devices

### ISSUE THREAD

**Issue by Mattrazol** [florisboard/florisboard#255]
Is it possible to add the haptic feedback on the devices that supports it (example pixel), instead of the regular vibration?

**Comment by patrickgold** [comment]
Thanks for your suggestion! Will add this to the v0.5.0 milestone!

**Comment by serebit** [comment]
I'd like to look into implementing this myself and submitting a PR, but I'm unsure of how the UI setting should look and how it should affect existing options. For example, I believe haptics should be default on supported devices, but should the presence of haptics support disable other vibration settings entirely? Any insight would be very helpful, @patrickgold.

**Comment by patrickgold** [comment]
@serebit I would do it this way: leave the current vibration settings as they are. Directly below I would add these preferences which only show if the device supports haptic feedback:

```
<SwitchPreference "Enable haptic feeback" />
<Other Preference(s) for haptic feedback  ../>
```

As I don't know to what extend you can customize haptic feedback, it is your decision to add customization preferences for this under the switch.

If the switch is enabled, the vibration preferences should be greyed out (set isEnabled=false for these preferences in the KeyboardFragment.kt logic) to indicate that using haptic feedback disables the "normal" vibrations.

In the core class where the vibration preference is read, you have to correctly interpret the preferences as well. Meaning that the switch can be true even though haptic feedback isn't even supported on that device.
