### ISSUE TITLE
There have not showing word suggestion while i type 

### ISSUE THREAD

**Issue by Prince060712** [florisboard/florisboard#2552]
### Feature idea

User distonary file , add the word suggestion 
![Screenshot_20240906-131414](https://github.com/user-attachments/assets/c861e6bc-25bf-4e1e-a5fd-6d02e83316dc)
Its only showing this

**Comment by tsiflimagas** [comment]
Word suggestions aren't implemented yet, these are just placeholders. This feature will come in v0.5.
