### ISSUE TITLE
Change language by swiping space bar

### ISSUE THREAD

**Issue by HzbiTigrinya** [florisboard/florisboard#2553]
### Feature idea

Sometimes I accidentally tap on the utility key (that i use to change languages) instead of the space bar creating a mess lol. So if possible I think swiping the space bar would be better for people that use multiple languages.

**Comment by Glitchy-Tozier** [comment]
Hi there, I'm pretty certain this already exists.
Could you go to **Settings** → **Gestures & Glide typing** → scroll down to **Space bar gestures** and check the **Swipe left/right** options?

**Comment by HzbiTigrinya** [comment]
Oh thanks! I only searched in the Language options. I tried the gestures on the keyboard, it worked and changed languages once for me but I couldnt return to English the same way and had to re-enable the utility key to change back.

For the space button gestures it didnt work at all. Does it work for you? Just to make sure its not device specific

**Comment by HzbiTigrinya** [comment]
*Solution found*
It seems my swipes were not fast enough.
After changing the swipe velocity threshold from 1900 dp/s to 400 dp/s I can succesfully change languages without any issues.

Thanks for your time

**Comment by HzbiTigrinya** [comment]
*Solution found*
It seems my swipes were not fast enough.
After changing the swipe velocity threshold from 1900 dp/s to 400 dp/s I can succesfully change languages without any issues.

Thanks for your time

**Comment by Glitchy-Tozier** [comment]
Great to hear we got it working! Ty for testing it out and closing the issue! :)

**Comment by mthecolt** [comment]
Had the same problem until I changed the swipe velocity threshold to the lowest value. (Shouldn't that be the default?)

It's easier now, although I still wish it can go even lower so that every swipe can register.
