### ISSUE TITLE
Inability to Append any Actions  to Singular Entry Rows

### ISSUE THREAD

**Issue by D-Maxwell** [florisboard/florisboard#2556]
Dragging any actions to an almost empty row will either fail and instantly snap back or will replace the only element present rather than being appended next to it.

**Comment by patrickgold** [comment]
Is this issue related to the drag&drop in the quick actions reorder UI?

**Comment by D-Maxwell** [comment]
> Is this issue related to the drag&drop in the quick actions reorder UI?

Yes, my apologies as i had forgotten to mention this fact after having my initial draft lost to my cellular's ram management.

**Comment by KevinVan9** [comment]
I assume this is the behavior of the icon when it is dragged to the empty space in the row. To get it to the the row, the item must cross the bounds an item in the desired row
