### ISSUE TITLE
layout and popup mapping is missing for Tamil(srilanka)

### ISSUE THREAD

**Issue by sudhegan** [florisboard/florisboard#2558]
### Short description

The Popup mapping and Characters layout is missing for Tamil (srilanka)

but as i understand it is already added by this commit https://github.com/florisboard/florisboard/commit/2d9605fbdaf384160a3d2fca279076ce4198943d

this commit has the layout and lables for that but cannot see these in app

### Steps to reproduce

1. Go to : Languages and layout
2. Click on : add subtype
3. Scroll down to : select Tamil(Srilanka) from subtype presets
4. See error : but the Popup mapping and Charaters layout is missing and has no relevant option  is available to select

### FlorisBoard Version

0.4.0-rc02(97)

### Install Source

GitHub

### Device

Motorola Edge 30

### Android

14 (cn=UPSIDE_DOWN_CAKE sdk=34) [U1RD34.80-40]

**Comment by tsiflimagas** [comment]
#2514 addresses this.
