### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by felschr** [florisboard/florisboard#257]
Hi, I like where FlorisBoard is headed, and I'd like to support it.
Do you accept donations?

**Comment by patrickgold** [comment]
Glad you like FlorisBoard!

I am currently not accepting donations, as my primary goal with this project is to learn building an open-source software, how to engage with the community and how to publish and maintain such a thing in the long-term. I am unsure if I will ever be accepting donations or if FlorisBoard will only accept other contributions (translations, PRs, feedback, ideas, etc.), as accepting donations also creates an administrative burden of managing these.

Hope you can understand my viewpoint.

- Patrick

**Comment by lethallunatic** [comment]
You could setup crypto wallets and accept crypto donations? 😁 That's shouldnt be too hard.

**Comment by Tmpod** [comment]
I understand Patrick's concerns. If he intends to maintain FloorisBoard as a libre and open project, I'd assume he'd also want to keep earnings and donations open and transparent if he was to accept them. That adds more management work into the equation, and since he's the only maintainer, it could negatively impact the project overall.

**Comment by TPS** [comment]
@patrickgold As an interim solution, why don't you link to _your_ favorite causes who _do_ need donations?  (I recommend non-controversial — anti-slavery, homeless, children's hospitals, &c.)  Then whoever wishes to could do so in thanks to FlorisBoard & devs.

**Comment by patrickgold** [comment]
@TPS That is indeed a wonderful idea which I could add to the README in place for the donation button. I will keep this idea in mind!

**Comment by lawson85** [comment]
People need to be able to download this keyboard from play store without having to join groups  I am fine with it however, i wish to be able to search in play store for it

**Comment by patrickgold** [comment]
As there are continuous requests in emails that I should add options for them to support me via a donation, I've finally read through all the legal stuff for my country when it comes to accept financial contributions. I've now set up options to donate and support my work on this project. For now, there are three options: PayPal, Bitcoin and GitHub sponsors, see the sponsors button menu for the exact links.

I still want to point out though that the most valuable contribution for me is when others engage in making PRs, adding layouts, discussing features with me or others, pointing out bugs, etc., though for some who want to show their love for my work this way this is now an additional option.
