### ISSUE TITLE
Landscape keyboard position in private mode

### ISSUE THREAD

**Issue by domy86** [florisboard/florisboard#2573]
### Short description

Hi,

I use FlorisBoard for very long time and this bug bothers me a little bit as keyboard takes more space than it should.

![Screenshot_20240919_113413_org mozilla firefox_beta](https://github.com/user-attachments/assets/fdf85b19-cfff-4955-9678-1b44dfaa5c18)

![Screenshot_20240919_113417_org mozilla firefox_beta](https://github.com/user-attachments/assets/ef860942-cded-4992-b6c2-9d8f288a3bdc)

![Screenshot_20240919_113557_dev patrickgold florisboard](https://github.com/user-attachments/assets/ff481fa1-9f99-4929-9c4f-0bee0820c81a)

The position in normal mode is correct, problem is only with private mode in landscape.

### Steps to reproduce

1. Go to Firefox or Edge private window and rotate a phone to activate landscape mode.
2. Click on some text box to start writing.

### FlorisBoard Version

0.4.0

### Install Source

GitHub

### Device

Huawei Mate 20 X

### Android

10

**Comment by wardahub-design** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by kizaski** [comment]
I found the culprit line, it's

https://github.com/florisboard/florisboard/blob/56bbe9d13c7a5dd30d8529e41097203bd7dde1de/app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/TextInputLayout.kt#L77

Changing it to something smaller like 152.dp makes this issue go away. I'm not really sure what to do to fix it though.
