### ISSUE TITLE
Swipe typing issue for spanish language

### ISSUE THREAD

**Issue by Maximiliem** [florisboard/florisboard#2579]
### Short description

When I try to write in spanish with swipe typing, the keyboard recognizes only English words, so I can't use this feature to write in spanish.
I don't know if this happens with other languages.
Thanks!

### Steps to reproduce

1. Go to 'Idiomas & Distribuciones'
2. Create a new Subtype
3. Select Español Uruguay
4. Try to write with swipe typing

### FlorisBoard Version

0.4.0

### Install Source

Google PlayStore

### Device

Xiaomi Poco M3 Pro

### Android

13, TP1A

**Comment by kizaski** [comment]
If you mean glide typing, I see in the debug version that this has been disabled and will be re-implemented.

![Screenshot_20240921_162332](https://github.com/user-attachments/assets/55c2e185-d378-4407-bd1d-69367fc88e8e)

**Comment by Maximiliem** [comment]
@kizaski oohhh thanks for your answer!!! And my apologies! I really appreciate your answer!!!

**Comment by patrickgold** [comment]
As stated in the text in the screenshot this feature will be re-implemented in v0.5 (or v0.6), closing this issue thus to avoid duplicate discussions.
