### ISSUE TITLE
Integration of Google/Yandex translator into the keyboard 

### ISSUE THREAD

**Issue by authorless** [florisboard/florisboard#2581]
### Feature idea

The idea is to add/integrate Google/Yandex translator into the keyboard, because I think this feature is important to many. Personally, for this reason, I cannot fully use your abbreviation, although I really like it. The absence of T9 is also disappointing, which would also be useful.

**Comment by authorless** [comment]
Of course, I understand that this is not the topic and it will be a long process, but we could try to add AI to the abbreviation

**Comment by patrickgold** [comment]
In general adding a translation idea is something I can imagine and is accepted as a proposal, however the translation engine used must align with the privacy goals of this keyboard, which Google/Yandex clearly do not. Some examples could be integrating Mozilla Translate or something similar, but the model used must work offline.
