### ISSUE TITLE
Dialog window buttons are not responsive to device width

### ISSUE THREAD

**Issue by AmroLouwe** [florisboard/florisboard#2582]
### Short description

Chnaging settings of keyboard dont get saved or applied at all.  That applies to all setrings i have tried excepr for choosing themw ((light,  dark,  pure night) 

### Steps to reproduce

Applys to all settings; changing settings of volume,  height of keyboard,  emoji skin tone etc... 

### FlorisBoard Version

0.4

### Install Source

Google PlayStore

### Device

Pixel 8 pro

### Android

14

**Comment by patrickgold** [comment]
I need more information on what exactly does not apply, because you are the first and only to report this issue on a wide-spread scale. If you refer to the utility key action, see #2587.

Also please make sure that if you have more than 1 version of FlorisBoard installed at the same time (e.g. 0.4. and 0.4.rc02) these do NOT sync on purpose, each of those installations operates isolated from each other.

**Comment by AmroLouwe** [comment]
Hi there,


I am.using Version 0.4.0 (98)

Settings that dont get applied:

1) changing system (app) language; its uses my system settings, trying to change that to engkish or anyother language doesnt get applied/saved

2) space bar/button label; set to name of language, cant be changed to space icon or no label.

3) adjusting button size set to 100, adjusting it doesnt get applied or saved

4) adjusting keyboard height set to 100,

5) adjusting keyboard volume for typing is set to 50 and adjusting it doesnt cause any effect or get saved

6) adjusting vibration duration or strenght.

7) adjusting vibration mood between direct and florisboard


It might be worth mentioning that while adjusting the settings i get two choices under standard and cancel, no button that says apply.


Also like i said in the original post, adjusting the theme into dark does work. Also adding a number row works fine, showing or hiding symbols work fine (things that has on and off switch seem to work fine)


I have tried restarting the phone for settings to apply but didnt help. Reinstalling the app didnt seem.to solve the issue either.


Is there any more specific information you need to help solve this issue?


Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by patrickgold** [comment]
> It might be worth mentioning that while adjusting the settings i get two choices under standard and cancel, no button that says apply.

There should be three buttons, in order left-to-right: Default, Cancel and OK (OK acts as apply). If not please send a screenshot.

> 1) changing system (app) language; its uses my system settings, trying to change that to engkish or anyother language doesnt get applied/saved

**Comment by AmroLouwe** [comment]
Here is a screenshots of the menu that shows up trying to change the settings in both portrait and landscape modes that doesnt show a button.

However, reading your reply i have tried to click on the far right side of next to (Annuleren = Cancel), it did cause it to highlight a button that is not visible or empty.  And that seems to have fixed the issue. See 3rd screenshot that shows the highlighted empty button

My guess would be it has to do with how long the words are in different languages (mine is Dutch),
So maybe the fix is merely adjusting the font size of buttons or spacing between them or the Ok button to be under the other ones to make sure they are visible in all languages.

Thanks so much for quickly contacting me and as our communication helped sort put the issue rather quickly.

I hope at least this have helped knowing where. The issue lays for other people om the future.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>

________________________________
Van: Patrick Goldinger ***@***.***>
Verstuurd: maandag, september 23, 2024 2:02:26 p.m.
Aan: florisboard/florisboard ***@***.***>
CC: AAL ***@***.***>; Author ***@***.***>
Onderwerp: Re: [florisboard/florisboard] Changing settings dont apply or get saved (Issue #2582)


It might be worth mentioning that while adjusting the settings i get two choices under standard and cancel, no button that says apply.

There should be three buttons, in order left-to-right: Default, Cancel and OK (OK acts as apply). If not please send a screenshot.

  1.  changing system (app) language; its uses my system settings, trying to change that to engkish or anyother language doesnt get applied/saved

**Comment by patrickgold** [comment]
I do not see the screenshots, they seem to got lost in your email reply.

> My guess would be it has to do with how long the words are in different languages (mine is Dutch),

Yes I think that's some localization issue, can you change the FlorisBoard in-app language to English and check the behavior then? I referenced the NL string for ok though and it is set properly

**Comment by patrickgold** [comment]
![Screenshot_2024-09-23-15-59-14-15_c853220993b0ed55eb2e57645fcd343d.jpg](https://github.com/user-attachments/assets/f62ec64b-1d1c-438b-a246-685ba0bdf512)

Ok yes it is defibutely a localization issue, can reproduce it with Bulgarian. Re-tagging the issue

**Comment by AmroLouwe** [comment]
Yes,  since i found the empty button area and clicked it,  it saved the language of florisboard to English and then the button ok is completely visible. If i switch it back to dutch then it hides again,  but now i know where to find it.  Even changing other settings (where the ok button was not visible)  works the same way.
Like you said its localization issue due to the display language.

I have reattached the screenshots to this reply.  If you still cant see it,  let me know how can i best forward it to you.


Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by patrickgold** [comment]
As I can now fully reproduce this issue it is an easy fix, so no need for you to send the screenshots anymore, but thanks
