### ISSUE TITLE
action bar is misaligned with the keys in shared layout

### ISSUE THREAD

**Issue by xronin01** [florisboard/florisboard#2583]
### Short description

![Screenshot_20240921-195539_FlorisBoard](https://github.com/user-attachments/assets/a09735d0-9751-4878-9774-1b4864efedc8)
![Screenshot_20240921-195555_FlorisBoard](https://github.com/user-attachments/assets/1e6250f9-a23b-449c-9064-9635ee4e5382)

### Steps to reproduce

.

### FlorisBoard Version

0.4.0

### Install Source

GitHub

### Device

.

### Android

11

**Comment by lm41** [comment]
This is not a bug. The alignment of the quickactions with the other keys of the keyboard is device width and keyboard layout specific. The alignment you are seeing is just a coincidence as you can see in the image below. (Default configuration with 'Actions only' Smartbar)

![image](https://github.com/user-attachments/assets/d2aa82a8-b4ac-476b-a3fa-80246ad64fdc)
