### ISSUE TITLE
Play Store Uses Old App-Icons

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#2589]
### Short description

The Google Play Store uses old app-icons. I suggest updating to the newest ones.

![PlayStoreScreenshots](https://github.com/user-attachments/assets/541b5c47-ad1a-433f-8080-2b4fc4e7a487)

### Steps to reproduce

1. Search for FlorisBoard on the Google Play Store
2. See old icons

### FlorisBoard Version

0.4.0

### Install Source

Google PlayStore

### Device

Samsung Galaxy S9

### Android

10

**Comment by patrickgold** [comment]
Changed and sent the new icons for review in the Play Dev Console, so it may take a few days for them to show up.
