### ISSUE TITLE
Thanks you Soo much😘

### ISSUE THREAD

**Issue by shockergit** [florisboard/florisboard#259]
Im a swiftkey user for many years. Just came to know about the app from fdroid. I have to say this is one of the best keyboad app i have used please upload to google play store and dont sell to google. This app have tremendous chance for coming to top in future.Just add two features 
1)next word suggestion
2)clipboard manager

**Comment by patrickgold** [comment]
I am happy to see that you like FlorisBoard, thanks for the positive feedback!

> please upload to google play store

The closed alpha track is already on the Google Play Store, see the README for details on how to join it.

> Just add two features
1)next word suggestion
2)clipboard manager

Both are already planned, suggestions for v0.4.0 and clipboard manager probably for v0.5.0
