### ISSUE TITLE
Publish stable versions on the beta-track

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#2590]
### Feature idea

For testing the app as a beta-user, it would be the convenient to also get supplied with the stable release on the beta-track.  (if it currently is the most recent version.)
This way, users & testers of the most recent version could simply stay on the beta-track instead of having to switch to the stable track for each stable release.

That release could be
- The last rc: `v0.4.0-rcFinal`
- Simply `v0.4.0`
- The first rc for the next version: `v0.4.1-rc00`

**Comment by patrickgold** [comment]
I am aware that there needs to be some kind of dual-release for some of the stable versions. See the idea posted here: https://gitlab.com/IzzyOnDroid/applists/-/issues/27 , it addresses it in a relatively simple way. However the exact approach is not set in stone yet.

**Comment by Glitchy-Tozier** [comment]
Neat! Will that also work on the Play Store?

**Comment by patrickgold** [comment]
Yes, as I just need to also build duplicate aab files and push them to Google

**Comment by Glitchy-Tozier** [comment]
Looking forward to getting the update! :)

**Comment by patrickgold** [comment]
Dual-release support has been added, with the not-yet published v0.4.1 these will go live :)
