### ISSUE TITLE
 Add toggle for popup selection method

### ISSUE THREAD

**Issue by Valentin-N** [florisboard/florisboard#2593]
### Feature idea

_Note: copy-pasted and reworded from https://github.com/florisboard/florisboard/issues/949._

### Short description
Selecting a key from a popup is unintuitive because the selection position does not match the finger position on screen. E.g., when long pressing the `a` key to select the `@` sign you can't simply move your finger on top of the `@` sign. Instead one has to slide their finger position to some designated empty space below the `@` sign, but never really knowing if they've moved their finger enough or too much. This is even less intuitive when there are more rows in the popup. This is not intuitive because it breaks away from the general UX where the finger directly controls elements on screen through touch. It also likely prevents muscle memory from forming.

The request is to add a toggle to be able to directly select keys from a popup.

### Steps to reproduce
1. open the keyboard
2. long press the `a` key
3. try to select the `@` sign
4. directly selecting the key does not work
5. sliding your fingers 2 rows below will select the `@` sign

**Comment by patrickgold** [comment]
Hi there!

The described behavior sounds very unintuitive to me, because if the active popup letter is below the finger you never see what's under the finger, that makes no sense to me. There is a reason why the constant y-offset is there, so you are actually able to see what you will input once you release your finger. This is also for the most part industry standard.

Popup calculation is complicated as it is and to avoid complicating it further with conditionals based on a toggle the popup UX will stay like this, hope you can understand.

**Comment by Valentin-N** [comment]
Thanks for reviewing. I understand the reluctance, but I have to disagree with the brief conclusion.

I see two completely different behaviors when tapping things in this keyboard, which makes using this keyboard unintuitive:
1. Selecting everything directly with your finger: what the finger touches is what gets selected. This applies to most keys and is also the default expectation across Android. This allows muscle memory to form as there is a direct relationship between the finger position and the element that gets activated.
2. As an exception to the general rule above, for popups the selection does not follow the finger, but like you describe there's an offset. This offset is unintuitive and I feel that the benefit of seeing what is selected is not enough to compensate for the drawback of having to always slow down to select the proper symbol or accent. I am fine with not seeing what I tap on for most other Android things and I assume so are most other Android users.

> This is also for the most part industry standard.
I don't have data on hand, but I just checked the following keyboard and they all have the behavior requested as an option here: AOSP keyboard, AnySoftKeyboard, Samsung keyboard, IOS keyboard, Hacker Keyboard, Technical Keyboard. Besides Gboard, I couldn't find a single other keyboard that has this behavior.

In https://github.com/florisboard/florisboard/issues/949 you seemed a lot more receptive to the same request. Do you have more insights that you could share that led to the summary rejection for the exact same request this time without further consideration?

**Comment by lm41** [comment]
![Screenshot_20240923-144145.png](https://github.com/user-attachments/assets/70e4aef0-179c-40f1-a07c-c5f1ec4b5077)

White dot = where my finger is

As you can see the behavior is the same in AOSP.

**Comment by Valentin-N** [comment]
@lm41 if you move your finger towards one of the accents, your finger has to rest on the target on it for a selection. For your example if you wanted to select `æ` your finger would have to rest on it.

**Comment by Valentin-N** [comment]
@lm41 I'm seeing the behavior I described in the previous messages. I personally tested the keyboards I mentioned in the previous message before posting.
![Screenshot_20240923-142339](https://github.com/user-attachments/assets/a0bb1631-8e87-4d1f-98b5-c68eadf25541)
![Screenshot_20240923-142612](https://github.com/user-attachments/assets/32fac029-6d2b-4806-a2dd-74b48e45c53e)
