### ISSUE TITLE
Add arrow-symbols

### ISSUE THREAD

**Issue by heschy2** [florisboard/florisboard#2601]
### Feature idea

First of all, please excuse my bad english.
Sometimes I want to write `→` (or `←`) but the closest you can get on mobile is this: `->` and it looks very ugly. It would be cool if the arrows could be added to the long-press options of `<` and `>`.

**Comment by maivohun** [comment]
![Screenshot_2024-09-26_04-05-47](https://github.com/user-attachments/assets/d642c8d1-9fa1-40d8-b3c2-3cbe77d2fd51)

Long press the caret `^` key.

**Comment by BHydden** [comment]
Your English was perfect ❤️ you can find both the characters you are looking for with a long press on `^`
