### ISSUE TITLE
"Preferred emoji skin tone" breaks emoji suggestions

### ISSUE THREAD

**Issue by maivohun** [florisboard/florisboard#2604]
### Short description

Choosing a different skin tone for emojis break the newly added emoji suggestions.

Default skin tone:
![Screenshot_2024-09-26_03-28-14](https://github.com/user-attachments/assets/b7f33bcd-e137-469c-ae1d-bbe0861b8593)

Any other:
![Screenshot_2024-09-26_03-27-43](https://github.com/user-attachments/assets/1ba63f5c-8b39-4d25-b12d-4e55592c4ef0)

### Steps to reproduce

1. Enable suggestions
2. Select a different emoji skin tone
3. Type ":love" or any other emoji name
4. Emoji suggestions are limited to emojis that support the  selected "preferred skin tone"

### FlorisBoard Version

0.4.0-rc02 (97)

### Install Source

F-Droid

### Device

Nokia 6.1 & OnePlus Nord

### Android

10 & 14

**Comment by patrickgold** [comment]
Yep tested and reproducible, will address this before the 0.4.1 release
