### ISSUE TITLE
Built-in KeepassDX button functionality

### ISSUE THREAD

**Issue by A1eeeee** [florisboard/florisboard#2608]
### Feature idea

Although FlorisBoard has a built-in autofill service, sometimes it often fails without prompting, and you need to switch the KeepassDX input method for input. Can FlorisBoard directly build in KeepassDX to directly search for accounts and passwords? The KeepassDX button is built into the smart bar.

**Comment by A1eeeee** [comment]
![Uploading Screenshot_2024-09-28-12-54-48-664_mark.via-edit.jpg…]()

**Comment by A1eeeee** [comment]
![Screenshot_2024-09-28-12-54-48-664_mark via-edit](https://github.com/user-attachments/assets/218f5595-8e6b-4cd7-8b10-d9e35a7f061f)

**Comment by A1eeeee** [comment]
It may not be practical to build the entire KeePass application directly into FlorisBoard.
Create a KeepassDX search button in the smart bar. Click Jump to KeepassDX to select the data and return the data to FloriBoard. At this time, the smart block has the account, password, and totp buttons, and you can directly click the corresponding buttons to automatically output KeepassDX data

**Comment by A1eeeee** [comment]
> ![Screenshot_2024-09-28-12-54-48-664_mark via-edit](https://private-user-images.githubusercontent.com/118139709/371727673-218f5595-8e6b-4cd7-8b10-d9e35a7f061f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MDAxNjQsIm5iZiI6MTcyNzQ5OTg2NCwicGF0aCI6Ii8xMTgxMzk3MDkvMzcxNzI3NjczLTIxOGY1NTk1LThlNmItNGNkNy04YjEwLWQ5ZTM1YTdmMDYxZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwNTA0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGFjYjA0ZmI5OGU4NDg4YTlhYzQ0MDU0ZTgwZmYwMzFmOTRlNDA0NDE3NDQ3NzYyMDA4ZThiY2IyMDYwMzhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PUHz2F3JutqP_7pxqF5f994e27FT-HOexjIRrJI3YtY)

It may not be practical to build the entire KeePass application directly into FlorisBoard.
Create a KeepassDX search button in the smart bar. Click Jump to KeepassDX to select the data and return the data to FloriBoard. At this time, the smart block has the account, password, and totp buttons, and you can directly click the corresponding buttons to automatically output KeepassDX data

**Comment by A1eeeee** [comment]
> ### Feature idea
> Although FlorisBoard has a built-in autofill service, sometimes it often fails without prompting, and you need to switch the KeepassDX input method for input. Can FlorisBoard directly build in KeepassDX to directly search for accounts and passwords? The KeepassDX button is built into the smart bar.

It may not be practical to build the entire KeePass application directly into FlorisBoard.
Create a KeepassDX search button in the smart bar. Click Jump to KeepassDX to select the data and return the data to FloriBoard. At this time, the smart block has the account, password, and totp buttons, and you can directly click the corresponding buttons to automatically output KeepassDX data
![Screenshot_2024-09-28-12-54-48-664_mark via-edit](https://github.com/user-attachments/assets/ee088bc8-6037-40b9-8a5b-caa1280361d5)

**Comment by patrickgold** [comment]
Please see PR #2613, which majorly reworks the inline autofill suggestions, fixing some UX issues and bugs, so the inline autofill from password managers should be more stable now.

As for the request of integrating KeePassDX directly into FlorisBoard I have to reject this proposal, as this is out-of-scope for this project. Closing thus.
