### ISSUE TITLE
Auto-delete sensitive clip data in clipboard history

### ISSUE THREAD

**Issue by alejandracios** [florisboard/florisboard#2610]
### Feature idea

Hi all,
New with Florisboard. Excellent project and keyboard. 
I noticed when copying from password manager and you have clipboard history enabled (plus the sync function) whatever you copied from PM wont be deleted from the history. 
I set the clipboard history to autodelete on 10 minutes, so no big deal but probably you may consider to build some interactions or add a section where you can restrict apps to save history. 
I use ditto on windows and have restricted keepassxc to track history and works well.

Thanks for yiur hard work on this.

**Comment by patrickgold** [comment]
Related #2510
