### ISSUE TITLE
Keys are stretched when opening "=/<" on characters (bug ?)

### ISSUE THREAD

**Issue by lalalasupa0** [florisboard/florisboard#2618]
### Short description

![Media_241004_050414](https://github.com/user-attachments/assets/e5327c11-9852-4fd4-b244-44b3c5472e43)

If there's actually a way for the edges to just be of the same height I would appreciate if someone could tell me how

I'm not sure if this a "bug" too 😵‍💫

### Steps to reproduce

Not sure if it comes with specific steps, I use the default Spanish (Latin) distribution, but this technically happens with any, or at least it does with Russian and Japanese language, although only when entering "?123"

### FlorisBoard Version

0.4.0 (98)

### Install Source

F-Droid

### Device

Samsung

### Android

Android 12

**Comment by patrickgold** [comment]
Not really a bug but a questions of layout calculation behavior. See #2616, which describes the different calculation behaviors that should be supported. Closing this to avoid duplicate discussions.
