### ISSUE TITLE
Alternate characters not visible in a landscape mode

### ISSUE THREAD

**Issue by Cysiuu** [florisboard/florisboard#2622]
### Short description

In messages app,  whatsapp or signal the most upper row have alternate characters hidden under a text field in a landscape mode

![Screenshot_20241006-234621](https://github.com/user-attachments/assets/d3dfb5c8-e173-4e03-b77a-d372a7be4b17)
![Screenshot_20241006-234611](https://github.com/user-attachments/assets/f17f04db-046c-4b56-98ac-721196aca289)

### Steps to reproduce

1. Open communicator like signal or whatsapp
2. Rotate screen to landscape mode
3. Try to access alternate characters for most upper row
4. They're hidden under the text field 

### FlorisBoard Version

0.4.0

### Install Source

GitHub

### Device

Google Pixel 7

### Android

15, Beta,  AP31.24

**Comment by lm41** [comment]
Might be related to  https://github.com/florisboard/florisboard/issues/1228

**Comment by patrickgold** [comment]
Duplicate #1803. Not related to current state bugs, the extracted input layout just draws over the popup area.
