### ISSUE TITLE
Composing region indicator unable to disable in 0.4.1

### ISSUE THREAD

**Issue by floatingatoms** [florisboard/florisboard#2627]
### Short description

Composing region indicator cannot be disabled anymore as it is tied to suggestion enabled state in https://github.com/florisboard/florisboard/pull/1913/commits/b36bcf7733ed09ae377bab7e59de68a74fed1b13 as 0.4.1 has made Suggestions unavailable.

Is this side effect intended?  

### Steps to reproduce

1. Go to Typing, disable "Display suggestions" 
2. Use keyboard and start typing
3. Characters are being underlined

### FlorisBoard Version

0.4.1

### Install Source

GitHub

### Device

Pixel 7a

### Android

GrapheneOS

**Comment by patrickgold** [comment]
Thanks for your bug report!

It is enabled because there is at least 1 suggestion type enabled that requires text history context, namely emoji suggestions. If you disable both emoji suggestions and normal suggestions the indicator will be gone. This behavior is intended, as the emoji suggestion provider makes use of the normal suggestion interfaces.

**Comment by floatingatoms** [comment]
> Thanks for your bug report!
> 
> It is enabled because there is at least 1 suggestion type enabled that requires text history context, namely emoji suggestions. If you disable both emoji suggestions and normal suggestions the indicator will be gone. This behavior is intended, as the emoji suggestion provider makes use of the normal suggestion interfaces.

Thanks so much for quick response. Didn't realise there were emoji suggestions as well, couldn't spot from info, apologies.

**Comment by patrickgold** [comment]
No worries, the emoji suggestions exited in 0.4.0 too but since 0.4.1 they got their separate toggle, so it can be easy to miss :)
