### ISSUE TITLE
Long press popup does not appear often

### ISSUE THREAD

**Issue by steadfasterX** [florisboard/florisboard#2629]
### Short description

Up to the current release I never had an issue regarding long pressing a key and then choosing from that list. I use german umlauts and special chars a lot but since v0.4.1 sometimes simply nothing happens when long pressing a key. It immediately restarts to work when I close and reopen the keyboard or by simply switching to the numbers only view and back. Then it works the whole text long but re-appears next time. 

### Steps to reproduce

1. Long press a key 
2. Sometimes it work always sometimes not

### FlorisBoard Version

0.4.1

### Install Source

F-Droid

### Device

Pixel 7pro

### Android

13

**Comment by patrickgold** [comment]
Yes that's a bug introduced by a dependency upgrade and bound to be fixed by v0.4.2 once we find the issue.

**Comment by steadfasterX** [comment]
Hm i am on 4.2.0 now but still the same for me @patrickgold . It seems to be better in my main profile but still happens often in my work profile.

 is there anything i need to do like full reset of the app or something?

**Comment by patrickgold** [comment]
No, we discovered later that this bug was one of the few state bugs not associated to the compose strong skipping mode, and we currently believe it to be a race condition. Resetting does not help as it is a runtime bug in the state of the popups. We are internally investigating and hoping to provide a fix soon as a 0.4.3 patch. See also related #2642

**Comment by steadfasterX** [comment]
Ah ok cool that its not just me 😉 thanks for the feedback!

**Comment by tom22k** [comment]
@steadfasterX 
>  is there anything i need to do like full reset of the app or something?

For me, force stopping Florisboard from Android settings (and subsequently opening it again) temporarily solves the problem.

**Comment by patrickgold** [comment]
Temporary fix is switch to symbols and back to characters and popups show again :)

**Comment by patrickgold** [comment]
Above linked PR should fix the issue, could some of you confirm that by testing the debug artifact? On my devices it now behaves correctly again.

**Comment by steadfasterX** [comment]
Great have it installed and test it from now on. Thanks

**Comment by steadfasterX** [comment]
@patrickgold tested within my work profile and main profile since yesterday and it didnt occured a single time with that debug build! Seems that solved it 👍 many thanks!!

**Comment by patrickgold** [comment]
Thanks a lot for testing and confirming the fix!
