### ISSUE TITLE
Text selector not working as intended sometimes in some websites

### ISSUE THREAD

**Issue by foss77** [florisboard/florisboard#2630]
### Short description

In the previous version of this app the text selector almost always worked but in the latest update i have found it does not work at certain places where it used to work on previous version e,g; search box in reddit web (plz note that it sometime works fine with this website too). 
In previous version i used a trick to make it work in places such as this.... i used to jump cursor to either a couple of letters left or right but in the latest version it just doesn't lit up it keeps remaining dim as if it recognizes no text.
It sometimes hangs and shows error which pops up momentarily and goes something like this "failed to retrieve text...."

Refer to attached screenshots. In one instance (red highlight) it is working just fine and in another it is not responding (blue highlight).
Thanks a lot for this amazing app.
![IMG_20241013_194421](https://github.com/user-attachments/assets/1fcd4ca8-2a22-4adf-a7d6-21a6b40a31ca)
![IMG_20241013_193849](https://github.com/user-attachments/assets/93f02721-302a-4dde-aad5-48f153b20993)

### Steps to reproduce

Type something in search bar in reddit webpage and observe text selector button on keyboard (refer to attached screenshots)

### FlorisBoard Version

0.4.1

### Install Source

F-Droid

### Device

Narzo 30 Pro 5G

### Android

12

**Comment by maivohun** [comment]
See if the workaround I have mentioned in #2176 works for you.

**Comment by foss77** [comment]
Yes, clicking on triple dot menu (show/hide additional buttons) makes it work.
Thanks
