### ISSUE TITLE
adding alt ctrl tab, plus other things

### ISSUE THREAD

**Issue by bm16ton** [florisboard/florisboard#2632]
### Feature idea

I was heartbroken when the aging thumbkeyboard no longer installs on newer android. Sadly have not found any other keyboard with same functionality, Floris seems closest tho. I use a ton of linux terminal on my devices requiring ctrl alt tab |  etc to be easily accesible on main keyboard layout (ie wo switching to a second keyboard page) Also if buttons on top bar could be customizable to any key or key combo. Also the split keyboards would be amazing..Haha pretty much all the features thumbkeyboard had that no others have. Thank you, awesome project!

**Comment by tsiflimagas** [comment]
This has already been suggested in #229, and many other times from what I remember. I know, it's old, but there are just so many suggestions to be fulfilled. If you have something to add, please do so there.
