### ISSUE TITLE
Pop-ups dimensions stuck on portrait mode

### ISSUE THREAD

**Issue by SebiTalent04** [florisboard/florisboard#2642]
### Short description

When turning the device into landscape mode then returning to portrait, the key pop-ups remain at the landscape dimensions. It's being solved by switching to the characters tab.

### Steps to reproduce

1. Turn auto-rotate on
2. Turn the device into landscape mode
3. Open keyboard
4. Go back into portrait mode
5. The key pop-ups are big, as if the screen is in landscape mode

### FlorisBoard Version

0.4.2 (100)

### Install Source

GitHub

### Device

Pixel 6a

### Android

GrapheneOS 14 (AP2A.240905.003.F1)

**Comment by lm41** [comment]
Thank you for reporting this issue. I can fully reproduce that.

**Comment by patrickgold** [comment]
I can also reproduce this bug. See also related #2629, both issues seem to be affected by the same bug I think

**Comment by patrickgold** [comment]
No, that's an issue with UI zIndex order and that the extracted input layout lays on a separate UI layer by default
