### ISSUE TITLE
Clipboard autofill URL incorrectly split

### ISSUE THREAD

**Issue by tom22k** [florisboard/florisboard#2645]
### Short description

When copying the URL `https://fpx3r.app.goo.gl/PKC4` (NYT games app playstore link) and subsequently opening a text input, the autofill suggestion shows the full URL but also shows 2 more options which are the first and second halves of the URL.

### Steps to reproduce

1. Copy URL `https://fpx3r.app.goo.gl/PKC4`
2. Open a text input box so that autofill suggestion comes up
3. See split URL

### FlorisBoard Version

0.4.2 (Beta)

### Install Source

F-Droid

### Device

Fairphone 5

### Android

14

**Comment by tom22k** [comment]
Screenshots:
![Screenshot_20241019-124331_1](https://github.com/user-attachments/assets/9ef6e7f1-e844-4cc7-98ba-d80fbf1c020e)
![Screenshot_20241019-123658_1](https://github.com/user-attachments/assets/50c56945-deb5-4f20-9e45-8c685017884c)

**Comment by patrickgold** [comment]
Makes sense because the host regex in the NetworkUtils does not have digits in its pattern.

https://github.com/florisboard/florisboard/blob/13fc7679a2c090b551e621cb1240a90a45452b70/app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/NetworkUtils.kt#L28

Adding to clipboard issues
