### ISSUE TITLE
Toggling utility key causes spacebar and utility key misalignment

### ISSUE THREAD

**Issue by itsmartashub** [florisboard/florisboard#2648]
### Short description

There is a misalignment issue with the spacebar and utility key when toggling the `Show utility key` option. When enabling or disabling this option, the spacebar fails to resize correctly, leading to the partial visibility or hiding of the utility key.

To temporarily resolve the issue:

- `Force stop` the keyboard app and relaunch it (but before it choose the desired option)
- Long-pressing the `,` key and selecting the emoji key from its popup, then going back to main keyboard layout triggers a layout update. Or just press `?123`, or 3-dots settings, or any key that changea the layout. This behavior looks similar to the issues you fixed with #2625

### Recording

https://github.com/user-attachments/assets/b690266c-0994-4ae4-8c93-43b4373bef95

### EDIT
Ah, I should rec the video with the bordered theme. In border themes is more noticable that when the utility icon is hidden/removed, its border remains visible, creating an empty, non-functional inactive key area (even `:pressed` feedback style is not triggered)

![fb_toggling_utility_key_bordered](https://github.com/user-attachments/assets/dcda3172-4b18-4a85-bcc0-ee1699b975a6)

### Steps to reproduce

1. Open the keyboard settings and locate the `Show utility key` option
2. Enable the option and observe the keyboard layout. The spacebar should shrink to accommodate the utility key, but it remains at its original size, causing the utility key to be partially hidden behind it.
3. Now, disable the `Show utility key` option. Notice that the utility key is no longer visible, but the spacebar does not expand to fill the available space.

### FlorisBoard Version

0.4.2 (100)

### Install Source

GitHub

### Device

OnePlus 5T (A14) and POCO F3 (A13)

### Android

A14 and A13

**Comment by patrickgold** [comment]
Can reproduce this issue. It is as simple as:
- Go to Floris Settings > Keyboard
- Focus the keyboard in the preview text box
- Toggle the utility key setting

To temporarily fix this issue just switch to symbols (or any other layout) and back

**Comment by patrickgold** [comment]
Related to #2647

**Comment by patrickgold** [comment]
Could you please test the debug artifact of the latest commit in #2647? I updated the layout recompose condition and it should update correctly now.

**Comment by itsmartashub** [comment]
@patrickgold lol, you are faster with fixing then github actions with apk building ⌛

**Comment by itsmartashub** [comment]
With #2647  this seems to be fixed on both mentioned devices 🎉

**Comment by patrickgold** [comment]
Thanks a lot for testing and confirming so quickly ❤️
