### ISSUE TITLE
Long press on language selection key to show input method picker

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#265]
That's the default behavior of the key on gboard too. Whether you'll make it default or put an extra option for it, I guess that's your call (if you agree to add this behavior of course)😄

**Comment by patrickgold** [comment]
Thanks for the suggestion! I will add this as the default, no need for an extra option here. Adding to my todo list!

**Comment by tsiflimagas** [comment]
I see that this issue is addressed by yesterday's pull request and the feature works as expected. It serves me good because I can now disable the long press on spacebar, and be as slow as I want when swiping on it to move the cursor. Thanks!
