### ISSUE TITLE
Accents / special characters pop-up doesn't always show up

### ISSUE THREAD

**Issue by SpidFightFR** [florisboard/florisboard#2651]
### Short description

Sometimes, the pop-ups for accents and such stop showing. It happens randomly.
It appears though that going into the "numbers and special characters tab" and going back into the regular keyboard solves the issue (temporarily).

I managed to get it on video (notice at the beginning, i hold the "A" key, and nothing happens):

https://github.com/user-attachments/assets/6822b06a-b2b9-4c96-bd93-3de2bc690059

### Steps to reproduce

1. [happens randomly]

### FlorisBoard Version

0.4.2

### Install Source

F-Droid

### Device

Fairphone 5

### Android

Android 14 stock

**Comment by patrickgold** [comment]
Duplicate #2629, bound to be fixed by v0.4.3
