### ISSUE TITLE
Annoying keyboard switch option

### ISSUE THREAD

**Issue by Prgramming-backup** [florisboard/florisboard#2652]
### Feature idea

 Long press on spacebar gives prompt to switvh keyboard. No option to disable it while it was available in heliboard . Its annoys me when I cruise control of curser

**Comment by klaurence** [comment]
Welcome! There is a way to disable this behaviour on Florisboard. You can go to `Settings > Gestures & Glide typing > Space bar long press` and selecting `No action.`

(P.S.: There is also a way to disable it in HeliBoard: `Settings > Advanced > Change input method with space key`.)

**Comment by patrickgold** [comment]
As klaurence correctly said this can already be disabled, closing this issue thus.

**Comment by Prgramming-backup** [comment]
Sorry Guys , on wasting your time . I just love your keyboard and this behaviour irritated me so much that I tried switching but failed. Loved your work. I am sorry again for my ignorance and wasting your time. Thanks again , I cant tell you thanks enough, this behaviour was irritating me for past 6 months. Lol. I am very happy now👍🏻. Keep up the good work.

**Comment by Prgramming-backup** [comment]
Your reply was also fast , so thanks for that also.
