### ISSUE TITLE
Change "transportation" emoji picker category icon for 🚂 or 🚲

### ISSUE THREAD

**Issue by boredsquirrel** [florisboard/florisboard#2653]
### Feature idea

I got this interesting idea from a random other issue.

Florisboard uses a mixed icon of a car and a skyscraper for the "transportation and buildings" emoji section.

This is a small change, but changing this to a bicycle/train and a house would be nice?

Cars are destroying our planet, would be cool to have a small something that is different.

I would be happy to make such an icon if you show me where it needs to be :D

**Comment by patrickgold** [comment]
Hey there,

thanks for your feature proposal! The icon we use there is the default Material icon and I think it's best to just keep using it, also for easier migration to FlorisBoard by new users using the default icon used in the Android system eco system.

Hope you can understand!
