### ISSUE TITLE
Popup Buttons are not functional.

### ISSUE THREAD

**Issue by GitAlasGo** [florisboard/florisboard#2657]
### Short description

There's a bug in florisboard, where if you click two times in a row to select a text, it will actually make the text disappear.

The only way around it, is to hold the word until it's selected.

I was only been able to reproduce it in **Acode,** although it's florisboard fault.

The bug can't be reproduced on versions before **0.4.1**

Here is some videos:

In this one, i clicked the copy button but it acted as a **delete button:** https://imgur.com/a/wcs8K7f

The Video with the workaround, is  me holding the text, and clicking copy, as you will see it doesn't act as a **delete button:** https://imgur.com/a/oFUrATh

### Steps to reproduce

1. Install Acode
2. Click twice on the text to select it
3. Click on any buttons like **copy** or **cut**

### FlorisBoard Version

0.4.3 (101)

### Install Source

F-Droid

### Device

tecno

### Android

11, Stock

**Comment by GitAlasGo** [comment]
I don't want it fixed anymore, i found a better keyboard.

**Comment by tsiflimagas** [comment]
It's fixed v0.4.3, for what it's worth.

**Comment by GitAlasGo** [comment]
> It's fixed v0.4.3, for what it's worth.

It's not fixed for me in v0.4.3 and it only happens in Acode application, never mind friend i'm using **unexpected keyboard** for now, i'm sure other people will help him.
