### ISSUE TITLE
Clipboard Select All button no longer  enables by default

### ISSUE THREAD

**Issue by slimfish08** [florisboard/florisboard#2663]
### Short description

When placing the cursor above text, the Clipboard Select All feature is not enabled by default in most apps. Long press above a word has to be done in order to activate the button. This didn't happen before this update.

However the bug does not happen everytime and I don't know when to reproduce it

### Steps to reproduce

1. Go to some text and place the cursor with no long prss
2. The select all button is not activated.
3. To activate it, long press a word.

### FlorisBoard Version

0.4.1

### Install Source

F-Droid

### Device

Sony Xperia 1 V

### Android

14

**Comment by maivohun** [comment]
#2176?

**Comment by slimfish08** [comment]
> #2176?

Yes

**Comment by tsiflimagas** [comment]
So we can close this as a duplicate and keep the discussion there.
