### ISSUE TITLE
Symbols intermitently not displayed/accesible by long pressing keys after update to version 0.4.2 

### ISSUE THREAD

**Issue by rfurb** [florisboard/florisboard#2669]
### Short description

After updating to version 0.4.2, the symbols associated to each key are no longer displayed (so cannot be used). 

This issue is intermitent, as some condition which I could not determine randonly triggers the symbols display on for a short time or until the next reboot, then it stops working again.

Reverting the app to its previous version (0.3.16) solves the problem.

### Steps to reproduce

Just long pressing a key when needing to use any symbol associated to it.

### FlorisBoard Version

0.4.2

### Install Source

F-Droid

### Device

Samsung SM-980F/DS

### Android

12, Stock, Magisk rooted

**Comment by klaurence** [comment]
Welcome! I think this is a duplicate of #2629, which seems to have been fixed in 0.4.3. Please update and, if the bug still occurs, notify us.

**Comment by rfurb** [comment]
Will follow up at #2629 as requested.
