### ISSUE TITLE
Emoji recents / most used category / history

### ISSUE THREAD

**Issue by antonygggg** [florisboard/florisboard#268]
A most used emojis category ( button ) that will keep the 40 - 50 most used emojis for quick access like in many other android keyboards.

The button will have a clock icon and will be the default category when you switch in emojis screen, it also will be the most left one.
It would be nice that each icon on the most used screen can be manually removed ( maybe with long press context menu ).

For example 
[Keyboard Image](https://imgur.com/WMI0lPa)

**Comment by patrickgold** [comment]
Thanks for the suggestion! I think what you are asking is already on my todo list (#180), though your issue is way more detailed and also contains the manual remove action. I will let your issue up and transfer the other one to this.

**Comment by ProblematicDude** [comment]
Seriously need this. As most of the time all of us just send 5-10 common emojis like **haha** / **sad** and not look in the whole spectrum during a chat. Please look forward this request.

**Comment by patrickgold** [comment]
Above pull request re-implements the emoji palette for the preference and keyboard UI rework. With that, I also added the highly requested emoji history/recently used view. The emoji history is the first tab in the emoji view (the clock symbol) and contains all recently used emojis, sorted by new>>old. Recently used emojis can be removed again by long-pressing them.

This change will be included in the next beta release 0.3.14-beta13. Thanks again for your feature proposal!
