### ISSUE TITLE
Pop-Ups are Displaced in Signal

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#269]
![Screenshot_20210128-202156_Signal.jpg](https://user-images.githubusercontent.com/59611881/106188537-6103be00-61a7-11eb-99f9-a6b3febd8700.jpg)

**Environment information**
- FlorisBoard Version: 0.3.5
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Steps to reproduce**
1. Open Signal.
2. Turn phone sideways.
3. Type something. Tr, to find the popups. They're under your thumbs.

(Maybe this only happens when FlorisBoard has to use its own text-field?)

**Comment by itskareem** [comment]
Uploading recording_20210128_212953.mp4…

You mean this?

**Comment by Glitchy-Tozier** [comment]
I can't see anything, unfortunately.

**Comment by itskareem** [comment]
Sorry, I had the same problem also on facebook messenger so I think it's on all apps

**Comment by patrickgold** [comment]
This bug occurs on all apps which require FlorisBoard to display the pseudo-inline text field in landscape as I've just tested this. I will add a proper extract edit text implementation tomorrow which should fix this issue.

**Comment by patrickgold** [comment]
Above PR adds a proper extract edit layout implementation and fixes the popup placement bug you described. Thanks again for reporting!

**Comment by Glitchy-Tozier** [comment]
No worries, I'll find new ways to break your nice little app.  ;)
