### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [florisboard/florisboard#2697]
### Feature idea

Hey,

i noticed in the Settings a few things which I would correct about German Translation and would appreciate if you could change them. Because they are mixed with English at the moment.

Design -> Floris Pure Night (borderless)
Better and more accurate would be for German Translation: Floris reines schwarz (grenzenlos)

Tastatur -> Utility-Taste anzeigen / Utility-Taste Aktion
Better and more accurate would be for German Translation: Werkzeug-Taste anzeigen / Werkzeug-Taste Aktion

Tastatur -> Layout -> Better and more accurate would be for German Translation: Anordnung

Schnellzugriffsleiste -> Layout -> Here "Anordnung" too, instead of "Layout"

Instead of "Sprachen & Layouts -> Sprachen & Anordnung
-> Sprachen & Layouts -> when I click on German and then scroll there it says "Zahlenlayout" and better would be instead "Zahlenanordnung"

Tippen -> Suggestions (except system autofill) and spell checking are not available in this alpha release.  All preferences in the "Corrections" group are properly implemented though. -> German Translation for that would be: Vorschläge (außer automatisches ausfüllen des Systems) und Rechtschreibprüfung sind nicht verfügbar in dieser Alpha Veröffentlichung.

Tippen -> Möglicherweise unangebrachte Wörter / Prevents possibly offensive Words from being suggested while you type -> German Translation for the English Part is: Verhindert mögliche unangebrachte Wörter vom vorgeschlagen werden, während du tippst.

Tippen -> system aurofill suggestions -> German Translation would be: Vorschläge zum automatischen Ausfüllen des Systems

Gesten & Glide Typing -> German Translation which would be more accurate is: Gesten & Gleitschreiben

Gesten & Glide Typing -> Glide Typing is currently not available and will be re-implemented from the ground up with word suggestions & the new keyboard layout engine. DO NOT file an issue for this missing functionality.
German Translation would be: Gleitschreiben ist derzeit nicht verfügbar und wird von Grund auf mit Wortvorschlägen und dem neuen Tastaturanordnung-System neu implementiert. Reichen Sie KEIN Problem für diese fehlende Funktionalität ein.

Emojis -> Emoji-Historie -> Better would be "Emoji-Verlauf
And instead of "Aktiviere Emoji-Historie -> better would be "Aktiviere Emoji-Verlauf"

Emojis -> Update Emoji-Historie -> Better would be "Emoji-Verlauf aktaulisieren"
And instead of "Angenommene vorgeschlagene Emojis werden zur Emoji-Historie hinzugefügt" -> better would be: "Angenommene vorschlagene Emojis werden zum Emoji-Verlauf hinzugefügt"

Über -> Repository (Github) -> better would be "Quelle (Github)"

I hope my Contribution here, to the German Translation for the App helped! And I hope my Suggestions and Corrections will be implemented and changed in the German Language for the App! Thank you.

**Comment by lm41** [comment]
Hello, thank you for your contribution. 

If you take a look into the [contribution guidelines](https://github.com/florisboard/florisboard/blob/main/CONTRIBUTING.md#translation), PRs and Issues with translation updates are not accepted. [Crowdin][crowdin] is used to manage the translations. 

I personally do not think that the translations suggestions below are a good addition to FlorisBoard. Words like [Repository](https://www.duden.de/rechtschreibung/Repository), [Historie](https://www.duden.de/rechtschreibung/Historie), [Layout](https://www.duden.de/rechtschreibung/Layout) and [Utility](https://www.duden.de/rechtschreibung/Utility) are completely normal German words, and I don't see the point in changing the current translation. The other strings are either hard-coded into the app and will be removed later or are part of preinstalled extensions witch cannot be localized. (`Floris Pure Night (Borderless)`).

Even though I will close this issue I would like to encourage you to take a look at [Crowdin][crowdin].

[crowdin]: https://crowdin.florisboard.patrickgold.dev/
