### ISSUE TITLE
Bug in suggestions

### ISSUE THREAD

**Issue by obeho** [florisboard/florisboard#27]
**Environment information**
- FlorisBoard Version: `0.2.1`
- Install Source: `F-Droid`
- Device: `Realme`
- Android version, ROM: <10>

**Steps to reproduce**
Install the app and enable Suggestions, start typing... You get suggestion as the (wordtest) it should've been (word), when clicked on the suggestion, (wordtest) is entered into the field.

![pic](https://user-images.githubusercontent.com/71698631/97111757-e3925400-1673-11eb-919c-17efa6d000c5.jpg)

**Comment by patrickgold** [comment]
Like I stated in #24, this feature is _not yet implemented_. I will probably add suggestions with v0.4.0 or v0.5.0.

**Comment by obeho** [comment]
My bad. [#24](https://github.com/florisboard/florisboard/issues/24) its title was misleading and didn't bother to check it.

**Comment by patrickgold** [comment]
I've just changed the title of #24 so it is clearer what the "bug" in candidate suggestions is.
