### ISSUE TITLE
Change app language without changing the system language

### ISSUE THREAD

**Issue by ungubajue90k** [florisboard/florisboard#277]
Unfortunately, I have not found an option to change the app language without changing the system language.

This option is handy when I use Android devices that don't have my language built in as the system language.

**Comment by patrickgold** [comment]
That is indeed correct, it is currently impossible to change the Settings UI language without also changing the system language. Will add this to my todo list.

**Comment by Luensche** [comment]
@patrickgold in which part of the settings do you would add the language change? Advanced?

**Comment by patrickgold** [comment]
@Luensche Yes, I would add this above the "Settings Theme" preference in Advanced.

**Comment by patrickgold** [comment]
This feature has been implemented in above PR and is available as of 0.3.14-beta01. Thanks again for your suggestion!
