### ISSUE TITLE
Keyboard sizes

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#279]
Hey man, not an issue per se but what are the default sizes for each keyboard setting? I want to use a custom size and it would be helpful to have a starting point. Maybe its something you could put into the wiki.

**Comment by patrickgold** [comment]
The baseline is `Normal` with 100%, then in each direction increases/decreases in 5% steps. See also https://github.com/florisboard/florisboard/blob/c5ae916ece119f82bb226023751c3352d4a183c5/app/src/main/java/dev/patrickgold/florisboard/ime/core/InputView.kt#L99-L105

The wiki will definitely be extended but currently only if absolutely necessary (like with the theme editor). I will definitely add and improve the wiki over time, but some very important things such as suggestions are still _not yet implemented_, so these take priority.

**Comment by Kreuger** [comment]
Cool thanks man.
