### ISSUE TITLE
Spacebar swipe doesn't work like delete-swipe.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#281]
The sensitivity varies depending on how fast you swipe.Which _would_ be fine, but it's implemented exactly the wrong way.

Please use the same mechanism for spacebar-swipe as you do for delete-swipe.

Delete-swipe-pr: https://github.com/florisboard/florisboard/pull/218

**Environment information**
- FlorisBoard Version: 0.3.5
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment]
Above PR improves moving gestures in general and also carries over the precise character deletion code to the space  bar swipes. Will be released with v0.3.6 today or tomorrow.

**Comment by Glitchy-Tozier** [comment]
Amazing, thank you!  :)
