### ISSUE TITLE
Change request: Please make labels on bottom navigation always visible

### ISSUE THREAD

**Issue by cloudrac3r** [florisboard/florisboard#282]
Currently, on the settings page, on the bottom navigation bar, only the currently selected item shows the label, which makes it very very hard for me to get around. I have to press all the icons to find the one I actually want.

I suggest making the labels on all items visible at all times.

I looked at the documentation for the android bottom bar and I think you need to change the option labelVisibilityMode to LABEL_VISIBILITY_LABELED.
https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView#setLabelVisibilityMode(int)

I am a developer on other projects, but I do not know how to set up an environment for android app development, so even though I would love to make this change myself, I don't know how.

Thank you!

**Comment by patrickgold** [comment]
Thanks for your suggestion! Personally, I like to show the label only for the active item, though if it is more clear for some what each section is, I can make the label visible for inactive sections too. Implementation commit for reference: f801c31ebb861c7c1f62021e4b0c27a3f37e3191

Will be released with v0.3.6 tomorrow or on Monday.

**Comment by cloudrac3r** [comment]
Thank you, I really appreciate it!
