### ISSUE TITLE
Add German keyboard layout (Germany) with Ä, Ö, Ü, ß key

### ISSUE THREAD

**Issue by soybeansrabbitowl** [florisboard/florisboard#285]
Here is a picture of exactly what I mean. This is from AnySoftKeyboard.

![IMG_20210130_152647](https://user-images.githubusercontent.com/78264930/106358977-a511d280-630f-11eb-83e2-5a5892e3e558.jpg)

**Comment by patrickgold** [comment]
Thanks for your suggestion! This is indeed a good suggestion for German. Currently you could use the "Swiss German" keyboard layout to have QWERTZ with `ä`` `ö` `ü` as a workaround, the only thing is that the `ß`` is missing.

**Comment by patrickgold** [comment]
Completely forgot to link the relevant PR which added this layout: #556. Closing this issue as it is now resolved.
