### ISSUE TITLE
Spell check not always working

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#286]
Hey Ive noticed that spell check doesnt always work. In fact in some apps, I haven't seen it work at all. One of those is Snapchat.

**Comment by patrickgold** [comment]
What makes me wonder is that spell check even works in some apps, as FlorisBoard does not ship a spell checker and thus it should never work. My guess is that the system default spellchecker service from Android partially works for some input or that some apps provide their own spellchecker.

**Comment by Kreuger** [comment]
Ah I didnt know that was possible. Strange.
