### ISSUE TITLE
long-press for symbol function doesn't work

### ISSUE THREAD

**Issue by formula-spectre** [florisboard/florisboard#29]
**Environment information**
- FlorisBoard Version:e.g. 0.2.1
- Install Source: F-droid
- Device: Samsung Galaxy A50 
- Android version, ROM: Android 10 Stock ROM

**Steps to reproduce**
1. open the keyboard..? 
simply, long press for symbols doesn't work. no symbols appear on the keyboard itself, if not on the second "page". tried to look around in the options but no toggle is present (maybe it is and I'm just blind). I thought this was not implemented, but apparently it's a  bug on mine.

**Comment by patrickgold** [comment]
Ahhh now I get what you meant by long-press for symbols in your feature proposal #23. I thought you meant the popup itself (like if you long-press on 'a' then 'ä', 'á', ... appears or if you press 'h' then a 'h' popup appears). You meant that the symbols from "page" 2 are also integrated into the first page, right? [(like this)](https://imgur.com/a/UIP6OBE). If so, then sorry for closing your feature proposal, I completely misunderstood it.

The underlying number row and symbols have been implemented with the latest release [v0.2.2](https://github.com/florisboard/florisboard/releases/tag/v0.2.2), so it should arrive at your device soon.

Have a nice day,
Patrick
