### ISSUE TITLE
Preset OLED black mode for keyboard

### ISSUE THREAD

**Issue by serebit** [florisboard/florisboard#294]
While the current dark keyboard theme is satisfactory for many, more and more apps and keyboards are including an OLED black mode, and I believe FlorisBoard should include one as well by default. If accepted, I may submit a PR with this preset theme.

**Comment by serebit** [comment]
Also, very nice to see an actively developed keyboard on F-Droid, especially one written in Kotlin. Looking forward to seeing this fleshed out :)

**Comment by patrickgold** [comment]
Thanks for your suggestion, this is definitely something which could be a nice touch to the theme presets. If you want, you can design the theme and make a PR, I'm always happy about new contributions!

**Comment by serebit** [comment]
Working on this--should have a PR ready by the end of today.

**Comment by serebit** [comment]
What happened to the themes I added? They seem to have been removed in v0.3.14.

**Comment by patrickgold** [comment]
> What happened to the themes I added? They seem to have been removed in v0.3.14.

See #1702
