### ISSUE TITLE
Italian layout accents

### ISSUE THREAD

**Issue by zeronovantuno** [florisboard/florisboard#299]
Hello! 
When using the Italian layout, long pressing the vowels to type the stressed wovels with an accent gives to á, é, í, ó, ü. 
However, it should be à, è, ì, ò, ù, as these are the stressed letters that we use the most, by far.
Moreover, long pressing "n" gives ń as the first option, which is pretty useless for Italian. It should be "!" Instead.
Thank you!

**Comment by patrickgold** [comment]
Thanks for your suggestion! I will add this to my todo list to fix this!

**Comment by Stenafo** [comment]
@patrickgold the layout of the letters in the google keyboard is perfect, if it helps I can help you to copy that

**Comment by patrickgold** [comment]
Above commit fixes the popup order in the Italian keyboard layout. Works best if you set the hinted preferences in Settings > Keyboard to either "Disabled" or "Smart prioritization". Will be included in the next release, v0.3.7.
