### ISSUE TITLE
Show row of numbers above the keyboard

### ISSUE THREAD

**Issue by qw123wh** [florisboard/florisboard#3]
look at this keyboard there are interesting things you could add such as the number row and other features

https://github.com/rkkr/simple-keyboard

**Comment by patrickgold** [comment]
I will definitely look into adding this in the near feature, thanks for the request!

**Comment by patrickgold** [comment]
An option to show a number row above the keyboard has been added with #13, if you have any feedback to the newly added features please write it either here or in the PR. Thank you!
