### ISSUE TITLE
Don't remember caps lock state

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#30]
I find it a bit annoying that the keyboard remembers the caps lock state. When I enable caps lock in one text field and then open the keyboard in another it is still enabled.

Would you mind adding an option to disable this behavior and always reset caps lock instead?

**Comment by D3SOX** [comment]
Thank you very much for your efforts.

**Comment by patrickgold** [comment]
Above commit adds a toggle to turn remembering caps lock state on/off. Will be included in the next release (v0.2.3).

Thanks again for your suggestion and have a nice day!
