### ISSUE TITLE
How to contribute a theme?

### ISSUE THREAD

**Issue by kj7rrv** [florisboard/florisboard#301]
I made a new theme. How can I contribute it?

**Comment by patrickgold** [comment]
If you made the theme as a JSON file, just place it in `https://github.com/florisboard/florisboard/tree/master/app/src/main/assets/ime/theme` and make an pull request, then I will be able to merge it.

**Comment by kj7rrv** [comment]
I made it in FlorisBoard's UI.

**Comment by patrickgold** [comment]
Oh then it is currently not possible to export this, I am very sorry. Such functionality will definitely be added in the future though!

**Comment by kj7rrv** [comment]
Okay, no problem.

**Comment by patrickgold** [comment]
I just noticed that with the theme import/export feature this issue has been resolved, will close it now.
