### ISSUE TITLE
Open one-handed mode on the side of activation

### ISSUE THREAD

**Issue by ursi** [florisboard/florisboard#303]
When I switch to one-handed mode, it goes to right-handed mode no matter which key I used to launch it. I think it would be a better UX to launch one-handed mode on the side it was activated on.

**Comment by patrickgold** [comment]
Above commit improves the one-handed toggle and sets the one-handed mode to left when the toggle in the popups of the `.` / `@` / `/` key is used, else it sets the one-handed mode to the right side. Thanks again for your suggestion!
