### ISSUE TITLE
Copy-button doesn't work

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#308]
![20210203_113756.jpg](https://user-images.githubusercontent.com/59611881/106735240-45b80900-6614-11eb-9f25-8ad691eab08a.jpg)

**Environment information**
- FlorisBoard Version: 0.3.6
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Steps to reproduce**
1. Select text
2. The copy button stays disabled.

**Comment by patrickgold** [comment]
Thanks for the report, I am able to reproduce this. Will fix this issue later on.

**Comment by patrickgold** [comment]
Above commit fixes the copy/cut button not working. It was a single exclamation character (`!`) which was missing and caused the boolean statement to always fail :)

**Comment by Glitchy-Tozier** [comment]
I see. It's good this is fixed as it seems like a pretty big bug.
