### ISSUE TITLE
Github issue template reordering

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#309]
Unles there's a particular thought behind why you place it so far up, I suggest moving the **Enviroment Information** section further down. As far as I know, this is the usual place to put it.
I think, it should at least be below description & steps to reproduce.

Also, using `#### abcd` instead of `**abcd**` may be better semantics.

Comparison:
#### 12#4
**12*4**
So I suggest something like this:

```
<!--
- Describe the bug in a short but concise way.
- If you have a screenshot or screen recording of the bug, link them at
  the end of this issue.
- Please search existing bug reports to avoid creating duplicates.
- Thank you for your help in making FlorisBoard better!
-->

#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

#### Environment information
- FlorisBoard Version: <!-- e.g. 0.1.0 -->
- Install Source: <!-- Google PlayStore/F-Droid/GitHub/? -->
- Device: <!-- e.g. OnePlus 7T -->
- Android version, ROM: <!-- e.g. 10, Stock -->

<!-- (remove this line if you paste a log)
`••••`••••`
If applicable, paste the captured debug log here.
`••••`••••`
(remove this line if you paste a log) -->
```

(remove the •••• at the end)

**Comment by Glitchy-Tozier** [comment]
AHHHH I didn't mean to file this as a bug!

**Comment by patrickgold** [comment]
Thanks for the suggestion! Yeah you are right, this looks better. Will change the bug report template to your new version.

**Comment by Glitchy-Tozier** [comment]
_Test with ### (3x#):_
___
### Short description
Describe the bug in a short but concise way. Describe the bug in a short but concise way. Describe the bug in a short but concise way. Describe the bug in a short but concise way. Describe the bug in a short but concise way.
Describe the bug in a short but concise way.

### Steps to reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android version, ROM: 


___
___

_Test with #### (4x#)_
___
#### Short description
Describe the bug in a short but concise way. Describe the bug in a short but concise way. Describe the bug in a short but concise way. Describe the bug in a short but concise way. Describe the bug in a short but concise way.
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android version, ROM: 


___

**Comment by patrickgold** [comment]
Above commit updates the `bug_report.md` template, I've gone with the 4*# version (looks better to me). Thanks again for your suggestion!
