### ISSUE TITLE
Increase the size of numeric keys in number row

### ISSUE THREAD

**Issue by Scripterr** [florisboard/florisboard#31]
The numaric keys in number row are too small and are hard to use so make them big as there is more space so it can be utilized more efficiently.

**Environment information**
- FlorisBoard Version:  0.2.2
- Install Source:  izzy f-droid
- Device:  huawei y9s
- Android version, ROM:  android 10

**Steps to reproduce**
1. Enable number row.
2. Click on a input field to open keyboard.
3. See issue.

**Screenshot** -
![Screenshot](https://user-images.githubusercontent.com/42364681/97733208-89731200-1afd-11eb-8285-d623f8bb15f4.jpg)

**Comment by Scripterr** [comment]
Yes, I have set the keyboard height tall .
> I will look into it and try to increase the size, maybe even remove the Smartbar arrow when the character layout is shown to give the number row extra space.

Yes this would be very helpful.
Thanks.

**Comment by patrickgold** [comment]
Above commit improves the number row in Smartbar (number row takes whole width + supports popups like any other key), which should make it easier to use. Will roll out with the next release (v0.2.4). Thanks again for your suggestion!

**Screenshot for reference:**

![Screenshot_1605478606](https://user-images.githubusercontent.com/19412843/99199080-e7aa2100-279c-11eb-8d3f-2b98703837cd.png)
