### ISSUE TITLE
Download issue 

### ISSUE THREAD

**Issue by atmavandas** [florisboard/florisboard#315]
Cannot download on fdroid. See screenshot. 
Have sony xz2 compact, android 10. Google services deactivated. Other apps have downloaded fine on fdroid. 
![Screenshot_20210204-091115](https://user-images.githubusercontent.com/78531353/106864720-8d00d100-66ca-11eb-9f9c-3f5e31e2be37.png)

**Comment by patrickgold** [comment]
This is because your packet repository cache of F-Droid is out-of-date. Try refreshing it, then there shouldn't be an issue.

**Comment by Filip62** [comment]
I also can't download it with the direct link to the page on F-Droid, also F-Droid crashes when opening your page from it's search function.

**Comment by patrickgold** [comment]
Well I didn't code the F-Droid app, so I can't say why it is crashing when opening the FlorisBoard F-Droid page. When opening the F-Droid link on my side, everything works fine and I can download the APK.

**Comment by Filip62** [comment]
I'm fully aware of that, just thought I might point it out.

Interesting.

**Comment by tsiflimagas** [comment]
This is probably fixed now(?)

**Comment by patrickgold** [comment]
F-Droid occasionally still seems to bug out when downloading apps, but that's not in my hands sadly. In an effort to clean up stalled issues, I will close this issue thus.
