### ISSUE TITLE
Replace the Cursor-Icon

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#316]
#### Short description
In the Quick Actions menu, there's this `I`-button that opens up the selection-keyboard.

That icon shouldn't be cursive. A cursive `I` is commonly used as an indicator for _italics_, and this makes it confusing. (Look at LibreOffice or Github and what they use for italics)

![Screenshot_20210204-150848_GitHub.jpg](https://user-images.githubusercontent.com/59611881/106903951-e7b22100-66fa-11eb-852e-83949c1342a4.jpg)

**Environment information**
- FlorisBoard Version: 0.3.6
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by Glitchy-Tozier** [comment]
It's probably best to use something with a similar styling to this example: https://www.iconfinder.com/icons/2564918/cursor_mouse_pointer_rename_text_icon , as it's best to use something that can easily be differenciated from a capital **i**.

**Comment by patrickgold** [comment]
Thanks for your suggestion! I think I've chosen that icon because I didn't find any better looking over at material.io/resources/icons. I can of course change this if you or I find a better one which is included within the material icon library.

**Comment by patrickgold** [comment]
The only thing I have found is this: https://material.io/resources/icons/?search=move&icon=open_with&style=baseline

Maybe there's something better in it, but I don't want to go through all icons manually.

**Comment by Triplesweet** [comment]
@patrickgold just and only just if you think of an icon I just might be able to make one in corel draw since I know some stuff about it I have to do some searching to know how exactly or its even possible or not but it should be it costs 100 dollar 😑

**Comment by kj7rrv** [comment]
I personally like the one you just linked to, but
https://material.io/resources/icons/?search=move&icon=control_camera&style=baseline
is another possibility.

**Comment by patrickgold** [comment]
@kj7rrv Yeah that would also be another possibility which looks good, thanks for linking!

@Triplesweet Thanks but no, I will resort to an icon of the material icon library, I am certain that one of the many icons will fit.

**Comment by Glitchy-Tozier** [comment]
I wanna give my vote to this:

> The only thing I have found is this: https://material.io/resources/icons/?search=move&icon=open_with&style=baseline

**Comment by patrickgold** [comment]
I've gone with this icon: https://material.io/resources/icons/?search=move&icon=open_with&style=baseline as I like it more after testing it out in the UI. Above commit changes the icon. Will be released now with v0.3.7.

**Comment by yashpalgoyal1304** [comment]
hi, was control_camera (suggested by @ kj7rrv in https://github.com/florisboard/florisboard/issues/316#issuecomment-773507913 ) seems more apt as it gives the dot in the centre feels analogous to cursor to me. Did u try that in testing too?? 

Maybe the open_with icon will seem good too, but hard to say without using both. Some beta/dev version of app where i can check it myself?

**Comment by Glitchy-Tozier** [comment]
@yashpalgoyal1304 Didn't you make an interesting icon just for this purpose? I'd be interested to ser how that looks.

**Comment by yashpalgoyal1304** [comment]
@Glitchy-Tozier haha, yeah, i thought about that too. but seems it wont fit here. That icon doesnt highlight the movement part. But yeah... i guess it still can be used in this context too.  it was this one:

![photo_2021-02-12_23-30-39 (2)](https://user-images.githubusercontent.com/19423063/107873454-b2ff5000-6ed8-11eb-96b0-9316fde7f4f2.jpg)

**Comment by MisterY** [comment]
OK, moving my vote here. Some of the terminology is a bit confusing, I guess.

My proposal is to use the Paste (clipboard) icon for this purpose. It is more intuitive than the current arrows icon, which relates to the floating keyboard or it's position on the screen.
