### ISSUE TITLE
Changing Font colour and size of Symbols in main keyboard

### ISSUE THREAD

**Issue by shockergit** [florisboard/florisboard#321]
The symbols are a bit difficult to read . Can you give an option to increase the size and change its colour. it would have been extremely usefull when using phone outdoors

**Comment by patrickgold** [comment]
In v0.3.7, the contrast as well as the size of the key hint symbols has been increased. There's currently no dedicated setting to change this individually though, but I can place this on my todo list if you want me to.

**Comment by shockergit** [comment]
now its perfect thanks. sorry i havent got the notification for the latest update in playstore. i was using 0.3.5. now its fine.

**Comment by shockergit** [comment]
i have one more suggestion can you remove the bottom number row and add more symbols when you turn on top number row.
eg symbols like _<>=`~  this will help easy typing for a markdown user rather switching back and forth.
![IMG_20210207_090554](https://user-images.githubusercontent.com/63154802/107135961-ffee8f80-68f6-11eb-932a-674dc9a84c52.jpg)

**Comment by patrickgold** [comment]
Closing this issue as it is stale. In the latest stable release 0.3.14 key and key-hint font size/color can be adjusted separately within the stylesheet editor.

> i have one more suggestion can you remove the bottom number row and add more symbols when you turn on top number row.

Yeah something along this is planned, not sure when it will find its way into FlorisBoard though.
