### ISSUE TITLE
Question about the keyboard base

### ISSUE THREAD

**Issue by itskareem** [florisboard/florisboard#322]
So from what I heard that the keyboard is using HTML on some sides not all kotlin or java like other keyboards which is causing some of low speed typing compared to other keyboards
So does the keyboard have planned to change the HTML codes to kotlin?

**Comment by itskareem** [comment]
I checked the code and found out that there's just one HTML which about licenses and not keyboard file so I'm sorry for disturbing. My apologize.

**Comment by patrickgold** [comment]
No problem :)

It is true that my keyboard currently isn't the most performant on older devices, but I am constantly improving on that. The licenses are included via HTML because it is easier to include and expand the licenses screen this way.
