### ISSUE TITLE
Quick-action-toggle has a squared pressing-animation

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#323]
(This was happening for a few minutes straight. Then I switched to the static florisboard-day theme and even after switching back, i can't reproduce it.)

#### Short description
When pressing the quick action toggle, rather than a circular animation, those animations happened:
![20210206_192223.jpg](https://user-images.githubusercontent.com/59611881/107145702-abbdcc80-6943-11eb-89d0-8aa5305f80e1.jpg)

![20210206_192242.jpg](https://user-images.githubusercontent.com/59611881/107145704-aeb8bd00-6943-11eb-94ed-d121116693d9.jpg)

#### Environment information
- FlorisBoard Version: e.g. 0.3.7
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment]
Thanks for reporting! This bug is indeed very strange, as I am currently unable to reproduce it and also this normally shouldn't happen. I will add this to my investigation todo list.

**Comment by Glitchy-Tozier** [comment]
Apparently it also happens on the normal keyboard. Also, this time it ony went away after rotating the screen (=resetting the keyboard)


https://user-images.githubusercontent.com/59611881/107760790-9f15eb80-6d2a-11eb-8e1b-94bd2aa29211.mp4

**Comment by Glitchy-Tozier** [comment]
Okay, I know how to reproduce it!
1. Set any gesture (or long-press action) to input "move cursor left/right".
2. Go to any textbox with an adjacent button (for example play-store or f-droid where there is the magnifying glass-icon next to the textbox)
3. If necessary, click on the textbox to bring up the keyboard
4. Use the "move cursor left/right"-command
5. The focus/selection should now jump out of the textbox (bug?)
6. See Bug:
From now on the quick-action-toggle should have a squared animation.

**Comment by kj7rrv** [comment]
Reproduced on my Moto G Power 2020, running stock Android 10 and
FlorisBoard 0.3.7.

I'm not sure this is significant, but after following those instructions in
F-Droid search and switching to Gmail, it is still square.

**Comment by Glitchy-Tozier** [comment]
Yeah, it should stay a square until you reset the keyboard (for example by rotating the screen)

**Comment by patrickgold** [comment]
Reproducible for me too now in the latest release version v0.3.7, thanks for the steps!

>  The focus/selection should now jump out of the textbox (bug?)

Yup that's a thing with the hardware emulated arrow keys. Though the suggestions overhaul of the EditorInstance class adds a SOFT_KEYBOARD flag to hardware emulated keys, which seems to resolve at least the arrow jumps out of textfield bug (that fix was rather accidential and only discovered while trying to reproduce your steps in the Debug version).
