### ISSUE TITLE
"Vibrate on long press" option

### ISSUE THREAD

**Issue by djpohly** [florisboard/florisboard#324]
Currently the only indication that you have held a key long enough to activate the long-press options is the pop-up. For me, it feels more natural to use this feature when there is tactile feedback: a (second) vibration "bump" to indicate that the long press has happened. (The same thing happens when long-pressing other parts of the UI, such as notifications.)

Other open-source keyboards that have implemented this are Hacker's Keyboard and AnySoftKeyboard, in case that helps!

**Comment by patrickgold** [comment]
Thanks for your suggestion! I will add this to my todo list.
