### ISSUE TITLE
Amoled Black Theme

### ISSUE THREAD

**Issue by imanincel** [florisboard/florisboard#328]
Full Black Mode with white/gray borders on each keypress

**Comment by patrickgold** [comment]
Thanks for your suggestion! If you look at the theme presets for night themes, does "Floris Black Borderless" represent what you ask for? The keyboard background is pitch-black and no key borders (except on key press) are shown. If you want to cstomize it, you can copy the theme by clicking on the "+" and then "Create from selected theme" and modify attributes as you desire.

**Comment by imanincel** [comment]
Eyy That works Thx!
