### ISSUE TITLE
Send keys behaves diffently

### ISSUE THREAD

**Issue by farfromrefug** [florisboard/florisboard#33]
When using apps like slack or discords the send key from florisboard behaves differently as other keyboards.
In this apps the keyboard send key adds a new line and does not send the message(intended behavior)
But florisboard does not add a new line and instead sends the message

**Comment by patrickgold** [comment]
Thanks for pointing out this issue. I know that the send key can behave strangely in some apps, but I'm not 100% sure why and what apps don't function to well with the FlorisBoard enter key. I'll look into this and hopefully find a solution.

**Comment by patrickgold** [comment]
I've just released v0.2.3. When this new version arrives on your device, could you please check if your issue has been resolved, so I can check if my implementation rework has worked? Thanks in advance!

**Comment by farfromrefug** [comment]
@patrickgold i can confirm it works thanks
