### ISSUE TITLE
Adding composing suggestions to FlorisBoard

### ISSUE THREAD

**Issue by patrickgold** [florisboard/florisboard#34]
Hi all,

thanks for checking out this project, I hope you like it! I am @patrickgold, this projects lead developer and maintainer and looking for your help. While I currently work on other features atm (gestures, polishing of existing features, etc.), I am also planning the implementation of composing suggestions, a much wanted feature, which I aim to release with v0.4.0 (current project's version is v0.2.2).

The implementation of composing suggestions is a rather huge task which requires a lot of coding but also a lot of datasets like _word lists_, preferably with _frequency_ measures to better suggest words, maybe also _word pair_ lists, ... I've searched the net quite a while now and haven't really found the datasets I am looking for.

**How can you help?**
I am looking for word lists in different languages (German, English, French, etc.) which fulfill the following requirements:
- The dataset is open-source and free to use
- Its license is compatible with this project's (Apache 2.0) and its license allows the dataset to be included within the FlorisBoard APK
- The format of the dataset can be any (xml, json, txt, csv, whatever), but must be machine readable
- (Optional) The word list has some metric which indicates how often the word appears (frequency) or other useful attributes for each word
- I will of course give full attribution to the source and link to it in both the README.md of this project and in the app's about screen

If you know an open-source word list, it would be incredible if you could post a link to it as a comment below. I will let this issue stay open for a few weeks, so I can hopefully gather enough suggestions to find a usable word list.

Thank you for your help in making FlorisBoard better and stay safe!

Patrick

**EDIT:**
These suggestions have already been gathered:
- AnySoftKeyboard wordlists
- OpenBoard wordlists
- https://github.com/berzerk0/Probable-Wordlists
- https://github.com/hermitdave/FrequencyWords

**Comment by LongJohn-Silver** [comment]
What exactly should I put in the search engine to try and found something? I'm finding some stuff but they were originally created for password managers and security, but maybe they can be repurposed.

**Comment by patrickgold** [comment]
That's exactly what I'm struggling with too - _what_ I should put into the search field to get the desired result. Thanks for the link though!

**Comment by HyknuF** [comment]
I don't know of its legal and meets the criteria, but my first thought was to fork the wordlist of [https://github.com/AnySoftKeyboard](https://github.com/AnySoftKeyboard) ? 

Is there a way to contribute without knowing such wordlist/source?

**Comment by LongJohn-Silver** [comment]
If I'm not wromg they use the Apache license, which is the same used here on FlorisBoard, so that shoudn't be a problem. Still I didn't found wordlists on any their repositories but maybe I checked poorly.

**Comment by HyknuF** [comment]
Before my last post, i found this wordlist:  https://github.com/AnySoftKeyboard/LanguagePack/blob/German/dictionary/de_wordlist.combined
(german i.e.)

**Comment by patrickgold** [comment]
Thanks for your input. Putting legal things aside for a moment, it would be pretty easy to take the word lists of AnySoftKeyboard or OpenBoard and work with that. But often times the dataset is licensed differently than the whole project, as I've seen it with the dictionaries included in the Android LatinIME sources, which specifically allows the dictionaries to be used only within the application.

Maybe I'll try to find out where other libre keyboards have their word lists from and work with that.

**Comment by patrickgold** [comment]
What I've also found is this great repo, which generated great word lists for all sorts of different languages: https://github.com/hermitdave/FrequencyWords

The unlucky thing with it is that all words are in lowercase, so it is pretty unusable for languages for German, where many words like nouns start with uppercase letters...

**Comment by LongJohn-Silver** [comment]
I'm on my phone so I can't see how the list is displayed, but if it has some differentiation between types of words, it wouldn't be so hard to modifiy all nouns in German, and if not, it can be done manually. Still, if something else appears that's better, great.

**Comment by patrickgold** [comment]
The format of the word list the following: `<word><space><frequency>`.  So unluckily no differentiation between types. If nothing better comes up I will probably work with this source, as it contains lists for many different languages and has at least the important frequency measure.

**Comment by LongJohn-Silver** [comment]
Darn, I can help with tedious capitalization if you want. The best option woulf be to have both capitalized and uncapitalized words, right? Because there's always the chance you start a sentence with X or Y word, or it would be ridiculous to consider ever non capitalized noun as wrong (in German, for example) since this is not common in every day messages and can be frustrating.

**Comment by HyknuF** [comment]
Just a quick thought:  Wouldn't it be possible to copy and paste the whole wordlist in "Word" and let the autocorrection do the duty to capalize all nouns? Afterwards, there would be a corrected wordlist, theoretically :-) Can't try it at the moment, but could try if this method works tomorrow.

**Comment by patrickgold** [comment]
@LongJohn-Silver It would be best to have each word only in its correct form, so either capitalized or uncapitalized. As the keyboard reads the CapsMode flag from the target app, I can determine if the current word hast to be capitalized or not and apply this before showing the suggestion to the user.

**Comment by patrickgold** [comment]
@HyknuF Thats actually a smart idea. It can actually be any auto-correction tool, doesn't necessarily have to be Word. Still, there will be issues for words which are correct both capitalized and uncapitalized. (Like "Sie" and "sie" in German; the former is the polite "you", the latter is basically "they")

**Comment by HyknuF** [comment]
darn, you are right. can't appraise the hassle to correct these words manually. let me know if i can contribute 👍 (especially with german wordlist).

**Comment by LongJohn-Silver** [comment]
I was about to say that, too, or "Estado" and "estado" in Spanish. But would that mark it as a mistake if I write Krankenversicherung without the capitalization?

**Comment by patrickgold** [comment]
@HyknuF I will definitely let you know if I need assistance, thanks for your offer! 👍

@LongJohn-Silver I will probably add a toggle in the spell check preferences so people can decide if capitalization at the beginning of a word matters to them. But you are right, exceptions like these are easily manually editable.

**Comment by ivangjxyz** [comment]
Are we allowing AnySoftKeyboard's dictionaries? 
The only thing that stops me from using this app is a catalan dictionary:
[https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/addons/languages/catalan/pack/dictionary/prebuilt/ca_wordlist.xml](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/addons/languages/catalan/pack/dictionary/prebuilt/ca_wordlist.xml)
There's not even need for a particular layout, as catalan is mostly used besides spanish so it is actually best if the catalan layout does not change from the spanish one (or at least it is not totally necessary for now).

**Comment by patrickgold** [comment]
@ivangjxyz The biggest problem with using dictionaries from other apps is that these wordlists are often licensed to be used only within this app and must not be used in other app.

**Comment by Kreuger** [comment]
According to FDroid,

**Comment by WNemencha** [comment]
Here's what Android default keyboard's use:
http://androidxref.com/5.0.0_r2/xref/packages/inputmethods/LatinIME/dictionaries/

**Comment by WNemencha** [comment]
@patrickgold May I help on this one? FlorisBoard is my main keyboard but it's kind of anonying when I don't know how to write a word, lol. Where should I start to contribute?

**Comment by patrickgold** [comment]
@WNemencha Thanks for considering to help developing suggestions! Are you more interested in the programming side (developing a dictionary class which can be used to retrieve words) or the feedback/tester side? If it is the former, see https://github.com/florisboard/florisboard/issues/191#issuecomment-760517146, if it is the latter than you can help me out soon when I start adding alpha alpha releases for this feature.

**Comment by smarquespt** [comment]
I'm not sure if this could be of any help but for Portuguese, we have open source dictionary in various formats. There are Aspell, Jspell, Ispell and Hunspell. If you'r willing to add those please let me know because we have 2 variants and best to have latest variant and I can help you with that. Check here: https://natura.di.uminho.pt/wiki/doku.php?id=dicionarios:main

**Comment by smarquespt** [comment]
HWe also have world lists here: https://natura.di.uminho.pt/download/sources/Dictionaries/wordlists/

**Comment by patrickgold** [comment]
@smarquespt Thanks for the links! In general, I try to use one dictionary format for all languages, but I will keep these in mind for maybe fine-tuning Portuguese suggestions, as your source seem to be very detailed.

**Comment by Iorvethe** [comment]
I'm not sure if this is what you are looking for but here are two links :

- [List of english words](https://github.com/dwyl/english-words)
- [List of french words](https://www.pallier.org/liste-de-mots-francais.html) (it is in French but basically the guy explains how he extracted this list from a dictionary under GPL-2 license)

**Comment by BasilTomato** [comment]
Would it be feasible to use the LibreOffice dictionary files?
- https://github.com/LibreOffice/dictionaries

These are published in hunspell format (.aff & .dic files) in multiple languages.

**Comment by patrickgold** [comment]
@BasilTomato Definitely useful for spellchecking, though it is missing any frequency measure, which is important to weight what to suggest based on the input. Will keep this one in mind!

**Comment by ursi** [comment]
Maybe this goes without saying, but please please PLEASE give us the ability to turn this off without disabling anything else. One of the things I hate most about Gboard is that it has no way of turning suggestions off without also also removing the tool bar.

**Comment by patrickgold** [comment]
@ursi The mechanic to enable/disable suggestions separately from the Smartbar is already there, only that suggestions currently do nothing when enabled.

**Comment by Joshix-1** [comment]
https://www.aaabbb.de/WordList/WordList_en.php there are great word lists in german and english. But there is sadly no frequency measure. Maybe someone could modify the program used to generate those lists and include some frequency measure.

**Comment by modestderp** [comment]
Found the following website when I googled the keywords "chinese word lists":

[http://technology.chtsai.org/wordlist/](http://technology.chtsai.org/wordlist/)

It seems to contain word lists for both _Zhuyin_ (the phonetic input used by Taiwan) in BIG5 encoding, and _Hanyu Pinyin_ (the phoentic input used by Mainland China) in GB encoding.

Currently I'm using [**Luna Pinyin**](https://github.com/rime/rime-luna-pinyin) via [Trime](https://github.com/osfans/trime) as a means to input Traditional Chinese characters using _Hanyu Pinyin_ using the following method as detailed in this reddit post:

[Post here](https://www.reddit.com/r/fossdroid/comments/io8ere/foss_privacy_oriented_chinese_keyboard/g4fm5kq/)

Inside the trime.7z file there is a file "luna_pinyin.dict.yaml" which is essentially the word list containing mapping of Traditional Chinese characters with the phonetic _Hanyu Pinyin_ input.

**Comment by patrickgold** [comment]
Thanks to everyone who commented in this thread! I have looked at everything and some suggestions will definitely find its way into suggestions. I will close this issue now, as the "source-gathering" phase is now completed. I have chosen this repo (https://github.com/LuminosoInsight/wordfreq) to be my main source for the dictionaries, but I will definitely use a variety of different sources to support language accents / dialects and other languages as well. Further discussion can be held in #325.
