### ISSUE TITLE
Correct "Move to End of Line"

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#340]
(All of this also applies to "move to beginning of line)

#### Short description
This option (for long-presses and gestures) does not do what it says it does.

Move to end of line should be exactly that: Move the cursor to the end of the ONE horizontal line.
With the current behaviour, I suggest naming it something like "move to end of text"
![Screenshot_20210212-120800_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/107819150-fb076100-6d78-11eb-9de2-73926a208a3c.jpg)

#### Environment information
- FlorisBoard Version: 0.3.7
- Install Source: Google PlayStore

**Comment by patrickgold** [comment]
That's because the move to start/end of line sends hardware-emulated `ALT left` + `arrow left/right` keys to the target app, and the default behavior of this is t move to the end of the textfield (which in a single line works, but not in a multiline).

Will add this to my todo list.

**Comment by Glitchy-Tozier** [comment]
I'm fine with it going to the end of the whole text. In that case it should be renamed though.

**Comment by patrickgold** [comment]
Above commit fixes the "Move to start/end of line" behavior, it now correctly moves to the start/end of a line. I've also added a "Move to start/end of page" swipe action available to choose from in the gesture preferences, which brings the cursor to start/end of a text field (or in a document to the start/end of a page). Will be released in v0.3.8 this Sunday.

**Comment by Glitchy-Tozier** [comment]
Perfect!
