### ISSUE TITLE
Build signed apk in Actions

### ISSUE THREAD

**Issue by victorbnl** [florisboard/florisboard#342]
You could use https://github.com/marketplace/actions/build-signed-apk to build signed APK in the Actions if you want. That's a suggestion I'm not sure about, and don't know neither if it corresponds with your goals. Just ignore it if it's not pertinent

**Comment by patrickgold** [comment]
Signed APK's can only be build by the owner of the keystore file. Of course, if I give GitHub a copy of my keystore file alongside the key password, then GitHub Actions can also make signed APKs in my name for debug builds, but I do not want to upload the keystore file, so this will never happen, sorry.
