### ISSUE TITLE
Please add Hebrew layout

### ISSUE THREAD

**Issue by yot1337** [florisboard/florisboard#346]
I live is Israel so I communicate with other people in Hebrew. I really like this keyboard and I use it for typing in English but it would be also nice to be able to use it for typing in Hebrew.
Thank you in advance and cheers for making this open source!

**Comment by patrickgold** [comment]
The latest version v0.3.7 should include a Hebrew layout.

**Comment by patrickgold** [comment]
Closing this issue as it is stale and the requested layout is already included in the latest builds.
