### ISSUE TITLE
Normal layout after number typed

### ISSUE THREAD

**Issue by victorbnl** [florisboard/florisboard#347]
Hello! It would be cool that when we go to the number & symbols layout, type something here and press space it goes back to the letters layout. GBoard does that for example, but I think many keyboards do that

**Comment by kj7rrv** [comment]
I do agree that this should be available and probably default, but can you
please make it optional? Personally, the fact that FlorisBoard does not do
this is one reason I like it better than Gboard.

**Comment by victorbnl** [comment]
Like a switch in the options

**Comment by patrickgold** [comment]
Thanks for your suggestion! I can definitely add a toggle for this, will add this to my todo list!

**Comment by patrickgold** [comment]
Above commit adds an option to automatically switch back to the characters layout. It is enabled by default and can be found in (Settings > Keyboard > Space bar switches to characters). Will be included in the next beta release. Thanks again for your suggestion!

**Comment by opusforlife2** [comment]
> It is enabled by default

@patrickgold It wasn't enabled by default for me after updating from 0.3.12 to 0.3.13. Could you check if the settings migration is implemented correctly? I was actually about to open a new issue for it, but landed here while checking for duplicates.

**Comment by opusforlife2** [comment]
If the code is correct, then that was probably the case. Thanks for confirming. 👍
