### ISSUE TITLE
The shift key is working as a Caps Lock. Is this intended behaviour? 

### ISSUE THREAD

**Issue by ivangjxyz** [florisboard/florisboard#35]
Actually, if I double tap the button, it changes colors, signaling a typical _Caps Lock_ activation, so that seems like it's definitely a bug, because if I only tap once... it does not go back after the first letter. 

Normally you expect the shift key to work only for the next letter to capitalize it. 

I don't know if this is the intended behaviour, because I have never seen a keyboard act like this, and the color changing thing makes it look very much like a bug.

**Comment by patrickgold** [comment]
Yeah that is definitely a bug. Caps lock itself is only active if you double-tab and the shift icon gets a color. Is this bug system-wide (appears in any input field, regardless of the app) or does this bug happen only in specific apps?

Also could you please fill out the info below so I better pinpoint where the issue occurs. Thank you!

**Environment information**
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android version, ROM:

**Comment by ivangjxyz** [comment]
Yes. 

### Environment information 
* FlorisBoard version: 0.2.2
* install Source: Play Store Beta access
* Device: Xiaomi Redmi 6
* Android Version, ROM: Android 9, MIUI Global 11.0.4

**Comment by patrickgold** [comment]
I've just released v0.2.3. When this new version arrives on your device, could you please check if your issue has been resolved, so I can check if my implementation rework has worked? Thanks in advance!

**Comment by ivangjxyz** [comment]
It works! Thank you very much.

**Comment by patrickgold** [comment]
Thanks for confirming!
