### ISSUE TITLE
Long-press on enter doesn't work on symbol keyboards

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#350]
#### Steps to reproduce
1. Go to one of the symbol keyboards
2. Hold down enter
3. Nothing happens

#### Suggestion
Make all the long-press options (like the emoji-view) pop up, just as they would on the main keyboard.

#### Environment information
- FlorisBoard Version: 0.3.7
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment]
That's because the default config for popups only applies to character layouts, symbol keyboard must define each and every popup manually in their layout file. But you are right, it would make sense to have the enter popup also in the symbols layout. Will add this to my todo list.

**Comment by patrickgold** [comment]
Above commit fixes the enter popup, it is now working on all character, symbol, symbol2 and numeric(advanced) layouts. Will be released this Sunday with v0.3.8!
