### ISSUE TITLE
Add alphabetic letters to phone dialer layout

### ISSUE THREAD

**Issue by yashpalgoyal1304** [florisboard/florisboard#355]
#### Short description

The florisboard numpad (in blue) in the dialer/new contacts doesnt contain the alphabet preview. That may be problematic in _some_ corner cases where the number is _given_ in the form of some letters for easy remembrance. E.g. in US. : +1-800-9-BELOIT .Shown in black is dialer numpad of simple keyboard.

![photo_2021-02-13_18-45-57](https://user-images.githubusercontent.com/19423063/107875163-4b4f0200-6ee4-11eb-9328-641e3568d8b7.jpg)
![photo_2021-02-13_18-45-56](https://user-images.githubusercontent.com/19423063/107875162-4a1dd500-6ee4-11eb-8603-04c60248627b.jpg)

**Comment by patrickgold** [comment]
Well here in Europe I haven't seen this before, but good to know that phone _numbers_ can contain letters too in some countries xD. Will add it to my todo list!

**Comment by yashpalgoyal1304** [comment]
no no, they dont contain letters per se. I _guess_ it is just shown in that format as an easy way to remember. Example: 

`1800-9BELOIT` --> `1800-923-5648`

![photo_2021-02-13_18-45-56 - Copy](https://user-images.githubusercontent.com/19423063/107880497-199a6300-6f05-11eb-95ce-5d0c1710a57e.jpg)

**Comment by kj7rrv** [comment]
Phone numbers don't actually contain letters, the letters just represent
numbers. For example, our postal service's phone number is  1-800-275-8777,
but they advertise it as 1-800-ASK-USPS. If you type that into a keypad
that shows the letters, you get 1-800-275-8777.

**Comment by kj7rrv** [comment]
Oops, I was already typing.

**Comment by yashpalgoyal1304** [comment]
> oops, i was already typing

hahaha lol, i was trying to create the illustrative image for hours. 🤣🤣🤣 🤝

**Comment by yashpalgoyal1304** [comment]
anyways, nice to have ur first hand input too. And it confirmed my guess. So, yeah, thanks :) :handshake_:

**Comment by yashpalgoyal1304** [comment]
also, just noticed the description was a bit ambiguous. so, fixed it to reflect this fact clearly.

**Comment by patrickgold** [comment]
> Phone numbers don't actually contain letters, the letters just represent
numbers. 

Oh my god I feel so stupid but now I get it haha

Ok so the letters are just there for help in typing in the numbers, but in the end the phone number is a phone number. That makes a lot more sense!

**Comment by yashpalgoyal1304** [comment]
the phone dialer: 

![Screenshot_2021-06-01_16-14-11_1](https://user-images.githubusercontent.com/19423063/120311424-1630b900-c2f5-11eb-94d1-586cb0e10685.png)

**Comment by patrickgold** [comment]
Above PR implements your idea. I decided to place the letters right of the digits, due to vertical spacing issues (see screenshot in #1693). Will be released in 0.3.15-beta01 soon, thanks again for your proposal!
