### ISSUE TITLE
Theme ideas

### ISSUE THREAD

**Issue by yashpalgoyal1304** [florisboard/florisboard#357]
Split from https://github.com/florisboard/florisboard/issues/341 (2B)

#### Short description
- themes UX maybe streamlined a bit
- themes preset options maybe diversified (bg color, accent color, etc)
- mockups pending - will take quite a long time. If some refactor of theming is planned, then please tell me about that. I'll try to come with mockups before that. :)

**Comment by patrickgold** [comment]
Like I commented in #341, if possible, could you provide a mockup of your theme UX when you have the time? Because I am not exactly sure what you suggest here. Thanks in advance!

**Comment by patrickgold** [comment]
If possible, could you test out the latest beta 0.3.14-beta11 and give me feedback if the new theme editor UI has improved for you, so we can finish and close this issue?

**Comment by yashpalgoyal1304** [comment]
it looks awesome :+1:
