### ISSUE TITLE
Promote florisboard

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [florisboard/florisboard#36]
hi @patrickgold , i paint #freesoftware for example of fdroid as #acrylicpictures and promote it on #mastodon and #pixelfedsociel and link there website too.
and now my question: can i paint your florisboard app logo ? 

@IzzySoft knows it already, he is always happy about it ;-)

**Comment by patrickgold** [comment]
Hi @mondlicht-und-sterne , yes of course you can paint the FlorisBoard app logo for your #acrylicpictures, I am really honored by it!

**Comment by mondlicht-und-sterne** [comment]
@patrickgold oh nice. #florisboard is so awesome. I use this keyboard now.

**Comment by mondlicht-und-sterne** [comment]
@patrickgold 

here your florisboard promo on [pixelfedsocial ](https://pixelfed.social/p/mondstern/239051539581374464)
and on [mastodon](https://mastodon.technology/@mondstern/105300043587227677)

**Comment by patrickgold** [comment]
@mondlicht-und-sterne I really like your #acrylicpicture, thanks again for promoting FlorisBoard! 😄
