### ISSUE TITLE
Per Screen Orientation key height and key gaps

### ISSUE THREAD

**Issue by ravener** [florisboard/florisboard#360]
It'd be great to have some more options for keyboard sizes.

Specifically: allow keyboard height to be changed differently depending on whether the phone is in portrait mode or landscape.

Also maybe allow the gaps between buttons to be disabled, I'd like to use it in landscape mode in an app where I need to have as much as screen view as possible without sacrificing keyboard usability, my current keyboard does it well by letting me change the size in landscape and removing the key gaps so the buttons are easier to click.

Here's a screenshot of some of the options my current keyboard has for inspiration:

![image](https://cdn.discordapp.com/attachments/455058727884554240/810489850230603826/Screenshot_20210214_133142.jpg)

If you want more screenshots of how my current keyboard looks like:

Portrait:

![image](https://cdn.discordapp.com/attachments/455058727884554240/810490123342446652/Screenshot_20210214_134641.jpg)

Landscape:

![image](https://cdn.discordapp.com/attachments/455058727884554240/810490188542509066/Screenshot_20210214_134614.jpg)

Thanks.

P.S I love the keyboard so far and it could potentially replace this deprecated keyboard I've been stuck with for so long, just some tiny details that needs to be fixed around.

**Comment by Glitchy-Tozier** [comment]
If I understood correctly something similar already is in the works: https://github.com/florisboard/florisboard/pull/338

**Comment by patrickgold** [comment]
Thanks for the suggestion. The trend in FlorisBoard with the latest preferences regarding layouting is to have a separate portrait/landscape option. The keyboard height pref existed way before that, thus it is currently for both orientations. Will add it to my todo list!

> If I understood correctly something similar already is in the works: #338

That addresses the key spacing for both portrait and landscape, though the keyboard height is still 1 size for both orientations.

**Comment by yashpalgoyal1304** [comment]
hi @ravener which keyboard are the references from? is that open source?

**Comment by ravener** [comment]
> hi @ravener which keyboard are the references from? is that open source?

It's from Multiling Keyboard, Don't think it's open source. When I bought a new phone i couldn't even find it on google play. It's deprecated and the newer version is called Multiling-O which is on play store. But i couldn't get it to satisfy my needs like this one so i'm staying with this atm but looking into florisboard as a potential replacement.

**Comment by yashpalgoyal1304** [comment]
ahhw, okay. the same keyboard is also referred in #196 - seems it put heavy emphasis on key and layout customisability

**Comment by makintos90** [comment]
Thanks for the nice app, devs and all other contributors!
+1 this is very much an issue for me. This is especially a problem on tablets.
What parts would need to be changed to add this feature? I might be able to implement it, given the fact that we already have per-orientation font sizing on the beta

Btw, typed this on florisboard in landscape, and it was really hard.

**Comment by patrickgold** [comment]
With the new preference logic and UI this is very easy to achieve and above commit adds a separate keyboard height for portrait/landscape. Will be available in 0.3.14-beta03 this weekend!
