### ISSUE TITLE
Languages must go in alphabetical order

### ISSUE THREAD

**Issue by 532910** [florisboard/florisboard#361]
![image](https://user-images.githubusercontent.com/14617699/107891237-4e6ee000-6f2e-11eb-8ccd-d7a914055fe5.png)

I have not been able to find Russian from the first two attempts.

v0.3.6 from F-Droid, OP3T, LineageOS 17.1 + microG

**Comment by patrickgold** [comment]
Above commit fixes this, the language list is now sorted alphabetically, with the exception that English is always on top. Will be released this Sunday with v0.3.8.
