### ISSUE TITLE
Swipe the spacebar to change languages

### ISSUE THREAD

**Issue by ravener** [florisboard/florisboard#363]
Allow swiping the spacebar to switch languages and also by holding the spacebar to get a language selector for easier switching when there's a lot of languages active.

**Comment by D3SOX** [comment]
This is already implemented and I think it's even the default.
If not you can easily change it in the settings under gestures. Just change "Space bar swipe left/right" to "Switch to previous/next subtype" and "Space bar long press" to "Show input method picker"

**Comment by patrickgold** [comment]
Thanks for your suggestion! Like Nico said, this is already implemented. A language list in the input method picker is already suggested in #168.
