### ISSUE TITLE
Make keyboard more customized

### ISSUE THREAD

**Issue by kareeeeeeeem** [florisboard/florisboard#367]
It need maybe a .json file like the themes one but for the keyboard buttons (like size, border radius, empty space in buttons, space between buttons....). It would be great cause it give the keyboard more customizability than other keyboard have.

**Comment by patrickgold** [comment]
Thanks for your suggestion! This is definitely a nice idea, but requires a lot of rework both in the preferences UI and in the keyboard measurement logic. Will add it to my todo list, but am currently unsure when exactly this will get implemented!
