### ISSUE TITLE
Text expansion

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#369]
Florisboard is a fully-featured keyboard app. One feature still missing is text expansion. An example of of text expansion can be seen below:

![snippet_demo](https://user-images.githubusercontent.com/50382414/108260518-b4dc4400-7162-11eb-87b9-00ebabac640c.gif)

I suggest to add this feature to florisboard. You can re-use code from the currently existing open source app called snippet (https://github.com/andyb129/Snippet).

**Comment by patrickgold** [comment]
Thanks for your suggestion! I will add this to my todo list.

**Comment by lawson85** [comment]
I would love this too

**Comment by Invisible3ck** [comment]
@patrickgold I would like to add on to this suggestion. Snippet currently only expands text/phrases when typing the entire shortcut. Is it possible to add a feature with Snippet that expands phrases when typing a part of a shortcut? Here is an example. There are 3 shortcuts with the word "Test" This is an example made with Texpand.
![13057](https://user-images.githubusercontent.com/63332039/109690754-8768a080-7b3b-11eb-86a5-a2da1f6106ce.jpg)

**Comment by whispy** [comment]
I would be chuffed to have text expansion added! Contrary to the two proposals above, I think a better place for the post-expansion phrases should be in the smartbar.

**Comment by Donkey-Doug** [comment]
This functionality was added.
