### ISSUE TITLE
Hide language on space bar

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#371]
I only use one language, english. I believe most people only have one language set up. Make it possible to hide the currently used language from the space bar.

**Comment by Glitchy-Tozier** [comment]
Maybe automatocally hide the language if there is only one being used.

**Comment by patrickgold** [comment]
Thanks for your suggestion! I think the best approach is to automatically hide the label for 1 language and show it when using 2+ languages.

**Comment by patrickgold** [comment]
Above commit adds the ability to hide the language name from the space bar. Will be available in the next beta release 0.3.14-beta10. Thanks again for the suggestion!

**Comment by patrickgold** [comment]
It should be in the keyboard screen:

![Screenshot_20220215-210324.jpg](https://user-images.githubusercontent.com/19412843/154140151-95aaff68-9a8a-43f3-926e-9b8b15ca0c69.jpg)
