### ISSUE TITLE
Add release notes to F-Droid

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#378]
This might only happen because I'm using the Play Store version but in F-Droid the release notes are missing.

Please add them.

**Comment by Vendicated** [comment]
works fine for me! 
![Screenshot_20210219-144318](https://user-images.githubusercontent.com/45497981/108511997-eb2fd580-72c0-11eb-8032-cb79cdcaebbd.jpg)

**Comment by patrickgold** [comment]
> This might only happen because I'm using the Play Store version but in F-Droid the release notes are missing.

Ah F-Droid normall copies them 1:1 from fastlane/metadata/android/en-US/<versionnum>.txt`, also works fine on my site. Could quite possibly be a bug with F-Droid or a localization issue (though normally the English (US) locale should be fetched as a fallback).

**Comment by Glitchy-Tozier** [comment]
Closing this then
