### ISSUE TITLE
Theme editor going back to top

### ISSUE THREAD

**Issue by kyungjin** [florisboard/florisboard#379]
Hello, and thanks for this highly customizable keyboard !

In the theme editor, after changing an attributes, the list goes back to top, then you have to scroll all the way down to next parameter.
Would it be possible to keep the position of the list ?

**Comment by patrickgold** [comment]
That's a bug, normally the position should be kept. Will add this to my todo list!

**Comment by kyungjin** [comment]
Here are my environment informations if needed :
    FlorisBoard Version: 0.3.7
    Install Source: Fdroid
    Device: ZTE Blade A520
    Android version 7.0

**Comment by patrickgold** [comment]
Bug is now reproducible thanks to @Glitchy-Tozier: Found out how to reproduce it: Go into the design-editor and click/edit the name of the theme. Only then will the bug show itself.
