### ISSUE TITLE
Suggest pasting when opening the keyboard after copying something

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#38]
I would like to suggest another feature:

The keyboard should automatically ask if you want to paste something (In the smartbar?) if you copied something before you open it. (I think Gboard has a similar feature)
It would be nice if this would also work for images.
(I don't know if it's possible with Android but when I long press on an image in Bromite there is an option to "Copy image")

**Comment by patrickgold** [comment]
Thanks for your suggestion. It shouldn't be a problem to add this feature for text. I will see if I also get it running for images!

**Comment by patrickgold** [comment]
Above two commits add clipboard content suggestions. These suggestions only show up if suggestions are turned on as well. The suggestion feature detects both newly added text and images in the clipboard, but unfortunately inserting the content works only for text. I've tried to get it running for images as well, but it does not really work that well, most of the times it straight up does nothing...

I'll release v0.2.4 today, where your suggested feature (at least for text) will be in it. I will let this issue open until I've figured out how to make it work for images too. Thanks again for your suggestion and have a nice evening!

**Comment by D3SOX** [comment]
Thanks! Works really well but I can't use the number row in combination with this. I thought there was an issue that you can have suggestions/smart bar with the number row but I can't find it right now.

**Comment by patrickgold** [comment]
Well that indeed does not work, because the number row and the suggestion feature are two separate entities (especially since I gave the number row more space to be better usable).

The problem with showing both the number row and the suggestion strip is, that it completely destroys my layout rendering logic, which would require a major change in the core. Maybe I will do it with v0.4.0 (when I plan to add dictionary-based suggestions amd the suggestion strip becomes useful),  but until then I don't really think there's a way to accommodate both the number row and the suggestions at once, I'm sorry.

**Comment by D3SOX** [comment]
Seems like Google is going to add an API to make copying images from one app to another possible.

> Easier rich content insertion in apps
> 
> Google is making it easier for apps to move and receive rich content like images, videos, audio files, and more. Android 12 introduces a unified API that lets apps accept content from any source, be it a clipboard, keyboard, or drag and drop. Through a new interface called OnReceiveContentListener, apps will get a callback when content is inserted from another source. This interface is where all content insertion will be handled, no matter the content type.

Source: https://www.androidauthority.com/android-12-review-1201890/

**Comment by patrickgold** [comment]
Oh yeees, this is definitely a good improvement from Google, really looking forward (as a dev) to this change, as the current method is a real mess. Thanks for sharing!

**Comment by patrickgold** [comment]
Copying and pasting images should be possible in FlorisBoard too and the suggestions view also supports this, but for some reason the image never reaches the floris clipboard. That's a bug which seems to have been introduced in the latest version(s). I think opening a new bug ticket is best, so either I or someone else can have a look at this (I currently work on building the base for the native implementation in C++ , so I won't really work on that for the next week or so).
