### ISSUE TITLE
Please add Dvorak to the list

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#380]
Please add Dvorak layout to the list of supported layouts. This is the first thing I looked at when reading the description. The current list leaves the impression that this layout is NOT supported.
Fortunately, I tried the app anyway and found that Dvorak was just another layout linked to a selected language. This is great and just as it should be.
So, please just add it to the list (since there is one) or at least add the "..." to indicate that there's more.
I've seen this on F-Droid and GitHub. 

Might try this myself once I'm back near a PC.

Otherwise thanks for a well thought out app. In so many years nobody made copy/paste so easy to work with!
This goes onto my essentials list.

**Comment by patrickgold** [comment]
Thanks for letting me know! The list of actually supported layouts is out of sync with the README which itself is out of sync with the F-Droid/Gplay description. So yes, this should definitely be synced up again :)

Will do this probably when preparing the metadata for the final build before the v0.4.0 milestone, where I have to clean up some other incomplete parts as well.
