### ISSUE TITLE
The diacritic version missing on Z

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#381]
#### Short description

Using Serbian language, Dvorak layout. Long-press on letter Z is used for special characters.
However, in Serbian and potentially other languages, Z has a variant Ž, which is now impossible to write.
I think GBoard adds it to the special characters list.

#### Steps to reproduce
1. Add Serbian language with Dvorak layout, make it the active keyboard
2. Activate the keyboard by tapping a text field
3. Long-press the Z key
4. No letter Ž is available 

#### Environment information
- FlorisBoard Version: 0.3.7
- Install Source: F-Droid
- Device: Xiaomi Mi 9T
- Android version, ROM: 10, LineageOs 17.1

**Comment by patrickgold** [comment]
Thanks for letting me know, will add it to the to-be-fixed list!

**Comment by ronanlefichant** [comment]
#394

**Comment by patrickgold** [comment]
Above commit fixes the bug, the Ž is now available in Dvorak. Will be released in the next beta release v0.3.10-beta03.

**Comment by MisterY** [comment]
Thank you!

**Comment by MisterY** [comment]
There's a regression in 0.3.13-beta04 and the letter is gone again from the menu on long-press the Z character.
