### ISSUE TITLE
Start selection mode

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#382]
The current default bar is great in that it puts the cursor movement and the clipboard operations in the foreground. This is extremely useful when working with text and no other keyboard does it this well.

One thing that is missing is the start of the selection mode. There is the Select All button. Similarly, it would be very helpful to be able to start the character selection mode and then continue selecting the text using the cursor movement buttons. 
A toggle button would be ideal.

Alternatively, a "select current word" option might also work since it starts the selection mode and displays the handles for start and end of the selection. 

Hope this is clear. I can add some screenshots, if needed.

**Comment by MisterY** [comment]
I guess this is an equivalent of #352

**Comment by yashpalgoyal1304** [comment]
hi, yes, this is same as that issue. and can be closed and ur input moved (copy pasted) there

**Comment by MisterY** [comment]
The general idea is already described there and the additional information sparked some new ideas. Thanks!
