### ISSUE TITLE
The default smartbar

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#385]
The smartbar is one of the most useful features of the app. Therefore, the default buttons should be carefully selected.

As the clipboard operations and the cursor movement buttons are already found on the selection screen, the default bar might contain something else.
I'd propose that the second smartbar is used as the default.
Later this might be expanded by allowing the editing of the button positions.

My suggestion would be to keep the left/right cursor keys for now. That was the main reason for having AnySoftKeyboard. I work often in a terminal and these are a life saver.

**Comment by tsiflimagas** [comment]
Perhaps this have been solved in 0.3.14-beta07.

**Comment by patrickgold** [comment]
I kept this issue for now because I wasn't sure if beta07 satisfies OP's initial request. It is up to the OP to close this issue or to provide info on how the beta07 Smartbar can be improved.

**Comment by MisterY** [comment]
When would beta 7 be available?

**Comment by MisterY** [comment]
Got it, thanks! Didn't know beta is in Izzy's repo.

Cool, you guys have done it with the arrow key. This is very practical.
This satisfies the original request. Looking forward to using it. Thank you!
