### ISSUE TITLE
Editable Smartbar

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#386]
Creating a separate issue for the discussion on this specific topic.

As suggested elsewhere, the easily available functions will be different based on the context. For this reason I would even like to have a possibility to swipe smarbar left or right and have different sets of buttons.

The other option would be to make the bar customisable, letting the user select the preferred buttons. 

#385

**Comment by patrickgold** [comment]
Smartbar customization is on my todo list now, see #698. Note that I will use the newer issue for this, as it contains a lot of details which are very interesting to me.
