### ISSUE TITLE
Toggle Smartbar

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#387]
I think both Gboard and SwiftKey are now using a button in the suggestion bar to toggle the smart bar. To me this is better than using gestures, #243. Apart from swipe on delete, I actually can't stand keyboard gestures and prefer to have the swipe typing enabled instead.

**Comment by patrickgold** [comment]
The Smartbar gestures don't interfere with glide typing, so you can have both at the same time enabled. Adding a button here is difficult as the available space is limited (not on big phones, but FlorisBoard should also run on small phone screens and here it is a problem).

**Comment by MisterY** [comment]
Unfortunately, I can't make a screenshot without the keyboard hiding. But do have a look at either of these keyboards. I'm sure they are used on small devices as well. The button to toggle the smartbar is quite unobtrusive.

**Comment by patrickgold** [comment]
I don't use SwiftKey, but on Gboard I can only toggle between the quick actions and the suggestion bar, which FlorisBoard also supports since v0.1.0 by pressing arrow on the left side.

**Comment by MisterY** [comment]
Made it

![Screenshot_20210220-193809_Firefox_Beta](https://user-images.githubusercontent.com/462445/108605251-40e4aa80-73b3-11eb-9184-a42748d60d8a.png)

**Comment by MisterY** [comment]
![Screenshot_20210220-193955_Firefox_Beta](https://user-images.githubusercontent.com/462445/108605286-74273980-73b3-11eb-8b39-ec33ab482e54.png)

**Comment by patrickgold** [comment]
Ah you mean an additional Smartbar which shows above the keyboard, I see. I always meant that you can have different toolbars within the same place, so the height of the keyboard does not change.

**Comment by MisterY** [comment]
I see that you mention that aspect in different places but I don't understand the concern. If I'm the user, and I need, for example, copy/paste functionality, it is natural that I'm willing to have that bar shown when I need to do actual work.
Why is the height important?

Having only one bar creates an interesting situation - where will the suggestions be displayed? What will be the active bar? 
I mean, I don't have the answers or suggestions in that regard but, as usual, looking at how the best out there do it, usually inspires some ideas.

**Comment by patrickgold** [comment]
>  Why is the height important?

If the keyboard height changes, on some devices/some apps it is possible that the layout jumps or does some other ugly animation, this is why I try to have a static height. Though I see the usefulness in this feature, so I will add it to my todo list.

**Comment by tsiflimagas** [comment]
I guess this have been solved in 0.3.14-beta07.

**Comment by patrickgold** [comment]
Jup, forgot to attach it to the beta07 PR. Will close this issue manually now.

**Comment by MisterY** [comment]
Thank you, guys!
<3
