### ISSUE TITLE
Adaptve themes documentation?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#389]
Hey @patrickgold , do you have a link to the adaptve themes documentation you got your infos from?

(Asking for https://github.com/Neamar/KISS/issues/1654)

**Comment by patrickgold** [comment]
@Glitchy-Tozier I've joined the discussion in https://github.com/Neamar/KISS/issues/1654, closing this issue.

**Comment by Glitchy-Tozier** [comment]
Btw, danke für die so gewissenhafte Antwort im anderen Issue!  :)
