### ISSUE TITLE
Chinese language input support

### ISSUE THREAD

**Issue by Jakeyfu** [florisboard/florisboard#390]
Could you please add Chinese Language input method, thanks.

**Comment by patrickgold** [comment]
This is already suggested in #149 , please follow along that issue for more information on this topic.

**Comment by CrazyBoyFeng** [comment]
Do you need Simplified Chinese or Traditional Chinese? If it is Traditional Chinese, then there is an issue #149 being followed up on. If it's Simplified Chinese, it's best to make the presentation clear.

**Comment by Jakeyfu** [comment]
Sorry, I need Simplified Chinese input method. Thanks!
