### ISSUE TITLE
Sinhala(සිංහල) Language Input support

### ISSUE THREAD

**Issue by phoenixhp** [florisboard/florisboard#392]
First of all thank you for make this type of opensource keyboard for us. 

Could you please add sinhala(සිංහල) language support for this keyboard?
I would like to recommend you to add Smart Phonetic keyboard layout for Sinhala (සිංහල ) language. (like Helakuru Keyboard in playstore)

https://www.helakuru.lk/keyboard

If you can do it, It will really help for us who likes your keyboard very much.

Again thanks for all of you to who sacrifice their valuble time to develop a beautiful, feature rich, opensource floriskeyboard.

Keep up your good work !!!

**Comment by patrickgold** [comment]
Thanks for your suggestion. I am currently unsure, but will add it to the maybe todo list for now!
