### ISSUE TITLE
Cursor control fails

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#395]
### Short description
I use the swipe left on space and swipe right on space to control the cursor. However, about 50% of the time the cursor does not respond to the gesture. Sometimes it works and sometimes it does not. This is my only active gesture, but I think gestures in general are randomly failling. The failures occur in all apps (so there is not just one specific case). 

### Environment information
- FlorisBoard Version: 0.3.7
- Install Source: GitHub
- Device: Xiaomi Mi 9T Pro
- Android version, ROM: 10, LineageOS

**Comment by patrickgold** [comment]
If you feel that the gesture isn't triggering, does this occur on big swipes or only on small ones? If it is the latter, maybe you could try to lower the swipe distance threshold.

**Comment by Waelwindows** [comment]
Can confirm, this had happened to me before when swiping on the backspace key and cursor control on the space key.

Other gestures like switching subtypes or hiding the keyboard work fine all the type

**Comment by Donkey-Doug** [comment]
The gesture simply does not work sometimes. It has noting to do with swipe distance threshold.

**Comment by Donkey-Doug** [comment]
UPDATE: I am not entirely sure, but I think the bug is only visual. That is, I cannot see the cursor move, but when I type a new letter it inserts on a different location then where I see the cursor.
