### ISSUE TITLE
Add \ on long-press of /

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#396]
<img src="https://user-images.githubusercontent.com/462445/109073057-2cc3e480-76f6-11eb-8b1f-6f333a77b021.png" width="240px" />

In the numeric keyboard, the slash symbol does not have an alternative sign on long-tap.
I would suggest to add the backslash symbol there. 

Edit: The above probably goes for the whole special-characters screen, so singling-out one character may not be worth it. Apart from #397, I find it hard to find an easier way to switch to the image 3 (special chars) keyboard than tapping "?123" and then "=\<". I guess the pros have worked it out already.

**Comment by Glitchy-Tozier** [comment]
Do you think that, additionally, / should be a popup for \? (second page)

**Comment by MisterY** [comment]
> 
> 
> Do you think that, additionally, / should be a popup for ? (second page)

To be honest, I see the numeric page as somewhat redundant. I use FlorisBoard for some editing work where I don't want suggestions and need cursor movements.
And, what I find is that a lot of symbols are accessible by long-press on the main screen. 
Now - going to the 123 numeric keyboard simply duplicates all of those symbols. Then I need to go to the third screen to get the extra symbols, like \.

To answer your question, I find the alternative character ("/" on s, in my case) a great position, because that's it's position on the numeric screen. 
But, as for the rest, the numeric screen is somewhat redundant, or the 3rd screen is too far away. I don't have a definite opinion (or feeling on it). Will continue using it and see if anything elegant pops up.

I will attach the screenshots below for how it looks on Dvorak:

**Comment by MisterY** [comment]
![Screenshot_20210225-112726_Nova_Launcher](https://user-images.githubusercontent.com/462445/109140548-fcfbf780-775c-11eb-91cb-57aea8d94e6f.png)


![Screenshot_20210225-112750_Nova_Launcher](https://user-images.githubusercontent.com/462445/109140564-04230580-775d-11eb-9a2d-2d162a5ca179.png)

**Comment by MisterY** [comment]
![Screenshot_20210225-113306_Nova_Launcher](https://user-images.githubusercontent.com/462445/109140835-5106dc00-775d-11eb-926d-2164873148c3.png)

**Comment by MisterY** [comment]
Come to think of it, I prefer the phone-numeric keyboard to the 2nd one above. Would be great if the numeric key went to that one instead, or if this was configurable.

**Comment by MisterY** [comment]
![Screenshot_20210225-113857_Nova_Launcher](https://user-images.githubusercontent.com/462445/109141496-1782a080-775e-11eb-8758-7b18db8cc272.png)

**Comment by MisterY** [comment]
Moving the above to #397
