### ISSUE TITLE
Import user defined json layouts

### ISSUE THREAD

**Issue by Duvio** [florisboard/florisboard#398]
It would be nice if we could not only add user defined symbols, but also rearrange the entire layout of the keyboard

Maybe this could be done by importing a user-made xml file or even by an in-app layout editor (the former is obviously easier to implement (?))

**Comment by patrickgold** [comment]
Thanks for your suggestion! I think what you are asking is like #196, but that you also ask to import layout json files. Will add the import request to my todo list, as it is already planned sometime in the future.

**Comment by mirsella** [comment]
i think just letting the user add a layout.json file would be a lot easier to implement than a GUI to do it in the app like in #196

**Comment by whispy** [comment]
Agreed, this would be awesome! It would be great to be able to make a layout.json file that we can import for a custom layout.

**Comment by patrickgold** [comment]
The official addons store will allow community keyboard layouts and everything related to it, see https://github.com/florisboard/florisboard/issues/2468 for more info as it is the implementation effort thread now. Closing to avoid duplicate discussions around this.
