### ISSUE TITLE
Partially current (adaptive) partially static

### ISSUE THREAD

**Issue by imDusht** [florisboard/florisboard#399]
Hii, Is it possible to add adaptive theming in the theme creation mix too, so in our custom theme some part of the theme will be like we create them (static-not_changing) but some parts will be dynamic/current/adaptive (based on the foreground app). Like reference adaptive theming in the type section.
Thanks

**Comment by patrickgold** [comment]
That's an interesting proposal, though this does not really work together with the theme engine (the theme editor you see is basically just a nice UI while you are editing a theme json file in the background). I will add it to the maybe list for now, but I am tending to a no here probably. The only thing I plan currently with adaptive themeing is to disable it for some apps, while it is active for others.

**Comment by imDusht** [comment]
No problem, It just popped in my head & I thought that it would be super cool. (◔‿◔)

**Comment by patrickgold** [comment]
This feature is not supported by FlorisBoard anymore, thus I am closing this issue as not-planned.
