### ISSUE TITLE
Long pressing delete button crashes florisboard

### ISSUE THREAD

**Issue by aha999** [florisboard/florisboard#40]
When typing a text and long pressing delete button to delete bigger portions of text, florisboard crashes after 2 sec of holding delete button. Doesn't happen in all apps. Crashes in QKSMS

**Comment by patrickgold** [comment]
Which version are you on? If it is v0.2.2, please consider updating to v0.2.3, as I have completely reworked the core. If it is v0.2.3, I'll have to investigate this bug further.

**Comment by patrickgold** [comment]
I've just released v0.2.4, which adds a crash handler and allows you to copy the captured error log. It would be great if you could try out the new version and if it still crashes when long pressing the deleted key, copy the error log and paste it here. This would help me a lot to find and eliminate the source of the crash. Thanks in advance!

**Comment by RickyM7** [comment]
@patrickgold This bug occurred to me too.

Crash Log:
~~~ 1606213282209.stacktrace ~~~

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6956)	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1119)	at android.view.ViewGroup.invalidateChild(ViewGroup.java:5244)	at android.view.View.invalidateInternal(View.java:13596)	at android.view.View.invalidate(View.java:13560)	at android.view.View.invalidate(View.java:13544)	at dev.patrickgold.florisboard.ime.text.keyboard.KeyboardView.invalidateAllKeys(KeyboardView.kt:341)	at dev.patrickgold.florisboard.ime.text.TextInputManager.updateCapsState(TextInputManager.kt:297)	at dev.patrickgold.florisboard.ime.text.TextInputManager.sendKeyPress(TextInputManager.kt:638)	at dev.patrickgold.florisboard.ime.text.key.KeyView$onFlorisTouchEvent$2.run(KeyView.kt:231)	at java.util.TimerThread.mainLoop(Timer.java:555)	at java.util.TimerThread.run(Timer.java:505)

**Comment by patrickgold** [comment]
@RickyM7 thanks for sharing this crash log, this helped me identifying the error quickly! Interestingly the lines of code which produced this crash were introduced only after v0.2.3, which means that the delete key seems to have another source of crash (what @aha999 experienced in v0.2.2). I'll push a fix commit soon.
