### ISSUE TITLE
Japanese layout support

### ISSUE THREAD

**Issue by dnaka91** [florisboard/florisboard#401]
It would be awesome to have Japanese language support in Florisboard (and actually there seems to be no multi-language & open source keyboard so far that supports this).

I saw other issues regarding auto-completion and that would probably be difficult in a first version of support as it's a whole different language compared to western languages and has its own logic for completions.

But if would be great to have typing support, maybe auto-completion is more something for the far future in this case.

The typical layout is a 9-pad style keyboard where you have 9 big keys and swipe into up to 4 directions on the key to access other characters. And of course pressing the hutton instead triggers the main character for that button.
As this is a very special layout it's surely some extra effort. Maybe just adapting to the current _full-keyboard_ would be a first step (that's often used for Japanese input as well)?

Lastly thanks for all the effort so far on this project. I use the keyboard a lot and love that it's open source without google tracking my every display touch.

**Comment by Waelwindows** [comment]
This was previously discussed in #140. This feature is in the milestones for v0.5.0.

For now, if you're looking for an open source Japanese keyboard for android, you could use [mozc](https://f-droid.org/en/packages/org.mozc.android.inputmethod.japanese/)
