### ISSUE TITLE
Font size increases when switching to symbols.

### ISSUE THREAD

**Issue by vyassuresh** [florisboard/florisboard#402]
#### Short description
I have number row enabled (total 5 rows, including space bar), and font size is set to 125%. When i switch to symbols, the font size increases because there are only four rows now, and they expand to fill the space.

What should instead happen is that the space between them should increase (Gboard screenshots also attached for intended behavior).

I think this is due to the percentage modifier for font size.

#### Steps to reproduce
1. Enable number row
2. Start typing and switch to symbols
3. Notice how the font size increases

#### Environment information
- FlorisBoard Version: 0.3.7
- Install Source: F-Droid
- Device: Honor 8X
- Android version, ROM: 10, Stock

This is what happens :
![Screenshot_20210227_003029_org bromite bromite](https://user-images.githubusercontent.com/37186581/109344240-777b6300-7894-11eb-8175-9d1c9717db84.jpg)
![Screenshot_20210227_003026_org bromite bromite](https://user-images.githubusercontent.com/37186581/109344229-75b19f80-7894-11eb-8790-7c1700c19e06.jpg)

This is what should happen:

![Screenshot_20210227_003016_org bromite bromite](https://user-images.githubusercontent.com/37186581/109344329-92e66e00-7894-11eb-9c94-5c64cab4ff45.jpg)
![Screenshot_20210227_003020_org bromite bromite](https://user-images.githubusercontent.com/37186581/109344336-94b03180-7894-11eb-85b1-6749b261a2ff.jpg)

**Comment by patrickgold** [comment]
Thanks for your bug report! v0.3.8 has reworked some parts of the font size calculation. If the update arrives, could you please check if this issue has been resolved for you? If not, then I will have to investigate into this bug, else it has been fixed with the latest release.

**Comment by vyassuresh** [comment]
> 
> 
> Thanks for your bug report! v0.3.8 has reworked some parts of the font size calculation. If the update arrives, could you please check if this issue has been resolved for you? If not, then I will have to investigate into this bug, else it has been fixed with the latest release.

This has been fixed. Thank you.

**Comment by patrickgold** [comment]
Great to hear, I will close this issue then.
