### ISSUE TITLE
Improvement in florisboard when smartbar is disabled 

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#408]
Currently there is no way to change to text selection mode ,one handed mode when smartbar is disabled

![Screenshot_20210301-160842_Notally_1](https://user-images.githubusercontent.com/75420364/109486324-ba158900-7aa8-11eb-8d20-5339c66592db.png)

![Screenshot_20210301-160758_Notally](https://user-images.githubusercontent.com/75420364/109486368-c994d200-7aa8-11eb-947b-cb9fdcb27652.png)

This can be implemented when holding ?123 button like in(swype keyboard) below image/video (i am not a dev so maybe this can be easy or hard i dont know?)

![Screenshot_20210301-160524_Notally_1_1](https://user-images.githubusercontent.com/75420364/109486522-fe088e00-7aa8-11eb-833f-3bee23b213fe.png)

https://user-images.githubusercontent.com/75420364/109486562-0c56aa00-7aa9-11eb-9612-e8859d55a534.mp4

Thank you very much for developing  Florisboard
I hope i made my suggestion understandable.

**Comment by patrickgold** [comment]
You can switch to one-handed mode by long-pressing enter, where you can switch to emojis and toggle the one-handed mode. Text selection mode is indeed inaccessible without the Smartbar, will probably also add it to the enter popup.

**Comment by patrickgold** [comment]
As the text selection keyboard does not exist anymore and the one-handed mode is accessible through enter and comma long press, this issue is not relevant anymore and will be closed.
