### ISSUE TITLE
Popup symbols in different positions when in landscape mode

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#417]
#### Short description
Basically the symbols are not in the same position when in landscape mode. This occurs at least in the A and O letters.

Note: I tested with the keyboard language in English and this also occurred.

| Portrait |
| :---: |
| ![Portrait](https://user-images.githubusercontent.com/24703825/109639421-eb846800-7b2d-11eb-974f-ae26cf0296ec.jpg) |
| Landscape |
| ![Landscape](https://user-images.githubusercontent.com/24703825/109639440-f17a4900-7b2d-11eb-9f71-342c13edf6c7.jpg) |

#### Environment information
- FlorisBoard Version: v0.3.8
- Install Source: GitHub
- Device: Redmi Note 4
- Android version, ROM: MIUI 11 (Android 7.0)

**Comment by patrickgold** [comment]
Thanks for your report! Technically speaking this isn't a bug, the popup auto-adjustment is intended to do this. In landscape mode, there's enough space to the left to fit another character, so it puts one there while in portrait mode there isn't. Currently unsure how to fix that one, but it also happens in Gboard (at least for the "a" key). AnySoftKeyboard "fixes" this by making the popup width per key bigger, which prevents the layout reordering but looks a bit weird imo.

**Comment by RickyM7** [comment]
Got it! Anyway this does not get in the way too much, it's just a bit strange because as seen in the screenshot the auto-adjustment just moves the character to the side (which doesn't make much sense imo).

**Comment by patrickgold** [comment]
Above PR fixes the different position bug by making the width relations in landscape the same as in portrait, thus the order is also identical. Thanks again for bringing up this issue! Will be released later today with v0.3.10-beta04.
