### ISSUE TITLE
Tapping The Caps Key Two Times to Turn on All-Caps (Different Than Double Tap)

### ISSUE THREAD

**Issue by jetrosut** [florisboard/florisboard#419]
To turn on all capital letters, you need to press the ^ key twice quickly in a limited timeframe. Instead, it could be based on the ^ key's state: If you tapped it once, pressing it again would turn on all-caps; if not, it would capitalize only a single letter. This ensures a cleaner user experience while making it easier to use for people unable to double tap quickly. [Here is a video showcasing state-based capitalization](https://i.imgur.com/TVSoE5i.mp4).

**Comment by MisterY** [comment]
How would one go back to non-capitalized typing, if it was pressed by accident?

**Comment by jetrosut** [comment]
@MisterY Tapping once enables you to enter a single uppercase letter. If you tap twice, it activates the all-caps mode. If you tap it again, like how it is right now, you go back to lowercase.

**Comment by MisterY** [comment]
What I understood:

- tapping Shift once => enter capital case mode
- tapping once mode (after whatever time period) => enter all caps mode
- tapping the third time => enter lowercase mode

This adds one more step if one presses shift accidentally. This is also how SwiftKey implements it and I'm not a huge fan of that because I found that it creates more issues than it solves - at least in my case. But yes, that's one way to do it.

**Comment by jetrosut** [comment]
> 
> This adds one more step if one presses shift accidentally. This is also how SwiftKey implements it and I'm not a huge fan of that because I found that it creates more issues than it solves - at least in my case. I find that it normally takes me at least two full cycles before I'm back to the lowercase mode. That's about six keypresses to fix a simple mistake or change casing back. This normally happens when typing in chat, where fast response is required, so I find it extra annoying.
>

That is precisely why it will be implemented as an alternative. See [410](https://github.com/florisboard/florisboard/issues/410):
>
>I really like this idea to add as an alternative to the current behavior.
>

**Comment by patrickgold** [comment]
> This adds one more step if one presses shift accidentally.

This is true, but as I am adding this only as an alternative, it is the end user's decision if the behavior should be like it is now or the proposed behavior above.

**Comment by jetrosut** [comment]
Nevertheless, hitting backspace takes only a single tap and it exits out of uppercase mode. Plus, you can hit backspace right after hitting shift, meanwhile hitting shift again to exit out of uppercase mode would lead to all-caps since you'd be double tapping it quickly.
