### ISSUE TITLE
Localization Platforms

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#42]
~~It would be great if your project were added to some localization platform, such as [Crowdin](https://crowdin.com/), [WebLate](https://weblate.org/), [POEditor](https://poeditor.com/) or [Transifex](https://www.transifex.com/). These platforms have free plans and make the work of translators much easier.~~

Project added to **[Crowdin](https://crowdin.com/project/florisboard)**.

**Comment by patrickgold** [comment]
Thanks for your suggestion. After looking through your given platforms I have decided that I will apply for an open-source project at crowdin in the next few days, as it seems that there are a great amount of open-source projects. If FlorisBoard doesn't meet their criteria, I will probably use POEditor.

**Comment by RickyM7** [comment]
That's great, thank you.

**Comment by RickyM7** [comment]
That's great, thank you.

**Comment by patrickgold** [comment]
Update: I have set up the Crowdin project, but there are still some minor things missing, which I will add tomorrow. Then I will also add it to CONTRIBUTING.md and will officially open the Crowdin project.

**Comment by RickyM7** [comment]
Thank you. As soon as everything is ready (or shortly after) I will start translating into my native language.

**Comment by patrickgold** [comment]
Thank you for your help in translating FlorisBoard into your native language, I really appreciate it!

I've completed the setup and added the links to the Crowdin project to README and CONTRIBUTING. If your native language is missing from the language list, just ping me and I'll add it!

Have a nice evening
Patrick

**Comment by RickyM7** [comment]
@patrickgold I have already translated into my language (Brazilian Portuguese). The translation may not be perfect but I will improve it over time. Thank you.

**Comment by patrickgold** [comment]
@RickyM7 Thanks again for your great help! Your translations will be shipped with the next regular release and should be automatically applied if the system language is set to pt-BR Portuguese (Brazilian).

**Comment by RickyM7** [comment]
@patrickgold Some strings that should be translatable:

| Finish Setup Title | NYI Note, Localizations Prefs, Theme Prefs |
| :---: | :---: |
| ![Finish](https://user-images.githubusercontent.com/24703825/100563625-92423980-329d-11eb-95e7-7ec9ec429257.jpg) | ![NYINote-LocatePrefs-ThemePrefs](https://user-images.githubusercontent.com/24703825/100563638-9a01de00-329d-11eb-83ff-7a2131b615eb.jpg) |
