### ISSUE TITLE
Parentheses flipped in Hebrew

### ISSUE THREAD

**Issue by alonscheuer** [florisboard/florisboard#422]
When typing in hebrew the parentheses keys produce flipped characters of how they look in the keyboard. i.e. pressing the left parenthesis inserts a right parenthesis. This is the case for all types of parentheses.

**Comment by patrickgold** [comment]
I think this happens because the parentheses is displayed in ltr in the symbol layout but rtl in the actual textbox, this it is flipped. Will place this on my todo list.
