### ISSUE TITLE
Clipboard-suggestion issues

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#424]
#### Short description
1. Not sure whether this was intended or not, but the content of the clipboard doesn't actually show up in the word suggestions. It only shows up in the beginning.
2. After resetting the keyboard (by turning the device for example), the clipboard-suggestion-badge disappears immediately.
3. The clipboard suggestion is abbreviated by two dots. Why not three?
![dotdot](https://user-images.githubusercontent.com/59611881/109775527-e5f85200-7c01-11eb-9027-f4f535f5c973.jpeg)

#### Environment informa…
- FlorisBoard Version: 0.3.8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10, whatever Samsung uses (one-ui?)

**Comment by patrickgold** [comment]
> Not sure whether this was intended or not, but the content of the clipboard doesn't actually show up in the word suggestions. It only shows up in the beginning.

That's intended that way, because if you start typing you are indicating that you lost interest in the paste suggestion. Open though to rework this behavior, just currently not my main concern.

> After resetting the keyboard (by turning the device for example), the clipboard-suggestion-badge disappears immediately.

This happens because of the internal reset which happens when rotating the device. Will see how I can fix that one.

> The clipboard suggestion is abbreviated by two dots. Why not three?

Excellent question, intended were definitely three dots.

**Comment by Glitchy-Tozier** [comment]
> That's intended that way, because if you start typing you are indicating that you lost interest in the paste suggestion. Open though to rework this behavior, just currently not my main concern.

I feel like it would be a fun feature to have it always show up as the first word-suggestion for the first letter/number of the copied text.
Why? To make something like this possible:
1. Copy [0339… phone number]
2. Write "Her number is 0"
3. Insert the phone number.

Regarding the other two responses:
Great! :)

**Comment by MisterY** [comment]
SwiftKey has some interesting behaviour in that regard. After copying text, it will initially show only the paste suggestion. If you type something, it will show the word suggestions but keep the paste suggestion in the third box.
Only after a few words will it clear the paste suggestion completely and continue using all three boxes for the word suggestions.
Also, the clipboard feature remembers everything copied in the last hour (if it is the active keyboard), which is very practical.

**Comment by Glitchy-Tozier** [comment]
Personally, I prefer that
> 1. Copy [0339… phone number]
2. Write "Her number is 0"
3. Insert the phone number

workflow, as it saves and may be less annoying to people that don't want to insert anything. Basically it doesn't force you to empty your clipboard to get rid of the constant clipboard suggestion.

However, in any case, I agree that the clipboard-content *should* be kept available until the clipboard is cleared (or for about one hour, whatever happens first.)

**Comment by MisterY** [comment]
![Screenshot_20210304-102125_Firefox_Beta](https://user-images.githubusercontent.com/462445/109941567-94b89300-7cd3-11eb-93fd-0bdac13de09e.png)


![Screenshot_20210304-102148_Firefox_Beta](https://user-images.githubusercontent.com/462445/109941585-9a15dd80-7cd3-11eb-9852-270df34d88f2.png)


![Screenshot_20210304-102223_Firefox_Beta](https://user-images.githubusercontent.com/462445/109941624-a437dc00-7cd3-11eb-8099-e7af3a984421.png)

**Comment by Glitchy-Tozier** [comment]
What's that layout? Reminds me a little bit of neo2.

**Comment by MisterY** [comment]
> 
> 
> What's that layout? Reminds me a little bit of neo2.

The keyboard layout, you mean? Dvorak. Been using it for over 20 years. I think I can't even type on a Qwerty keyboard any more.

**Comment by Glitchy-Tozier** [comment]
Ah, I see!
I love seeing people use alternative layouts!

**Comment by MisterY** [comment]
Don't call it alternative. :)))
When one reads the history of the QWERTY keyboard and finds that this layout was used to prevent the early typewriters from jamming, while in the 21st century we can type almost as fast as we want and Dvorak makes it easy, I'd call Qwerty (a slow) "alternative". ;)

**Comment by Glitchy-Tozier** [comment]
I know, I use a non-standart keyboard as well (on the PC), KOY, a Layout optimized for German&English.  :)
Still learning it though, started last year.

> this layout was used on purpose, to slow down typing and prevent the early typewriters from jamming

Btw, I know about the second part, but i often hear that the first part may be incorrect. In any case, "new" keyboard layouts are way better and pretty fun, once you surpass the really painful part of learning a layout.

**Comment by mizzunet** [comment]
Is this intended 'bug' accepted to be fixed for showing it like SwiftKey does? That would be much appereciated

**Comment by patrickgold** [comment]
@mizzunet The clipboard suggestion feature definitely requires a rework, because in its current  state the usefulness is not really given. I can't guarantee that the implementation will work 1:1 like in SwiftKey but it will definitely integrate better with the displayed suggestions.

**Comment by mizzunet** [comment]
> @mizzunet The clipboard suggestion feature definitely requires a rework, because in its current state the usefulness is not really given. I can't guarantee that the implementation will work 1:1 like in SwiftKey but it will definitely integrate better with the displayed suggestions.

Looking forward it, thanks :)
