### ISSUE TITLE
Word suggestions: hyphenate words.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#425]
```
#### De-
#### scrip-
#### tion
```
This might either be very easy or very difficult to implement. Long words should be hyphenated correctly.
Look at the supercomputer. It doesn't look right:
![superpc](https://user-images.githubusercontent.com/59611881/109775993-6e76f280-7c02-11eb-926e-28671ed6d59b.jpeg)

#### Environment information
- FlorisBoard Version: 0.3.8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10, whatever Samsung uses (one-ui?)

**Comment by Glitchy-Tozier** [comment]
Also, those spaces (red) bother me a little, but i'm not sure what fix to suggest. Maybe enlarge the margins of the two separation-lines in the middle.
![superpc2](https://user-images.githubusercontent.com/59611881/109777080-9a46a800-7c03-11eb-9b4b-8ca6ce145457.jpeg)

**Comment by patrickgold** [comment]
As cool as this idea sounds, hyphenation of words depends on the grammar of the language selected and that's a bit difficult. Will add it to the todo list but handle it later on.

> Also, the difference in spacing (red) bother me a little, but I'm not sure what fix to suggest. Maybe enlarge the margins of the two separation-lines in the middle.

I could add a left/right margin on the separators of `1dp`, this doesn't really backfire on small devices but is at least a bit of space.

**Comment by Glitchy-Tozier** [comment]
Sure, go for it!  :)

(That's a response to both your answers)
