### ISSUE TITLE
"Next Character"-gesture still moves to next textbox

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#428]
#### Steps to reproduce
Not sure how to reproduce but this happened twice now. Might be connected to those steps:
1. Enter textbox by clicking on it
2. Press back to close keyboard.
3. Click on end of text to move cursor there and to open the keyboard
4. Do the gesture

https://user-images.githubusercontent.com/59611881/109795110-d8999280-7c16-11eb-9aff-c14433b8d2fa.mp4

#### Environment information
- FlorisBoard Version: 0.3.8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by Glitchy-Tozier** [comment]
(Me moving my finger down me trying out whether the "Move to end of line"-gesture also has this effect. It didn't.

**Comment by Glitchy-Tozier** [comment]
For some reason it only worked at at the end of the description, while it didn't do anything at the end of the title.

**Comment by patrickgold** [comment]
Hmm strange, I am completely unable to reproduce this bug even after following your steps and trying it out in the GitHub app. Will have to investigate into this one, but could theoretically also be a bug in the GitHub app, as I am just sending the shortcut and the actual cursor movement is done by the target app.

**Comment by Glitchy-Tozier** [comment]
@patrickgold Seems to have been fixed, should we close the issue?

**Comment by patrickgold** [comment]
If you can confirm for  you that it is fixed then we should close this issue.

**Comment by Glitchy-Tozier** [comment]
I can't reproduce it atm, so let's close the issue.
