### ISSUE TITLE
Switching apps doesn't reset word suggestions

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#429]
#### Steps to reproduce:
1. Write something without clicking on a word-suggestion
![Screenshot_20210303-112730_Phone.jpg](https://user-images.githubusercontent.com/59611881/109792440-cff38d00-7c13-11eb-88af-80c543720b3b.jpg)
2. Switch app & open keyboard
3. See bug.
![Screenshot_20210303-112738_Firefox Klar.jpg](https://user-images.githubusercontent.com/59611881/109792523-e39ef380-7c13-11eb-9bcf-ef63484c9d2b.jpg)
![Screenshot_20210303-112811_GitHub.jpg](https://user-images.githubusercontent.com/59611881/109792535-e568b700-7c13-11eb-95b4-3c48c8ce4ec1.jpg)

#### Environment information
- FlorisBoard Version: 0.3.8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment]
Yup, that's currently the case. Placed on the todo list for fixing suggestions.
