### ISSUE TITLE
Moving the cursor via Space-Swipe is buggy.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#430]
This happens especially often when "hitting" the end of the textbox with your cursor.

https://user-images.githubusercontent.com/59611881/109795147-e3542780-7c16-11eb-90ae-93ac5179032c.mp4

#### Environment information
- FlorisBoard Version: 0.3.8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by Glitchy-Tozier** [comment]
Btw., I didn't accomplish that crazy cursor-movement in the beginning by clicking all over the place at lightning speed. It was just me doing the first spacebar-swipe.  :)

**Comment by patrickgold** [comment]
I am aware of this issue, I've filed a bug report for this in #411. Has something to do with the composing suggestions marker, unsure where exactly the cursor though escalates that much. Closing this issue as it is a duplicate.

**Comment by Glitchy-Tozier** [comment]
Whoops, didn't see that issue.
