### ISSUE TITLE
Smartbar tools appearance related bug

### ISSUE THREAD

**Issue by GithbUser** [florisboard/florisboard#431]
Smartbar default tools are not visible in smartbar when display suggestions is enabled 
Look this picture below ,no smartbar tools are shown when tapping on a input field smartbar tools are not appeared
![Screenshot_20210303-161905_Notally](https://user-images.githubusercontent.com/75420364/109795978-9afc3000-7c3d-11eb-9fe5-87f4fbf3a195.png)
These are only visible when selecting them via delete gesture,example below

https://user-images.githubusercontent.com/75420364/109796364-1362f100-7c3e-11eb-9baf-09899a5a9d39.mp4

Steps to reproduce
1. Go to Florisboard setting
2. Click on typing 
3. Enable display suggestions 
4. Go to any input field
5. Smartbar is not visible
6. Type anything
7. Then try to erase it using delete gesture
8. Notice while choosing words by delete gesture,smartbar default tools are visible

 Environment information
- FlorisBoard Version:0.3.8
- Install Source: GitHub
- Device: Poco m2 pro
- Android version, ROM: 11 ,MSM Xtended Rom

**Comment by patrickgold** [comment]
The clipboard cursor tools shouldn't show when using the delete gesture, that's a bug. Will investigate into this.

**Comment by Glitchy-Tozier** [comment]
Why, @patrickgold ?

Text is selected and can be copied, after all.
(Also, displaying suggestions in this moment doesn't accomplish anything)

**Comment by patrickgold** [comment]
@Glitchy-Tozier  Because the delete swipe is intended to **delete** text, not to select and copy it. You are right, displaying selections here is also not kinda useful, but I like to have consistency in the UI when deleting text. Proper text selection is being prepared by me (currently I am reworking the core selection modifier implementation, which will enable me to add a better front-end method to select text).

**Comment by Glitchy-Tozier** [comment]
> which will enable me to add a better front-end method to select text

What do you mean by that?

Wanting to keep it static makes sense. I somehow feel like it could add something to the app being able to delete-swipe to quickly copy/cut text though.

Btw, the nice delete-swipe-"hack" got killed a few updates ago. :(

**Comment by patrickgold** [comment]
> What do you mean by that?

Sneaky-peaky preview: press and hold the shift key, then either use the clipboard arrow left/right or the space bar cursor left/right gesture (if set to cursor movement) and it behaves like you press `shift` and then the arrow keys on a PC. Currently I am preparing the backend, if this works fine I can write the UI logic for it.

> Wanting to keep it static makes sense. I somehow feel like it could add something to the app being able to delete-swipe to quickly copy/cut text though.

I will automatically display the clipboard tools if there's a selection which is not during the delete swipe, because then displaying suggestions makes no sense but clipboard tools are useful.

> Btw, the nice delete-swipe-"hack" got killed a few updates ago. :(

That was definitely not intentional, but I hope the shift + cursor movement feature can replace it :)

**Comment by Glitchy-Tozier** [comment]
> Sneaky-peaky preview: press and hold the shift key, then either use the clipboard arrow left/right or the space bar cursor left/right gesture (if set to cursor movement) and it behaves like you press shift and then the arrow keys on a PC. Currently I am preparing the backend, if this works fine I can write the UI logic for it.

I was going to suggest that eventually, along with shift+delete deleting words  xD

> That was definitely not intentional, but I hope the shift + cursor movement feature can replace it :)

Sounds like it may be able to replace it (though it will be slightly slower of course)
Two thoughts regarding this new feature:
1. Also make it compatible with the `move to start/end of line/paragraph`-gestures
2. I think after copying the cursor should be placed where it originated. I'm not 100% determined in that opinion though so if you have a good reason to want a different behavior, tell me.  :)

**Comment by patrickgold** [comment]
> Also make it compatible with the move to start/end of line/paragraph-gestures

Thanks for reminding me of that, would probably have overseen this one.

> I think after copying the cursor should be placed where it originated. I'm not 100% determined in that opinion though so if you have a good reason to want a different behavior, tell me. :)

That's a good question. Gboard handles it to set the cursor to where it traveled, I will probably follow that behavior.

**Comment by Glitchy-Tozier** [comment]
Btw patrick, your selection-board uses a different, third mechanism: 

If text is selected from point A to point B, the cursor will always end up on the point that's furthest down the text (point B)
Meaning that no matter whether you selected A→B or A←B, the cursor will always end up on B.

(Oh, and the `copy`-function in the smartbar works the same way.)
(In general, thiy seems to be the android way. Try it out by using android's "normal" copy-button)


Whatever you choose, I suggest using the same mechanism for all copy-features.  :)

**Comment by patrickgold** [comment]
> If text is selected from point A to point B, the cursor will always end up on the point that's furthest down the text (point B)
Meaning that no matter whether you selected A→B or A←B, the cursor will always end up on B.

I meant if you cancel the selection by pressing on "Select text" again, then the cursor moves to the destination. When using copy, the cursor indeed always moves to the end.

> Whatever you choose, I suggest using the same mechanism for all copy-features. :)

Yup definitely, consistency is very important here.
