### ISSUE TITLE
(Persistent) Clipboard History

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#435]
Related to #424, I'd like to suggest the Clipboard History feature similar to what SwiftKey does.

- The keyboard will remember everything copied to clipboard in the last n units of time (open for suggestions),
- items copied previously can be pasted from the Clipboard (History?) screen
- items can be pinned in order not to get automatically forgotten after the time expiration period
- items can be removed from history manually by swiping them away from the list

This would help sort out the paste suggestion issues some might have as it will keep multiple items in cache and it will be easy to paste desired item.

Screenshots [here](https://github.com/florisboard/florisboard/issues/424#issuecomment-790465673).

**Comment by Glitchy-Tozier** [comment]
As the discussion has moved here, I'll comment on this issue:

I agree with pretty much everything you suggested, the only thing I disagree with is swiftkey's implementation in the screenshots.

Personally I don't mind either way, but i can imagine non-tech-savy users (like my parents) getting annoyed because they just want to use word suggestions and this weid thing keeps blocking one third of all suggestions.

**Comment by MisterY** [comment]
> I agree with pretty much everything you suggested, the only thing I disagree with is swiftkey's implementation in the screenshots.

There's nothing to disagree with. That's how it works. :P

> Personally I don't mind either way, but i can imagine non-tech-savy users (like my parents) getting annoyed because they just want to use word suggestions and this weid thing keeps blocking one third of all suggestions.

Let me repeat here, as well. What you say is exactly how I'd prefer it to be. I like the initial suggestion because normally I'd want to paste it somewhere. If not, the case where one types something before pasting, there's the whole Clipboard history screen where it can be pasted from.

Don't get me wrong - in the other thread I was not proposing anything. Merely saying that this is how it works in another popular keyboard, to see if something useful can be observed in that pattern.

**Comment by Glitchy-Tozier** [comment]
> There's nothing to disagree with. That's how it works. :P

Sorry, I meant I prefer different implementations than theirs  🙈

> Don't get me wrong - in the other thread I was not proposing anything. Merely saying that this is how it works in another popular keyboard, to see if something useful can be observed in that pattern.

I see, thank you for giving us material to compare ideas!  :)
