### ISSUE TITLE
Smartbar disappears in password input fields

### ISSUE THREAD

**Issue by Atrate** [florisboard/florisboard#436]
Related: #153, #358

It seems that the Smartbar does not show in fields for inputting passwords. Is that intended? If so, could a switch be made available that allowed the smartbar to show there as well? Having gotten used to the smartbar-style paste, it is weird to have to break that workflow in certain input fields.

**Comment by patrickgold** [comment]
Yes, this is fully intended. As the Smartbar disappears fully for you, it seems that you've enabled the number row in the character layout. When this number row is disabled, the Smartbar shows a number row in password fields.

> If so, could a switch be made available that allowed the smartbar to show there as well?

Yes, can definitely be done, adding to my todo list.

**Comment by KaKi87** [comment]
Hello, as I'm using KeeWeb as password manager, how I paste my passwords into password inputs when not being able to use long press ? Thanks

**Comment by KaKi87** [comment]
Hello, any news on this ? Thanks

**Comment by patrickgold** [comment]
@KaKi87 No, the Smartbar has not changed in this regard. As per feature roadmap a full Smartbar customization and fix for this behavior will be done in 0.5.0.

**Comment by KaKi87** [comment]
What workarounds are possible until then ?

**Comment by Atrate** [comment]
> What workarounds are possible until then ?

For pasting, using Android's built-in paste on long-press.

**Comment by KaKi87** [comment]
> using Android's built-in paste on long-press

What if long-press is not available on some app ? That's precisely my issue. Thanks

**Comment by patrickgold** [comment]
In the upcoming release 0.3.14-beta07 the Smartbar will not disappear anymore for password fields, thus allowing for the same access to features as in non-password fields.

**Comment by KaKi87** [comment]
Any idea when this will be released on F-Droid ? Thanks

**Comment by patrickgold** [comment]
On the main F-Droid repo it will be released once 0.3.14 hits stale, this will not happen in this year though anymore, as the theme UI is still pending and also a lot of polishing work. If you use Izzy's F-Droid repo however you get the beta releases, which currently is the beta07 one and a new beta release will be made before New Year's eve (in the Christmas holidays).

**Comment by KaKi87** [comment]
I see, unfortunately it's a separate app and I'm too lazy to redo all my settings again. Maybe I'll switch when #467 will be implemented.
