### ISSUE TITLE
Cursor omitting a character on swipe gestures

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#448]
On gestures which move the cursor (swiping on spacebar and delete key), cursor always starts moving by two characters, and then move one by one, no matter the swipe distance threshold. It's a small detail but it could be polished out I guess.

**Comment by patrickgold** [comment]
Thanks for pointing out this little detail! I've fixed this issue in the input logic rework, will be included in the next release!

**Comment by patrickgold** [comment]
Yup you are right, above comment fixes the delete behavior as well!

**Comment by tsiflimagas** [comment]
Thank you very much, it works perfectly!
