### ISSUE TITLE
Wrong uppercase popups in greek

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#452]
I don't know about the mechanism of assigning uppercase letters to keys, since for localization we only have to write the lowercase letters, so I can only realize the result, which seems to be automatic assignment of uppercase letters (and their popups). For english at least it seems to work fine (I don't know about other languages), for greek though, uppercase vowels popups are wrong, they're supposed to be accented (as it happens with lowercase ). I don't know whether there is a way for me to configure it (it seems to me there's not). I need a clarification for this 😅

**Comment by patrickgold** [comment]
Hmm strange I use the localization util class Java provides. this is the line which makes a character uppercase:

```labelText.toUpperCase(subtype.locale)```

where subtype is your current default subtype selected (the language on the space bar). I've created [this](https://pl.kotl.in/UnlkbGjGg) simple Kotlin playground snippet. Could you replace the `str` with a Greek one and see if the uppercase output is correct or not? This way I can differentiate if the Locale class or some other part is failing.

**Comment by tsiflimagas** [comment]
Yes, this works fine.

**Comment by patrickgold** [comment]
Thanks for pointing this out! I've just run tests and the active subtype is always correctly set, though the uppercase variants are incorrect. Will investigate into this tomorrow.

**Comment by patrickgold** [comment]
Above commit is a workaround for the uppercase bug, it should now be capitalized correctly again. Thanks for reporting! Will be released in v0.3.9 now.
