### ISSUE TITLE
Hide Smartbar

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#46]
It would be great if an option to hide the Smartbar was added. This would also make the keyboard get a little bigger.

**Comment by patrickgold** [comment]
Thanks for your suggestion. I will add it to my todo list.

**Comment by RickyM7** [comment]
Closed due to #78.

**Comment by patrickgold** [comment]
Oh I completely oversaw that such an issue already exists, sorry for that. Nevertheless it will find its way into FlorisBoard soon :)

**Comment by RickyM7** [comment]
@patrickgold Don't worry. Thank you.

**Comment by patrickgold** [comment]
I've just merged the Smartbar rework branch into master, which also contains the ability to hide the Smartbar in the preferences. Will release with the next release v0.3.1. Thanks again for your suggestion!
