### ISSUE TITLE
Swipe to Delete Improvements

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#47]
I think these changes would greatly improve the way "Swipe to Delete" works in the app. The changes would be:

- [ ] 1. Mark the characters while swiping.

- [ ] 2. Don't interact with the keyboard while swiping.

- [ ] 3. Do not lock "Swipe to Delete" after deleting only one word.

Example:

| App in example: [Simple Keyboard](https://github.com/rkkr/simple-keyboard) |
| --- |
| ![Swipe to Delete Example](https://user-images.githubusercontent.com/24703825/100527303-069eaf00-31b0-11eb-91e8-83eaf69ae045.gif) |

**Comment by D3SOX** [comment]
Duplicate https://github.com/florisboard/florisboard/issues/25

**Comment by D3SOX** [comment]
Feel free to add your screen recording and information as a comment in my issue :smiley:

**Comment by RickyM7** [comment]
@D3SOX Thanks for letting me know. I apologize for this, I will look more carefully the next time you open an issue.
