### ISSUE TITLE
Switch Smartbar Access Button to the Right

### ISSUE THREAD

**Issue by yant0** [florisboard/florisboard#472]
i think its beneficial for right/left handed user (however they prefer) to have this feature in.

![PicsArt_03-19-06 23 39](https://user-images.githubusercontent.com/80298071/111710493-619e0400-887c-11eb-8eeb-d01fa2bcc6c7.png)

+ i got wonky screen protector that doesnt want to register the very left part of my screen.
and thanks for making this great app

**Comment by patrickgold** [comment]
This would fall in line with the full Smartbar customization feature, will add this to the todo list.

**Comment by patrickgold** [comment]
The upcoming release 0.3.14-beta07 will contain the ability to "flip" the actions button between left and right, so this issue will be resolved.
