### ISSUE TITLE
Key Press Feedback is Laggy

### ISSUE THREAD

**Issue by jetrosut** [florisboard/florisboard#474]
You know how the color of a key's background changed when pressed for a short duration? I find it a bit laggy. I am not sure whether it is delayed or it takes too long to disappear. [You can find the videos here](https://imgur.com/a/fuGdoGS), I also included a video of another keyboard for comparison.

#### Environment information
- FlorisBoard Version: e.g. 0.3.7
- Install Source: F-Droid
- Device: A Samsung Galaxy Note
- Android version, ROM: Stock Android 7

**Comment by tsiflimagas** [comment]
Latest version is 0.3.9, it is probably much better in performance.

**Comment by jetrosut** [comment]
> Latest version is 0.3.9, it is probably much better in performance.

Just tried it on 0.3.9. Seems to be definitely faster.
