### ISSUE TITLE
Enlarge letters on keys

### ISSUE THREAD

**Issue by kojid0** [florisboard/florisboard#48]
It would be nice if the letters would be a little bigger in order to see them better. Especially when setting the keyboard height to tall, the letter-whiteSpace ratio gets odd.

Here's a screenshot of Floris Keyboard (left) and Openboard with bigger letters (right).
![floris](https://user-images.githubusercontent.com/24477557/100539042-ac473200-3233-11eb-804e-a172b35890ed.jpg)

**Comment by patrickgold** [comment]
I agree that the letter/white space ratio is odd. I have tried to improve the font sizing several times (e.g. #32), but it seems that my sizing algorithm still fails for some screen aspect ratios. I will look into it. Could you please fill out the fields below so I can try to recreate and fix the issue? Thanks in advance!

**Environment information**
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android version, ROM:

**Comment by kojid0** [comment]
Thank you!

**Environment information**

* FlorisBoard Version:   0.2.4
* Install Source:   F-Droid (IzzyOnDroid)
* Device:   Huawei P20 Pro
* Android version, ROM:   Android 9, EMUI stock ROM

**Comment by patrickgold** [comment]
Above commit improves the key font size algorithm. Also, the key font size in general is now bigger (depends on the device on how much this has changed though). See image below for a comparison. Will be released later today.

Comparison:
![keyfontsizecomp](https://user-images.githubusercontent.com/19412843/100784691-d6ede200-340f-11eb-9fdb-e43075190b7d.png)

**Comment by kojid0** [comment]
This is awesome! Thank you so much for this super-fast fix.
I've tested your new version, looks good!

**Comment by patrickgold** [comment]
Great to to hear that everything works on your device, thanks for your feedback!

**Comment by D3SOX** [comment]
Now they are huge for me. I liked it better in the previous version. I think it would be nice if you could add a slider to customize them.
Before:
![Screenshot_20201201-210228](https://user-images.githubusercontent.com/24937357/100790769-96469680-3418-11eb-91a2-f267a7fa759a.jpg)
After:
![Screenshot_20201201-210204](https://user-images.githubusercontent.com/24937357/100790781-9ba3e100-3418-11eb-9c88-64f058152bbc.jpg)

(OnePlus 6)

**Comment by kojid0** [comment]
> Now they are too large for me. I liked it better in the previous version. I think it would be nice if you could add a slider to customize them.

Too large? Keys themselves or letter font size? Could it be that you have changed the keyboard height?

**Comment by patrickgold** [comment]
@D3SOX Do you mean the font size or the keyboard height? Because the font size seems to be almost equal. The keyboard height (which affects the key height) has changed though, which you could change through the keyboard height setting. (like @kojid0 also says).

**Comment by D3SOX** [comment]
> > Now they are too large for me. I liked it better in the previous version. I think it would be nice if you could add a slider to customize them.
> 
> Too large? Keys themselves or letter font size? Could it be that you have changed the keyboard height?

I think both. It looks better in 0.2.5 in my opinion. I haven't changed the height. I'm always using extra tall regarding the height.

**Comment by patrickgold** [comment]
Try using "normal" (or any other variation) instead of "extra tall", as that's what I've optimized the new height algorithm for.

**Comment by D3SOX** [comment]
> > I think both. It looks better in 0.2.5 in my opinion. I haven't changed the height. I'm always using extra tall regarding the height.
> 
> Try using "normal" (or any other variation) instead of "extra tall", as that's what I've optimized the new height algorithm for.

I see. Now mid-tall seems to be more appropriate for me.

**Comment by patrickgold** [comment]
> I see. Now mid-tall seems to be more appropriate for me.

That's because I've improved the height algorithm, which makes FlorisBoard's base height taller on x*dpi devices. As you have an OnePlus 6, this change directly affects you and at first FlorisBoard is way too tall. (On my phone OnePlus 7T I#ve also found mid-tall to be the best option). Sorry for the inconvenience I've caused, but it would have been impossible to auto-convert this setting.

**Comment by RickyM7** [comment]
On my phone the size is perfect, thank you.

Keyboard Height: Normal
Device: Redmi Note 4 (Miui 11 - Android 7.0)

**Comment by patrickgold** [comment]
@RickyM7 Thanks for the feedback!

**Comment by patrickgold** [comment]
@D3SOX As you've said that the key font size is too large, I went investigating and found that it can really be too large in some circumstances. Above commit improves the default key font size, but more importantly introduces an option to adjust the key font size multiplier in the preferences (found in the category Keyboard). I've made two separate multipliers, one for portrait and one for landscape mode. This allows for the customization of the font height up to +/-25% of the default font size for each orientation. Will ship with the next release,

**Comment by RickyM7** [comment]
@patrickgold Could you increase the size of the hints and popup letters a bit?
I preferred not to open a new issue for this but if you want I can open.

Comparison:

| ForisBoard (The letters look small) | Simple Keyboard (Ideal size in my opinion) |
| :---: | :---: |
| ![FlorisBoard](https://user-images.githubusercontent.com/24703825/103179979-2b9a4680-4870-11eb-8202-4c8876a52d98.jpg) | ![Simple Keyboard](https://user-images.githubusercontent.com/24703825/103179987-35bc4500-4870-11eb-9bcf-2f7d62596ef6.jpg) |

**Comment by patrickgold** [comment]
@RickyM7 The size of the popup font is synced up with the size of the key font, which means in order to increase the popup font you also have to increase the key font. The preference for this is `Settings > Keyboard > Font size multiplier`, where you can increase the font size. 

The size of the hint is indeed not affected by any preference, which I will look into.

**Comment by RickyM7** [comment]
@patrickgold Got it.
