### ISSUE TITLE
Clipboard manager related question

### ISSUE THREAD

**Issue by GithbUser** [florisboard/florisboard#481]
Look the video and tell me why florisboard is not pasting copied data?

https://user-images.githubusercontent.com/75420364/111910267-b2814880-8a86-11eb-92c5-72934793a1c2.mp4

I copied that in bromite incognito mode but i dont think this should be cause of this happening

**Comment by X-yl** [comment]
Yep, I see the issue. When copying html text I forgot to change the mime type to text/plain (we aren't supporting html for the moment). I'll make a pull request to fix later today. Thanks for pointing this out!

**Comment by anjannair** [comment]
Since this is a clipboard related question I do not see clipboard manager for my device as shown in this video. I thought this was a future feature but realized it was my device that does not have it.

Version: 0.3.9
Android: 11
Phone: Samsung
