### ISSUE TITLE
Clipboard manager

### ISSUE THREAD

**Issue by mizzunet** [florisboard/florisboard#483]
Any chance clipboard manager in Florisbord? 
Thanks

**Comment by D3SOX** [comment]
Already implemented as of #454
Released with https://github.com/florisboard/florisboard/releases/tag/v0.3.10-beta02

**Comment by mizzunet** [comment]
> Already implemented as of #454
> Released with https://github.com/florisboard/florisboard/releases/tag/v0.3.10-beta02
Uhm, i'm on latest Florisboard from F-Droid and it doesn't seem to have it or am i missing anything?
![Screenshot_20210322-145338](https://user-images.githubusercontent.com/10193999/111967759-6eda1d80-8b1e-11eb-943e-b09d2aa5418a.png)

**Comment by D3SOX** [comment]
See #476
Currently you have to use the GitHub APK for the Beta

**Comment by mizzunet** [comment]
> See #476
> Currently you have to use the GitHub APK for the Beta

I see. Thank you :)

**Comment by mizzunet** [comment]
Wait, i'm already on beta as I installed it from IzzyOnDroid repo, now i'm noticing this

**Comment by X-yl** [comment]
You have to enable clipboard history in the settings (under keyboard preferences). It is disabled by default.

**Comment by Glitchy-Tozier** [comment]
In that case, this issue should be closed, right?

**Comment by mizzunet** [comment]
> In that case, this issue should be closed, right?



> You have to enable clipboard history in the settings (under keyboard preferences). It is disabled by default.

Thanks

**Comment by mizzunet** [comment]
> In that case, this issue should be closed, right?

Yes, of course

**Comment by mizzunet** [comment]
Wait, I accidentally turned off Smart Bar and also had disabled showing launcher icon. Now it seems like I can't access Florisboard settings anyway. Normally, a keyboard settings would open if tapped it in On-Screen Keyboard part of Settings, but it doesn't for Florisboard

**Comment by Glitchy-Tozier** [comment]
Long-press the comma-key, there you should find a pop-up that lets you enter the settings  ;)
