### ISSUE TITLE
Option to swap Z and Y

### ISSUE THREAD

**Issue by GrbavaCigla** [florisboard/florisboard#493]
It would be nice to have option to swap `Z` and `Y`. I am willing to do it, but I don't have any experiences with kotlin.

**Comment by D3SOX** [comment]
Just select QWERTY instead of QWERTZ. Or is it not available for your language?

**Comment by GrbavaCigla** [comment]
I use serbian layout and I contributed serbian layouts. I don't like the idea of just copying the same layout and swaping Z and Y.

**Comment by patrickgold** [comment]
Well that's how FlorisBoard's layout engine works and will work in the future - until layout customization comes, then you can arrange the keys within the Settings layout editor like you want :)
