### ISSUE TITLE
Clipboard manager implementation question

### ISSUE THREAD

**Issue by ChaoticHub** [florisboard/florisboard#495]
Hello,

Back in #113 I was asking about a private clipboard seperate from the system clipboard. The clipboard feature I can access in 3.10-beta01 seems to copy to the system clipboard. 

Also, I have no setting for enabling a clipboard history through the beta settings as shown here
![signal-2021-03-24-214230](https://user-images.githubusercontent.com/35610319/112406262-3a1ac180-8cea-11eb-9aac-9b55027cc14f.jpeg)

Thank you in advance for any help!

**Comment by tsiflimagas** [comment]
Clipboard manager was merged in 0.3.10-beta02, so you may want to try that, or latest, beta03.

**Comment by ChaoticHub** [comment]
Sorry, I must have misread the thread I was looking into! Thank you for the clarification @tsiflimagas
