### ISSUE TITLE
[FEATURE] Add clipboard box like in GBoard

### ISSUE THREAD

**Issue by coolerspeex** [florisboard/florisboard#496]

**Comment by Glitchy-Tozier** [comment]
Could you describe how this is supposed to work?
Not everyone uses Gboard.

**Comment by coolerspeex** [comment]
I can't explain much about this GBoard feature it here but i given below a example so you guy will get the means
 
Watch GIF here: 
https://ibb.co/Nj9j7wH

**Comment by GithbUser** [comment]
Do you mean clipboard manager feature?
Then it is already implemented in florisboard
Just download latest beta version from github releases 
And enable it in the setting
