### ISSUE TITLE
Absolute size / height

### ISSUE THREAD

**Issue by HyknuF** [florisboard/florisboard#50]
Is it possible to increase the height/size in "very large"? Imo it is still a bit too small even on biggest setting. Would appreciate that. Thanks!

**Comment by kojid0** [comment]
This would be awesome. Not only letters are small (#48) but the keys themselves are small too.

**Comment by patrickgold** [comment]
I would suggest less am "extra extra large" setting than improving the detection and adjustment to different screens, where the "normal" setting is better adjusted to your screen density and size. Then it should not be a problem to find the perfect setting for the keyboard height. I'll add it to my todo list!

**Comment by HyknuF** [comment]
sounds perfect, thanks in advance!

**Comment by patrickgold** [comment]
Above commit improves the keyboard height calculation, which should better set the value for the "normal" keyboard height. Note, that this implementation is still far from perfect. I've tried this new method on several physical devices and some emulators as well, but there are so many factors playing into this calculation to get it right that something can easily break the method for one device. It would be nice if you could give me feedback when I release this change (probably either tomorrow or on Wednesday) to tell if it improved or worsened the issue. Thanks in advance!

**Comment by kojid0** [comment]
I definitely will!
Thanks for working on issues so fast, you are the best dev I've seen in a long time :D Off-Topic, but you might want to set up a liberapay account for donations :)

**Comment by HyknuF** [comment]
I will give feedback as well. Thanks for your great and fast work. it's a pleasure to work with you :-)

**Comment by patrickgold** [comment]
@kojid0 @HyknuF Thanks for your positive words! It is also a pleasure to work with all of you. Having a community which gives you ideas, gives feedback, etc. makes programming so much more fun and enjoyable. 😄

**Comment by patrickgold** [comment]
Above commit is the preliminary final commit regarding the keyboard height topic, which again improves the height algorithm, key sizing algorithm, etc. and adds a custom option to set the percentage value directly as well. This allows me to address all users and it is up to the user which option fits best to him.

These changes will ship with the next regular release on Sunday (v0.3.0). I will close this issue now, if anything regarding this topic arises again, feel free to reopen it though! (or create a new issue)
