### ISSUE TITLE
Auto-capitalisation of suggested words and auto-correct

### ISSUE THREAD

**Issue by gitanonaddy** [florisboard/florisboard#500]
1- Request to add auto-capitalisation of suggested words based on the caps states of the main keyboard. 

2- Request to add auto-correct option, replacing the word with the one shown in suggestion for the given language. If the user does not want to change the typed word to the suggested word, he/she may swipe up or down (gesture integrated suggestions) to navigate through different suggestions and even go back to the original typed word. This is a major attraction of Fleaky keyboard, and honestly it works great.

**Comment by patrickgold** [comment]
Thanks for your suggestion!

Auto-capitalisation as well as spellchecking&automatic selection of correct word is planned, will close this issue thus.
