### ISSUE TITLE
Implement system spell-checker

### ISSUE THREAD

**Issue by Lurux** [florisboard/florisboard#501]
Hi Patrick,

I've been following the evolution of Florisboard for a few months, and am starting to really enjoy it ! :smile:

One of the things I have noticed is that Florisboard is the only FOSS keyboard that I know which support actual multilingual suggestions (aka, without manually changing the type). This is **really** useful, please keep that option !

However, I've noticed the native Android spell-checker doesn't properly support multilingual suggestions, so word often get flagged as invalid even though they are properly recognized by Florisboard.

I've personally disabled that in the meantime - but, considering Florisboard already uses dictionary files, do you think it would be possible to implement a system spell-checker like GBoard does ?

**Edit:** Just to be clear, I think this may be a low priority one, since we can always click on a word and use the suggestion bar as a spelling corrector. It just won't highlight the wrong words.

Thanks !

**Comment by patrickgold** [comment]
That's true, FlorisBoard does currently not ship its own spell checker service, thus words which are recognized in the Smartbar are out of sync with the ones underlined in the textedit. A FlorisBoard spell checker service will definitely come, but don't know yet if I will do it in the 0.4.0 or 0.5.0 milestone.

**Comment by Lurux** [comment]
To be fair, I don't know any other FOSS keyboard that does this, either...

**Comment by patrickgold** [comment]
> To be fair, I don't know any other FOSS keyboard that does this either...

OpenBoard does it AFAIK (at least such is defined in the manifest).

> As I said, I don't really know if that should be a high priority, since one can disable the spell checker and use the smart bar as such anyways.

This is true, though a spellchecker still is useful IMO, so at some point I will add such.

**Comment by Lurux** [comment]
> OpenBoard does it AFAIK (at least such is defined in the manifest).

Oh, ok. I haven't tried OpenBoard recently, since it's very close to the AOSP keyboard that I use on LineageOS.
