### ISSUE TITLE
Fix question mark for Persian and Arabic and Urdu and Kurdish languages.

### ISSUE THREAD

**Issue by xmha97** [florisboard/florisboard#503]
question mark in L2R language is: `?` (U+003F)
but question mark in R2L language is: `؟` (U+061F)
Learn more: https://en.m.wiktionary.org/wiki/%D8%9F
![Firefox](https://user-images.githubusercontent.com/23485114/112623818-72d1ac80-8e4a-11eb-830e-ae46a2386ab3.jpg)
Please fix question mark for Persian and Arabic and Urdu and Kurdish languages.

**Comment by Waelwindows** [comment]
This was already discussed in #120

**Comment by patrickgold** [comment]
Above PR adds a rtl question mark for Arabic/Persian languages, will be released with v0.3.10-beta05
