### ISSUE TITLE
Add En-IN language customisation with rupee currency symbol

### ISSUE THREAD

**Issue by cookieninja01** [florisboard/florisboard#507]
Language addition and keyboard customisation / mspping for English-Indian with standard qwerty keyboard and rupee symbol (₹) instead of the standard currency key (₱£¥€¢ or $).

**Comment by cookieninja01** [comment]
![Screenshot_20210327-102217_Mull](https://user-images.githubusercontent.com/15329610/112710354-418fc580-8eb8-11eb-9dc1-019493b866a5.png)
Instead of the dollar symbol ($) on the currency, there needs to be a rupee (₹) symbol.

**Comment by patrickgold** [comment]
Thanks for your suggestion! English (India) is not yet supported by FlorisBoard, see #104. Currency symbol customization is another topic, which is also already in the issue tracker (#210). Closing this issue as it is a duplicate.
