### ISSUE TITLE
Three-dot (…) Character

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#51]
It would be great if this character was added to FlorisBoard.

![Tree-dot](https://user-images.githubusercontent.com/24703825/100635746-a4f55680-330f-11eb-96e1-1076d5d5c0a6.jpg)

**Comment by patrickgold** [comment]
Above commit adds the three dot character to the popup of the period in the symbols layout. Will be included in the next release. Thanks for your suggestion!

**Comment by RickyM7** [comment]
@patrickgold I don't want to open a new issue for this, but could you add this character (`⋮`) to the keyboard? I don't know where it should go because I've never seen a keyboard with that character, but maybe it being a popup of the character `:` (colon) would be nice.

**Comment by patrickgold** [comment]
@RickyM7 Yes, I can definitely add it as a colon `:` extended popup character. Could you just please open a new issue for this? It is hard to keep track for me which things to implement if they are hidden in already resolved and closed issues. Thanks!
