### ISSUE TITLE
It's possible to open multipe pop-ups

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#513]
Is this intentional? 

![20210327_184534.jpg](https://user-images.githubusercontent.com/59611881/112729568-1dba9700-8f2d-11eb-8190-b37624410719.jpg)

It seems like a handy system.
IF it's intended to work this way, i suggest always placing the most recent popup on top of all the other ones. Currently, there is no dynamic system that regulates this. For example, the `o`-pop-ups are always on top of the `u` ones.

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment]
No this was introduced rather accidentally with the multi-touch support, thus allowing for multiple popups to receive inputs from one unique pointer. Intended is that only the last popup is visible and any previously opened popups close themselves.

**Comment by Glitchy-Tozier** [comment]
In that case this should be corrected.  :)

**Comment by Glitchy-Tozier** [comment]
In case you need some motivation or enjoy having nightmares, enjoy those screenshots:  ;)

![20210328_211226.jpg](https://user-images.githubusercontent.com/59611881/112764847-a65b3500-900a-11eb-8727-b6c8d877ceca.jpg)
![Screenshot_20210328-211317_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/112764853-a9eebc00-900a-11eb-8d48-b5b9242fa24d.jpg)

**Comment by patrickgold** [comment]
Works also with emoji popups on the character layout :) I really have to force cancel pointers if the displayed layout/context changes...

**Comment by patrickgold** [comment]
Above PR rewrites the layout rendering and logic, with this the popup manager also got an update. it is now impossible to open multiple popups (in the text context) and this should also fix #515. (Can't reproduce that bug but I never could anyways so hard to tell). As I included several additional safeguards to reset popup states, I will close #515 with the above PR.

**Comment by Glitchy-Tozier** [comment]
Kk, good Job!
