### ISSUE TITLE
Changing Uppercase and lowercase for suggestion 

### ISSUE THREAD

**Issue by shockergit** [florisboard/florisboard#516]
It would have been handy if we can change the suggestions also to uppercase and lowercase when we change the keyboard cases. It works in Swiftkey hope we can also get that feature for suggestions.
Full lowercase
First word uppercase 
Full uppercase

**Comment by shockergit** [comment]
![Uploading IMG_20210328_161304.jpg…]()

**Comment by shockergit** [comment]
![IMG_20210328_161228](https://user-images.githubusercontent.com/63154802/112749545-741de900-8fb2-11eb-9c07-2c2281bbcabf.jpg)

**Comment by shockergit** [comment]
![Uploading IMG_20210328_161248.jpg…]()

**Comment by shockergit** [comment]
![IMG_20210328_161304](https://user-images.githubusercontent.com/63154802/112749559-99125c00-8fb2-11eb-984a-cf851dd2f5cd.jpg)

**Comment by shockergit** [comment]
![IMG_20210328_161228](https://user-images.githubusercontent.com/63154802/112749564-a3ccf100-8fb2-11eb-8f8c-9a437112c69d.jpg)

**Comment by shockergit** [comment]
![IMG_20210328_161304](https://user-images.githubusercontent.com/63154802/112749586-c101bf80-8fb2-11eb-8f88-d0aec3fde55d.jpg)

**Comment by patrickgold** [comment]
It is known that the suggestions currently not respect the caps state, see #441. Closing this issue as a duplicate.

**Comment by shockergit** [comment]
Sorry for the duplicate
