### ISSUE TITLE
Adding a Clipboard symbol by removing the emoji icon

### ISSUE THREAD

**Issue by shockergit** [florisboard/florisboard#517]
It would be nice if we remove the emoji symbol from top. We already have one emoji icon in the bottom row. I think you should change it into Clipboard icon which show all the saved clipboards.

**Comment by shockergit** [comment]
![IMG_20210328_161846](https://user-images.githubusercontent.com/63154802/112749700-a11ecb80-8fb3-11eb-84e7-dbac18a797dd.jpg)

**Comment by patrickgold** [comment]
Thanks for your suggestion! This issue falls under the Smartbar full-customization topic, so you will be able to change that when I implement Smartbar full-customization.

**Comment by shockergit** [comment]
Thanks soo much
