### ISSUE TITLE
Numbers disappear in the number row

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#52]
**Environment information**
- FlorisBoard Version: 0.2.5
- Install Source: GitHub
- Device: OnePlus 6
- Android version, ROM: Android 10, Paranoid Android Quartz 5

**Steps to reproduce**
1. Enable number row and open FlorisBoard on a text field
2. Type any number, switch to symbols, type a colon and switch back
3. Numbers are missing

<details><summary>Screen Recording</summary>
<p>

![screen-20201130-214441](https://user-images.githubusercontent.com/24937357/100663304-5fa84780-3356-11eb-952e-399d7b7fcee6.gif)

</p>
</details>

I hope you can reproduce it and it's not some weird bug that depends on my environment or some setting.

**Comment by patrickgold** [comment]
Thanks for reporting this bug, I'll look right into it!

**Comment by patrickgold** [comment]
Thanks to your screen recording I was able to quickly reproduce the bug on my system. I've fixed it so it only shows in the character layout like it should (the logic of the visibility was 1 step behind). Will release either tomorrow or on Wednesday. Have a nice evening!

**Comment by D3SOX** [comment]
Thanks for the fast response and resolution. A nice evening as well!
