### ISSUE TITLE
One-Handed Mode Cuts Off Text in Copy&Paste View

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#520]
Personally, I have zero interest in the one-handed mode, but i thought i'd mention the issue.  :)

It's not horribly cut-off, but it's not nice either.
![Screenshot_20210328-202554_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/112763578-5168f000-9005-11eb-9bd8-94e07e8d64f4.jpg)

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by Glitchy-Tozier** [comment]
The top of the screen is just me not being perfect at cropping images.

**Comment by patrickgold** [comment]
That's a result of localization imperfections, where the translated term is much longer than its English base. The only solution is to automatically decrease the font size for buttons where the text is too big. Placing on my todo list.

**Comment by Glitchy-Tozier** [comment]
Theoretically, there's the option to stack the words on top of each other.

The button seems big enough after all.

**Comment by lm41** [comment]
I think this layout was removed at some point.

**Comment by patrickgold** [comment]
Nope this layout does indeed not exist anymore, old times that this screenshot was taken in...

**Comment by Glitchy-Tozier** [comment]
> old times that this screenshot was taken in...

Indeed :)

Well, let's close the issue if it's not relevant anymore!
