### ISSUE TITLE
Back-Button in Emoji-View is Misleading

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#521]
It kind of implies that we'll return to the letter-keyboard. Instead we return to whatever view we were on before switching to the emoji-view.

(By doing Glitchy-Things™ I can even make the ABC-button return to the Copy&Paste-view.)

I suggest either changing the ABC icon or always backing off to the letter screen.

![Screenshot_20210328-204253_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/112764010-123b9e80-9007-11eb-8ef3-09f504ff4782.jpg)

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment]
> Instead we return to whatever view we were on before switching to the emoji-view.

Yup, this describes the code behind this button pretty much perfectly :)

> (By doing Glitchy-Things™ I can even make the ABC-button return to the Copy&Paste-view.)

You use the good ol' tap two buttons at the same time hack to confuse the input logic, aren't you xD? (At least I could reproduce the bug with this)

> I suggest either changing the ABC icon or always backing off to the letter screen.

I will do the latter one, as this was the original idea when I implemented the icon for this.

**Comment by patrickgold** [comment]
Above commit fixes the ABC behavior, it now always returns to the characters layout.

**Comment by Glitchy-Tozier** [comment]
> You use the good ol' tap two buttons at the same time hack to confuse the input logic, aren't you xD?

Yup  xD

Btw, all those emoji bugs occured to me as a result of trying to reproduce #515.
