### ISSUE TITLE
Double-space period is placing the period in the wrong spot

### ISSUE THREAD

**Issue by LordCozyCat** [florisboard/florisboard#524]
#### Short description
When entering a double-space for a period, the period is placed in the second space like this .

#### Steps to reproduce
1. Type words into any input field
2. Double-space to place a period
3. See period in wrong place

#### Environment information
- FlorisBoard Version: v0.3.9
- Install Source: F-Droid
- Device: Mi Mix 2
- Android version, ROM: 9, Lineage OS 16

Additionally, see the attached GIF: https://imgur.com/a/NsT1XI2

**Comment by patrickgold** [comment]
Nooo, not this bug again. I had this misbehavior for a long time while the input logic rework but then I adjusted things and this didn't really occur anymore. Will place this one on my todo list but I am unsure on a technical level how to fix it yet.

**Comment by Glitchy-Tozier** [comment]
This feels completely random. Timing doesn't seem to have any role in how the bug works and i can't see any patters.

One thing I would like to point out is that sometimes, rarely, no period is entered at all. Just two spaces.

**Comment by Glitchy-Tozier** [comment]
Glitchy reporting to duty.

Something that might help you get to the bottom of this: what actually happens in the `asdf .`-bug is that `SPACE → PERIOD → SPACE` gets entered, then the last space gets deleted.

You can check this out by getting the `asdf .`-bug to occur and then clicking the undo-button. This produces an additional space behind the period.

**Comment by patrickgold** [comment]
Thanks for the detailed inspection of what could be the issue behind this bug, I will use this when I fix this issue!

**Comment by magnus-ISU** [comment]
I'm unsure whether there is any interest in fixing this feature, however it doesn't seem random to me. If the last word I typed was typed regularly or filled in via suggestion, then it works as expected. If I glide-type a word, then the bug manifests.

**Comment by patrickgold** [comment]
Above linked PR majorly reworks the input connection editor cache and logic, with that I couldn't reproduce this bug anymore. When 0.3.16-beta01 releases (should be this weekend, am currently finishing off the rework), could you please check for yourself if this bug is fixed? Thanks in advance!
