### ISSUE TITLE
Auto-capitalize letters only

### ISSUE THREAD

**Issue by djpohly** [florisboard/florisboard#528]
#### Short description
It seems more intuitive for auto-capitalization to behave more like a temporary "Caps Lock" than a temporary "Shift Lock" - i.e. letters are shifted, but other characters are not.  This is noticeable on the Dvorak layout since there is punctuation on the main keyboard.  (Likewise, if an extended layout were someday to include a numbers row, you definitely wouldn't want auto-capitalization to turn the first digit into !@#$.)

#### Steps to reproduce
1. Update to latest FlorisBoard.
2. Try to text the message "..." to a friend.
3. Send ">.." instead.
4. Be mildly embarrassed.

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: F-Droid
- Device: OnePlus 6T
- Android version, ROM: 10, OxygenOS 10.3.9 (stock)

**Comment by patrickgold** [comment]
The punctuation difference on Dvorak for lower and upper case is a feature which has been added specifically for these layouts, because quite a few people suggested that other keyboards are also doing this, The upper case symbol is not random, but specifically defined. If a number for instance is defined, it can't just automagically turn into some random letter without a specific upper case modifier.

**Comment by djpohly** [comment]
Certainly - the punctuation change makes perfect sense if you've pressed Shift. This was meant to be about auto-capitalization at the beginning of a sentence, where it doesn't really make sense.

**Comment by patrickgold** [comment]
You can turn off auto-capitalization in Settings > Typing > Auto-capitalization

**Comment by djpohly** [comment]
Yes, I understand that I can turn off the entire feature, downgrade, build my own, uninstall, etc., though it's not my preferred solution. :)

There is a difference between *shifting* and *capitalization*. Shifting is what happens when you hold the Shift key, which should change `1a.` to `!A>` like on a regular computer keyboard. Capitalization is what the Caps Lock key does, changing `1a.` to `1A.`. The latter is what I think makes more sense at the beginning of a sentence, and the option isn't called "auto-shifting."

(It was my mistake to bring up the numbers row, because they now behave inconsistently with symbols by not being shifted when Shift is pressed. I can file a separate issue for that.)

**Comment by patrickgold** [comment]
Oh now I see what you mean! Gboard is changing the numbers out when shift is activated, but not if caps lock is activated. This could be a separate feature request, because currently it is not implemented.

**Comment by patrickgold** [comment]
Above PR implements a proper shift state logic and a shift state selector. This means the symbols in Dvorak are now fixed and behave like in other keyboards as well, only showing the other layer of the 3 symbols when the shift was manually pressed. For caps lock and auto-capitalization the "normal" 3 symbols are shown.

Thanks again for reporting and the good explanation of shift vs caps lock, this brought me on the right track to implement the shift logic properly into FlorisBoard :) In the future other layouts which require similar logic will benefit from this too. Will be released in 0.3.16-beta02 in a few days.
