### ISSUE TITLE
Number layout not reliably showing up in special input fields

### ISSUE THREAD

**Issue by s99h** [florisboard/florisboard#532]
#### Short description
This behaviour occured after the update from v0.3.10-beta03 to v0.3.10-beta04.
Usually the keyboard shows a reduced layout for entering numbers in special input fields like PINs or phone numbers.
After the update to the recent beta release it doesn't reliably show the number layout but often the default layout.

#### Steps to reproduce
1. Open an app with a field that requires to input numbers and simply enter that field.
2. The keyboard should come up with the number layout but instead shows the default layout.

Further observations:
1. Take the contacts app as an example. Open an existing contact and directly place the cursor in a field to enter a phone number. This triggers the default layout.
2. Now place the cursor in a pure text field, e. g. The name of your contact. The keyboard still shows the default layout, which is expected. 
3. Finally going back to the number field, the number layout comes up.

This can also be reproduced with the help of the security PIN field in Threema. If no keyboard is shown in your launcher and you start Threema, the bug is to be seen. 
Change back to your launcher (KISS or T-UI in my case) touch an input field to trigger the keyboard, change back to Threema - and the number layout ist there ...

#### Environment information
- FlorisBoard Version: v0.3.10-beta04
- Install Source: GitHub
- Device: Huawei Mate 9
- Android 7.0 Stock ROM, unrooted

Thank you!

**Comment by GithbUser** [comment]
I confirm this bug
Device Poco m2 pro
Android 11 ArrowOS
Florisboard 0.3.10 beta4

**Comment by GithbUser** [comment]
I confirm this bug
Device Poco m2 pro
Android 11 ArrowOS
Florisboard 0.3.10 beta4

**Comment by GithbUser** [comment]
I confirm this bug
Device Poco m2 pro
Android 11 ArrowOS
Florisboard 0.3.10 beta4

**Comment by patrickgold** [comment]
Above commit fixes the behavior, the number layout now consistently displays again. Thanks again for your bug report!
