### ISSUE TITLE
Tapping on predcited word doesn't replace word

### ISSUE THREAD

**Issue by mizzunet** [florisboard/florisboard#533]
#### Short description
http://transfer.sh/QwWdz/screen-20210330-134814.mp4

#### Steps to reproduce
1. Install latest, 0.3.10-beta04
2. Types somthing somewhere
3. Tap on any preditcted/suggested word
4. It does not correct the word, at rare times it does

#### Environment information
- FlorisBoard Version: 0.3.10-beta04
- Install Source: F-Droid
- Device: OnePlus 5
- Android version, ROM: Android 11, RevengeOS

http://transfer.sh/uuHiB/2021-03-30-13-47-49.txt

**Comment by patrickgold** [comment]
Yup, I am aware that this issue occurs on some devices. Just to be sure, if you go to Settings > Typing > Suggestions display mode and use another option that "Dynamic width & scrollable", it works flawlessly then?

**Comment by patrickgold** [comment]
Above PR (hopefully) fixes the dynamic scrollable word selection bug. The PR will close this issue automatically. Should the bug still occur after releasing v0.3.10-beta05, I will reopen this issue and further investigate into this bug.
