### ISSUE TITLE
Popup position is incorrect for rtl languages

### ISSUE THREAD

**Issue by dinuto** [florisboard/florisboard#536]
#### Short description
As you can see in the video, when my device language is Hebrew, the popups are shown in a wrong place. When I switch my device language to English it works fine.

https://user-images.githubusercontent.com/76748920/113027895-48a62480-9193-11eb-854d-86f5c57d79c9.mp4

#### Steps to reproduce
It may be miui-related bug.
1. Change your device language in your device settings to Hebrew (maybe other rtl language will also cause this bug)
2. Try to type with FlorisBoard

#### Environment information
- FlorisBoard Version: **0.3.10-beta04**
- Install Source: **F-Droid**
- Device: **Xiaomi redmi note 8**
- Android version, ROM: **android 10, miui 12**

**Comment by patrickgold** [comment]
Thanks for your bug report! This could be because the UI is set to RTL which may confuse the popup placement algorithm. WIll investigate into this.

**Comment by patrickgold** [comment]
Above PR fixes the popup position for rtl languages. Will be released in v0.3.11-beta01!

**Comment by yonnf** [comment]
Thank you, this is such an important project!

**Comment by dinuto** [comment]
Thank you, this is such an important project!
