### ISSUE TITLE
Hide clipboard suggestion after using it

### ISSUE THREAD

**Issue by mizzunet** [florisboard/florisboard#538]
I think, the clipboard suggestion should be hidden after using it. Currently this hides only if 60 seconds passed(timout default setting) no matter if used or not

**Comment by patrickgold** [comment]
Thanks for your suggestion! Placing this on my todo list.

**Comment by mizzunet** [comment]
> Thanks for your suggestion! Placing this on my todo list.

Thanks :)

**Comment by patrickgold** [comment]
Above PR adds your requested feature, will be released in v0.3.10-beta05.
