### ISSUE TITLE
Make icons scale with the text size

### ISSUE THREAD

**Issue by IronVeil** [florisboard/florisboard#540]
Hi. I think that it would be good if the icons for backspace/enter follow the same size as the font size multiplier. I currently have my font size set at 90%, but the icons look massive and don't change. By making the icons scale with the rest of the letters would make the keyboard look more consistant and overall better. 

Heres the large icons here:
![Keyboard here with the large icons](https://user-images.githubusercontent.com/46629504/113147342-96b93780-9228-11eb-8d85-e54bc54b0f1e.jpg)

**Comment by patrickgold** [comment]
Thanks for your suggestion! This is true, the font size multiplier currently only applies to the text labels and not to the icons, because the icons are trying to auto-fit into the key. Will place your suggestion on the todo list!

**Comment by patrickgold** [comment]
Above PR allows the drawables of the delete, shift, enter etc. key to scale automatically based on the font scaling set. Will be released in v0.3.11-beta04!
