### ISSUE TITLE
Add custom shortcuts

### ISSUE THREAD

**Issue by IronVeil** [florisboard/florisboard#541]
I think that it would be pretty cool if you could set custom shortcuts, like Gboard and Swiftkey. For example, if you enter "email" or "@@" then your email address appears in the smartbar.

**Comment by Turbotomate** [comment]
Would be a nice addition. Maybe one can implement it in an additional way, which not only shows the saved text in the smartbar, but instead directly replaces the written shortcut in the text field your writing in. But this should definetely be only an additional option.

**Comment by patrickgold** [comment]
With the use of user dictionaries you now indirectly also have a way to define shortcuts. Go to Settings > Typing > Dictionary > (System/Internal) User dictionary > Add new word. Here you can define a word and a shortcut for it. Will close this issue thus.
