### ISSUE TITLE
Copy&Paste activation after shift & space-swipe

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#542]
Okay, so the issue that happens on my phone is this:
When using Shift+Spacebar-swipe to select text, the copy-button only gets activated after you release BOTH shift and space. In my opinion it should be active immediately, even without releasing the two buttons.

(Delete-swipe also doesn't activate the copy-button anymore)

_Originally posted by @Glitchy-Tozier in https://github.com/florisboard/florisboard/issues/534#issuecomment-811121288_

**Comment by Glitchy-Tozier** [comment]
Patrick's response:
> > When using Shift+Spacebar-swipe to select text, the copy-button only gets activated after you release BOTH shift and space
> 
> This is actually intended behavior to avoid updating the UI constantly while the selection rapidly changes.
> 
> > Delete-swipe also doesn't activate the copy-button anymore
> 
> Happens because normally the copy/paste buttons don't get updated until the selection is final (meaning you stopped selecting and released your input pointer). For the delete swipe, there's no final selection, because the final selection is immediately deleted.
> 
> > Not sure if that's the same issues you're battling, but they are kind of annoying.
> 
> I can try to at least update the Smartbar UI for every change instead of only the final one, though this isn't the bug for the above mentioned issue.

**Comment by Glitchy-Tozier** [comment]
> I can try to at least update the Smartbar UI for every change instead of only the final one, though this isn't the bug for the above mentioned issue.

I don't quite understand... isn't that the thing you said you removed on purpose?

**Comment by patrickgold** [comment]
> I don't quite understand... isn't that the thing you said you removed on purpose?

I suppress the whole onUpdateSelection() event chain to avoid UI stuttering while rapidly changing the selection and then dispatch an update selection event when the pointer releases. I can try to single out the copy/paste button activation feature and let it update as soon as the selection changes, to the state is always up-to-date.

**Comment by Glitchy-Tozier** [comment]
If that doesn't hurt the UI, go for it!  :)

I think this is a good change to improve "flow" when using the keyboard, just like you let the user touch the next letter-key even when the previous one wasn't released yet.

**Comment by Glitchy-Tozier** [comment]
@patrickgold Seems to have been fixed, should we close the issue?

**Comment by patrickgold** [comment]
This bug is fixed (except for editors where the cursor position is incorrectly or not at all reported), so I think we should close this issue.
