### ISSUE TITLE
Keyboard switching unintended (gestures)

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#545]
At first, I thought it might be a bug.
Keyboard keeps switching randomly on new keyboard initiation.
I never notice it switching, only after keyboard opens due to trigger and other keyboard app is launched.

Somehow keyboard seems to be switching in the background.
It might be due to gestures activating in background?

![](https://i.imgur.com/7y9xeXm.png)

**Comment by patrickgold** [comment]
No, the space bar up gesture seems to be a bit too sensitive for some users. I don't exactly know why, but the only thing I can do is to further increase the distance threshold to avoid accidental triggering the gesture.

**Comment by patrickgold** [comment]
Above PR adjusts the space bar up gesture a bit so it doesn't trigger on move anymore. This should make hitting it accidentally a bit harder. Will be released in v0.3.11-beta01.
