### ISSUE TITLE
List all permissions in Readme 

### ISSUE THREAD

**Issue by kojid0** [florisboard/florisboard#55]
Especially for privacy enthusiasts, it would be nice to see all permissions florisboard has by default / requests

**Comment by patrickgold** [comment]
Great idea, I will add it to the README.md as a separate section.

**Comment by patrickgold** [comment]
I've added a reference to the [permission wiki page](https://github.com/florisboard/florisboard/wiki/List-of-permissions-FlorisBoard-requests) to the README.md.
