### ISSUE TITLE
Space Swipe Word delete on null field crashes floris

### ISSUE THREAD

**Issue by CanadianVice** [florisboard/florisboard#553]
Sorry if this has already been raised, but mobile.

Anyway, if the option to do full word deletion is set on the spacebar gestures (ie, swipe left on space to delete current word) and the field is empty, Floris crashes. It does fall back to an alternative keyboard, but otherwise it's not a graceful crash.

Brief testing makes it super obvious that it's just null was left unhandled when triggering that gesture. Easy fix, probably.

Nice keyboard, though!

**Comment by CanadianVice** [comment]
Android 10, vanilla, LG G8X ThinQ btw. Keyboard vers is 0.3.9 off of F-Droid.

**Comment by Glitchy-Tozier** [comment]
Sounds like it might be related to #525

**Comment by CanadianVice** [comment]
> Sounds like it might be related to #525

with near certainty. Sorry, i was on mobile and so not really in a place to search more thoroughly.

**Comment by Glitchy-Tozier** [comment]
No worries! Btw, I love that sentence!  :)

> ...but otherwise it's not a graceful crash.
