### ISSUE TITLE
Issue on suggest correct word

### ISSUE THREAD

**Issue by yankritt** [florisboard/florisboard#559]
#### Short description

First of all thank you for your great work, it is a very well done keyboard, although in my samsung S9+ device, when typing and the suggestion of the word you type appears at the top, it does not change down the word, it does not change to the suggested option, I do not know why????
#### Steps to reproduce
1. Go to: "cuando escribes"
2. Click on suggestion word
4. See error: dont change to suggested word

#### Environment information
- FlorisBoard Version:  the last Version
- Install Source:  F-DROID
- Device: 
- Android version, ROM:  10

**Comment by patrickgold** [comment]
Do you use the latest version of the stable or beta track? (The beta track is known to have this bug currently)

**Comment by yankritt** [comment]
I use 0.3.10.Beta04

2 abr. 2021 3:17:50 p. m. Patrick Goldinger ***@***.***>:

**Comment by patrickgold** [comment]
Ah ok, then it is most likely #533. If you go to Settings > Typing > Suggestions display mode and use another option that "Dynamic width & scrollable", does it works then?

**Comment by yankritt** [comment]
It worked!!!!!!  Thank you very much

2 abr. 2021 4:24:48 p. m. Patrick Goldinger ***@***.***>:

**Comment by yankritt** [comment]
Resuelto
