### ISSUE TITLE
Number row not showing 

### ISSUE THREAD

**Issue by GithbUser** [florisboard/florisboard#563]
In latest beta 3.10beta5 number row isnt showing 
Also when number row is enabled ,
Hinted symbols and numbers move below a row
![Screenshot_20210403-105432](https://user-images.githubusercontent.com/75420364/113469537-e9366600-946b-11eb-9c50-5316531706e3.png)

Environment information
- FlorisBoard Version: 0.3.10 beta 5
- Install Source: github
- Device: poco m2 pro
- Android version, ROM: Android 11,Arrow os

**Comment by s99h** [comment]
I can confirm.

Environment information

FlorisBoard Version: 0.3.10 beta 5
Install Source: github
Device: Huawei Mate 9
Android version, ROM: Android 7.0, stock

**Comment by patrickgold** [comment]
Thanks for your bug report! Can reproduce it and it happens because I forgot to update the layout type for the character number row, thus it fails to load the number row asset correctly. Will fix it ASAP!
