### ISSUE TITLE
Crowdin Dutch translation

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [florisboard/florisboard#57]
https://crowdin.com/project/florisboard/nl

Dutch translation is finished

(and i write you on crowdin)

**Comment by patrickgold** [comment]
Thanks for translating FlorisBoard into Dutch, i really appreciate it! Your translations will ship with the next release on Sunday (v0.3.0).

(Sorry for not answering on Crowdin, i seem to have completely missed the notification for it)
