### ISSUE TITLE
Keyboard crash when click on PASTE button!

### ISSUE THREAD

**Issue by kurdikeyboard** [florisboard/florisboard#571]
copy some content then open Text Editor suddenly Florisboard is crashing when when goto text editor and press on Paste button!

Android: 10

Device: Realme X2 Pro

FlorisBoard: 3.10.beta05

~~~ 1617590290636.stacktrace ~~~

java.lang.NullPointerException
	at dev.patrickgold.florisboard.ime.core.EditorInstance.performClipboardPaste(EditorInstance.kt:438)
	at dev.patrickgold.florisboard.ime.text.TextInputManager.onInputKeyUp(TextInputManager.kt:708)
	at dev.patrickgold.florisboard.ime.core.InputEventDispatcher$1$3.invokeSuspend(InputEventDispatcher.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by patrickgold** [comment]
Thanks for your bug report! I can't exactly reproduce this bug but see at least where the exception comes from. In https://github.com/florisboard/florisboard/blob/c0f90a7ea4cc59f671e174bd08226e3c7872d156/app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt#L473-L478

The primary clipboard clip is taken and committed to the input connection, though it is empty and thus crashing. I can wrap it around in a safeguard for null values, though the real question is why it was null in the first place, if you just copied an item.

Could you provide a screenshot of your clipboard settings (Settings > Keyboard > Clipboard group), so it is easier for us to debug what went wrong based on the enabled clipboard features? Thanks!

**Comment by X-yl** [comment]
Ah I think I figured it out. I believe this occurs when pasting with `EditingKeyboardView`. The enabled status is only set in the `onUpdateSelection`, here: https://github.com/florisboard/florisboard/blob/ffbf7f8ea72d6953e1b166a9417455e603ba24e9/app/src/main/java/dev/patrickgold/florisboard/ime/text/editing/EditingKeyboardView.kt#L83 (and even then, I've forgotten to do it properly by calling `FlorisClipboardManager#canBePasted`...) Which means when it's first opened, before any `onUpdateSelection` events, the paste button is enabled even if there isn't a primary clip set, leading to the above NPE.

I'll open a PR to fix.

**Comment by kurdikeyboard** [comment]
> Ah I think I figured it out. I believe this occurs when pasting with `EditingKeyboardView`. The enabled status is only set in the `onUpdateSelection`, here:
> 
> https://github.com/florisboard/florisboard/blob/ffbf7f8ea72d6953e1b166a9417455e603ba24e9/app/src/main/java/dev/patrickgold/florisboard/ime/text/editing/EditingKeyboardView.kt#L83
> 
> (and even then, I've forgotten to do it properly by calling `FlorisClipboardManager#canBePasted`...) Which means when it's first opened, before any `onUpdateSelection` events, the paste button is enabled even if there isn't a primary clip set, leading to the above NPE.
> I'll open a PR to fix. @kurdikeyboard could you confirm that this is the issue that occurred?

Yeah i confirm that's happening everytime when i open Text Editor and when press on Paste button the app is crash immediately

**Comment by kurdikeyboard** [comment]
Thank you all devs i hope you fix that error in new Beta version.
