### ISSUE TITLE
Number row disappeared

### ISSUE THREAD

**Issue by sirsleon** [florisboard/florisboard#572]
Number row on
![Screenshot_20210405-165231575](https://user-images.githubusercontent.com/65666396/113546460-6100be00-962f-11eb-9e23-7f9d63f17556.jpg)

Number row off
![Screenshot_20210405-165245403](https://user-images.githubusercontent.com/65666396/113546466-65c57200-962f-11eb-960e-4ca653978abb.jpg)

Florisboard Beta 0.3.10-beta05
Android 10 • Redmi Note 8 Pro

**Comment by Glitchy-Tozier** [comment]
Hi  :)

If this is the same issue as #563, it should be fixed in the next version.

**Comment by sirsleon** [comment]
> Hi :)
> 
> If this is the same issue as #563, it should be fixed in the next version.

Ah yep, I think so. thanks.
