### ISSUE TITLE
Space typed word after glide 

### ISSUE THREAD

**Issue by another-sapiens** [florisboard/florisboard#581]
Whenever you glide a word and manually type something immediately after, it won't be separated. 
This is okay if someone wants to add something to the previous word, like typing "as" after gliding "where" to form "whereas", but in other use cases it would be convinient to have that space.
Is this intended behaviour? In such case, maybe making it optional could help. 

For an example of what this means, Google implemented it into its keyboard.

**Comment by X-yl** [comment]
Okay I definitely added that so this is definitely an unintended thing. 
https://user-images.githubusercontent.com/28653555/113853729-0e4e1000-97af-11eb-99af-19ebcaa8768a.mp4
What app does it not work in?

**Comment by another-sapiens** [comment]
I can't figure out how to share a video from my phone, but it doesn't work like yours. It's the same in any app, no spaces.

**Comment by X-yl** [comment]
Does it also not give you a space if you click on a suggestion (when you're typing normally)? That should also insert a space if you start typing,

**Comment by another-sapiens** [comment]
Just confirmed: when suggestions are enabled, a space is inserted. When it's not enabled, there it's no space.

**Comment by Glitchy-Tozier** [comment]
Yeah, without suggestions (if I use the copy&paste-bar) no space is inserted when i start typing after a swipe-created word.
(v.0.3.10)
