### ISSUE TITLE
Optional threshold until glided word turns normal

### ISSUE THREAD

**Issue by another-sapiens** [florisboard/florisboard#582]
So, when you use the gesture typing and want to erase a written word, it gets fully deleted with a single tap. This is usually the best, but it could be even better to have a small threshold of say, 300ms until it's treated like a normal typed out word. 

It could be very useful in cases where you got a glided word wrong, but it was _mostly_ right. For example, if you try to glide "bomber" and it types "bombed", you would be able to just erase the last letter and it would be easier than gliding or typing the whole word again. 

In any case, if you consider this worthy of the keyboard, I think it should be optional as some people might prefer it the other way around. 
Also Google has some neat ideas as far as features go, and this was one of those. Their keyboard has it, if you need to see an example of this.

Edit: Something similar already seems to be implemented. Suggestions need to be enabled, then when you manually type a letter after gliding a word, the glided one is treated as normal.

**Comment by pierstitus** [comment]
I agree it's very confusing that sometime a whole word gets deleted when it is not expected.

I think the a timeout is a good idea. Also any cursor movement or typing should cancel the whole word deletion. Now when you glide a word ("bomb") and type some letters ("er") and you press backspace the whole word ("bomber") gets deleted, which I don't think anyone would expect.

**Comment by opusforlife2** [comment]
Another usage example: if you swipe type word1 and then word2, and then try to remove the space between them, the whole of word1 gets deleted. This makes it difficult to swipe type URLs.

**Comment by pierstitus** [comment]
@opusforlife2 In the last release ([v0.3.12](https://github.com/florisboard/florisboard/releases/tag/v0.3.12)) it is improved a lot, and moving the cursor or typing anything now cancels whole word deletion.

I feel even for the use case of @another-sapiens the time threshold is not necessary, as a time threshold is not an optimal solution either. Deciding to remove the whole word or only the last letter is just as quick. With the current implementation I see three easy solutions for the bomber->bombed case:
1. swiping the backspace to remove one character
2. moving the cursor to the end by swiping right on the spacebar and then backspace
3. typing a space and then two backspaces.

@another-sapiens do you still feel the need for a time threshold?

**Comment by opusforlife2** [comment]
> In the last release (v0.3.12) it is improved a lot, and moving the cursor or typing anything now cancels whole word deletion.

That's strange. v0.3.12 is the version I'm using, and I do see this issue.

> typing a space and then two backspaces.

Yeah, that's my habit on Google Keyboard. Type a space/letter and then backspace as needed.

**Comment by pierstitus** [comment]
@opusforlife2 do have the github apk or from another source?

**Comment by opusforlife2** [comment]
@pierstitus F-Droid.

**Comment by pierstitus** [comment]
I just tested F-Droid release v0.3.12, and that reacts just like the github apk. Glide word, space, backspace and just the space gets deleted. Maybe try the github apk, or remove and reinstall?

**Comment by opusforlife2** [comment]
@pierstitus Oh, I was referring to your other alternative action: "moving the cursor".

**Comment by pierstitus** [comment]
Ah, I see, I can confirm that is a bug. When moving the cursor by swiping the spacebar word deletion mode is canceled, but when moving the cursor by tapping the screen word deletion stays active.

**Comment by patrickgold** [comment]
It has almost been a year but a lot has changed in this area, and PR #1844 fixes a lot of these minor glide issues. One fix which is among them is, that selection update by tapping in the text box itself now cancels the word-deletion mode, same as inputting any other character or moving the cursor with space bar. As others have mentioned in this thread there's very little need for such threshold, and thus I see this issue as fixed.

The glide typing improvements will be released in 0.3.16-beta03, so this issue will auto-close when PR #1844 is merged in.
