### ISSUE TITLE
Typing "TM" on Florosboard

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#584]
Is there a popup somewhere that lets users add that small TM thing to the end of a word (similar to the "23" in `asdf²³`)?

I can't find it anywhere.

**Comment by kj7rrv** [comment]
At least on English QWERTY, it is on the second symbols page, right below ^ and °.On Apr 7, 2021 06:12, Glitchy-Tozier ***@***.***> wrote:
Is there a popup somewhere that lets users type that small TM-text? I can't find it anywhere.
