### ISSUE TITLE
Community repository for theme sharing / Matrix group chat

### ISSUE THREAD

**Issue by imDusht** [florisboard/florisboard#587]
What about creating a telegram group in which all users can share their custom-made themes.

**Comment by Glitchy-Tozier** [comment]
Just for privacy-reasons, i suggest using something else.

Telegram's groups (unfortunately) aren't E2E encrypted, and nobody knows what happens on their servers. In general, some of their practices are a bit suspect.


I _really_ like the idea of a theme-sharing group though, so I suggest using Element instead of Telegram.  :)

[Play Store](https://play.google.com/store/apps/details?id=im.vector.app), [F-Droid](https://f-droid.org/packages/im.vector.app)

**Comment by another-sapiens** [comment]
I second this.

**Comment by patrickgold** [comment]
Thanks for your suggestion! For theme sharing, I propose adding a community GitHub repository, as this is way easier and way more organizable than sharing the files in a group chat, regardless of the platform. Doing it this way also allows to build a simple web UI for browsing theme json files, which is even more appealing to manage community themes this way.

As for the Telegram group: I am personally not a fan of Telegram. I am favoring Element (using the Matrix servers) for such group chat. In fact I've already played around privately with such groups, though I never finished setting the FlorisBoard group up and making it public. May do it in the next few days if I find the time for it.

**Comment by Glitchy-Tozier** [comment]
Github sounds smart as well, keeping things organized by placing everything in the same ecosystem.  :)

**Comment by imDusht** [comment]
I don't have a love or hate relationship with telegram, believed it's one of the best for large groups.
community GitHub repository seems interesting and should be fine. Just wanted to have a place for theme sharing 😉 .
(I think i should add a little bit to the topic title)

**Comment by imDusht** [comment]
> I don't have a love or hate relationship with telegram, believed it's one of the best for large groups.
> community GitHub repository seems interesting and should be fine. Just wanted to have a place for theme sharing 😉 .
> (I think i should add a little bit to the topic title)

Bdbd

**Comment by patrickgold** [comment]
@imDusht Adjusted the issue topic so it matches up with the planned stuff.

**Comment by imDusht** [comment]
Perfect 👍

**Comment by patrickgold** [comment]
I've finally completed the set up for the Matrix (Element) group chat, if you want you can join here: https://matrix.to/#/#florisboard:matrix.org

The chat is intended for general discussion and chat around the project. Issues, feature requests etc. are still only managed on GitHub, but the group chat allows me and all joined users to chat with each other more directly.

I will let this issue open as the community repository is yet to be set up.

**Comment by patrickgold** [comment]
The official addons store will allow community themes and everything related to it, see https://github.com/florisboard/florisboard/issues/2468 for more info as it is the implementation effort thread now. Closing to avoid duplicate discussions around this.
