### ISSUE TITLE
ASCII emojis

### ISSUE THREAD

**Issue by Idesmi** [florisboard/florisboard#588]
I would like to add ASCII emojis that are marked as 'not yet implemented' in their tab in the emoticons section of the keyboard.
I would like to contribute, but I don't have experience with Java development. The question then would be, how would I add these text strings to the project?
[This list](https://github.com/dysfunc/ascii-emoji/blob/master/emojis) looks like a good compromise between conciseness and functionality.

**Comment by patrickgold** [comment]
Thanks for your question! ASCII emojis are very basically implemented, and there's already a separate tab in the emoji view with "not yet implemented" to add Kaomojis in v0.5.0. Note though that the emoji view will see a complete overhaul during v0.5.0 development, thus I don't think this change is necessary.

**Comment by Idesmi** [comment]
I was referring to ASCII emojis containing CJK symbols as in the link. 
Ok, then I'll wait for newer releases.
