### ISSUE TITLE
Animals & Nature - Emoji category bug

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#59]
When I arrive in the last row of emojis of the category "Animals & Nature" the list of emojis of this category goes back to the beginning. This bug only occurs in this category.

**Environment information**
- FlorisBoard Version: 0.2.6
- Install Source: GitHub
- Device: Redmi Note 4
- Android version, ROM: Miui 11 - Android 7.0

**Steps to reproduce**
1. Go to 'Animals & Nature' category on emoji tab
2. Scroll to the last row of emojis of this category
3. See error

**Comment by patrickgold** [comment]
Thanks for reporting this bug. I've tried to reproduce this, but was unable to do it on any device. I'll investigate this issue further. 

Question: Do you mean by "goes back to the beginning" that it jumps back to the beginning or that it just infinitely adds the same set of emojis?

**Comment by RickyM7** [comment]
@patrickgold It just jump back to the beginning. I'll try to make a screen record.

**Comment by patrickgold** [comment]
@RickyM7 Hmm that's very strange, also due to the fact that it only occurs in the 'Animals & Nature' category.

**Comment by RickyM7** [comment]
@patrickgold Sorry the delay, there is the video, maybe it helps a little.
![Emoji category bug](https://user-images.githubusercontent.com/24703825/100917081-6d281380-34b5-11eb-99d7-7a40e9b9799f.gif)

**Comment by patrickgold** [comment]
@RickyM7 Thanks for the screen recording, this definitely helps visualizing the bug more. I'll have to investigate why it exactly jumps back in the last row. Either is is a bug in the androidx library or in the last row there's a glitched emoji in the last row which causes the scrollview to reset.

**Comment by RickyM7** [comment]
@patrickgold This bug has been fixed on v0.3.0. Thank you.
