### ISSUE TITLE
Theming Gesture Typing

### ISSUE THREAD

**Issue by MathSteve22** [florisboard/florisboard#590]
I'm not sure if this might be something I am just not finding in the theming section of the app, but with the gesture typing, I think being able to change the coloring of the swiping would be a neat idea.
I apologize if this is duplicate, but I did not notice any proposal.

**Comment by Glitchy-Tozier** [comment]
Also, there should be an option to change the track-color in accordance to app-color.

(Just like adaptable themes function)

**Comment by patrickgold** [comment]
That's a problem with the way the theme editor works currently: you created a copy of a default theme before the gesture theme option was added, so your custom theme now does not contain the theme option. Best thing you can do is to temporarily copy of a default theme, copy the glide typing theme group name and attribute name and manually add them to your custom theme. This is of course a highly inconvenient thing and I will have to think about some mechanism to automatically do this for custom themes in the future.

**Comment by X-yl** [comment]
As patrick said, the glide trail attribute wasn't automatically added to custom themes. You can add it yourself by creating a group with the name "glideTrail", and adding the attribute "foreground" with whatever colour you'd like. If it's not added, it defaults to the primary colour with some transparency.
