### ISSUE TITLE
Adapt Gesture-Typing Touch-Trail to App colors

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#591]
Basically replicate what already exists within the fun "Adaptable Themes" feature.

**Comment by patrickgold** [comment]
Above PR adds the glide trail color to the adaptive theme and also fixes the caps-lock not getting a color (discovered accidentally while testing the glide trail color).

**Comment by Glitchy-Tozier** [comment]
Yay, nice!  :)
