### ISSUE TITLE
Copied message never enters clipboard-manager

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#597]
#### Short description
So far I haven't been able to make anything copied show up in the clipboard manager

![Screenshot_20210409-150917_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/114185244-cf9e8e00-9945-11eb-8e1c-ed90ef5e499c.jpg)

![Screenshot_20210409-150931_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/114185187-bac1fa80-9945-11eb-9748-9634a172b0c7.jpg)

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by X-yl** [comment]
Is the clipboard manager enabled? Settings -> Keyboard -> Clipboard.

**Comment by Glitchy-Tozier** [comment]
I didn't. But I still see a problem here:

If the clipboard manager is **disabled**, one of two things should occur:

1. Don't show the clipboard-manager popup anywhere
2. Add a "Clipboard-manager is disabled" note to the clipboard manager and put a button there, taking you to the settings where you can enable it.
(If you go for the second option, the clipboard manager maybe also shouldn't be the enter-key-popup closest to the primary popup.)

I think the first option is better. What do you think?

**Comment by X-yl** [comment]
I agree that the first option is probably better. However, at the moment, the popups are all statically defined from the .json files, and it's not super easy to show/hide them without making some changes to the main layout code (and I'm not _super_ comfortable with doing that). It would be 99% implemented with #362 (runtime layout customisation), so I suggest grouping this with that.

**Comment by Glitchy-Tozier** [comment]
Okay, then let's wait for Patrick to take action!

**Comment by patrickgold** [comment]
This issue will be fixed in 0.3.14-beta07, in this version the clipboard history will show that it is disabled with he ability to enable the history.
