### ISSUE TITLE
Can't scroll in the "Writing"-Tab of FlorisBoard

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#599]
Not sure how to reproduce it consistently, but it has happened twice within one day now. It's just stuck somewhere in the middle of the page and acts as if it was frozen.

![Screenshot_20210409-152107_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/114186902-ada60b00-9947-11eb-9ea0-ff7cba5e7493.jpg)

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! This bug is very strange, as I don't use any custom views for managing the scroll state. Will add it to the todo list.

**Comment by patrickgold** [comment]
This rather strange bug is something I don't really understand why it randomly happens to this day. As this screen does not exist in this configuration anymore though (and the UI is now implemented in Jetpack Compose), I see this issue as resolved in #1370 (beta06 once released). Thanks again for reporting!

**Comment by Glitchy-Tozier** [comment]
Yeah, it's weird. It never happened again after this incident.

Makes sense, let's close it when the new settings are implemented! 👍
