### ISSUE TITLE
Duplicate suggestions

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#602]
I know this is known already, but i wanted to create an issue for this, just to make things a little more orderly  :)

(Ignore the top half of the following screenshot)
![Screenshot_20210410-105136_GitHub.jpg](https://user-images.githubusercontent.com/59611881/114264620-41c9ae00-99ec-11eb-9f0b-ee2e1c7b4268.jpg)

Happens in v.0.3.10.

**Comment by patrickgold** [comment]
Totally forgot to link this issue, but this bug has been fixed in #858 with the setup of C++ interoperability (The suggestion list is the first thing I re-implemented and it blocks duplicate suggestions).
