### ISSUE TITLE
Suggestions replace previous word

### ISSUE THREAD

**Issue by Surendrajat** [florisboard/florisboard#604]
#### Short description
Sometimes when I click on a suggestion provided after glide typing, it replaces the previous word before space. It happens randomly, and I'm not sure what triggers it.

#### Steps to reproduce
1. Open some app, start typing (swipe)
2. Click on some suggested word
3. See it replace previous word

#### Environment information
- FlorisBoard Version: 0.3.10-beta06
- Install Source: F-Droid
- Device: Oppo K3
- Android version, ROM: ColorOS v7.1(10)

**Comment by pokegamer5547** [comment]
happened in my phone too.running on android10.

**Comment by X-yl** [comment]
Well this is how the word to replace is selected: https://github.com/florisboard/florisboard/blob/c0f90a7ea4cc59f671e174bd08226e3c7872d156/app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt#L243

@patrickgold any idea why this sometimes replaces the wrong word?

**Comment by Glitchy-Tozier** [comment]
Does this only happen when Gesture-typing?

My phone's dying, but could it use the same mechanism as #595?

**Comment by Surendrajat** [comment]
Wow. Thank you for fixing it so fast @patrickgold! Will wait for the debug release.
