### ISSUE TITLE
reduce keyboard height/size

### ISSUE THREAD

**Issue by angriness-sleek** [florisboard/florisboard#61]
bring back the sizes in 0.2.5
even "very small" is too big in 0.2.6

**Comment by HyknuF** [comment]
just wanted to admit, for me the size settings in 0.2.6 are almost perfect ;-) unless the action keys (enter, search etc) and toprow could be a bit smaller to give a more modern and sleek look. the screenshot shows "very large setting"

![Screenshot_20201202-214458](https://user-images.githubusercontent.com/53949193/100929974-b776b800-34e8-11eb-9a9c-5dcd431c3e69.png)

**Comment by angriness-sleek** [comment]
A possible solution could be size options like SimpleKeyboard has

**Comment by kojid0** [comment]
> even "very small" is too big in 0.2.6

Can you share a full-screen screenshot with "very small" and device information?

**Comment by patrickgold** [comment]
> bring back the sizes in 0.2.5
even "very small" is too big in 0.2.6

@angriness-sleek Could you please state which device you have and send a screenshot? Because I've tested the new keyboard height algorithm on various physical and emulated devices with different screen sizes/densities and "extra small" (that's the smallest height setting) is _very small_.

> A possible solution could be size options like SimpleKeyboard has

I see in SimpleKeyboard you can scale the height down to just 50% (!). Maybe I'll introduce height adjustment in percentage, but 50% of the height is incredibly small and the FlorisBoard UI isn't made to be that small... The minimum height I think is acceptable is 75%, nothing less. ("Extra small" is currently 85%)

**Comment by RickyM7** [comment]
It may be useful to download the [CPU Info](https://f-droid.org/packages/com.kgurgul.cpuinfo) and send a screenshot of your phone's screen information.
Like this:
![Screen Infos](https://user-images.githubusercontent.com/24703825/100944007-1f270600-34dd-11eb-9b7a-386ff85bff49.jpg)
Note: These are the screen information of my Redmi Note 4 (Miui 11 - Android 7.0) and in my opinion the size of the letters/keys is perfect on v0.2.6.

**Comment by HyknuF** [comment]
as already stated, for me size/height is perfect too. see screenshot of cpuinfo below. Device: OnePlus 6, Android 11.  (Sorry for german layout)

![Screenshot_20201203-033455](https://user-images.githubusercontent.com/53949193/100956554-f7ee2a00-3518-11eb-959b-3c3924d97db0.png)

if needed, i could post more examples.

**Comment by angriness-sleek** [comment]
> > even "very small" is too big in 0.2.6
> 
> Can you share a full-screen screenshot with "very small" and device information?

![Screenshot_20201203-143908](https://user-images.githubusercontent.com/62484249/100988540-c0e33d00-3547-11eb-87f6-d5febe5f3d94.png)

That size is perfect for me and i wouldn't want it any larger, which is why I'm sticking with 0.2.5 for now. i can send you a screenshot aith 0.2.6 if you wish

Xiaomi Mi A2
Android 10, unrooted and no custom ROMs

But yes, i have increased my smallest width:
![IMG_20201203_144503_739](https://user-images.githubusercontent.com/62484249/100988846-128bc780-3548-11eb-9441-e109788385a2.jpg)

**Comment by angriness-sleek** [comment]
> > A possible solution could be size options like SimpleKeyboard has
> 
> I see in SimpleKeyboard you can scale the height down to just 50% (!). Maybe I'll introduce height adjustment in percentage, but 50% of the height is incredibly small and the FlorisBoard UI isn't made to be that small... The minimum height I think is acceptable is 75%, nothing less. ("Extra small" is currently 85%)

Well I don't know man, I keep it at 50% and it's just the perfect height for me, anything bigger is too big, close to taking half the screen or so it feels to me...

**Comment by angriness-sleek** [comment]
> It may be useful to download the [CPU Info](https://f-droid.org/packages/com.kgurgul.cpuinfo) and send a screenshot of your phone's screen information.

![Screenshot_20201203-145316](https://user-images.githubusercontent.com/62484249/100989888-38659c00-3549-11eb-9264-74328690be71.png)

**Comment by patrickgold** [comment]
@angriness-sleek Thanks for sharing the screenshot and screen details. I think I will implement an "Other" option in the keyboard height preference, which then allows you to freely adjust the height. By doing this I don't affect the majority of the users which seem to like the new keyboard height algorithm better, but still allow for the previous smaller height by setting the percentage value.

**Comment by angriness-sleek** [comment]
Yay thanks a lot :)

**Comment by patrickgold** [comment]
@angriness-sleek Above commit adds a custom option (besides the predefined values extra-small, normal, etc.) to the keyboard height preference, which then allows you to set the height value to any percentage between 50 and 150. Note that the UI doesn't look particular good on 50% though, even after I've vastly improved it for extreme these values. I've also chased away several logical bugs in the key font size algorithm, which should make the font sizing better for xxhdpi screens.

I hope that with this solution I could address all sides. These changes will ship with the next regular release on Sunday (v0.3.0). Note that I will close this issue now. If anything regarding this topic arises again, feel free to reopen it!
