### ISSUE TITLE
Feature request: Making default smart bar accessible when suggestions are enabled.

### ISSUE THREAD

**Issue by gammerboy** [florisboard/florisboard#612]
It's seems at the moment that clipboard manager is not accessible when suggestions are enabled.
![Screenshot_20210411-123117_Settings_Suggestions](https://user-images.githubusercontent.com/22491935/114295586-d18e5b80-9ac3-11eb-8bdf-dfa218a71433.png)
For this post "default smartbar" will be the one with the curser navigation buttons(right and left) as shown in the image above and the clipboard manager button.

Suggestion 1:
To make the default smartbar available when no suggestion is being displayed.
![Screenshot_20210411-123042_Settings_Suggestions](https://user-images.githubusercontent.com/22491935/114295641-24681300-9ac4-11eb-8229-c5fcfb559a14.png)
ie. To have the blank space be occupied by the default smartbar.

Suggestion 2:
As for when next word suggestion will be implemented I don't think there will be much time where the suggestions are going to be empty and so to include another button on the right (like the arrow on the left which expands the smartbar kinda) to access the default smartbar and the button on the left to enter the "expanded smartbar"
As for conflict - will be having an issue having the button on the right when in private keyboard mode. As for solution maybe can try making the private indicator to be the a button in a way. ie. to have 2 themes for the button kinda one for the normal mode and one for the private mode( with private mode being purple nd having that shield or making the shield look like a arrow or a button of some sort where it's clear that it's not just a logo but a button so as to exclude confusion or to be mentioned that the logo is a button when in private mode).

**Comment by Kreuger** [comment]
If Im understanding correctly, tap that arrow above the keyboard to reveal the smartbar.

**Comment by gammerboy** [comment]
@Kreuger Let me put it in this way. the smart bar has two pages nd pressing the arrow toggles the page 2 of the smartbar nd reverses it while on page 2. 
When suggestions is enabled the page 1 of the smart bar is not displayed nd only the page 2 of the smartbar can be accessed.
The options available on page one like the navigation of the curser,copy, paste and the clipboard manager are not available on page 2 of the smartbar.

**Comment by Kreuger** [comment]
Ive never used those arrows so Im not sure. Sorry.

**Comment by Sociolect** [comment]
> Ive never used those arrows so Im not sure. Sorry.

Try accessing the clipboard with suggestions enabled. 

Or, as per your own suggestion, with suggestions enabled tap that arrow above the keyboard to reveal the smartbar. You'll see its a different smartbar than the one in OPs first image.

**Comment by Kreuger** [comment]
I do have the smart bar enabled and tapped that arrow.

**Comment by MisterY** [comment]
This has been requested before.

To create a screenshot, usually Power+Vol Down work without hiding the keyboard.

**Comment by gammerboy** [comment]
#387  does ask for a togglable smartbar.
but then for now atleast for now (i guess until next work suggestion is implimented) the smartbar space is left empty until you start typing when suggestions is enabled ( As shown in the second screenshot) and the we are unable to access the "page1" of the smartbar which has the button to access the clipboard manager. 

As for having a bar extend on top of the keyboard with the toggle idk if all apps will behave well with it on all devices. And for some reason I just think that having a static height keyboard will also help save battery with the gpu having to render less but I really don't know how devices render the frames.
And would like to have a toggle to be able to access both the pages of smartbar when having the suggestions enabled.

But I guess it's in the works to have a customizable smartbar but I guess we'll have to wait and see.
