### ISSUE TITLE
Position of accents for french (france) AZERTY 

### ISSUE THREAD

**Issue by Bapt17** [florisboard/florisboard#615]
The order of accents for French (France) AZERTY is incorrect, this makes typing more complicated

Actual behavior:
![IMG_20210411_192703](https://user-images.githubusercontent.com/80645093/114315619-0a4c2600-9b00-11eb-8869-0bf086e15df3.jpg)
![IMG_20210411_192635](https://user-images.githubusercontent.com/80645093/114315627-10420700-9b00-11eb-9302-58a982d63cd3.jpg)
![IMG_20210411_192616](https://user-images.githubusercontent.com/80645093/114315631-146e2480-9b00-11eb-8735-842ce16c4db9.jpg)
![IMG_20210411_192548](https://user-images.githubusercontent.com/80645093/114315637-19cb6f00-9b00-11eb-98e8-7dc3d2b1f902.jpg)
![IMG_20210411_192233](https://user-images.githubusercontent.com/80645093/114315641-1e902300-9b00-11eb-9f63-6939d3966968.jpg)
![IMG_20210411_192103](https://user-images.githubusercontent.com/80645093/114315647-22bc4080-9b00-11eb-9a64-e3c078a6e347.jpg)

Normal behavior (e.g. aosp keyboard):
![IMG_20210411_192723](https://user-images.githubusercontent.com/80645093/114315736-8a728b80-9b00-11eb-8c4c-8c8f6fbf9a0b.jpg)
![IMG_20210411_192520](https://user-images.githubusercontent.com/80645093/114315759-aa09b400-9b00-11eb-9579-e703aa94a7a2.jpg)
![IMG_20210411_192449](https://user-images.githubusercontent.com/80645093/114315778-b8f06680-9b00-11eb-903b-aef40a69368e.jpg)
![IMG_20210411_192418](https://user-images.githubusercontent.com/80645093/114315809-e0473380-9b00-11eb-9826-675f1be0df81.jpg)
![IMG_20210411_192356](https://user-images.githubusercontent.com/80645093/114315832-fc4ad500-9b00-11eb-8177-15a5d06282b3.jpg)
![IMG_20210411_192326](https://user-images.githubusercontent.com/80645093/114315834-0240b600-9b01-11eb-9e4a-a5b6e26faa68.jpg)

Other than that the keyboard is awesome

**Comment by patrickgold** [comment]
Thanks for your suggestion! Accent optimization has not yet been done for French, so I am very grateful for your detailed specifications on the order of the popups. Will add this to my todo list!

**Comment by patrickgold** [comment]
Above PR fixes the French popups for the most part. There's some issues with the ordering when the number is dynamically inserted but at least the primary accent is now 100% the one you provided your screenshots. Will be released in v0.3.11-beta01.
