### ISSUE TITLE
Ability to set private/incognito mode to always off

### ISSUE THREAD

**Issue by CalAlaera** [florisboard/florisboard#617]
A number of apps tell the keyboard to turn private mode on. For less privacy-friendly keyboards that makes sense, but as the data in FlorisBoard never leaves the user's device, the user could benefit from customised suggestions (when implemented) without compromising their privacy.

I therefore request the ability to turn private mode off and gather data from my typing for my own use, no matter what the app I'm using suggests, please.

PS: Thanks for all your hard work :)

**Comment by patrickgold** [comment]
That's the opposite of many requests haha, but I can surely add this one, should be quite easy to do so!

**Comment by pokegamer5547** [comment]
I agree,but maybe having the ability to turn on/off private mode from smartbar or having it in the additional options of enter button(like the clipboard and emoji buttons)  would be more convienent.

**Comment by jerryn70** [comment]
Sounds good idea .

**Comment by patrickgold** [comment]
Above linked PR reworks the incognito mode as parts of the Smartbar actions rework. With this incognito mode can now always be forced off by going to Settings > Advanced > Incognito mode and setting this to "Force off".

This will be released in 0.4.0-alpha03. Thanks again for suggesting!
