### ISSUE TITLE
Horizontal Ellipsis (Three-dots) character related bug

### ISSUE THREAD

**Issue by GithbUser** [florisboard/florisboard#62]
Horizontal Ellipsis (Three-dots) character is not showing in symbols
And it appears in popup on typing many keywords like a,n,!,? etc

**Environment information**
- FlorisBoard Version: 0.2.6
- Install Source: Aurora Droid (F-droid client)
- Device: Poco M2 Pro
- Android version, ROM: Android 10 , Resurrection Remix OS Special Edition

**Steps to reproduce**
1. Go to search bar
2. Click any words like a,n,?,!,m
3. And you will see Horizontal Ellipsis (Three-dots) character in popup
4. Also i am unable to type the Horizontal Ellipsis (Three-dots) character

Screenshot1: https://cloud.operationtulip.com/s/ebRykrgXLWNnJ7L
Screenshot2: https://cloud.operationtulip.com/s/cyPdLAjELg7ZAQc

**Comment by RickyM7** [comment]
I think this is expected, three-dots appears in this case to represent that the clicked character has other characters at its disposal if you press and hold it. To really see the tree-dots you have to click and hold on on dot while the symbols tab is open.

**Comment by GithbUser** [comment]
> I think this is expected, three-dots appears in this case to represent that the clicked character has other characters at its disposal if you press and hold it. To really see the three-dots you have to press and hold on the dot while the symbols tab is open.
> ![three-dots](https://user-images.githubusercontent.com/24703825/100999434-8bd0ed80-353b-11eb-8bec-ed1b427f4540.jpg)

 I wasn't aware of this
Thanks for sharing information
