### ISSUE TITLE
Memory consumption on Florisboard

### ISSUE THREAD

**Issue by TheThunderspy** [florisboard/florisboard#621]
I need to know if there is any issue regardings to memory consumption, I enabled glide gestures, full screen horizontal input (set to always show, because I use SystemUI Tuner inmersive mode), clipboard, enabled smart bar with suggestions, theme changed to black borderless, etc.

The thing is, that for some reason, the keyboard wants to consume more than 100mb, that is a lot for a keyboard.

At this point, I'm asking if this is my fault, if I disabled any app that may contain some library that florisboard is reliant to.

Here is the Image:

![Screenshot_20210411-175509 1](https://user-images.githubusercontent.com/78750328/114356660-819cac80-9b36-11eb-93ee-fdce12364ff3.png)

I'm panicked because the phone can barely work with 1gb of RAM (is a cheap one), and the keyboard is my favorite, I can't ditch florisboard. I really love the effort that you guys put into developing this app...!

Could it be my fault..? Maybe because I disabled many system apps using "adb shell pm uninstall (-k for security in case that you want to renable the app) --user 0 com.package.name"
I think is my fault 'cause I disabled Launcher3...

**Comment by lawson85** [comment]
Perhaps to test further, if you then some features off and then check RAM usage it will better determination what is causing it. To test you'll need to turn things off 1 by one and keep checking. 

Maybe turn off things like sound and vibrate

Sometimes a simple reboot helps though.

**Comment by another-sapiens** [comment]
![Screenshot_2021-04-12-04-47-04](https://user-images.githubusercontent.com/80379945/114359980-e7932f00-9b4a-11eb-9bd1-81342280b0a3.png)

Same here, but it's only noticeable after a while of using it. I'd say it's related to the suggestions, as pressing the delete button on a word makes it lag the most (presumably because it has to figure out the suggestions, and with our limited 1GB of RAM it may be struggling a bit). 

In any case, it starts out working smoothly, and it's only after some use that it seems to consume this much memory.

**Comment by patrickgold** [comment]
Thanks for your bug report! Yes, in terms of memory management FlorisBoard has its issues currently, especially if an instance is running for a longer period of times. Partly the suggestions are to blame (which will get replaced in the next few weeks) and partly its just several issues with some memory leaks, and so on. I am constantly on the hunt for such issues and things will improve over time.

> The thing is, that for some reason, the keyboard wants to consume more than 100mb, that is a lot for a keyboard.

Try turning off suggestions and then force stop FlorisBoard so the service must re-instantiate again. This should definitely help with the memory usage.

**Comment by patrickgold** [comment]
Note that I am now bundling all discussion and issues around OOM crashes and memory usage in #677, as the number of duplicate issues regarding this topic is getting waaaay out of hand and it is impossible for me to manage this if not bundled.
