### ISSUE TITLE
Add multilanguage typing for same layout (As for SwiftKey and Gboard) 

### ISSUE THREAD

**Issue by ali-oem** [florisboard/florisboard#624]
![Screenshot_20210412-151419_GitHub.jpg](https://user-images.githubusercontent.com/71282548/114408998-e5a88a80-9ba1-11eb-9f4f-93fbd7466593.jpg)
It's helpful to use one layout and corrector for two similar languages

**Comment by pierstitus** [comment]
duplicate of #155

**Comment by patrickgold** [comment]
Thanks for your suggestion! As already pointed out, this is a duplicate of #155, so closing this one.
