### ISSUE TITLE
View clipboard history

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#636]
Hey guys. I recently recommended the app on reddit and someone asked how to view the clipboard history. Is this possible? Currently it seems that only whatever is currently copied is visible.

**Comment by sav1tarr** [comment]
another way I know of is going in gestures, selecting hold space bar as showing clipboard history

**Comment by hakkikaancaliskan** [comment]
Or you can see clipboard history button while some text selected
definitely there a way to reach directly

![Screenshot_20210412-234100_Firefox_Beta](https://user-images.githubusercontent.com/17825767/114459262-f5978d00-9be8-11eb-8f46-191c44f30234.png)

**Comment by Kreuger** [comment]
Thank you!

**Comment by patrickgold** [comment]
Important to note is that the clipboard manager only works if it is enabled in the Settings (Keyboard > Clipboard group).

A more direct way to access it is by long-pressing enter and then selecting the clipboard manager icon or by setting a swipe pref to the clipboard manager show action.

**Comment by hakkikaancaliskan** [comment]
> A more direct way to access it is by long-pressing enter and then selecting the clipboard manager icon or by setting a swipe pref to the clipboard manager show action. 

This should be written somewhere in the app, really useful :)

**Comment by rancidfrog** [comment]
History always appears when available for me,
![](https://i.imgur.com/JVLGYiB.jpg)  
Which is perfect.

But and enter/send button would be great to have in history, as selecting from clipboard history pastes and you need to click back button then hit enter.
![](https://i.imgur.com/eOHFHyz.jpg)
Having a button on the left side would be great as users might hit clear all if it is the right by mistake, some screens are iffy in touch points.

**Comment by patrickgold** [comment]
> But having an enter/send button would be great to have in history, as selecting from clipboard history pastes and you need to click back button then hit enter.

Hmm that's a neat idea.

>  Having a button on the left side would be great as users might hit clear all if it is the right by mistake, some screens are iffy in touch points.

I would prefer the right side so it is consistent with the main layout, but as a green mini-fab (like the button in the theme editor but smaller).

**Comment by KaKi87** [comment]
Hello, how to use clipboard history ? It's always empty for me. Thanks

**Comment by patrickgold** [comment]
You need to enable the clipboard history in Settings > Keyboard > Clipboard > Enable history (or Settings > CLipboard > Enable history on the latest beta)

**Comment by KaKi87** [comment]
It works, thanks ! So I would suggest hiding the history button when the feature is not enabled, or even better, adding a button to enaable the feature when using the history button. Thanks

**Comment by patrickgold** [comment]
The clipboard history now properly indicates in the UI that it is disabled or empty, so any confusion around this topic should be resolved. Will be included in tomorrows beta07 release. Thanks again for your input!
