### ISSUE TITLE
Nintype-like glide input

### ISSUE THREAD

**Issue by ambroisie** [florisboard/florisboard#638]
Hello, thank you for working on this great keyboard.

I'd like to suggest a feature request : having a slide input method in a similar manner to what Nintype allows you to do. To expand on this, one of the peculiarities of Nintype are from the way it manages to use two fingers at the same time when using sliding inputs. It also has a few great shortcuts, such as sliding to the left from enter to delete a word, sliding from comma to the right and up to input a question mark, etc... 

I would encourage you to try out the tutorial for Nintype (called Keyboard 69 on Android...) as it is difficult to explain without having experienced it for yourself.

I could try recording myself going through the tutorial to showcase the sliding behavior, I should be able to find some time later in the week for this.

Edit: I would like to stress to anyone trying it out that the aforementioned tutorial wants you to be very precise both in timing and precision, however it is not nearly as much of an issue during day to day use. It still makes for a good intro, and a great way to learn the ropes initially.

**Comment by jeremiah-miller** [comment]
I think this is duplicated by #116

**Comment by ambroisie** [comment]
That is correct, I'll close the issue then. Sorry about the duplicate.
