### ISSUE TITLE
Remove number row area when typing in number input field

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#65]
**Environment information**
- FlorisBoard Version: 0.2.6
- Install Source: GitHub
- Device: OnePlus 8T
- Android version, ROM: 10, OxygenOS

**Steps to reproduce**
1. Disable suggestions and show number row
2. Open keyboard in number input field
3. There is a black area at the top where otherwise the number row would be

This would probably fit in with the rewrite you mentioned to allow having suggestions with the number row

<details><summary>Screenshot</summary>
<p>

![emptyspace](https://user-images.githubusercontent.com/24937357/101085940-70ec9080-35b0-11eb-96bc-0d3639fcd6bd.png)

</p>
</details>

**Comment by patrickgold** [comment]
It may look like a bug to you but this is intended, because displaying a number row above the numeric input field makes no sense at all. To avoid content jumping because the height of FlorisBoard would change when hiding the Smartbar, I just leave it blank. This behavior is also implemented for the phone layout.

**Comment by D3SOX** [comment]
Okay, thanks for the clarification. I still think it looks a bit weird. Maybe it would look better when there were suggestions or the cursor tools instead.
It's generally not a big deal so I will close this for now.

**Comment by patrickgold** [comment]
I've just merged the Smartbar rework branch into master, which contains an improved Smartbar logic. When FlorisBoard is in a numeric or phone input field, the Smartbar will automatically be hidden. Will release with the next release v0.3.1. Thanks again for your suggestion!
