### ISSUE TITLE
Vibration strength on keypress

### ISSUE THREAD

**Issue by BrudiBanani** [florisboard/florisboard#652]
#### Short description
In settings i can choose the vibration strength on keypress. First of all i can not choose 1%, all other percentages are easy to setup. 1% just seems to be 'missing'. And no matter what strength i choose it feels like there is no difference at all.

#### Steps to reproduce
1. Go to Settings -> Keyboard -> Vibration strength on key press
2. Try choosing 1%
3. Additionally test out different settings (like 100% and 2%)

#### Environment information
- FlorisBoard Version: 0.3.11-beta01
- Install Source: github
- Device: Xiaomi Mi 9 SE
- Android version, ROM: 11

**Comment by patrickgold** [comment]
Thanks for your bug report!

> First of all i can not choose 1%

Weird. Works like a charm on my testing setup. Does this bug also occur with other preferences which have this slider popup? If so, the preference item logic has a bug.

> And no matter what strength i choose it feels like there is no difference at all.

This seems like haptic feedback is available on your system. Currently, FlorisBoard first tries to perform a haptic feedback option, if this fails then uses the Vibrator API. Probably have to add a toggle for this to prevent this issue from occurring.

**Comment by BrudiBanani** [comment]
Alright, recorded my screen to share the slider problem.
Here it becomes weird. As you can see while recording it clearly jumps from 97% to 100% percent. On the other hand 1% is working. Sometimes 1% is not working, but i can choose anything from 97,98 or 99 or the other way around. 
If you want i can aswell record the 1% missing....

https://user-images.githubusercontent.com/78300550/114602902-68f7d800-9c97-11eb-9fc5-132cfee62282.mp4
