### ISSUE TITLE
Clipboard section in settings not translated in Bulgarian

### ISSUE THREAD

**Issue by StoyanDimitrov** [florisboard/florisboard#654]
#### Short description
Clipboard section in settings not translated in Bulgarian

#### Steps to reproduce
0. Change the system language to Bulgarian;
1. Go to Keyboard page in settings;
3. Scroll down to Clipboard section;
4. See only this section not translated.

<details>
  <summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/10962709/114605942-28459200-9c8a-11eb-9149-ccc2774adea7.png" width="50%"/>
</details>

It was never translated.

#### Environment information
- FlorisBoard Version: v0.3.10 as well as v0.3.11-beta01
- Install Source: F-Droid for the stable, GitHub for the beta
- Device: LG G5 (h850)
- Android version, ROM: 11, Lineage OS

**Comment by X-yl** [comment]
Ah shit, I forgot to extract all the clipboard preference strings to to the strings.xml so they can be translated. Thanks for the report!
