### ISSUE TITLE
Why only the beta release is on fdroid?

### ISSUE THREAD

**Issue by bluecheeser** [florisboard/florisboard#656]
![Screenshot_2021-04-14-01-58-12-632_nya.kitsunyan.foxydroid.jpg](https://user-images.githubusercontent.com/81776134/114617148-5dbba100-9cc5-11eb-93be-f9c1e3485087.jpg)

**Comment by patrickgold** [comment]
The stable version is also on F-Droid, but the difference is that F-Droid builds and signs the stable builds themselves on their own build servers, thus the certificates with my own builds on GitHub don't match up. Beta builds of GitHub and on IzzyOnDroid are both signed and built by me and thus can be installed interchangeably. Hope that could answer your question!

**Comment by Glitchy-Tozier** [comment]
If everything is clear this issue can probably be closed.

**Comment by patrickgold** [comment]
Yes, I think so too.
