### ISSUE TITLE
Keyboard keeps flashing

### ISSUE THREAD

**Issue by TheLastProject** [florisboard/florisboard#665]
#### Short description
Keyboard kept changing brightness, like "pulsating". It was very confusing. Looking through GitHub issues, it looks like it may be a "loading keyboard" feature, so maybe a race condition happened? https://github.com/florisboard/florisboard/issues/207. The keyboard was working fine though, so it clearly wasn't still loading.

#### Steps to reproduce
I honestly don't know, it just started happening. It stopped the moment I switched to another keyboard and back.

#### Environment information
- FlorisBoard Version: v0.3.10
- Install Source: F-Droid
- Device: Fairphone 3
- Android version, ROM: Android 9, /e/OS 0.15

https://user-images.githubusercontent.com/1885159/114699336-7311e900-9d20-11eb-819d-2ad83fc7fec1.mp4

**Comment by kurdikeyboard** [comment]
You right I have that problem sometimes when turn on or off my device dark mode that's happening also when using Adapt colors in theme!

**Comment by Glitchy-Tozier** [comment]
Hi, thank you for your bug report!
(And for filling out the tempate so well)

This is a known bug (duplicate of #589), so i suggest we close this report to keep to one issue per bug.  :)

**Comment by Glitchy-Tozier** [comment]
And yeah, it's probably related to #207. Let's see what Patrick can do about it!

**Comment by TheLastProject** [comment]
Oops, my bad. I did search GitHub issues but that issue didn't pop up. Thanks for telling me it's a duplicate! I'll close this then.
