### ISSUE TITLE
Customize keys/rows spacing

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#67]
Having an option to customize (slightly to avoid errors) the spacing of both the keys and rows may be something interesting.
This option can be implemented in two ways (I think), literally pushing away the keys and rows a bit or reducing the size of the top and bottom edges of the keys.

**Comment by patrickgold** [comment]
Thanks for your suggestion! This generally seems like a viable option to implement. I'll add it to my todo list!
