### ISSUE TITLE
Backup All Settings and Add Import Function

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#672]
Hey man. I downloaded the beta to use and I realized that none of my settings carried over from the stable release. Would it be possible to add the functionality to backup all settings and import them? Also it would be easier if there was an import button for themes.

**Comment by patrickgold** [comment]
Thanks for your suggestion! Settings backup is indeed not possible currently, but is already on my todo list (see #272). I have re-assigned it from v0.5.0 to v0.4.0, as this functionality seems more important to me.

> Also it would be easier if there was an import button for themes.

Click the `+` in the theme manager and you will see the import button :)

**Comment by Kreuger** [comment]
@patrickgold I actually knew about that. Ive used it. I dont know how I missed the button.
