### ISSUE TITLE
Randomly freeze, crash and stop opening apps.

### ISSUE THREAD

**Issue by NeutralBit** [florisboard/florisboard#675]
I have encountered few issues. 

-  Many time when click on input field, keyboard doesn't show, even sometimes freeze the apps that I'm writing in.

-  When try to open Edit theme. it crashes with OutOfMemory exception. 

-  Last but most sadly issue,  typing is too much slow and lags a lot. I'm using android 10 with 6GB RAM and and powerful enough chip. But the experience is like I'm using an older android with 256mb ram.  

Note: When i found this app, I got soo much excited. Really appreciate the work. We needed an open-source secure keyboard that could compete keyboards like gboard in user experience (privacy doesn't have to be ugly right?).  I think this is the one. Please keep up the good work.

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677.
Patrick (the creator of Florisboard) knows about the issue and probably already is working on it, so I suggest we close this issue.

And i agree! Patrick is doing an amazing job with Florisboard. It's nice to have an open-source keyboard that's not horrible in some way.  :)

**Comment by NeutralBit** [comment]
Thank you for your reply. I'm closing this.
