### ISSUE TITLE
Feature request for ENTER and SPACE button.

### ISSUE THREAD

**Issue by NeutralBit** [florisboard/florisboard#676]
- Currently ENTER and SPACE button heights are too much big. It doesn't look comfortable with the other part of keyboard.
It would be nice to have option to change its width and height. 

thank you.

**Comment by patrickgold** [comment]
How can the ENTER and SPACE button heights be to big? I can clearly see the point for the width, but the height doesn't really make sense to me. In general you can set the keyboard height, this changes the height of all keys.

**Comment by NeutralBit** [comment]
Yes, ENTER and SPACE button size matches with other keys when borders are visible. But the problem starts with Border-less theme.
Let's see examples with screenshot.
Floris: <img src="https://user-images.githubusercontent.com/63266908/115287225-d3b28300-a171-11eb-9b87-85b1357ece83.jpg" width="160"> Gboard: <img src="https://user-images.githubusercontent.com/63266908/115287177-c7c6c100-a171-11eb-811b-5fa7d0316978.jpg " width="160"> 
[Note: ENTER and SPACE buttons are weirdly bigger compared to other keys. Now compare it with gboardb (right pic), see even though floris keys are smaller than gboard, still ENTER and SPACE buttons are much bigger than gboard.]

Let's customize, this is after after changing the keyboard height to "Extra-Short".
<img src="https://user-images.githubusercontent.com/63266908/115287906-9f8b9200-a172-11eb-9bf9-6df7b3259429.jpg" width="160">
[Note: This is the lowest height, keys are now extremely small that it's not even possible to write properly. So, this height is not usable, it's just to show an example that even with this extremely low height, ENTER and SPACE buttons are still noticeably bigger.]

Let's hack around some,
Key spacing (vertical)" to highest value. Key spacing (horizontal) to 8 half dp. Modify height and font size a bit.
Floris: <img src="https://user-images.githubusercontent.com/63266908/115290042-fd20de00-a174-11eb-8098-9d389de58637.jpg" width="160"> Gboard: <img src="https://user-images.githubusercontent.com/63266908/115287177-c7c6c100-a171-11eb-811b-5fa7d0316978.jpg" width="160"> 
[Note: Somewhat okay. But this is not a normal procedure. Also changing key space leads to other problems. eg: changing horizontal space also changes key popup width to smaller, which doesn't look suitable. ]

Even with all these changes still I couldn't find my desired size.

**Comment by NeutralBit** [comment]
@patrickgold  Yes, ENTER and SPACE button size matches with other keys when borders are visible. But the problem starts with Border-less theme.
Let's see examples with screenshot.
<img src="https://user-images.githubusercontent.com/63266908/115312524-4a13ad00-a193-11eb-948d-ff3d9e61632e.jpg" width="160"/> <img src="https://user-images.githubusercontent.com/63266908/115312605-6d3e5c80-a193-11eb-90cf-4a413b90dc27.jpg" width="160"/>
Note: ENTER and SPACE buttons are weirdly bigger compared to other keys. Now compare it with gboardb (second pic), see even though floris keys are smaller than gboard, still ENTER and SPACE buttons are much bigger than gboard.

Let's customize. This is after after changing the keyboard height to "Extra-Short".
<img src="https://user-images.githubusercontent.com/63266908/115312764-c3130480-a193-11eb-896e-d93ffb6a0a3a.jpg" width="160"/>
Note: This is the lowest height, keys are now extremely small that it's not even possible to write properly. So, this height is not usable, it's just to show an example that even with this extremely low height, ENTER and SPACE buttons are still noticeably bigger.

Let's hack around some,
Key spacing (vertical)" to highest value. Key spacing (horizontal) to 8 half dp. Modify height and font size a bit.
<img src="https://user-images.githubusercontent.com/63266908/115312961-3288f400-a194-11eb-88e8-57c07cf84517.jpg" width="160"/> <img src="https://user-images.githubusercontent.com/63266908/115312605-6d3e5c80-a193-11eb-90cf-4a413b90dc27.jpg" width="160"/>
Note: Somewhat okay. But changing key space leads to other problems. eg: keys area become smaller which causes problem to write quickly, changing horizontal space also changes key popup width to smaller which doesn't look suitable.

Even with all these changes still I couldn't find my desired size, also this is not a normal procedure for average users.

**Comment by patrickgold** [comment]
Thanks for providing the extra info! For the borderless theme it indeed makes sense to set the visual height of the key, I agree. Must this be configurable separately for you or is it enough if it does reduce the visual height automatically if a borderless theme is active?

**Comment by NeutralBit** [comment]
@patrickgold If automatically reducing height is easy for you to maintain, then that's okay. 
But for width, changing automatically is not gonna work right? Different phone has different curved edge, ENTER button width needs to reduce manually in order to avoid overlap with curved edge. 
So, if you will add option to change width, it's reasonable to add height option too with it. But reducing height automatically also works I think. 
Thank you.

**Comment by patrickgold** [comment]
I've included your request for auto-adjusting the enter/space height in the above PR, will be released in v0.3.11-beta02!

**Comment by NeutralBit** [comment]
Thank you..
