### ISSUE TITLE
Two key popups in Persian keyboard triggering digits/symbols keyboard and delete key

### ISSUE THREAD

**Issue by HeiWiper** [florisboard/florisboard#68]
The key `ظ` in Persian keyboard which is located on the bottom left corner has a 'U' as symbol hint and when held the popup shows the same letter `ظ` and after releasing the keyboard switches to digits/symbols layout.
The key `چ` in Persian keyboard which is next to the Delete key has an unknown character as symbol hint and when held the popup shows the unknown character and after releasing a letter is deleted from the input text as if the delete key was pressed.

Here's an example:
![Screen-recording](https://user-images.githubusercontent.com/12894695/101104619-d0a46500-35cb-11eb-8df7-2f1f59330af1.gif)

**Environment information**
- FlorisBoard Version: 0.2.6
- Install Source: F-Droid
- Device: Moto G6
- Android version, ROM: 10, Custom

**Steps to reproduce**
1. Enable Persian keyboard, trigger the keyboard and switch to Persian.
2. To reproduce the first bug, hold click on the letter `ظ` located on the bottom left corner.
3. To reproduce the second bug, write anything then hold click on the letter `چ` located next to the Delete key.

**Comment by patrickgold** [comment]
Above commit resolves both reported bugs. The "view symbols2" and "delete" character are now not taken from the symbol layout anymore.

Thanks for reporting this bug!
