### ISSUE TITLE
The App randomly crashes

### ISSUE THREAD

**Issue by soulgermocks** [florisboard/florisboard#680]
#### Short description
Describe the bug in a short but concise way.

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android version, ROM:

**Comment by Glitchy-Tozier** [comment]
1. Thank you for your bug-report!
2. It is way easier to fix bugs if the bug-template is completed, so, if possible, please share more information. (Like app version and so on. The things asked in the template.)
3. This issue has been reported a couple of times and is summarized in #677.
Patrick (the creator of Florisboard) knows about the issue and probably already is working on it, so I suggest we close this issue.
