### ISSUE TITLE
Add top row like anysoftkeyboard's terminal row

### ISSUE THREAD

**Issue by laraib07** [florisboard/florisboard#684]
![image2](https://user-images.githubusercontent.com/25507825/114856506-d2492980-9e04-11eb-8603-46189ead1c57.png)

Add an option to enable top row like the image so it can be used in termux and stuffs. This can be slided left or right to default copy/paste row.

**Comment by patrickgold** [comment]
If you disable the suggestions you kind of have such a bar (called the clipboard cursor bar). A separate button to show such bar besides the suggestions is planned, as well as customization of this bar (so you can have your own custom order and types of buttons). I will close your issue as it is kind of a duplicate, but still thanks for the suggestion!
