### ISSUE TITLE
Keyboard triggers the right-most key when the language of the phone is RTL and UI is mirror flipped

### ISSUE THREAD

**Issue by HeiWiper** [florisboard/florisboard#69]
I have tried this on a phone which Arabic language is set to default, the whole UI of the keyboard would switch to RTL including letter keys, and when clicking on any key except the ones on the Smartbar the keyboard would trigger the right-most key.
Other keyboards usually keep the same UI for the keyboard layout while only changing the bar above the keyboard.

Here's a screen recording from FlorisBoard on RTL phone language: 
![Screen-recording-1](https://user-images.githubusercontent.com/12894695/101106083-9937b780-35cf-11eb-8042-1d77ba6d5683.gif)

Here's a screen recording from AOSP keyboard on RTL phone language:
![Screen-recording-2](https://user-images.githubusercontent.com/12894695/101106285-04818980-35d0-11eb-8274-58b31aa7fc05.gif)

**Environment information**
- FlorisBoard Version: 0.2.6
- Install Source: F-Droid
- Device: Moto G6
- Android version, ROM: 10, Custom

**Steps to reproduce**
1. Go to the phone settings and add Arabic language to your device then move it to the top so that the UI changes to RTL.
2. Trigger FlorisBoard, notice how the UI is completely reversed including letters.
3. Try to press any key and notice how the right-most key is being pressed instead.

**Comment by patrickgold** [comment]
Above commit always lets the KeyboardView always display from left-to-right, regardless of the language set system-wide. The Smartbar however turns around, like it should. Note that this also fixed the trigger only right-most key issue, as the touch logic doesn't understand rtl.

Thanks for reporting!
