### ISSUE TITLE
Partial strings offered for translations

### ISSUE THREAD

**Issue by StoyanDimitrov** [florisboard/florisboard#692]
It is a bad idea to use partial strings instead of the whole string for translation. I'm referring to [pref__unit_minutes](/florisboard/florisboard/blob/0eb35c5edc0e0a608856b2d753769712ec51d13e/app/src/main/res/xml/prefs_keyboard.xml#L309) and [pref__unit_items](https://github.com/florisboard/florisboard/blob/0eb35c5edc0e0a608856b2d753769712ec51d13e/app/src/main/res/xml/prefs_keyboard.xml#L328) There are several reasons which I'm not going into details here but will list briefly:
 1. not all languages are created equal and what seems to be a prefix in one may be a suffix in other;
 2. keeping leading/trailing white-space intact is unreliable and leads to frustrations;

As a rule of a thumb **provide translator with whole strings along with the context information** (and of course don't reuse but that's out of scope for now).

So the best possible way to fix those is to use some placeholder:
 * `$num minutes` for pref__unit_minutes
 * `$num items` for pref__unit_items

Or whatever is available in your environment.

Translators in general are used to the idea of the placeholders and get along quite nicely.

**Comment by X-yl** [comment]
Thanks, this is a good point. I can see how this could cause issues. I will switch all the units to be placeholders. Could you clarify what you mean by "don't reuse", though? I was going to make only one placeholder for units like milliseconds that are used a couple times for different settings. Would this cause an issue?

**Comment by Luensche** [comment]
I guess @StoyanDimitrov means strings like "Text will disappear after $d seconds" instead of "Text will disappear after" and "$d seconds".

**Comment by Luensche** [comment]
@StoyanDimitrov can you just shortly explain what did you mean?

**Comment by patrickgold** [comment]
As I am currently reworking the preferences, I am also addressing this issue. The new preferences will define the units this way:

```xml
    <!-- Unit strings (symbols) -->
    <string name="unit__hours__symbol" translatable="false">{v} h</string>
    <string name="unit__minutes__symbol" translatable="false">{v} m</string>
    <string name="unit__seconds__symbol" translatable="false">{v} s</string>
    <string name="unit__milliseconds__symbol" translatable="false">{v} ms</string>
    <string name="unit__percent__symbol" translatable="false">{v}%</string>
    <string name="unit__display_pixel__symbol" translatable="false">{v} dp</string>

    <!-- Unit strings (written words) -->
    <plurals name="unit__hours__written">
        <item quantity="one">{v} hour</item>
        <item quantity="other">{v} hours</item>
    </plurals>
    <plurals name="unit__minutes__written">
        <item quantity="one">{v} minute</item>
        <item quantity="other">{v} minutes</item>
    </plurals>
    <plurals name="unit__seconds__written">
        <item quantity="one">{v} second</item>
        <item quantity="other">{v} seconds</item>
    </plurals>
```

The unit symbols are not translatable, as these are using the international standard for the unit they are abbreviating. The written units are translatable and define plural forms. It is also easy to add custom written units without a hassle. Please let me know what you think of the unit strings and if this issue is resolved when the above snippet is merged!

**Comment by StoyanDimitrov** [comment]
I don't see an issue with strings defined like this. Quite frankly, I don't even see an issue in reusing them since I can't imagine a scenario where there will be ambiguity coming from the context.

To @X-yl about string reuse. **Reusing strings makes translators work harder not easier.**
- the conscientious translators check the resulting translation in the UI of the application (as you can imagine it is not always as easy as it seems, but that's another story). Having one string spread on different parts of the application is distracting and hampers the translation process;
- there are things called translation memory (TM) that help translators in case of equal strings. What we gain here is the freedom to shorten or otherwise modify the translation to convey the meaning better for the given context;
- different languages have different ways of expression of seemingly equal concepts. Than one greatly depends of the string context;
- as extension to previous point seemingly different source strings may appear the same in translation based solely of different contexts;
- different languages have or don't have different structures like genders, cardinals etc that vary differently between contexts;
- probably way more points since it's the middle of the night here and I'm almost falling asleep.

If I may summarize my whole rant in two points:
1. Make every possible effort to give the translators the whole string as it will appear in the UI. That one is crucial for **fluent** translations.
2. Do not reuse strings. Don't spare translators feed them strings. Not all of them will jump from joy, but the one that need to tweak that particular string will be extremely happy to have the freedom to do without the fear of breaking the UI on other place.

**Comment by another-sapiens** [comment]
@StoyanDimitrov +1 on context. It's the hardest part to guess in any app, and pretty much the most important. Especially in Spanish, with all the conjugations and whatnot. 
That's why it's always harder to translate a few in-app strings correctly, than the whole readme file.
