### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by patrickgold** [florisboard/florisboard#7]
Note to myself that I will translate FlorisBoard into German (both in-app resources and PlayStore listing).

**Comment by mondlicht-und-sterne** [comment]
llet us easy translate your projects on bubu his #weblate [weblate.bubu1.eu](https://weblate.bubu1.eu/) because there its free.

**Comment by patrickgold** [comment]
Thanks for your suggestion, I will look into it when I have free time.

**Comment by patrickgold** [comment]
Localization is now managed on Crowdin.
