### ISSUE TITLE
Allow undo for pasting

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#70]
Having an undo button when pasting would be great, for when pasting in wrong position.
Hacker's keyboard allows this through ctrl+z.
Having an undo icon in toolbar would be enough.

**Comment by patrickgold** [comment]
This sounds like a great idea but I already see difficulties in the backend, as I would have to save the state of each pasting action. I'll for now add it to the v0.4.0 milestone and will see when rewriting the suggestions if I will implement it.
