### ISSUE TITLE
Few features and default settings

### ISSUE THREAD

**Issue by antonygggg** [florisboard/florisboard#701]
Features request :

1) Word delete ( when **holding** delete key, word divided by white spaces will be delete and not chars ), maybe somethings like
**Delete key long press** configurable gesture can be exactly what is needed.

2) Emoji dedicated key that will take you to the last state of the emoji selection screen, i know that i can set this but i want also the language switch key.

3) Space key move right/left gesture add switch language action ( this is another option to get along with **Emoji dedicated key** ), I have seen that this option already exists in the gestures screen ( move next subtype ) but its no working as expected.

Default settings :
I think that it may be more suitable for the most, especially new users to have
a. Keyboard height = Tall
b. Key spacing (vertical) = 8 half dp
c. Key spacing (horizontal) = 6 half dp

**Comment by patrickgold** [comment]
Closing as stale
