### ISSUE TITLE
Swipe from delete button to select text

### ISSUE THREAD

**Issue by alxlg** [florisboard/florisboard#705]
Currently if enabled you can use a swipe from delete button to select text and **delete it**. I think it would be more useful if it **just selects the text without deleting it** , then you would press delete, copy, cut or whatever.

**Comment by patrickgold** [comment]
Thanks for your suggestion! This can definitely be done, adding to the todo list!

As a workaround you could use shift+space left/right (if set to cursor movement) to select text, then you can decide to cut/copy/whatever with the text.

**Comment by GithbUser** [comment]
this feature would be good to have in florisboard
because the current workaround needs you to use both hands
while select text with delete gesture would allow user to to select text one handed

**Comment by pierstitus** [comment]
> As a workaround you could use shift+space left/right (if set to cursor movement) to select text, then you can decide to cut/copy/whatever with the text.

I tried that (in v0.3.12) but it doesn't seem to work for me. Swiping the spacebar with shift pressed just inserts a space, while without shift pressed it does move the cursor around. Did it get removed @patrickgold?

**Comment by patrickgold** [comment]
@pierstitus It didn't get removed, but the layout re-implementation currently bugs out when two input pointers are simultaneously responsible for executing a swipe action (and shift/space bar is one of such). When I fix that this gesture will work again.

**Comment by pierstitus** [comment]
Ok, good to know! Thanks!

**Comment by patrickgold** [comment]
Above commit adds the option to select text either by characters or by words with the delete key. Will be available in the next beta release 0.3.14-beta10. Thanks again for your suggestion!

**Comment by alxlg** [comment]
@patrickgold thank you very much, looking to try it as soon as it is released!
