### ISSUE TITLE
Slow responding in latest version

### ISSUE THREAD

**Issue by mortezae** [florisboard/florisboard#708]
#### Short description
It got too slow in latest version, I guess this occurred after upgrading to new layout system. I found some similar issues here, all reported some low memory error message, not sure if mine is the same, btw I see no error message. The problem is that it's slow in responding and sometimes completely freezing.

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: F-Droid
- Device: Galaxy A21s
- Android: 10
- Layouts: English, Persian

**Comment by Glitchy-Tozier** [comment]
Possobly connected to #677.

**Comment by stipey75** [comment]
Same here.

Info:

- FlorisBoard Version: 0.3.10
- Install Source: F-Droid
- Device: Asus Zenfone Max Pro 2
- Android: 9
- Layouts: Italian,English

**Comment by reg3xp** [comment]
Same here
I had no problem until i disabled hinted number row and hinted symbols.
Info:

    FlorisBoard Version: 0.3.10
    Install Source: F-Droid
    Device: S9
    Android: 10
    Layouts: Persian,English

**Comment by Glitchy-Tozier** [comment]
> I note that the app get less responsive after some time of use, clearing cache seems temporary solving the problem. So memory issue seems the real problem as pointed out in #677

In that case we can probably close this issue and focus the discussion on #677!

**Comment by lawson85** [comment]
Android 11 is out for your device: https://m.gsmarena.com/samsung_galaxy_a21s-10239.php

Maybe that fix the slowness? 

Or turn off animations from developer options to make your entire device faster

**Comment by R4ygen** [comment]
Same here, since the last update the keybord keep lagging behind of 2-3 seconds when opening, when writing, and sometimes get stuck on the screen without a way to close it but to force close the application from system settings.

Following the advices on #677 of deactivating both functions: Suggestions and Internal clipboard, and then reboot the phone, the issue looks to be disappeared for now.

**Comment by tsiflimagas** [comment]
I suspect that FlorisBoard has become much better in this aspect, especially in today's version 0.3.13-beta03.

**Comment by patrickgold** [comment]
Thanks for the feedback! It seems like a lot of testers say exactly this - beta03 is a noticeable improvements. Lags and issues with gestures and backspace are still there, but far more rarely.

**Comment by Glitchy-Tozier** [comment]
I'll close this issue as it most likely has been solved in later versions of FlorisBoard.

Please reopen, should the problem persist!
