### ISSUE TITLE
Description in F-Droid is cut-off

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#709]
#### Screenshot
![Screenshot_20210418-190249_F-Droid.jpg](https://user-images.githubusercontent.com/59611881/115154291-67a12380-a07a-11eb-8988-35edcafd99bc.jpg)

#### Comment
On the (German) PlayStore everything seems to be just fine.

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by Glitchy-Tozier** [comment]
Kind of funny. It's like writing "fat" like this: **fat**.
Or "kursive" like this *kursive*.

**Comment by Glitchy-Tozier** [comment]
The only [file](https://github.com/florisboard/florisboard/blob/80bfe03c0b1d681e9816f2cb9479788f20db0018/fastlane/metadata/android/en-US/short_description.txt) I can find is complete, however. Maybe there's a character limit?

**Comment by patrickgold** [comment]
Thanks for pointing this out! This seems to be a character limit in F-Droid I wasn't aware of. Will see how I fix that one, because I like the description how it is currently.

**Comment by Glitchy-Tozier** [comment]
I like it too... 
Maybe we could just remove the word "stage".

Btw, once the really pressing issues (like OOM) are fixed, I'd suggest also checking whether the descriptions in other languages have the correct amount of characters.

**Comment by another-sapiens** [comment]
While making the Spanish readme, I had this in mind and instead of "Actualmente", I wrote "Aún". In English, that would be "Still" instead of "Currently".

I think shaving off those extra 4 characters would be just enough to not exceed the limit.

So, we could either go with @Glitchy-Tozier 's suggestion and erase "stage", or change "currently" to "still".

**Comment by Glitchy-Tozier** [comment]
Personally, i prefer @Glitchy-Tozier 's suggestion (what a shocker, I know)

"Still in early-beta stage" has a slightly negative connotation in my opinion. It sounds a little like "why is devellopment so slow??" My english isn't perfect though, so i may be mistaken.

@ Patrick: To me, it sounds like the German "immer noch in beta"

**Comment by patrickgold** [comment]
@Glitchy-Tozier I completely agree with you - "still" indicates that development should be further ahead and the app is still in beta even though it should be release, while "currently" suggests that FlorisBoard IS currently in beta, without indicating that it is further ahead or back in the plan. So I will probably just cut off the "stage" at the end. This is on my todo list but currently I am working on #734 and until that's up and running (the PR is essential in improving the base memory management and performance) I won't really work on other things.

**Comment by Glitchy-Tozier** [comment]
> This is on my todo list but currently I am working on #734 and until that's up and running (the PR is essential in improving the base memory management and performance) I won't really work on other things.

No worries, I agree that #677 and #734 clearly are the most pressing issues!

**Comment by another-sapiens** [comment]
@Glitchy-Tozier Yeah I think you're right, haven't thought it like that. I'll blame it on my non-nativeness.
 
Kinda wanna change it in the translation now, but Spanish is not very known for being compact and the words need to be shaved off, else they won't fit.

**Comment by another-sapiens** [comment]
Also, you Germans have some really long words. How in panzers name do you manage to fit everything into apps' tiny UIs?

**Comment by Glitchy-Tozier** [comment]
Yeah, German's kind of fun, you can theoretically  just link nouns together for pages on end. :smile:

**Comment by another-sapiens** [comment]
LOL! Imagine an app where the UI is reduced to just one button, the sheer size of a single word leaving space for nothing else but that one button. 
And I thought Spanish was hard to work with.

**Comment by Glitchy-Tozier** [comment]
Interestingly enough, the word "stage" already is missing in the Gihub-description as fas as I can see.

**Comment by patrickgold** [comment]
> Interestingly enough, the word "stage" already is missing in the Gihub-description as fas as I can see.

Good catch! Seems like I forgot to add "stage" in the GitHub description, but removing it is the way to go anyways thanks to the tight character limit in F-Droid.

**Comment by patrickgold** [comment]
Above commit fixes the F-Droid store description by removing the "stage" at the end. Additionally, I also had to adjust the beta short description, as it was also over the character limit.
