### ISSUE TITLE
Option to have spacing in the middle row

### ISSUE THREAD

**Issue by mahmutsezai** [florisboard/florisboard#710]
Migrating from Gboard but there is no spacing between borders of the phone and first/last letter of the middle row. This makes typing so hard for me. I'd very happy to have an option. Leaving screenshots for better understanding.
![IMG_20210419_013544](https://user-images.githubusercontent.com/82783313/115163053-a1405180-a0af-11eb-81d7-ec4964eb6f17.jpg)
![IMG_20210419_013606](https://user-images.githubusercontent.com/82783313/115163056-a30a1500-a0af-11eb-8580-209902f0f2fc.jpg)

**Comment by hakkikaancaliskan** [comment]
Duplicate of #688
