### ISSUE TITLE
German Crash Report has Inconsistencies.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#712]
Maybe just place the button names in variables and reference them whenever necessary?

![Screenshot_20210419-094946_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/115201054-2c900600-a0f5-11eb-99ac-3bba569327ad.jpg)

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
This was indeed an issue in v0.3.10. I circumvented it in #704 by not using the exact labels of the keys anymore. For the crash report label, it is saved in an extra variable and never translated, as everything on GitHub is always in English and it is more confusing if I allow this label to be translated.

**Comment by Glitchy-Tozier** [comment]
Ah, correct, we changed that part too! I'll close this issue then. :)
