### ISSUE TITLE
Keyboard flashing after turning enery save on/off

### ISSUE THREAD

**Issue by felixwiemuth** [florisboard/florisboard#713]
#### Short description
Whole keyboard widget flashes at around 1Hz.
Happened after switching energy save mode on/off. According to settings, switching to energy save mode comes with switching to dark mode (and back to light mode when turning off). I observed the issue both in dark and light mode. Keyboard can be closed and opened and it happens again. The keyboard can be used normally while it flashes. After switching to a different keyboard and back it does not flash anymore.

#### Steps to reproduce
1. Have keyboard enabled, use it and
  a. leave it open
  b. or close it
2. Turn energy save mode on or off.
3. Tap into a text area to open keyboard, it flashes.
4. Close and reopen keyboard, it continues flashing.

First it seemed that the keyboard had to be closed when turning energy save mode on/off and that having it open would stop the flashing when reopening the automatically closing keyboard. But then it happened in both cases.

#### Screenshots
Here are screenshots in the "normal" and "faded out" state between which it switches when flashing.

![KeyboardFlashing1_20210419-124212_1](https://user-images.githubusercontent.com/533601/115224332-070ef680-a10d-11eb-89db-baf54f2659f1.png)
![KeyboardFlashing2_20210419-124324_1](https://user-images.githubusercontent.com/533601/115224327-05ddc980-a10d-11eb-8f6e-862c71e7e95b.png)

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: F-Droid
- Device: Pixel 4a
- Android: Android 11 (GrapheneOS)

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for the detailed bug-report!  :)

This bug was already reported in #589 and (hopefully) fixed for good in #669. In v0.3.11 the bug should be gone, so i suggest we close this as a duplicate.

**Comment by felixwiemuth** [comment]
Ah interesting how it can be triggered by different things apparently. Unfortunately I only searched with the standard filter which excludes closed issues :D.

**Comment by Glitchy-Tozier** [comment]
Ah, that makes sense! I can see how that closed issue could slip under the radar.

Could you possibly close the issue? I don't have any editing privilegues (I'm just a regular user 😅)

**Comment by patrickgold** [comment]
Could you possibly close the issue? I don't have any editing privilegues (I'm just a regular user sweat_smile)

@Glitchy-Tozier I just discovered that one can add people to a repository with varying privilege levels. As you are a very frequent issue contributor and one I do trust, I've invited you to be added to this repository team with the level "Triage" (if I understood correctly this level allows you to close issues, give labels, etc.) This would be very useful in cases like this issue, as currently only the issue reporter and I can close the issue. If you want to accept this, you can confirm the invite by using the link GitHub has sent you via email. :)

**Comment by Glitchy-Tozier** [comment]
@patrickgold Yep, that's what it seems to enable me to do! I'll happily accept the invitation.  :D
(btw, it also lets me edit assignees and milestones. I don't plan on doing anything with those, just mentioning it for your information. Also, no editing titles of issues or anything like that.)
