### ISSUE TITLE
german dictionary?

### ISSUE THREAD

**Issue by kosakepferd** [florisboard/florisboard#715]
I'm not sure if I'm being too stupid or if the German dictionary just isn't there yet?

**Comment by tsiflimagas** [comment]
Word suggestions are in an early age and will undergo a re-write, so more dictionaries will come for sure but when the suggestions mechanism will get stable at some level I guess.

**Comment by Glitchy-Tozier** [comment]
tsiflimagas summarized it perfectly.

If you're interested in seeing the exact plan Patrick is following, check out #325. (you can ignore the version numbers though, pretty sure we're still in **Phase 1**.)

Are there any further questions?  :)

**Comment by kosakepferd** [comment]
I like the keyboard very much so far. Unfortunately, there is no good keyboard with glide typing that is not commercial and does not send data to large companies.

So I see potential here and if there is a German spell checker, maybe there will be a recommendation on kuketz-blog.de (which is an important German blog for data security).

The important thing is that the settings remain clear and not such a mess as with anysoftkeyboard. :)

**Comment by Glitchy-Tozier** [comment]
> The important thing is that the settings remain clear and not such a mess as with anysoftkeyboard. :)

I, too, was on the search for a good keyboard for years. I went trough AnySoftKeyboard (ASK), then Simple Keyboard, then OpenBoard (which looked really promising, but did weird pop-up-stuff and had long periods of inactivity), and even 8Vim.
One of my first thoughts after finding Florisboard was "This is amazing, let's hope he doesn't accept every single feature request and turns the app into ASK". 
So far Patrick did a good job at keeping things manageable and even announced a settings-redesign.

> So I see potential here and if there is a German spell checker, maybe there will be a recommendation on kuketz-blog.de (which is an important German blog for data security).

Sollte ich mir mal anschauen, sieht nach einem interessanten Blog aus!  :)

**Comment by kosakepferd** [comment]
Ja mach mal, die Artikel dort und die Empfehlungsecke sind echt genial.

The biggest deficit of all free keyboards is the poor word recognition and the poor dictionary. And I have the feeling that all free keyboards technically have the SAME word recognition.

**Comment by Glitchy-Tozier** [comment]
> The biggest deficit of all free keyboards is the poor word recognition and the poor dictionary. And I have the feeling that all free keyboards technically have the SAME word recognition.

As far as I am aware, Florisboard uses ASK's glide typing, with small changes. (See #544)

Suggestions something really important and most open-source keyboards were really disappointing in that regard.
Florisboard's suggestions still are somewhat basic, but it's reassuring that Patrick (and other contributers) *know* that it's basic and are planning to do something about that.  :)

**Comment by kosakepferd** [comment]
I noticed another advantage of Florisboard: With other keyboards, the suggestion bar disappears in certain situations (For example, in some search masks). With Florisboard, it has always appeared so far.

**Comment by Glitchy-Tozier** [comment]
Yeah, the URL keyboard is pretty similar!
In password-fields and (i think) in the numerical mode it's gone and replaced by something more useful, but those make sense I think.

Let's close this issue as a duplicate (of #325) to keep the issues clean! Should you have any questions, make sure to ask!  :)
