### ISSUE TITLE
colemak support

### ISSUE THREAD

**Issue by nonetrix** [florisboard/florisboard#72]
Colemak or other alternative English keyboard layouts would be great I use colemak over QWERTY since it's a lot easier for me to type on theirs also other keyboards like Dvorak halmak and many more I can't think of the top of my head

Here is what colemak looks like in my current keyboard openboard
![Screenshot_20201207-183427](https://user-images.githubusercontent.com/45698918/101421869-f5922400-38ba-11eb-903e-af09a4c1a5df.png)

**Comment by patrickgold** [comment]
Thanks for your suggestion, nonetrix! I've heard of QWERTY alternatives long before I started with this project but then never thought of implementing it into FlorisBoard. I've put it on my todo list for v0.4.0!

**Comment by zachdecook** [comment]
For additional keyboard layouts, it would be fantastic to be able to directly load these from external files. That way, users with very specialized needs won't have to compile their own builds.

**Comment by nonetrix** [comment]
yeah this would be amazing I want to make my own keyboard layout for fun soon tbh

**Comment by patrickgold** [comment]
Above two commits add the Colemak and Dvorak keyboard layout, selectable as an alternative layout in the subtype dialog. Will be released with v0.3.1 tomorrow.

**Comment by patrickgold** [comment]
> For additional keyboard layouts, it would be fantastic to be able to directly load these from external files. That way, users with very specialized needs won't have to compile their own builds.

Extension support for dictionaries, keyboard layouts, etc. is planned for v0.4.0, I just don't know yet how it will exactly work. (See milestone v0.4.0 / Module C).
