### ISSUE TITLE
Test issue, please ignore!!

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#722]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
4. See crash

**Comment by Glitchy-Tozier** [comment]
@patrickgold Adding a separate (crash)-tag seems like a good idea to me... What's your opinion on that? I could also understand the view of "It still is a bug, so no separate label".

**Comment by patrickgold** [comment]
On the one hand this would look cool, though when filtering issues on GitHub and I want to see all bugs (which logically includes crashes for me) this gets annoying real fast, so I think I will let it on the same label for now.

**Comment by Glitchy-Tozier** [comment]
Understood  :)
