### ISSUE TITLE
Add `Copied to Clipboard.`-toast on button-click in crash-report

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#724]
Currently the user has no indication that anything has happened when clicking on the "Copy to clipboard"-button. I suggest adding a toast with a length of your choosing notifying the user that, indeed, something was copied.

(As an example, see the toast in Signal when copying an invitation-link for a group)

1. Here's the first Website that looked helpful: https://kotlin-android.com/android-toast-kotlin/
1. This looks like a fun fix, and i would be motivated to pull-request this myself, but unfortunately I'm currently a too busy to also try getting the hang of Kotlin.  :/
1. Not sure whether there should be a period at the end of the toast and whether "clipboard" should be capitalized.

**Comment by Glitchy-Tozier** [comment]
Not sure whether there should be a period at the end of the toast and whether "clipboard" should be capitalized.

**Comment by kj7rrv** [comment]
Maybe just "Copied"? If I were writing it and the whole phrase was needed I would probably say "Copied to clipboard".On Apr 21, 2021 06:37, Glitchy-Tozier ***@***.***> wrote:
Not sure whether there should be a period at the end of the toast and whether "clipboard" should be capitalized.

**Comment by Glitchy-Tozier** [comment]
That would also be an option. Let's see what Patrick thinks about it once he finds this issue!

**Comment by patrickgold** [comment]
Thanks for your suggestion! IMO the term "Copied to clipboard" works best for the scenario, will add this soon via a PR!

**Comment by patrickgold** [comment]
I've settled on using "Copied to system clipboard" to further indicate that the system clipboard, not the internal Floris clipboard is used when pressing this button. Will be available in v0.3.11-beta03!

**Comment by Glitchy-Tozier** [comment]
1. Yay!  :)
For some reason i'm really looking forward to seeing this change in action.
2. Actually, @patrickgold , your comment raises a new question: If the internal clipboard is enabled, shouldn't we copy it there instead?

**Comment by patrickgold** [comment]
> Actually, @ patrickgold , your comment raises a new question: If the internal clipboard is enabled, shouldn't we copy it there instead?

No, because the crash dialog is installed outside of Android's Application context and thus it does not really know what crashed. Imagine the crash source IS the internal clipboard - we would have a crash loop. Another thing is if the crash occurs while opening the keyboard, you can never paste the copied stacktrace as the crash will prevent you from even seeing the internal clipboard paste button.

**Comment by Glitchy-Tozier** [comment]
Makes sense, let's stick with your implementation then!
