### ISSUE TITLE
Florisboard crashed according to my phone

### ISSUE THREAD

**Issue by brae-16** [florisboard/florisboard#729]
#### Short description
Describe what you were doing that could've led to the crash.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See crash

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report! In the future, please complete the issue-template to make the it more informative.

This issue has been reported a couple of times and is summarized in #677.
It is already being worked on, so I suggest we close this issue as a duplicate.
