### ISSUE TITLE
Bug on Label and Letter Previews!

### ISSUE THREAD

**Issue by kurdikeyboard** [florisboard/florisboard#730]
#### Short description
The label for alphabets in not shown in the keyboard app , In the central kurdish we have some vowel words (ھ - ێ - ڵ - ڕ and ە ) some of them have a same preview for example ( ە and ە ) this two words is diffrent but both of them are shown in same shape ( ە ) and also this ( ئ and ﺋ ) or letter Ha ( ھ ).

for that we are use the Label to them becuase of label the user is know which letter is Hah and which one is small vowel A for your information to understand me what i mean when i created the Central Kurdish layout to FlorisBoard i used this 

      { "code":  1607, "label": "ھ" },

      { "code":  1574, "label": "ﺋ" },

      { "code":  1749, "label": "ﻪ" },

in the keyboard app the label is not shown as you see above i used ( ھ ) for letter Hah and ( ﺋ ) for letter Alif.. etc 

but i don't know why is just show the code of letter and Label is not shown and that's difficult to users how to know which word is Hah and which one is vowel A look at the screenshot both of words is looks like eash other but they are so diffrent in writing...

[![Screenshot-2021-04-21-23-26-45-24.jpg](https://i.postimg.cc/kG1KJfRS/Screenshot-2021-04-21-23-26-45-24.jpg)](https://postimg.cc/T5bpQj92)

The word in left is Hah and another one is vowel A,
For Hah it must be shown ( ھ ) label  and for vowel A it must be show ( ﻪ )

In the GBoard that is have a diffrent layout the Hah is shown correctly as ھ but in FlorisBoard is NOT :( 

this one is Gboard that show Hah correctly 

[![Screenshot-2021-04-21-22-56-43-81.jpg](https://i.postimg.cc/fLbY6GJs/Screenshot-2021-04-21-22-56-43-81.jpg)](https://postimg.cc/f363dgcq)

I hope you understand me and fix that small bug for Labels (^_^)

#### Steps to reproduce
1. Go to 'Keyboard app'
2. Click on 'Writing something'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: curently 3.11 beta01 and all other versions have same bug
- Install Source: GitHub
- Device: Realme X2 Pro
- Android: 10 , Realme UI 1.0

**Comment by patrickgold** [comment]
Thanks for your bug report! The new version of the layout engine (#734) actually uses the label as the display now, will attach this issue to the PR! Will be released in v0.3.11-beta02.

**Comment by kurdikeyboard** [comment]
Oh thank you very much for your hard work bro you are awesome the label is now showing correctly, But there are another small bug in the debug version i downloaded the bottom bar that includes symbol space and enter button is disappeared in kurdish layout i don't know what's the problem i also added some other layouts there's no problem at all 🤔

![Screenshot_2021-04-29-04-27-31-13](https://user-images.githubusercontent.com/3160786/116491940-b8e3bb00-a8a3-11eb-9e69-5ab677130439.jpg)

**Comment by kurdikeyboard** [comment]
I found the bug when i enable Number row the bottom bar is Gone and numbers on the top is taller than alphabets but when disable number row the bottom bar is show and all buttons small than normal also the number row is showing in smaller size look the screenshot with when Number row disabled 
👇
![Screenshot_2021-04-29-04-47-01-62](https://user-images.githubusercontent.com/3160786/116492836-f47f8480-a8a5-11eb-89f2-a851614736bb.jpg)

**Comment by patrickgold** [comment]
Thanks for pointing this bug out! This is indeed a sync issue between the preferences and the keyboard state, will add a fix to the PR!

**Comment by kurdikeyboard** [comment]
Thank you very much
