### ISSUE TITLE
Keyboard starts flashing

### ISSUE THREAD

**Issue by kosakepferd** [florisboard/florisboard#731]
Hi community,

I have noticed something strange: after some time of use, Florisboard starts flashing. Approximately every second. I can continue to use it normally but the flashing is annoying :)
If I then switch to the aosp keyboard, everything is normal again.

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: <!--. OnePlus 5 with crdroid 7.4 (Andröid 11) -

**Comment by Glitchy-Tozier** [comment]
Hi again!  :)

This was already reported & fixed (see #589), so let's close it as a duplicate!
