### ISSUE TITLE
Smartbar state reset on screen-rotation

### ISSUE THREAD

**Issue by GenosseFlosse** [florisboard/florisboard#733]
#### Short description
The Smartbar status is reset after rotating screen. I expect the state to be remembered.

https://user-images.githubusercontent.com/59205524/115691649-8a735680-a35e-11eb-95b1-307bba0b7511.mp4

#### Steps to reproduce
1. Press smartbar access button
2. Rotate screen
3. Smartbar state was reset

#### Environment information
- FlorisBoard Version: 0.3.10 
- Install Source: GPlay
- Device: Pocophone F1 
- Android: 10, MIUI

**Comment by Glitchy-Tozier** [comment]
Additionally, if you're in any of the other views (symbol, emoji,...), you also get transported back to the normal letter-keyboard.

**Comment by GenosseFlosse** [comment]
What just occurred to me: is it only me who considers this a bug? 

One could argue it is a feature since normally one does not rotate screen mid-sentence when typing. And starting always at the same keyboard state can be seen as a feature.

I would appreciate other opinions on that.

**Comment by patrickgold** [comment]
> What just occurred to me: is it only me who considers this a bug?

The current behavior is not a bug but intended this way. The primary reason for this is that the whole input UI gets rebuilt upon rotating (although not everything anymore when using the experimental code in #734 ). Thus also the Smartbar gets re-initialized and the Smartbar state evaluation begins from upfront. Of course, I could cache the state, though in my opinion I like it that it resets.

**Comment by GenosseFlosse** [comment]
The BDFL has spoken! 😄
