### ISSUE TITLE
Searching for issue to ~remove typing errors.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#748]
@patrickgold Do you remember the "type letter upon pressed key instead of upon released key"-issue? (The one where you also suggested that the button that was pressed the longest should be typed)

Do you have a link to that issue? I have been searching for about half an hour and still can't find it...

**Comment by patrickgold** [comment]
I think you mean #601 :)

**Comment by Glitchy-Tozier** [comment]
Yay, ty ♪
