### ISSUE TITLE
Keyboard glitches when turning on or off dark mode

### ISSUE THREAD

**Issue by chillypeppe** [florisboard/florisboard#757]
#### Short description
After you turn off or on the dark mode on your phone and you open the keyboard, the color flickers and stops recieving input. It won't stop until you force close florisboard. Obviously the theme mode of florisboard is "follow system"

#### Steps to reproduce
1. Check if the theme mode of florisboard is set at "follow system"
2. Go on your phone settings and turn on or off dark mode
3. Open the keyboard in some app, as firefox browser or whatever
4. See the flickering and notice that the keyboard isn't working properly

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: F-Droid
- Device: Samsung Galaxy S10
- Android: 11 stock

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your bug report!

Is #589 your bug?

**Comment by chillypeppe** [comment]
@Glitchy-Tozier Yes! Sorry, I searched for it but I haven't seen that one. It's precisely what happens

**Comment by Glitchy-Tozier** [comment]
Great, thank you for looking up the issue!

It's easy to miss, as it only shows up when searching for "flashing" but hides when looking for "flickering".
