### ISSUE TITLE
Add Flow layout when implementing glide/swype typing

### ISSUE THREAD

**Issue by jeremiah-miller** [florisboard/florisboard#76]
I just learned about the Flow keyboard after seeing [this issue](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2545) on ASK, and while I haven't spent a ton of time on it, my initial thought is it's super promising and if the reviews on google play are anything to go by, it's really good. That said, the emoji keyboard is seriously lacking, and there's no dark theme option. Perhaps that layout could be added to florisboard, and the glide typing as done in Flow could be used as an inspiration for implementing it in florisboard?

I'd love to help, however I'm not an android dev so I may not be able to help as much as I'd like :(

https://sourceforge.net/p/flowkeyboard/code/HEAD/tree/
https://play.google.com/store/apps/details?id=com.enchantedcode.flow

**Comment by patrickgold** [comment]
Thanks for bringing up this new concept of text input. I've never heard of it, but on first look is a truly new way of inputting text on a phone screen. This is worth trying out at some time in FlorisBoard but would require a completely separate rendering and touch logic for this layout. At the current state I'm unsure if this concept will make it into FlorisBoard or if one should just use the original IME, but I'll definitely keep an eye on it. Note though that v0.4.0 (next planned major release which adds composing suggestions and hopefully glide typing) is due to start with developing, so I'll probably don't have time for looking at this topic until early 2021.

> I'd love to help, however I'm not an android dev so I may not be able to help as much as I'd like :(

Even if you are not an Android dev, you can still help by testing out new features, suggest ideas, report bugs and crashes, etc. This help is incredibly useful in improving FlorisBoard and for me it would not be possible to do this alone :)

**Comment by jeremiah-miller** [comment]
Yeah, I tried looking through the source code of flow and florisboard to see if I could do it myself but I got lost real quick. I was hoping that since glide typing hasn't been implemented yet that it would be easy to use a similar algorithm for all the swipe typing in florisboard regardless of layout, but it sounds like that won't be possible which is unfortunate. 

I'll keep an eye out for anything, it's already a pretty solid keyboard from what I've seen so keep up the good work :+1:

**Comment by patrickgold** [comment]
> I was hoping that since glide typing hasn't been implemented yet that it would be easy to use a similar algorithm for all the swipe typing in florisboard regardless of layout

As I've not worked on glide typing yet, I'm not sure how much of its algorithm could be reused for the flow algorithm as well. I've planned that the glide typing algorithm works on top of the custom KeyboardView (and detects the current key with the touch hit box, which is usually bigger than the key itself). When implementing glide typing I could try to make every part of the algorithm as standalone as possible to be able to adapt it easily for a flow type layout.

Another issue after trying it out more I currently see with the flow layout after trying it out more is that it is pretty English focused. Yes, i know that it supports different languages but the insertion of special characters like ä ö ü isn't that well designed imo.

> I'll keep an eye out for anything, it's already a pretty solid keyboard from what I've seen so keep up the good work 👍

Thanks for the positive feedback! :)

**Comment by jeremiah-miller** [comment]
That would be pretty cool, and would make it easier to add all sorts of new layouts in the future. But yeah that is one big issue with it, unfortunately I think for other languages (even ignoring the lack of special characters) you'd need to regenerate the optimal layout based on the common patterns of that language. I'm not sure how Peter Eastman generated flow for english, but I'm sure it could be done with an ai like how this guy made [halmak](https://github.com/MadRabbit/halmak) (also English, but the process could be followed for other languages)

**Comment by testing4573** [comment]
It would be awesome for the ability to choose between which layout you wanted to use was implemented in settings, so you could switch back and forth between the layouts if you needed to.
Considering that flow is open source wouldn't it be possible to input/implement some of it's code into Florisboard?

**Comment by testing4573** [comment]
> That would be pretty cool, and would make it easier to add all sorts of new layouts in the future. But yeah that is one big issue with it, unfortunately I think for other languages (even ignoring the lack of special characters) you'd need to regenerate the optimal layout based on the common patterns of that language. I'm not sure how Peter Eastman generated flow for english, but I'm sure it could be done with an ai like how this guy made [halmak](https://github.com/MadRabbit/halmak) (also English, but the process could be followed for other languages)

It looks like Flow keyboard supports French, German, Spanish, Portuguese, and American and British English.
https://sourceforge.net/p/flowkeyboard/code/HEAD/tree/trunk/res/raw/

**Comment by jeremiah-miller** [comment]
@patrickgold I finally got around to trying out the latest beta and I just wanted to say great work on the gesture/swipe typing! 

A couple other potential layouts that could be good to add for swipe typing are the ones found here http://sangaline.com/post/finding-an-optimal-keyboard-layout-for-swype/ and here https://jasmcole.com/2017/06/04/swype-right/

If you'd be ok with adding those layouts I could probably go ahead and make a pull request with them

**Comment by patrickgold** [comment]
@jeremiah-miller Definitely interesting but I'd wait for the new layout logic to be merged into master (#734). This PR abstracts the layout definition and should make implementing such a layout a bit easier.

**Comment by jeremiah-miller** [comment]
I think with #1015 merged, there's no longer any reason to bring in the flow keyboard layout. The amount of effort to get it to work seems excessive to me, and after getting used to the NALMY layout for several weeks after using flow regularly, it's about the same if not better in terms of efficiency anyways. Of course if you want to add it eventually that's up to you, but I think it makes the most sense to close this issue

**Comment by patrickgold** [comment]
@jeremiah-miller If you think so then we can close this issue. As there's already a lot of development stuff to do in so many different areas I think this is the best option.
