### ISSUE TITLE
How do I contribute to this project? Unable to create a new branch / Pull request

### ISSUE THREAD

**Issue by olLenz** [florisboard/florisboard#760]
Hey :)
I am currently looking through this project and I noticed some parts of the project that could be improved. I already created a new local branch but I am unable to push the branch.

Do you have any rules that prevent new people from contributing? 

This is my first contribution to other peoples Open Source Projects so I am not sure what I am doing wrong. Pulling and pushing my own private/public repositories via ssh on github is working for me without problems.

**Comment by Lurux** [comment]
I haven't contributed here, but - does the fork function not work here ? I'm pretty sure that's the correct way to do it.

**Comment by patrickgold** [comment]
Hi,

To properly contribute to FlorisBoard you first need to fork this project, then clone the fork.to your local machine. Once that's done you can create a local branch, make your changes and push the local branch to your fork remote. After this you can go to Pull Requests > New within this repository, select your remote fork branch as the source and the FlorisBoard master branch as the destination. Then I can review your code and decide if it can be merged into master etc.

Direct write-access to this repo is disabled for non-members to protect unwanted modifications to be done without going through the Pull Request review cycle.

Hope this could help :)

**Comment by olLenz** [comment]
Thank you for the explicit explanation!
I am used to a protected main/dev branch and just opening new feature branches in the same repository.
I successfully created the pr :)
