### ISSUE TITLE
Keyboard flashes after changing the theme.

### ISSUE THREAD

**Issue by psiwray** [florisboard/florisboard#762]
#### Short description
I noticed that when I change the dark theme on the fly from the settings, sometimes the keyboard starts flashing brighter and darker. This doesn't always happen, but when it happens it's not a single app but any app.

#### Steps to reproduce
1. Change theme to dark or light.
2. ...
3. Sometimes you can see the keyboard flashing.

https://user-images.githubusercontent.com/47721792/116047204-227d8280-a674-11eb-9389-cc5086034dc5.mp4

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: F-Droid
- Device: Samsung Galaxy A5 2017 (a5y17lte) 
- Android: LineageOS 17.1

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your bug report!

This bug has already ben reported in #589. It's already fixed and yhouldn't be happening anymore in the coming release.

Let's close this issue to keep the list free of clutter!  :)

**Comment by psiwray** [comment]
Sure thing. I tried searching first for an existing issue but didn't come up with a lot of keywords to describe it and as a result found no open issues. Sorry for having opened another one, my bad!

**Comment by Glitchy-Tozier** [comment]
No worries. Thank you for looking for duplicates in advance!
