### ISSUE TITLE
AdaptiveTheme memory leak

### ISSUE THREAD

**Issue by patrickgold** [florisboard/florisboard#763]
#### Short description
The Adaptive Theme overlay is a bigger memory hog than anticipated:

![image](https://user-images.githubusercontent.com/19412843/116123878-d65a2e80-a6c3-11eb-91f9-b7ab7f41f4fc.png)

Above picture showcases the allocations / remaining size in memory only caused by the `updateRemoteColorValues()` method in `ThemeManager`. If enabled, you can see the memory usage continuously climbing (~5MB per minute), if disabled, it grows but only 0.01MB / minute (values of course are only if continuously typing is done). For now the adaptive theme feature will stay disabled (and probably will so for the next beta release), as the leak itself occurs within an Android OS class and not FlorisBoard one (though maybe there are ways to circumvent it).

This issue funnily occurs regardless if adaptive themeing is enabled, as the remote color update was always performed. There is definitely room to improve here...

Disclaimer: Clipboard and Glide typing were disabled during this profiling session, the layout code uses the new memory optimizations in #734.

Related to #677

#### Steps to reproduce
Enable adaptive theme in the theme settings and watch your RAM usage go up...

#### Environment information
- FlorisBoard Version: 0.3.11-beta01
- Install Source: ADB
- Device:  OnePlus 7T
- Android: 10, Oxygen OS

**Comment by Glitchy-Tozier** [comment]
Now it would be interesting to see how ASK manages not to crash!

**Comment by patrickgold** [comment]
Yes definitely. I am updating the colors similar to ASK, though maybe I am doing something differently and exactly that is the issue.

**Comment by patrickgold** [comment]
Above PR changes the way I retrieve the colors a bit and is now very similar to ASK's way. The memory adaptive theme uses now is a lot less and the dynamically created context objects are cleared after some Garbage Collector cycles. Adaptive themeing will thus be available again in v0.3.11-beta03.
