### ISSUE TITLE
Florisboard blinks

### ISSUE THREAD

**Issue by shinze** [florisboard/florisboard#768]
Pixel 2 XL, stock Android
Florisboard keyboard blinks on opening. To stop it I have to select another input method and go back to Florisboard.
Not sure how to reproduce this, it seems to do that after a lonq time not being used.

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your bug report!

This bug has already been reported in #589. It's already fixed and shouldn't be happening anymore in the coming release.
For now, rotating your phone into horizontal mode and back may stop the flashing.

Let's close this issue to keep the list free of clutter! :)
