### ISSUE TITLE
Follow system theme

### ISSUE THREAD

**Issue by LongJohn-Silver** [florisboard/florisboard#77]
As of now there are both darl and white themes for Florisboard, but you need to select them manually if you want to switch from one to the other, which is not super convenient if you use a scheduled dark mode, and since they keyboard is a big part of the screen and something you use a lot it is a bit impractical to have the rest of your system on it while the keyboard remains on a light mode.

It would also be awesome that when this gets added, that you could select the variation of both the light and dark themes. So, for example I changed the colours of my light theme, but I do not want them to go to default once I switch to dark mode, and viceversa. Slide, a Reddit client, does this pretty well.

**Comment by patrickgold** [comment]
Thanks for your suggestion! I'll definitely put the scheduled theme / follow system theme on my todo list. Regarding the theme variations, I think it is best if one could save the current theme locally as a custom theme, so the configuration doesn't get lost when switching.

**Comment by LongJohn-Silver** [comment]
@patrickgold Thank you for accepting it! Is this going to be released on 4.0 or 5.0?

Yeah, I think that would be best, as long as users do not need tp reload the file every time, this could also make it easier for people to share themes.
