### ISSUE TITLE
Add a textfield close to the settings to test the changes

### ISSUE THREAD

**Issue by Luensche** [florisboard/florisboard#770]
Hello, 
I hope I didn't miss an issue, but I think it would be nice to have a simple text field close to settings to test the changes just made.

**Comment by patrickgold** [comment]
Thanks for your suggestion! This has already been proposed in #190 and is planned sometime during the v0.5.0 development. Closing this issue as a duplicate.

**Comment by Luensche** [comment]
I am sorry, it seems, that I didn't search well.
