### ISSUE TITLE
Small visual bugs in Theme Manager preview screen

### ISSUE THREAD

**Issue by hbarsaiyan** [florisboard/florisboard#776]
#### Short description
Small visual bugs in Theme Manager preview screen.

![Screenshot_20210501-005850_FlorisBoard_Beta_1](https://user-images.githubusercontent.com/37732050/116746245-cfac1e00-aa19-11eb-9e17-a3f29717598f.png)

#### Steps to reproduce
1. Go to Theme
2. Click on Selected Theme

#### Environment information
- FlorisBoard Version: 0.3.11 beta 2
- Install Source: Github
- Device: Lenovo Tab4 X304L
- Android: Lineage OS 16

**Comment by patrickgold** [comment]
Thanks for your bug report! I've just checked this one out and confirm the visual bug, will push a fix right away.
