### ISSUE TITLE
Buttons in Theme-Selection don't fit onto Screen

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#777]
#### Short description
No idea if this still is a problem in the 0.3.11 beta versions, but in 0.3.10 the buttons in the theme-selection are to big to fit onto the screen.
(See how "Bearbeiten" turns into "Bear".)

![Screenshot_20210430-214455_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/116747292-f4929800-a9fd-11eb-86d8-277472961a17.jpg)

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! That's the result of localization again... In English the buttons perfectly fit onto the screen. Only thing I can do is to auto-wrap the buttons.

**Comment by patrickgold** [comment]
Here's a preview of the wrapping I added:

![theme-manager-wrapping-buttons](https://user-images.githubusercontent.com/19412843/116778549-d2872d00-aa72-11eb-94d5-4d48e213f1cb.jpeg)

Will be merged momentarily and released in beta03!

**Comment by Glitchy-Tozier** [comment]
Thiy seems like the best option, good job.  :)
