### ISSUE TITLE
Rendering issues regarding the new TextKeyboardView

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#778]
Im not sure what happened but my theme got changed when I installed the newest beta today. The foreground colour of all the button by default is lighter now. I went through the theme settings comparing them to the official release and everything is the same. I also deleted my theme and imported it again. Its still happening. 

Here is how it looks now:

https://picc.io/p/hdYEHeJ.jpg

And how it should be:

https://picc.io/p/iEKQfPW.jpg

**Comment by patrickgold** [comment]
That is indeed strange, I agree.I suspect that there's a bug in the way FlorisBoard draws the color (as your theme itself hasn't changed). DO you by any chance have a special opacity/alpha value set for the background color of the default key? Maybe the new rendering ignores the alpha channel, which could explain the above issue.

**Comment by Kreuger** [comment]
I dont think so. Im pretty sure I just changed the shift, backspace and enter keys. 

To try and make this easier for you to look into, heres the theme.

https://u.pcloud.link/publink/show?code=XZuIw1XZL2JWyVTRF8jS5xbq8Q8yEzQu1RR7

**Comment by patrickgold** [comment]
Thanks for sharing the theme, will try it out soon on my device! You are indeed not using semi-transparent colors, strange. Does the background color of the keys change when you press a normal key or is it stuck? This could maybe narrow it down where the bug happens.

**Comment by patrickgold** [comment]
Ok I just tested out your theme and the colors look normal on my end. This seems to be a more device-specific bug then. I'll now investigate the rendering logic where the issue could be. One question: Is it possible for you to install debug builds too or only the beta versions? Based on that I could try different things without completely being in the black.

**Comment by patrickgold** [comment]
Above commit is a possible fix for the key background color and also fixes another bug with the shift/delete foreground color always being black. If possible, could you try out the debug build and see if the issue is fixed? If so, it will be released in beta03 tomorrow. Thanks in advance!

**Comment by Kreuger** [comment]
Yeah I can try out the debug. I imagine it will install alongside the other 2?

**Comment by patrickgold** [comment]
Yes it installs alongside your two other versions. The Settings and everything else don't sync, but for test purposes it is sufficient if you import the theme you linked and try out if it renders correctly.

**Comment by Kreuger** [comment]
Do I have to build the apk myself or is there a download for it?

**Comment by patrickgold** [comment]
No, GitHub pre-builds debug APKs. See https://github.com/florisboard/florisboard/pull/782/checks then Artifacts and the app-debug.apk file.

**Comment by Kreuger** [comment]
Still happens with the debug. 😞

**Comment by patrickgold** [comment]
Thanks for trying it out! What I absolutely don't understand is why it only happens to the default color and not the shift, enter and delete. These use the absolute same method and logic to set the color... If for test purposes you try to change the default key background color in the debug version to some other colors, both in the gray scale and in some colorful colors like blue, red etc., what are the results?

**Comment by Kreuger** [comment]
All of the other ones work fine. Im baffled dude.

**Comment by patrickgold** [comment]
Wait even if you just change the color code's last digit by 1 value? Dafuq :confused:

**Comment by patrickgold** [comment]
Ok this smells like one color channel (either red, green or blue) is miscalculated somewhere, but seemingly only for your device. I'm really really baffled. Will investigate into this in a few hours and see what results I can get.

**Comment by Kreuger** [comment]
Ok dude no worries. I will keep using the main release for now but keep the beta and debug installed as well.

**Comment by patrickgold** [comment]
Ok thanks! I hope I can get behind the source of this sneaky bug, because it seems I introduced it with the latest beta 02.

**Comment by Kreuger** [comment]
Ooh I found something out. Rebooted my phone on a whim and now it works as expected. So Im guessing its a caching issue?

**Comment by patrickgold** [comment]
So it works both on the beta and debug build flawlessly? This fact makes the bug even more sneaky and strange...

I don't really think it is a caching issue, as the debug build generates a new cache after installing, but a caching issue in the Android framework for the drawing could also be the issue. Tbh, I currently don't know, I'm so confused by this bug's behavior :)

**Comment by Kreuger** [comment]
Yes it works on both after rebooting. Sorry I dont know enough about coding to make any other guesses.

**Comment by Kreuger** [comment]
Ok this is weird as hell man. Ive restarted my phone a couple of more times today for a different reason, and the colours have gone lighter again.

**Comment by patrickgold** [comment]
I've experimented further into this issue and just won't get smarter regarding this very weird behavior. Maybe someone else also experiences this issue so I can begin to narrow it down why this is happening.

**Comment by patrickgold** [comment]
Above commit fixes some color rendering issues for the foreground drawables (they were always black in certain scenarios, e.g. when changing the theme mid-way throughout the Service lifespan). Although it still doesn't fix your particular issue, it at least has something to to with your issue as well, so Iinked the commit here.

**Comment by patrickgold** [comment]
@Kreuger If possible, could you try out the latest beta release 0.3.14-beta09 and check if you can reproduce this issue? The UI library responsible for rendering has since then completely changed and maybe this bug got resolved with that. Thanks in advance!

**Comment by Kreuger** [comment]
Im currently unable to import my theme. I tried exporting it from the regular release and it comes up invalid.

**Comment by patrickgold** [comment]
Importing a 0.3.13 theme is impossible in 0.3.14, due to the massive changes in the underlying theme engine, stylesheet format and the introduction of extension files.

**Comment by Kreuger** [comment]
Alright so Im trying to make a new theme. How do I edit buttons? Like in the old one I would use "key:delete" and then set the colours I want. Is that possible?

**Comment by patrickgold** [comment]
The theme editor itself is very flexible (especially in the latest beta), the only drawback currently is that keys must be styled using their corresponding key code. The codes are defined when adding/editing rules, but on the upside any key (also multiple keys in the same rule) is/are now possible, which makes the possibilities of themeing the keyboard greater.

**Comment by patrickgold** [comment]
![Screenshot_20220208-073945.jpg](https://user-images.githubusercontent.com/19412843/152932242-6ab42eb6-b193-4075-8212-dab35b75f7bd.jpg)

This would be the rule to add for a delete key (note the -7 as code defined)

**Comment by patrickgold** [comment]
I can and will look into making selecting the codes easier (was also proposed by some other early testers of the new theme editor).

**Comment by Kreuger** [comment]
Is there a list for the codes?

**Comment by patrickgold** [comment]
If you press the question mark icon in the code dialog you will see links to how you get codes

**Comment by Kreuger** [comment]
Alright I was able to change a couple independantly and also the background colour as a whole and it seems the issue is gone. Well done!

**Comment by patrickgold** [comment]
Great to hear, thanks for confirming! If it is okay for you I will close this issue, as it is not present anymore.

**Comment by Kreuger** [comment]
Yeah man, no worries.
