### ISSUE TITLE
Option to hide Smartbar and its features altogether

### ISSUE THREAD

**Issue by puppykickr** [florisboard/florisboard#78]
<!--
- Describe your idea in a short but concise way.

Since the number row is an option as a long press on the top row of letters, it would be great if the number row could be eliminated altogether.

This would save screenspace for those of us that like larger keys.

**Comment by patrickgold** [comment]
Thanks for your suggestion! The ability to hide or better customize the Smartbar is planned to be implemented with v0.4.0 (composing suggestions + Smartbar rework), I'll add it to the corresponding milestone!

**Comment by patrickgold** [comment]
I've just merged the Smartbar rework branch into master, which also contains the ability to hide the Smartbar in the preferences. Will release with the next release v0.3.1. Thanks again for your suggestion!
