### ISSUE TITLE
Emoji button have different color when orientated

### ISSUE THREAD

**Issue by yant0** [florisboard/florisboard#783]
I have purple primary, primary (dark), and accent

![Screenshot_20210501-184414](https://user-images.githubusercontent.com/80298071/116781472-49d9b280-aaad-11eb-8f29-89082986c2f5.png)

![Screenshot_20210501-184420](https://user-images.githubusercontent.com/80298071/116781486-5b22bf00-aaad-11eb-8e38-96a54284b281.png)

- FlorisBoard Version: 0.3.11 beta 2
- Install Source: Github
- Device: Asus Zenfone Max Pro M1
- Android: 9, stock

**Comment by yant0** [comment]
Apparently this bug occurs when the keyboard opens and then rotated

**Comment by patrickgold** [comment]
Thanks for your bug report! This is indeed strange, possibly a bug applying the theme color to the tab ripple color. Will set this bug on the v0.5.0 milestone together with the emoji rework.
