### ISSUE TITLE
Option to remove/relocate emoji and language subtype switch button

### ISSUE THREAD

**Issue by puppykickr** [florisboard/florisboard#79]
<!--
- Describe your idea in a short but concise way.

I keep missing the spacebar and have to constantly go back and add spaces between words.

If the emoji button was removed, then the spacebar could be made quite a bit larger.

The emoji button could then be available upon a long press of the comma (or some other) button.

**Comment by patrickgold** [comment]
Thanks for your suggestion! I've put it on my todo list for the media rework, as it is directly connected to these milestone.

**Comment by Flame-0** [comment]
+1 relocate the emoji button as hint to comma button and enter button.

**Comment by patrickgold** [comment]
Above PR finally adds a way to customize how the emoji key / language switch should behave and if they should be shown. Will be released today with v0.3.5! Thanks again for your suggestion!
