### ISSUE TITLE
gesture not working

### ISSUE THREAD

**Issue by theotheroracle** [florisboard/florisboard#791]
since beta02 gesture doesnt seem to work

 https://ufile.io/l27hcpvp

**Comment by patrickgold** [comment]
Yes, this is known and stated in the btea02 changelog:

> NOTE: Glide typing and adaptive themes temporarily do not work in this release, also the gestures shift+space and shift-swipe+character.

Adaptive themes are already fixed, glide typing will hopefully be fixed tomorrow by me. The multi-pointer gestures will need a bit more time, but will definitely also find their way back into the codebase. Closing this issue thus.
