### ISSUE TITLE
Czech special characters unavailable

### ISSUE THREAD

**Issue by JosefLitos** [florisboard/florisboard#793]
Hello, I like this app in every way, but unfortunately it is unusable for me, as I use the czech keyboard, of which no layout is yet available.
The current options are sufficient for the most part, but our language uses acute characters and more, which is impossible to write with the current keyboard options.
Nonstandart letters we use:
žščřďťň, áěéíóúůý

**Comment by Luensche** [comment]
Maybe you can have a try by yourself, because I think it's an easier issue. As an example you can use the [German layout](https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/text/characters/german.json). An explanation how it is done you can find [here](https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md#adding-a-new-keyboard-layout).

**Comment by JosefLitos** [comment]
I didn't mean to create a different layout, I just miss these characters in the menus that pop up on a long key press. If I knew, where to add that, I would have tried myself.

**Comment by Luensche** [comment]
If a popup is enough for czech you can change [this file](https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/text/characters/extended_popups/cs.json) and create a pull request with the change.

**Comment by JosefLitos** [comment]
Ok, I will have a look, thanks.

**Comment by JosefLitos** [comment]
The problem is, it is already there, I just don't know, how to enable it. All the characters are present in the file, but I have no idea how to enable them in the app.

**Comment by Luensche** [comment]
Did you enable the czech style under writing in the app settings?

**Comment by JosefLitos** [comment]
The problem is - I don't see such option, I am running version 0.3.10, downloaded from f-droid. I am not sure, whether there is a mewer version available, but I went through every menu and none has the word 'czech'

**Comment by JosefLitos** [comment]
So, the beta version includes something called the Czech keyboard, but unfortunately no matter the keyboard I set, I can not write anything on it. So I guess we will have to wait until 0.3.11 is officially released.

**Comment by Luensche** [comment]
Ah sorry, you are right. It was added 23 days ago, but the last non-beta was released 27 days ago.

**Comment by JosefLitos** [comment]
No problem, thanks for the help.
