### ISSUE TITLE
Backspace icon colour

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#80]
Hey i just found your app and I'm liking it so far. I was just wondering if you could add an option to change the backspace button colour as we can with the shift and enter buttons. Thanks.

**Comment by patrickgold** [comment]
Thanks for your suggestion! This is definitely doable, although I'm not sure if it makes it into v0.4.0 or it will be added in v0.5.0 with the media rework. I'll put it on my todo list!

**Comment by Kreuger** [comment]
Awesome. Thanks!

**Comment by Kreuger** [comment]
Hey man I just got the new update, 0.3.3 for which I think you have closed this. However the new theme page is quite confusing. And I tried changing the background colour on the shift/caps lock button but it seems to have not worked. Is there anything else I need to do after saving it? And maybe you could do a quick guide explaining everything youve added.

**Comment by Kreuger** [comment]
I also cant figure out how to add a new key to customize. I tried using add group and when I use a colon to define the key (I tried key:backspace), it comes up as an invalid character.

**Comment by patrickgold** [comment]
You are right, I should have included a guide on how to use it properly. I will probably write a help guide in this repo's wiki and begin to link to it with the next version (v0.4.0).

> I tried using add group and when I use a colon to define the key (I tried key:backspace)

The correct term would be `key:delete` and then you would have to add a `background` and probably `backgroundPressed` attribute, which are the colors of the background specific for the backspace key.

**Comment by Kreuger** [comment]
Thanks man but that doesnt work as it wont accept the colon.

**Comment by patrickgold** [comment]
Yeah you are right I just noticed I am stupid and limited the input of the group name too much 🤦 . I will definitely fix this with the next version!

I've just drafted a guide for the new Theme Editor which explains all the groups and attributes: https://github.com/florisboard/florisboard/wiki/Using-the-new-Theme-Editor

Could you read over this and give me feedback if this helps you in using the Theme Editor?

**Comment by Kreuger** [comment]
That looks great man. And I managed to figure some things out as well such as using the textColor attribute to state the font colour. Although after reading that guide, it appears that is an unnecessary step as it is already defined by default in the window settings. I wasnt entirely sure so I added it in one spot, not realizing it was a global setting. I hope that makes sense. I think I get the gist of it now and I think it will help others as well. Great work!

**Comment by patrickgold** [comment]
> Thanks man but that doesnt work as it wont accept the colon.

Commit eecada311895a33ce465988cf8b9198dc87eb069 fixes this and allows for colons according to the format specified in the Theme Editor guide. Will be released in the next version v0.3.4!

**Comment by Kreuger** [comment]
I hate to be that guy but do you have an ETA? I built the apk myself but it made it the debug one so none of my other settings were there.

**Comment by patrickgold** [comment]
I will probably release v0.3.4 on Wednesday or on Thursday evening, depending on how fast I am able to identify and fix some issues I want to see fixed with v0.3.4.

**Comment by Kreuger** [comment]
Awesome man. Thanks for all that you do.

**Comment by Kreuger** [comment]
I just noticed another option that doesnt work. He attributes with an underscore in the name can't be changed because its not an accepted character.

**Comment by patrickgold** [comment]
Slowly but surely I am questioning my intelligence when it comes to input validation xD, this is the next thing I forgot to allow... Thanks though for bringing this up, I will fix it in v0.3.5 (will be released this Sunday evening).

**Comment by Kreuger** [comment]
Haha no worries man. I dont mind being a guinea pig.

**Comment by patrickgold** [comment]
Commit aab7a6e33addc11d766627df57ac2d0f0b2f59ed fixes the theme group name input validation for the underscore. Thanks again for pointing this out!

**Comment by Kreuger** [comment]
Once again, happy to help.
