### ISSUE TITLE
[Bug]: Glide Typing seems to be broken in v0.3.11-beta03

### ISSUE THREAD

**Issue by just-Nob** [florisboard/florisboard#802]
#### Short description
In the current beta v0.3.11- beta03, glide typing seems to be broken, i.e. the keyboard's behaviour is like glide typing was enabled (although it obviously is enabled in _FlorisBoard's_ settings, for sure).

##### Remarks
1. To ensure that there's no interdependency with my environment, I installed both versions ("official" one taken from F-Droid repo – currently v0.3.10 – & beta taken from GitHub) in parallel, so that I'm able to compare them. In v0.3.10, glide typing works fine!
2. I'm really impressed that _FlorisBoard_ doesn't seem to rely on google's libs for glide/gesture typing – thumbs up! My CustomROM comes with AOSP keyboard by default; for which I had to install google's gesture typing libs afterwards. I did that by installing the magisk module "Install gesture typing enabled AOSP keyboard". But _FlorisBoard_ keeps glide typing available even with that Magisk module disabled - chapeau! :-)

#### Steps to reproduce
1. Go to 'settings'
2. Enable 'activate glide typing' (or something similar – it's "Glide Typing aktivieren" in german)
3. Leave settings
4. Try to use glide typing
5. Observe that it doesn't work

#### Environment information
- FlorisBoard Version: v0.3.11-beta03
- Install Source: GitHub
- Device: Poco X3 NFC
- Android: ArrowOS 11 Vanilla
- Google Framework: microG v0.2.18.204714
- other Frameworks & Mods: Magisk, LSPosed (each with some mods, e.g. XPrivacyLua)

**Comment by patrickgold** [comment]
> In the current beta v0.3.11- beta03, glide typing seems to be broken, i.e. the keyboard's behaviour is like glide typing was enabled (although it obviously is enabled in FlorisBoard's settings, for sure).

That's because the glide typing interface has not yet been re-implemented ontop of the new rendering view class and the layout rework, thus the glide typing logic is not triggered at all. This is though planned to be fixed soon, hopefully before I release beta04!

**Comment by patrickgold** [comment]
Just so you know I will release v0.3.11-beta04 already now as it contains some critical fixes for memory management and annoying layout issues, so glide typing will be added back again in beta05!
