### ISSUE TITLE
Bottom row keys not shifted in Dvorak layout

### ISSUE THREAD

**Issue by benisjammin** [florisboard/florisboard#805]
#### Short description
The "Q" and "Z" keys remain lowercase when shift/caps-lock is applied in the Dvorak layout. This seems to be locale independent (tested across several locales using the Latin alphabet).

#### Steps to reproduce
1. Choose the Dvorak layout
2. Tap or double-tap on the shift key
3. Letters in the bottom row remain lowercase

#### Environment information
- FlorisBoard Version:  0.3.11-beta03
- Install Source: GitHub releases apk
- Device: LG G8x
- Android: 10

**Comment by patrickgold** [comment]
Thanks for pointing out that issue! I forgot to mark the "q" and "z" key to auto-capitalize themselves, thus they were always in lowercase. Above linked commit fixes this, will be released in beta04!
