### ISSUE TITLE
Keyboard Hangs

### ISSUE THREAD

**Issue by shom13** [florisboard/florisboard#812]
Its a very handy keyboard, but recently has started to hang, cause slowdowns. So much so its become unusable on my phone. On my older device it had to be removed to be able to type again. Using open keyboard until further notice

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, but the update may take 1-2 more weeks to be released.

**Comment by shom13** [comment]
Really glad to hear that. Looking forward to using floris board again. Thanks for taking note.

**Comment by Glitchy-Tozier** [comment]
Great, make sure to try out the next version (0.3.11) once it's released!  :)
