### ISSUE TITLE
Transliteration Tool

### ISSUE THREAD

**Issue by alphanerdgen** [florisboard/florisboard#818]
Don't know about other indic/non-latin languages, but at least in the case of Hindi, present day keyboards aren't built to give a smooth typing experience to the user. That's where the transliteration tool comes in handy. Using roman letters to produce non-latin words is very, very convenient.

Gboard has it, Samsung Keyboard has it, Indic keyboard has it. Hope Floris will also have it someday soon

App Version: 0.3.10
Repo: F-Droid

**Comment by Luensche** [comment]
Duplicate of #295?
