### ISSUE TITLE
Suggestions for Smart Bar

### ISSUE THREAD

**Issue by alphanerdgen** [florisboard/florisboard#819]
Please space out the icons in the space bar. They seem bunched up. Do consider reducing the size of those icons slightly. 

Also, one can easily access Settings and Emojis either by long-pressing on comma or tapping the utility key so why have them in smart bar too? Maybe replace them with some other options? (Hopefully alliteration tool in the future.)

App Version: 0.3.10
Repo: F-Droid

**Comment by patrickgold** [comment]
Quick action icons are relatively well distributed according to the available space in the latest beta release 0.3.14-beta13. Optimizations to that will come in the future. Closing this issue in an effort to clean up the list of open issues.
