### ISSUE TITLE
Preview the keyboard

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#82]
Hey Im just wondering if you could add a "preview" of the keyboard into the app so that we can see any changes without switching apps. I have seen this in other keyboards but not sure how easy it would be to do.

**Comment by patrickgold** [comment]
Thanks for your suggestion! There is already a keyboard preview in the Theme tab of Settings, which applies all the colors you select and lets you preview the keyboard.

What you ask for is a Settings wide preview, which is doable, but also needs some work simulating the core, to get some things to apply in the preview mode. I've put this on my todo list, as it is a really good idea, although I currently don't know when exactly it will be implemented yet!

**Comment by Kreuger** [comment]
Wow Im not sure how I missed that. I guess I just thought it was an image and scrolled down.

**Comment by patrickgold** [comment]
This feature has been implemented in above PR and is available as of 0.3.14-beta01. Thanks again for your suggestion!
