### ISSUE TITLE
Keyboard With Pc Options

### ISSUE THREAD

**Issue by TAGINARl** [florisboard/florisboard#823]
It would be really cool to add an option to put Pc keys on the keyboard, like Control, Alt, Tab, Shift, and many others

**Comment by another-sapiens** [comment]
Yes! Hacker's keyboard has it, and it would be especially nice for things like KDE Connect.

**Comment by patrickgold** [comment]
Thanks for your feature proposal! This has already been suggested in #229 and is planned for v0.5.0! Closing this as a duplicate.

**Comment by AdityaMH** [comment]
0.6.0 and still nothing

**Comment by lm41** [comment]
The versioning scheme was changed after patricks comment was written
