### ISSUE TITLE
Backspace deletes whole word and moves the cursor around

### ISSUE THREAD

**Issue by Kreuger** [florisboard/florisboard#828]
Hey guys. Tried looking through open issues and didnt see this. Sometimes while typing if I hit backspace to correct a typo, it will delete the whole word and the cursor will randomly move to another word so I end up typing in the middle of another word.

**Comment by Glitchy-Tozier** [comment]
What is your backspace set to?
(Especially the it's swipe-gesture)

**Comment by Kreuger** [comment]
Do you mean glide? I dont have that enabled. Delete key swipe left is set to delete characters precisely.

**Comment by Glitchy-Tozier** [comment]
> Delete key swipe left is set to delete characters precisely.

That's what I meant.
What is your Space-Swipe set to?

For me, something similar to this happens when I touch the delete-key while i swipe right on the space-bar.

**Comment by Kreuger** [comment]
Ive never changed these settings, never paid attention. Space swipe is normal.

**Comment by rancidfrog** [comment]
Is there a way to change sensitivity?
I am having this issue with backspace,
Whenever i click backspace or long press backspace it sometimes selects too much texts

**Comment by patrickgold** [comment]
@Kreuger what is the behavior of this in the latest stable release 0.3.14 (or 0.3.15-rc01 if you use the beta track)?

**Comment by Kreuger** [comment]
It seems to be just moving the cursor now. Although I did have it happen once a few days ago. It highlighted the word, then deleted it.

**Comment by Kreuger** [comment]
I think maybe the delete upon highlighting a word may be a feature?

**Comment by patrickgold** [comment]
Do you by any chance have a screen recording of the cursor moving around? Depending on how the cursor bugs out I may be able to pinpoint more exactly where the issue is coming from.

> Although I did have it happen once a few days ago. It highlighted the word, then deleted it.

That might sound like you accidentally select a word through the delete key swipe left feature. This can be caused by a too sensitive threshold setting. If you decrease the sensitivity of the gestures (adjust the thresholds for distance and velocity), does this mitigate this behavior?

**Comment by Kreuger** [comment]
I think thats exactly what I did. i just turned it off, I have no use for it.
