### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by TAGINARl** [florisboard/florisboard#829]
Hello, sorry, you are wasting time and also for the question, because it may seem very nosy on my part, but I would like to know, or have an idea, when FlorisBoard version 0.5.0 will be released?

**Comment by patrickgold** [comment]
As you can see, FlorisBoard is currently at version 0.3.10 (on Sunday or Monday evening on v0.3.11) and is going towards the v0.4.0 release. The biggest factor currently holding me back is the predictions part, which is required to be implemented well before v0.4.0 will be released. As for v0.5.0, that's a long way. A raw estimate based on how long v0.4.0 milestone took would be end of q3 2021 (so September). Note though that items planned for v0.5.0 are implemented much sooner often (e.g. like 0.4.2, 0.4.7 or whatever), so depending on what exactly you want to see implemented it can be soon or it can take longer.

**Comment by Glitchy-Tozier** [comment]
This issue sounds like it could be closed.

**Comment by patrickgold** [comment]
Yes, I agree.
