### ISSUE TITLE
what is frequency?

### ISSUE THREAD

**Issue by pokegamer5547** [florisboard/florisboard#831]
When adding words to dictionary, there's a option called "frequency" what does that do?

**Comment by patrickgold** [comment]
This value is a measure for how frequent a word is and is used to order the suggestions. Higher frequency means a more important word, less frequent means less important. The default value (128) is kinda the middle ground.

**Comment by pokegamer5547** [comment]
@patrickgold oh i see, now i get it. thankyou!
