### ISSUE TITLE
Keyboard starts blinking after system theme change

### ISSUE THREAD

**Issue by r5d** [florisboard/florisboard#835]
#### Short description

When the Android system theme changes from Light to Dark or vice-versa, the FlorisBoard keyboard starts blinking.

Changing the keyboard to the Android system's keyboard and then back to the FlorisBoard keyboard makes the blinking stop.

#### Steps to reproduce

1. Change the Android system theme from Light to Dark or vice-versa.
2. Open the FlorisBoard keyboard.
3. It starts blinking (the issue).

Here's a screen recording that illustrates the issue:

  https://ricketyspace.net/tmp/florisboard-blinking-issue.mp4

The recording also shows all the FlorisBoard settings.

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: F-Droid
- Device: Pixel 3a
- Android: [GrapheneOS][gos] (Android version 11, Build number [RQ2A.210505.002.2021.05.04.01][gos-bn])

[gos]: https://grapheneos.org/
[gos-bn]: https://github.com/GrapheneOS/platform_manifest/releases/tag/RQ2A.210505.002.2021.05.04.01

**Comment by patrickgold** [comment]
Thanks for your bug report! This bug was fixed in #669 and was released in beta04 (and confirmed to be fixed in beta05). For stable, this will be released in v0.3.11 either tomorrow or on Monday.
