### ISSUE TITLE
Language label on space bar is exceeding maximum boundaries

### ISSUE THREAD

**Issue by rex07** [florisboard/florisboard#837]
The language name on the apace bar is stretch over the border
Like this

![](https://i.imgur.com/gBubFJs.png)

**Comment by patrickgold** [comment]
Thanks for your bug report! Are you on v0.3.10 or v0.3.11-beta05? If you are still on v0.3.10, could you try out the new beta if this bug is still persistent?

**Comment by rex07** [comment]
I try the beta 5 it still here
![](https://i.imgur.com/nPzKZGR.png)

**Comment by rex07** [comment]
this bug is gone when i enable  Show utility key.

**Comment by patrickgold** [comment]
@rex07 What values do you have set for the keyboard height and font size multiplier?
