### ISSUE TITLE
Change language on the fly

### ISSUE THREAD

**Issue by Victor-Bo** [florisboard/florisboard#84]
I'd like to have a feature to change the language on the fly. For english, french, spanish and italian for example it isn't a problem as they use the same alphabet and there is no autocorrection but I often need to write russian so I'd like to be able to switch to cyrillic (when it will be available) without going in the settings each time

**Comment by patrickgold** [comment]
You can use the language switch button (or the swipe left/right action) to quickly change between languages without going to the Settings. Just define multiple subtypes, then the language button will show up in the keyboard (left of the space bar).

**Comment by Victor-Bo** [comment]
Ah yes it's true, I didn't see it, thanks !

**Comment by marioeljuga** [comment]
in case somebody is missing that button, go to settings>keyboard>show utility key

**Comment by fiordiconio** [comment]
@patrickgold Thank you, it helped me
