### ISSUE TITLE
Main extended pop ups characters are not always shown right above the key

### ISSUE THREAD

**Issue by PEPERSO** [florisboard/florisboard#845]
Hello !

At first I have to say that FlorisBoard is really good, and I appreciate your work a lot.

I have a little issue : I'm using the french azerty keayboard and when I long-press the `e` key, it show a pop up with different `e` accents, as expected, but the `é` which is the most used one in french is not right above the key, it is on top of all keys, but then more difficult to get to.
After a little digging on submitting new key boards, I've learnt that there are `main` and `relevant` extended pop ups. It seems to me that the `main` ones are placed as the first of the extended key list, instead of right on top of the pressed key. 
I wanted to fork the extended layout keyboard, but it would be more convenient I think, if the `main` extended pop up is placed just above the key

Is it clear enough ?

Thanks anyway for your work and efforts !

**Comment by PEPERSO** [comment]
I'm sorry, I can't show a screenshot, becaus I have to long-press and when I take the screenshot, it closes the keyboard

**Comment by patrickgold** [comment]
Thanks for your suggestion! Are you still using v0.3.10? If so, this was indeed an issue there, but the latest beta06 has the `é` as the main popup for `e`: https://github.com/florisboard/florisboard/blob/fdd7e60c1df69d21df6261faca3302553a3bec40/app/src/main/assets/ime/text/characters/extended_popups/fr.json#L27-L37

(Note that the code in master is pretty much always ahead of the latest release, if you want to search the code base for a specific release you can use the version tags)

v0.3.11 releases today evening (and takes a few days until it arrives in F-Droid and GPlay), which has this issue fixed if you don't want to use the beta version.

**Comment by patrickgold** [comment]
Stalled issue, will close it thus.
