### ISSUE TITLE
[SUGGESTION] Create Telegram Group/Matrix Room

### ISSUE THREAD

**Issue by hbarsaiyan** [florisboard/florisboard#846]
Hi all! I love this app very much and was thinking if a Telegram group/Matrix room could be created for Florisboard to better facilitate suggestions/bugs between the users and developer since not everyone is on Github. An unofficial Telegram group for Florisboard already exists at https://t.me/florisboard.

Thanks

**Comment by Glitchy-Tozier** [comment]
The issue that first brought up the idea wa #587  :)

You're welcome to join!

**Comment by hbarsaiyan** [comment]
Ok guys i will see you on the other side :)
