### ISSUE TITLE
"test" behind all the things I write

### ISSUE THREAD

**Issue by Victor-Bo** [florisboard/florisboard#85]
In the suggestions there is "test" behind all the things I write

![Screenshot_20201216-125919.jpg](https://user-images.githubusercontent.com/39555268/102346192-c0629180-3f9e-11eb-9709-99f5073dbcb2.jpg)

**Environment information**
- FlorisBoard Version: 0.3.0
- Install Source: F-Droid
- Device: Mi A2 Lite
- Android version, ROM: Havoc 10

Honestly I don't know the steps to reproduce it, I'll try things and update this issue

UPDATE: Same after cleaning the app storage

**Comment by D3SOX** [comment]
Suggestions are not yet implemented.
See https://github.com/florisboard/florisboard#feature-roadmap

There have been several issues describing this and even an issue with the exact same information: https://github.com/florisboard/florisboard/issues/24
Please search for possible issue duplicates before opening one and if you have more information provide it in the existing issue.

**Comment by Victor-Bo** [comment]
Oh sorry I'll check next time, sorry for the disturbing 😅
