### ISSUE TITLE
Color Adaption UI "bug"

### ISSUE THREAD

**Issue by FrameXX** [florisboard/florisboard#853]
Hi. There is an option inside FlorisBoard that makes adapt colors to app that is in foreground. This option works, however there's one small problem.
As background colors changes on every opened app, letters and other vectors switches between white and black to be visible on background (if background is darker letters are white if...).
But this is not a thing with vectors on emoji screen. No matter what, these vectors stays black (with light theme) all the time and are nearly invisible on some dark backgrounds as keyboard adapts to the app colors. (screenshot attached).

EDIT: This also applyes for clipboard history section.

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: GitHub

![Screenshot_20210511-133020~2](https://user-images.githubusercontent.com/56247804/117810907-3f16de80-b260-11eb-80dd-95236092254d.png)

**Comment by FrameXX** [comment]
I am making issue on github second time and I still don't know how to add labels. It needs to be hidden somewhere.

**Comment by Glitchy-Tozier** [comment]
The labels get added automatically depemding on what template you choose  ;)

For example, you (correctly) chose the bug-template and thus (bug) was added. If you had chosen the question-template, the label (question) would've been added.

![Screenshot_20210511-143144_GitHub.jpg](https://user-images.githubusercontent.com/59611881/117815522-dcc0dc80-b265-11eb-9148-eb90ae240c07.jpg)

**Comment by TheLoving** [comment]
I also have the same issue with color adapted theme.

**Comment by patrickgold** [comment]
This feature is not supported by FlorisBoard anymore, thus I am closing this issue as not-planned.

**Comment by Glitchy-Tozier** [comment]
@patrickgold That's unfortunate. Are there any plans to bring it back at some point of time?

**Comment by patrickgold** [comment]
No there are not atm because its a very difficult feature to get right, apps use all sorts of coloring schemes nowadays, we have Material 1, 2 and 3, then we have apps that are written in Jetpack Compose and thus often times leave the xml colors on the default colors, so yeah
