### ISSUE TITLE
[Bug] Number row impacts glide typing accuracy

### ISSUE THREAD

**Issue by Sykomaniac** [florisboard/florisboard#854]
On the latest beta, enabling the number row severely impacts the accuracy of glide typing.

It appears the calculation of which key is hovered over is incorrectly calculated as the key position is offset

**Comment by Glitchy-Tozier** [comment]
@X-yl Tell me if you want me to stop @-ing you.

Anyway, this could be of interest to you.

**Comment by X-yl** [comment]
> @X-yl Tell me if you want me to stop @-ing you.
> 
> Anyway, this could be of interest to you.

No it's fine haha, I love bugs ;)

I can confirm that this is reproducible. I'll try and fix it.
