### ISSUE TITLE
Gesture Typing While Capitalized

### ISSUE THREAD

**Issue by MathSteve22** [florisboard/florisboard#857]
I apologize if this is duplicate, but I did not see an issue raised for this. 

#### Short description
After recently updating and trying in a variety of apps (Signal, QKSMS, DuckDuckGo Browser, F-droid), I have not been able to gesture type while capitalized. I am able to turn off the capitalization and the gesture typing works as expected. However, while capitalized, after swiping, no word is created and none is suggested. The keyboard does not crash at all and the gesture trail is present, but no word is created.

#### Steps to reproduce
1. Open keyboard
2. Capitalize letter if not by default
3. Gesture type

#### Environment information
- FlorisBoard Version: 0.3.11-BETA06
- Install Source: Fdroid
- Device: Samsung S20 FE
- Android: Android 11

**Comment by keforbes** [comment]
This is fixed in v0.3.12 (#847).

**Comment by MathSteve22** [comment]
Thanks.
