### ISSUE TITLE
Crash when setting vibration to 0

### ISSUE THREAD

**Issue by castrik** [florisboard/florisboard#859]
#### Short description
Describe the bug in a short but concise way.

when we set the vibration strength or intensity to 0, it crashes
#### Steps to reproduce
1. Go to 'keyboard panel, key press'
2. Click on 'keyboard strength or duration(either works)'
3. Set it to 0
4. type any letter
5. See error

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-droid
- Device: Samsung Galaxy S21 Ultra
- Android: 11, One ui 3.1

**Comment by anurag-0-dart** [comment]
1+

**Comment by anurag-0-dart** [comment]
+1

**Comment by patrickgold** [comment]
Above PR fixes this issue, will be available in beta09!
