### ISSUE TITLE
Deletion doesn't work in some cases

### ISSUE THREAD

**Issue by angriness-sleek** [florisboard/florisboard#86]
**Environment information**
- FlorisBoard Version: 
- Install Source: F-Droid
- Device: Mi A2
- Android version, ROM: 10, LineageOS

Comparison of AnySoftKeyboard and FlorisBoard with respect to backspace/deletion:
1. Telegram
![ScreenRecord-2020-12-16-17-52-53](https://user-images.githubusercontent.com/62484249/102351311-200c6d00-3f9e-11eb-9bab-c795e686bfcb.gif)

Sorry, GitHub doesn't support big gif files so I'll just put a public Telegram link to a public channel post with the gif :(
2. uBlock Origin "my filters" editor:
https://t.me/testbuggy/2
3. a CodiMD instance hosted by someone: 
https://t.me/testbuggy/5

**Comment by D3SOX** [comment]
I'm not 100% sure but this might be related to https://github.com/florisboard/florisboard/issues/64

**Comment by angriness-sleek** [comment]
> I'm not 100% sure but this might be related to #64

Yes, i think so as well. It's along the same lines... but this behaviour is same with SimpleKeyboard and AOSP keyboard. Just AnySoftkeyboad can delete anything anywhere for some reason

**Comment by patrickgold** [comment]
@D3SOX good catch! The reason FlorisBoard deletion key is not recognized is that FlorisBoard tells the app to delete the previous character to be deleted, but as the input field is empty, there's nothing to delete. AnySoft Keyboard however seems to just send KeyEvent.KEYCODE_DELETE, which is basically a simulated hardware keypress. Personally I don't want to emulate a hardware keyboard, but I think I have to revert to this option as quite some apps rely on this hardware key...

**Comment by angriness-sleek** [comment]
> Personally I don't want to emulate a hardware keyboard

hmm, why's that?
> but I think I have to revert to this option

well, i guess you can give an option in settings maybe

**Comment by patrickgold** [comment]
> hmm, why's that?

Because Android provides an InputConnection with methods to commit text, set the cursor position, delete text, etc. If I emulate a hardware keyboard, I'm somewhat ignoring these methods provided by the InputConnection...

> well, i guess you can give an option in settings maybe

No, because the average user can't really distinguish what the difference would be and I want such a basic feature to work out-the-box. I will just emulate hardware key presses for these buttons and leave other text input as it is.
