### ISSUE TITLE
tap the correct character

### ISSUE THREAD

**Issue by castrik** [florisboard/florisboard#860]
first of all, I remember seeing a issue here similar to this, but I can't find it now, so I'm opening a new issue

when we are typing, and our finger swipes a little(by mistake), the keyboard registers the word we have swiped to eg. if i wanna type g, but my screen is oily or slippery and my finger slides to h, the keyboard will register h and not g 

I remember seeing a issue regarding if we wanna type space, sometimes the letters above space are registered by keyboard and I see that you have fixed that, but the issue is still here for letters

**Comment by Glitchy-Tozier** [comment]
Looking for #601?  ;)

**Comment by patrickgold** [comment]
Like @ Glitchy correctly linked, this is planned and detailed in #601. Will close this issue thus to help clean up the issue list a bit.
