### ISSUE TITLE
Number row bug!

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#863]
#### Short description
Bug when enable the top Number row with stabdard_kurdish layout this bug was appeard since version 3.11.beta02 the older versions is not have this number row BUG and in the latest 3.12(HotFix) version all other layouts works perfectly when number row enabled expext mine kurdish layout when enabled is shown like below screenshot

Number row: Enabled

![IMG_20210513_150328](https://user-images.githubusercontent.com/3160786/118124764-ba15fb80-b3fe-11eb-80c0-5df1f3a35b18.jpg)

The bug is with this layout when enabling number row but when i disable number row everything works like charm!

Number row: Disabled 

![IMG_20210513_150305](https://user-images.githubusercontent.com/3160786/118125017-1a0ca200-b3ff-11eb-8c42-e581a5223031.jpg)

#### Steps to reproduce
1. Go to 'app settings'
2. Click on 'Numbur row'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 3.12.HotFix 
- Install Source: Google PlayStore
- Device: Redmi Note 10
- Android: 11, MiUi 12 Stable

**Comment by patrickgold** [comment]
#1100 will be used to resolve this issue, as it contains more info about the same bug.
