### ISSUE TITLE
Hide keys border

### ISSUE THREAD

**Issue by Victor-Bo** [florisboard/florisboard#87]
I'd like a feature to hide keys border / shadows to make something like in GBoard 

![Screenshot_20201216-214054.jpg](https://user-images.githubusercontent.com/39555268/102404072-7a7deb80-3fe7-11eb-91fb-5b00682e8e53.jpg)

**Comment by D3SOX** [comment]
This is already possible if you set the key background color to the same color as the keyboard background color

![Screenshot_20201216-230041](https://user-images.githubusercontent.com/24937357/102411656-95099200-3ff2-11eb-827b-a3c3d8293d10.jpg)
![Screenshot_20201216-230055](https://user-images.githubusercontent.com/24937357/102411661-989d1900-3ff2-11eb-991f-adc889da7d05.jpg)

**Comment by Victor-Bo** [comment]
You set it to black so the shadow isn't visible but you can't set it to red or grey as the shadow will be visible

**Comment by D3SOX** [comment]
Oh, I did not know that. Sorry for the misconception

**Comment by patrickgold** [comment]
@Victor-Bo Thanks for your suggestion! Yes, currently the key shadow can't be removed (except you set the backgrounds to something dark and the same where the shadow is almost invisible). I'll add it to my todo list!

**Comment by Victor-Bo** [comment]
Perfect thanks! I know many people must tell you that but I love this app, some months ago I was looking for a good open source keyboard and couldn't find one and it's good to finally have one awesome. Also I think that this project as a lot of interesting things to come in the future. Good luck!
