### ISSUE TITLE
Copy/paste in smart bar when suggestions are enabled

### ISSUE THREAD

**Issue by hackills** [florisboard/florisboard#870]
Environment:
FlorisBoard version: 0.3.12

Steps to reproduce:
1. Enable Typing>Suggestions
2. Go to a website where context menu is disabled for text fields
3. Select text field

Actual result:
No way to 'select all/copy/paste' within text field.

Expected result: 
There should have been a way to 'select all/copy/paste' within the text field.

Suggestions:
This result could have been achieved if selection keyboard were enabled or if smartbar would somehow display 'select all/copy/paste' options even after enabling Typing>Suggestions.

**Comment by Glitchy-Tozier** [comment]
Just a small heads-up: If you select text, THEN the copy&paste bar will show up and replace the suggestions.

**Comment by hackills** [comment]
> Just a small heads-up: If you select text, THEN the copy&paste bar will show up and replace the suggestions.

True, but pages where context menu is disabled, selecting text is not possible.

**Comment by Glitchy-Tozier** [comment]
Where? (Except for password fields)

Also I'm not saying this freature shouldn't be proposed, I just wanted to share a trick with you that might make your life a little easier.  :)

**Comment by hackills** [comment]
> Where? (Except for password fields)
> 
> Also I'm not saying this freature shouldn't be proposed, I just wanted to share a trick with you that might make your life a little easier. :)

For example try the username field on this webpage:

https://ib.habibmetro.com/userlogin.hmb

**Comment by Glitchy-Tozier** [comment]
> For example, try the username field on this webpage:

I... honestly am not able to even highlight text in that input-area. :sweat_smile:.

**Comment by hackills** [comment]
> > For example, try the username field on this webpage:
> 
> I... honestly am not able to even highlight text in that input-area. 😅.

Yup that exactly is the issue 😄

**Comment by Glitchy-Tozier** [comment]
Somehow, FlorisBoard's selection suddenly seems to be a little buggy in general. When I visit Youtube in Firefox, delete-swipe gets REALLY buggy in the search-bar.

**Comment by MisterY** [comment]
> Just a small heads-up: If you select text, THEN the copy&paste bar will show up and replace the suggestions.

That's a cool tip. However, I'm using the bar mostly for the precise cursor movement, in which case it doesn't help.

**Comment by Glitchy-Tozier** [comment]
So, I found out that this has been proposed a couple of times (in #612 for example). Mind if we close this issue to keep the list clean?

**Comment by patrickgold** [comment]
Your proposal was already possible for some beta versions now, the above PR fixes some minor issues with this. When text gets selected, the primary actions get automatically expanded, in which you can configure that the clipboard cursor tools should be shown. Alternatively you can also have the clipboard cursor tools in the secondary Smartbar row, which takes up more space though.

This issue will be closed when above PR is merged.
