### ISSUE TITLE
Arrow Keys + Shift doesn't work repeatedly

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#871]
#### Steps to reproduce
1. Place cursor inside text
2. Hold down Shift
3. Click on one of the arrow-keys in the copy&paste-bar
4. Everything works fine (the next/previous letter gets selected) 
5. (Still holding Shift!!!!:) Press the arrow-key again
6. **See bug: Selection is lost.**

The process works if you release and re-press shift every time, but that shouldn't be necessary in my opinion.

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! This is a bug which has been introduced with the new KeyboardView in v0.3.11-beta02 I think. Will place it on my todo list to fix!

**Comment by Glitchy-Tozier** [comment]
Sooo.... I can't even get Shift+Spaceswipe to highlight text at all. Could it be broke in general?

**Comment by patrickgold** [comment]
I think any gestures which requires two pointers at once is messed, as they cancel out each other.

**Comment by Glitchy-Tozier** [comment]
Right, I forgot you mentioned that!
Looking forward to the fix :)

**Comment by pokegamer5547** [comment]
> Sooo.... I can't even get Shift+Spaceswipe to highlight text at all. Could it be broke in general?

I can't do that either even though it was mentioned as fixed in v0.3.11 beta3
