### ISSUE TITLE
1, 2, and 3 missing on Dvorak

### ISSUE THREAD

**Issue by MisterY** [florisboard/florisboard#872]
#### Short description

The numbers 1, 2, and 3 are missing as the options on long-press on ',. keys on Dvorak layout. 
They are also not displayed the way the other digits are.

 
![Screenshot_20210515-100139_Firefox_Beta](https://user-images.githubusercontent.com/462445/118352956-910f7b00-b564-11eb-8a14-2189f026b61c.png)

#### Environment information
- FlorisBoard Version: 0.3.11-beta04
- Install Source: GitHub
- Device: Xiaomi Mi 9T
- Android: LOS 17.1

**Comment by patrickgold** [comment]
Thanks for your bug report! This bug seems to be because hints currently only get applied to characters and not symbols within the character layout. Will place this one on my todo list!

**Comment by Kommynct** [comment]
I have also noticed that if the number row is enabled, the number hints stay even though they're then made useless, on gboard the top row hints become:

% \ |= [ 6 < > { }

Which makes a lot more sense. Should that be a separate bug report?

**Comment by patrickgold** [comment]
> Should that be a separate bug report?

No, because this has been reported several times and a new hint logic has been introduced in #606 (currently live on the master branch and will be released tomorrow with v0.3.13-beta01.)

**Comment by ostrya** [comment]
@patrickgold  if you don't mind, I can provide a fix. I somehow missed to check my changes when rebasing onto the new layout generation code. The basic issue is that now a key may actually be a variant or case selector, rather than a single key. I already noticed myself that this leads to strange effects.

**Comment by patrickgold** [comment]
@ostrya If you want, you can, would really appreciate it!
