### ISSUE TITLE
Move to a better place!

### ISSUE THREAD

**Issue by soheilkhanalipur** [florisboard/florisboard#873]
Unfortunately, I have to say that you have put this program in a bad place! GitHub!
This app deserves places like: Codeberg, Gitea, GitLab (Instances), and wherever better…
GitHub boycotts users, removes apps, and actually says "Whatever I want is going to be saved and whatever I don't need Is going to be deleted." The app has not paid attention to users' requests for RTL support for years, and says this is not a priority!
Free software should be free somewhere, which GitHub does not have!
Aren't these enough to leave GitHub?

**Comment by patrickgold** [comment]
GitHub has its flaws, that's unfortunately undeniable, though viewed in the bigger picture GitHub's advantages outweigh the disadvantages. GitHub is the main place where the developers are, FlorisBoard is also very welcoming to first-time contributors and these use GitHub more likely than any other platform combined. Also moving the project requires a lot of work and I rather use this time to improve FlorisBoard and add new features. The project's home is GitHub - this won't change except GitHub does something which requires action to be taken to move to a new platform, but this is very unlikely in the foreseeable future.

**Comment by PitiBouchon** [comment]
> GitHub is the main place where the developers are

That is because there are a lot of projects on GitHub
