### ISSUE TITLE
Emoji popups not showing on any emoji in the right-half of the emoji panel

### ISSUE THREAD

**Issue by sabzo** [florisboard/florisboard#877]
#### Short description
The emoji popups show in the first half of the emoji panel but not the second half. For example, 

#### Steps to reproduce
1. go on the "people" emoji category. 
2. Long press on any emoji on the first column.
3. Slide fingers across popup. (notice that this works)
4. Now go the last column on the same row.
5. Long press (this won't bring up emoji screen).
6. If emoji screen pops up, it will flash, but not remain constant enough for user to choose a popup.

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by sabzo** [comment]
This is 
version 0.3.12 
installed from Github
ran on Android emulator, and Blu S5
Android 8 and Android 10

**Comment by sabzo** [comment]
Issue also persists on latest master commit [ba3dc0178d12c653a4120c8112edbf21654f4265](https://github.com/florisboard/florisboard/commit/ba3dc0178d12c653a4120c8112edbf21654f4265)

**Comment by X-yl** [comment]
I wonder if this is a regression from my commit to reuse EmojiKeyViews. If it is I'll try and sort it out.

**Comment by sabzo** [comment]
Not sure, where you able to reproduce the bug @X-yl

**Comment by patrickgold** [comment]
Emoji popups are kind of broken and I am aware of it. This is because the popup manager is designed for the new layout logic but the emoji part uses the old one (with some improved mixins by @ X-yl, but I don't think that these worsened the situation). Thus the popup manager doesn't really know how to wok with the emoji keys.

My plan was to fix this issue when I completely rebuild the emoji UI logic in v0.5.0 development (and bring it on par with the text logic which works really well). Maybe I try to bridge the issue so the v0.4.0 release has working emoji popups, will see.

**Comment by X-yl** [comment]
@patrickgold Wait, how are you planning on rewriting the emoji logic? It seems like it might be quite time consuming to basically re-write and then maintain a scroll view implementation, not to mention all the recycler view caches and stuff. I understand flattening the view though.. maybe just combine each row into a single view and then have a RecyclerView of rows?

**Comment by patrickgold** [comment]
@X-yl Writing a custom scroll view is pretty easy to achieve and maintain, see the [`CandidateView`](https://github.com/florisboard/florisboard/blob/master/app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/CandidateView.kt) for instance. Of course, the candidate view does have very few items though and thus doesn't use a recycler view approach, which could make things complicated. I will see how I will approach this problem, the main goal is though to have each emoji in a properly measured `EmojiKey` object so the popup manager and other logic requiring it to be a descendant of a `Key` can work with it.

Another thing is that the outer UI needs a rewrite to support emoji search, the recents tab, etc. and probably flattening (although thanks to the recycler view you added is is muuuch better.

**Comment by anurag-0-dart** [comment]
any update....?
