### ISSUE TITLE
Keyboard switching function interferes with gesture

### ISSUE THREAD

**Issue by LongJohn-Silver** [florisboard/florisboard#88]
When I try to use the spacebar gesture to navigate between letters of a word most of the times I end up triggering the switching keyboards function, and sometimes even switching keyboards. It would be nice if the function could be disabled, or if it could take more time so that it doesn't trigger while doing this, or maybe something else could work, too.

**Comment by patrickgold** [comment]
Hmm strange I didn't come along this issue in testing. Do you accidentally trigger the switching on the language switch button or with the swipe left/right gesture? If it is the latter, you can disable those swipe gestures as a workaround.

**Comment by LongJohn-Silver** [comment]
I accidentally trigger while holding down the spacebar which asks me if I want to change my current keyboard. This is done by holding it down for a relatively long time, which makes it harder to use the left/right gesture to move between a word's letters, even more so when you need to obly move a word and you need more precision, therefore more time. 

I don't know if this is a problem that happens to me only but I feel like it is really hard to avoid and there is no option to disable it.

**Comment by patrickgold** [comment]
Ah I see the problem now. The only solution I see so far is that I add a toggle to disable the space bar long press menu. I can't really distinguish between a slight delay before moving left/right and long pressing, as the long press action triggers as long as you haven't moved at least the minimum distance threshold.

**Comment by Kreuger** [comment]
Id like to add that this affects me as well and the option to disable the switch would be much appreciated.

**Comment by LongJohn-Silver** [comment]
Good, I'm not crazy.

**Comment by patrickgold** [comment]
@LongJohn-Silver Above PR adds a preference which allows you to configure the space bar long press action. Setting this preference to `No action` will disable the input menu on the space bar, thus allowing you to properly move the cursor. Thanks again for reporting!

**Comment by LongJohn-Silver** [comment]
Thanks a lot to you, keep up the good work!
