### ISSUE TITLE
About section, longpress to copy version number

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#881]
Just a small feature which can be useful to some.
Allow user to copy version number on longpress in about section:
![](https://i.imgur.com/oJge7L3.png)

**Comment by patrickgold** [comment]
Thanks for your suggestion, is a small but nice addition to the about section. Placing on my todo list!

**Comment by Luensche** [comment]
Since I was looking for a good first issue, I will have a try.
