### ISSUE TITLE
Turkish QWERTY layout is wrong

### ISSUE THREAD

**Issue by dvrnynr** [florisboard/florisboard#882]
In Turkish there is two types of letter i. One with a dot (İ, i) and one without (I, ı). After the update 0.3.11 now capital İ is replaced with I and there is two I letters.

Btw is it possible to edit accent layout? If so maybe i can help. Because there is a lot of unused stuff.

**Comment by Luensche** [comment]
Does the description from #793 perhaps already help you?

**Comment by dvrnynr** [comment]
I have edited the .json file and created a pull request #909 

But i still have no idea about how to assign lower case "i" to upper case "İ" and lower case "ı" to upper case "I"

**Comment by patrickgold** [comment]
#1091 fixed the dotless i bug already in beta07, but I forgot to link it, sorry. Will close this issue thus.

As for the other unused popup mappings, #909 will still handle it.
