### ISSUE TITLE
Switching between languages/subtypes in spacebar

### ISSUE THREAD

**Issue by MohammedALShimmary** [florisboard/florisboard#886]
#### Short description
I've added a gesture to slide between subtypes in the spacebar but it is unusable and super glitchy.

#### Steps to reproduce
1. Go to 'Gestures'
2. Click on 'Spacebar swipe left' or  'Spacebar swipe right'
3. choose 'Switch to next subtype' or 'Switch to previous subtype'
4. Go ahead and test in typing..
5. See the glitches/bug

#### Environment information
- FlorisBoard Version: 0.3.12  
- Install Source: F-Droid 
- Device: Nubia RedMagic 5G 
- Android: 11, Stock

**Comment by patrickgold** [comment]
Thanks for your bug report! This is caused because currently all gestures for space bar left/right are repeating and triggered on move (designed to work for the arrow movements), but I agree if set to gesture actions like switching subtypes this is suuuuper glitchy. Placing on my todo list!
