### ISSUE TITLE
Russian language issues 

### ISSUE THREAD

**Issue by TMS-Namespace** [florisboard/florisboard#889]
The word suggestions in case of Russian language  goes crazy,  particularly,  typing first character in Russian,  gives you suggestings in Russian, but after typing second character, it start to give you suggesting in english, not sure why..

Also, would ask to slightly increase suggests fonts size, and reduce spacing between words.

And, thx for giving us best open source keyboard, finally.

**Comment by opusforlife2** [comment]
This is what the option says: "currently regardless of the selected subtype the dictionary language is English (US)".
