### ISSUE TITLE
Help needed with adding esperanto keyboard layout

### ISSUE THREAD

**Issue by jeremiah-miller** [florisboard/florisboard#89]
Hello, I'm learning esperanto and I'd like to be able to use florisboard instead of the aosp keyboard or [anysoftkeyboard](https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.esperanto&hl=en_US&gl=US). I know you want to hold off on adding layouts till it's more stable and it's totally ok if you decide to stay firm on that, but if you are ok with adding it early I did my best to make a layout json file however gradle wasn't letting me install the debug app on my phone (`> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package dev.patrickgold.florisboard signatures do not match previously installed version; ignoring!`) so I don't know if I did it right. I based the code values on the furthest right number in the table at https://en.wikipedia.org/wiki/Esperanto_orthography#Unicode

```
{
  "type": "characters",
  "name": "Esperanto",
  "direction": "ltr",
  "arrangement": [
    [
      { "code":  349, "label": "ŝ" },
      { "code":  365, "label": "ŭ" },
      { "code":  101, "label": "e" },
      { "code":  114, "label": "r" },
      { "code":  116, "label": "t" },
      { "code":  285, "label": "ĝ" },
      { "code":  117, "label": "u" },
      { "code":  105, "label": "i" },
      { "code":  111, "label": "o" },
      { "code":  112, "label": "p" }
    ], [
    ], [
      { "code":   97, "label": "a" },
      { "code":  115, "label": "s" },
      { "code":  100, "label": "d" },
      { "code":  102, "label": "f" },
      { "code":  103, "label": "g" },
      { "code":  104, "label": "h" },
      { "code":  106, "label": "j" },
      { "code":  107, "label": "k" },
      { "code":  108, "label": "l" }
      { "code":  309, "label": "ĵ" },
    ], [
      { "code":  122, "label": "z" },
      { "code":  265, "label": "ĉ" },
      { "code":   99, "label": "c" },
      { "code":  118, "label": "v" },
      { "code":   98, "label": "b" },
      { "code":  110, "label": "n" },
      { "code":  109, "label": "m" }
      { "code":  293, "label": "ĥ" }
    ]
  ]
}
```

**Comment by patrickgold** [comment]
Thanks for contributing to FlorisBoard, I really appreciate this!

> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package dev.patrickgold.florisboard signatures do not match previously installed version; ignoring!

Based on this Exception, it seems that you've installed a release version of FlorisBoard (either from GPlay, F-Droid or GitHub). When installing a debug version on top of a release version, the application signatures don't match and Android refuses to install the debug version on your system. On some phones a dialog appears which asks if the release version should be removed, on some you have to manually uninstall the release version before installing the debug version. Then the installation of the debug version should work without a problem.

While not the cause of this Exception, you have misplaced some commas in your JSON file, which will later on cause an Exception thrown by Moshi (the JSON parser).

Hope I could help! :)

**Comment by jeremiah-miller** [comment]
ah gotcha, I figured it was something like that, thanks for confirming! It might be a good idea to make the debug build use a different signature so they can be installed side by side, especially when it reaches a more stable version and more options are added, so people can contribute without resetting their settings in the released version of the app. 

And thanks for that catch with the commas!

**Comment by jeremiah-miller** [comment]
I should be able to help translate the rest of the app to Esperanto in a few months too :)

**Comment by patrickgold** [comment]
> It might be a good idea to make the debug build use a different signature so they can be installed side by side, especially when it reaches a more stable version and more options are added, so people can contribute without resetting their settings in the released version of the app.

Thanks for the idea. I've looked up some methods to install a release and debug version at once on a device and will probably work with release types and application suffixes for non-production builds.

> I should be able to help translate the rest of the app to Esperanto in a few months too :)

Thanks for considering to translate FlorisBoard into Esperanto! I've added it to the list of translatable languages in Crowdin. :)

**Comment by jeremiah-miller** [comment]
I know the [KISS launcher](https://github.com/Neamar/KISS) does that, if you're looking for any examples

**Comment by patrickgold** [comment]
I've taken your advice and added a separate debug build id, like the KISS launcher does. This allows FlorisBoard to be installed on a single device in both a debug and release version. Should be available when I merge the feat-smartbar-rework branch into master.

**Comment by jeremiah-miller** [comment]
#90 merged
