### ISSUE TITLE
Floris not part of keyboard selection 'cycle'

### ISSUE THREAD

**Issue by opusforlife2** [florisboard/florisboard#890]
#### Short description

Some keyboards have a keyboard switcher key that cycles between the enabled keyboards directly instead of showing the "Choose input method" dialog. For some reason, Floris's turn never comes up in this cycle. Floris is being bullied. :(

There is a clear way to tell that Floris isn't being considered for switching, which I've listed in the steps below.

#### Steps to reproduce
1. Enable only Google Keyboard (so sorry about this).
2. Enable any one other keyboard other than Floris.
3. Google Keyboard shows the keyboard switcher next to the space bar.
4. Try this with some other keyboards. It keeps showing the keyboard switcher.
5. Now enable only Floris. Suddenly, Google Keyboard shows an emoji switcher in place of the keyboard switcher! Moreover, long pressing on the space bar, which should bring up the "Choose input method" dialog, does nothing.

#### Alternate STR

Thankfully, after writing the steps above, I found an alternative that doesn't force you to install proprietary crap:
1. Enable only kboard (https://f-droid.org/packages/com.adgad.kboard) (https://github.com/adgad/kboard).
2. Enable any one other keyboard other than Floris.
3. The keyboard switcher in kboard successfully switches to the other keyboard.
4. Try this with some other keyboards. The keyboard switcher keeps working.
5. Now enable only Floris. Suddenly, kboard's keyboard switcher stops working! Now there is no way to switch to Floris again except going into OS settings.

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Device: Xiaomi Mi 5
- Android: 10, LOS 17.1

**Comment by patrickgold** [comment]
> Floris is being bullied. :(

Oh no :(

Jokes aside, this is an issue because FlorisBoard's `method.xml` is not configured correctly and thus the flag required for FlorisBoard to be included in the keyboard cycle is missing. This will be fixed in #876 and released tomorrow in v0.3.13-beta01.

I just tested this and if only v0.3.12 is enabled besides any other keyboard it gets ignored. for the current debug build of #876 all keyboards which support keyboard cycling detect FlorisBoard, with the exception of Gboard, which ignores all other keyboards on my device.

**Comment by opusforlife2** [comment]
> with the exception of Gboard, which ignores all other keyboards on my device.

Interesting. So Google made the app even more irritating. As stated in the OP, Google Keyboard only ignores Floris. It detects and readily switches to all other keyboards.

Welp, Google being Google, I guess.
