### ISSUE TITLE
Attach sha256 checksums for APK releases on GitHub

### ISSUE THREAD

**Issue by pokegamer5547** [florisboard/florisboard#893]
I love having beta updates of florisboard as i get faster fixes and features. But im a little bit scared because of apk installing. i know i can use fdroid but it only gets update once in a month making me wait so long. I think it wouldbe great if we can verify the apks of florisboard via hash like sha256 or something. Sorry i know its a bit too much to ask for since it causes more delay but it would be great for people like me who want to test beyata updates ithout worrying about what if apk got tampered.

**Comment by patrickgold** [comment]
Thanks for your suggestion! This is definitely a good idea and especially as I am on Linux pretty easy to accomplish. I will try to begin attaching the sha256 checksums tomorrow with the v0.3.13-bta01 release.

**Comment by pokegamer5547** [comment]
Wow that's really great! thankyou so much :)  should i close this issue now or keep it open?

**Comment by patrickgold** [comment]
Please keep it open! I will close this issue automatically once I've released the first APK with an sha256 sum (should be tomorrow).

**Comment by pokegamer5547** [comment]
Oh ok then! Thanks!

**Comment by patrickgold** [comment]
The newest v0.3.13-beta01 release contains an sha256 checksum attached. Will close this issue thus. Thanks again for your suggestion!
