### ISSUE TITLE
Cursor sometimes moves to another line itself.

### ISSUE THREAD

**Issue by pokegamer5547** [florisboard/florisboard#894]
Well thia is hard to explain but i will try my best. sometimes when typing in issue box or reply box in github the cursor moves up to first line itself. Idk what causes it  but it happens a lot.
Stepa to reproduce (not sure exactly but thia is its pattern i noticed)
Open github from firefox and try to type long text in github (in issue or reply box) and keep typing and then try to do something else and continue typing again. And then it moves the cursor itself to first line when we entee any letter. 
Im  sorry i know this data isn't enough but if i find it again i will try to reproduce it.

**Comment by patrickgold** [comment]
Thanks for your bug report!

I tried to reproduce this bug but was unable to. If possible could you try to find out if this issue also occurs with other keyboards as well or if this issue occurs outside of Firefox? Sometimes the textbox implementation of Firefox is a bit messy and I want to make sure its a bug within FlorisBoard so I can narrow it down and fix it.

**Comment by pokegamer5547** [comment]
Oh i see, i understand its alright. I will try to see if i  can reproduce this bug in my note taking app and report back.

**Comment by Glitchy-Tozier** [comment]
Could this be an accidental activation of gestures? What happens if you disable all gestures?

**Comment by pokegamer5547** [comment]
> Could this be an accidental activation of gestures? 
What happens if you disable all gestures?
Idk, tbh this bug is happening so rarely that i can't find a way to reproduce it so until i find out how to trigger this bug i can't test this with gestures disabled (as i usually keep them enabled)

**Comment by keforbes** [comment]
I had a similar issue where glide typing in a text area would sometimes cause the cursor to jump all over the place.  I had configured the gestures on space bar to move cursor left/right on swipe left/right and I think if my glide happened to cross over the space bar it triggered those gestures.  I disabled those space bar gestures since I don't really use them (I was just playing with florisboard's settings) and I haven't seen the problem since.  That might be relevant to you, not sure.

**Comment by pokegamer5547** [comment]
> I had a similar issue where glide typing in a text area would sometimes cause the cursor to jump all over the place. I had configured the gestures on space bar to move cursor left/right on swipe left/right and I think if my glide happened to cross over the space bar it triggered those gestures. I disabled those space bar gestures since I don't really use them (I was just playing with florisboard's settings) and I haven't seen the problem since. That might be relevant to you, not sure.

Your issue seems very similar to mine. But i don't think mine was caused by gestures because i wasn't reaching the space bar nor using any gestures when i was typing. and for me it immediately jumps to first line first word or random word in first line when i type any letter. I still can't figure out how to reprpduce it.

**Comment by MisterY** [comment]
> Open github from firefox

I get this quite a lot. However, I didn't think that the keyboard was the problem. Switching the keyboards when this happens doesn't fix the issue so I assume that Firefox is the culprit here. 
There are other, similar, problems when using SwiftKey auto-type, where the space is iinserted (or not) after a word, etc. that also happen in FF textboxes.

**Comment by pokegamer5547** [comment]
> > Open github from firefox
> 
> I get this quite a lot. However, I didn't think that the keyboard was the problem. Switching the keyboards when this happens doesn't fix the issue so I assume that Firefox is the culprit here.
> There are other, similar, problems when using SwiftKey auto-type, where the space is iinserted (or not) after a word, etc. that also happen in FF textboxes.
> 
> Edit: I don't use any gestures or auto-type in FlorisBoard.

Ig so too maybe it's firefox fault, i'm still unable to reproduce this issue so ig maybe for now jt's better to assume it's firefox causing. But i will wait and see it can somhow find a way to reproduce it again.

**Comment by Duvio** [comment]
The cursor weirdly jumps around when you press the soace bar fast multiple times consecutively, it is easy to reproduce, i will open a new issue for this

**Comment by pokegamer5547** [comment]
> The cursor weirdly jumps around when you press the soace bar fast multiple times consecutively, it is easy to reproduce, i will open a new issue for this

Oh i see, this bug looks bit simlar to mine but in my case it just always jumps to first word whenever i type something. Btw also want to mention that i'm unable to reproduce my bug anymore, maybe it 's fixed after latest beta? I'm not sure.
