### ISSUE TITLE
Sometimes Floris doesn't open in one handed mode

### ISSUE THREAD

**Issue by opusforlife2** [florisboard/florisboard#896]
#### Short description

The keyboard usually opens correctly, but sometimes it opens with full width and height, and sometimes it opens with full width but shortened height. It is easily fixed by tapping the Back button to close the keyboard and then opening it again.

#### Steps to reproduce
1. Enable one handed mode.
2. Do some random things.
3. Tap on a text field.
4. Sometimes, the keyboard will open with full width and height, and sometimes it will open with full width but shortened height.

Closing the keyboard by tapping the Back button and then opening it again always fixes the issue and opens it in one handed mode as expected.

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Device: Xiaomi Mi 5
- Android: 10, LOS 17.1

**Comment by patrickgold** [comment]
Thanks for your bug report! Just tried this one out and it indeed bugs out. I think it's because I forget to properly update the status of the one-handed mode, am not entirely sure though.

**Comment by patrickgold** [comment]
Above commit fixes the one-handed panel issue (it was incorrectly measured sometimes and thus its width was 0). Will be released in v0.3.13-beta02!
