### ISSUE TITLE
Import language file

### ISSUE THREAD

**Issue by LuukHenk** [florisboard/florisboard#898]
Hi,

I'm trying to add my language (Dutch) to the personal dictionary.
I've build a .clb file of the dutch dictionary, which is in the same format as when a florisboard personal dictionary file is exported.
Importing a small part of my .clb file to my personal florisboard dictionary works fine.
However I can not import files bigger than 2.4kB, and the complete Dutch dictionary I'm trying to import is 4.4 MB. 
Is there a way to add the complete  dictionary?
I can share the .clb file if needed.

And thanks for letting me use this open source keyboard!

cheers,
LuukHenk

**Comment by patrickgold** [comment]
Hi LuukHenk,

this is because the import logic has a very strict limit on the file size, this comes from the times when I added theme import/export and it crashed for files about ~10MB. I think I limited to 512kB. For dictionaries this limit is intended to be at ~2MB, but I just looked the value up and it is 2kB :facepalm:. I can raise the limit to 2MB, even try to go for 5MB but I have to ensure that this works fine on all devices without crashing. Will experiment with this now and push a fix for this.

Cheers,
Patrick

**Comment by patrickgold** [comment]
Good experimented a bit and 6Mb seems to work, will test this out on some other devices as well before pushing.

**Comment by LuukHenk** [comment]
Thanks a lot, let me know!

**Comment by hakkikaancaliskan** [comment]
Could you please tell me how did you build clb file, i wanna do it for Turkish as well

Thanks!

**Comment by LuukHenk** [comment]
@hakkikaancaliskan I downloaded a wordlist from github (https://github.com/OpenTaal/opentaal-wordlist in my case), and wrote a small python script (see below) to format the wordlist to .clb. 

```
import os

# Saving and loading directory
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_FILE = os.path.join(BASE_DIR, "wordlist.txt")

word_line_format = "w={};f=250;l=nl" # The format used in the clb file (l=language)
words = [] # The formatted word list

with open(INPUT_FILE, "r") as f: # Open input file
    for line in f.readlines(): # Loop over each word and format

        # Spaces are not allowed, so we remove these
        line = line.strip()
        line = line.replace(" ", "-")

        # Format using the word line format
        words.append(word_line_format.format())


# The clb file needs a header
head = "dictionary=30;date=1621256341514;generated-by=luuk;version=1"
out_file = open(os.path.join(BASE_DIR, "out", "my_dict.clb"), "w") # Open output file

# Write the head and the words to the file
# (Make sure that all the words start with a single space)
out_file.write(head + "\n " + "\n ".join(words))
out_file.close()
```

**Comment by hakkikaancaliskan** [comment]
Awesome, thanks heaps!

**Comment by khlsvr** [comment]
@LuukHenk  I'm trying to run your python script, but I get an error. Wonder if I'm doing something wrong. The txt_to_clb.py has the content from your code and I downloaded thist file https://raw.githubusercontent.com/OpenTaal/opentaal-wordlist/master/wordlist.txt for the wordlist.txt.

```
$  python3 txt_to_clb.py 
Traceback (most recent call last):
  File "/home/onla/mnt/languages/suomi/txt_to_clb.py", line 18, in <module>
    words.append(word_line_format.format())
IndexError: Replacement index 0 out of range for positional args tuple
```

**Comment by ronajon** [comment]
got the same error, and fixed it by modifying line 18 to 
words.append(word_line_format.format(**line**))

this raised another error, my dict.clb file now is >10MB, so larger than the max dictionary sizze of 6mb


> @LuukHenk I'm trying to run your python script, but I get an error. I guess the problem is with the .format() function and the curly braces as someone answers here https://stackoverflow.com/a/67013888/13977393 ? I'm not sure what should I do though to fix it. The txt_to_clb.py has the content from your code and I downloaded this file https://raw.githubusercontent.com/OpenTaal/opentaal-wordlist/master/wordlist.txt for the wordlist.txt.
> 
> ```
> $  python3 txt_to_clb.py 
> Traceback (most recent call last):
>   File "/home/xxx/txt_to_clb.py", line 18, in <module>
>     words.append(word_line_format.format())
> IndexError: Replacement index 0 out of range for positional args tuple
> ```
> 
> I'm also interested in english dictionaries. Anyone know a good one with size 1-6MB and the format like the dutch dictionary (or ready made .clb)?
> 
> edit:
> 
> Or.. can one import similarly those .dict files the below tools generate? https://github.com/florisboard/dictionary-tools Although I'm not sure I would be able to pull that work off, seems maybe complex and I might run into problems. I'm interested in adding/importing a finnish and english dictionaries if someone can help me out. The wordfreq that dictionary-tools is partly based on seems to support finnish but if not from there here I can download finnish in so that this one python script could generate the clb file https://github.com/hugovk/everyfinnishword

**Comment by LuukHenk** [comment]
@khlsvr, ah yes I forgot add the line in the formatter (as @ronajon said)  `words.append(word_line_format.format(**line**))`. Hope that that solves the problem

**Comment by LuukHenk** [comment]
@ronajon I found that the dictionary of https://raw.githubusercontent.com/Speedbuilder/NL-dictionary-file/master/dutch.dic is a lot smaller but also contains many words (instead of https://github.com/OpenTaal/opentaal-wordlist). With this list you end up at ~4MB

**Comment by LuukHenk** [comment]
I also added the frequency of the words now

**Comment by khlsvr** [comment]
cool it did work. Having used it for a while now it's not very useful though as I have every word with the same frequency value. Also without the next word prediction you almost never get good suggestions on the suggestion bar but oh well, at least there's something :)

**Comment by AmroLouwe** [comment]
Anybody knkws where i can find the dutch language pack download page?  For some reason i cant find any languages hers except for chinees.  
@luukhenk zou jij jouw nederlandse language pack kunnen/willen delen?
