### ISSUE TITLE
[Regression] Buttons on the Smart bar don't change color in Dark mode

### ISSUE THREAD

**Issue by Huy-Ngo** [florisboard/florisboard#906]
#### Short description
![Screenshot_2021-05-18-18-54-46-645_com keylesspalace tusky test](https://user-images.githubusercontent.com/19296926/118646773-d359e600-b80a-11eb-9d99-50c3c35cb73e.jpg)
In a recent update (0.3.12) the icons on smart bar and the language button are black, which is not visible in dark mode

#### Steps to reproduce
1. Switch to Dark mode
2. See error

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source:  f-droid
- Device:  Xiaomi Redmi Note 7
- Android:  10

**Comment by patrickgold** [comment]
Thanks for your bug report! During testing this issue occurred on Samsung phones but I then added a fix which has resolved it there. It seems that this bug is still present on Xiaomi devices though, interesting. I will see how I can fix this.

**Comment by deepu2** [comment]
@Huy-Ngo Try seeing if system dark mode is turned on for florisboard in Settings > Display > More dark mode options > and turn off toggle for florisboard

**Comment by Huy-Ngo** [comment]
Thanks, that worked. But I think it's a workaround and this issue remains.

**Comment by deepu2** [comment]
I guess it's more of xiaomi's issue, I face this issue with almost every app I install that comes with dark mode. 

But if there is a fix from the app side then yeah issue still remains.

**Comment by Huy-Ngo** [comment]
> I guess it's more of xiaomi's issue, I face this issue with almost every app I install that comes with dark mode.

Yep, Xiaomi devices seem to always introduce weird behaviors for dark
mode, especially in foss apps for some reason. But Xiaomi's
modification is closed source so we'd have to work around it.

> But if there is a fix from the app side then yeah issue still remains.

The problem didn't appear before so I suppose there must be a fix, but
since it's a purely cosmetic bug and there's a workaround I wouldn't
urge anyone to fix this.

**Comment by staticdev** [comment]
Don't know if it is a different issue @patrickgold, but on dark mode (triggered by energy saver) I see the number buttons dark and they still work BTW:

![Screenshot_20211220-160759](https://user-images.githubusercontent.com/1446633/146808478-d67bc6ce-38c3-44c4-a793-ec3e5d5594ca.png)

**Comment by patrickgold** [comment]
These UI issues should be fixed with the new UI library I introduced in the development cycle for 0.3.14 (latest beta beta13 for it), at least reports from other users who also faced similar issues reported it. Thus I will close this issue.

Should this still be a thing with the latest beta release then please report it in this thread!  
(please check first with a default theme if you are using a custom theme, because the theme API is not stable yet and thus coloring issues can occur with older custom themes)

**Comment by staticdev** [comment]
@patrickgold do you have a plan to release 0.3.14 to public soon?

**Comment by patrickgold** [comment]
I need to make the 0.3.14-rc02 (release candidate 2) release first, for this release I need to fix a few things still. But it shouldn't take too long anymore, it will be anywhere between this Sunday and next Wednesday then 0.3.14 will release on stable.

**Comment by staticdev** [comment]
Tested, it works, thanks!
