### ISSUE TITLE
Word deletion mode (after gliding) stays active on cursor move

### ISSUE THREAD

**Issue by pierstitus** [florisboard/florisboard#916]
#### Short description
After gliding a word, a single backspace press deletes the whole word. However if you move the cursor by tapping on the screen the word deletion mode stays active and backspace will delete the word were the cursor is moved to. In v0.3.10 this was also the case when moving the cursor by swiping the spacebar or when typing single characters. In v0.3.12 it's fixed for those two cases, but moving the cursor by tapping the screen still leaves the word deletion mode active.

This bug is also mentioned in https://github.com/florisboard/florisboard/issues/582#issuecomment-845971939

#### Steps to reproduce
1. Glide a word
2. Tap on the screen to move the cursor to another word
3. Press backspace, this removes the word, while it should remove a single letter like when the cursor is moved by swiping the spacebar.

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid/GitHub

**Comment by Glitchy-Tozier** [comment]
Present in v0.3.13, beta 6.
@X-yl May I add you again?

**Comment by X-yl** [comment]
You know what, why not! I'll make a PR :)

**Comment by Glitchy-Tozier** [comment]
Yay, awesome!  :smile:

**Comment by patrickgold** [comment]
Above linked commit/PR fixes the issue, the phantom space did not reset for unrelated selection updates, which caused this issue to occur. Will be released in 0.3.16-beta03, thanks for reporting this issue!
