### ISSUE TITLE
glide typing accuracy impacted by "number row" setting

### ISSUE THREAD

**Issue by khimaros** [florisboard/florisboard#917]
#### Short description
when the "Number row" setting is enabled, glide typing accuracy drops precipitously.

for example, "thank" consistently registers as "gram" or "guam" without "thank" even as a suggested word. i can reproduce this difference in accuracy consistently. disabling the "Number row" setting suddenly improves my accuracy.

it's possible that this is due to visual perception. eg. having the additional row above causes me to start my swipes slightly lower on the keyboard or makes me feel that my finger is higher than it actually is. 

@X-yl for visibility.

#### Steps to reproduce
1. disable "Number row" in keyboard settings
2. glide type the word "thank" ten times and note the accuracy
3. enable "Number row" in keyboard settings
4. glide type the word "thank" ten times and note the accuracy
5. compare the accuracy of each

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Device: Pixel 3
- Android: RattlesnakeOS (AOSP) 11.0

**Comment by X-yl** [comment]
Thanks for your bug report! 

However this was already reported in #854 and has been fixed in the latest beta :)

A workaround until it hits stable is to restart florisboard after changing the number row visibility.

**Comment by khimaros** [comment]
thank you for the quick fix! and thank you for the workaround!
