### ISSUE TITLE
Not getting word suggestions on signed APK or debug apk

### ISSUE THREAD

**Issue by rayavarapuvikram1** [florisboard/florisboard#919]
Hello, I am a begginer in android development. I have forked this repository and build APK (tried both DEBUG and RELEASE) from android studio, when I am typing I am not getting word suggestions even after turning on the option. anyone, please help.

**Comment by pokegamer5547** [comment]
Latest beta doesn'tprovide word suggestions for anything except inline suggestions and dictonary. Suggestions are currently in rework again.

**Comment by rayavarapuvikram1** [comment]
I need how to set up in-line suggestions?
it's okay even if it is older version

**Comment by pokegamer5547** [comment]
> I need how to set up in-line suggestions?
> it's okay even if it is older version

Inline suggestions are like autofill suggestions which requires android 11 and your password manager to implement a specific API only available for android 11.

**Comment by rayavarapuvikram1** [comment]
![Uploading Screenshot_2021-05-22-18-53-07-393_com.android.mms.jpg…]()

I am sorry I need these.

**Comment by pokegamer5547** [comment]
> I am sorry I need these.
> ![IMG_20210522_185623](https://user-images.githubusercontent.com/46016457/119228180-6ce90680-bb2f-11eb-8b89-6d5a0627600b.jpg)

Oh you meant only word suggestions😅 sorry about that. Currently dev is working on re-implementing suggestions again and he will also gonna implement next word suggestions with it. You can however use latest stable build over beta for suggestions.

**Comment by rayavarapuvikram1** [comment]
> > I am sorry I need these.
> > ![IMG_20210522_185623](https://user-images.githubusercontent.com/46016457/119228180-6ce90680-bb2f-11eb-8b89-6d5a0627600b.jpg)
> 
> Oh you meant only word suggestions😅 sorry about that. Currently dev is working on re-implementing suggestions and he will also gonna implement next word suggestions with it. You can however use latest stable build over beta for suggestions.( which doesn't have next word suggestions)

If I revert to "Release v0.3.12" commit can I get those suggestions through APK compiled through android studio

**Comment by pokegamer5547** [comment]
> > > I am sorry I need these.
> > > ![IMG_20210522_185623](https://user-images.githubusercontent.com/46016457/119228180-6ce90680-bb2f-11eb-8b89-6d5a0627600b.jpg)
> > 
> > 
> > Oh you meant only word suggestions😅 sorry about that. Currently dev is working on re-implementing suggestions and he will also gonna implement next word suggestions with it. You can however use latest stable build over beta for suggestions.( which doesn't have next word suggestions)
> 
> If I revert to "Release v0.3.12" commit can I get those suggestions through APK compiled through android studio

Yeah ig you should be able to get it. Suggestions(without next word) were working in that release.

**Comment by rayavarapuvikram1** [comment]
Thank You @pokegamer5547  It worked. Closing this issue.
