### ISSUE TITLE
Please add key shadows like in Gboard

### ISSUE THREAD

**Issue by andrew-47** [florisboard/florisboard#921]
Key shadows would make an awesome addition to this keyboard. Gboard has this implemented and it really adds some depth to each key. I've attached screenshots of how it looks in Gboard compared to Florisboard(3.12)

Florisboard:
![Screenshot_20210522-120130_Lawnchair (2)](https://user-images.githubusercontent.com/82853945/119233266-3e9b0500-baf6-11eb-906f-dca3b8ba26db.jpg)

Gboard:
![Screenshot_20210522-120141_Lawnchair (2)](https://user-images.githubusercontent.com/82853945/119233279-4a86c700-baf6-11eb-88ee-83d7c7fb7f23.jpg)

**Comment by patrickgold** [comment]
Thanks for your suggestion! Above linked PR fixes this issue, will be released in v0.3.13-beta02 in the next few days!

**Comment by patrickgold** [comment]
Note: see #941 why I've moved key shadow support to v0.3.13-beta03. As cool as shadows are the current implementation causes slowdowns on older devices and I cannot release this to all my beta testers without trying to improve the performance.

**Comment by ggdorman** [comment]
It seems like v0.3.13-beta03 adds a key border, but not shadows?

**Comment by patrickgold** [comment]
It's a fake shadow, kind of a compromise for now. I couldn't get the native elevation to work for now, but I am working on this.
