### ISSUE TITLE
Suggest strip always lower case

### ISSUE THREAD

**Issue by Theo-user** [florisboard/florisboard#925]
Version 0.3.12

![Screenshot_20210522-221233_Firefox Beta](https://user-images.githubusercontent.com/75871295/119240902-e8a47c80-bb4a-11eb-8ad5-a95d6dda6af4.jpg)

Auto caps is on too.

**Comment by patrickgold** [comment]
This has already been reported multiple times (first time #441) and is known to me. When the new suggestions stuff is included this will definitely be addressed and the caps state will be respected.
