### ISSUE TITLE
Create and share Custom themes

### ISSUE THREAD

**Issue by yashx** [florisboard/florisboard#93]
As [json files](https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/theme/floris_day.json) are already used to load default themes, I think it should be possible to let people export and load them for custom themes.

It will allow people to create and share custom themes, and can result in creating a community-based theme store.

**Comment by D3SOX** [comment]
I'm not entirely sure if this fits in here but I would propose a general settings export and import. (Maybe of each tab at the bottom)
I sometimes switch between the releases and a compiled version from master and I always have set it up in the same way.
I think this would come in handy.

**Comment by angriness-sleek** [comment]
> Maybe of each tab at the bottom

4 different backups for one app sounds weird, however an only theme backup and a theme + app settings backup makes sense to me

**Comment by RickyM7** [comment]
Theme Import/Export is on the v0.5.0 roadmap in README.md And I think that's basically it.

**Comment by yashx** [comment]
I somehow missed it. But to be clear, I was thinking more like eventually having a dedicated screen (which pulls data from a Github repo) from where themes can be downloaded.  
So a little bit extra than Theme Import/Export

**Comment by D3SOX** [comment]
> 4 different backups for one app sounds weird, however an only theme backup and a theme + app settings backup makes sense to me

I don't mean 4 backups. Just an option what to include/exclude in the import/export (some checkboxes)

**Comment by patrickgold** [comment]
Thanks for the suggestion! As @RickyM7 already said, theme import/export (from the local file system) is in the feature roadmap, but currently not assigned to any milestone yet.

> I somehow missed it. But to be clear, I was thinking more like eventually having a dedicated screen (which pulls data from a Github repo) from where themes can be downloaded.

That would be a nice way of implementing it but has the same problem as the GIF functionality proposal: To pull data from GitHub in runtime, FlorisBoard needs the NETWORK permission. And as already stated in #53, I personally don't want to use the network permission, as FlorisBoard should be a privacy-focused keyboard and full network access is the exact opposite of it.

Regarding the idea of importing/exporting the preferences, that's definitely doable but requires a bit more work, as SharedPreferences are stored in XML and I need to write every key separately.

**Comment by angriness-sleek** [comment]
i think the same solution as the gif one can be used here, a Theme Store extention-app which has access to internet, and can download and apply themes to FlorisBoard

**Comment by Kreuger** [comment]
hey @patrickgold where are the theme settings stored locally? Could I copy it to a new device for example and use my theme?

**Comment by patrickgold** [comment]
@Kreuger If you have root, yes. They are stored in `/data/data/dev.patrickgold.florisboard/ime/theme/` and could be copied that way. As this issue suggests, I will make an export UI for this so every user, regardless of root or not, can copy themes.

**Comment by Kreuger** [comment]
Appreciate it but my phone went for a swim yesterday so I may end up getting a new one before you have this done so its great that I can do that.

**Comment by patrickgold** [comment]
> Edit: I didnt have the IME folder in the florisboard one. Had to go into the files folder first.

Can definitely be the case, I had the path memorized from a few months ago, maybe I missed the files/ directory before the ime/ folder.

**Comment by Kreuger** [comment]
All good. I ended up just making an archive of the whole folder. Figured its easier that way.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/florisboard/florisboard/issues/93#issuecomment-750895533

Has the "share" part of this issue been implemented? I don't see any evident way to export custom themes:

>

**Comment by lm41** [comment]
Implemented in https://github.com/florisboard/florisboard/pull/2473

**Comment by RokeJulianLockhart** [comment]
> https://github.com/florisboard/florisboard/issues/93#issuecomment-2209413025

@lm41, I don't see any explanation for how to export a theme in that PR's thread. Could you elaborate?

**Comment by lm41** [comment]
Settings -> Addons & Extensions -> Theme Extensions -> View Details -> Export

**Comment by RokeJulianLockhart** [comment]
> https://github.com/florisboard/florisboard/issues/93#issuecomment-2209646946

@lm41, that doesn't match what I see at all. I'm using https://github.com/florisboard/florisboard/releases/download/v0.4.0-alpha02/florisboard-0.4.0-alpha02.apk from https://apt.izzysoft.de/fdroid/repo/dev.patrickgold.florisboard.beta_94.apk:

**Comment by lm41** [comment]
If you had looked at the date of the merge commit, you would have found out that it is not yet released and will come with the next beta release.
