### ISSUE TITLE
Swipe gestures not working!

### ISSUE THREAD

**Issue by kurdikeyboard** [florisboard/florisboard#932]
#### Short description
Since version 3.11.beta06 no action gestures works and nothing happening for examlpe change keyboard layout by swiping from right to left or any other swipe actions doesn't work i have got this bug since 3.11.beta06 and till now same thing and not fixed on newer versions of Floris!

#### Steps to reproduce
1. Go to 'App settings'
2. Click on 'Gestures'
3. Scroll down to 'Any gesture actions'

#### Environment information
- FlorisBoard Version: 3.12
- Install Source: GitHub
- Device: OnePlus Nord
- Android: 11, Stock OOS 11

**Comment by kurdikeyboard** [comment]
The bug is still appear and not fixed could you please re-open the issue related to #972

**Comment by patrickgold** [comment]
See #972 for the probable reason for this issue.
