### ISSUE TITLE
Word translation, just like GBoard

### ISSUE THREAD

**Issue by TAGINARl** [florisboard/florisboard#933]
It would be really cool, to have the translation of words like GBoard, it would be too cool, especially for someone who doesn't speak the same language, and who would like to speak in a certain language.

**Comment by pokegamer5547** [comment]
I'm not a dev so i may be wrong but word translation seems not so easy to do. Even if it gets implemented it might not good as gboard since that translates online(if i'm not wrong) and florisboard doesn't require internet.

**Comment by patrickgold** [comment]
Please see above linked issue regarding the addition of a translator, will close this issue as a duplicate.
