### ISSUE TITLE
sometimes emoji below an emoji gets an emoji gets clicked

### ISSUE THREAD

**Issue by pokegamer5547** [florisboard/florisboard#934]
Steps to reproduce 
1: switch to emoji panel
2: tap on "🤔" continously in slight down way and sometimes the emoji right below it"😬" gets clicked.
![Screenshot_2021-05-24-15-01-46-325_org mozilla firefox](https://user-images.githubusercontent.com/65234485/119327794-fff57e00-bca0-11eb-8c94-105d4958c5b5.jpg)

**Comment by anurag-0-dart** [comment]
it's not a bug , it happen  because of ### miss touch

**Comment by anurag-0-dart** [comment]
it's not a bug, it happen because of miss touch

**Comment by pokegamer5547** [comment]
> it's not a bug, it happen because of miss touch

But it's happening even if the emoji below "🤔" emoji isn't visible on screen. It shouldn't happen if its' not visible which is what happening here.

**Comment by kj7rrv** [comment]
🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔😬🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔


I can replicate it, but only when I tap low on 🤔. My guess is that the clickable area of 😬 is partially in the visible area, so it can be tapped.

**Comment by pokegamer5547** [comment]
> 🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔😬🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔
> 
> I can replicate it, but only when I tap low on 🤔. My guess is that the clickable area of 😬 is partially in the visible area, so it can be tapped.

Yes that's what i think so too, i often noticed it clicking 😬 in chats when i was actually clicked on 🤔
