### ISSUE TITLE
Keyboard changes size randomly

### ISSUE THREAD

**Issue by Duvio** [florisboard/florisboard#939]
#### Short description
Usually when you enter a text field, the keyboard automatically appears, but sometimes it appears and its height is somehow smaller than what i set it to be in the settings.
In the attached video you can see this happening. The second time i open the keyboard it works correctly.

https://user-images.githubusercontent.com/29256280/119497020-5d9ece80-bd64-11eb-9649-4b75b1c46c55.mp4

#### Steps to reproduce
1. Tap on a text field
2. Watch the keyboard being not as tall as you expect it to be
This doesnt happen always and i dont know under which circumstances it happens, so it might be difficult to reproduce and you have to encounter the bug by chance

#### Environment information
- FlorisBoard Version: v0.3.12
- Install Source: GitHub
- Device: Samsung Galaxy S10; SM-G973F
- Android: Stock Android 10

**Comment by patrickgold** [comment]
Thanks for your bug report! This smells like the measure logic in the InputView is too slow in updating the height and the end result is this bug. Will add it to my todo list!
