### ISSUE TITLE
Will adding Russian language?

### ISSUE THREAD

**Issue by Dats1K** [florisboard/florisboard#94]
I can help with translate app on russian.
But will can not with adding russian layout.

**Comment by patrickgold** [comment]
That depends if the source for the dictionaries I will use supports the Russian language or not. As I am still in planning phase (will soon start working on word suggestions), I can't say for certain if the dictionary source which I will use has a Russian dictionary too. I will definitely inform you about it though!

**Comment by patrickgold** [comment]
>  But will can not with adding russian layout.

Adding a Russian keyboard layout though is absolutely doable and I will add this on my todo list!

**Comment by williamtheaker** [comment]
I made an attempt at this in PR #137.

**Comment by Glitchy-Tozier** [comment]
This issue can be closed as the Ruusian was implemented, correct?

**Comment by patrickgold** [comment]
Yup! As for the Russian dictionary, it will come at once with all other initially supported languages, so no need for an extra issue.
