### ISSUE TITLE
TextKeyBoardView rendering issues (in terms of performance)

### ISSUE THREAD

**Issue by patrickgold** [florisboard/florisboard#943]
#### Short description
The current implementation of the TextKeyboardView drawing methods works well, but in terms of performance is a real slowdown. This is especially noticeable since I merged in 845739015680cb31c1062cae19231144d43d001f, which causes severe lags (on older devices), because the shadows get redrawn way too often. This issue's goal is to find a way to cache as much as possible for the rendering process to make FlorisBoard more performant on older devices (where this issue is most noticeable).

Note: the v0.3.13-btea02 release will NOT contain key shadow support to minimize the lag in this beta release. v0.3.13-beta03 will introduce a new rendering concept and re-add support for key shadows. (#921)

#### Steps to reproduce
- N/A

#### Environment information
- FlorisBoard Version: 0.3.12-beta02 or newer
- Device: pretty much all, really noticeable though only on older devices.
- Android: Affects all API levels

**Comment by pokegamer5547** [comment]
I noticedthe lag too even tho my phone RAM and processor is really powerful. But @patrickgold ican no longer access clipboard by long pressing enter key, what was intentional? And also after trying multiple times to access clipbaord  my phone started lagging and keyboard stopped responding. And if i go to recent apps screen, any app i launch was getting swiped away.that was really weird but i never seen it happening before. (Not blaming your keyboard 😅i know it wasn't meant to happen)

**Comment by patrickgold** [comment]
> ican no longer access clipboard by long pressing enter key, what was intentional?

Hmm somehow I ruined the enter popup only in the latest beta, this was definitely not intentional. Will try to fix this for the next beta. Currently I am experimenting with a few optimizations (removing the MaterialDrawables and replacing them with the normal ones), which surprisingly greatly reduces the render time. Will push a draft PR soon.

**Comment by pokegamer5547** [comment]
> > ican no longer access clipboard by long pressing enter key, what was intentional?
> 
> Hmm somehow I ruined the enter popup only in the latest beta, this was definitely not intentional. Will try to fix this for the next beta. Currently I am experimenting with a few optimizations (removing the MaterialDrawables and replacing them with the normal ones), which surprisingly greatly reduces the render time. Will push a draft PR soon.

Oh i see,i understand i will give my feedback once i get next update :)

**Comment by X-yl** [comment]
Do you think maybe we should move gesture trail to its own view so it doesn't have to redraw the TextKeyboardView every time it is updated? This issue is pretty noticeable when glide typing, and besides I think it's a bit weird we have to redraw the TextKeyboardView to show the glide trail.

**Comment by patrickgold** [comment]
We don't have to necessarily move it to a new view, as long as we cache the text keyboard view in an bitmap / offscreen canvas. You are right, when gliding a lot of drawings happen, though the exact same issue goes for space bar left/right, delete swipe etc., so I need to find a solution anyways without a new view.

**Comment by X-yl** [comment]
Hmm fair enough.

**Comment by patrickgold** [comment]
Ok I've played around a bit with trying to improve performance. One method could be to save the keyboard output to a bitmap and as long as the buffer bitmap is not invalidated, this bitmap is reused. I  don't like it though that for every state change this bitmap has to be recreated (that eats memory although old bitmaps get eventually gc'ed), and the main problem is still rendering of the key shadows (they eat performance like a lot).

Another solution could be to use [OpenGL](https://developer.android.com/guide/topics/graphics/opengl) for rendering the keyboard, which is a lot of rework and new learning though and I am a bit skeptical if OpenGL is not a bit overkill for the task of rendering a keyboard (but I am still eyeing on it currently)

Moving the output to another view does not really help, as I must still draw the shadows and the native hardware-accelerated elevation just does not want to render itself within the keyboard view.

What is your opinion or do you have any other ideas I could try out? I am a bit stuck rn, but will play around and potentially push some changes tomorrow.

**Comment by patrickgold** [comment]
@X-yl above PR is a major overhaul for the input logic and should help with the frequent lags reported around shadows, etc. If you want you can have a look at it and give feedback on it. Additionally the "keys being eaten"-bug is also fixed, so typing should work as expected again.

Regarding the concern of rendering performance for the glide trail: I've tested it out and it is surprisingly fluent, even though it is just drawn above the keys within the same view:

https://user-images.githubusercontent.com/19412843/120135261-2ac76100-c1d0-11eb-83cc-ec217182fedc.mp4
