### ISSUE TITLE
Favorite emoji and most recent emoji menu

### ISSUE THREAD

**Issue by aboyd52501** [florisboard/florisboard#944]
A recent emoji list (preferably with a variable sized history) would make the emoji keyboard much more usable.

Additionally, a favorite emoji menu would be very helpful for a personal project of ours, which involves heavy use of emoji.

I would love to contribute some code. If anyone has pointers as to how to get accustomed to this codebase I would appreciate it.

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your feature-request! :) 

Two things:
1. If possible, please edit the topic title to only include the **Favorite…"** functionality. The **Most recent…** has already been suggested before, see #268.
2. I don't know much about the codebase, but if you want to talk about this as soon as possible, I suggest @-ing patrickgold.

**Comment by FadeDave77** [comment]
Adding this would be a game changer, since an emoji board is quite hard to use without some sort of "top emojis" section.

**Comment by patrickgold** [comment]
Above pull request re-implements the emoji palette for the preference and keyboard UI rework. With that, I also added the highly requested emoji history/recently used view. The emoji history is the first tab in the emoji view (the clock symbol) and contains all recently used emojis, sorted by new>>old. Recently used emojis can be removed again by long-pressing them.

This change will be included in the next beta release 0.3.14-beta13. Thanks again for your feature proposal!

**Comment by FadeDave77** [comment]
Thank you!
