### ISSUE TITLE
Bug in indic numerals in v0.3.13-beta02

### ISSUE THREAD

**Issue by yashpalgoyal1304** [florisboard/florisboard#945]
just tested the apk of beta02, and found that the indic numerals added in #940 v0.3.13-beta02 are not correct. i am filling this issue just to avoid the duplicates. i am investigating the issue. sorry for inconvenience.

This issues came up as i couldnt build the apk for testing it earlier myself. i am very sorry, i tried (see here: https://github.com/florisboard/florisboard/pull/940#issuecomment-848485096 ) but just couldnt figure out the process for building apk. the condition is without the use of android studio. 
**any help on this would be welcome. please foss community**

again, sorry for inconvenience.

----

#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by patrickgold** [comment]
> just tested the apk of beta02, and found that the indic numerals added in #940 v0.3.13-beta02 are not correct.

What exactly is not correct?

**Comment by yashpalgoyal1304** [comment]
@patrickgold i have fixed it in https://github.com/yashpalgoyal1304/florisboard/commit/96d39816d42178d58f6a966c1455c00a5699266a  but i guess i messed up while creating the commit. the master version of my fork contains some wrong commits too. so.... :(

can u handle this?

**Comment by yashpalgoyal1304** [comment]
hahhhhhh, thanks goddd it worked out. i got sooo worried.

Rectifying steps:
1. Most important one: it bases new branch on upstream's default branch. exactly the thing i was looking for. i tried setting this up previously too (see column 2), but it was still creating new branch based off of my master. So, i retried after deleting local repo, and recloning it. and it worked :)

choosing on fresh cloning (worked) | choosing in existing clone (didnt work)
-- | --
![new try] | ![old try]

[new try]: https://user-images.githubusercontent.com/19423063/119731381-7e664180-be94-11eb-871e-45fc3a698ebd.png
[old try]: https://user-images.githubusercontent.com/19423063/119731934-2c71eb80-be95-11eb-9389-86f5b139d1d6.png

2. it took effect/behaved expectedly on doing on fresh clone
![GitHubDesktop_kuEj58kQwk](https://user-images.githubusercontent.com/19423063/119731715-e6b52300-be94-11eb-98e0-a4523423435a.png)

3. copy paste commit (i'd call it copy paste, cherry-pick is sooo fancy name 😆)

https://user-images.githubusercontent.com/19423063/119732530-ebc6a200-be95-11eb-8b97-592bc689c795.mp4

4. And voilla
![GitHubDesktop_REi7atz1H4](https://user-images.githubusercontent.com/19423063/119732540-f08b5600-be95-11eb-8912-7b2ed1b78029.png)

**Comment by yashpalgoyal1304** [comment]
Any tips  u wanna share on how can i avoid this mistake in future? (i.e.
since i am just guessing, dont know for sure)

**Comment by patrickgold** [comment]
> Any tips  u wanna share on how can i avoid this mistake in future? (i.e.
since i am just guessing, dont know for sure)

After a branch of yours was merged in to FlorisBoard's master branch, never touch that branch again. Sync your fork's master branch with FlorisBoard's and then branch off again. This saves you a lot of work and is the cleanest way to contribute to any code base.
