### ISSUE TITLE
Glide does not consider words in dictionary  

### ISSUE THREAD

**Issue by esrk** [florisboard/florisboard#948]
I have added few words in both system and internal dictionaries under 'All Languages'. The same words are available as suggestions when typing. But while using glide, those words do not get formed. Its also not present in suggestions.

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Android: 11

**Comment by Glitchy-Tozier** [comment]
Sounds like it's a fault with the suggestions instead of the glide-typing 🤔

**Comment by esrk** [comment]
Not sure of that because the suggestions work perfectly fine when typing (one by one keypress). Even words from dictionaries are displayed fine. 
But while gliding, only words from the language pack within florisboard is used. I'm guessing glide is somehow not provided the words from dictionaries.

**Comment by deepu2** [comment]
I noticed this too, I can glide type some words though but not all words. I can't type most of the words in my dictionary through glide typing no matter how I try. 

Is this somehow affected by the frequency of the words added in the dictionary?

**Comment by Glitchy-Tozier** [comment]
Two things:

1. I feel like this bug is a fuplicate of #849. Would you agree?
2. @deepu2 Do you use the number row? Your issues might be connected to #917 in that case.

**Comment by deepu2** [comment]
@Glitchy-Tozier I do have the number row turned on, as with #917 I did restart my phone recently and I still cant glide type my dictionary words.

**Comment by patrickgold** [comment]
Thanks for your bug report! Yes, glide typing currently does not look up words from custom dictionaries, this will be improved in upcoming releases. See #841 for details. Closing this issue as a duplicate.
