### ISSUE TITLE
weird deletion cases

### ISSUE THREAD

**Issue by angriness-sleek** [florisboard/florisboard#95]
Below is an experiment conducted on the uBlock Origin (installed on firefox android) element selector text input field. AnySoftKeyboard deletes only the characters on the left of the cursor, always, as you keep the backspace pressed. FlorisBoard somehow deletes characters on both sides as you repeat the same backspace long press action.
Experiment:
https://gifyu.com/image/CuH8
(sorry, github doesn't allow large gifs)

**Environment information**
- FlorisBoard Version: 3.1.0
- Install Source: F-Droid
- Device: Mi A2
- Android version, ROM: 10, LineageOS

**Comment by patrickgold** [comment]
Thanks for reporting this bug, I really appreciate it!

Seems related to #64 and #86 (although entirely different apps, it is still the same source of issue). I have to fall back to just emulating a hardware backspace key press, which seems to be better supported that the official input connection of the system...

I will mark the key deletion thingie as more important on my todo list so this should be fixed soon!
