### ISSUE TITLE
Emoticon-section is missing

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#950]
1. I was looking for duplicates but didn't find any.
2. This happens regardless of which theme is used.
3. I think a screenshot best illustrates this:
![Screenshot_20210527-122518_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/119811591-93b88b80-bee7-11eb-8d2d-7190e61941c5.jpg)

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by Glitchy-Tozier** [comment]
I know the third section isn't implemented yet but i could swear the middle one existed before.

**Comment by patrickgold** [comment]
> I know the third section isn't implemented yet but i could swear the middle one existed before.

Yup it did :) I haven't been in this tab for ages though, so unsure when I introduced this bug. I think though the main candidate is the layout rework, but I am not 100% sure.

**Comment by Glitchy-Tozier** [comment]
>I think though the main candidate is the layout rework, but I am not 100% sure.

Yup, that's what I thought.

**Comment by patrickgold** [comment]
Found the issue: the emoticon json load code was still pre-layout-rework and was commented out. Fixed this and it is up and running again. Will be released in v0.3.13-beta03.

Off-topic: What would you think of the idea that I start publishing beta releases on Google Play too? (pre-v0.4.0 still requiring the Google Group to get access) This way you could test out new ~bugs~ features faster and be more up-to-date.

**Comment by Glitchy-Tozier** [comment]
> Found the issue: the emoticon json load code was still pre-layout-rework and was commented out. Fixed this and it is up and running again. Will be released in v0.3.13-beta03.

Yay  ^^

> What would you think of the idea that I start publishing beta releases on Google Play too? (pre-v0.4.0 still requiring the Google Group to get access) This way you could test out new bugs features faster and be more up-to-date.

If it isn't too much work for you, that would be great! I'd definitely use those beta-versions!

~  *~Destroying~ Testing apps in real-time. What a dream.*

**Comment by patrickgold** [comment]
> If it isn't too much work for you, that would be great! I'd definitely use those beta-versions!

Kk, I will then begin setting up the beta GPlay channel, note this requires bit of time because Google Play must approve this first (I have to file it as a new app because stable and beta have different package names).

> ~ Destroying Testing apps in real-time. What a dream.

:)

**Comment by patrickgold** [comment]
I just completed the setup of the GPlay beta channel, it is now in review. Should no issues come up it should be available either this weekend or beginning next week under this URL: https://play.google.com/store/apps/details?id=dev.patrickgold.florisboard.beta (you are already part of the stable track alpha group, so no need to set up anything else).

**Comment by Glitchy-Tozier** [comment]
I'll check it out in a few days then, thank you!  :)

**Comment by patrickgold** [comment]
@Glitchy-Tozier Google just notified me that the app entry alongside beta03 was published, so as long as you are enrolled in the alpha testing group the above link should work. Let me know if it does, because I will update the README accordingly then.

**Comment by Glitchy-Tozier** [comment]
@patrickgold 
1. Yep, works!
2. (offtopic) first time I've ever seen something like this  xD
![Screenshot_20210605-064344_Google Play Store.jpg](https://user-images.githubusercontent.com/59611881/120880266-a3ac2b80-c5c9-11eb-857c-cc3ce9cbd28c.jpg)

**Comment by patrickgold** [comment]
> Yep, works!

Thanks for confirming!

>  Feels kind of mean rofl

Well I mean the beta channel is completely new so GPlay is correct, but yeah it looks really weird :)

**Comment by Glitchy-Tozier** [comment]
Btw, what is this? ![Screenshot_20210605-065126_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/120890651-834d9280-c604-11eb-8ad5-5a84f7afb80a.jpg)

**Comment by patrickgold** [comment]
That's the composer for how character input is treated, for most Western languages appender just does what you expect: 1 char inserts 1 char. For some languages like Korean, Viatmenese, etc. this is not the case, and character input may be 2-3 Latin chars -> 1 char in that language.

**Comment by Glitchy-Tozier** [comment]
I suggest doing somethin about that.
1. (At least to me) it was really confusing. Made me think that it was about who added the layout to Florisboard.
2. I assume most people won't ever need to use this option.

I'm not sure what the best course of action is, but things i'd consider are
1. Rename to something like encoding and
2. Somehow add `"default"` to the standart-option to make sure people aren't too scared about what it is.
(Atom's settings made me think of this)
3. Move it to a different place. It being even in front of `"QWERTZ"` makes it seem REALLY IMPORTANT.

Of course those options could be combined to improve this problem even more.

What are your thoughts on this?

Also, should this be moved to a new issue?
