### ISSUE TITLE
Add explantion to settings about hint priorization

### ISSUE THREAD

**Issue by Luensche** [florisboard/florisboard#955]
A few days ago I asked in the matrix chat, why if I long press for example on s (on the german layout) '#' is not the first character in the pop-up. I've learned that I have to change the hint prioritization. I think an explanation in the settings would be helpful for others as well.

**Comment by patrickgold** [comment]
Thanks for your suggestion! This is definitely a good idea, requires a bit of work for a new dialog widget which supports descriptions for each entry. Placing on my todo list!
