### ISSUE TITLE
Space bar swipe gestures to move cursor lag greatly with suggestions enabled

### ISSUE THREAD

**Issue by Iwaslazkis** [florisboard/florisboard#957]
#### Short description
Coming over from [openboard](https://github.com/dslul/openboard), I've grown used to swiping the spacebar left & right to navigate the cursor around quite aggressively. The issue is, though FlorisBoard can do the same, when the experimental suggestions feature is enabled it seems the cursor lags quite a bit if I try moving around too fast; sometimes being 2-3 seconds behind. 

Not sure if this is helpful, I've noticed too that it seems that the underline that shows the word you're currently on seems to "jitter" a lot more than openboard does when swiping the spacebar; and its especially apparent when I do so aggressively. It hasn't crashed however and is very usable if I move slowly, but it is quite inconvenient as is sometimes.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Device: Pixel 5
- Android: 11, Stock

*Thought I'd also add, this is an awesome project! I've never seen a keyboard as customizable, feature-packed, on top of being FOSS. Thank you for your work!*

**Comment by Glitchy-Tozier** [comment]
>The issue is, though FlorisBoard can do the same, when the experimental suggestions feature is enabled it seems the cursor lags quite a bit if I try moving around too fast; sometimes being 2-3 seconds behind.

Sounds like it could be related to #883.

**Comment by patrickgold** [comment]
Although the current debug build does not support suggestions (except from user dictionaries), this source of lag has been eliminated in above linked PR and when suggestions are re-implemented the suggestions are only computed once you release your input pointer.
