### ISSUE TITLE
Width of the keyboard

### ISSUE THREAD

**Issue by mad1mystic** [florisboard/florisboard#96]
First of all the keyboard is good and improving lot thank you. It would be nice to have option to set and change the width of the keyboard just like option of changing the height of keyboard. The default width for one handed mode it still too wide for big phones and small hands. Thank you hope yoy consider.

**Comment by patrickgold** [comment]
Great to hear that you like FlorisBoard thus far!

> It would be nice to have option to set and change the width of the keyboard just like option of changing the height of keyboard. The default width for one handed mode it still too wide for big phones and small hands. 

Good idea, I didn't even think about this when implementing one-handed mode. Will add it to my todo list, probably for the v0.4.0 milestone!

**Comment by puppykickr** [comment]
I love this idea myself.

Perhaps a way of implementing it would be to be able to customize the shape of the keys.

Myself, I would enjoy being able to increase the gaps between keys.

Being able to customize the size/shape of the keys/spaces would allow for a greater personal customization of the keyboard for each user.

**Comment by patrickgold** [comment]
Above PR adds an option for setting the width of the keyboard in one-handed mode, as a value between 70 and 90%. Will be released in the next few days with v0.3.9!
