### ISSUE TITLE
Clipboard button (and others) missing on enabling suggestions.

### ISSUE THREAD

**Issue by Shaurya-7** [florisboard/florisboard#960]
If I **enable word suggestions**, then the smart bar **doesn't show any clipboard button**. 
In fact it is absent even when I haven't typed anything, the suggestions row tends to be blank.

Please see the screenshots attached: 

1. Normal state when I haven't typed anything: https://i.imgur.com/jUYywIn.png
2. When I click on the arrow button on the left to display options (clipboard is still missing): https://i.imgur.com/TVhtxhD.png

The clipboard is really important and should co-exist with word suggestions.

**Comment by pokegamer5547** [comment]
Clipboard is accessible by pressing shift + space bar left or right , you will see an icon of clipboard.
![390f5334-afd5-43c4-9ada-86bc76d2c518](https://user-images.githubusercontent.com/65234485/120089717-73bcde00-c11a-11eb-9d4d-becd89da1d52.jpg)

**Comment by Shaurya-7** [comment]
I'm using v3.12 (which I think is the latest stable release)

**Comment by pokegamer5547** [comment]
> I'm using v3.12 (which I think is the latest stable release)

Oh yeah that build is stable.  This must be a bug then

**Comment by patrickgold** [comment]
> If I enable word suggestions, then the smart bar doesn't show any clipboard button.

That issue is kind of known and currently unavoidable. When the Smartbar gets a second expandable row you can have a clipboard row and suggestions at one, before that it won't be possible (so either suggestions or clipboard row). Not though that when selecting text the clipboard row is always shows, this is kind of a compromise currently.

**Comment by patrickgold** [comment]
Will be fixed in 0.3.14-beta07 tomorrow.
