### ISSUE TITLE
Backspace does not work in search box of tldr app.

### ISSUE THREAD

**Issue by CryptGoat** [florisboard/florisboard#968]
#### Short description
Backspace does not delete characters in the search box of tldr app. Using backspace with other keyboard apps (such as the stock one) work fine.

#### Steps to reproduce
1. Get the tldr app and install it: https://f-droid.org/en/packages/wtf.technodisaster.tldr/
2. Start the app and click on 'Search'.
3. Enter some text in the search box.
4. Press backspace to delete a character.

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Device: Google Pixel 4a (sunfish)
- Android: Android 11, CalyxOS 2.5.0

**Comment by patrickgold** [comment]
Thanks for your bug report!

The mentioned app is built with Flutter and in there is a bug that input fields don't accept physical backspace keys (and FlorisBoard emulates such a physical backspace key). See https://github.com/flutter/flutter/issues/78769. Once that is resolved, merged, released and then used by tldr app then it will work again.

**Comment by drakex90** [comment]
Having the exact same issue with a C++ app too
**Steps to reproduce**

1. Get the opentodolist from here https://apt.izzysoft.de/fdroid/index/apk/net.rpdev.opentodolist
2. Start the app and click on new library >> local library
3. Enter some text in the name
4. Press backspace

**Environment information**

- FlorisBoard Version: 0.3.13-beta03
- Install Source: F-Droid
- Device: OnePlus 7 Pro
- Android: LineageOS 17.1

**Comment by tsiflimagas** [comment]
I'm not quite sure, but was this resolved by #1844?

**Comment by tsiflimagas** [comment]
Well, tried both apps myself, it works fine.
