### ISSUE TITLE
Numpad reopens instead of normal keyboard mode

### ISSUE THREAD

**Issue by Flash1232** [florisboard/florisboard#969]
#### Short description
After using the numpad for entering a PIN inside an app, when subsequently starting the keyboard in the Firefox search bar, the numpad view again opened up instead of the normal QWERTZ keyboard.

The phenonenon was only observed once. Could not reliably reproduce afterwards.

#### Steps to reproduce
1. Use FlorisBoard to enter a PIN (for unlocking a U2F device) inside FairMail.
2. Switch to another app, e.g. Firefox.
3. Click the (empty?) search bar so that the keyboard opens up.
4. Observe the numpad.

#### Environment information
- FlorisBoard Version: v0.3.12
- Install Source: Google Play Store
- Device: OnePlus 5T
- Android: 10, Oxygen OS

**Comment by patrickgold** [comment]
Thanks for your bug report!

I can imagine that this can happen rarely, though currently in the latest debug build I am unable to reproduce this behavior. Will let this issue open for now and see if this is indeed a bug that can be reproduced and eliminated.

**Comment by patrickgold** [comment]
Does #981 fix this issue consistently for you?

**Comment by Flash1232** [comment]
Thanks for your quick action!

I'll keep an eye out and let you know when it happens again. Btw I think this is the best keyboard around atm. :+1:

**Comment by Flash1232** [comment]
Thanks for your quick action.

Gonna try as soon as I find some time. Appreciate it!

**Comment by burny0202** [comment]
I have the same and opposite problem as well. It doesn't seem to know whether it should be numpad or text. Occasionally the wrong opens.

Getting rid of keyboard and clicking back in always sorts it.

I'm on f-droid so haven't checked the fix.

Love your keyboard & work...Many thanks indeed
