### ISSUE TITLE
Swipe gestures not work!

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#972]
In the previous versions swipe gestures doesn't work and nothing happened when swiping from left or right actions, A few minutes ago i saw the new 3.13 beta03 version and installed but still not fixed and gestures not works like before.

Here is the short video:

👇
https://ufile.io/67hqfb8a

Idk why i can't attach video on github 🤔

Device: OnePlus Nord

System: Stock Android 11

Florisboard 3.13 beta03

**Comment by Glitchy-Tozier** [comment]
> Idk why i can't attach video on github 🤔

On the app, if just doesn't work.  :/
On PC or in your mobile browser you should be able to do it, given that the file has the correct file type.

**Comment by patrickgold** [comment]
It's working flawlessly for me. I suspect that different display densities play a key role in this issue. Could you try playing around both with the swipe velocity and distance threshold and see if it works with any of those configurations? If it works, it may indeed be a density issue and have to make the speed constants somewhat dynamic.

**Comment by patrickgold** [comment]
> On the app, if just doesn't work. :/

I think GitHub lately just released a version where video playback support was added, so it is a step forward. I agree though that video upload support should be a thing in the app.

**Comment by kurdikeyboard** [comment]
> It's working flawlessly for me. I suspect that different display densities play a key role in this issue. Could you try playing around both with the swipe velocity and distance threshold and see if it works with any of those configurations? If it works, it may indeed be a density issue and have to make the speed constants somewhat dynamic.

I tried with your step changed the distance and velocity threshold but not works same bug is there on Stable version 3.12 but i Tested the old 3.10 Stable there is no problem and works like charm :)

**Comment by kurdikeyboard** [comment]
Here is the short video this time is attached 😅

https://user-images.githubusercontent.com/3160786/120233596-e20ab900-c25e-11eb-8392-4cc2f4a23cd9.mp4

**Comment by patrickgold** [comment]
That's just strange. This also occurs with a clean install of the latest beta? (make sure to wide FlorisBoard's cache and data, then uninstall and install again)

**Comment by GoRaN909** [comment]
> That's just strange. This also occurs with a clean install of the latest beta? (make sure to wipe FlorisBoard's cache and data, then uninstall and install again)

Yeah belive me i can swear that i DID everything cache clears uninstall then re install from scrath but the gesturs does NOT work on my device also i tested on my mom ZTE Axon 7 with Stock Android Oreo 8.0 same bug is there the languages or any actions does not changes by swipe left/right that's so strange :/

**Comment by CaptainJKoB** [comment]
Experiencing same issue. Fiddled around with swipe velocity and distance.
Options `Very slow` and `Very long` together work consistently and perform the given gesture on my device.
Any other combination has a worse success rate of performing the gesture.
Combinations used in conjunction with `Short`, `Very short`, `Fast` or `Very fast` will never perform the gesture. 
Tested on clean installs from v0.3.11-beta01 to v0.3.13-beta03.
This behaviour started to appear in v0.3.11-beta03.

Device: Pixel 1
OS: Android 10
First occurrence: v0.3.11-beta03
Tested on: v0.3.11-beta0[1-6], v0.3.12, v0.3.13-beta03

**Comment by patrickgold** [comment]
Thanks for investigating into this issue! That further indicates that the display density probably plays a key role for the gesture detection. Why exactly beta03 introduced this problem is questionable though, but I will see what I can do.

**Comment by KLaurence** [comment]
I think 0.3.13-beta03 didn't introduce the problem; the problem is also present in 0.3.12.

**Comment by patrickgold** [comment]
> I think 0.3.13-beta03 didn't introduce the problem. The problem is also present in 0.3.12.

I just realized I over-read the version name, it is v0.3.11-beta03, not v0.3.13-beta03.  :facepalm: 

Checking the changes for v0.3.11-beta03, I introduced the velocity threshold for gestures. This is most likely the reason why it does not work, as it seems I read these values in raw pixels, instead of density-independent pixels.

**Comment by KLaurence** [comment]
I think 0.3.11-beta03 did introduce the problem because 0.3.11-beta02 doesn't have it.

**Comment by GoRaN909** [comment]
> I think 0.3.11-beta03 did introduce the problem because 0.3.11-beta02 doesn't have it.

Yeah after he added the velocity threshold that bug is appear and swipe to left/right doesn't works anymore :(

**Comment by patrickgold** [comment]
@GoRaN909 Above linked PR is an attempt by me to fix the gesture bugs. If possible, could you install the debug APK and check if the gestures work correctly for you again (especially swipe left/right/up/down when gliding is turned off)? Thanks in advance!

**Comment by GoRaN909** [comment]
check if the gestures work correctly for you again (especially swipe left/right/up/down

I checked the debug version and hopefully gestures action is works smoothly left/right/down but the up gesture is not good you need to swipe up more than two or three times then the up gestures action is works

Other left/right and down are very good and do action fast instead UP gesture.

* Note: i was changed swipe up action to open clipboard manager/history


Thank you very much for your hard work @patrickgold  💙

**Comment by patrickgold** [comment]
Thanks for testing this out! The UP gesture has the issue that it is cancelled if your finger hits the Smartbar, I have to find a way around this and the UP gesture should work as smooth as the others. But this i(#1018)s at least some sort of progress, will see how I can fix the UP gesture.

**Comment by GoRaN909** [comment]
> Thanks for testing this out! The UP gesture has the issue that it is cancelled if your finger hits the Smartbar, I have to find a way around this and the UP gesture should work as smooth as the others. But this is at least some sort of progress, will see how I can fix the UP gesture.

You very welcome bro it's my pleasure for me the UP gesture is not most important i just use left right and down that three one works very good thanks again and take your time to fix that small up bug i just wanted to tell you about that bug 😊

Also I'm waiting to 5 or 6 Row layouts will be fix as soon as possible when you have a free time please take a look at that bug that so important. 

Best regards.
