### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Khatri7yash** [florisboard/florisboard#979]
#### Short description
This is one of the best keyboard i've found on the git but also got some bugs and that is because it is under developing mode and the issue(Bug) i'm facing is that after clearing keyboard application from recent it takes around 5-10 seconds to load after focusing on edittext. I searched for the solution related to this issue but i'was unable to find one 

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: GitHub
- Device: Samsung M30 and Samsung S7 edge 
- Android: Android 11(M30) and Android 8(S7 edge) 

#### Video related to this issue(bug)

https://user-images.githubusercontent.com/85149265/120272504-d94fcc80-c2ca-11eb-95c9-aa687ca3a56b.mp4

**Comment by Glitchy-Tozier** [comment]
Hi!
This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, and the update should already be available in the app-stores. (v0.3.12)

**Comment by Khatri7yash** [comment]
> Hi!
> This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, and the update should already be available in the app-stores. (v0.3.12)

Thanks for helping me out...
