### ISSUE TITLE
Keyboard inputting 2 capital letters

### ISSUE THREAD

**Issue by StefanTraistaru** [florisboard/florisboard#984]
#### Short description
In a field where the first letter is a capital one, if you type fast enough the second letter will also be capital. This can also happen if you press the shift key once.

This may be related to the issue/fix of this: #953 

#### Steps to reproduce
1. Go to: I managed to reproduce this bug in all text fields I could find.
2. Click on: 2 sepperate keys really fast, one after the other when the shift key is enabled.
3. See error: both letters will be capital letters

#### Environment information
- FlorisBoard Version: v.0.3.13-beta03
- Install Source: F-Droid
- Device: OnePlus 7T
- Android: 11, Stock

https://user-images.githubusercontent.com/23136219/120492566-dafcbb80-c3c2-11eb-81aa-9b1c13cf669b.mp4

**Comment by zer0fl0w** [comment]
+1

**Comment by ggdorman** [comment]
Can confirm.

**Comment by StefanTraistaru** [comment]
I tried the same with FlorisBoard Version: v.0.3.13-beta04 and the problem seems to have disappeared. I will close this issue for now.
