### ISSUE TITLE
Smartbar gone when changing keyboard

### ISSUE THREAD

**Issue by yant0** [florisboard/florisboard#987]
#### Short description
Its gone

#### Steps to reproduce
1. Open any text field
2. Switch with any method to beta
3. See error

#### Environment information
- FlorisBoard Version: 0.3.13 beta 3
- Install Source: Fdroid
- Device: Asus Zenfone Max Pro M1
- Android: 9 stock

**Comment by yant0** [comment]
![Screenshot_20210603-003044](https://user-images.githubusercontent.com/80298071/120528280-99422580-c36e-11eb-8524-37397192d732.png)

![Screenshot_20210603-003058](https://user-images.githubusercontent.com/80298071/120528245-8deefa00-c36e-11eb-841e-ac84f66badc2.png)

**Comment by patrickgold** [comment]
Thanks for your bug report! I tried this one out and there's a flaw in the event initialization, meaning the Smartbar may or may not appear. Will add this to the keyboard state branch I am currently working on.
