### ISSUE TITLE
Copy greyed out

### ISSUE THREAD

**Issue by yant0** [florisboard/florisboard#988]
#### Short description
Copy button in Smartbar always greyed out. Using shift + space or manually selecting.

#### Steps to reproduce
1. Select text
2. See error

#### Environment information
- FlorisBoard Version: 0.3.13 beta 3
- Install Source: Fdroid
- Device: Asus Zenfone Max Pro M1
- Android: 9 stock

**Comment by yant0** [comment]
After typing this with beta and retry to copy, i opened my browser address bar and the copy shows. But when i copy it doesnt paste..

**Comment by zer0fl0w** [comment]
happens for me too on op8t with stock oxygenos based on android 11.
