### ISSUE TITLE
Language name font is very big and wide on tablet

### ISSUE THREAD

**Issue by ZorinArch** [florisboard/florisboard#990]
Hi,

Language name font is very big and wide on tablet. this is how it look like:
![floris](https://user-images.githubusercontent.com/62427713/120633684-b5c38800-c46a-11eb-9090-871f1d29e9df.png)

also, when i want to type a new line the first letter didn't turn to uppercase. i'm enable it from setting and doesn't work.

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: F-Droid
- Device: lenovo A5500
- Android: 7

Thanks,

**Comment by patrickgold** [comment]
Probably solved on the latest beta v0.3.13-beta03. Could you try it out and see if this problem still persists for you? Thanks in advance!

**Comment by ZorinArch** [comment]
I tried latest beta v0.3.13-beta03 and problems solved. but, Display suggestion not working in this version. i hope all of the developers team of this project all good times.
Thanks,

**Comment by patrickgold** [comment]
Suggestions are not working in the latest beta I know, but at least the label bug is resolved :)
