### ISSUE TITLE
punctuation popup on long press of full stop (period)

### ISSUE THREAD

**Issue by nicktyke** [florisboard/florisboard#995]
Hi.
When you long press the full stop a pop up board of punctuation characters appears but when you slide your fingertip up to select one, it chooses the character from the row above.

Environment V0.3.12 F-droid build
UK English QWERTY layout (reproducible US layout)
Umidigi F2 Android 10

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for taking the time to fill out this issue!

Could this be a cuplicate of #949?

**Comment by nicktyke** [comment]
looks that way. Sorry.
Seems it's intended behaviour!

**Comment by Glitchy-Tozier** [comment]
Thank you for checking it out and closing the issue  :)
