### ISSUE TITLE
Improve Settings: Welcome Screens

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#996]
I think the welcome-screens should be improved. Here's a few thoughts, formulated in a very curt way:

___
- I don't see any need to add a link to a page that just tells you **again**, that you won't get tracked.
- In general, use way way less text. Maybe also make the important parts bold.
![Screenshot_20210605-064813_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/120888096-d28cc680-c5f6-11eb-8743-612111fca201.jpg)

___
Shouldn't be required. Please don't disable "weiter" (or whatever the english word is)
![Screenshot_20210605-064840_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/120888383-54312400-c5f8-11eb-90e5-3cfb806d558f.jpg)

___
Seems like a very unneccessary screen to me.
If you want the user to be notified about "you're done", use a temporary popup. 
![Screenshot_20210605-064855_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/120888441-9f4b3700-c5f8-11eb-9337-85a9b76ce633.jpg)

**Comment by patrickgold** [comment]
Thanks for your suggestions for improving the welcome screen! The whole setup screen is not the greatest, I know. The initial introduction screen has waay to much text, which probably only half of the people are gonna read through anyways, so better off shortening it. The final "finish" screen was intended to get some extra setup options, but never got some.

Thus I just thought about the setup screen and developed a quick mock-up for a new screen in draw.io:

![image](https://user-images.githubusercontent.com/19412843/120890506-63699f00-c603-11eb-8f98-3e638e253916.png)

The setup activity is now only one page, without any prev/next buttons, so just this screen. depending on the stage, you can either be in step 1 (left), step 2 (middle) or step 3 (right). When opening up the setup screen, you are automatically in step 1. After enabling FlorisBoard, the screen will automatically switch to step 2, if you select FlorisBoard as the default (or press skip), it will switch to step 3. There, I basically included the most important info from the old welcome screen.

What do you think of this concept? On a backend level, it reduces the amount of coding required (no separate fragments for each page, etc.) and this screen looks also less cluttered.

Note for the mock-up: the orange and green colors are a bit random (just what draw.io had as the default ones), I of course use the already established ones for FlorisBoard in-app.

> Shouldn't be required. Please don't disable "weiter" (or whatever the english word is)

Well it is required because most other keyboards also require it. In the mock-up I've included a skip button for that step but still I am a bit skeptical if some people will skip that step and then complain that their old keyboard shows.

**Comment by Glitchy-Tozier** [comment]
It looks really good! Maybe you could add some fancy collapse-effects to the sections when they change :) 
(what i mean is something like the sections on this website: https://www.osocalc.org/)

Other than that... I like it. Can't find anything to complain about. :(

**Comment by Glitchy-Tozier** [comment]
Actually, one thing.  :)

"Ty for trying out FlorisBoard" seems a little... insecure, as if many people might uninstall it after they have "tried it out". It's just a line you probably wouldn't use in gBoard, if you know what I mean.

**Comment by Glitchy-Tozier** [comment]
And regarding the activate-keyboard-thing: You're right, pretty much nobody wants to skip that screen. You can make it mandatory.

The only reason why i mentioned this is because i used to check out what progress ASK had made, without wanting to type on it. And they didn't let me progress into the app (even after having completed the welcome-screens) without enabling the keyboard. It was very annoying.

However, you're doing a great job with FlorisBoard so i'm using it instead of trying it out sparringly. (catch my genius reference? 🙃)

**Comment by patrickgold** [comment]
> It looks really good! Maybe you could add some fancy collapse-effects to the sections when they change :)

Yes I thought about that too, hopefully it isn't too difficult to add it on a technical level (I hate Android animations soo much haha).

> "Ty for trying out FlorisBoard" seems a little... insecure, as if many people might uninstall it after they have "tried it out". It's just a line you probably wouldn't use in gBoard, if you know what I mean.

Then the header should look like this?

```
Welcome to FlorisBoard!

This quick setup guides you through the required steps to use FlorisBoard on your device.
```

You are right, the big players like SwiftKey and GBoard just straight away go to the setup, so yeah I see where you are coming from.

> And regarding the activate-keyboard-thing: You're right, pretty much nobody wants to skip that screen. You can make it mandatory.

This step is only mandatory in the initial setup guide, once it is finished I never force the user to switch to FlorisBoard whenever he checks out the Settings activity. I only show the red/yellow warning box on the home tab if FlorisBoard is not enabled/selected, but that's passive and non-aggressive (ryhme unintended lol).

> However, you're doing a great job with FlorisBoard so i'm using it instead of trying it out sparringly. (catch my genius reference?)

:smile:

**Comment by Glitchy-Tozier** [comment]
> (I hate Android animations soo much haha).

Because of the flashing keyboard-thing or in general?

>Then the header should look like this?

That, or you could replace "trying" with "using".

>You are right, the big players like SwiftKey and GBoard just straight away go to the setup, so yeah I see where you are coming from.

How do they make you activate the keyboard?

>I only show the red/yellow warning box

Yeah, that one seems perfectly reasonable to me.

**Comment by patrickgold** [comment]
> Because of the flashing keyboard-thing or in general?

Both (although I've learned quite a bit from that issue and for single-property animations it is pretty easy now).

> That, or you could replace "trying" with "using".

Is also a valid option, yeah.

> How do they make you activate the keyboard?

Similar to above proposal, but basically just the buttons from step 1-3 without much text + their data collection agreement pages etc.

**Comment by Glitchy-Tozier** [comment]
> Similar to above proposal, but basically just the buttons from step 1-3 without much text + their data collection agreement pages etc.

I see, I thought you meant they had a design that didn't require welcome-pages.

**Comment by KLaurence** [comment]
In my unqualified opinion, I like the mockup.

I think some parts of the text could be made shorter. For example, we could probably replace "language & input settings" with "settings".

I think we can also split the text into small lines. It makes the text look less dense and it can be used to emphasize important lines.

**Comment by Glitchy-Tozier** [comment]
On the bottom right, we could put the link to GitHub instead to the issues-page.

Lets hope that the app works well enough that users don't flock to the issue-tracker upon seeing the welcome-screen 🙃

**Comment by patrickgold** [comment]
This is also a viable alternative, as it allows to view the GH repo and you still have access to the issues if you want to.

**Comment by Halfmit** [comment]
![Screenshot_2021-08-18-17-21-18-582_dev patrickgold florisboard](https://user-images.githubusercontent.com/89081209/129893497-c19e1d10-9cac-4af3-aba1-e2ed03bc49e0.jpg)
Display suggestions wh.....
What after that? It should show full heading

**Comment by patrickgold** [comment]
> Display suggestions wh.....
What after that? It should show full heading

Suggestions are buggy as hell and not existent in the latest beta. A better implementation will come in 0.3.15. Marking your comment as off-topic, as this issue is about the setup screen and not suggestions.

**Comment by moriel5** [comment]
This post is only relevant for the current first use welcome screens:

Being able to swipe through the first use welcome screens (after completing the required actions, of course) would certainly make things more convenient.

Also, a "Finish" button in the middle of the screen at the last step would make it slightly easier to press the button.

**Comment by patrickgold** [comment]
I've been working on a new setup screen and this is the first actual implementation:

https://user-images.githubusercontent.com/19412843/134213550-2e69afaf-9ba4-4dbc-92d8-1d86c102b754.mp4

Some minimal things have changed from the mockup, notably there's no orange (it just does not look right) and I've adjusted the text a bit. Also there's no dotted line on the left side, because I think it is already clear what step the current is. For now I will add the setup screen as seen above, but if there are fixes / design changes to be done I will add them later on.

**Comment by Glitchy-Tozier** [comment]
Nice!  :)

Two small improvement ideas:

![Screenshot_20210921-215729_GitHub.jpg](https://user-images.githubusercontent.com/59611881/134239262-787ec944-44cb-4ef4-a93d-99d8ef02b85b.jpg)
Something about that second sentence seems wrong.


![Screenshot_20210921-215851_GitHub.jpg](https://user-images.githubusercontent.com/59611881/134239340-5c9fa7ab-62d0-4a23-b5f3-ad7076590784.jpg)
This might be completely wrong but isn't it "**on** your systen? 🤔

**Comment by GoRaN909** [comment]
> I've been working on a new setup screen and this is the first actual implementation:
> 
>  new-setup-screen.mp4 
> Some minimal things have changed from the mockup, notably there's no orange (it just does not look right) and I've adjusted the text a bit. Also there's no dotted line on the left side, because I think it is already clear what step the current is. For now I will add the setup screen as seen above, but if there are fixes / design changes to be done I will add them later on.

Wow that's very nice i like it so much the new setup screen but idk why is not works for me i downloaded the debug apk from artifacts and installed but nothing show up like yours in short video also the old one is not works and i can't Enable it inside the app it self :/

**Comment by patrickgold** [comment]
>  Something about that second sentence seems wrong. The then-part should be canged.

Reading it again now you are right, this sentence contains parts of two long sentences concatenated and truncated to be a lot shorter.

Suggestion: `Open the Language & Input preferences with below button, then enable FlorisBoard in the list.`

>  This might be completely wrong but isn't it "on your system"? thinking

Now you are really asking a question where I am never sure what is correct. I think both is correct, but there seems to be a little difference in the meaning. Not sure though.

> Wow that's very nice i like it so much the new setup screen but idk why is not works for me i downloaded the debug apk from artifacts and installed but nothing show up like yours in short video also the old one is not works and i can't Enable it inside the app it self :/

If you go to advanced settings and then scroll to the bottom is there a "Reset isImeSetUp flag" preference?

**Comment by patrickgold** [comment]
I just checked and it seems that there's indeed a bug in the initial screen selection, causing the setup screen to be ignored. I will fix this and the other setup screen issues tomorrow.

**Comment by Glitchy-Tozier** [comment]
> Suggestion: Open the Language & Input preferences with below button, then enable FlorisBoard in the list.

This sounds better, but "with below button" still bothers me.

What do you think about: `Click on the button to open the Language & Input preferences. There, enable FlorisBoard.`

In this suggestion I also left out some details that seemed very obvious to me.

**Comment by GoRaN909** [comment]
@patrickgold @Glitchy-Tozier  What you think about photo instead a text for first time setup for new users explain to Enable & Switch FlorisBoard to more understand and simplest

This one for Enabling:

[![ic-enable.png](https://i.postimg.cc/dQzT7dRb/ic-enable.png)](https://postimg.cc/6TfQg8mc)

And the second one for Switching to FlorisBoard:

[![ic-switch.png](https://i.postimg.cc/rFxR5mQK/ic-switch.png)](https://postimg.cc/F7FK49t4)

**Comment by Glitchy-Tozier** [comment]
@GoRaN909 It sounds like a fun idea, especially if smart screenshots are chosen.

That being said, the problem I see is that people with tons of different Android versions use FlorisBoard. Different device manufacturers may create their own settings-style. This may make the screenshots suboptimal, as they may only show the correct settings in ~5% of the cases.
Do you know what I mean?

**Comment by tsiflimagas** [comment]
Setup screen now  shows up, and I think it looks simple, clean and nice! One thing I wanted to report since a long time is that in both old and new ui, when you open the settings, setup screen flashes for a moment, which looks glitchy (no pun intended 😅). One suggestion I have on this is to add a splash screen, but I'm not sure everyone would agree with it.

**Comment by Glitchy-Tozier** [comment]
Ooooh! Should you ever want to add a splash-screen, @ me! I have some fun ideas 🤩

**Comment by GoRaN909** [comment]
> @GoRaN909 It sounds like a fun idea, especially if smart screenshots are chosen.
> 
> That being said, the problem I see is that people with tons of different Android versions use FlorisBoard. Different device manufacturers may create their own settings-style. This may make the screenshots suboptimal, as they may only show the correct settings in ~5% of the cases.
> Do you know what I mean?

Oh i see you right maybe the small screens doesn't show fully image of the screenshot okay so let's just ignore it 🥲

**Comment by GoRaN909** [comment]
> @GoRaN909 I've pushed a fix commit, could you please try out the debug APK if the setup screen shows this time?
> 
> > What you think about photo instead a text for first time setup for new users explain to Enable & Switch FlorisBoard to more understand and simplest
> 
> Screenshot is simple for the user but incredibly hard to get right for the developer. Glitchy made a few very good points against this already. Android 12 makes matters even worse, because with Material You the system Settings can have user defined colors, where the screenshot looks even more out-of-place. Also, on smaller device screens I do not really have space for a screenshot and the APK size unnecessarily rises by a few 100 kB. SO generally I am not really a fan of the screenshot idea, sorry.
> 
> > EDIT: You max even be able to get rid of the "click the button"-part, because the button is clearly visible and has a good label-text.
> 
> @ Glitchy-Tozier: I've now taken your suggested sentence with a minimal modification, because it is simpler and clearer than my original sentence. Thanks for the correction!

Yes this time is shows the new seup screen but just for the first time if user switch to another keyboard app you can't re-enable or switch to it again! 

Okay bro i just suggested you are a developer you know more than me anyways I like the new setup screen your works is great like all before you did long live FlorisBoard Im in love with this keyboard 😁😅

**Comment by patrickgold** [comment]
> One thing I wanted to report since a long time is that in both old and new ui, when you open the settings, setup screen flashes for a moment, which looks glitchy (no pun intended sweat_smile)

I agree, this is indeed an issue.

> One suggestion I have on this is to add a splash screen, but I'm not sure everyone would agree with it.

I am already planning to add a splash screen for the new UI (because there's literally no valid reason which would speak against adding one), but am not really sure what the correct approach (on a technical level) is, thus currently the startup of the settings is not fluent.

For the design I've some ideas, but I've also seen that @Glitchy-Tozier seems to have some, so I am open to suggestions here :)

> Yes this time is shows the new seup screen but just for the first time if user switch to another keyboard app you can't re-enable or switch to it again!

That's true because the yellow/red boxes do not show currently on the home screen. Has nothing to do with the setup screen, but will note that.

**Comment by Glitchy-Tozier** [comment]
> For the design I've some ideas, but I've also seen that @Glitchy-Tozier seems to have some, so I am open to suggestions here :)

My thought was that the splash-screen could be something really simple, mostly a background in FlorisBoard-colors, with the name `FlorisBoard` getting typed onto the screen (preferably in a 𝚖𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎-font)

As an example you could look at the text animation on this website: https://tanzschulestanek.at/tanzkurse/dance-times-perfektion/
(The only difference is that I think 𝙵𝚕𝚘𝚛𝚒𝚜𝙱𝚘𝚊𝚛𝚍 should only get typed once.

Optionally you could also add the florisboard-logo above the text, but that's not mandatory.
