### ISSUE TITLE
Keyboard-preview is buggy

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#997]
#### Short description
The keyboard-preview is distorted. All the buttons seem to be too large. (i didn't change anything about those default themes)
See Screenshots:
![Screenshot_20210605-065355_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/120899917-57e19c80-c632-11eb-9ecc-ae759cf85a3e.jpg)
![Screenshot_20210605-065337_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/120899920-5a43f680-c632-11eb-98a7-b6f7775fe242.jpg)

#### Environment information
- FlorisBoard Version: 0.3.12 Beta3
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! This should be fixed in beta04, probably on Thursday live on Google Play.

**Comment by Glitchy-Tozier** [comment]
Great!  :)
